-- ════════════════════════════════════════════════════════════════════
-- Biology Chapter 5 — The Endocrine System (flashcard deck)
-- ════════════════════════════════════════════════════════════════════
-- Section: biology | Topic: Body Systems | Subtopic: the_endocrine_system | Sort: 5
--
-- 106 cloze cards. REVISED 2026-07-09: split/tightened 36 over-long cards
-- (beta-tester feedback that some cards were too long/wordy) into focused single-
-- fact cards; 33 already-crisp cards kept verbatim. Facts cross-verified against
-- OpenStax Anatomy & Physiology 2e (Ch 17). Idempotent: wipes any prior version.
-- ════════════════════════════════════════════════════════════════════

DO $$
DECLARE
    deck UUID;
BEGIN
    DELETE FROM flashcard_decks
    WHERE section = 'biology'
      AND title IN (
          'The Endocrine System',
          'Endocrine System',
          'Biology Review Chapter 5: The Endocrine System',
          'Biology Review Chapter Five: The Endocrine System'
      );

    INSERT INTO flashcard_decks (section, topic, subtopic, title, description, sort_order)
    VALUES (
        'biology',
        'Body Systems',
        'the_endocrine_system',
        'The Endocrine System',
        'Hormone chemistry and signaling — peptide, steroid, and amine classes, receptor location, second messengers and amplification, speed/duration, and feedback — then the endocrine glands one by one: hypothalamus and pituitary, thyroid and parathyroid, adrenal cortex and medulla, pancreatic islets, gonads, pineal, and minor endocrine organs.',
        5
    )
    RETURNING id INTO deck;

    INSERT INTO flashcards (deck_id, position, card_type, cloze_text, cloze_count) VALUES
    (deck, 0, 'cloze',
     'By chemical structure, hormones fall into three classes: {{c1::peptide/protein}}, {{c2::steroid}}, and {{c3::amine (amino-acid-derived)}} hormones.',
     3),
    (deck, 1, 'cloze',
     'Because {{c1::steroid}} hormones are built from {{c2::cholesterol}}, they are hydrophobic and need {{c3::carrier (transport) proteins}} to travel through the blood.',
     3),
    (deck, 2, 'cloze',
     'A cell making a peptide hormone first synthesizes a preprohormone, which is trimmed to an inactive precursor called a {{c1::prohormone}}.',
     1),
    (deck, 3, 'cloze',
     'The active peptide hormone is freed from its prohormone by enzymatic {{c1::cleavage}}, then released from the cell via {{c2::exocytosis}}.',
     2),
    (deck, 4, 'cloze',
     'Every steroid hormone traces back to a single lipid precursor, {{c1::cholesterol}}, and the tissues that build them are concentrated in two places: the {{c2::adrenal cortex}} and the {{c2::gonads}}.',
     2),
    (deck, 5, 'cloze',
     'Strip the carboxyl off a single {{c1::amino acid}} — usually {{c2::tyrosine}} — and you get an amine hormone; this small class covers the catecholamines {{c3::epinephrine and norepinephrine}} plus the thyroid hormones {{c4::T3 and thyroxine (T4)}}.',
     4),
    (deck, 6, 'cloze',
     'Peptide and most amine hormones are {{c1::hydrophilic}}, so they travel dissolved freely in plasma and bind {{c2::cell-surface (membrane)}} receptors.',
     2),
    (deck, 7, 'cloze',
     'Steroid and thyroid hormones are {{c1::lipophilic}}, so they ride the blood on {{c2::transport (carrier) proteins}} and diffuse across the membrane to {{c3::intracellular}} receptors.',
     3),
    (deck, 8, 'cloze',
     'Because they are lipid-soluble, {{c1::steroid}} hormones slip straight through the plasma membrane and dock at {{c2::intracellular (cytosolic/nuclear)}} receptors, while {{c3::peptide (water-soluble)}} hormones—stopped by the lipid bilayer—must signal through receptors on the {{c4::cell surface}} instead.',
     4),
    (deck, 9, 'cloze',
     'Once a steroid hormone reaches its intracellular receptor, the resulting complex behaves as a {{c1::transcription factor}}: docking onto a specific DNA sequence, it {{c2::up- or down-regulates (increases or decreases)}} transcription of the target gene.',
     2),
    (deck, 10, 'cloze',
     'A peptide hormone can''t cross the plasma membrane, so it binds a surface receptor and acts as the {{c1::first messenger}}.',
     1),
    (deck, 11, 'cloze',
     'In response to a peptide hormone, the cell generates an intracellular {{c1::second messenger}} (such as {{c2::cAMP}}) that relays the signal deeper into the cell.',
     2),
    (deck, 12, 'cloze',
     'For water-soluble hormones, G-protein activation of {{c1::adenylyl cyclase}} converts ATP into the second messenger {{c2::cAMP}}.',
     2),
    (deck, 13, 'cloze',
     'G-protein activation of {{c1::phospholipase C (PLC)}} yields the second messenger {{c2::IP3}}, which triggers {{c3::Ca2+}} release from the smooth endoplasmic reticulum.',
     3),
    (deck, 14, 'cloze',
     'When a peptide hormone binds a G-protein-coupled receptor, the freed G protein activates {{c1::adenylyl cyclase}}, which converts ATP into the second messenger {{c2::cAMP}}.',
     2),
    (deck, 15, 'cloze',
     'Rising cAMP activates {{c1::protein kinase A (PKA)}}, which then {{c2::phosphorylates}} downstream target proteins to launch the cellular response.',
     2),
    (deck, 16, 'cloze',
     'Because each tier of a {{c1::phosphorylation cascade}} activates many copies of the next enzyme, a tiny hormone signal is magnified into thousands of intracellular events — signal {{c2::amplification}}.',
     2),
    (deck, 17, 'cloze',
     'Because its second-messenger cascade fires within seconds, a peptide hormone''s effect is {{c1::rapid}} in onset but {{c2::brief}} in duration.',
     2),
    (deck, 18, 'cloze',
     'A peptide hormone''s response ceases once {{c1::phosphodiesterase (PDE)}} degrades the {{c2::cAMP}} second messenger, unless fresh hormone keeps binding the surface receptor.',
     2),
    (deck, 19, 'cloze',
     'A steroid hormone crosses the membrane and binds an {{c1::intracellular receptor}}; the complex docks on DNA to drive {{c2::transcription}}.',
     2),
    (deck, 20, 'cloze',
     'Because steroid hormones act by altering {{c1::mRNA and protein}} synthesis, their effects are {{c2::slow to appear}} yet {{c3::long-lasting}}.',
     3),
    (deck, 21, 'cloze',
     'Because they are {{c1::lipid-soluble}}, steroid hormones travel in plasma bound to {{c2::transport (carrier) proteins}}, which prolongs their {{c3::half-life}}.',
     3),
    (deck, 22, 'cloze',
     'Carrier binding shields steroid hormones from clearance, so they are long-lived: cortisol''s half-life is about {{c1::60–90 minutes}}, whereas free epinephrine clears in roughly {{c2::1 minute}}.',
     2),
    (deck, 23, 'cloze',
     'Carrier proteins keep a lipid-soluble hormone {{c1::bound}} and biologically {{c1::inactive}}; only the {{c2::free (unbound)}} fraction can enter target cells and act.',
     2),
    (deck, 24, 'cloze',
     'A {{c1::direct}} hormone binds receptors on its {{c2::ultimate target}} tissue and triggers the physiological response itself.',
     2),
    (deck, 25, 'cloze',
     'A {{c1::tropic}} hormone switches another endocrine gland on or off, prompting it to secrete a downstream hormone — e.g., ACTH driving the adrenal cortex to release {{c2::cortisol}}.',
     2),
    (deck, 26, 'cloze',
     'Once a hormone reaches adequate blood concentrations, {{c1::negative feedback}} kicks in: the hormone (or a downstream product) {{c2::inhibits}} the upstream steps that drove its own secretion.',
     2),
    (deck, 27, 'cloze',
     'In the classic thyroid loop, rising {{c1::T3 and T4}} inhibit the release of {{c2::TRH and TSH}} from the hypothalamus and anterior pituitary.',
     2),
    (deck, 28, 'cloze',
     'Most endocrine axes are governed by negative feedback, making {{c1::positive}} feedback the rare exception among hormonal control loops.',
     1),
    (deck, 29, 'cloze',
     'The classic positive-feedback example is {{c1::oxytocin}} in labor: contractions stretch the cervix, which signals the {{c2::hypothalamus and pituitary}} to release still more hormone until birth.',
     2),
    (deck, 30, 'cloze',
     'Because a nervous-system stimulus must pass through it to be translated into a hormonal signal, the {{c1::hypothalamus}} serves as the functional junction between the {{c2::nervous and endocrine}} systems, issuing the releasing and inhibiting commands that govern the {{c3::pituitary}} gland.',
     3),
    (deck, 31, 'cloze',
     'Because releasing and inhibiting hormones from the {{c1::hypothalamus}} travel through the {{c2::hypophyseal portal}} vessels straight to the {{c3::anterior}} pituitary rather than looping through the general bloodstream first, they act at concentrations far too low to register in {{c4::systemic circulation}}.',
     4),
    (deck, 32, 'cloze',
     'Traveling down the hypophyseal portal veins, four hypothalamic releasing hormones each switch on a specific anterior-pituitary output: {{c1::GnRH}} drives release of the gonadotropins FSH and LH, {{c2::GHRH}} triggers GH, {{c3::TRH}} triggers TSH, and {{c4::CRH (CRF)}} triggers ACTH.',
     4),
    (deck, 33, 'cloze',
     'The hypothalamus controls the anterior pituitary {{c1::hormonally}}, sending releasing and inhibiting factors through the {{c2::hypophyseal portal system}}.',
     2),
    (deck, 34, 'cloze',
     'The hypothalamus controls the posterior pituitary {{c1::neurally}}: {{c2::axons}} from paraventricular and supraoptic neurons descend into it and release hormones directly.',
     2),
    (deck, 35, 'cloze',
     'Because the posterior pituitary holds only axon terminals, it {{c1::synthesizes no hormones of its own}} — instead, {{c2::hypothalamic}} neurons build ADH and oxytocin, then ferry them down their {{c3::axons}} to be stored and released from those terminals.',
     3),
    (deck, 36, 'cloze',
     'Among the tropic anterior-pituitary hormones, the gonadotropins {{c1::FSH and LH}} act on the {{c2::gonads}}.',
     2),
    (deck, 37, 'cloze',
     'The tropic anterior-pituitary hormone ACTH drives the {{c1::adrenal cortex}}, while TSH drives the {{c2::thyroid}}.',
     2),
    (deck, 38, 'cloze',
     'The anterior pituitary''s two gonadotropins, {{c1::FSH}} and {{c1::LH}}, target the gonads and are secreted only when the hypothalamus signals upstream by releasing {{c2::GnRH}}.',
     2),
    (deck, 39, 'cloze',
     'In the HPA axis, the hypothalamus releases {{c1::CRH (corticotropin-releasing hormone)}}, which drives the anterior pituitary to secrete {{c2::ACTH}}, stimulating adrenal glucocorticoid output.',
     2),
    (deck, 40, 'cloze',
     'ACTH''s name reveals its adrenal-cortex target: it stands for {{c1::adrenocorticotropic}} hormone.',
     1),
    (deck, 41, 'cloze',
     'An anterior pituitary hormone acting directly on non-endocrine tissue, {{c1::growth hormone}} drives protein synthesis in bone and skeletal muscle.',
     1),
    (deck, 42, 'cloze',
     'The anterior pituitary hormone {{c1::prolactin}} acts directly on the mammary glands to stimulate milk production.',
     1),
    (deck, 43, 'cloze',
     'Secreted by the anterior pituitary, {{c1::endorphins}} are brain opioid peptides that blunt pain perception.',
     1),
    (deck, 44, 'cloze',
     'Unlike other anterior pituitary hormones, {{c1::prolactin}} is held under tonic inhibitory control: the hypothalamus continuously releases {{c2::dopamine}} (prolactin-inhibiting hormone), which suppresses prolactin secretion until that brake is lifted.',
     2),
    (deck, 45, 'cloze',
     'Before the growth plates fuse, oversecretion of growth hormone from the anterior pituitary causes the excessive skeletal growth of {{c1::gigantism}}.',
     1),
    (deck, 46, 'cloze',
     'Too little growth hormone during childhood, before the growth plates fuse, stunts skeletal growth as {{c1::pituitary dwarfism}} (GH deficiency).',
     1),
    (deck, 47, 'cloze',
     'The {{c1::hypothalamus}} manufactures {{c2::ADH (antidiuretic hormone)}} and {{c2::oxytocin}}, but neither is synthesized in the posterior pituitary — that lobe only {{c3::stores and releases}} them into the blood.',
     3),
    (deck, 48, 'cloze',
     'When blood osmolarity rises, the posterior pituitary secretes {{c1::ADH (vasopressin)}}, which acts on the kidney to reabsorb water and produce more concentrated urine.',
     1),
    (deck, 49, 'cloze',
     'ADH inserts {{c1::aquaporin}} water channels into the apical membrane of {{c2::collecting duct}} principal cells, raising water permeability so filtrate water is reabsorbed into the blood.',
     2),
    (deck, 50, 'cloze',
     'Hypothalamic osmoreceptors trigger posterior pituitary release of {{c1::ADH (vasopressin)}} when they detect a rise in {{c2::plasma osmolarity}}, driving renal water reabsorption to dilute the blood.',
     2),
    (deck, 51, 'cloze',
     'A {{c1::drop in blood volume or pressure}} also stimulates {{c2::ADH (vasopressin)}} release, promoting renal water reabsorption to conserve water and restore volume.',
     2),
    (deck, 52, 'cloze',
     'Released from the posterior pituitary, {{c1::oxytocin}} acts on two smooth-muscle targets: it triggers {{c2::uterine contractions}} that expel the fetus during childbirth and drives {{c3::milk ejection (let-down)}} when suckling signals reach the hypothalamus during lactation.',
     3),
    (deck, 53, 'cloze',
     'During labor, oxytocin from the posterior pituitary runs a {{c1::positive}} feedback loop: {{c2::cervical stretch}} triggers more oxytocin release, and the added oxytocin {{c3::intensifies uterine contractions}} that stretch the cervix still further — the cycle breaking only at birth.',
     3),
    (deck, 54, 'cloze',
     'Under the control of {{c1::TSH}} from the anterior pituitary, the thyroid runs two separate programs: {{c2::T3 and T4}} drive up the basal metabolic rate, while {{c3::calcitonin}} pushes blood calcium down by throttling osteoclasts.',
     3),
    (deck, 55, 'cloze',
     'To build thyroid hormone, follicular cells stud residues of the amino acid {{c1::tyrosine}} (held on thyroglobulin) with iodine: linking {{c2::three}} iodines yields T3, while {{c3::four}} iodines yields T4 (thyroxine).',
     3),
    (deck, 56, 'cloze',
     'Because {{c1::T3 and T4}} drive mitochondria to burn more oxygen for ATP and accelerate the turnover — both {{c3::synthesis and breakdown}} — of proteins and fats, they push the {{c2::basal metabolic rate}} upward.',
     3),
    (deck, 57, 'cloze',
     'Dietary iodine deficiency blocks synthesis of T3 and T4, lowering basal metabolic rate — the classic cause of {{c1::hypothyroidism}}.',
     1),
    (deck, 58, 'cloze',
     'Hypothyroidism presents with {{c1::lethargy, cold intolerance, and weight gain}} plus a {{c2::slowed heart and respiratory rate}}, reflecting reduced tissue sensitivity to catecholamines.',
     2),
    (deck, 59, 'cloze',
     'Because thyroid hormone sets basal metabolic rate, a patient running hot rather than cold points toward {{c1::hyperthyroidism}} instead of hypothyroidism.',
     1),
    (deck, 60, 'cloze',
     'Elevated thyroid hormone speeds metabolism, driving {{c1::heat intolerance and sweating}}, {{c2::weight loss}} despite normal intake, and a {{c3::faster heart and breathing rate}} with restlessness.',
     3),
    (deck, 61, 'cloze',
     'When blood calcium climbs, the thyroid''s {{c1::C (parafollicular) cells}} release calcitonin, which {{c2::lowers}} serum Ca²⁺ by driving three parallel shifts: {{c3::depositing calcium into bone (inhibiting osteoclasts), curbing intestinal calcium absorption, and increasing urinary calcium excretion}}.',
     3),
    (deck, 62, 'cloze',
     'When blood calcium falls, the parathyroid glands release {{c1::parathyroid hormone (PTH)}}, which {{c2::raises}} circulating calcium — directly opposing the thyroid hormone {{c3::calcitonin}}, its physiological antagonist that lowers calcium.',
     3),
    (deck, 63, 'cloze',
     'To raise low plasma calcium, PTH acts on three fronts: it drives {{c1::osteoclasts to resorb bone}}, boosts {{c2::calcium reabsorption in the kidney}}, and indirectly increases {{c3::intestinal calcium absorption}}.',
     3),
    (deck, 64, 'cloze',
     'PTH raises intestinal calcium absorption indirectly by stimulating the kidney to synthesize {{c1::calcitriol (active vitamin D3 / 1,25-dihydroxyvitamin D)}}.',
     1),
    (deck, 65, 'cloze',
     'In the gut, intestinal epithelial cells absorb dietary {{c1::calcium and phosphate}} only after vitamin D is activated to {{c2::calcitriol}}.',
     2),
    (deck, 66, 'cloze',
     '{{c1::PTH}} drives the conversion of vitamin D to active calcitriol, which in turn boosts intestinal absorption of {{c2::calcium}}.',
     2),
    (deck, 67, 'cloze',
     'Blood calcium homeostasis rests on an opposing pair: when levels fall too low, {{c1::parathyroid hormone (PTH)}} drives them back up, whereas a rise too high triggers {{c2::calcitonin}} from the thyroid to pull them back down.',
     2),
    (deck, 68, 'cloze',
     'The zona glomerulosa of the adrenal cortex secretes {{c1::mineralocorticoids}}, such as {{c2::aldosterone}}.',
     2),
    (deck, 69, 'cloze',
     'The zona fasciculata of the adrenal cortex secretes {{c1::glucocorticoids}}, such as {{c2::cortisol}}.',
     2),
    (deck, 70, 'cloze',
     'The zona reticularis of the adrenal cortex secretes {{c1::cortical sex hormones (androgens/estrogens)}}.',
     1),
    (deck, 71, 'cloze',
     'The zona fasciculata secretes {{c1::glucocorticoids}} (chiefly {{c2::cortisol}}) under drive from {{c3::ACTH}}, the pituitary hormone released during prolonged stress.',
     3),
    (deck, 72, 'cloze',
     'During prolonged stress, cortisol raises blood glucose by driving {{c1::gluconeogenesis}}, favors protein {{c2::catabolism}} over synthesis, and suppresses the {{c3::immune}} response and inflammation.',
     3),
    (deck, 73, 'cloze',
     'Under long-term stress, the zona fasciculata secretes the glucocorticoid {{c1::cortisol}}, whose net metabolic effect is to {{c2::raise blood glucose}}.',
     2),
    (deck, 74, 'cloze',
     'To supply raw material for making fuel, cortisol drives catabolism of {{c1::glycogen}}, {{c2::stored triglycerides}}, and {{c3::muscle proteins}}.',
     3),
    (deck, 75, 'cloze',
     'Along the HPA axis, the hypothalamus releases {{c1::CRH (corticotropin-releasing hormone)}}, which drives the anterior pituitary to secrete {{c2::ACTH (adrenocorticotropic hormone)}}; ACTH then signals the adrenal cortex''s zona fasciculata to release the glucocorticoid {{c3::cortisol}}.',
     3),
    (deck, 76, 'cloze',
     'In the distal nephron, the mineralocorticoid {{c1::aldosterone}} defends blood pressure by driving reabsorption of {{c2::Na+}} (water follows), while the negative luminal electrochemical gradient this creates favors secretion of {{c3::K+ and H+}} into the forming urine.',
     3),
    (deck, 77, 'cloze',
     'When blood pressure drops, {{c1::juxtaglomerular}} cells of the kidney release {{c2::renin}}, which cleaves angiotensinogen into angiotensin I.',
     2),
    (deck, 78, 'cloze',
     'In the lungs, {{c1::ACE (angiotensin-converting enzyme)}} converts {{c2::angiotensin I}} into {{c2::angiotensin II}}, the active signaling peptide.',
     2),
    (deck, 79, 'cloze',
     'Angiotensin II drives the {{c1::adrenal cortex}} to release {{c2::aldosterone}}, raising blood pressure.',
     2),
    (deck, 80, 'cloze',
     'The {{c1::adrenal medulla}} pours the catecholamines {{c2::epinephrine and norepinephrine}} straight into the bloodstream; because both are built from a single amino acid (tyrosine), they belong to the {{c3::amino-acid–derivative (amine)}} class of hormones rather than the steroid or peptide classes.',
     3),
    (deck, 81, 'cloze',
     'Under acute stress, chromaffin cells of the adrenal medulla flood the circulation with the catecholamines {{c1::epinephrine and norepinephrine}}, which quicken the heartbeat.',
     1),
    (deck, 82, 'cloze',
     'During the acute stress response, catecholamines raise blood oxygen by {{c1::dilating the airways (bronchodilation)}}.',
     1),
    (deck, 83, 'cloze',
     'Catecholamines redirect blood toward skeletal muscle by {{c1::dilating muscle vessels}} while {{c2::constricting those to the gut, kidneys, and skin}}.',
     2),
    (deck, 84, 'cloze',
     'During acute stress, epinephrine from the adrenal medulla drives {{c1::glycogenolysis}} in both {{c2::the liver and skeletal muscle}}, dumping glucose into the blood while also pushing up the {{c3::basal metabolic rate}}.',
     3),
    (deck, 85, 'cloze',
     'When a threat hits, the adrenal medulla''s catecholamines (epinephrine and norepinephrine) drive the {{c1::short-term}} stress response, while glucocorticoids like {{c2::cortisol}} from the adrenal {{c3::cortex}} sustain the {{c4::long-term}} response.',
     4),
    (deck, 86, 'cloze',
     'Within the pancreatic islets, three endocrine cell types partition the work of glucose control: {{c1::alpha}} cells release {{c2::glucagon}}, {{c1::beta}} cells release {{c3::insulin}}, and {{c1::delta}} cells release {{c4::somatostatin}}, which itself brakes the secretion of the other two.',
     4),
    (deck, 87, 'cloze',
     'When fasting drops blood glucose, the pancreatic {{c1::alpha}} cells release {{c2::glucagon}}, which pushes glucose back into circulation by driving the liver to break down glycogen ({{c3::glycogenolysis}}) and to synthesize new glucose from amino acids and glycerol ({{c4::gluconeogenesis}}).',
     4),
    (deck, 88, 'cloze',
     'When blood glucose climbs, pancreatic {{c1::beta cells}} release {{c2::insulin}}, the antagonist of {{c3::glucagon}}.',
     3),
    (deck, 89, 'cloze',
     'Insulin drives glucose from the blood into {{c1::skeletal muscle and fat}}, prompts the liver to store the surplus as {{c2::glycogen}}, and promotes anabolic synthesis of {{c3::triglycerides and protein}}.',
     3),
    (deck, 90, 'cloze',
     'Within the pancreatic islets, the {{c1::delta cells}} release {{c2::somatostatin}}, a hormone that dampens secretion of {{c3::both insulin and glucagon}}.',
     3),
    (deck, 91, 'cloze',
     'In {{c1::type 1}} diabetes mellitus, an {{c2::autoimmune}} attack destroys the pancreatic {{c3::beta cells}}, so almost no insulin is made.',
     3),
    (deck, 92, 'cloze',
     'In {{c1::type 2}} diabetes mellitus, beta cells still secrete insulin, but target cells have grown {{c2::resistant}} to it.',
     2),
    (deck, 93, 'cloze',
     'When filtered glucose exceeds the proximal tubule''s {{c1::transport maximum}}, the excess spills into the urine as {{c2::glucosuria}}.',
     2),
    (deck, 94, 'cloze',
     'Unrecovered urinary glucose acts as an {{c1::osmotic diuretic}}, holding water in the filtrate to drive the {{c2::polyuria}} and {{c2::polydipsia}} of diabetes mellitus.',
     2),
    (deck, 95, 'cloze',
     'Too much circulating insulin drives blood glucose dangerously {{c1::low}} — a state called {{c1::hypoglycemia}} — starving cells of glucose and producing {{c2::muscle weakness}} and, if uncorrected, unconsciousness or death.',
     2),
    (deck, 96, 'cloze',
     'Pituitary {{c1::LH}} drives the {{c2::Leydig}} cells of the testes to release {{c3::testosterone}}, whose fetal surge directs {{c4::anatomical differentiation of the male sexual organs}} in utero.',
     4),
    (deck, 97, 'cloze',
     'At puberty, the rise in {{c1::testosterone}} triggers {{c2::secondary sex characteristics}} such as a deepened voice and increased muscle mass.',
     2),
    (deck, 98, 'cloze',
     'Prompted by pituitary {{c1::gonadotropins}} (LH and FSH), the ovaries release {{c2::estrogens}} and {{c2::progesterone}} — the hormones that steer female reproductive development and the {{c3::secondary sex characteristics}}.',
     3),
    (deck, 99, 'cloze',
     'Two glycoprotein gonadotropins released by the {{c1::anterior pituitary}} — {{c2::FSH and LH}} — act on the testes and ovaries, driving the gonads to synthesize their {{c3::sex-steroid hormones}} (testosterone, estrogens, and progesterone).',
     3),
    (deck, 100, 'cloze',
     'Sitting inferior and posterior to the thalamus, the {{c1::pineal}} gland secretes {{c2::melatonin}}, an amine hormone whose blood levels climb as light fades — entraining the body''s {{c3::circadian rhythm}} and ushering in drowsiness.',
     3),
    (deck, 101, 'cloze',
     '{{c1::Melatonin}} from the {{c2::pineal gland}}, suppressed by light and increased by {{c3::darkness}}, synchronizes the body''s {{c4::circadian}} rhythm to the day–night cycle.',
     4),
    (deck, 102, 'cloze',
     'In response to hypoxia, the kidneys release {{c1::erythropoietin (EPO)}}, which stimulates the {{c2::bone marrow}} to increase red blood cell production.',
     2),
    (deck, 103, 'cloze',
     'Once oxygen-carrying capacity recovers, EPO secretion falls, closing the loop through {{c1::negative feedback}}.',
     1),
    (deck, 104, 'cloze',
     'When high blood volume overstretches the heart''s {{c1::atria}}, they secrete {{c2::atrial natriuretic peptide (ANP)}}, which drives renal excretion of {{c3::sodium and water}} and thereby opposes the salt-and-fluid retention of {{c4::aldosterone}}.',
     4),
    (deck, 105, 'cloze',
     'Perched above the heart, the thymus releases {{c1::thymosins}}, the hormones that guide maturation of {{c2::T lymphocytes (T cells)}}; because the gland {{c3::atrophies (shrinks / involutes)}} through adulthood, its output of these hormones tapers off with age.',
     3);

    RAISE NOTICE 'Seeded deck % with % cards.', deck, 106;
END $$;
