-- Biochemistry Ch1: Amino Acids, Peptides & Proteins — REMEDIATED (quality + scope sweep)
-- Replaces 23 flagged questions in place (UPDATE by id). 15 re-engineered (quality), 8 scope-replaced
-- (off-scope concept swapped for an in-scope one in the same subtopic). Grounded in LibreTexts Biochemistry;
-- scope confirmed against the AAMC 2026 outline. distractor_category overgeneralization->misconception,
-- true_but_irrelevant->partial_truth (CHECK constraint). Idempotent; safe to re-run.

BEGIN;

-- [Peptide Bond Formation & Hydrolysis] SCOPE-REPLACE ans=A hard skill2
UPDATE questions SET
  question_text = 'X-ray crystallography of a folded protein shows that the backbone C–N bond linking each pair of adjacent residues is measurably shorter than a typical C–N single bond, and that the two atoms bonded to the carbonyl carbon and the two atoms bonded to the amide nitrogen all lie in a single plane with little rotation observed around that C–N bond. Which explanation best accounts for these observations?',
  options = '[{"label": "A", "text": "The nitrogen lone pair delocalizes into the carbonyl, giving the C–N bond partial double-bond character."}, {"label": "B", "text": "Hydrogen bonds between each carbonyl oxygen and a nearby amide hydrogen lock the backbone atoms into one plane."}, {"label": "C", "text": "Steric clash between the two flanking side chains prevents any twisting around the C–N bond."}, {"label": "D", "text": "The nitrogen becomes sp-hybridized, forming a true C–N double bond in place of the single bond."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The peptide (amide) linkage that joins residues is not a simple C–N single bond: the nonbonding electron pair on the amide nitrogen delocalizes toward the carbonyl carbon, so the bond has partial double-bond character. This resonance forces the carbonyl carbon and amide nitrogen (and the two other atoms bonded to each) into one plane, gives them \(sp^2\) character with roughly 120° bond angles, shortens the C–N distance relative to a pure single bond, and restricts rotation about the bond (LibreTexts lines 10385–10388, 10501). (Choice A) is correct: delocalizing the nitrogen lone pair into the carbonyl produces the partial double-bond character that explains both the shortened C–N bond and its planarity and restricted rotation. (Choice B) is incorrect: backbone hydrogen bonds between a carbonyl oxygen and an amide hydrogen do form, but they stabilize higher-order secondary structure such as helices and sheets — they are not what confers the individual peptide bond''s own rigidity, planarity, or shortened length. (Choice C) is incorrect: side-chain (R-group) bulk restricts the \(\phi\) and \(\psi\) rotations around the alpha carbon that separates two peptide planes (LibreTexts lines 10404–10408), not rotation around the C–N bond itself, and it would not shorten that bond. (Choice D) is incorrect: the character is partial, not a full double bond, and the nitrogen adopts \(sp^2\) (not \(sp\)) hybridization consistent with its 120° geometry; describing it as a true double bond from \(sp\) nitrogen overstates the resonance effect. This is a Scientific Reasoning and Problem Solving question because you must apply the resonance model of the amide bond to interpret specific structural observations (a shortened bond, planarity, and restricted rotation) rather than recall a stated fact.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '4cfc5d0d-fe18-4a6b-9dd7-cacb41453a50';
DELETE FROM question_distractor_metadata WHERE question_id = '4cfc5d0d-fe18-4a6b-9dd7-cacb41453a50';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4cfc5d0d-fe18-4a6b-9dd7-cacb41453a50', 'B', 'misconception', 'attributes peptide-bond rigidity to hydrogen bonding (a real backbone feature) rather than to resonance'),
  ('4cfc5d0d-fe18-4a6b-9dd7-cacb41453a50', 'C', 'partial_truth', 'applies side-chain steric restriction of phi/psi angles to the wrong bond (the C–N bond itself)'),
  ('4cfc5d0d-fe18-4a6b-9dd7-cacb41453a50', 'D', 'misconception', 'upgrades partial double-bond character to a full double bond and misassigns sp hybridization');

-- [Hydrophobicity & Unique Residues] reengineer ans=B medium skill1
UPDATE questions SET
  question_text = 'A student sorts the 20 standard amino acids into "polar" and "nonpolar" bins using a simple structural rule: any side chain containing an O, N, or S heteroatom is called polar. This rule places serine, threonine, cysteine, and asparagine all in the polar bin. When the student later checks the Kyte-Doolittle hydropathy scale, one of these four residues has a strongly positive (hydrophobic) value and is, in fact, commonly found buried in the nonpolar interior of folded proteins. Which residue is it?',
  options = '[{"label": "A", "text": "Serine"}, {"label": "B", "text": "Cysteine"}, {"label": "C", "text": "Asparagine"}, {"label": "D", "text": "Threonine"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Structural classification bins a side chain as polar whenever it carries an O, N, or S heteroatom, but empirical hydropathy scales measure the actual free energy of transferring a side chain from water to a nonpolar solvent, and the two do not always agree. LibreTexts notes this discrepancy explicitly, stating that on the Kyte-Doolittle scale "cysteine is quite nonpolar" and that "cysteine is often buried in protein in a more hydrophobic environment," even though its -SH group leads the structural rule to classify it as polar (libretexts-biochemistry.txt, lines 5365-5366, 5237). (Choice A) is incorrect: serine''s -CH2OH side chain is genuinely hydrophilic, with a negative Kyte-Doolittle value (-0.8), so both the structural rule and the scale agree it is polar and surface-favoring. (Choice B) is correct: cysteine''s sulfhydryl (-SH) group makes it look polar structurally, but its Kyte-Doolittle value is strongly positive (+2.5, more hydrophobic than alanine at +1.8), so it is the residue whose empirical hydropathy contradicts the naive structural rule and which is commonly buried in the core. (Choice C) is incorrect: asparagine''s amide side chain is one of the most hydrophilic residues, with a strongly negative Kyte-Doolittle value (-3.5); structure and scale agree it is polar and surface-exposed. (Choice D) is incorrect: threonine''s hydroxyl side chain is hydrophilic, with a negative Kyte-Doolittle value (-0.7), so like serine it is correctly binned as polar by both the structural rule and the scale. This is a Knowledge of Scientific Concepts and Principles question because you must recall that cysteine, despite its polar-looking sulfhydryl group, is empirically hydrophobic on the Kyte-Doolittle scale and is frequently buried in the protein interior.',
  difficulty = 'medium',
  cognitive_skill = 1
WHERE id = 'ed218917-2f90-4d23-b87f-bf7f665ef8c3';
DELETE FROM question_distractor_metadata WHERE question_id = 'ed218917-2f90-4d23-b87f-bf7f665ef8c3';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('ed218917-2f90-4d23-b87f-bf7f665ef8c3', 'A', 'misconception', 'heteroatom-implies-hydrophilic'),
  ('ed218917-2f90-4d23-b87f-bf7f665ef8c3', 'C', 'misconception', 'amide-looks-buriable'),
  ('ed218917-2f90-4d23-b87f-bf7f665ef8c3', 'D', 'misconception', 'hydroxyl-implies-hydrophilic');

-- [Conjugated Proteins & Denaturation] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher purifies a small single-domain enzyme and heats the solution until the enzyme completely loses its catalytic activity. When the solution is slowly cooled back to room temperature, with no chaperones or other proteins present, the enzyme spontaneously recovers essentially all of its original activity. Which conclusion about this enzyme is best supported by the result?',
  options = '[{"label": "A", "text": "Its native three-dimensional fold is specified by its amino acid sequence"}, {"label": "B", "text": "Its activity depends on molecular chaperones that refold it after heating"}, {"label": "C", "text": "Its peptide-bond backbone was cleaved by heat and then re-formed on cooling"}, {"label": "D", "text": "Its covalent structure was too stable for the heat to disrupt any bonding"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Heating disrupts the weak, noncovalent interactions (hydrogen bonds, hydrophobic contacts, van der Waals forces) that hold a protein in its native fold, producing an unfolded, inactive (denatured) state; the covalent primary structure — the peptide-bonded sequence of amino acids — is left intact. In Anfinsen''s classic ribonuclease experiment, the textbook notes that a denatured protein allowed to refold demonstrated that "the primary sequence contains all the information required for the protein to achieve its native conformation." (Choice A) is correct: because the enzyme refolds and regains full activity on its own once the denaturing heat is removed, the information needed to reach the active native fold must reside in the polypeptide itself — that is, in its amino acid sequence — since nothing else was present to guide folding. (Choice B) is incorrect: molecular chaperones help prevent misfolding and aggregation in the crowded cell, but this experiment contained no chaperones or other proteins, and the enzyme still refolded, so chaperones are not required here. (Choice C) is incorrect: heat denaturation disrupts noncovalent interactions, not the covalent peptide bonds of the backbone; the primary structure is not cleaved during simple thermal denaturation, so no bonds need to "re-form" on cooling. (Choice D) is incorrect: the enzyme did lose all activity when heated, which shows the native structure was in fact disrupted (unfolded); the covalent backbone survived, but the functional folded state clearly did not. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that a protein''s native fold is encoded by its primary sequence to interpret a spontaneous refolding result.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'db2b9f84-c963-460a-b120-64458d4b33aa';
DELETE FROM question_distractor_metadata WHERE question_id = 'db2b9f84-c963-460a-b120-64458d4b33aa';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('db2b9f84-c963-460a-b120-64458d4b33aa', 'B', 'misconception', 'chaperones are always required for folding'),
  ('db2b9f84-c963-460a-b120-64458d4b33aa', 'C', 'misconception', 'denaturation breaks covalent/primary structure'),
  ('db2b9f84-c963-460a-b120-64458d4b33aa', 'D', 'reversed_relationship', 'regained activity means never denatured');

-- [Amino Acid Structure & Stereochemistry] reengineer ans=B hard skill2
UPDATE questions SET
  question_text = 'Nearly every amino acid found in proteins is an L-isomer and, when its absolute configuration is assigned using Cahn–Ingold–Prelog (CIP) priority rules, is designated (S) at the \(\alpha\)-carbon. One proteinogenic amino acid, however, is designated (R) despite having the identical L-spatial arrangement of its four substituents. Which amino acid is the exception?',
  options = '[{"label": "A", "text": "Serine"}, {"label": "B", "text": "Cysteine"}, {"label": "C", "text": "Methionine"}, {"label": "D", "text": "Threonine"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Every chiral proteinogenic amino acid shares the same L-arrangement at the \(\alpha\)-carbon, but the (R)/(S) label depends on the CIP priority order of the four substituents: \(-\text{NH}_3^+\), \(-\text{COO}^-\), the side chain, and \(-\text{H}\). For nearly all amino acids the nitrogen ranks first, the carboxyl carbon (bonded to O, O, O) ranks second, and the side-chain carbon ranks third, which yields (S). The label flips to (R) only when a side chain atom outranks oxygen at the first point of difference. (Choice B) is correct: cysteine''s \(-\text{CH}_2\text{SH}\) side chain places a sulfur atom (Z = 16) on the very first side-chain carbon; because sulfur outranks the oxygens of the carboxyl group, the side chain is promoted above \(-\text{COO}^-\), swapping priorities 2 and 3 and inverting the descriptor to (R) even though the physical L-arrangement is unchanged. (Choice A) is incorrect: serine''s \(-\text{CH}_2\text{OH}\) side chain also carries a heteroatom on the first carbon, but that atom is oxygen, so the side chain cannot outrank the triply-oxygenated carboxyl carbon; serine remains L-(S). (Choice C) is incorrect: methionine does contain sulfur, but it sits two carbons out in \(-\text{CH}_2\text{CH}_2\text{SCH}_3\); at the first side-chain carbon the atoms are C, H, H, which lose to the carboxyl carbon''s O, O, O, so methionine is L-(S). (Choice D) is incorrect: threonine has a second stereocenter in its \(-\text{CH(OH)CH}_3\) side chain, but its \(\alpha\)-carbon still ranks the carboxyl above the side chain and is designated (S). This is a Scientific Reasoning and Problem Solving question because you must apply CIP priority rules to each side chain to determine which one promotes an atom above the carboxyl oxygens and thereby inverts the (R)/(S) descriptor.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '5982b835-e805-4f47-baf1-5c1282149586';
DELETE FROM question_distractor_metadata WHERE question_id = '5982b835-e805-4f47-baf1-5c1282149586';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('5982b835-e805-4f47-baf1-5c1282149586', 'A', 'misconception', 'heteroatom-on-first-carbon assumed to flip priority regardless of element'),
  ('5982b835-e805-4f47-baf1-5c1282149586', 'C', 'misconception', 'presence of sulfur assumed sufficient without accounting for its position'),
  ('5982b835-e805-4f47-baf1-5c1282149586', 'D', 'partial_truth', 'extra stereocenter/hydroxyl conflated with R designation');

-- [Amino Acid Structure & Stereochemistry] reengineer ans=A medium skill2
UPDATE questions SET
  question_text = 'Every standard amino acid used in proteins belongs to the L family, yet the chiral residues are not all assigned the same absolute configuration: all of them except L-cysteine are \(S\) at the α-carbon, while L-cysteine is instead assigned \(R\). The atoms bonded to the α-carbon are arranged in space in the same relative orientation for L-cysteine as for the other L-amino acids, such as L-serine; only the descriptor differs. What does the cysteine exception best illustrate about amino acid stereochemistry?',
  options = '[{"label": "A", "text": "The L/D and \\(R\\)/\\(S\\) systems classify stereochemistry by different criteria, so one fixed spatial arrangement can correspond to either descriptor."}, {"label": "B", "text": "L-cysteine and L-serine are enantiomers of each other, which is why they are given opposite absolute-configuration descriptors."}, {"label": "C", "text": "The α-carbon of L-cysteine holds its substituents in the opposite spatial arrangement compared with the other L-amino acids."}, {"label": "D", "text": "Assigning an amino acid to the L family always requires first determining whether its α-carbon is \\(R\\) or \\(S\\)."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The L/D system is a relative descriptor that fixes the spatial arrangement of the α-carbon by reference to L-glyceraldehyde (the "CORN" orientation), whereas the \(R\)/\(S\) system is an absolute descriptor assigned from Cahn–Ingold–Prelog priorities, which rank substituents by atomic number. Because the two systems judge configuration by different criteria, a single fixed spatial arrangement can map to either \(R\) or \(S\): the textbook states that "L-cysteine is also (R)-cysteine," while "all the other L-amino acids are (S), but this reflects the human decision to give a sulfur atom a higher priority than a carbon atom and does not reflect a real difference in configuration" (LibreTexts 5419–5461). (Choice A) is correct: L/D and \(R\)/\(S\) are independent classification schemes, so cysteine can keep the same L spatial arrangement as the other residues yet receive the opposite CIP descriptor simply because its sulfur outranks the carboxyl carbon. (Choice B) is incorrect: L-cysteine and L-serine are different compounds with different side chains, not mirror images of the same molecule, so they are not enantiomers; enantiomers are non-superimposable mirror images of one identical structure. (Choice C) is incorrect: the stem specifies that the spatial arrangement is the same as the other L-amino acids, and the textbook stresses the differing descriptor "does not reflect a real difference in configuration," so the atoms are not oppositely arranged. (Choice D) is incorrect: the L designation is assigned by spatial comparison to L-glyceraldehyde independently of the \(R\)/\(S\) descriptor, which is precisely why L can correspond to either \(R\) or \(S\); the two systems are not derived one from the other. This is a Scientific Reasoning and Problem Solving question because you must apply the distinction between the relative L/D system and the absolute CIP \(R\)/\(S\) system to interpret why one spatial configuration yields different descriptors.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '2434f09f-b70c-408f-8396-bd484d105d84';
DELETE FROM question_distractor_metadata WHERE question_id = '2434f09f-b70c-408f-8396-bd484d105d84';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('2434f09f-b70c-408f-8396-bd484d105d84', 'B', 'misconception', 'confusing_different_compounds_with_enantiomers'),
  ('2434f09f-b70c-408f-8396-bd484d105d84', 'C', 'misconception', 'descriptor_change_implies_spatial_change'),
  ('2434f09f-b70c-408f-8396-bd484d105d84', 'D', 'reversed_relationship', 'L_depends_on_RS_assignment');

-- [Peptide Bond Formation & Hydrolysis] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'During stepwise peptide synthesis, a chemist attaches a bulky, unreactive protecting group to the α-amino group of a free amino acid and then adds this modified amino acid to a peptide chain that is being elongated one residue at a time. What is the most likely consequence for the modified amino acid?',
  options = '[{"label": "A", "text": "It can be joined to the chain, but no further residue can be attached beyond it."}, {"label": "B", "text": "It can be joined to the chain, and further residues can still be attached beyond it."}, {"label": "C", "text": "It cannot be joined to the chain, because its carboxyl group is no longer available."}, {"label": "D", "text": "It cannot be joined to the chain, because peptide bonds form only between two amino groups."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' A peptide bond is an amide linkage formed by dehydration synthesis: the textbook states the reaction "connects the carboxylic acid of the upstream amino acid with the amine functional group of the downstream amino acid to form an amide linkage," in which "this carbonyl of the modified end serves as an electrophile in the attack of the amine nitrogen, a nucleophile." Thus every new bond requires a free carboxyl group (activated as the electrophile) on one partner and a free α-amino group (the nucleophile) on the other. Blocking the α-amino group removes only the nucleophile that would accept the next residue. (Choice A) is correct: the modified amino acid still has an available carboxyl group, so it can be coupled to the chain''s free amino end, but its own capped amino group can no longer act as the nucleophile to accept a subsequent residue, so elongation stops there. (Choice B) is incorrect: this ignores that the α-amino group is the nucleophile required for the next coupling; with it blocked, no additional residue can add beyond this one, which is precisely why protecting groups are used to control chain growth. (Choice C) is incorrect: the protecting group was placed on the amino group, not the carboxyl group, so the carboxyl remains available to form an amide bond with the chain''s amino end. (Choice D) is incorrect: a peptide bond forms between a carboxyl group and an amino group (yielding an amide), not between two amino groups, so this misstates the chemistry of the linkage. This is a Scientific Reasoning and Problem Solving question because you must apply the nucleophile/electrophile roles in peptide bond formation to predict how blocking one functional group changes which couplings can still occur.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '8c747741-9044-4bec-af0f-5537494c82a0';
DELETE FROM question_distractor_metadata WHERE question_id = '8c747741-9044-4bec-af0f-5537494c82a0';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8c747741-9044-4bec-af0f-5537494c82a0', 'B', 'misconception', 'ignores the amino group''s role as the nucleophile needed for the next coupling'),
  ('8c747741-9044-4bec-af0f-5537494c82a0', 'C', 'reversed_relationship', 'confuses which terminus was blocked (amino vs carboxyl)'),
  ('8c747741-9044-4bec-af0f-5537494c82a0', 'D', 'misconception', 'misremembers peptide bond as forming between two amino groups rather than a carboxyl and an amino group');

-- [Isoelectric Point (pI)] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'Glutamate has three ionizable groups, whose \(\text{pK}_a\) values are listed in the table. Starting from a strongly acidic solution and raising the pH, the amino acid passes through a species with a net charge of zero before becoming net negative. Based on the table, the isoelectric point (\(\text{pI}\)) of glutamate is closest to which value?

| Ionizable group (glutamate) | \(\text{pK}_a\) |
| --- | --- |
| \(\alpha\)-\(\text{COOH}\) | 2.2 |
| side-chain \(\gamma\)-\(\text{COOH}\) | 4.3 |
| \(\alpha\)-\(\text{NH}_3^+\) | 9.7 |',
  options = '[{"label": "A", "text": "\\(\\text{pI} \\approx 3.25\\)"}, {"label": "B", "text": "\\(\\text{pI} \\approx 5.95\\)"}, {"label": "C", "text": "\\(\\text{pI} \\approx 7.0\\)"}, {"label": "D", "text": "\\(\\text{pI} \\approx 5.4\\)"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The textbook states that as pH rises from acidic to basic, ionizable groups deprotonate in order of increasing \(\text{pK}_a\), and the \(\text{pI}\) is found by "averaging the pKa values of the two groups closest to and on either side of" the net-neutral species. A protonated carboxyl carries charge 0 and becomes \(-1\) when deprotonated, while a protonated \(\alpha\)-amino group carries \(+1\) and becomes 0 when deprotonated. For glutamate you must track the net charge across pH and identify which two \(\text{pK}_a\) values flank the zero-charge form. Below 2.2 both carboxyls are neutral and the amino group is \(+1\) (net \(+1\)); deprotonating the \(\alpha\)-\(\text{COOH}\) at 2.2 gives net 0; deprotonating the side-chain \(\gamma\)-\(\text{COOH}\) at 4.3 gives net \(-1\). The net-zero species is therefore bracketed by the two lowest \(\text{pK}_a\) values. (Choice A) is correct: the zero-charge form is flanked by \(\alpha\)-\(\text{COOH}\) (2.2) below and \(\gamma\)-\(\text{COOH}\) (4.3) above, so \(\text{pI} = (2.2 + 4.3)/2 = 3.25\). (Choice B) is incorrect: averaging the two terminal groups \(\alpha\)-\(\text{COOH}\) and \(\alpha\)-\(\text{NH}_3^+\), \((2.2 + 9.7)/2 = 5.95\), ignores that glutamate''s acidic side chain deprotonates before the amino group, so these two \(\text{pK}_a\) values do not bracket the net-neutral species. (Choice C) is incorrect: averaging the two highest values, \((4.3 + 9.7)/2 = 7.0\), is the rule for a basic amino acid, but glutamate is acidic and its zero-charge form lies at the low-pH end. (Choice D) is incorrect: averaging all three \(\text{pK}_a\) values, \((2.2 + 4.3 + 9.7)/3 = 5.4\), is not how \(\text{pI}\) is defined; only the two \(\text{pK}_a\) values flanking the net-neutral form are averaged. This is a Scientific Reasoning and Problem Solving question because you must apply charge-state reasoning to order the deprotonation events, locate the net-zero species, and average only the two \(\text{pK}_a\) values that flank it.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '1514b8b3-96e6-4005-b48e-be25618c81f1';
DELETE FROM question_distractor_metadata WHERE question_id = '1514b8b3-96e6-4005-b48e-be25618c81f1';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('1514b8b3-96e6-4005-b48e-be25618c81f1', 'B', 'misconception', 'always-average-the-two-termini'),
  ('1514b8b3-96e6-4005-b48e-be25618c81f1', 'C', 'misconception', 'acidic-treated-as-basic'),
  ('1514b8b3-96e6-4005-b48e-be25618c81f1', 'D', 'misconception', 'average-all-pKa-values');

-- [Side-Chain Classification] reengineer ans=B hard skill2
UPDATE questions SET
  question_text = 'A researcher is designing a metalloenzyme active site that requires one amino acid residue whose side chain can readily shuttle a proton — existing in an appreciable mix of both its protonated and deprotonated forms — under the near-neutral conditions of the cytoplasm (pH ≈ 7.4). She consults a table of side-chain pKa values: aspartate ≈ 3.9, histidine ≈ 6.5, lysine ≈ 10.5, and arginine ≈ 12.5. Which residue best meets her requirement?',
  options = '[{"label": "A", "text": "Aspartate"}, {"label": "B", "text": "Histidine"}, {"label": "C", "text": "Lysine"}, {"label": "D", "text": "Arginine"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Whether a side chain is protonated at a given pH depends on how its pKa compares with that pH: by the +2 rule, a group is roughly half protonated when \(\text{pH} = \text{pK}_\text{a}\), and it shifts to ~99% one form once the pH is about two units away from its pKa. A residue can act as a proton shuttle (general acid–base) only if a meaningful fraction of it sits in each ionization state at the working pH, which requires a side-chain pKa close to that pH. (Choice B) is correct: histidine''s imidazole side chain has a pKa of about 6.5, only ~0.9 units below physiological pH, so at pH 7.4 it exists as an appreciable mixture of protonated and deprotonated forms and can readily gain or donate a proton — the reason histidine is the residue most often found doing general acid–base chemistry in enzyme active sites. (Choice A) is incorrect: aspartate''s carboxyl side chain has a pKa near 3.9, roughly 3.5 units below pH 7.4, so it is essentially fully deprotonated (negatively charged) and cannot shuttle a proton at physiological pH. (Choice C) is incorrect: lysine''s ε-amino side chain has a pKa of about 10.5, roughly 3 units above pH 7.4, so it remains essentially fully protonated (positively charged) and does not readily give up its proton under these conditions. (Choice D) is incorrect: arginine''s guanidino side chain has a pKa of about 12.5 and is the most basic standard residue, but that high pKa means it stays fully protonated at physiological pH — being the "most basic" makes it a poorer, not better, proton shuttle at pH 7.4. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between side-chain pKa and ambient pH to predict which residue is significantly ionizable at physiological pH.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'd458540f-9425-4e83-b1d7-3bcfed4e05b7';
DELETE FROM question_distractor_metadata WHERE question_id = 'd458540f-9425-4e83-b1d7-3bcfed4e05b7';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d458540f-9425-4e83-b1d7-3bcfed4e05b7', 'A', 'misconception', 'acidic-residue-confused-for-proton-shuttle'),
  ('d458540f-9425-4e83-b1d7-3bcfed4e05b7', 'C', 'adjacent_fact', 'basic-but-wrong-pKa-window'),
  ('d458540f-9425-4e83-b1d7-3bcfed4e05b7', 'D', 'misconception', 'most-basic-equals-most-reactive');

-- [Primary Structure] reengineer ans=A hard skill2
UPDATE questions SET
  question_text = 'A researcher purifies an intact 40-residue polypeptide and attempts to determine its sequence by Edman degradation. Amino acid composition analysis confirms the protein is full-length and undegraded, yet the very first cycle of the procedure releases no identifiable PTH-amino acid. Which feature of the polypeptide best explains this result?

A. The α-amino group at the N-terminus is acetylated
B. The polypeptide exceeds the length that Edman degradation can sequence
C. The two cysteine residues in the chain form a single disulfide bond
D. The α-carboxyl group at the C-terminus is amidated',
  options = '[{"label": "A", "text": "The α-amino group at the N-terminus is acetylated"}, {"label": "B", "text": "The polypeptide exceeds the length that Edman degradation can sequence"}, {"label": "C", "text": "The two cysteine residues in the chain form a single disulfide bond"}, {"label": "D", "text": "The α-carboxyl group at the C-terminus is amidated"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Edman degradation determines primary sequence by reacting phenylisothiocyanate with an uncharged, free N-terminal α-amino group, then cleaving that residue as a phenylthiohydantoin (PTH)-amino acid without disrupting the remaining peptide bonds; the cycle repeats to read the sequence from the N-terminus toward the C-terminus. The reaction therefore depends entirely on the N-terminal amine being available to attack the reagent. (Choice A) is correct: acetylation of the N-terminal α-amino group leaves no free amine for phenylisothiocyanate to react with, so no PTH-amino acid is generated in the first cycle at all, exactly the observed failure; the textbook notes Edman "will not work if the N-terminus has been chemically modified (e.g., by acetylation or formation of pyroglutamic acid)." (Choice B) is incorrect: the length limit (~50–60 residues) caps how many cycles can be read reliably because derivatization is incomplete over many rounds, but at 40 residues the chain is within range and, more importantly, length would never prevent the first residue from being released. (Choice C) is incorrect: a disulfide bond makes it hard to assign disulfide positions and can complicate sequencing across the linkage, but it does not block the free N-terminal amine, so a first PTH-amino acid would still be produced. (Choice D) is incorrect: Edman degradation proceeds from the N-terminus, so a modification of the C-terminal α-carboxyl group is irrelevant to the first cycle; this choice confuses the direction in which Edman chemistry reads the chain. This is a Scientific Reasoning and Problem Solving question because you must apply the mechanism of N-terminal Edman chemistry to a novel experimental failure and infer which structural feature blocks the first sequencing cycle.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '1528fdcc-1d62-4484-ac59-bab7f1d2b936';
DELETE FROM question_distractor_metadata WHERE question_id = '1528fdcc-1d62-4484-ac59-bab7f1d2b936';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('1528fdcc-1d62-4484-ac59-bab7f1d2b936', 'B', 'misconception', 'applies a real length limit to the wrong symptom (first-cycle failure vs. how far sequencing can proceed)'),
  ('1528fdcc-1d62-4484-ac59-bab7f1d2b936', 'C', 'partial_truth', 'cites a genuine Edman limitation (disulfides) that does not block the N-terminal reaction'),
  ('1528fdcc-1d62-4484-ac59-bab7f1d2b936', 'D', 'reversed_relationship', 'confuses N-terminal vs C-terminal directionality of Edman chemistry');

-- [Hydrophobicity & Unique Residues] reengineer ans=A hard skill2
UPDATE questions SET
  question_text = 'A researcher analyzes a water-soluble globular protein and uses the Kyte-Doolittle hydropathy scale, on which positive values indicate hydrophobic side chains and negative values indicate hydrophilic ones (Phe +2.8, Leu +3.8, Trp -0.9, Tyr -1.3). She notices that one aromatic residue — despite being routinely grouped with the "nonpolar aromatic" amino acids in introductory classifications — is repeatedly found on the solvent-exposed surface rather than in the buried hydrophobic core. Which residue is she most likely describing?',
  options = '[{"label": "A", "text": "Tyrosine"}, {"label": "B", "text": "Phenylalanine"}, {"label": "C", "text": "Leucine"}, {"label": "D", "text": "Alanine"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' A residue''s placement in a folded, water-soluble protein tracks its position on a hydropathy scale: a continuous stretch of high average hydrophobicity (positive Kyte-Doolittle values) tends to be buried in the interior away from water, while low-hydrophobicity (negative) residues tend to sit at the solvent-exposed surface (libretexts-biochemistry.txt lines 5367-5369). The textbook explicitly notes that although the aromatic amino acids are often labeled nonpolar, the Kyte-Doolittle scale actually shows that "the two large aromatic tyrosine and tryptophan... are more polar than nonpolar" (lines 5363-5365), a discrepancy driven for tyrosine by its ring hydroxyl, which "increases its reactivity and solubility compared to phenylalanine" (lines 5255-5256). (Choice A) is correct: tyrosine is an aromatic amino acid commonly grouped as nonpolar, yet its Kyte-Doolittle value is negative (-1.3), so it behaves as hydrophilic and is favored at the water-exposed surface rather than the buried core. (Choice B) is incorrect: phenylalanine is aromatic but its side chain is an unsubstituted benzene ring with a strongly positive Kyte-Doolittle value (+2.8), so it is genuinely hydrophobic and is preferentially buried in the core — it is not the mislabeled residue. (Choice C) is incorrect: leucine has the highest hydrophobicity of these options (+3.8) and is a classic core-forming residue, and it is aliphatic rather than aromatic, so it does not fit the "aromatic residue" description at all. (Choice D) is incorrect: alanine has a small nonpolar methyl side chain with a modestly positive value (+1.8); it is neither aromatic nor unexpectedly surface-seeking, so it is not the residue whose classification is misleading. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between hydropathy values and residue burial to recognize that an aromatic side chain with a negative Kyte-Doolittle value behaves as hydrophilic and localizes to the protein surface.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '972bcc49-2349-4f89-8494-a2fb635c8ef4';
DELETE FROM question_distractor_metadata WHERE question_id = '972bcc49-2349-4f89-8494-a2fb635c8ef4';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('972bcc49-2349-4f89-8494-a2fb635c8ef4', 'B', 'misconception', 'assumes all aromatic residues are equally hydrophobic and buried'),
  ('972bcc49-2349-4f89-8494-a2fb635c8ef4', 'C', 'adjacent_fact', 'picks the most hydrophobic residue as the ''surprising'' one, ignoring the aromatic requirement'),
  ('972bcc49-2349-4f89-8494-a2fb635c8ef4', 'D', 'partial_truth', 'recognizes a nonpolar residue but it is neither aromatic nor surface-seeking');

-- [Conjugated Proteins & Denaturation] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'A single-chain enzyme is unfolded by incubation in 8 M urea, which disrupts the noncovalent interactions that stabilize its folded shape. When the urea is later removed by dialysis, the enzyme spontaneously refolds and recovers full catalytic activity, even though no other proteins are added and its amino acid sequence never changes. This result most strongly supports which conclusion about the enzyme''s three-dimensional structure?',
  options = '[{"label": "A", "text": "The native fold is dictated by the protein''s amino acid sequence."}, {"label": "B", "text": "The native fold requires peptide bonds to be broken and reformed."}, {"label": "C", "text": "The native fold depends on chaperone proteins supplied during refolding."}, {"label": "D", "text": "The native fold is held together mainly by covalent bonds between distant residues."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Denaturation disrupts the noncovalent interactions and higher-order structure that give a protein its native fold, but it leaves the covalent peptide backbone (the amino acid sequence) intact. In Anfinsen''s classic experiment, a denatured single-chain protein that spontaneously refolds and regains activity once the denaturant is removed demonstrates that "all the necessary and sufficient information required to direct the folding of a protein into the native state is present in the primary sequence" (LibreTexts Biochemistry, lines 13813-13814). (Choice A) is correct: because the enzyme refolds spontaneously to its active shape with an unchanged sequence and no external machinery, the fold must be encoded by the sequence itself, exactly the inference Anfinsen drew from reversible denaturation/renaturation (LibreTexts Biochemistry, lines 13813-13833). (Choice B) is incorrect: denaturation and refolding disrupt and re-form noncovalent interactions, not the covalent peptide bonds; the backbone sequence "never changes," so peptide bonds are neither broken nor reformed during folding. (Choice C) is incorrect: while chaperones assist folding in vivo, this in vitro experiment adds no other proteins, so spontaneous recovery of activity shows the sequence alone suffices under these conditions (LibreTexts Biochemistry, lines 13847-13849). (Choice D) is incorrect: the fold is stabilized chiefly by noncovalent interactions and the hydrophobic effect, described as "the main thermodynamic driving force" for burying nonpolar residues (LibreTexts Biochemistry, line 4751), rather than by covalent bonds linking distant residues. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that denaturation disrupts noncovalent higher-order structure while preserving the primary sequence to infer, from a described reversible-refolding experiment, that the amino acid sequence determines the native fold.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '9a584f44-5e1a-4859-9510-668906f8953b';
DELETE FROM question_distractor_metadata WHERE question_id = '9a584f44-5e1a-4859-9510-668906f8953b';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('9a584f44-5e1a-4859-9510-668906f8953b', 'B', 'misconception', 'confuses denaturation with breaking covalent peptide bonds'),
  ('9a584f44-5e1a-4859-9510-668906f8953b', 'C', 'misconception', 'assumes folding always requires chaperones'),
  ('9a584f44-5e1a-4859-9510-668906f8953b', 'D', 'misconception', 'attributes fold stability to covalent rather than noncovalent interactions');

-- [Hydrophobicity & Unique Residues] reengineer ans=A hard skill2
UPDATE questions SET
  question_text = 'A typical aspartate side chain exposed to solvent on a protein''s surface has a carboxyl pKa near 4. In one enzyme, however, an aspartate residue packed into the protein''s hydrophobic core is measured to have a pKa near 9, meaning it stays protonated (neutral) across most of the physiological pH range. Which effect of the nonpolar microenvironment best explains this elevated pKa?

A. The nonpolar surroundings destabilize the negatively charged carboxylate, favoring the neutral protonated form.
B. The nonpolar surroundings stabilize the negatively charged carboxylate, favoring the deprotonated form.
C. The nonpolar surroundings physically block water from reaching and deprotonating the side chain.
D. The nonpolar surroundings lower the local pH, keeping the side chain protonated.',
  options = '[{"label": "A", "text": "The nonpolar surroundings destabilize the negatively charged carboxylate, favoring the neutral protonated form."}, {"label": "B", "text": "The nonpolar surroundings stabilize the negatively charged carboxylate, favoring the deprotonated form."}, {"label": "C", "text": "The nonpolar surroundings physically block water from reaching and deprotonating the side chain."}, {"label": "D", "text": "The nonpolar surroundings lower the local pH, keeping the side chain protonated."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The pKa of an ionizable side chain is not fixed; it depends on the microenvironment, because the environment determines how stable the charged (deprotonated) form is relative to the neutral (protonated) form. A carboxyl group deprotonates readily when water and nearby polar or positively charged groups can stabilize the resulting negative charge, but a hydrophobic core offers none of that stabilization. (Choice A) is correct: buried among nonpolar groups, the aspartate carboxylate has no polar solvent or counter-charge to stabilize its negative charge, so the deprotonated \(-\text{COO}^-\) form is energetically unfavorable and the neutral \(-\text{COOH}\) form is favored; making a group harder to deprotonate raises its pKa, exactly as the textbook describes for a buried Asp whose pKa is elevated to about 9. (Choice B) is incorrect: this reverses the effect. A nonpolar environment cannot stabilize a full negative charge (it lacks the polar or ionic partners that do so), and stabilizing the deprotonated form would instead lower the pKa, not raise it. (Choice C) is incorrect: a shifted pKa is a thermodynamic property reflecting the relative stability of the two protonation states, not a kinetic barrier; the core does not work by mechanically shielding the proton from water, and burial does not prevent proton exchange. (Choice D) is incorrect: pH is a bulk property of the aqueous solution, not something a patch of nonpolar side chains sets to a different value; the microenvironment shifts the residue''s pKa, but it does not create a local pH. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that a hydrophobic microenvironment destabilizes a charged side chain, and reason that favoring the neutral protonated form raises the measured pKa.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'cfe53a9a-ebd4-4433-9aa0-735ca9249c72';
DELETE FROM question_distractor_metadata WHERE question_id = 'cfe53a9a-ebd4-4433-9aa0-735ca9249c72';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('cfe53a9a-ebd4-4433-9aa0-735ca9249c72', 'B', 'reversed_relationship', 'flips the direction of charge stabilization, so it predicts a lowered rather than raised pKa'),
  ('cfe53a9a-ebd4-4433-9aa0-735ca9249c72', 'C', 'misconception', 'treats a thermodynamic pKa shift as a kinetic/steric barrier to deprotonation'),
  ('cfe53a9a-ebd4-4433-9aa0-735ca9249c72', 'D', 'misconception', 'confuses microenvironment polarity with a local change in bulk-solution pH');

-- [Zwitterions & Titration Curves] reengineer ans=A medium skill2
UPDATE questions SET
  question_text = 'Glutamate has three ionizable groups: the \(\alpha\text{-COOH}\) (\(\text{pK}_a = 2.2\)), the side-chain \(\gamma\text{-COOH}\) (\(\text{pK}_a = 4.25\)), and the \(\alpha\text{-NH}_3^+\) (\(\text{pK}_a = 9.7\)). A biochemist dissolves free glutamate in a buffer held at physiological \(\text{pH} = 7.4\). What is the net charge on the predominant form of glutamate under these conditions?',
  options = '[{"label": "A", "text": "\\(-1\\)"}, {"label": "B", "text": "\\(0\\)"}, {"label": "C", "text": "\\(-2\\)"}, {"label": "D", "text": "\\(+1\\)"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The net charge on an amino acid at a given pH is found by evaluating each ionizable group against its \(\text{pK}_a\): when the pH is above a group''s \(\text{pK}_a\) the group is deprotonated, and when the pH is below its \(\text{pK}_a\) the group is protonated (LibreTexts states that at pH two units above the \(\text{pK}_a\) a group is ~99% deprotonated, and two units below it is ~99% protonated, lines 5505-5510). Carboxyl groups carry \(0\) charge when protonated and \(-1\) when deprotonated, whereas the \(\alpha\)-amino group carries \(+1\) when protonated and \(0\) when deprotonated (lines 5485-5486, 5561). At \(\text{pH} = 7.4\): both the \(\alpha\text{-COOH}\) (\(\text{pK}_a = 2.2\)) and the side-chain \(\gamma\text{-COOH}\) (\(\text{pK}_a = 4.25\)) are well above their \(\text{pK}_a\) values, so both are deprotonated at \(-1\) each; the \(\alpha\text{-NH}_3^+\) (\(\text{pK}_a = 9.7\)) is below its \(\text{pK}_a\), so it stays protonated at \(+1\). (Choice A) is correct: summing the charges gives \(-1 + (-1) + (+1) = -1\). (Choice B) \(0\) is incorrect: this treats glutamate as a simple neutral zwitterion, ignoring that its acidic side-chain carboxyl is deprotonated (\(-1\)) at pH 7.4; only amino acids without a charged R-group are net-neutral at their \(\text{pI}\). (Choice C) \(-2\) is incorrect: this deprotonates all three groups, but pH 7.4 is more than two units below the amino \(\text{pK}_a\) of 9.7, so the \(\alpha\)-amino group remains protonated at \(+1\) and is not removed. (Choice D) \(+1\) is incorrect: this counts only the protonated amino group and overlooks that both carboxyls are deprotonated at this pH, each contributing \(-1\). This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between pH and \(\text{pK}_a\) to each of the three ionizable groups and sum their individual charges to predict the net charge.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '42419bb7-8672-40fe-95cc-4455cbb73a87';
DELETE FROM question_distractor_metadata WHERE question_id = '42419bb7-8672-40fe-95cc-4455cbb73a87';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('42419bb7-8672-40fe-95cc-4455cbb73a87', 'B', 'misconception', 'treats amino acid as neutral zwitterion and ignores charged acidic side chain'),
  ('42419bb7-8672-40fe-95cc-4455cbb73a87', 'C', 'misconception', 'deprotonates the alpha-amino group at neutral pH, misapplying the pH-vs-pKa rule'),
  ('42419bb7-8672-40fe-95cc-4455cbb73a87', 'D', 'misconception', 'counts only the amino group and forgets both carboxyls deprotonate above their pKa');

-- [Peptide Bond Formation & Hydrolysis] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher chemically links 15 free amino acids into a single, unbranched linear peptide. Assuming each linkage forms by the same reaction that joins amino acids in a protein, how many water molecules are released during the synthesis of this peptide?',
  options = '[{"label": "A", "text": "14"}, {"label": "B", "text": "15"}, {"label": "C", "text": "16"}, {"label": "D", "text": "30"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Amino acids are joined into peptides by dehydration synthesis (condensation): the amine of one amino acid attacks the carbonyl carbon of another''s carboxyl group, forming an amide (peptide) bond and releasing one molecule of water per bond, as the textbook states that in forming the amide link "water is released." In an unbranched chain of \(n\) residues, the residues are connected in a single line, so the number of peptide bonds is \(n-1\); each of those bonds releases exactly one water molecule. (Choice A) is correct: 15 residues joined in a line require \(15-1=14\) peptide bonds, and because each bond formation releases one water, 14 water molecules are released. (Choice B) is incorrect: counting one water per residue (15) rather than one water per bond ignores that a linear chain of 15 residues has only 14 linkages, since the two terminal residues each participate in one bond, not two. (Choice C) is incorrect: 16 would count one more linkage than exists, as if the chain were cyclized (joining the ends adds a bond) or as if there were one bond per residue plus an extra; the peptide here is linear and unbranched, so no closing bond forms. (Choice D) is incorrect: doubling to 30 treats each peptide bond as though it released two waters, but the condensation of a carboxyl and an amine group releases only a single water per amide bond formed. This is a Scientific Reasoning and Problem Solving question because you must apply the dehydration-synthesis mechanism of peptide bond formation to determine that a linear chain of \(n\) amino acids forms \(n-1\) bonds and therefore releases \(n-1\) water molecules.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'd5db305f-d6ac-4e59-9fc1-d0b62ae1dfd4';
DELETE FROM question_distractor_metadata WHERE question_id = 'd5db305f-d6ac-4e59-9fc1-d0b62ae1dfd4';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d5db305f-d6ac-4e59-9fc1-d0b62ae1dfd4', 'B', 'misconception', 'off-by-one: counts one water per residue instead of per bond'),
  ('d5db305f-d6ac-4e59-9fc1-d0b62ae1dfd4', 'C', 'misconception', 'treats linear chain as cyclic / adds an extra linkage'),
  ('d5db305f-d6ac-4e59-9fc1-d0b62ae1dfd4', 'D', 'misconception', 'double-counts water per amide bond');

-- [Primary Structure] reengineer ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher synthesizes the linear pentapeptide Ala-Gly-Val-Leu-Phe, drawn in the conventional N-to-C direction. None of the five side chains in this peptide contains an ionizable group. Considering only the backbone \(\alpha\)-amino and \(\alpha\)-carboxyl groups, how many of them can gain or lose a proton to carry a charge at an appropriate pH?',
  options = '[{"label": "A", "text": "2 groups"}, {"label": "B", "text": "4 groups"}, {"label": "C", "text": "5 groups"}, {"label": "D", "text": "10 groups"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' In a polypeptide, each peptide bond ties up the \(\alpha\)-carboxyl group of one residue and the \(\alpha\)-amino group of the next residue in an amide linkage; the textbook states that "when the amino acids are linked by peptide bonds (amide link), the alpha N and the carboxyl C are in an amide link and are not charged," and that only "the amino group of the N-terminal amino acid and the carboxyl group of the C-terminal amino acid of a protein may be charged" (LibreTexts 3.1.10). Because every internal \(\alpha\)-group is locked in a peptide bond, only the free \(\alpha\)-amino group at the N-terminus and the free \(\alpha\)-carboxyl group at the C-terminus remain ionizable. (Choice A) is correct: with no ionizable side chains, the only backbone groups that can carry charge are the single free N-terminal \(\alpha\)-amino group and the single free C-terminal \(\alpha\)-carboxyl group, for a total of 2. (Choice B) is incorrect: counting the four internal \(\alpha\)-groups (or the four amide nitrogens) treats peptide-bonded backbone groups as titratable, but those \(\alpha\)-N and \(\alpha\)-C atoms are consumed in amide bonds and cannot gain or lose a proton. (Choice C) is incorrect: assigning one ionizable backbone group per residue ignores that in a chain of five residues four \(\alpha\)-amino and four \(\alpha\)-carboxyl groups are already committed to the four peptide bonds. (Choice D) is incorrect: this counts both the \(\alpha\)-amino and \(\alpha\)-carboxyl group of all five residues as free, which is only true for isolated amino acids; peptide bond formation removes all but the two terminal groups from the pool of ionizable backbone groups. This is a Scientific Reasoning and Problem Solving question because you must apply the fact that peptide bonds convert internal \(\alpha\)-amino and \(\alpha\)-carboxyl groups into non-ionizable amide linkages to determine how many backbone groups remain titratable in a specific peptide.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '6053e3f1-a02f-4e83-9295-ef57e07187cb';
DELETE FROM question_distractor_metadata WHERE question_id = '6053e3f1-a02f-4e83-9295-ef57e07187cb';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6053e3f1-a02f-4e83-9295-ef57e07187cb', 'B', 'misconception', 'treats internal backbone groups as titratable'),
  ('6053e3f1-a02f-4e83-9295-ef57e07187cb', 'C', 'misconception', 'one ionizable group per residue'),
  ('6053e3f1-a02f-4e83-9295-ef57e07187cb', 'D', 'misconception', 'applies free-amino-acid charge count to a peptide');

-- [Zwitterions & Titration Curves] reengineer ans=A hard skill2
UPDATE questions SET
  question_text = 'A biochemist titrates glutamate, an amino acid whose carboxylic acid side chain adds a third ionizable group. The three pK_a values are listed below.

| Ionizable group | \(\text{pK}_a\) |
|---|---|
| \(\alpha\text{-COOH}\) | 2.2 |
| side-chain \(\gamma\text{-COOH}\) | 4.2 |
| \(\alpha\text{-NH}_3^+\) | 9.7 |

As base is added, the molecule passes through a species that carries a net charge of zero (the zwitterion). What is the isoelectric point (\(\text{pI}\)) of glutamate?',
  options = '[{"label": "A", "text": "3.2"}, {"label": "B", "text": "5.4"}, {"label": "C", "text": "6.0"}, {"label": "D", "text": "7.0"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' The isoelectric point is the pH at which the molecule carries no net charge; for a molecule with more than two ionizable groups it is found not by averaging the extreme or all pK_a values, but by averaging the two pK_a values that flank the net-zero (zwitterionic) species. To locate that species you track the charge as pH rises: at very low pH glutamate is fully protonated with net charge \(+1\) (both carboxyls neutral, amino group \(+1\)); deprotonating the \(\alpha\text{-COOH}\) (pK_a 2.2) gives net \(0\); deprotonating the side-chain \(\gamma\text{-COOH}\) (pK_a 4.2) gives net \(-1\); and deprotonating the \(\alpha\text{-NH}_3^+\) (pK_a 9.7) gives net \(-2\). The zwitterion therefore sits between pK_a 2.2 and pK_a 4.2, so \(\text{pI} = (2.2 + 4.2)/2 = 3.2\). (Choice A) is correct: 3.2 averages the two lowest pK_a values, which are the ones flanking the net-zero form of an acidic amino acid. (Choice B) is incorrect: 5.4 comes from averaging all three pK_a values, \((2.2 + 4.2 + 9.7)/3\), but the pI is defined only by the two that bracket the neutral species. (Choice C) is incorrect: 6.0 comes from averaging the two extreme values, \((2.2 + 9.7)/2\), the correct method for a simple amino acid with no ionizable side chain but wrong here because it skips the acidic \(\gamma\)-carboxyl and lands on a pH where the molecule is net \(-1\). (Choice D) is incorrect: 7.0 comes from averaging the two highest values, \((4.2 + 9.7)/2\); those pK_a values flank the transition from \(-1\) to \(-2\), not the net-zero species, so they give the wrong pH. This is a Scientific Reasoning and Problem Solving question because you must apply the definition of the isoelectric point to a triprotic amino acid, track its net charge through each deprotonation, and identify the correct pair of pK_a values to average rather than defaulting to a memorized two-value formula.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '77c9dedc-f49d-4b12-9c6a-c9ef5b066faf';
DELETE FROM question_distractor_metadata WHERE question_id = '77c9dedc-f49d-4b12-9c6a-c9ef5b066faf';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('77c9dedc-f49d-4b12-9c6a-c9ef5b066faf', 'B', 'misconception', 'average-all-pKa'),
  ('77c9dedc-f49d-4b12-9c6a-c9ef5b066faf', 'C', 'misconception', 'two-value-formula-ignores-side-chain'),
  ('77c9dedc-f49d-4b12-9c6a-c9ef5b066faf', 'D', 'reversed_relationship', 'wrong-flanking-pair');

-- [Primary Structure] SCOPE-REPLACE ans=A medium skill2
UPDATE questions SET
  question_text = 'A tetrapeptide is written in standard convention as Val–Thr–Cys–Arg. Which residue retains a free α-amino group that is not incorporated into a peptide bond?',
  options = '[{"label": "A", "text": "Valine"}, {"label": "B", "text": "Threonine"}, {"label": "C", "text": "Cysteine"}, {"label": "D", "text": "Arginine"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' By convention, a protein''s primary structure is written from the N-terminus to the C-terminus, so the leftmost residue in a sequence is the amino-terminal residue. Each peptide bond is an amide link formed between the α-carboxyl group of one residue and the α-amino group of the next; consequently, every residue''s α-amino group is consumed in a peptide bond except that of the very first residue, whose α-amino group remains free. (Choice A) is correct: valine is written first, marking it as the N-terminal residue, and only its α-amino group is not tied up in a peptide bond. (Choice B) is incorrect: threonine is the second residue, so its α-amino group forms the amide bond with valine''s α-carboxyl and is therefore not free. (Choice C) is incorrect: cysteine is an internal residue whose α-amino group is bonded to threonine''s carbonyl; a free α-amino group cannot appear in the interior of a chain. (Choice D) is incorrect: arginine is the C-terminal residue, so it retains a free α-carboxyl group, not a free α-amino group — a free α-amino group is a property of the N-terminus, and arginine''s nitrogen-rich guanidino side chain does not change which α-group is free. This is a Scientific Reasoning and Problem Solving question because you must apply the N-to-C writing convention and the mechanism of peptide-bond formation to deduce which single residue''s α-amino group escapes incorporation into an amide linkage.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '1cadec9c-8372-415c-a06c-b4067208d2ce';
DELETE FROM question_distractor_metadata WHERE question_id = '1cadec9c-8372-415c-a06c-b4067208d2ce';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('1cadec9c-8372-415c-a06c-b4067208d2ce', 'B', 'misconception', 'internal residue mistaken for having a free terminal group'),
  ('1cadec9c-8372-415c-a06c-b4067208d2ce', 'C', 'misconception', 'internal residue mistaken for having a free terminal group'),
  ('1cadec9c-8372-415c-a06c-b4067208d2ce', 'D', 'reversed_relationship', 'C-terminus confused with N-terminus / side-chain nitrogen mistaken for free alpha-amino');

-- [Secondary Structure (α-helix & β-sheet)] reengineer ans=C hard skill2
UPDATE questions SET
  question_text = 'A researcher studies a 21-residue segment of a membrane-associated protein. Charting the sequence, she finds that nonpolar residues occur at positions 1, 4, 8, 11, 15, and 18, while charged and polar residues occupy the intervening positions. When the segment folds, the nonpolar side chains all cluster along a single continuous longitudinal face of the folded segment, leaving the opposite face polar. Which secondary structure best accounts for this segregation of nonpolar side chains onto one face?',
  options = '[{"label": "A", "text": "A parallel \\(\\beta\\)-pleated sheet"}, {"label": "B", "text": "A random coil"}, {"label": "C", "text": "An \\(\\alpha\\)-helix"}, {"label": "D", "text": "A collagen triple helix"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Because the textbook notes an \(\alpha\)-helix has about 3.6 residues per turn (\(n = 3.6\)), residues spaced roughly three to four apart in the sequence end up rotated back onto nearly the same side of the helix; when hydrophobic residues recur at that spacing they collect on one longitudinal face, producing an amphipathic helix with "hydrophilic residues... on one side of the helix and hydrophobic residues on the other." Here the nonpolar residues sit at positions 1, 4, 8, 11, 15, 18 — a repeat of about 3.5 residues — exactly the periodicity that maps them onto a single face of a 3.6-residue-per-turn coil. (Choice A) is incorrect: in a \(\beta\)-strand successive side chains alternate to opposite faces, so an amphipathic \(\beta\)-strand shows a two-residue (i, i+2) hydrophobic repeat, not the ~3.5-residue repeat described here. (Choice B) is incorrect: a random coil lacks a regular repeating backbone geometry, so it cannot systematically project a defined set of positions onto one continuous face. (Choice C) is correct: only a coil with ~3.6 residues per turn converts a ~3.5-residue sequence periodicity into a single hydrophobic face. (Choice D) is incorrect: the collagen triple helix is a rope of three separate polyproline-II-like strands whose defining feature is a Gly-X-Y repeat and interchain packing, not the segregation of one strand''s side chains onto a hydrophobic face. This is a Scientific Reasoning and Problem Solving question because you must apply the ~3.6-residue-per-turn geometry of secondary structures to a sequence periodicity in order to infer which structure places the nonpolar side chains on one face.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '3c0fe327-9ef4-4d56-9f3a-7c31aba085c7';
DELETE FROM question_distractor_metadata WHERE question_id = '3c0fe327-9ef4-4d56-9f3a-7c31aba085c7';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('3c0fe327-9ef4-4d56-9f3a-7c31aba085c7', 'A', 'misconception', 'confuses helix periodicity with beta-strand alternation'),
  ('3c0fe327-9ef4-4d56-9f3a-7c31aba085c7', 'B', 'misconception', 'believes side-chain segregation needs no regular backbone geometry'),
  ('3c0fe327-9ef4-4d56-9f3a-7c31aba085c7', 'D', 'adjacent_fact', 'recognizes ''helix'' keyword but ignores triple-strand Gly-X-Y definition');

-- [Quaternary Structure & Cooperativity] reengineer ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher compares two oxygen-carrying proteins from the same organism. Protein X is a single polypeptide with one heme site and gives a hyperbolic oxygen-saturation curve. Protein Y is an assembly of four subunits, each with one heme site, and gives a sigmoidal oxygen-saturation curve that rises steeply over a narrow range of oxygen pressures. Which statement best accounts for the sigmoidal curve observed for Protein Y?',
  options = '[{"label": "A", "text": "Binding of oxygen at one subunit raises the oxygen affinity of the remaining subunits"}, {"label": "B", "text": "Each subunit binds oxygen with an identical, unchanging affinity independent of the others"}, {"label": "C", "text": "Oxygen must occupy all four subunits simultaneously before any binding can be measured"}, {"label": "D", "text": "Binding of oxygen at one subunit lowers the oxygen affinity of the remaining subunits"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' A sigmoidal oxygen-binding curve is the signature of positive cooperativity in a multi-subunit protein: the textbook states that for hemoglobin, plots of fractional saturation versus oxygen pressure are ''sigmoidal for Hb, suggesting cooperative binding of oxygen to Hb (binding of the first oxygen facilitates binding of the second, etc)'' (line 20392), and that ''the binding of one oxygen molecule increases the affinity of the remaining sites (homotropic allosterism)'' (line 20980). A single-site monomer like myoglobin cannot show this behavior and instead gives a hyperbolic curve. (Choice A) is correct: cooperativity means that oxygen binding at one subunit shifts the tetramer toward a higher-affinity conformation, so the remaining subunits bind more readily — this produces the steep, sigmoidal rise. (Choice B) is incorrect: if every subunit bound with a fixed, independent affinity, the curve would be hyperbolic like Protein X''s, not sigmoidal, so identical unchanging affinity cannot explain the sigmoid. (Choice C) is incorrect: cooperativity does not require all four sites to fill simultaneously; oxygens bind sequentially, and partially saturated intermediates are measurable — an all-or-none requirement describes a hypothetical limit, not the graded sigmoidal binding seen here. (Choice D) is incorrect: if binding at one subunit lowered the affinity of the others (negative cooperativity), the remaining sites would resist further binding and the curve would flatten early rather than steepen, which does not match a sigmoidal curve. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between quaternary structure, cooperative binding, and curve shape to infer the mechanism behind an observed sigmoidal binding curve.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '4e561080-1af0-495a-ac2b-20214250af80';
DELETE FROM question_distractor_metadata WHERE question_id = '4e561080-1af0-495a-ac2b-20214250af80';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4e561080-1af0-495a-ac2b-20214250af80', 'B', 'misconception', 'confuses independent binding (hyperbolic) with cooperative binding (sigmoidal)'),
  ('4e561080-1af0-495a-ac2b-20214250af80', 'C', 'misconception', 'treats cooperativity as all-or-none simultaneous occupancy rather than graded sequential binding'),
  ('4e561080-1af0-495a-ac2b-20214250af80', 'D', 'reversed_relationship', 'attributes sigmoidal curve to negative cooperativity instead of positive cooperativity');

-- [Tertiary Structure & Folding] reengineer ans=A hard skill2
UPDATE questions SET
  question_text = 'A soluble globular enzyme buries a valine residue deep in its water-excluded core, packed against other nonpolar side chains. Using site-directed mutagenesis, a researcher replaces this buried valine with glutamate, whose side chain is negatively charged at physiological pH. The mutant enzyme folds but unfolds at a markedly lower temperature than the wild type, indicating a less stable tertiary structure. Which factor best accounts for the mutant''s reduced stability?',
  options = '[{"label": "A", "text": "Placing the charged glutamate side chain in the nonpolar interior is energetically costly and weakens the hydrophobic packing of the core."}, {"label": "B", "text": "The glutamate side chain forms a disulfide crosslink with a neighboring residue that distorts the folded core."}, {"label": "C", "text": "The substitution breaks a backbone amide-to-carbonyl hydrogen bond that defined the local secondary structure."}, {"label": "D", "text": "The added surface charge raises the enzyme''s solubility, and greater solubility drives the polypeptide to unfold."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Tertiary structure is the overall 3D shape of a single polypeptide, and its dominant stabilizing force is the hydrophobic effect: nonpolar R groups are buried in a water-excluded interior while polar and charged R groups face the solvent. LibreTexts notes that nonpolar side chains such as Val, Leu, Ile, Met, and Phe are ''predominantly (83%) in the protein''s interior'' and that the hydrophobic effect is ''the main thermodynamic driving force'' for folding; it also cites staphylococcal nuclease mutants in which a buried Val is changed to a charged residue, imposing an energetic penalty for dehydrating and burying that charge. (Choice A) is correct: forcing a charged glutamate into the nonpolar, water-excluded core is energetically unfavorable because the charge is stripped of its stabilizing hydration and no longer participates in favorable hydrophobic packing, so the fold is destabilized and melts at a lower temperature. (Choice B) is incorrect: only cysteine thiols are oxidized to disulfide crosslinks; a glutamate carboxylate cannot form an -S-S- bond, so no new covalent crosslink is created. (Choice C) is incorrect: backbone amide-to-carbonyl hydrogen bonds define secondary structure and depend on main-chain atoms, which are unchanged by swapping one side chain for another, so this force is not what is lost. (Choice D) is incorrect: proteins are least soluble near their isoelectric point and adding charge can raise solubility, but greater solubility does not itself unfold a protein, and the destabilizing residue here is buried in the core rather than exposed on the surface. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that the hydrophobic effect stabilizes tertiary structure to predict why burying a charged side chain in the core destabilizes the fold.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'd34f18b3-ddb8-468f-8477-ab896ffd6dbb';
DELETE FROM question_distractor_metadata WHERE question_id = 'd34f18b3-ddb8-468f-8477-ab896ffd6dbb';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d34f18b3-ddb8-468f-8477-ab896ffd6dbb', 'B', 'misconception', 'wrong-side-chain-chemistry'),
  ('d34f18b3-ddb8-468f-8477-ab896ffd6dbb', 'C', 'adjacent_fact', 'secondary-vs-tertiary-confusion'),
  ('d34f18b3-ddb8-468f-8477-ab896ffd6dbb', 'D', 'reversed_relationship', 'solubility-stability-conflation');

-- [Side-Chain Classification] reengineer ans=B medium skill2
UPDATE questions SET
  question_text = 'Cysteine and methionine are the two amino acids whose R-groups contain a sulfur atom. A student must assign each residue to one of the standard side-chain classes (nonpolar, polar uncharged, acidic, or basic). Which statement correctly describes how each is classified and why?',
  options = '[{"label": "A", "text": "Both are polar uncharged, because any side chain containing a sulfur heteroatom is hydrophilic."}, {"label": "B", "text": "Cysteine is polar uncharged and methionine is nonpolar, because only the sulfhydryl group forms a permanent dipole."}, {"label": "C", "text": "Methionine is polar uncharged and cysteine is nonpolar, because the thioether sulfur is the more electronegative group."}, {"label": "D", "text": "Both are nonpolar, because sulfur-containing side chains are too weakly polar to be hydrophilic."}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Side chains are sorted into nonpolar, polar uncharged, acidic, or basic classes not by which atoms they contain but by the property those atoms actually confer: the polar uncharged class is defined by heteroatoms (O, S, or N) that form a permanent dipole within the R-group, whereas a side chain whose heteroatom does not create such a dipole stays nonpolar. The two sulfur residues sit on opposite sides of this line: cysteine''s free sulfhydryl (\(-\text{SH}\)) forms a permanent dipole, but methionine''s terminal thioether \"generally cannot form a permanent dipole within the molecule and retains low solubility,\" so methionine \"is usually classified as a nonpolar, hydrophobic amino acid\" (LibreTexts Biochemistry, lines 5257-5258). (Choice A) is incorrect: it assumes that merely containing a sulfur heteroatom makes a side chain hydrophilic, but classification depends on whether that heteroatom forms a permanent dipole, which methionine''s thioether does not. (Choice B) is correct: cysteine''s sulfhydryl forms a permanent dipole and places it in the polar uncharged class alongside serine and threonine (lines 5262-5263), while methionine''s dipole-free thioether keeps it nonpolar. (Choice C) is incorrect: it reverses the two assignments, and no greater electronegativity of the thioether drives polarity — it is the sulfhydryl of cysteine, not the thioether of methionine, that produces the dipole. (Choice D) is incorrect: it overgeneralizes methionine''s nonpolar behavior to cysteine, ignoring that the free \(-\text{SH}\) of cysteine does form a permanent dipole and makes cysteine polar uncharged. This is a Scientific Reasoning and Problem Solving question because you must apply the permanent-dipole criterion for the polar uncharged class to two chemically similar residues and infer that identical elemental composition does not guarantee identical classification.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '76d5de93-0e32-4c0b-a1ad-a71245eaa6ba';
DELETE FROM question_distractor_metadata WHERE question_id = '76d5de93-0e32-4c0b-a1ad-a71245eaa6ba';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('76d5de93-0e32-4c0b-a1ad-a71245eaa6ba', 'A', 'misconception', 'presence of a heteroatom equals polarity'),
  ('76d5de93-0e32-4c0b-a1ad-a71245eaa6ba', 'C', 'reversed_relationship', 'swapped class assignments'),
  ('76d5de93-0e32-4c0b-a1ad-a71245eaa6ba', 'D', 'misconception', 'all sulfur side chains are nonpolar');

-- [Peptide Bond Formation & Hydrolysis] SCOPE-REPLACE ans=A hard skill2
UPDATE questions SET
  question_text = 'Two free amino acids are joined into a dipeptide. Before the reaction, only the carbonyl (C=O) oxygen of the N-terminal residue''s α-carboxyl group is labeled with the heavy isotope ¹⁸O; that carboxyl group''s hydroxyl (–OH) oxygen and every other oxygen in both amino acids are ordinary ¹⁶O. The N-terminal residue contributes the carboxyl carbon of the new peptide bond, and the C-terminal residue contributes the attacking α-amino group. After the peptide bond forms and the released water molecule is collected, is that water ¹⁸O-labeled, and why?',
  options = '[{"label": "A", "text": "No — the water contains only ¹⁶O, because the labeled carbonyl oxygen is retained in the new amide bond while the oxygen that leaves as water comes from the carboxyl group''s ¹⁶O hydroxyl"}, {"label": "B", "text": "Yes — the water is ¹⁸O-labeled, because the carbonyl oxygen leaves as part of the water while the hydroxyl oxygen is retained in the new amide bond"}, {"label": "C", "text": "No — the water contains only ¹⁶O, because its oxygen is supplied by the C-terminal residue''s amino group rather than by either oxygen of the N-terminal carboxyl group"}, {"label": "D", "text": "Yes — the water is ¹⁸O-labeled, because both oxygens of the N-terminal residue''s carboxyl group leave together as part of the single released water molecule"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' A peptide bond forms by dehydration synthesis: the α-amino nitrogen of one amino acid acts as a nucleophile and attacks the electrophilic carbonyl carbon of the other amino acid''s α-carboxyl group, and "in this reaction, water is released." In this nucleophilic acyl substitution the carbonyl carbon keeps its carbonyl oxygen, which becomes the C=O of the new amide bond, whereas the oxygen expelled as water is the carboxyl group''s hydroxyl (–OH) oxygen — the textbook notes this hydroxyl "must be activated to provide a better leaving group than OH−." Because only the retained carbonyl oxygen carries the ¹⁸O label and the departing hydroxyl oxygen is ¹⁶O, the collected water contains ordinary ¹⁶O. (Choice A) is correct: the labeled carbonyl oxygen stays behind in the amide bond, so the leaving-group oxygen that ends up in water is the unlabeled ¹⁶O hydroxyl oxygen, giving unlabeled water. (Choice B) is incorrect: it reverses the two carboxyl oxygens, claiming the carbonyl oxygen leaves and the hydroxyl is retained; in fact the carbonyl oxygen is retained in the amide and the hydroxyl oxygen departs, so the water is not ¹⁸O-labeled. (Choice C) is incorrect: amino groups contain no oxygen, so the water''s oxygen cannot come from the C-terminal residue''s amino group; the oxygen of the released water is always contributed by the carboxyl group. (Choice D) is incorrect: a single water molecule contains only one oxygen atom, and only one carboxyl oxygen (the hydroxyl) is lost — the carbonyl oxygen is retained — so both carboxyl oxygens do not leave together and the water is not ¹⁸O-labeled. This is a Scientific Reasoning and Problem Solving question because you must apply the nucleophile–electrophile mechanism of peptide bond formation to track which specific oxygen leaves as water in an isotope-labeling scenario.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '24758af0-ee86-48b3-bd36-e9357747a566';
DELETE FROM question_distractor_metadata WHERE question_id = '24758af0-ee86-48b3-bd36-e9357747a566';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('24758af0-ee86-48b3-bd36-e9357747a566', 'B', 'reversed_relationship', 'swaps which carboxyl oxygen (carbonyl vs. hydroxyl) is retained versus lost as water'),
  ('24758af0-ee86-48b3-bd36-e9357747a566', 'C', 'misconception', 'believes the released water''s oxygen comes from the oxygen-free amino group'),
  ('24758af0-ee86-48b3-bd36-e9357747a566', 'D', 'misconception', 'assumes both carboxyl oxygens leave together in the single released water molecule');

-- [Hydrophobicity & Unique Residues] reengineer ans=A medium skill2
UPDATE questions SET
  question_text = 'A structural biologist engineers a single proline substitution into the middle of an otherwise stable \(\alpha\)-helix and finds that the helix unwinds at that position, introducing a kink. Which property of proline best explains why it destabilizes the helix at this internal site?',
  options = '[{"label": "A", "text": "Its ring-bound nitrogen cannot donate the backbone hydrogen bond a helix requires"}, {"label": "B", "text": "Its bulky nonpolar side chain sterically collides with adjacent residue side chains"}, {"label": "C", "text": "Its positively charged side chain electrostatically repels neighboring backbone groups"}, {"label": "D", "text": "Its extra side-chain hydrogen bonds lock neighboring turns too tightly together"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' An \(\alpha\)-helix is held together by regular backbone hydrogen bonds between each residue''s amide N–H (donor) and a carbonyl oxygen four residues away (acceptor). Because proline''s side chain loops back and bonds to its own \(\alpha\)-amino nitrogen, that nitrogen sits in the ring as a secondary amine and lacks the free backbone N–H the helix needs; proline is also sterically locked into a limited backbone conformation, so it cannot adopt the helical geometry. (Choice A) is correct: the textbook states proline''s ring "R-group is unable to participate in H-bonding needed for helix stabilization, and also is sterically locked in one conformation" (LibreTexts 18851-18852), so the missing backbone hydrogen-bond donor is exactly what interrupts the helix. (Choice B) is incorrect: proline''s cyclic side chain is actually compact rather than bulky, and helix breakage arises from the lost backbone N–H and conformational rigidity, not from side-chain steric clashes with neighbors. (Choice C) is incorrect: proline is a nonpolar residue with an uncharged side chain (LibreTexts 5242-5245), so it carries no charge to electrostatically repel backbone groups. (Choice D) is incorrect: this reverses the true relationship—proline removes a backbone hydrogen-bond donor rather than adding side-chain hydrogen bonds, so it loosens rather than over-tightens the helix. This is a Scientific Reasoning and Problem Solving question because you must apply proline''s unique ring structure to predict its mechanistic effect on \(\alpha\)-helix hydrogen bonding in a novel substitution experiment.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '6d9b99b8-a57e-469c-9e60-9f2f23d76649';
DELETE FROM question_distractor_metadata WHERE question_id = '6d9b99b8-a57e-469c-9e60-9f2f23d76649';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6d9b99b8-a57e-469c-9e60-9f2f23d76649', 'B', 'misconception', 'attributes helix disruption to side-chain steric bulk rather than the missing backbone N-H'),
  ('6d9b99b8-a57e-469c-9e60-9f2f23d76649', 'C', 'misconception', 'treats proline as charged/polar when it is nonpolar and uncharged'),
  ('6d9b99b8-a57e-469c-9e60-9f2f23d76649', 'D', 'reversed_relationship', 'claims proline adds stabilizing H-bonds when it actually removes a backbone donor');

COMMIT;
