-- Biology Ch11: The Musculoskeletal System — REMEDIATED (quality + scope sweep); grounded in OpenStax A&P 2e
-- Remediated 24/24 flagged questions in place (UPDATE by id, ids preserved). 14 re-engineered, 10 scope-flagged.
-- distractor_category mapped to the question_distractor_metadata CHECK set. Idempotent; safe to re-run.

BEGIN;

-- [Cartilage & Ossification] ans=A medium skill2
UPDATE questions SET
  question_text = 'A collegiate soccer player tears the cartilage in her knee joint during a match. Her surgeon warns that this injury will heal far more slowly than the tibial bone fracture she suffered the previous season, even though both tissues are part of the skeletal system. Which structural feature of cartilage best accounts for its notably slow healing?',
  options = '[{"label": "A", "text": "Cartilage has no direct blood supply, so nutrients and repair materials must diffuse slowly through its matrix."}, {"label": "B", "text": "Cartilage matrix is hardened by mineral crystals, so new cells cannot penetrate it to remodel the tissue."}, {"label": "C", "text": "Cartilage contains no resident cells, so no cells remain on site to synthesize replacement matrix."}, {"label": "D", "text": "Cartilage is densely innervated, so pain signaling suppresses the local inflammatory repair response."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Cartilage is a connective tissue built from chondrocytes housed in lacunae and embedded in a matrix of chondroitin-sulfate proteoglycans, and unlike most connective tissues it carries no blood vessels of its own. Because the tissue is avascular, every nutrient and repair material must travel by diffusion through the dense matrix to reach the chondrocytes, and the textbook identifies this as the factor behind the very slow healing of cartilage (lines 6987-6989). (Choice A) is correct: cartilage is avascular, so nutrients and the substances needed for repair must diffuse across the matrix rather than being delivered directly by capillaries, which is precisely why it heals so slowly compared with well-vascularized bone. (Choice B) is incorrect: it describes bone, whose matrix is hardened by calcium mineral crystals; cartilage matrix is a flexible proteoglycan gel, not a mineralized solid, so hardness is not the barrier to healing (lines 6984-6985). (Choice C) is incorrect: cartilage is not acellular—living chondrocytes reside within the lacunae of the matrix; the problem is that these cells are poorly supplied, not that they are absent (lines 6985-6986). (Choice D) is incorrect: it inverts the relevant property, since cartilage is sparsely supplied rather than densely innervated, and slow healing traces to the lack of a blood supply, not to any nerve-driven suppression of inflammation (lines 6987-6989). This is a Scientific Reasoning and Problem Solving question because you must apply the avascular, diffusion-limited structure of cartilage to explain a novel clinical difference in healing rate rather than recall a stated fact.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '244e2ce7-aba6-43fb-984b-57cb173ae3cc';
DELETE FROM question_distractor_metadata WHERE question_id = '244e2ce7-aba6-43fb-984b-57cb173ae3cc';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('244e2ce7-aba6-43fb-984b-57cb173ae3cc', 'B', 'misconception', 'confuses cartilage matrix with mineralized bone matrix'),
  ('244e2ce7-aba6-43fb-984b-57cb173ae3cc', 'C', 'misconception', 'believes cartilage is inert/acellular tissue'),
  ('244e2ce7-aba6-43fb-984b-57cb173ae3cc', 'D', 'reversed_relationship', 'attributes slow healing to innervation rather than avascularity');

-- [Bone Matrix & Microstructure] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher soaks an intact long bone in a dilute acid bath long enough to dissolve away its mineral component while leaving its protein component intact. When the bone is removed and tested, it is soft and rubbery: it can be bent, and even tied into a loose knot, without breaking. Which change to the bone''s matrix best explains this new behavior?',
  options = '[{"label": "A", "text": "Loss of hydroxyapatite removed the component that had provided hardness and resistance to bending."}, {"label": "B", "text": "Loss of collagen removed the component that had provided hardness and resistance to bending."}, {"label": "C", "text": "Loss of hydroxyapatite removed the component that had provided flexibility and resistance to shattering."}, {"label": "D", "text": "Loss of collagen removed the component that had provided flexibility and resistance to shattering."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Bone''s rigid extracellular matrix has two structural contributors that divide the mechanical labor: inorganic hydroxyapatite crystals (a form of calcium phosphate) and organic collagen fibers. The textbook states that "the hydroxyapatite crystals give bones their hardness and strength, while the collagen fibers give them flexibility so that they are not brittle," and notes that without mineral crystals "bones would flex and provide little support," whereas without collagen "bones would be brittle and shatter easily." A dilute acid dissolves the inorganic mineral (calcium salts are acid-soluble) but spares the collagen, so what remains is the flexible protein scaffold. (Choice A) is correct: dissolving the hydroxyapatite strips away the mineral that normally supplies hardness and rigidity, leaving only the collagen scaffold, which is why the demineralized bone bends and can be knotted instead of holding its shape. (Choice B) is incorrect: acid dissolves mineral salts, not the protein, so collagen is the component that remains, not the one lost; it also misassigns hardness to collagen, when hardness comes from the mineral. (Choice C) is incorrect: it correctly identifies hydroxyapatite as the component removed by acid but assigns it the wrong mechanical role—the mineral provides hardness and rigidity, whereas flexibility and resistance to shattering come from collagen. (Choice D) is incorrect: acid does not remove collagen, and even if it did, loss of the flexible component would make the bone more brittle and rigid, which is the opposite of the soft, bendable result observed. This is a Scientific Reasoning and Problem Solving question because you must apply the distinct mechanical roles of the inorganic and organic matrix components to predict which component acid removes and how its loss changes the bone''s behavior.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '6c6035b2-683f-488f-a6bf-fae0bf9e979d';
DELETE FROM question_distractor_metadata WHERE question_id = '6c6035b2-683f-488f-a6bf-fae0bf9e979d';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6c6035b2-683f-488f-a6bf-fae0bf9e979d', 'B', 'misconception', 'confuses which component acid dissolves and misassigns the mechanical role'),
  ('6c6035b2-683f-488f-a6bf-fae0bf9e979d', 'C', 'reversed_relationship', 'correct component removed but swaps the mechanical roles of mineral and collagen'),
  ('6c6035b2-683f-488f-a6bf-fae0bf9e979d', 'D', 'misconception', 'believes acid removes collagen rather than mineral');

-- [Joints & Movement] ans=A hard skill2
UPDATE questions SET
  question_text = 'A person lifts a cup by flexing the forearm at the elbow, with the biceps brachii serving as the prime mover. During this action, another muscle contracts not to bend or straighten the elbow but to hold the scapula rigid, so that the bone anchoring the biceps'' non-moving end does not shift while the biceps pulls. Which classification best describes the role of this scapula-stabilizing muscle in this action?',
  options = '[{"label": "A", "text": "It is a fixator, a type of synergist"}, {"label": "B", "text": "It is an antagonist of the prime mover"}, {"label": "C", "text": "It is the agonist of forearm flexion"}, {"label": "D", "text": "It is the insertion of the prime mover"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' A skeletal muscle attaches to a fixed (stabilized) bone at its origin and to the bone being pulled at its insertion; the principal muscle producing a movement is the prime mover (agonist), a muscle that assists it is a synergist, and a muscle with the opposite action is an antagonist. The textbook adds that "a synergist can also be a fixator that stabilizes the bone that is the attachment for the prime mover''s origin." Here, the described muscle does not move the elbow at all—it steadies the scapula so the biceps can pull against a firm anchor, which is exactly the fixator role. (Choice A) is correct: because the muscle stabilizes the bone anchoring the prime mover''s origin rather than producing the flexion itself, it functions as a fixator, which is a specialized kind of synergist. (Choice B) is incorrect: an antagonist produces the opposite action of the prime mover (here, forearm extension, as the triceps does), but the described muscle produces no elbow motion at all—it only stabilizes, so it is not an antagonist. (Choice C) is incorrect: the agonist is the prime mover that principally produces the movement, which the stem assigns to the biceps brachii; the stabilizing muscle does not drive the flexion, so it cannot be the agonist. (Choice D) is incorrect: an insertion is an attachment point of a muscle on a bone, not a muscle or a functional role, so a whole contracting muscle cannot "be" the insertion of another muscle. This is a Scientific Reasoning and Problem Solving question because you must apply the definitions of prime mover, synergist, fixator, and antagonist to a muscle whose role is described only by its mechanical function rather than named.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'a687a9b9-cb94-4ef4-8700-5e0b3869803e';
DELETE FROM question_distractor_metadata WHERE question_id = 'a687a9b9-cb94-4ef4-8700-5e0b3869803e';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('a687a9b9-cb94-4ef4-8700-5e0b3869803e', 'B', 'misconception', 'confusing stabilizing/assisting muscles with opposing muscles'),
  ('a687a9b9-cb94-4ef4-8700-5e0b3869803e', 'C', 'misconception', 'conflating any active muscle with the prime mover/agonist'),
  ('a687a9b9-cb94-4ef4-8700-5e0b3869803e', 'D', 'misconception', 'confusing an attachment point (insertion) with a functional muscle role');

-- [Bone Remodeling & Calcium Homeostasis] ans=A hard skill2
UPDATE questions SET
  question_text = 'A biotech company engineers an analog of calcitonin that acts only on bone, where it inhibits osteoclasts and promotes calcium uptake, but that has no effect on the kidney. In a healthy subject with elevated blood calcium, how would a dose of this bone-selective analog most likely affect the fall in blood \(\text{Ca}^{2+}\) and the rate of urinary \(\text{Ca}^{2+}\) excretion, compared with an equivalent dose of native calcitonin?',
  options = '[{"label": "A", "text": "Smaller fall in blood \\(\\text{Ca}^{2+}\\); lower urinary \\(\\text{Ca}^{2+}\\) excretion"}, {"label": "B", "text": "Larger fall in blood \\(\\text{Ca}^{2+}\\); higher urinary \\(\\text{Ca}^{2+}\\) excretion"}, {"label": "C", "text": "Smaller fall in blood \\(\\text{Ca}^{2+}\\); higher urinary \\(\\text{Ca}^{2+}\\) excretion"}, {"label": "D", "text": "Larger fall in blood \\(\\text{Ca}^{2+}\\); lower urinary \\(\\text{Ca}^{2+}\\) excretion"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Native calcitonin lowers blood calcium through two cooperating actions: it drives calcium into bone by inhibiting osteoclasts, and it reduces the kidney''s reabsorption of calcium, which sends more calcium into the urine. As the text states, calcitonin "inhibits osteoclast activity and stimulates calcium uptake by the bones, but also decreases reabsorption of calcium by the kidneys. All of these actions lower blood levels of calcium" (A&P 2e, lines 10310-10312). A bone-selective analog keeps the bone action but discards the renal action, so its effects must be predicted by removing that renal contribution. (Choice A) is correct: dropping the renal action removes one of the two calcium-lowering mechanisms, so blood \(\text{Ca}^{2+}\) falls less than with native calcitonin; and because native calcitonin''s renal effect is what pushes calcium into the urine, an analog lacking that effect leaves more calcium reabsorbed and therefore produces lower urinary \(\text{Ca}^{2+}\) excretion. (Choice B) is incorrect because it treats the analog as more potent on both fronts; losing the renal action cannot produce a larger blood-calcium fall, and without the renal effect that promotes urinary loss, urinary \(\text{Ca}^{2+}\) cannot be higher than with the full hormone. (Choice C) is incorrect because, although it correctly predicts a smaller blood-calcium fall, it wrongly keeps urinary \(\text{Ca}^{2+}\) high; the elevated urinary loss under native calcitonin comes specifically from its renal action, which this analog does not have (lines 10311-10312). (Choice D) is incorrect because it assumes that sparing the kidney''s calcium loss would let more calcium enter bone and deepen the fall; in reality removing a calcium-lowering pathway can only blunt, not amplify, the decline in blood \(\text{Ca}^{2+}\). This is a Scientific Reasoning and Problem Solving question because you must apply calcitonin''s two distinct mechanisms of lowering blood calcium to a modified molecule and predict how removing its renal action changes both blood and urinary calcium.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '991ec131-846d-42a5-86a4-549782a850cb';
DELETE FROM question_distractor_metadata WHERE question_id = '991ec131-846d-42a5-86a4-549782a850cb';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('991ec131-846d-42a5-86a4-549782a850cb', 'B', 'misconception', 'assumes a more selective drug is uniformly more potent'),
  ('991ec131-846d-42a5-86a4-549782a850cb', 'C', 'reversed_relationship', 'attributes calcitonin''s urinary calcium loss to the wrong mechanism'),
  ('991ec131-846d-42a5-86a4-549782a850cb', 'D', 'misconception', 'assumes sparing renal loss redirects calcium into bone and deepens the fall');

-- [Muscle Types & Characteristics] ans=B medium skill2
UPDATE questions SET
  question_text = 'A physiologist stimulates a single smooth-muscle cell within an intact strip of tissue dissected from the wall of the small intestine. The contraction that follows does not stay confined to the stimulated cell; instead, it propagates as a coordinated wave across the whole strip. In a separate trial, gently stretching the resting strip is itself sufficient to initiate a contraction. Which structural feature of this tissue best accounts for both observations?',
  options = '[{"label": "A", "text": "Each fiber is contacted by its own dedicated autonomic nerve terminal"}, {"label": "B", "text": "Adjacent fibers are joined to one another by gap junctions"}, {"label": "C", "text": "The fibers are connected end-to-end by intercalated discs"}, {"label": "D", "text": "An extensive T-tubule network carries the impulse deep into each fiber"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Smooth muscle is organized in two functional forms: single-unit (visceral) smooth muscle, whose fibers are joined by gap junctions so that the whole sheet contracts as a single unit and which displays a stress-relaxation (stretch-triggered) response, and multiunit smooth muscle, whose cells rarely possess gap junctions, are not electrically coupled, and are driven only by autonomic nerves or hormones. The two behaviors described in the strip—a contraction that spreads cell-to-cell as a coordinated wave, and a contraction that can be started by stretch alone—are the defining functional signatures of single-unit visceral muscle, and both trace to one structural feature. (Choice A) is incorrect: dedicated one-to-one autonomic innervation of each fiber is characteristic of multiunit smooth muscle, in which contraction stays confined to the stimulated cell and cannot be triggered by stretch, so it explains neither the spreading wave nor the stretch response. (Choice B) is correct: gap junctions electrically couple neighboring fibers, letting depolarization pass directly from cell to cell so a stimulus applied to one cell produces a propagating wave, and this same coupled, single-unit organization underlies the stress-relaxation response by which stretch triggers contraction. (Choice C) is incorrect: intercalated discs join cardiac muscle cells, not smooth muscle fibers; although they do contain gap junctions, they are the wrong structure for this tissue, and citing them misattributes a cardiac feature to smooth muscle. (Choice D) is incorrect: smooth muscle fibers are small in diameter and lack a T-tubule system entirely, relying instead on sarcolemmal calcium channels; T-tubules therefore cannot explain the observed spread of contraction between cells. This is a Scientific Reasoning and Problem Solving question because you must apply the distinction between single-unit and multiunit smooth muscle to interpret two experimental observations and infer the coupling structure responsible for both.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'c12d925a-50b0-44bc-aace-d6f6d2807bfa';
DELETE FROM question_distractor_metadata WHERE question_id = 'c12d925a-50b0-44bc-aace-d6f6d2807bfa';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('c12d925a-50b0-44bc-aace-d6f6d2807bfa', 'A', 'reversed_relationship', 'attributes the multiunit (isolated, nerve-driven) mechanism to a tissue showing single-unit behavior'),
  ('c12d925a-50b0-44bc-aace-d6f6d2807bfa', 'C', 'misconception', 'transfers a cardiac-muscle structure (intercalated discs) to smooth muscle'),
  ('c12d925a-50b0-44bc-aace-d6f6d2807bfa', 'D', 'misconception', 'assumes smooth muscle has a T-tubule system like skeletal muscle');

-- [Cartilage & Ossification] ans=A medium skill2
UPDATE questions SET
  question_text = 'A basketball player simultaneously tears the hyaline cartilage lining her knee joint and fractures the bone directly beneath it. Both injuries are surgically stabilized. Six months later, imaging shows that the bone fracture has fully healed, but the cartilage lesion remains largely unrepaired. Which structural feature of cartilage best accounts for this difference in healing?',
  options = '[{"label": "A", "text": "Cartilage contains no blood vessels, so nutrients and repair cells must diffuse slowly through its matrix"}, {"label": "B", "text": "Cartilage contains no cells capable of dividing to lay down replacement matrix at the injury site"}, {"label": "C", "text": "Cartilage matrix is hardened by hydroxyapatite crystals that resist enzymatic remodeling during repair"}, {"label": "D", "text": "Cartilage is wrapped in a dense perichondrium that seals out the immune cells needed for repair"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Cartilage and bone are both supportive connective tissues, but they differ sharply in vascularity: bone is highly vascularized and recovers from injury relatively quickly, whereas cartilaginous tissue is avascular, so all nutrients must diffuse through the matrix to reach the chondrocytes, a factor that contributes to the very slow healing of cartilage (A&P 2e, lines 6987-6989, 7018-7019). Predicting the healing outcome requires linking this structural property to functional consequences at the injury site. (Choice A) is correct: because cartilage has no blood supply, nutrients and the cells that drive repair can only reach the wound by slow diffusion through the dense matrix, which is precisely why hyaline cartilage heals far more slowly than the vascularized bone beneath it. (Choice B) is incorrect: cartilage does contain chondrocytes embedded in its matrix, and its slow repair is due to poor delivery of nutrients through an avascular tissue, not to a complete absence of cells that can produce matrix (A&P 2e, lines 6985-6988). (Choice C) is incorrect: it is bone, not cartilage, whose rigid matrix is mineralized with hydroxyapatite, a form of calcium phosphate; the flexible cartilage matrix is built from proteoglycans and collagen rather than hardened mineral crystals (A&P 2e, lines 6984-6985, 7013-7014). (Choice D) is incorrect: the perichondrium is a real layer of dense connective tissue encapsulating cartilage, but the tissue''s slow healing traces to its avascularity and reliance on diffusion, not to a barrier that excludes immune cells (A&P 2e, lines 6986-6989). This is a Scientific Reasoning and Problem Solving question because you must apply the avascular, diffusion-dependent structure of cartilage to explain why it heals more slowly than the adjacent vascularized bone.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '16ea533f-97f3-49e7-aefb-28a89030af38';
DELETE FROM question_distractor_metadata WHERE question_id = '16ea533f-97f3-49e7-aefb-28a89030af38';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('16ea533f-97f3-49e7-aefb-28a89030af38', 'B', 'misconception', 'attributes slow healing to absent cells rather than absent blood supply'),
  ('16ea533f-97f3-49e7-aefb-28a89030af38', 'C', 'reversed_relationship', 'assigns bone''s mineralized-matrix property to cartilage'),
  ('16ea533f-97f3-49e7-aefb-28a89030af38', 'D', 'partial_truth', 'cites a real structure (perichondrium) as a false causal barrier');

-- [Muscle Types & Characteristics] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher applies an experimental compound to isolated ventricular tissue that selectively blocks the gap junctions within the intercalated discs of cardiac muscle, while leaving each cell''s contractile machinery, membrane excitability, and pacemaker-driven autorhythmicity fully intact. Individual cells can still generate action potentials and shorten normally. Compared with untreated ventricular tissue, how is the mechanical behavior of the treated tissue most likely to change?',
  options = '[{"label": "A", "text": "The cells contract at different times instead of as one coordinated unit"}, {"label": "B", "text": "The cells fuse into a single multinucleate fiber that contracts more forcefully"}, {"label": "C", "text": "The tissue contracts more strongly by recruiting additional muscle cells"}, {"label": "D", "text": "The cells stop contracting because they can no longer initiate action potentials"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' In cardiac muscle, adjacent cells are joined at intercalated discs whose gap junctions let the depolarizing current pass directly from one cell to the next; this electrical coupling turns the many separate cardiomyocytes into a functional syncytium so that the entire chamber depolarizes and contracts as a single coordinated unit. The stem specifies that only the gap junctions are blocked, while each cell''s excitability, autorhythmicity, and contractile apparatus remain intact, so you must reason about what is lost when cells are electrically uncoupled rather than what stops working inside a cell. (Choice A) is correct: with the gap junctions blocked, the action potential can no longer spread cell-to-cell, so each cell excites and shortens on its own schedule instead of firing together, and the tissue loses its unified, coordinated contraction. (Choice B) is incorrect: cardiac cells form only a functional (electrochemical) syncytium and always remain physically separate single cells; true fusion into one multinucleate fiber describes skeletal muscle, and blocking gap junctions would never cause cells to merge. (Choice C) is incorrect: graded, stronger contraction by recruiting more cells is a property of skeletal muscle organized into independently innervated motor units; cardiac tissue normally contracts as an all-or-none unit and losing coupling weakens coordination rather than adding recruitable strength. (Choice D) is incorrect: the stem states that excitability and pacemaker autorhythmicity are untouched, so the cells can still initiate action potentials on their own; gap junctions propagate depolarization between cells but are not required for an individual cell to fire. This is a Scientific Reasoning and Problem Solving question because you must apply the structure-function link between cardiac gap junctions and the functional syncytium to predict the consequence of uncoupling the cells in a novel experiment.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '0e07b07c-f20d-4c69-b746-9faa43bc543c';
DELETE FROM question_distractor_metadata WHERE question_id = '0e07b07c-f20d-4c69-b746-9faa43bc543c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('0e07b07c-f20d-4c69-b746-9faa43bc543c', 'B', 'misconception', 'conflates functional syncytium with skeletal muscle''s true multinucleate fusion'),
  ('0e07b07c-f20d-4c69-b746-9faa43bc543c', 'C', 'misconception', 'applies skeletal motor-unit recruitment/graded contraction to cardiac muscle'),
  ('0e07b07c-f20d-4c69-b746-9faa43bc543c', 'D', 'misconception', 'assumes gap junctions are required to initiate contraction rather than to coordinate it');

-- [Bone Matrix & Microstructure] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher submerges a fresh long bone in a weak acid bath long enough to fully dissolve its hydroxyapatite mineral, while the collagen fiber framework of the matrix is left intact. When the treated bone is then loaded, how is its mechanical behavior most likely to change?',
  options = '[{"label": "A", "text": "It bends easily under load and no longer supports weight rigidly."}, {"label": "B", "text": "It shatters into fragments when even a small force is applied."}, {"label": "C", "text": "It collapses into a shapeless mass as its collagen dissolves away."}, {"label": "D", "text": "It keeps its full stiffness because the remaining collagen is rigid."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Bone''s rigid extracellular matrix is a composite of an organic component (mostly collagen fibers) embedded in a mineralized ground substance containing hydroxyapatite, a form of calcium phosphate, and each component contributes a distinct mechanical property: the text states that "without collagen, bones would be brittle and shatter easily" and that "without mineral crystals, bones would flex and provide little support" (lines 7015-7016). Selectively dissolving the mineral therefore removes the source of hardness and rigidity while leaving the flexible collagen scaffold behind. (Choice A) is correct: with the hydroxyapatite gone, only the collagen framework remains, so the demineralized bone flexes and can no longer provide rigid support, exactly the outcome the text predicts when mineral crystals are absent. (Choice B) is incorrect: brittleness and shattering are what result from losing the collagen ("without collagen, bones would be brittle and shatter easily"), so this reverses which component was removed; the intact collagen actually makes the treated bone tough and pliable, not brittle. (Choice C) is incorrect: the acid dissolves the inorganic hydroxyapatite, not the collagen, so the organic scaffold persists and preserves the bone''s overall shape rather than collapsing into a shapeless mass. (Choice D) is incorrect: collagen supplies flexibility and tensile strength, not stiffness, so removing the mineral removes the rigidity and the bone cannot retain its full stiffness. This is a Scientific Reasoning and Problem Solving question because you must apply the division of labor within the calcium-protein matrix—mineral providing rigidity, collagen providing flexibility—to predict the mechanical result of removing one component.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '0b359fce-abbe-478d-8daa-518f6c86989b';
DELETE FROM question_distractor_metadata WHERE question_id = '0b359fce-abbe-478d-8daa-518f6c86989b';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('0b359fce-abbe-478d-8daa-518f6c86989b', 'B', 'reversed_relationship', 'swaps the effect of removing collagen for the effect of removing mineral'),
  ('0b359fce-abbe-478d-8daa-518f6c86989b', 'C', 'misconception', 'assumes acid dissolves the organic collagen rather than the inorganic mineral'),
  ('0b359fce-abbe-478d-8daa-518f6c86989b', 'D', 'misconception', 'attributes rigidity/stiffness to collagen instead of to the mineral component');

-- [Sarcomere Structure] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher images a single skeletal muscle sarcomere with electron microscopy, first at rest and again while the fiber is actively shortening. Comparing the two images, she measures the width of each banded region of the sarcomere. According to the sliding filament model, which region''s width remains unchanged as the sarcomere shortens?',
  options = '[{"label": "A", "text": "The A band"}, {"label": "B", "text": "The I band"}, {"label": "C", "text": "The H zone"}, {"label": "D", "text": "The distance between adjacent Z-discs"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' In the sliding filament model, contraction does not shorten the filaments themselves; instead, the thin filaments slide inward past the thick filaments toward the center of the sarcomere. Because the A band corresponds exactly to the length of the thick (myosin) filaments, and those filaments do not change length during contraction, the A band width is constant even as the sarcomere as a whole gets shorter. (Choice A) is correct: the A band is defined by the span of the thick filaments, whose length is fixed; since sliding does not change filament length, the A band stays the same width throughout contraction. (Choice B) is incorrect: the I band contains only thin filaments not overlapped by thick filaments, and as thin filaments slide inward this non-overlap region narrows, so the I band becomes smaller during contraction. (Choice C) is incorrect: the H zone is the central region containing only thick filaments; as thin filaments advance toward the center they invade this zone, so the H zone narrows and can disappear at full contraction rather than staying constant. (Choice D) is incorrect: the Z-discs mark the sarcomere boundaries, and because contraction shortens the sarcomere, the Z-discs are pulled closer together, so this distance decreases. This is a Scientific Reasoning and Problem Solving question because you must apply the sliding filament model to predict how each band''s width changes, recognizing that only the region set by fixed thick-filament length is unaffected by filament sliding.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '887ad657-bb71-4994-b622-72a6b6c17f82';
DELETE FROM question_distractor_metadata WHERE question_id = '887ad657-bb71-4994-b622-72a6b6c17f82';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('887ad657-bb71-4994-b622-72a6b6c17f82', 'B', 'misconception', 'confuses which band tracks filament overlap'),
  ('887ad657-bb71-4994-b622-72a6b6c17f82', 'C', 'misconception', 'assumes central thick-filament zone is unchanged'),
  ('887ad657-bb71-4994-b622-72a6b6c17f82', 'D', 'misconception', 'conflates sarcomere shortening with a constant boundary');

-- [Muscle Mechanics & Contraction Dynamics] ans=C hard skill2
UPDATE questions SET
  question_text = 'A physiologist studies an isolated skeletal muscle fiber. A single stimulus produces a twitch that begins at the stimulus and returns fully to baseline tension 90 ms later (a 5 ms latent period, a 40 ms contraction phase, and a 45 ms relaxation phase). The physiologist then delivers repeated stimuli at four fixed inter-stimulus intervals. Assuming each individual twitch retains the same time course, which stimulation protocol is the first (as interval shortens) at which the recorded tension will be greater than that of a single twitch?

| Protocol | Inter-stimulus interval |
|---|---|
| W | 120 ms |
| X | 100 ms |
| Y | 70 ms |
| Z | 30 ms |',
  options = '[{"label": "A", "text": "Protocol W"}, {"label": "B", "text": "Protocol X"}, {"label": "C", "text": "Protocol Y"}, {"label": "D", "text": "Protocol Z"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Skeletal muscle tension is graded partly by the frequency of motor-neuron firing: if a second stimulus arrives while the fiber is still contracting from the first, the two responses add together in wave summation, releasing more \(\text{Ca}^{2+}\) and activating additional sarcomeres so the recorded tension exceeds a single twitch. The critical comparison is between the inter-stimulus interval and the full duration of one twitch. A twitch here lasts 90 ms from stimulus to complete return to baseline, so any stimulus arriving less than 90 ms after the previous one lands before relaxation is finished and will summate; any interval of 90 ms or longer lets the fiber relax fully first, producing separate, non-summing twitches of unchanged amplitude. (Choice C) is correct: 70 ms is the longest listed interval that is still shorter than the 90 ms twitch, so it is the first protocol (as the interval shortens from W to Z) in which the second stimulus arrives during the ongoing twitch and tension summates above a single twitch. (Choice A) is incorrect: at 120 ms the fiber has fully relaxed (well past 90 ms) before the next stimulus, so each twitch is discrete and peak tension equals a single twitch. (Choice B) is incorrect: 100 ms still exceeds the 90 ms twitch duration, so relaxation completes and no summation occurs; a student who assumes any rapid repetition summates may pick the first interval under a nice round threshold rather than comparing to the actual twitch duration. (Choice D) is incorrect: 30 ms does produce strong summation and even approaches tetanus, but the question asks for the first protocol that exceeds a single twitch as the interval shortens, and summation already begins at the longer 70 ms interval, so Z is not the first. This is a Scientific Reasoning and Problem Solving question because you must apply the mechanism of wave summation—comparing the inter-stimulus interval to the full twitch duration—to determine which stimulation pattern first raises tension above a single twitch.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '67418d80-e84c-4a6c-a669-601d3c0cb7ff';
DELETE FROM question_distractor_metadata WHERE question_id = '67418d80-e84c-4a6c-a669-601d3c0cb7ff';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('67418d80-e84c-4a6c-a669-601d3c0cb7ff', 'A', 'misconception', 'confuses fast repetition with summation regardless of twitch timing'),
  ('67418d80-e84c-4a6c-a669-601d3c0cb7ff', 'B', 'misconception', 'uses a round-number threshold instead of the actual twitch duration'),
  ('67418d80-e84c-4a6c-a669-601d3c0cb7ff', 'D', 'partial_truth', 'picks the strongest-summation interval instead of the first one to exceed a single twitch');

-- [Muscle Energetics & Fatigue] ans=A medium skill2
UPDATE questions SET
  question_text = 'A sprinter finishes a 200-meter dash and stops moving, but for several minutes afterward she continues to breathe rapidly and deeply, consuming far more \(\text{O}_2\) than she did at rest before the race. Her leg muscles are relaxed and no longer contracting. Which explanation best accounts for why her oxygen consumption stays elevated even though the muscular work has ended?',
  options = '[{"label": "A", "text": "Oxygen is being used to rebuild creatine phosphate and ATP reserves and to clear the lactic acid produced during the race."}, {"label": "B", "text": "The leg muscles are still contracting at a near-maximal rate and require the same oxygen delivery as during the sprint."}, {"label": "C", "text": "Oxygen is required to convert the pyruvic acid remaining in the muscle into lactic acid so that glycolysis can resume."}, {"label": "D", "text": "The extra oxygen regenerates NAD+ directly in the cytosol so that anaerobic glycolysis can keep running."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' During an all-out sprint, muscles regenerate \(\text{ATP}\) mostly through creatine phosphate and anaerobic glycolysis, depleting phosphate reserves and accumulating lactic acid. The textbook explains that intense muscle activity produces an oxygen debt — the amount of oxygen needed to compensate for \(\text{ATP}\) produced without oxygen — and that after exercise stops, oxygen intake stays elevated to restore \(\text{ATP}\) and creatine phosphate levels and to convert lactic acid back to pyruvic acid (and, in the liver, into glucose or glycogen), which is why breathing rate remains high even after activity ends (lines 17529-17533). (Choice A) is correct: the sustained \(\text{O}_2\) uptake repays the oxygen debt by rebuilding the creatine phosphate and \(\text{ATP}\) energy reserves and metabolizing the lactic acid that built up during the anaerobic effort. (Choice B) is incorrect: the stem states her muscles are relaxed and no longer contracting, so ongoing high-rate contraction cannot be the reason; oxygen demand during recovery reflects metabolic repair, not continued mechanical work. (Choice C) is incorrect: pyruvic acid is converted to lactic acid precisely when \(\text{O}_2\) is absent, allowing glycolysis to continue anaerobically; this conversion does not consume oxygen, so it cannot explain the elevated post-exercise \(\text{O}_2\) uptake. (Choice D) is incorrect: \(\text{NAD}^+\) is regenerated in the cytosol by converting pyruvic acid to lactic acid during anaerobic glycolysis, a process that requires no oxygen; oxygen debt instead pays back reserves and clears lactate rather than sustaining anaerobic glycolysis. This is a Scientific Reasoning and Problem Solving question because you must apply the concept of oxygen debt to a novel post-exercise scenario and infer that continued oxygen use serves metabolic recovery, information the scenario does not state directly.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'cbd1db92-9aa2-4810-ad6a-b1731d045ef4';
DELETE FROM question_distractor_metadata WHERE question_id = 'cbd1db92-9aa2-4810-ad6a-b1731d045ef4';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('cbd1db92-9aa2-4810-ad6a-b1731d045ef4', 'B', 'misconception', 'assumes oxygen demand tracks mechanical work rather than metabolic recovery'),
  ('cbd1db92-9aa2-4810-ad6a-b1731d045ef4', 'C', 'reversed_relationship', 'treats lactic acid formation as oxygen-requiring when it occurs anaerobically'),
  ('cbd1db92-9aa2-4810-ad6a-b1731d045ef4', 'D', 'misconception', 'confuses aerobic oxygen use with cytosolic NAD+ regeneration of glycolysis');

-- [Cross-Bridge Cycle & Sliding Filament] ans=A medium skill2
UPDATE questions SET
  question_text = 'A physiologist sets a single skinned skeletal muscle fiber to a series of fixed sarcomere lengths (expressed as a percentage of the length that gives maximal tension) and, at each length, floods the fiber with saturating free \(\text{Ca}^{2+}\) and excess \(\text{ATP}\) before measuring peak isometric tension.

| Sarcomere length (% of optimal) | Peak tension (% of max) |
|---|---|
| 65 | 40 |
| 85 | 88 |
| 100 | 100 |
| 130 | 72 |
| 175 | 18 |

Because \(\text{Ca}^{2+}\) and \(\text{ATP}\) are held at saturating levels at every length, which mechanism most directly accounts for the low tension measured at 175% of optimal length?',
  options = '[{"label": "A", "text": "At this length the thick and thin filaments overlap over too short a region for many cross-bridges to form."}, {"label": "B", "text": "At this length thin filaments from opposite Z-discs overlap each other and obstruct myosin binding."}, {"label": "C", "text": "At this length less \\(\\text{Ca}^{2+}\\) reaches troponin, so fewer actin binding sites become exposed."}, {"label": "D", "text": "At this length myosin hydrolyzes \\(\\text{ATP}\\) too slowly to power repeated power strokes."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Tension in a sarcomere is set by the length-tension relationship: cross-bridges can only form where thick and thin filaments already overlap, so the length of the sarcomere directly influences how much force it generates. The textbook explains that maximal tension occurs near optimal length, but that "if a sarcomere is stretched past this ideal length (beyond 120 percent), thick and thin filaments do not overlap sufficiently, which results in less tension produced," and that if it is stretched until the filaments "do not overlap at all, no cross-bridges can be formed, and no tension is produced." The 175% length sits far out on the descending limb, so the correct mechanism must explain a stretched, low-overlap sarcomere. (Choice A) is correct: at 175% of optimal length the sarcomere is overstretched, the zone where thick and thin filaments overlap is greatly reduced, and only a small fraction of myosin heads can reach actin, so few cross-bridges form and tension is low. (Choice B) is incorrect: opposing thin filaments colliding and interfering is the mechanism that lowers tension at very short sarcomere lengths, where the fiber is compressed below about 80% of optimal, not at a stretched 175% length, so it describes the wrong limb of the curve. (Choice C) is incorrect: \(\text{Ca}^{2+}\) is held saturating at every length, so troponin is fully occupied and site exposure is not the variable being changed; the falloff in tension is geometric, not a change in activation. (Choice D) is incorrect: \(\text{ATP}\) is also held in excess and myosin ATPase rate is not altered by stretching the fiber, so cross-bridge fueling is not limiting; the loss of tension comes from having few filaments overlapping, not from slower ATP turnover. This is a Scientific Reasoning and Problem Solving question because you must apply the length-tension relationship to a specific data point on the descending limb and infer which molecular geometry, rather than which biochemical input, limits force there.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '8a6d8b5d-4ba2-42ec-aed9-f30c788c0617';
DELETE FROM question_distractor_metadata WHERE question_id = '8a6d8b5d-4ba2-42ec-aed9-f30c788c0617';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8a6d8b5d-4ba2-42ec-aed9-f30c788c0617', 'B', 'misconception', 'right-mechanism-wrong-limb'),
  ('8a6d8b5d-4ba2-42ec-aed9-f30c788c0617', 'C', 'misconception', 'confuses-activation-with-mechanics'),
  ('8a6d8b5d-4ba2-42ec-aed9-f30c788c0617', 'D', 'misconception', 'confuses-fueling-with-geometry');

-- [Muscle Types & Characteristics] ans=A hard skill2
UPDATE questions SET
  question_text = 'As the urinary bladder fills, mechanical stretch of the wall triggers a wave of contraction that sweeps across the smooth muscle before any autonomic input arrives. If a researcher wanted to abolish this coordinated, stretch-initiated wave while leaving each individual fiber still able to contract when directly depolarized, which structural feature of the bladder wall should the intervention target?',
  options = '[{"label": "A", "text": "The gap junctions that connect adjacent fibers"}, {"label": "B", "text": "The T-tubules that penetrate each fiber''s interior"}, {"label": "C", "text": "The autonomic varicosities that release neurotransmitter"}, {"label": "D", "text": "The calmodulin that binds calcium within each fiber"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Single-unit (visceral) smooth muscle, which lines hollow organs such as the bladder, has its fibers joined by gap junctions so that the tissue contracts as a single unit; its stress-relaxation response means that stretching the wall as the organ fills is itself a myogenic trigger for contraction. The question asks which feature makes the response coordinated across the wall (spreading cell to cell) rather than the feature that lets any one fiber contract, so the target must be the structure responsible for electrical coupling between fibers. (Choice A) is correct: gap junctions electrically couple neighboring fibers, so a stretch-initiated action potential in one cell passes directly to the next; removing them would confine excitation to the originally stimulated fiber (as in multiunit smooth muscle) and abolish the propagating wave, while each fiber could still contract if depolarized on its own. (Choice B) is incorrect: smooth muscle fibers are thin enough that they do not require T-tubules and in fact lack them, and even where T-tubules exist (skeletal and cardiac muscle) they carry excitation into the interior of a single fiber, not from one fiber to the next, so they cannot account for tissue-wide spread. (Choice C) is incorrect: autonomic varicosities do release neurotransmitter onto smooth muscle, but the premise states the wave occurs before autonomic input arrives, so this pathway is not what carries the stretch-initiated signal across the wall. (Choice D) is incorrect: calmodulin is the intracellular calcium-binding regulator that activates myosin light-chain kinase within each fiber, so blocking it would impair contraction of individual fibers rather than selectively remove the cell-to-cell coupling the question isolates. This is a Scientific Reasoning and Problem Solving question because you must apply the property that only gap junctions electrically couple single-unit smooth muscle to predict which intervention removes coordinated spread while sparing individual-fiber contraction.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'e49d5590-6839-4a83-918d-2f6c9042d128';
DELETE FROM question_distractor_metadata WHERE question_id = 'e49d5590-6839-4a83-918d-2f6c9042d128';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('e49d5590-6839-4a83-918d-2f6c9042d128', 'B', 'misconception', 'wrong structure attributed to smooth muscle'),
  ('e49d5590-6839-4a83-918d-2f6c9042d128', 'C', 'partial_truth', 'real innervation feature that violates the stated premise'),
  ('e49d5590-6839-4a83-918d-2f6c9042d128', 'D', 'partial_truth', 'intracellular regulator, not intercellular coupling');

-- [Muscle Mechanics & Contraction Dynamics] ans=A hard skill2
UPDATE questions SET
  question_text = 'An isolated skeletal muscle is stimulated at a fixed 15 Hz. The myogram shows tension rising to about twice a single twitch, but the trace still oscillates and dips partway toward baseline between stimuli. Without changing the stimulus frequency, a researcher then applies a drug that partially inhibits the sarcoplasmic reticulum \(\text{Ca}^{2+}\) pump. How is the myogram most likely to change, and why?

A. The oscillations flatten into a smooth, elevated plateau, because residual \(\text{Ca}^{2+}\) between stimuli prevents the relaxation phase
B. The oscillations flatten into a smooth, elevated plateau, because the drug lengthens the latent period of each twitch
C. The trace fully returns to baseline after each stimulus, because \(\text{Ca}^{2+}\) can no longer reach troponin
D. Each successive peak grows taller in a stepwise staircase, because the muscle becomes more efficient with repeated use',
  options = '[{"label": "A", "text": "The oscillations flatten into a smooth, elevated plateau, because residual \\(\\text{Ca}^{2+}\\) between stimuli prevents the relaxation phase"}, {"label": "B", "text": "The oscillations flatten into a smooth, elevated plateau, because the drug lengthens the latent period of each twitch"}, {"label": "C", "text": "The trace fully returns to baseline after each stimulus, because \\(\\text{Ca}^{2+}\\) can no longer reach troponin"}, {"label": "D", "text": "Each successive peak grows taller in a stepwise staircase, because the muscle becomes more efficient with repeated use"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' A skeletal muscle relaxes only when \(\text{Ca}^{2+}\) is pumped out of the sarcoplasm back into the sarcoplasmic reticulum, letting tropomyosin re-block the actin binding sites; the partial dips in the 15 Hz trace represent this incomplete tetanus, where a brief relaxation phase survives between stimuli. The task is not to name the starting state but to predict how slowing \(\text{Ca}^{2+}\) reuptake shifts the trace, so you must trace the drug''s effect through the calcium mechanism rather than the stimulus frequency. (Choice A) is correct: with the reticular pump partially blocked, \(\text{Ca}^{2+}\) that was released by each stimulus lingers in the sarcoplasm instead of being cleared, so it keeps troponin occupied and cross-bridges cycling during the interval when the muscle would otherwise begin relaxing; eliminating the relaxation phase fuses the twitches into the smooth, continuous plateau of complete tetanus, even though the stimulus frequency never changed. (Choice B) is incorrect: the latent period is the delay before contraction begins as the action potential propagates and \(\text{Ca}^{2+}\) is released, and slowing reuptake does not lengthen it; even if it did, a longer latent period would delay contractions rather than fuse them into a plateau. (Choice C) is incorrect: this reverses the pump''s role. Inhibiting \(\text{Ca}^{2+}\) removal keeps sarcoplasmic \(\text{Ca}^{2+}\) high, so \(\text{Ca}^{2+}\) reaches troponin more readily, not less; the muscle would relax less, not return fully to baseline. (Choice D) is incorrect: this describes treppe, the staircase seen when a dormant muscle is first activated and successive fully relaxing twitches grow stronger; treppe traces still dip to baseline between stimuli, whereas impairing reuptake abolishes relaxation and produces fusion instead of a staircase. This is a Scientific Reasoning and Problem Solving question because you must apply the calcium-reuptake mechanism of relaxation to predict how a pharmacological change, not a frequency change, converts incomplete tetanus into a fused plateau.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '4030b821-2be9-4416-b26f-174770ed5101';
DELETE FROM question_distractor_metadata WHERE question_id = '4030b821-2be9-4416-b26f-174770ed5101';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4030b821-2be9-4416-b26f-174770ed5101', 'B', 'misconception', 'wrong-mechanism-plausible-outcome'),
  ('4030b821-2be9-4416-b26f-174770ed5101', 'C', 'reversed_relationship', 'inverted-pump-effect'),
  ('4030b821-2be9-4416-b26f-174770ed5101', 'D', 'adjacent_fact', 'confused-neighboring-phenomenon');

-- [Bone Matrix & Microstructure] ans=A medium skill2
UPDATE questions SET
  question_text = 'A patient has an inherited disorder in which osteoblasts synthesize defective collagen, so very little functional collagen is incorporated into the bone matrix. Mineral (hydroxyapatite) is still deposited normally throughout the matrix. Compared with normal bone, how are this patient''s long bones most likely to behave under mechanical stress?',
  options = '[{"label": "A", "text": "They become brittle and fracture easily under sudden impact."}, {"label": "B", "text": "They become overly flexible and bend under the body''s weight."}, {"label": "C", "text": "They lose stored calcium and gradually soften over time."}, {"label": "D", "text": "They elongate abnormally because the matrix no longer limits growth."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Bone''s rigid extracellular matrix is a calcium-protein composite: mostly collagen fibers embedded in a mineralized ground substance containing hydroxyapatite, a form of calcium phosphate. Both components contribute to bone''s unusual properties: without collagen bones would be brittle and shatter easily, whereas without the mineral crystals bones would flex and provide little support (OpenStax A&P 2e, lines 7012-7016). The collagen (organic) fibers act as scaffolding that gives bone tensile strength and toughness, while the deposited mineral gives it hardness and compressive stiffness. (Choice A) is correct: with functional collagen largely missing but mineralization intact, the bone retains its hard, stiff mineral component but loses the tough, flexible organic scaffolding, so it behaves like the collagen-deficient case the text describes as brittle and prone to shattering, fracturing easily under sudden impact. (Choice B) is incorrect: excessive flexibility and bending under load is the predicted result of losing the mineral component, not the collagen; here the mineral is deposited normally, so the bone stays stiff rather than becoming rubbery (lines 7015-7016). (Choice C) is incorrect: this reverses cause and effect by assuming any matrix defect triggers loss of stored calcium and softening, but the mineral is deposited normally in this patient, so calcium content and hardness are preserved; the failure is in the organic scaffolding, not in mineralization. (Choice D) is incorrect: longitudinal bone growth is governed by cartilage proliferation at the epiphyseal (growth) plate, not by mechanical restraint from the collagen matrix, so a collagen defect would not cause bones to elongate abnormally. This is a Scientific Reasoning and Problem Solving question because you must apply the distinct mechanical contributions of bone''s organic and inorganic matrix components to predict how a novel collagen defect alters bone behavior under stress.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '1236b67e-0777-409b-8f96-bbd84873ea15';
DELETE FROM question_distractor_metadata WHERE question_id = '1236b67e-0777-409b-8f96-bbd84873ea15';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('1236b67e-0777-409b-8f96-bbd84873ea15', 'B', 'reversed_relationship', 'swaps the role of the mineral component for the collagen component'),
  ('1236b67e-0777-409b-8f96-bbd84873ea15', 'C', 'misconception', 'assumes any bone-matrix defect means demineralization and softening'),
  ('1236b67e-0777-409b-8f96-bbd84873ea15', 'D', 'misconception', 'conflates matrix composition with epiphyseal-plate control of bone length');

-- [Bone Remodeling & Calcium Homeostasis] ans=C medium skill2
UPDATE questions SET
  question_text = 'During a thyroidectomy, a surgeon inadvertently removes all four of the patient''s parathyroid glands, and the patient can no longer secrete parathyroid hormone (PTH). Over the following days, the patient develops muscle cramps and tetany. Assuming no medical intervention, how does the loss of PTH most directly alter blood \(\text{Ca}^{2+}\) through its effect on bone?',
  options = '[{"label": "A", "text": "Blood \\(\\text{Ca}^{2+}\\) rises because osteoclast-mediated bone resorption is no longer restrained"}, {"label": "B", "text": "Blood \\(\\text{Ca}^{2+}\\) rises because osteoblasts increase deposition of calcium into bone matrix"}, {"label": "C", "text": "Blood \\(\\text{Ca}^{2+}\\) falls because osteoclast-mediated bone resorption is no longer stimulated"}, {"label": "D", "text": "Blood \\(\\text{Ca}^{2+}\\) falls because osteoblasts stop depositing calcium into bone matrix"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Blood calcium is held near 10 mg/dL by opposing hormones: parathyroid hormone (PTH) raises it and calcitonin lowers it. The textbook states that "PTH stimulates osteoclast proliferation and activity. As a result, calcium is released from the bones into the circulation, thus increasing the calcium ion concentration in the blood." When calcium stops binding the parathyroid gland''s plasma-membrane receptors, those cells release PTH, driving this osteoclast-mediated resorption. If the parathyroid glands are removed, this drive disappears, so bone resorption is no longer stimulated and blood \(\text{Ca}^{2+}\) drops toward hypocalcemia, producing the patient''s tetany. (Choice A) is incorrect: PTH stimulates osteoclasts rather than restraining them, so its loss reduces resorption; the hormone that inhibits osteoclasts is calcitonin, which "inhibits osteoclast activity and stimulates calcium uptake by the bones, thus reducing the concentration of calcium ions in the blood," so removing an inhibitor is the wrong model here. (Choice B) is incorrect: PTH does not act primarily through osteoblasts to raise calcium, and increased matrix deposition would move calcium out of the blood into bone, lowering blood \(\text{Ca}^{2+}\) rather than raising it. (Choice C) is correct: losing PTH withdraws the signal that "stimulates osteoclast proliferation and resorption of bone by osteoclasts," so less calcium is liberated from bone and blood \(\text{Ca}^{2+}\) falls, matching the patient''s cramps and tetany. (Choice D) is incorrect: it reaches the right direction (falling calcium) by the wrong mechanism, because PTH''s calcium-raising action operates through osteoclast resorption, not through control of osteoblastic deposition, so attributing the fall to halted deposition misidentifies PTH''s target cell. This is a Scientific Reasoning and Problem Solving question because you must apply PTH''s role in stimulating osteoclast resorption to a scenario of glandular loss and predict the resulting direction of change in blood \(\text{Ca}^{2+}\).',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '8fc05595-5b71-435e-bfea-c37ff290fd60';
DELETE FROM question_distractor_metadata WHERE question_id = '8fc05595-5b71-435e-bfea-c37ff290fd60';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8fc05595-5b71-435e-bfea-c37ff290fd60', 'A', 'reversed_relationship', 'confusing PTH''s stimulatory action with calcitonin''s inhibitory action on osteoclasts'),
  ('8fc05595-5b71-435e-bfea-c37ff290fd60', 'B', 'misconception', 'believing PTH raises blood calcium by acting on osteoblasts to build bone'),
  ('8fc05595-5b71-435e-bfea-c37ff290fd60', 'D', 'adjacent_fact', 'right direction (calcium falls) attributed to the wrong bone cell (osteoblast deposition instead of osteoclast resorption)');

-- [Muscle Fiber Types] ans=B medium skill1
UPDATE questions SET
  question_text = 'A muscle is dominated by fibers that contract quickly enough to power repeated walking and jogging yet resist fatigue far better than the fibers used for an all-out sprint. Compared with the fibers a sprinter relies on for a single explosive push, the fibers dominating this muscle would be expected to contain which combination of features?',
  options = '[{"label": "A", "text": "More mitochondria but a similar reliance on aerobic respiration"}, {"label": "B", "text": "More mitochondria and a greater reliance on aerobic respiration"}, {"label": "C", "text": "Fewer mitochondria and a greater reliance on anaerobic glycolysis"}, {"label": "D", "text": "Fewer mitochondria but a similar reliance on anaerobic glycolysis"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Skeletal muscle contains three fiber types distinguished by contractile speed and how they make ATP: slow oxidative (SO) fibers contract slowly and resist fatigue, fast oxidative (FO) fibers contract quickly yet stay relatively fatigue-resistant, and fast glycolytic (FG) fibers contract quickly but fatigue rapidly. The described muscle powers repeated jogging while resisting fatigue better than sprint fibers, identifying it as FO-dominant; the sprinter''s explosive-push fibers are FG. The textbook states FO fibers "are oxidative because they produce ATP aerobically, possess high amounts of mitochondria, and do not fatigue quickly," whereas FG fibers "primarily use anaerobic glycolysis" and "do not possess substantial numbers of mitochondria." (Choice A) is incorrect: FO fibers do have more mitochondria than FG fibers, but they do not merely match FG fibers in metabolism—they rely far more on aerobic respiration, so "similar reliance" understates the metabolic difference. (Choice B) is correct: relative to FG fibers, FO fibers possess both more mitochondria and a greater reliance on aerobic (oxidative) respiration, which is what makes them fast yet fatigue-resistant. (Choice C) is incorrect: this reverses the relationship—it describes the FG (sprint) fibers themselves, which have fewer mitochondria and depend on anaerobic glycolysis, not the more fatigue-resistant FO fibers. (Choice D) is incorrect: it keeps the glycolytic metabolism of sprint fibers while wrongly claiming fewer mitochondria than an already low-mitochondria fiber, describing no real fiber type and contradicting the aerobic basis of FO fatigue resistance. This is a Knowledge of Scientific Concepts and Principles question because you must recall how mitochondrial content and aerobic versus anaerobic ATP production distinguish fast oxidative from fast glycolytic muscle fibers.',
  difficulty = 'medium',
  cognitive_skill = 1
WHERE id = 'fafa1030-f2f2-4ca4-bd30-816985003d0b';
DELETE FROM question_distractor_metadata WHERE question_id = 'fafa1030-f2f2-4ca4-bd30-816985003d0b';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('fafa1030-f2f2-4ca4-bd30-816985003d0b', 'A', 'misconception', 'partial-match (right direction on mitochondria, wrong on metabolism)'),
  ('fafa1030-f2f2-4ca4-bd30-816985003d0b', 'C', 'reversed_relationship', 'describes the comparison fiber (FG) instead of the target fiber (FO)'),
  ('fafa1030-f2f2-4ca4-bd30-816985003d0b', 'D', 'misconception', 'conflates fast fibers as uniformly glycolytic');

-- [Sarcomere Structure] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher records electron micrographs of a single skeletal muscle fiber at rest and again while the fiber is maximally shortened. Comparing the two images, she measures the width of each striation band within a sarcomere. One band has the same width in both images, whereas the others are narrower during shortening. Which band is unchanged, and why?',
  options = '[{"label": "A", "text": "The A band, because the length of the thick filament does not change"}, {"label": "B", "text": "The I band, because the length of the thin filament does not change"}, {"label": "C", "text": "The H zone, because the thin filaments do not enter this region"}, {"label": "D", "text": "The A band, because the thin and thick filaments detach in this region"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Under the sliding filament model, a sarcomere shortens because the thin (actin) and thick (myosin) filaments slide past one another; the filaments themselves do not shorten, only their degree of overlap changes. Because the A band corresponds to the full length of the thick filament, its width is fixed no matter how much the sarcomere contracts, while the I band (thin filament only) and the H zone (thick filament only) shrink as overlap increases and the Z lines are pulled inward. (Choice A) is correct: the A band spans the entire length of the thick filament, and since the thick filament does not change length during the sliding filament mechanism, the A band width stays constant even as the sarcomere shortens. (Choice B) is incorrect: the I band does narrow during contraction because it is the thin-filament-only region, and increasing overlap with the thick filaments reduces it; the thin filament''s length is constant, but the I band width is not. (Choice C) is incorrect: it is true that thin filaments do not extend into the H zone at rest, but during contraction the thin filaments slide toward the center and encroach on this region, so the H zone actually narrows rather than staying constant. (Choice D) is incorrect: it names the correct band but gives a false reason — filaments do not detach across the A band during contraction; cross-bridges cycle there, and the band''s constancy reflects the fixed thick-filament length, not detachment. This is a Scientific Reasoning and Problem Solving question because you must apply the sliding filament model to predict how each sarcomere band''s dimensions respond to shortening.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '6facf011-1034-4e2e-b710-47c288784ab6';
DELETE FROM question_distractor_metadata WHERE question_id = '6facf011-1034-4e2e-b710-47c288784ab6';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6facf011-1034-4e2e-b710-47c288784ab6', 'B', 'misconception', 'conflates constant filament length with constant band width'),
  ('6facf011-1034-4e2e-b710-47c288784ab6', 'C', 'adjacent_fact', 'true resting fact misapplied to the contracted state'),
  ('6facf011-1034-4e2e-b710-47c288784ab6', 'D', 'reversed_relationship', 'right band, wrong mechanism (invokes detachment instead of fixed filament length)');

-- [Joints & Movement] ans=C medium skill2
UPDATE questions SET
  question_text = 'A physical therapist evaluates a patient whose elbow joint has healed in a fully mobile state but whose shoulder is completely immobilized in a cast. Holding the upper arm fixed, the patient is asked to move the forearm through its full available range at the elbow alone. Which movement is the elbow capable of producing under these conditions?',
  options = '[{"label": "A", "text": "Abduction of the forearm"}, {"label": "B", "text": "Medial rotation of the forearm"}, {"label": "C", "text": "Flexion of the forearm"}, {"label": "D", "text": "Circumduction of the forearm"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Joints are classified functionally by how many planes of motion they permit: the elbow is a hinge joint, which the textbook states "allows only for bending and straightening motions along a single axis," making it a uniaxial joint. Because the shoulder is immobilized, motion must come from the elbow alone, so only movements available at a uniaxial hinge joint are possible. (Choice A) is incorrect: abduction is a medial-lateral limb movement in the coronal plane that occurs at condyloid, saddle, and ball-and-socket joints; the uniaxial hinge of the elbow cannot move the forearm laterally away from the body. (Choice B) is incorrect: medial rotation of the limb around its long axis "can only occur at the multiaxial shoulder and hip joints," so it is not available at the elbow, and with the shoulder immobilized it cannot occur at all. (Choice C) is correct: bending the forearm to decrease the angle between the humerus and the bones of the forearm is flexion, an anterior-going motion at the elbow that the uniaxial hinge joint permits along its single axis. (Choice D) is incorrect: circumduction is the sequential combination of flexion, abduction, extension, and adduction and requires a biaxial or multiaxial joint; a uniaxial hinge cannot supply the abduction/adduction components needed to trace a circle. This is a Scientific Reasoning and Problem Solving question because you must apply the functional classification of the elbow as a uniaxial hinge joint to determine which of several named movements its structure can actually produce.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '84f9f113-0578-44de-9916-ea3708cdf95a';
DELETE FROM question_distractor_metadata WHERE question_id = '84f9f113-0578-44de-9916-ea3708cdf95a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('84f9f113-0578-44de-9916-ea3708cdf95a', 'A', 'misconception', 'applies_a_ball_and_socket_movement_to_a_hinge_joint'),
  ('84f9f113-0578-44de-9916-ea3708cdf95a', 'B', 'misconception', 'assumes_rotation_is_available_at_any_synovial_joint'),
  ('84f9f113-0578-44de-9916-ea3708cdf95a', 'D', 'misconception', 'assumes_all_mobile_joints_permit_circumduction');

-- [Sarcomere Structure] ans=A hard skill2
UPDATE questions SET
  question_text = 'A physiologist images the same skeletal muscle fiber by electron microscopy in a fully relaxed state and again while it is maximally contracted, and measures the width of individual sarcomere regions in each state. Assuming the sliding filament model, which region''s measured width is expected to be essentially unchanged between the relaxed and contracted images?

I. The A band (the region spanned by the thick filaments)
II. The I band (the region containing only thin filaments)
III. The distance between adjacent Z-discs',
  options = '[{"label": "A", "text": "I only"}, {"label": "B", "text": "II only"}, {"label": "C", "text": "I and III only"}, {"label": "D", "text": "II and III only"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' In the sliding filament model, the thin filaments are pulled past the thick filaments and slide toward the center of the sarcomere; the filaments themselves do not shorten, so only the regions defined by filament overlap or by thin-filament-only zones change size. The textbook states that "when a sarcomere contracts, the Z lines move closer together, and the I band becomes smaller" while "the A band stays the same width," because the A band corresponds to the fixed length of the thick filaments. (Choice A) is correct: the A band is the span of the thick (myosin) filaments, and because the filaments slide rather than shorten, the thick-filament length—and therefore the A band width—is essentially unchanged from relaxation to contraction. (Choice B) is incorrect: the I band is the thin-filament-only zone, and as the thin filaments slide inward the I band narrows, so its width does change; this choice also wrongly implies the A band changes. (Choice C) is incorrect: it correctly includes the A band but wrongly includes the Z-disc spacing, which is the full sarcomere length and shortens as the Z-discs are pulled toward each other during contraction. (Choice D) is incorrect: both the I band and the Z-to-Z distance shrink during contraction, so neither is the region that stays constant. This is a Scientific Reasoning and Problem Solving question because you must apply the sliding filament model to a measured micrograph and reason out which sarcomere region reflects an unchanging filament length rather than a changing overlap or spacing.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'aab6e327-c6f1-47b3-a0a8-f9f67f5e623a';
DELETE FROM question_distractor_metadata WHERE question_id = 'aab6e327-c6f1-47b3-a0a8-f9f67f5e623a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('aab6e327-c6f1-47b3-a0a8-f9f67f5e623a', 'B', 'misconception', 'assumes the shrinking I band, rather than the constant A band, is the invariant region'),
  ('aab6e327-c6f1-47b3-a0a8-f9f67f5e623a', 'C', 'misconception', 'believes Z-disc spacing (whole sarcomere length) stays constant during contraction'),
  ('aab6e327-c6f1-47b3-a0a8-f9f67f5e623a', 'D', 'misconception', 'treats all bands that are not the thick-filament span as unchanging');

-- [Bone Matrix & Microstructure] ans=B medium skill2
UPDATE questions SET
  question_text = 'A child is born with a genetic disorder that severely impairs production of the collagen fibers normally deposited in the bone matrix; the deposition of hydroxyapatite mineral proceeds normally. Compared with healthy bone, the child''s bones would most likely be:',
  options = '[{"label": "A", "text": "more flexible and prone to bending under load"}, {"label": "B", "text": "brittle and prone to shattering under load"}, {"label": "C", "text": "unable to store calcium for release into the blood"}, {"label": "D", "text": "softer and easily compressed into a misshapen form"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' The bone matrix is a calcium-protein composite: an organic framework of collagen fibers on which an inorganic mineral, hydroxyapatite (a form of calcium phosphate), crystallizes. The two components divide the mechanical labor — the hydroxyapatite crystals give bone its hardness and strength, while the collagen fibers give it flexibility so that it is not brittle (OpenStax A&P 2e, lines 9557–9558). The text states this explicitly as a pair of thought experiments: without collagen, bones would be brittle and shatter easily; without mineral crystals, bones would flex and provide little support (lines 7015–7016). (Choice A) is incorrect: increased flexibility and bending are what result when the mineral component is lost, not the collagen — the text notes that without mineral crystals bone would flex and provide little support, so this reverses which component was impaired. (Choice B) is correct: collagen fibers are what keep bone from being brittle, so severely reducing collagen while mineral deposition continues leaves an over-mineralized matrix that is hard but brittle and prone to shattering under load (lines 7015–7016, 9557–9558). (Choice C) is incorrect: calcium is stored in and released from the mineral (hydroxyapatite) fraction of the matrix, which is deposited normally here, so calcium-storage capacity is retained; the mechanical failure, not a storage failure, is the key consequence of losing collagen. (Choice D) is incorrect: softening and compression into a misshapen form describe under-mineralized bone, as seen when calcium/mineral is lacking (for example rickets, lines 8550–8551); a bone with normal mineral but deficient collagen is not soft but brittle. This is a Scientific Reasoning and Problem Solving question because you must apply the division of labor between the organic (collagen) and inorganic (hydroxyapatite) components of the bone matrix to predict the mechanical outcome of losing one component in a novel scenario.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'fc28327f-05d8-4fc0-9e5f-99c3a9e3d0be';
DELETE FROM question_distractor_metadata WHERE question_id = 'fc28327f-05d8-4fc0-9e5f-99c3a9e3d0be';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('fc28327f-05d8-4fc0-9e5f-99c3a9e3d0be', 'A', 'reversed_relationship', 'swapping the mechanical roles of the organic and inorganic matrix components'),
  ('fc28327f-05d8-4fc0-9e5f-99c3a9e3d0be', 'C', 'partial_truth', 'invoking the calcium-storage function of bone, which is unaffected here'),
  ('fc28327f-05d8-4fc0-9e5f-99c3a9e3d0be', 'D', 'misconception', 'confusing collagen loss with mineral loss (rickets-style softening)');

-- [Muscle Types & Characteristics] ans=A hard skill2
UPDATE questions SET
  question_text = 'A physiologist isolates two single skeletal-muscle fibers from a mixed muscle and measures each while stimulating maximal contractions:

| Property | Fiber 1 | Fiber 2 |
|---|---|---|
| Maximum shortening velocity | Fast | Slow |
| Mitochondrial density | Low | High |
| Myoglobin content | Low | High |
| Time to fatigue | Short | Long |

Both fibers generate the same peak force per cross-sectional area. Which difference most directly accounts for the faster maximum shortening velocity of Fiber 1?',
  options = '[{"label": "A", "text": "Its myosin hydrolyzes ATP at a higher rate, cycling cross-bridges faster"}, {"label": "B", "text": "Its lower mitochondrial density leaves more room for contractile filaments"}, {"label": "C", "text": "Its sparse myoglobin lets oxygen diffuse to the filaments more rapidly"}, {"label": "D", "text": "Its reliance on aerobic respiration yields more ATP per glucose molecule"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Skeletal muscle fibers are classified by how fast they contract and how they produce ATP; the speed of contraction is set by how quickly a fiber''s myosin ATPase can hydrolyze ATP to drive the cross-bridge cycle, which pulls thin filaments toward the sarcomere center. Fiber 1 is a fast (glycolytic) fiber and Fiber 2 is a slow oxidative fiber, but the data ask specifically about shortening velocity, not endurance. (Choice A) is correct: the textbook states that "the speed of contraction is dependent on how quickly myosin''s ATPase hydrolyzes ATP to produce cross-bridge action," and that "fast fibers hydrolyze ATP approximately twice as quickly as slow fibers, resulting in much quicker cross-bridge cycling" — a faster myosin ATPase directly produces the faster shortening velocity. (Choice B) is incorrect: mitochondrial density chiefly determines a fiber''s capacity for aerobic ATP production and its fatigue resistance, not the intrinsic rate at which cross-bridges cycle; "freeing room for filaments" does not set shortening velocity, and both fibers here produce equal force per area. (Choice C) is incorrect: myoglobin is an oxygen-storage molecule that supports sustained aerobic metabolism (and gives slow fibers their red color); low myoglobin does not speed oxygen delivery to accelerate contraction, and oxygen supply governs fatigue resistance rather than contraction speed. (Choice D) is incorrect: aerobic respiration does yield more ATP per glucose, but that greater efficiency underlies the slow oxidative fiber''s fatigue resistance, not fast contraction — a higher ATP yield per cycle would, if anything, describe Fiber 2, and it does not determine how fast myosin cycles. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between myosin ATPase activity and cross-bridge cycling rate to the measured fiber properties to isolate the one difference that sets shortening velocity.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '9832b22b-3dd9-45fe-ba3e-740069bacfb7';
DELETE FROM question_distractor_metadata WHERE question_id = '9832b22b-3dd9-45fe-ba3e-740069bacfb7';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('9832b22b-3dd9-45fe-ba3e-740069bacfb7', 'B', 'misconception', 'conflates_structural_space_with_function'),
  ('9832b22b-3dd9-45fe-ba3e-740069bacfb7', 'C', 'reversed_relationship', 'myoglobin_speeds_delivery'),
  ('9832b22b-3dd9-45fe-ba3e-740069bacfb7', 'D', 'partial_truth', 'atp_yield_vs_cycling_rate');

-- [Sarcomere Structure] ans=B medium skill2
UPDATE questions SET
  question_text = 'During a maximal isotonic contraction, a researcher records electron micrographs of a single sarcomere at rest and again at full shortening. Comparing the two images, how do the widths of the A band and the I band change as the sarcomere contracts?',
  options = '[{"label": "A", "text": "The A band narrows and the I band stays the same width"}, {"label": "B", "text": "The I band narrows and the A band stays the same width"}, {"label": "C", "text": "Both the A band and the I band narrow proportionally"}, {"label": "D", "text": "Both the A band and the I band stay the same width"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' Under the sliding filament model, a sarcomere shortens because the thin (actin) filaments are pulled to slide past the thick (myosin) filaments toward the center, drawing the Z-discs closer together; the filaments themselves do not shorten. The A band corresponds to the full length of the thick filaments, whereas the I band is the region occupied only by thin filaments not yet overlapped by thick filaments. (Choice B) is correct: because thick filament length is fixed, the A band stays the same width, while the thin filaments sliding inward reduce the non-overlap zone, so the I band narrows (the textbook states that during contraction "the Z lines move closer together, and the I band becomes smaller. The A band stays the same width."). (Choice A) is incorrect: it reverses the relationship—students who assume the darkest, thickest-looking band must be the part that "contracts" wrongly shrink the A band and leave the I band fixed, but the A band tracks the unchanging thick-filament length. (Choice C) is incorrect: it assumes the whole sarcomere shrinks uniformly like a stretched spring relaxing, but shortening comes from filament sliding, not from any band''s own filaments compressing, so the A band width is preserved. (Choice D) is incorrect: if neither band changed, the sarcomere could not shorten at all; the I band must narrow as the zone of overlap increases. This is a Scientific Reasoning and Problem Solving question because you must apply the sliding filament model to predict which band width is constrained by fixed thick-filament length and which changes as overlap increases.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '697f24c3-3998-4d76-bab5-6a9e42e037fb';
DELETE FROM question_distractor_metadata WHERE question_id = '697f24c3-3998-4d76-bab5-6a9e42e037fb';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('697f24c3-3998-4d76-bab5-6a9e42e037fb', 'A', 'reversed_relationship', 'swaps which band is fixed vs. shrinking'),
  ('697f24c3-3998-4d76-bab5-6a9e42e037fb', 'C', 'misconception', 'assumes uniform proportional shrinkage of the whole sarcomere'),
  ('697f24c3-3998-4d76-bab5-6a9e42e037fb', 'D', 'misconception', 'believes band widths are static so filaments compress in place');

-- [Muscle Energetics & Fatigue] ans=A medium skill2
UPDATE questions SET
  question_text = 'A sprinter runs an all-out 400 m race and then stops and stands still at the finish line. Her rate of oxygen consumption is recorded before, during, and after the race:

| Phase | O2 consumption |
|---|---|
| Standing at rest before the race | Baseline |
| During the 400 m sprint | Sharply elevated |
| First several minutes after she stops running | Still well above baseline, then slowly declining |

Although her muscles are no longer contracting after she stops, her oxygen consumption stays elevated for several minutes. Which process most directly accounts for this elevated post-exercise oxygen consumption?',
  options = '[{"label": "A", "text": "Oxygen is used to rebuild creatine phosphate stores and to reconvert accumulated lactic acid"}, {"label": "B", "text": "Contracting muscle fibers continue to consume oxygen to sustain aerobic ATP production"}, {"label": "C", "text": "Myoglobin releases its stored oxygen to resupply the working mitochondria"}, {"label": "D", "text": "Anaerobic glycolysis accelerates to replace the ATP spent during the sprint"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Organ Systems.'' During an all-out sprint, much of the ATP is produced anaerobically, and the textbook defines the resulting oxygen debt as "the amount of oxygen needed to compensate for ATP produced without oxygen during muscle contraction"; this debt is repaid after exercise, which is why "oxygen intake is elevated, even after exercise has stopped." The task is to reason about why oxygen uptake stays high once contraction has ceased, not simply to name an energy source. (Choice A) is correct: the textbook states that after intense activity, oxygen is required to "restore ATP and creatine phosphate levels, convert lactic acid to pyruvic acid, and, in the liver, to convert lactic acid into glucose or glycogen," so the elevated recovery oxygen consumption reflects repaying this oxygen debt while the muscle is no longer contracting. (Choice B) is incorrect: this attributes the elevated oxygen use to ongoing contractile work, but the stem specifies the muscles have stopped contracting, so sustained aerobic ATP production to power contraction cannot be the cause. (Choice C) is incorrect: myoglobin is an oxygen reserve that releases stored O2 to support aerobic respiration during activity, so it would supply oxygen while she is running rather than drive extra oxygen intake after she stops. (Choice D) is incorrect: glycolysis is an anaerobic, "non-oxygen-dependent" process, so accelerating it would not consume the additional inhaled oxygen; in fact restoring ATP and clearing lactic acid during recovery is oxygen-dependent, which is the opposite of anaerobic glycolysis. This is a Scientific Reasoning and Problem Solving question because you must apply the concept of oxygen debt to explain why post-exercise oxygen consumption remains elevated after muscular contraction has ceased.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '2b8a8094-9302-4a9c-98dd-061c52c2c2cf';
DELETE FROM question_distractor_metadata WHERE question_id = '2b8a8094-9302-4a9c-98dd-061c52c2c2cf';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('2b8a8094-9302-4a9c-98dd-061c52c2c2cf', 'B', 'misconception', 'confuses recovery oxygen uptake with ongoing contractile work'),
  ('2b8a8094-9302-4a9c-98dd-061c52c2c2cf', 'C', 'adjacent_fact', 'myoglobin oxygen store invoked in the wrong phase'),
  ('2b8a8094-9302-4a9c-98dd-061c52c2c2cf', 'D', 'reversed_relationship', 'treats an anaerobic process as the driver of increased oxygen use');

COMMIT;
