-- Biology Ch4: The Nervous System — REMEDIATED (quality + scope sweep); grounded in OpenStax A&P 2e
-- Remediated 19/19 flagged questions in place (UPDATE by id, ids preserved). 17 re-engineered, 2 scope-flagged.
-- distractor_category mapped to the question_distractor_metadata CHECK set. Idempotent; safe to re-run.

BEGIN;

-- [Neuron Anatomy & Signal Flow] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher applies a drug that blocks voltage-gated sodium channels to a single, tightly localized region of a multipolar neuron. After treatment, the neuron''s dendrites still develop graded potentials when synapses are activated, and its axon still conducts an action potential normally when one is triggered artificially partway down the fiber. However, the neuron no longer initiates its own action potentials in response to incoming synaptic input, no matter how strong that input is. Which region of the neuron did the drug most likely block?',
  options = '[{"label": "A", "text": "The axon hillock and initial segment"}, {"label": "B", "text": "The dendritic branches"}, {"label": "C", "text": "The axon terminals"}, {"label": "D", "text": "The nodes of Ranvier"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' Information flows through a neuron with a fixed polarity: dendrites and the cell body receive and sum graded potentials, and if the summed voltage reaches threshold at the trigger zone, an all-or-none action potential is initiated and then propagated down the axon to the terminals. OpenStax Anatomy and Physiology 2e states that the axon hillock is a tapering of the cell body that narrows into the initial segment, and that "action potentials are generated in the trigger zone, which is a combination of the axon hillock and initial segment." The experiment isolates the initiation step: reception (dendrites) and conduction (axon) are intact, but the neuron cannot start an action potential of its own. (Choice A) is correct: the axon hillock and initial segment form the trigger zone, the region with the density of voltage-gated sodium channels where summed graded potentials are converted into an action potential; blocking those channels here abolishes initiation while leaving reception and downstream conduction untouched. (Choice B) is incorrect: dendrites receive input and produce graded potentials, which the scenario says are still intact, so a dendritic block would not selectively eliminate action-potential initiation. (Choice C) is incorrect: axon terminals are the output end where the action potential triggers neurotransmitter release onto the target cell; blocking them would impair signaling to other cells, not the neuron''s own ability to fire. (Choice D) is incorrect: the nodes of Ranvier are gaps in the myelin sheath that speed propagation along the axon, but the scenario states axonal conduction is still normal, so they are not the site of initiation. This is a Scientific Reasoning and Problem Solving question because you must apply the concept of neuronal signal flow to deduce which region generates the action potential from the pattern of preserved and lost functions.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '544a32e9-5580-45ba-a8cc-4bceda653aa7';
DELETE FROM question_distractor_metadata WHERE question_id = '544a32e9-5580-45ba-a8cc-4bceda653aa7';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('544a32e9-5580-45ba-a8cc-4bceda653aa7', 'B', 'misconception', 'action potentials begin where input is received'),
  ('544a32e9-5580-45ba-a8cc-4bceda653aa7', 'C', 'misconception', 'the output/terminal end starts the signal'),
  ('544a32e9-5580-45ba-a8cc-4bceda653aa7', 'D', 'misconception', 'propagation gaps are where the impulse originates');

-- [Myelin & Myelinating Glia] ans=A hard skill2
UPDATE questions SET
  question_text = 'In multiple sclerosis, the immune system strips myelin from central axons while leaving the axonal membrane, its ion pumps, and its voltage-gated Na+ channels intact. A neurologist records from a single demyelinated axon and finds that action potentials still occur but travel far more slowly than before. Which change best explains the slowed conduction along the affected axon?',
  options = '[{"label": "A", "text": "Local current now leaks across the internodal membrane, so depolarization can no longer spread efficiently to the next node."}, {"label": "B", "text": "The loss of myelin removes the axon''s only source of ATP, so the Na+/K+ pump can no longer restore the resting potential between spikes."}, {"label": "C", "text": "Voltage-gated Na+ channels are destroyed along with the myelin, forcing the signal to travel by passive spread alone."}, {"label": "D", "text": "Without myelin the axon reverses its polarity, so each action potential must now propagate backward toward the cell body."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' In a myelinated axon, voltage-gated Na+ channels are clustered only at the nodes of Ranvier; between nodes the myelin acts as insulation so that the inward Na+ current spreads passively down the internode and still arrives above threshold at the next node, producing fast saltatory ("leaping") conduction. The textbook notes that when myelin insulation is compromised, "electrical signaling [becomes] slower," which is why demyelinating diseases like MS impair conduction even when the axon and its channels survive. (Choice A) is correct: myelin''s job is to keep the internodal membrane sealed so charge does not dissipate before reaching the next node; stripping it lets local current leak out, the depolarization falls off before the next node, and the axon reverts toward slow continuous conduction. (Choice B) is incorrect: myelin is glial-derived insulation, not a metabolic fuel source, and the axon''s mitochondria and Na+/K+ pumps are unaffected by demyelination, so ATP supply and repolarization are not the bottleneck. (Choice C) is incorrect: the stem specifies the voltage-gated Na+ channels remain intact, and it is the loss of insulation—not loss of channels—that slows the signal; the channels are still present and can still fire at the nodes. (Choice D) is incorrect: myelin does not set the direction of propagation; the action potential still travels toward the axon terminals because the membrane behind it is refractory, regardless of whether myelin is present. This is a Scientific Reasoning and Problem Solving question because you must apply the insulating role of myelin in saltatory conduction to a novel demyelination scenario and predict the biophysical cause of slowed signaling.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '01b37a48-8ac2-4952-9962-20344ef1677b';
DELETE FROM question_distractor_metadata WHERE question_id = '01b37a48-8ac2-4952-9962-20344ef1677b';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('01b37a48-8ac2-4952-9962-20344ef1677b', 'B', 'misconception', 'wrong-mechanism'),
  ('01b37a48-8ac2-4952-9962-20344ef1677b', 'C', 'misconception', 'confuses-insulation-with-channels'),
  ('01b37a48-8ac2-4952-9962-20344ef1677b', 'D', 'misconception', 'wrong-direction-of-propagation');

-- [CNS Tissue Organization] ans=A medium skill2
UPDATE questions SET
  question_text = 'During an ischemic stroke, neurons in the affected region of the brain fire repeatedly and then fail, causing potassium ions to accumulate to abnormally high levels in the extracellular fluid surrounding them. A neuroscientist wants to identify the glial cell that normally counteracts this buildup by taking up excess extracellular potassium and helping restore the ionic environment neurons need to signal. Which cell fills this role?',
  options = '[{"label": "A", "text": "The astrocyte, which regulates the concentration of ions in the extracellular space around CNS neurons"}, {"label": "B", "text": "The oligodendrocyte, which wraps insulating myelin around axon segments of CNS neurons"}, {"label": "C", "text": "The microglial cell, which ingests damaged cells and pathogens throughout CNS tissue"}, {"label": "D", "text": "The ependymal cell, which filters blood to produce the cerebrospinal fluid that bathes the CNS"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' The four glial cells of the central nervous system each perform a distinct supporting role, and answering requires matching the described task—buffering extracellular ions—to the correct cell rather than recognizing a named structure. OpenStax A&P 2e states that astrocytes support CNS neurons by "maintaining the concentration of chemicals in the extracellular space" and that following an ischemic event in which "extracellular K+ levels are elevated," the "astrocytes in the area are equipped to clear excess K+ to aid the pump." Because the stimulus describes potassium accumulating outside neurons and asks which cell takes it up to restore the ionic environment, the answer is the cell whose defined job is managing extracellular ion concentrations. (Choice A) is correct: the astrocyte is the CNS glial cell that maintains the extracellular chemical environment, including clearing excess K+ after neuronal activity, so it is the cell that counteracts the potassium buildup. (Choice B) is incorrect: the oligodendrocyte insulates CNS axons with myelin, which speeds signal conduction but does nothing to remove ions from the extracellular fluid. (Choice C) is incorrect: microglia act as resident macrophages that phagocytose damaged cells and pathogens; they perform immune surveillance rather than ionic buffering, though tissue damage from a stroke could later recruit them. (Choice D) is incorrect: ependymal cells line the ventricles and produce cerebrospinal fluid at the choroid plexus, a bulk-fluid function distinct from locally regulating extracellular ion levels next to signaling neurons. This is a Scientific Reasoning and Problem Solving question because you must apply the distinct functional roles of the CNS glial cell types to a novel physiological scenario and infer which cell restores the extracellular ionic balance.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '43111300-983f-46bf-b4bd-1aaa25037bd9';
DELETE FROM question_distractor_metadata WHERE question_id = '43111300-983f-46bf-b4bd-1aaa25037bd9';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('43111300-983f-46bf-b4bd-1aaa25037bd9', 'B', 'misconception', 'confusing the insulating/myelinating glial cell with the ion-buffering one'),
  ('43111300-983f-46bf-b4bd-1aaa25037bd9', 'C', 'adjacent_fact', 'invoking the immune glial cell because the scenario involves tissue damage'),
  ('43111300-983f-46bf-b4bd-1aaa25037bd9', 'D', 'partial_truth', 'citing a real CNS glial function (CSF production) that does not address local extracellular ions');

-- [Neuron Functional Types] ans=A medium skill2
UPDATE questions SET
  question_text = 'A histologist examines a single neuron isolated from a peripheral nerve. A lone process emerges from the cell body and shortly divides into two branches. One branch ends in fine endings embedded in the skin, where it responds to mechanical deformation; the other branch travels toward the spinal cord and forms synapses within the central nervous system. The cell body itself sits in a ganglion just outside the cord and lies along the pathway rather than at either end of it. Based on this architecture, the neuron is best classified by function as:',
  options = '[{"label": "A", "text": "A sensory (afferent) neuron"}, {"label": "B", "text": "A motor (efferent) neuron"}, {"label": "C", "text": "An interneuron (association neuron)"}, {"label": "D", "text": "A postganglionic autonomic motor neuron"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' Neurons can be grouped by their structural shape (unipolar, bipolar, multipolar) or by their function (sensory/afferent, motor/efferent, interneuron), and the two schemes are correlated: the described cell has a single process that splits into two branches, with its cell body positioned along the pathway inside a ganglion, which is the signature of a unipolar (pseudo-unipolar) neuron. OpenStax Anatomy & Physiology 2e states that in these cells the peripheral branch bears dendritic endings that receive the stimulus and the other branch "projects... into the central nervous system," and critically that "unipolar cells are exclusively sensory neurons." The key inference is directional and structural: information flows from a peripheral stimulus toward the CNS, and only the sensory class has this pseudo-unipolar architecture. (Choice A) is correct: dendritic endings in the skin detect the stimulus and the axon carries the signal inward to the CNS, which is the afferent (sensory) direction, and the single-process, ganglion-seated shape is unique to sensory neurons. (Choice B) is incorrect: a motor (efferent) neuron carries commands outward from the CNS to an effector, the opposite direction from the described periphery-to-CNS flow, and motor neurons are multipolar rather than pseudo-unipolar. (Choice C) is incorrect: an interneuron connects neurons entirely within the CNS and does not extend a process out to receive a peripheral stimulus, so a cell with endings in the skin and a body in a peripheral ganglion cannot be an interneuron. (Choice D) is incorrect: a postganglionic autonomic motor neuron does sit in a peripheral ganglion, but it is efferent—its axon projects away from the ganglion to a visceral effector such as a gland or smooth muscle—whereas this cell''s axon projects into the CNS and its dendrites sense a stimulus. This is a Scientific Reasoning and Problem Solving question because you must apply the structure-to-function correlation of neuron classification—reading the single bifurcating process, the ganglionic cell body, and the periphery-to-CNS direction of signal flow—to infer the functional class rather than recall a definition directly.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'a713b712-af90-4ec8-97c3-69b2217dc0d5';
DELETE FROM question_distractor_metadata WHERE question_id = 'a713b712-af90-4ec8-97c3-69b2217dc0d5';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('a713b712-af90-4ec8-97c3-69b2217dc0d5', 'B', 'reversed_relationship', 'confusing afferent (into CNS) with efferent (out of CNS) direction of flow'),
  ('a713b712-af90-4ec8-97c3-69b2217dc0d5', 'C', 'misconception', 'treating any relay neuron as an interneuron regardless of CNS-only location'),
  ('a713b712-af90-4ec8-97c3-69b2217dc0d5', 'D', 'adjacent_fact', 'over-weighting the ganglion location cue and assuming a peripheral-ganglion cell must be autonomic/efferent');

-- [Neuron Anatomy & Signal Flow] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher stimulates several dendrites of a multipolar neuron and records where the action potential first arises. Even when a dendrite receives an unusually strong depolarizing input, the impulse reliably originates at the axon hillock rather than near the stimulated dendrite. Which membrane property of the axon hillock best accounts for its consistently being the site of impulse initiation?',
  options = '[{"label": "A", "text": "It has the highest density of voltage-gated sodium channels of any region of the neuron"}, {"label": "B", "text": "It is the most heavily myelinated region of the neuron"}, {"label": "C", "text": "It has the highest density of ligand-gated neurotransmitter receptors of any region of the neuron"}, {"label": "D", "text": "It has the highest density of sodium-potassium pumps of any region of the neuron"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' Graded potentials from many synapses spread passively toward the axon hillock and initial segment, where they summate; an action potential fires only where the membrane can reach threshold and rapidly regenerate the depolarization. According to OpenStax A&P 2e, graded potentials "summate at a specific location at the beginning of the axon to initiate the action potential, namely the initial segment," and "the axon hillock is essentially the initial segment of the axon," a region that has "a high density of voltage-gated Na+ channels that initiate the depolarizing phase of the action potential." (Choice A) is correct: because voltage-gated sodium channels are packed most densely here, this region has the lowest threshold, so summed inputs trigger the regenerative sodium influx of the action potential at the hillock before they can do so anywhere else. (Choice B) is incorrect: the axon hillock is not the most heavily myelinated region—it is unmyelinated, and myelin insulates the axon between nodes of Ranvier downstream; insulation would not lower threshold or explain why the impulse begins at the hillock. (Choice C) is incorrect: ligand-gated receptors are concentrated at the postsynaptic membranes of dendrites and the soma, where they produce graded potentials; they do not generate the all-or-none action potential and are not enriched at the hillock. (Choice D) is incorrect: the sodium-potassium pump restores resting gradients over time and does not open in response to depolarization, so a high pump density cannot account for rapid, threshold-triggered impulse initiation. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between voltage-gated sodium channel density and firing threshold to explain why the action potential originates at the axon hillock rather than at a more strongly stimulated dendrite.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'dc9aaeee-a329-4db1-93d6-8f61f958e388';
DELETE FROM question_distractor_metadata WHERE question_id = 'dc9aaeee-a329-4db1-93d6-8f61f958e388';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('dc9aaeee-a329-4db1-93d6-8f61f958e388', 'B', 'misconception', 'conflating the myelinated axon with the impulse-initiation site'),
  ('dc9aaeee-a329-4db1-93d6-8f61f958e388', 'C', 'misconception', 'attributing impulse initiation to the input (ligand-gated) receptors that produce graded potentials'),
  ('dc9aaeee-a329-4db1-93d6-8f61f958e388', 'D', 'misconception', 'confusing the resting-gradient Na+/K+ pump with the voltage-gated channels that fire the action potential');

-- [Support Glia: Astrocytes, Ependymal & Microglia] ans=D hard skill2
UPDATE questions SET
  question_text = 'A histologist examines CNS tissue from a patient and finds that one glial population, which normally forms a single ciliated layer lining the ventricles and wraps around the blood capillaries of the choroid plexus, has been selectively destroyed. Following this loss, the clear ventricular fluid — normally a filtrate of blood containing water, electrolytes, and small molecules — is no longer generated. Which glial cell was lost, and what specific role does its position at the capillary wall serve?',
  options = '[{"label": "A", "text": "Astrocytes, which extend processes onto capillaries to help regulate ion concentrations in the extracellular fluid."}, {"label": "B", "text": "Microglia, which contact capillaries to intercept and phagocytose pathogens entering the nervous tissue."}, {"label": "C", "text": "Oligodendrocytes, which reach out to capillaries to wrap nearby central axons in insulating myelin."}, {"label": "D", "text": "Ependymal cells, which surround capillaries to filter blood into a fluid that circulates through the CNS."}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' The four CNS glia each occupy characteristic positions and perform distinct jobs, and the diagnostic clue here is a cell that lines the ventricles, bears cilia, and physically wraps the capillaries of the choroid plexus. OpenStax Anatomy and Physiology 2e states that at the choroid plexus, ependymal cells "surround blood capillaries and filter the blood to make CSF," a fluid that is "essentially water, small molecules, and electrolytes," and that these cells "line each ventricle" and have "cilia on their apical surface." (Choice A) is incorrect: astrocytes do send processes onto capillaries and do "maintain the concentration of chemicals in the extracellular space," but their capillary contact contributes to the blood-brain barrier and ion buffering, not to filtering blood into ventricular fluid. (Choice B) is incorrect: microglia are the CNS-resident macrophages that "ingest and digest" diseased cells and pathogens, so although immune surveillance is real, it does not generate a blood-derived fluid. (Choice C) is incorrect: oligodendrocytes reach out to axon segments to "insulate it in myelin," not to capillaries, so myelination is unrelated to producing ventricular fluid. (Choice D) is correct: only ependymal cells occupy the choroid plexus, wrap its capillaries, and filter blood to produce the clear fluid that circulates through the CNS, so their loss halts production of that fluid. This is a Scientific Reasoning and Problem Solving question because you must apply the structural and positional clues (ventricular lining, cilia, capillary-wrapping at the choroid plexus) to identify the glial cell whose blood-filtering function is described, rather than recalling a stated cushioning role.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = '6ba0ec85-ce95-4f26-aae2-3ce410e33d25';
DELETE FROM question_distractor_metadata WHERE question_id = '6ba0ec85-ce95-4f26-aae2-3ce410e33d25';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6ba0ec85-ce95-4f26-aae2-3ce410e33d25', 'A', 'adjacent_fact', 'correct-function-wrong-outcome'),
  ('6ba0ec85-ce95-4f26-aae2-3ce410e33d25', 'B', 'adjacent_fact', 'correct-function-wrong-outcome'),
  ('6ba0ec85-ce95-4f26-aae2-3ce410e33d25', 'C', 'misconception', 'role-confusion');

-- [Neuron Anatomy & Signal Flow] ans=C medium skill2
UPDATE questions SET
  question_text = 'A researcher records from a multipolar neuron and confirms that a normal action potential is still generated at its trigger zone in response to synaptic input. However, a drug applied to one region of the same neuron prevents that action potential from ever reaching and exciting the downstream target cell, even though neurotransmitter release machinery and the target''s receptors are intact. At which structure is the drug most likely acting?',
  options = '[{"label": "A", "text": "The dendrites"}, {"label": "B", "text": "The cell body (soma)"}, {"label": "C", "text": "The axon"}, {"label": "D", "text": "The postsynaptic membrane of the target cell"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' Information flows through a neuron in one direction—from the dendrites, across the cell body, and down the axon—giving the neuron its polarity; the action potential is generated at the trigger zone (axon hillock plus initial segment) and then propagates along the axon to the axon terminals and synaptic end bulbs, where it triggers neurotransmitter release onto the target. The scenario fixes the problem downstream of impulse generation but upstream of the target: the action potential is made normally, yet it never arrives to excite the next cell, and both the release machinery and the target receptors are known to be intact. (Choice A) is incorrect: the dendrites lie on the input side of the neuron, receiving synaptic signals and carrying them inward to the cell body; blocking them would prevent input, but here the action potential is already being generated normally. (Choice B) is incorrect: the cell body sits before the trigger zone in the signal path, so a lesion there would impair generation of the impulse, yet the stem states the action potential is produced normally at the trigger zone. (Choice C) is correct: the axon is the conducting output fiber that carries the action potential away from the trigger zone toward the terminals, so a drug that blocks propagation along the axon would stop the already-generated impulse from ever reaching the target, exactly matching the observation. (Choice D) is incorrect: the postsynaptic membrane belongs to the target cell and carries its receptors, which the stem specifies are intact, so the failure lies in the presynaptic neuron''s own output pathway rather than at reception. This is a Scientific Reasoning and Problem Solving question because you must apply the fixed directional flow of signals through a neuron to locate where an intact impulse could be halted before reaching its target.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '0a2c3b3d-8bfb-4bf8-8320-df7270c98473';
DELETE FROM question_distractor_metadata WHERE question_id = '0a2c3b3d-8bfb-4bf8-8320-df7270c98473';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('0a2c3b3d-8bfb-4bf8-8320-df7270c98473', 'A', 'reversed_relationship', 'input-side structure confused for output pathway'),
  ('0a2c3b3d-8bfb-4bf8-8320-df7270c98473', 'B', 'misconception', 'placing the block before impulse generation despite normal trigger-zone firing'),
  ('0a2c3b3d-8bfb-4bf8-8320-df7270c98473', 'D', 'partial_truth', 'targeting the postsynaptic cell after stem rules out receptor failure');

-- [PNS: Somatic vs Autonomic] ans=D medium skill2
UPDATE questions SET
  question_text = 'A hiker rounds a bend and is startled by a snake on the trail. In the next second, several changes occur: her heart pounds faster, the pupils of her eyes widen, her palms begin to sweat, and she instantly jumps backward away from the snake. A physiologist reviewing these four responses wants to identify the one that is produced by the somatic nervous system rather than the autonomic nervous system. Which response should she select?',
  options = '[{"label": "A", "text": "The acceleration of her heart rate"}, {"label": "B", "text": "The widening of her pupils"}, {"label": "C", "text": "The onset of sweating on her palms"}, {"label": "D", "text": "The backward jump away from the snake"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' The peripheral nervous system is divided functionally: the somatic nervous system produces voluntary motor responses by contracting skeletal muscle (including reflexive skeletal-muscle movements), whereas the autonomic nervous system produces involuntary responses by acting on cardiac muscle, smooth muscle, and glandular tissue to regulate homeostasis. OpenStax Anatomy & Physiology 2e states that "the somatic nervous system causes contraction of skeletal muscles," while "the autonomic nervous system controls cardiac and smooth muscle, as well as glandular tissue," and it specifically notes that a startle response such as leaping back "is a reflex involving skeletal muscle contractions." Sorting each response by its effector tissue, rather than by whether it feels automatic, is the key to this problem. (Choice A) is incorrect: the heart is composed of cardiac muscle, an autonomic effector; the sympathetic division accelerates heart rate during the fight-or-flight response, so this is autonomic, not somatic. (Choice B) is incorrect: pupil diameter is set by smooth muscle of the iris, an autonomic effector, and sympathetic activation dilates the pupils to increase visual information—an autonomic response. (Choice C) is incorrect: sweat glands are glandular tissue controlled by the autonomic system, and their activation during a threat is a sympathetic (autonomic) response, not a somatic one. (Choice D) is correct: jumping backward is a contraction of skeletal muscle, the effector of the somatic nervous system; even though it happens reflexively without a conscious decision, it is a somatic motor response because skeletal muscle is involved. This is a Scientific Reasoning and Problem Solving question because you must apply the rule that somatic output acts on skeletal muscle while autonomic output acts on cardiac muscle, smooth muscle, and glands to classify each novel response by its effector tissue.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '199b981a-682c-4830-9e31-d92fc0c962ce';
DELETE FROM question_distractor_metadata WHERE question_id = '199b981a-682c-4830-9e31-d92fc0c962ce';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('199b981a-682c-4830-9e31-d92fc0c962ce', 'A', 'misconception', 'confusing effector tissue: treating rapid involuntary cardiac change as somatic'),
  ('199b981a-682c-4830-9e31-d92fc0c962ce', 'B', 'misconception', 'assuming a conscious sensory-related change (vision) is somatically controlled'),
  ('199b981a-682c-4830-9e31-d92fc0c962ce', 'C', 'misconception', 'classifying a glandular secretion as somatic because it is body-surface and noticeable');

-- [Neuron Functional Types] ans=C medium skill2
UPDATE questions SET
  question_text = 'During a physical exam, a physician taps the patellar tendon just below the kneecap. The tap briefly stretches the quadriceps, activating a muscle-spindle receptor. The receptor''s neuron carries this signal into the spinal cord and synapses directly onto the neuron whose axon leaves the cord to contract the quadriceps, producing the knee jerk with almost no delay. (A separate collateral branch quiets the antagonist hamstring muscles.) Considering only the direct two-neuron pathway that produces the quadriceps contraction, which functional class of reflex-arc neuron is absent from that pathway?',
  options = '[{"label": "A", "text": "The sensory (afferent) neuron"}, {"label": "B", "text": "The motor (efferent) neuron"}, {"label": "C", "text": "The interneuron"}, {"label": "D", "text": "The postganglionic autonomic neuron"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' A reflex arc is built from a set of functional neuron classes: sensory (afferent) neurons carry input from receptors into the CNS, motor (efferent) neurons carry output from the CNS to effectors, and interneurons sit entirely within the CNS as the integrating center that connects the afferent and efferent branches. OpenStax Anatomy & Physiology 2e defines a reflex arc as a circuit involving "a sensory input and motor output... and an integrating center to connect the two branches," and it distinguishes a monosynaptic reflex, "in which the sensory neuron directly activates the motor neuron," from a polysynaptic reflex such as the hot-stove withdrawal, in which an interneuron is interposed between them. The knee-jerk stretch reflex is monosynaptic: the muscle-spindle sensory neuron "will cause direct contraction of the muscle" by synapsing straight onto the motor neuron, so no integrating relay participates in the direct excitatory limb. (Choice A) is incorrect: the sensory (afferent) neuron is present—it is the muscle-spindle neuron that detects the stretch and carries that input into the spinal cord, forming the first neuron of the two-neuron pathway. (Choice B) is incorrect: the motor (efferent) neuron is present—it is the second neuron whose axon leaves the cord to contract the quadriceps, so removing it would eliminate the contraction the stem describes. (Choice C) is correct: because the sensory neuron synapses directly onto the motor neuron, the arc is monosynaptic and contains no interneuron in the excitatory pathway; the interneuron is the integrating class that would only appear if a relay were interposed between the afferent and efferent branches, as in a polysynaptic reflex. (Choice D) is incorrect: the postganglionic autonomic neuron is not one of the reflex arc''s functional classes at all—it belongs to the visceral (autonomic) efferent pathway that drives smooth muscle, cardiac muscle, and glands; the somatic knee-jerk reflex contracts skeletal muscle and never includes an autonomic neuron regardless of synapse count. This is a Scientific Reasoning and Problem Solving question because you must apply the functional classification of reflex-arc neurons and the monosynaptic-versus-polysynaptic distinction to infer, from the stated direct synapse, which neuron class is missing from the arc.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'f62255c8-f053-4943-87e1-f909f8decb25';
DELETE FROM question_distractor_metadata WHERE question_id = 'f62255c8-f053-4943-87e1-f909f8decb25';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('f62255c8-f053-4943-87e1-f909f8decb25', 'A', 'misconception', 'confuses which limb of the reflex arc is present'),
  ('f62255c8-f053-4943-87e1-f909f8decb25', 'B', 'misconception', 'assumes the output neuron is bypassed in an automatic reflex'),
  ('f62255c8-f053-4943-87e1-f909f8decb25', 'D', 'partial_truth', 'imports autonomic wiring into a somatic reflex');

-- [Myelin & Myelinating Glia] ans=A medium skill2
UPDATE questions SET
  question_text = 'In a patient with multiple sclerosis, an autoimmune process strips the myelin from axons in a CNS tract while leaving the axons themselves intact. Compared with a healthy axon, how is the propagation of an action potential along one of these affected axons most likely changed, and why?',
  options = '[{"label": "A", "text": "Conduction slows because depolarizing current now leaks across the bare membrane between nodes instead of jumping ahead"}, {"label": "B", "text": "Conduction speeds up because the insulating layer that had impeded the flow of ions along the axon is gone"}, {"label": "C", "text": "Conduction is unchanged because voltage-gated sodium channels are clustered only at the nodes regardless of myelin"}, {"label": "D", "text": "Conduction fails entirely because losing myelin also removes the voltage-gated sodium channels the axon needs"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' In a healthy myelinated axon, the insulating sheath forces the depolarizing sodium current to spread down the inside of the axon and regenerate the action potential only at the nodes of Ranvier, so the impulse effectively "leaps" from node to node in fast saltatory conduction; the internodal distance is tuned so the membrane is still above threshold when the current reaches the next node. When myelin is lost, the current is no longer contained and dissipates across the now-exposed internodal membrane, so the signal must fall back toward slow continuous conduction and, if it decays below threshold, may fail to reach the next node. (Choice A) is correct: with myelin gone, current leaks across the bare membrane rather than being channeled to the next node, so depolarization dissipates and conduction slows—the text notes that when "the insulation around the axons is destroyed," the result is "making electrical signaling slower." (Choice B) is incorrect: it reverses the actual role of myelin, treating insulation as a barrier that slows ions; in reality myelin speeds conduction by preventing current leak, so removing it makes conduction slower, not faster. (Choice C) is incorrect: although voltage-gated sodium channels are indeed concentrated at the nodes, saltatory conduction still depends on myelin keeping the internodal current from leaking, so demyelination degrades conduction even with the channel distribution unchanged. (Choice D) is incorrect: the myelin sheath is made by glial cells and is separate from the axon''s own membrane proteins, so stripping myelin does not remove the axon''s voltage-gated sodium channels; the axon can still fire, just less efficiently. This is a Scientific Reasoning and Problem Solving question because you must apply the mechanism of saltatory conduction to a novel demyelination scenario and predict the functional consequence, rather than recall a definition.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'b4371073-4e28-4fd9-90e7-bf3af9f33126';
DELETE FROM question_distractor_metadata WHERE question_id = 'b4371073-4e28-4fd9-90e7-bf3af9f33126';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('b4371073-4e28-4fd9-90e7-bf3af9f33126', 'B', 'reversed_relationship', 'treats myelin as a physical barrier to ion flow, so removing it should speed conduction'),
  ('b4371073-4e28-4fd9-90e7-bf3af9f33126', 'C', 'misconception', 'knows Na+ channels sit at nodes and concludes myelin is therefore irrelevant to conduction speed'),
  ('b4371073-4e28-4fd9-90e7-bf3af9f33126', 'D', 'misconception', 'conflates loss of the glial myelin sheath with loss of the axon''s own voltage-gated channels');

-- [Neuron Functional Types] ans=C medium skill2
UPDATE questions SET
  question_text = 'During a flexor-withdrawal reflex, a subject rapidly pulls a hand away from a hot surface. Researchers selectively silence one class of neuron in the spinal cord and find that the flexor (biceps) still contracts normally, but the antagonist extensor (triceps) now fails to relax during the reflex, briefly resisting the withdrawal. The silenced cells were confined to the spinal gray matter. Which functional class of neuron did the researchers most likely silence?',
  options = '[{"label": "A", "text": "Sensory (afferent) neurons carrying pain signals from the skin"}, {"label": "B", "text": "Motor (efferent) neurons driving contraction of the biceps"}, {"label": "C", "text": "Interneurons that inhibit the extensor''s motor neuron"}, {"label": "D", "text": "Motor (efferent) neurons driving contraction of the triceps"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' In a spinal withdrawal reflex, sensory input is integrated within the gray matter before a motor response is produced, and smooth withdrawal requires the antagonist muscle to relax while the agonist contracts. Because the neuromuscular junction is strictly excitatory and skeletal muscle cannot actively relax, relaxation of the antagonist must be produced by inhibiting its motor neuron rather than by any signal sent directly to the muscle. (Choice C) is correct: OpenStax states that during the withdrawal reflex an interneuron in the spinal cord "inhibits the motor neuron that controls the triceps brachii" by hyperpolarizing it, so the triceps relaxes; silencing this integrating interneuron removes the inhibition, leaving the extensor motor neuron active and the triceps unable to relax—exactly the observed deficit. (Choice A) is incorrect: silencing the afferent pain neurons would abolish the trigger for the entire reflex, so the biceps would not contract either, yet the flexor contraction was preserved. (Choice B) is incorrect: the biceps motor neuron drives the flexor contraction that was still normal, so silencing it would weaken withdrawal rather than block antagonist relaxation. (Choice D) is incorrect: silencing the triceps motor neuron would itself let the triceps go slack, which is the opposite of the observed failure to relax, and this cell lies in the ventral horn projecting to muscle rather than acting as the intermediary that produces inhibition. This is a Scientific Reasoning and Problem Solving question because you must apply the roles of sensory, motor, and interneurons to a reflex-arc perturbation and infer which class produces antagonist inhibition.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '46be95ca-4d35-49af-af9b-7b726954b606';
DELETE FROM question_distractor_metadata WHERE question_id = '46be95ca-4d35-49af-af9b-7b726954b606';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('46be95ca-4d35-49af-af9b-7b726954b606', 'A', 'misconception', 'wrong-link-in-reflex-arc'),
  ('46be95ca-4d35-49af-af9b-7b726954b606', 'B', 'partial_truth', 'correct-cell-wrong-role'),
  ('46be95ca-4d35-49af-af9b-7b726954b606', 'D', 'reversed_relationship', 'silencing-produces-opposite-effect');

-- [CNS Tissue Organization] ans=A medium skill2
UPDATE questions SET
  question_text = 'The axons carrying visual information leave the retina as a bundle called the optic nerve. As these axons pass the optic chiasm and travel deeper into the brain toward the thalamus, the same retinal fibers continue on without any being added or removed. In the region beyond the chiasm, where the fibers now lie inside the brain, this bundle of axons is instead designated the optic:',
  options = '[{"label": "A", "text": "tract"}, {"label": "B", "text": "ganglion"}, {"label": "C", "text": "nucleus"}, {"label": "D", "text": "nerve"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' Anatomical names for neural structures depend jointly on two variables: what the structure is made of (bundled axons versus clustered cell bodies) and where it lies (central nervous system versus peripheral nervous system). A bundle of axons is called a nerve in the PNS but a tract in the CNS, while a cluster of cell bodies is called a ganglion in the PNS but a nucleus in the CNS; because the optic fibers pass from peripheral to central without any change in their physical content, only the location-dependent name changes. (Choice A) is correct: past the optic chiasm the fibers lie within the brain, so the axon bundle is now central, and the CNS term for a bundle of axons is a tract, making it the optic tract. (Choice B) is incorrect: a ganglion is a cluster of neuron cell bodies in the PNS, which is wrong on both counts, since the structure is a bundle of axons (not cell bodies) and it lies in the CNS (not the PNS). (Choice C) is incorrect: a nucleus is the CNS location, correctly capturing that the fibers are now central, but it names a cluster of cell bodies rather than a bundle of axons, so it describes the wrong type of structure. (Choice D) is incorrect: nerve is the PNS term for a bundle of axons, which correctly identifies the structure as an axon bundle but wrongly places it in the periphery, whereas beyond the chiasm the fibers are inside the CNS. This is a Scientific Reasoning and Problem Solving question because you must apply the two-variable naming rule (axons versus cell bodies, and CNS versus PNS location) to a bundle that keeps the same fibers but crosses from the peripheral to the central nervous system, rather than recalling a single fixed definition.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '470fcb67-3017-46f1-96d7-bdb674eac437';
DELETE FROM question_distractor_metadata WHERE question_id = '470fcb67-3017-46f1-96d7-bdb674eac437';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('470fcb67-3017-46f1-96d7-bdb674eac437', 'B', 'misconception', 'wrong-structure-and-wrong-location'),
  ('470fcb67-3017-46f1-96d7-bdb674eac437', 'C', 'adjacent_fact', 'correct-location-wrong-structure'),
  ('470fcb67-3017-46f1-96d7-bdb674eac437', 'D', 'misconception', 'correct-structure-wrong-location');

-- [CNS Tissue Organization] ans=A hard skill2
UPDATE questions SET
  question_text = 'In a study of the central nervous system, researchers destroy one myelinating glial cell in the spinal cord''s white matter and observe that the myelin is lost from segments belonging to several different, physically separate axons at once. Which feature of the affected cell type best accounts for this pattern of injury?',
  options = '[{"label": "A", "text": "One oligodendrocyte extends processes that myelinate segments of several separate axons"}, {"label": "B", "text": "One Schwann cell wraps a single axon segment and myelinates no other axons"}, {"label": "C", "text": "One astrocyte contacts many axons to supply the myelin that insulates each of them"}, {"label": "D", "text": "One microglial cell ensheathes multiple neighboring axons to insulate them in myelin"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Neuron & Glial Cell Structure.'' Myelin in the nervous system is produced by glial cells, and the way each type contacts axons differs between the CNS and the PNS: a single oligodendrocyte sends out multiple processes, each reaching a different axon segment, so one oligodendrocyte can myelinate segments belonging to several separate axons, whereas a single Schwann cell in the PNS wraps only one segment of one axon. Because the injury described spreads myelin loss across multiple separate axons from the death of a single cell, the responsible cell must be the one that services many axons at once. (Choice A) is correct: an oligodendrocyte''s several processes each insulate a different axon segment, so destroying one oligodendrocyte demyelinates parts of several distinct axons simultaneously, exactly the pattern observed. (Choice B) is incorrect: a Schwann cell myelinates only a single segment of a single axon, so its loss would demyelinate just one axon, not several; Schwann cells also reside in the PNS, not the CNS white matter described. (Choice C) is incorrect: astrocytes provide structural and metabolic support and help form the blood-brain barrier, but they do not produce myelin, so they cannot be the source of the myelin lost. (Choice D) is incorrect: microglia act as resident macrophages that clear debris and pathogens in the CNS; they are not myelinating cells and do not ensheathe axons in myelin. This is a Scientific Reasoning and Problem Solving question because you must apply the structural difference between how oligodendrocytes and Schwann cells contact axons to infer which cell type would produce demyelination across multiple separate axons.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'b947bb9c-b362-4e7e-9354-618193ed7390';
DELETE FROM question_distractor_metadata WHERE question_id = 'b947bb9c-b362-4e7e-9354-618193ed7390';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('b947bb9c-b362-4e7e-9354-618193ed7390', 'B', 'partial_truth', 'true Schwann-cell fact (single axon segment, PNS) that does not explain CNS multi-axon demyelination'),
  ('b947bb9c-b362-4e7e-9354-618193ed7390', 'C', 'misconception', 'attributing myelination to astrocytes (support glia)'),
  ('b947bb9c-b362-4e7e-9354-618193ed7390', 'D', 'misconception', 'attributing myelination to microglia (immune glia)');

-- [CNS & Spinal Cord Organization] ans=A medium skill2
UPDATE questions SET
  question_text = 'A student jerks her hand away from a hot stove. In this withdrawal reflex, a sensory neuron from the skin triggers a spinal circuit that contracts the biceps brachii to flex the elbow. For the hand to be pulled back quickly, the antagonistic triceps brachii must relax at the same moment. Given that the neuromuscular junction of skeletal muscle is strictly excitatory and skeletal muscle cannot actively relax on command, how does the spinal circuit cause the triceps to relax during this reflex?',
  options = '[{"label": "A", "text": "An inhibitory interneuron in the spinal cord hyperpolarizes the motor neuron that supplies the triceps."}, {"label": "B", "text": "The motor neuron supplying the triceps releases an inhibitory transmitter onto the triceps muscle fibers."}, {"label": "C", "text": "The sensory neuron from the skin synapses directly on the triceps muscle fibers to silence them."}, {"label": "D", "text": "The triceps relaxes passively once its own motor neuron stops receiving stretch input."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' In a spinal reflex, sensory input is processed by the spinal cord and converted to motor output; because the neuromuscular junction is strictly excitatory, a motor neuron can only make its muscle contract, and skeletal muscle cannot be actively told to relax. The textbook states that for the antagonist to relax during withdrawal, the motor neuron "needs to ''quiet down,'' or be inhibited," which "occurs through an interneuron in the spinal cord" whose cell body sits in the dorsal horn and which "inhibits the motor neuron that controls the triceps brachii" by "releasing a neurotransmitter or other signal that hyperpolarizes the motor neuron." (Choice A) is correct: relaxation of the antagonist is produced by an inhibitory interneuron in the spinal cord that hyperpolarizes the triceps motor neuron, making it less likely to fire, so the muscle it drives goes slack. (Choice B) is incorrect: motor neurons of skeletal muscle release only excitatory transmitter at the neuromuscular junction and cannot signal a muscle to relax, so an "inhibitory transmitter onto the muscle fibers" contradicts the strictly excitatory nature of the junction. (Choice C) is incorrect: sensory afferents synapse on neurons within the CNS, not on skeletal muscle fibers, so a sensory neuron cannot directly silence a muscle. (Choice D) is incorrect: skeletal muscle does not relax passively on demand within the reflex; the antagonist must be actively unloaded by inhibiting its motor neuron, and stretch input is not what is being withdrawn here. This is a Scientific Reasoning and Problem Solving question because you must apply the constraint that the neuromuscular junction is excitatory-only to deduce that antagonist relaxation must come from inhibition of a motor neuron by a spinal interneuron rather than from any direct "relax" signal.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '302dacc1-4950-4f39-94d7-345329b77eba';
DELETE FROM question_distractor_metadata WHERE question_id = '302dacc1-4950-4f39-94d7-345329b77eba';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('302dacc1-4950-4f39-94d7-345329b77eba', 'B', 'misconception', 'motor neurons can send an inhibitory/relax signal to skeletal muscle'),
  ('302dacc1-4950-4f39-94d7-345329b77eba', 'C', 'misconception', 'sensory afferents synapse directly on muscle rather than on CNS neurons'),
  ('302dacc1-4950-4f39-94d7-345329b77eba', 'D', 'misconception', 'skeletal muscle relaxes passively without active inhibition of its motor neuron');

-- [PNS: Somatic vs Autonomic] ans=C medium skill2
UPDATE questions SET
  question_text = 'A startled person suddenly jumps back and screams when a friend leaps out from behind a corner, all before they have any chance to think about it. Considering how the peripheral nervous system''s functional divisions are defined by the effector tissues they command, which division carried the motor signal that produced this jumping-and-screaming response?',
  options = '[{"label": "A", "text": "The autonomic nervous system, because the reaction happened involuntarily before any conscious decision was made"}, {"label": "B", "text": "The autonomic nervous system, because a sudden startle triggers a fight-or-flight surge throughout the body"}, {"label": "C", "text": "The somatic nervous system, because the jump and scream are contractions of skeletal muscle"}, {"label": "D", "text": "The enteric nervous system, because it independently coordinates rapid protective movements of the trunk"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' The peripheral nervous system''s functional divisions are distinguished chiefly by the effector tissue each one commands: the somatic nervous system innervates skeletal muscle, while the autonomic nervous system innervates smooth muscle, cardiac muscle, and glands. OpenStax states that "voluntary motor response means the contraction of skeletal muscle, but those contractions are not always voluntary," and gives the exact example that being startled and jumping back "is a reflex involving skeletal muscle contractions" — a somatic response that occurs without a conscious decision. (Choice C) is correct: jumping back and screaming are both produced by contractions of skeletal muscle (limb, trunk, and laryngeal muscles), and skeletal muscle is the effector the somatic division commands, so the somatic system carried this motor signal even though the movement was reflexive. (Choice A) is incorrect: lack of conscious control does not by itself make a response autonomic — the text notes that reflexes and habit-learned movements are involuntary yet remain somatic because they act on skeletal muscle; the division is defined by the effector tissue, not by whether a decision was made. (Choice B) is incorrect: although a startle does trigger a sympathetic surge, that autonomic output drives smooth/cardiac muscle and glands (racing heart, sweating), not the skeletal-muscle contractions that constitute the actual jumping and screaming. (Choice D) is incorrect: the enteric nervous system controls the smooth muscle and glandular tissue of the digestive tract, not the skeletal muscles that move the trunk and limbs. This is a Scientific Reasoning and Problem Solving question because you must apply the effector-tissue basis of the somatic-versus-autonomic distinction to a reflexive skeletal-muscle response and resist the trap that "involuntary" equals autonomic.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '78094775-f665-45dc-848f-2af5d02bcd3c';
DELETE FROM question_distractor_metadata WHERE question_id = '78094775-f665-45dc-848f-2af5d02bcd3c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('78094775-f665-45dc-848f-2af5d02bcd3c', 'A', 'misconception', 'involuntary_means_autonomic'),
  ('78094775-f665-45dc-848f-2af5d02bcd3c', 'B', 'partial_truth', 'correct_side_effect_wrong_effector'),
  ('78094775-f665-45dc-848f-2af5d02bcd3c', 'D', 'adjacent_fact', 'wrong_division_right_neighborhood');

-- [CNS & Spinal Cord Organization] ans=A medium skill2
UPDATE questions SET
  question_text = 'A patient sustains an injury that cleanly severs the dorsal root of one lumbar spinal nerve; the ventral root of that same nerve is confirmed to be fully intact. A physician then examines the leg region supplied by that spinal nerve. Compared with the patient''s healthy leg, what is the most likely combination of findings in the affected leg?',
  options = '[{"label": "A", "text": "Loss of skin sensation, an absent knee-jerk reflex, but preserved voluntary muscle contraction"}, {"label": "B", "text": "Loss of skin sensation, an intact knee-jerk reflex, but absent voluntary muscle contraction"}, {"label": "C", "text": "Normal skin sensation, an absent knee-jerk reflex, and absent voluntary muscle contraction"}, {"label": "D", "text": "Loss of skin sensation, an absent knee-jerk reflex, and absent voluntary muscle contraction"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Nervous System Organization.'' As a spinal nerve approaches the cord it splits into two roots: the dorsal root carries only the axons of sensory (afferent) neurons, whose cell bodies sit in the dorsal root ganglion, while the ventral root carries only motor (efferent) axons leaving the cord. A stretch reflex such as the knee-jerk depends on both limbs of a reflex arc: the muscle spindle''s sensory signal enters through the dorsal root and synapses directly on a ventral-horn motor neuron, whose axon exits through the ventral root to contract the muscle. Voluntary contraction, by contrast, is driven by descending motor commands that reach that same ventral-horn motor neuron and leave via the ventral root, without needing the dorsal root at all. (Choice A) is correct: cutting only the dorsal root destroys the afferent limb, so peripheral sensation and the reflex''s sensory input are lost and the knee-jerk disappears; because the ventral root and its motor neurons are intact and still receive descending commands, the patient can still voluntarily contract the muscle. (Choice B) is incorrect: it keeps the knee-jerk reflex and removes voluntary movement, which is backwards, because the reflex requires the severed sensory limb while voluntary contraction runs entirely through the spared ventral (motor) root. (Choice C) is incorrect: it preserves skin sensation, but the dorsal root is the sole entry point for afferent axons from that region, so severing it must abolish sensation. (Choice D) is incorrect: it correctly loses sensation and the reflex but wrongly abolishes voluntary contraction, reflecting the misconception that a dorsal-root lesion also blocks motor output, when in fact motor axons exit through the untouched ventral root. This is a Scientific Reasoning and Problem Solving question because you must apply the segregated dorsal-sensory/ventral-motor organization of spinal roots and the two-limb structure of a reflex arc to predict which sensory, reflexive, and voluntary functions survive a targeted lesion.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '84ffd452-8468-4a2e-a098-7f08641da4c6';
DELETE FROM question_distractor_metadata WHERE question_id = '84ffd452-8468-4a2e-a098-7f08641da4c6';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('84ffd452-8468-4a2e-a098-7f08641da4c6', 'B', 'reversed_relationship', 'swaps which limb of the reflex arc the dorsal root serves'),
  ('84ffd452-8468-4a2e-a098-7f08641da4c6', 'C', 'misconception', 'believes sensation can persist without the dorsal root'),
  ('84ffd452-8468-4a2e-a098-7f08641da4c6', 'D', 'misconception', 'assumes any root lesion abolishes both sensation and all motor output');

-- [Repolarization & Hyperpolarization] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher records the membrane voltage of a neuron during a single action potential. After the peak, the voltage falls back through -70 mV and continues downward, briefly reaching about -80 mV before slowly returning to the resting value. Which mechanism best accounts for the membrane becoming more negative than the resting potential during this brief interval?',
  options = '[{"label": "A", "text": "The voltage-gated K+ channels close with a delay, so K+ continues to exit toward its equilibrium value, which lies below -70 mV."}, {"label": "B", "text": "The Na+/K+ pump transiently accelerates, expelling extra Na+ and drawing the membrane below its normal resting value."}, {"label": "C", "text": "The voltage-gated Na+ channels briefly reopen, and the returning Na+ current pulls the membrane past -70 mV."}, {"label": "D", "text": "Voltage-gated Cl- channels open at the peak, and the resulting Cl- influx drives the membrane below -70 mV."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''The Action Potential.'' Repolarization returns the membrane toward the -70 mV resting potential, but the membrane actually overshoots to a more negative value before settling back. The textbook attributes this dip to potassium: K+ reaches electrochemical equilibrium at a voltage below -70 mV, and because the voltage-gated K+ channels are slightly delayed in closing, K+ keeps leaving the cell and drives the membrane below rest until those channels shut and the non-gated channels and Na+/K+ pump restore the resting potential. (Choice A) is correct: the voltage-gated K+ channels lag in closing, so K+ efflux continues toward its equilibrium potential, which sits below -70 mV, pulling the membrane more negative than rest. (Choice B) is incorrect: the Na+/K+ pump works continuously to maintain and restore the resting potential; it does not suddenly speed up to create the undershoot, and its slow, steady activity brings the membrane back up to rest rather than dragging it below. (Choice C) is incorrect: voltage-gated Na+ channels are inactivated near the peak and Na+ entry depolarizes the membrane (drives it toward positive values), so reopening Na+ channels would move the membrane away from, not past, the negative resting value. (Choice D) is incorrect: although Cl- influx can hyperpolarize a membrane during inhibitory graded potentials, the action potential''s undershoot below rest is produced by continued K+ efflux, not by voltage-gated Cl- channels, which are not the drivers of this phase. This is a Scientific Reasoning and Problem Solving question because you must apply your understanding of ion equilibrium potentials and channel gating kinetics to explain why the membrane transiently drops below its resting value.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '7e6b6495-4a8e-45e5-a2d9-aae928949e7c';
DELETE FROM question_distractor_metadata WHERE question_id = '7e6b6495-4a8e-45e5-a2d9-aae928949e7c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('7e6b6495-4a8e-45e5-a2d9-aae928949e7c', 'B', 'misconception', 'pump-causes-hyperpolarization'),
  ('7e6b6495-4a8e-45e5-a2d9-aae928949e7c', 'C', 'reversed_relationship', 'wrong-ion-direction'),
  ('7e6b6495-4a8e-45e5-a2d9-aae928949e7c', 'D', 'adjacent_fact', 'chloride-from-IPSP-context');

-- [Impulse Propagation & Conduction Velocity] ans=B medium skill2
UPDATE questions SET
  question_text = 'A researcher records conduction velocity along two unmyelinated axons that are identical in every respect except caliber: one is wide (large diameter) and one is narrow (small diameter). An identical action potential is triggered at the initial segment of each, and the researcher measures how quickly the depolarization reaches the axon terminal. Which axon conducts the impulse to its terminal faster, and what accounts for the difference?',
  options = '[{"label": "A", "text": "The narrow axon, because its smaller cytoplasmic volume reaches threshold with less Na+ influx per unit length."}, {"label": "B", "text": "The wide axon, because its larger cross-sectional area lowers the internal resistance opposing the spread of depolarization."}, {"label": "C", "text": "Neither; both conduct at the same velocity, because velocity in unmyelinated axons is fixed by the membrane threshold voltage."}, {"label": "D", "text": "The narrow axon, because a higher surface-area-to-volume ratio packs voltage-gated Na+ channels more densely along its length."}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Impulse Propagation & Synapses.'' In an unmyelinated axon, the impulse spreads by continuous conduction: Na+ that enters at one point flows along the inside of the membrane and depolarizes the adjacent segment, opening the next set of voltage-gated Na+ channels. How fast that internal current spreads depends on the resistance the cytoplasm offers to it, and a larger cross-sectional area offers a lower-resistance path. The text states that "Na+-based depolarization spreads faster down a wide axon than down a narrow one. This concept is known as resistance" (A&P 22066–22067). (Choice B) is correct: the wide axon''s greater cross-sectional area presents lower internal (axial) resistance to the spreading Na+ current, so the depolarization travels down it faster, exactly as the wide-river-versus-narrow-creek analogy in the text describes. (Choice A) is incorrect: this reverses the actual relationship, and conduction velocity depends on how fast current spreads down the axon interior, not on how much total Na+ is needed to bring a small volume to threshold—the narrow axon is in fact slower. (Choice C) is incorrect: threshold voltage sets whether an action potential fires, not how fast it propagates; the text explicitly names diameter as a determinant of conduction speed, so velocity is not fixed and geometry matters. (Choice D) is incorrect: in continuous conduction it is the axial resistance to current spread, not channel packing density, that limits speed, and treating a higher surface-area-to-volume ratio as an advantage ignores that the narrow axon actually conducts more slowly. This is a Scientific Reasoning and Problem Solving question because you must apply the resistance principle to a novel two-axon comparison and identify which geometric factor governs the difference in conduction velocity.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '8ecd630d-fc4f-4300-b53e-c770dfa23eb2';
DELETE FROM question_distractor_metadata WHERE question_id = '8ecd630d-fc4f-4300-b53e-c770dfa23eb2';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8ecd630d-fc4f-4300-b53e-c770dfa23eb2', 'A', 'reversed_relationship', 'inverts the diameter-resistance-velocity relationship (thinner = faster)'),
  ('8ecd630d-fc4f-4300-b53e-c770dfa23eb2', 'C', 'misconception', 'confuses the determinant of firing (threshold) with the determinant of propagation speed'),
  ('8ecd630d-fc4f-4300-b53e-c770dfa23eb2', 'D', 'misconception', 'attributes conduction speed to channel packing density rather than axial resistance');

-- [Postsynaptic Receptors & Neurotransmitter Removal] ans=A hard skill2
UPDATE questions SET
  question_text = 'A patient begins taking a selective serotonin reuptake inhibitor (SSRI), a drug that blocks the presynaptic transporter that normally pumps serotonin back into the serotonergic terminal. At a serotonergic synapse where reuptake is the only clearance route and no cleft enzyme degrades this transmitter, a researcher measures signaling at the postsynaptic receptors after the drug takes effect. Which prediction is correct?',
  options = '[{"label": "A", "text": "Postsynaptic signaling is prolonged and intensified relative to the untreated synapse."}, {"label": "B", "text": "Postsynaptic signaling returns to its baseline level once the terminal reduces further serotonin release."}, {"label": "C", "text": "Postsynaptic signaling falls sharply because the terminal is starved of serotonin to release."}, {"label": "D", "text": "Postsynaptic signaling switches from excitatory to inhibitory as serotonin builds up in the cleft."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Impulse Propagation & Synapses.'' Serotonin is a biogenic amine whose only route of removal from the synaptic cleft is reuptake: the textbook states that serotonin "is transported back into the presynaptic cell for repackaging" and lists "Reuptake by neurons" as the elimination mechanism for biogenic amines, with no cleft-degrading enzyme (Anatomy & Physiology 2e). Because a neurotransmitter''s effect persists only while it remains bound to its receptors, blocking the sole clearance transporter lets serotonin accumulate and keep re-binding. (Choice A) is correct: with reuptake blocked and no enzyme to substitute, serotonin lingers in the cleft and continues binding its receptors, so the postsynaptic response lasts longer and is stronger than at the untreated synapse. (Choice B) is incorrect: although serotonergic terminals do have autoreceptors, the immediate pharmacological effect of blocking clearance is a net rise in cleft serotonin; presynaptic feedback modulates but does not fully cancel the accumulation, so signaling does not simply return to baseline. (Choice C) is incorrect: it confuses clearance with release—reuptake recycles transmitter for later use, but vesicular release is a separate Ca2+-triggered exocytosis step, and the drug acts fast enough that impaired recycling does not starve the terminal or reduce signaling. (Choice D) is incorrect: accumulating serotonin binds the same receptors more, prolonging and strengthening the existing response; the sign of the effect is set by the receptor type, so simply having more transmitter does not flip an excitatory synapse into an inhibitory one. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between a transmitter''s clearance route and its receptor-binding duration to predict the downstream effect of blocking that route.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'ea28b186-88de-4b7c-acd2-b0151f88ca0c';
DELETE FROM question_distractor_metadata WHERE question_id = 'ea28b186-88de-4b7c-acd2-b0151f88ca0c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('ea28b186-88de-4b7c-acd2-b0151f88ca0c', 'B', 'misconception', 'homeostatic feedback fully cancels a drug''s effect'),
  ('ea28b186-88de-4b7c-acd2-b0151f88ca0c', 'C', 'misconception', 'conflating reuptake-for-recycling with vesicular release'),
  ('ea28b186-88de-4b7c-acd2-b0151f88ca0c', 'D', 'misconception', 'more transmitter reverses the sign of signaling');

COMMIT;
