-- The Endocrine System — Batch 3 — Thyroid/Parathyroid + Adrenal Glands
-- Original Praxist Prep questions, grounded in the subject reference textbook; scope verified vs AAMC 2026 outline.
-- Idempotent: deletes only this batch's subtopics, then re-inserts. question_attempts / distractor_metadata cascade.

DELETE FROM questions WHERE topic = 'The Endocrine System' AND subtopic IN ('Adrenal Glands', 'Thyroid & Parathyroid');

-- Q1 [Thyroid & Parathyroid] easy skill1 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A gland in the front of the neck releases two iodine-containing hormones, but only after the anterior pituitary sends it a stimulating signal. Once in the blood, these hormones enter cells throughout the entire body and bind receptors on the mitochondria and in the nucleus. Which of the following whole-body parameters is established by this gland''s hormones?', '[{"label": "A", "text": "Resting energy expenditure"}, {"label": "B", "text": "Concentration of calcium in the blood"}, {"label": "C", "text": "Concentration of glucose in the blood"}, {"label": "D", "text": "Intensity of the fight-or-flight response"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because the described gland is the thyroid, whose iodine-containing hormones T3 and T4 are released in response to thyroid-stimulating hormone (TSH) from the anterior pituitary; T3 and T4 enter cells throughout the body and bind intracellular receptors on the mitochondria and in the nucleus, where they raise nutrient breakdown, oxygen consumption, and ATP output. (Choice A) is correct: the sum of this activity at rest is the body''s basal metabolic rate, described here as resting energy expenditure, the amount of energy the body uses at rest, and thyroid hormones are the metabolic hormones that set it. (Choice B) is incorrect: the concentration of calcium in the blood is established by parathyroid hormone (which raises it) and calcitonin (which lowers it) acting on bone, kidney, and intestine, not by the iodine-containing metabolic hormones T3/T4 described in the stem. (Choice C) is incorrect: the concentration of glucose in the blood is set chiefly by pancreatic insulin and glucagon (with cortisol raising it); although thyroid hormones initiate transcription of genes for glucose oxidation inside cells, they do not establish the blood glucose level itself. (Choice D) is incorrect: the intensity of the fight-or-flight response is driven by epinephrine and norepinephrine from the adrenal medulla, an acute stress function distinct from the sustained, body-wide metabolic set point governed by thyroid hormones. This is a Skill 1 (Knowledge of Scientific Concepts) item because it requires recognizing the thyroid''s characteristic role in setting basal metabolic rate from a description of its control relationship and broad intracellular action.', 'easy', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 1, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'same-region hormone with a different set point (PTH/calcitonin regulate blood calcium, not energy expenditure)' FROM q
  UNION ALL
  SELECT id, 'C', 'misconception', 'conflating thyroid-driven intracellular glucose oxidation with blood glucose homeostasis (insulin/glucagon)' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'substituting an unrelated systemic endocrine parameter (adrenal medulla epinephrine/norepinephrine, fight-or-flight)' FROM q;

-- Q2 [Thyroid & Parathyroid] medium skill2 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A patient''s cells show a sustained rise in the hormone that binds intracellular receptors on mitochondria and drives transcription of genes for nutrient breakdown. Which whole-body consequence is most expected?', '[{"label": "A", "text": "Reduced blood calcium concentration"}, {"label": "B", "text": "Higher oxygen consumption and heat output"}, {"label": "C", "text": "Lowered fasting blood glucose"}, {"label": "D", "text": "Decreased sodium reabsorption by kidneys"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because the hormone described—thyroid hormone (T3/T4), which binds intracellular receptors on mitochondria and initiates transcription of genes for nutrient breakdown and glucose oxidation—raises the body''s basal metabolic rate. When present in excess, it increases nutrient breakdown and the use of oxygen to produce ATP; because this ATP production is inefficient, abnormally increased heat is released as a byproduct (the calorigenic effect), raising body temperature. Thus elevated levels drive up oxygen consumption and heat output together. (Choice B) is correct: elevated thyroid hormone increases cellular respiration, so oxygen use climbs, and the inefficient ATP synthesis releases surplus heat, elevating metabolic rate and body temperature. (Choice A) is incorrect: blood calcium is lowered by calcitonin (from the thyroid''s parafollicular cells) and raised by parathyroid hormone; calcium homeostasis is a separate hormonal axis from the metabolic-rate hormone described, and elevated metabolic hormone does not itself drive calcium down. (Choice C) is incorrect: fasting blood glucose is lowered chiefly by insulin; the metabolic hormone described actually promotes glucose oxidation and, in excess, tends to accompany catabolism rather than a hypoglycemic set point, so predicting lowered glucose misattributes insulin''s role. (Choice D) is incorrect: renal sodium handling is governed largely by aldosterone (and, for water, ADH); the calorigenic metabolic hormone does not act primarily on sodium reabsorption, so this confuses the mineralocorticoid axis with the metabolic one. This question requires Skill 2 reasoning because the student must map a described mechanism onto its downstream physiological effect—predicting increased oxygen use and heat from an elevated metabolic hormone—rather than recalling a stated definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'adjacent_fact', 'same-gland-different-hormone (calcitonin/PTH calcium role attributed to the metabolic thyroid hormone)' FROM q
  UNION ALL
  SELECT id, 'C', 'misconception', 'metabolic-hormone-equals-glucose-lowering (conflates thyroid hormone with insulin)' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'wrong-axis (attributes aldosterone/ADH renal sodium role to the metabolic hormone)' FROM q;

-- Q3 [Thyroid & Parathyroid] medium skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A 26-year-old woman reports that over several months she has felt uncomfortably warm even in cool rooms, her resting pulse is persistently rapid, and she has lost 6 kg despite eating more than usual and feeling restless and "wired." Which endocrine change best accounts for this cluster of findings?', '[{"label": "A", "text": "Sustained overproduction of adrenal epinephrine"}, {"label": "B", "text": "Deficient secretion of triiodothyronine and thyroxine"}, {"label": "C", "text": "Excess secretion of triiodothyronine and thyroxine"}, {"label": "D", "text": "Chronic oversecretion of parathyroid hormone"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because the thyroid hormones triiodothyronine (T3) and thyroxine (T4) set the basal metabolic rate, so an abnormally elevated blood level of these hormones drives the whole cluster described: increased metabolic rate produces excessive body heat and heat intolerance, catabolism of energy stores causes weight loss despite increased appetite, and sympathetic-like stimulation raises heart rate and produces restlessness. (Choice C) is correct: elevated T3/T4 raises the metabolic rate, which the textbook lists as causing excessive body heat and sweating, weight loss, and increased heart rate, matching every finding in the scenario. (Choice B) is incorrect: too little T3/T4 lowers the metabolic rate, producing the opposite profile of weight gain, cold extremities, and reduced activity, so a deficiency cannot explain heat intolerance, weight loss, and tachycardia. (Choice A) is incorrect: adrenal epinephrine does accelerate heart rate and mobilize glucose during the fight-or-flight response, but it acts as a brief, acute surge rather than the sustained months-long state of hypermetabolism and net weight loss described here. (Choice D) is incorrect: parathyroid hormone regulates blood calcium by raising it, and its excess disturbs calcium and bone rather than metabolic rate, body temperature, and appetite-independent weight loss. To answer, the student had to reason from the presenting signs back to which hormone''s output level was disturbed and in which direction, rather than recall a stated definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'Confuses the direction of hormone imbalance, attributing a hypermetabolic presentation to a hormone deficiency (hypothyroid profile) rather than excess' FROM q
  UNION ALL
  SELECT id, 'A', 'adjacent_fact', 'Latches onto the overlapping sign of tachycardia and picks the fight-or-flight catecholamine, ignoring that epinephrine acts acutely and does not explain sustained hypermetabolism and weight loss' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'Selects another thyroid-region hormone but one governing calcium homeostasis, conflating ''thyroid area'' hormones and missing that PTH does not control metabolic rate or body temperature' FROM q;

-- Q4 [Thyroid & Parathyroid] medium skill2 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A 44-year-old patient reports persistent fatigue, unexplained weight gain, and feeling cold even in a warm room. On examination, both heart rate and respiratory rate are noticeably slower than normal. Which underlying endocrine state best accounts for this combination of findings?', '[{"label": "A", "text": "Parathyroid glands secreting insufficient hormone"}, {"label": "B", "text": "Overactive thyroid gland from follicular-cell overstimulation"}, {"label": "C", "text": "Adrenal cortex hypersecreting cortisol"}, {"label": "D", "text": "Underactive thyroid gland, reducing metabolic hormone output"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the thyroid hormones T3 and T4 set the body''s basal metabolic rate, drive calorigenic heat production, and increase the body''s sensitivity to catecholamines that accelerate the heartbeat; when their output falls, metabolism, heat generation, and cardiorespiratory drive all decline. This produces exactly the described cluster: low metabolic rate, weight gain, cold intolerance, lethargy, and a slowed heart and respiratory rate. (Choice D) is correct: an underactive thyroid gland lowers circulating T3 and T4, and OpenStax lists a low metabolic rate, weight gain, cold extremities, and reduced activity as the hallmark presentation of this deficiency state. (Choice B) is incorrect: an overactive thyroid gland raises T3 and T4, which increases metabolic rate and body heat and accelerates the heart rate, yielding heat intolerance, weight loss, and tachycardia—the opposite of the findings described, so it is the reversed-direction trap. (Choice C) is incorrect: adrenal hypersecretion of cortisol causes Cushing''s disease, which does produce lipid accumulation and weight changes, but it is marked by high blood glucose and central fat deposits rather than cold intolerance and a slowed heart rate, so the matching symptom is only superficial. (Choice A) is incorrect: deficient parathyroid hormone lowers blood calcium and causes muscle twitching, cramping, and spasms; although the parathyroid glands sit within the thyroid region, their hormone governs calcium balance, not basal metabolism, so it cannot explain this metabolic-slowing picture. This item requires Skill 2 reasoning because the student must map an unlabeled clinical cluster onto the correct hormonal direction and gland rather than recall a stated definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'Confuses hyperthyroidism with hypothyroidism, selecting the elevated-hormone state for a low-hormone symptom cluster' FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', 'Anchors on weight gain and picks Cushing''s/cortisol excess, ignoring the cold intolerance and bradycardia that point to metabolic slowing' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'Associates any deficiency in the thyroid region with the parathyroid glands, conflating calcium regulation with basal metabolism' FROM q;

-- Q5 [Thyroid & Parathyroid] hard skill2 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A dietary survey finds that residents of a landlocked region who do not use iodized salt have chronically enlarged thyroid glands. Blood tests reveal their circulating triiodothyronine (T3) and thyroxine (T4) are persistently low. Which laboratory finding for a pituitary-derived hormone best explains why the gland became enlarged?', '[{"label": "A", "text": "Thyroid-stimulating hormone is suppressed"}, {"label": "B", "text": "Thyroid-stimulating hormone is elevated"}, {"label": "C", "text": "Thyrotropin-releasing hormone is suppressed"}, {"label": "D", "text": "Calcitonin is elevated"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because iodine is an essential substrate for building T3 and T4, so a deficiency blocks their synthesis and drops their circulating levels; because rising T3 and T4 normally inhibit the anterior pituitary through negative feedback, chronically low T3 and T4 remove that inhibition, and the pituitary secretes thyroid-stimulating hormone (TSH) in increasing amounts. The sustained TSH hyperstimulation drives thyroglobulin and colloid to accumulate in the follicles, enlarging the gland into a goiter. (Choice B) is correct: with negative feedback lifted by the low T3 and T4, TSH from the anterior pituitary rises and its chronic trophic drive on the follicles produces the enlargement. (Choice A) is incorrect: suppressed TSH would occur when T3 and T4 are high (as in a T4-secreting tumor), which would signal the pituitary to shut down; low TSH provides no growth stimulus and would leave the gland small, the opposite of the observed goiter. (Choice C) is incorrect: thyrotropin-releasing hormone (TRH) is a hypothalamic, not a pituitary, hormone, so it does not answer the question as posed; moreover, low thyroid hormone relieves feedback on the hypothalamus, so TRH rises rather than falls. (Choice D) is incorrect: calcitonin is secreted by the thyroid parafollicular (C) cells to lower blood calcium and is regulated by serum calcium, not by iodine status or the TSH feedback axis, so it neither reflects the deficiency nor drives follicular growth. Answering requires chaining the loss of substrate to falling hormone output, then to loss of feedback inhibition, and finally to the pituitary response that enlarges the gland, rather than recalling a single definition.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 100, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'reversed_relationship', NULL FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', NULL FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', NULL FROM q;

-- Q6 [Thyroid & Parathyroid] easy skill1 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'Residents of a landlocked mountain region who eat no seafood and use non-fortified salt frequently develop enlarged thyroid glands (goiter), even though their follicular cells contain normal amounts of tyrosine and thyroglobulin. Which dietary component are these individuals most likely lacking?', '[{"label": "A", "text": "Cholesterol"}, {"label": "B", "text": "Calcium"}, {"label": "C", "text": "Iodine"}, {"label": "D", "text": "Tryptophan"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because thyroid hormones (T3 and T4) are built by covalently attaching iodine atoms to the tyrosine residues of thyroglobulin in the follicular cells; when dietary iodine is scarce, the follicular cells cannot complete synthesis despite having plenty of tyrosine and thyroglobulin, so hormone output falls, TSH rises, and the gland enlarges into a goiter. (Choice C) is correct: iodine is the essential and unique component of thyroid hormone, and regions without seafood or iodized salt are the classic setting for iodine-deficiency goiter. (Choice B) is incorrect: calcium is regulated by the thyroid''s parafollicular (C) cells via calcitonin, but calcium is not incorporated into T3/T4, so a calcium shortage would not block their synthesis or cause goiter. (Choice A) is incorrect: cholesterol is the precursor for steroid hormones such as cortisol and the sex steroids, not for the tyrosine-derived thyroid hormones. (Choice D) is incorrect: tryptophan is the amino-acid precursor for melatonin and serotonin, whereas thyroid hormone is built on tyrosine, so tryptophan is not the limiting building block here. This question requires recognizing the specific element that must be supplied to make thyroid hormone, a Skill 1 recall of scientific knowledge.', 'easy', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 1, 60, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'same-gland confusion: calcium is regulated by the thyroid''s parafollicular cells (calcitonin), so a student links the thyroid to calcium' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'precursor confusion: assumes all hormones derive from cholesterol, the steroid-hormone precursor' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'wrong amino-acid precursor: confuses the tryptophan-derived amines (melatonin/serotonin) with the tyrosine-derived thyroid hormones' FROM q;

-- Q7 [Thyroid & Parathyroid] easy skill1 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A routine blood panel shows a patient''s ionized calcium concentration has fallen below the normal reference range. In response, an endocrine gland in the neck secretes a peptide hormone that acts on bone, kidney, and intestine to restore calcium toward normal. Which hormone is secreted?', '[{"label": "A", "text": "Thyroxine"}, {"label": "B", "text": "Calcitonin"}, {"label": "C", "text": "Aldosterone"}, {"label": "D", "text": "Parathyroid hormone"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because a fall in blood calcium is corrected by parathyroid hormone, the peptide secreted by the chief cells of the parathyroid glands, which stimulates osteoclast-driven calcium release from bone, increases calcium reabsorption in the kidney tubules, and activates vitamin D (calcitriol) to enhance intestinal calcium absorption. (Choice D) is correct: parathyroid hormone is released specifically in response to low blood calcium and raises it through its combined actions on bone, kidney, and intestine. (Choice B) is incorrect: calcitonin, produced by the parafollicular (C) cells of the thyroid, is secreted when blood calcium is high and lowers it by inhibiting osteoclasts; it acts in the opposite direction from what a low-calcium state requires. (Choice C) is incorrect: aldosterone, a mineralocorticoid from the adrenal cortex, regulates blood sodium and potassium and fluid balance, not blood calcium. (Choice A) is incorrect: thyroxine, the thyroid''s metabolic hormone, sets basal metabolic rate and promotes bone growth but is not the hormone that acutely corrects a low blood calcium level. This is a Skill 1 item because it requires recalling the source and function of the hormone that maintains blood calcium homeostasis.', 'easy', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 1, 45, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'antagonist hormone acting in the opposite direction' FROM q
  UNION ALL
  SELECT id, 'C', 'misconception', 'confusing which ion/electrolyte the hormone regulates' FROM q
  UNION ALL
  SELECT id, 'A', 'adjacent_fact', 'same-region gland hormone with an unrelated function' FROM q;

-- Q8 [Thyroid & Parathyroid] hard skill2 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A patient''s blood calcium is chronically elevated far above the normal set point. Which hormone, and its correct gland of origin, would the body secrete to counteract this excess?', '[{"label": "A", "text": "Calcitonin, from the thyroid gland"}, {"label": "B", "text": "Parathyroid hormone, from the parathyroid glands"}, {"label": "C", "text": "Calcitonin, from the parathyroid glands"}, {"label": "D", "text": "Calcitriol, from the kidneys"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because blood calcium is governed by an antagonistic hormone pair, and only the calcium-lowering member of that pair opposes an excess; that hormone is calcitonin, which is secreted by the parafollicular (C) cells of the thyroid gland when blood calcium rises, and it lowers calcium by inhibiting osteoclasts, reducing intestinal calcium absorption, and increasing urinary calcium loss. (Choice A) is correct: calcitonin is released in response to a rise in blood calcium and decreases blood calcium concentration, and its source is correctly identified as the thyroid gland, so both the hormone and its gland match the high-calcium scenario. (Choice B) is incorrect: although parathyroid hormone is correctly paired with the parathyroid glands, it is the antagonist that raises blood calcium (by stimulating osteoclasts and renal reabsorption), so secreting it would worsen the excess rather than correct it. (Choice C) is incorrect: calcitonin is indeed the calcium-lowering hormone, but its gland of origin is misassigned—it comes from the thyroid''s C cells, not the parathyroid glands, which secrete PTH instead. (Choice D) is incorrect: calcitriol (active vitamin D) is a genuine calcium-regulating hormone from the kidneys, but it raises blood calcium by increasing intestinal calcium absorption, making it the wrong direction for a high-calcium state. Reasoning through this scenario requires applying the antagonistic-pair concept to select the corrective hormone and simultaneously match it to the correct gland, which is characteristic of Skill 2 knowledge application rather than simple recall.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 90, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'correct gland-hormone pair but wrong direction (PTH raises calcium)' FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', 'correct calcium-lowering hormone paired with the wrong gland' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'real calcium hormone from correct source but wrong direction (calcitriol raises calcium)' FROM q;

-- Q9 [Thyroid & Parathyroid] medium skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A routine metabolic panel shows that a patient''s plasma Ca²⁺ concentration has dropped below the normal range. In response, an endocrine gland releases a peptide hormone that acts on the kidney tubules to help restore calcium levels. Which effect does this hormone most likely produce at the kidney?', '[{"label": "A", "text": "Reduced synthesis of active vitamin D"}, {"label": "B", "text": "Increased urinary excretion of calcium"}, {"label": "C", "text": "Increased reabsorption of filtered calcium"}, {"label": "D", "text": "Direct inhibition of renal osteoclasts"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because a fall in plasma Ca²⁺ triggers the parathyroid glands to secrete parathyroid hormone (PTH), which acts on the kidney tubules to increase reabsorption of calcium from the filtrate, thereby decreasing urinary calcium loss and returning blood calcium toward normal. (Choice C) is correct: PTH stimulates the renal tubules to reclaim filtered calcium, one of its three calcium-raising actions alongside stimulating osteoclastic bone resorption and initiating calcitriol production for intestinal absorption. (Choice B) is incorrect: increased urinary excretion of calcium is a calcitonin effect, secreted when calcium is high; it would further lower calcium and worsen the deficit, making it the reverse of the needed correction. (Choice A) is incorrect: the calcium-raising hormone initiates, not reduces, calcitriol (active vitamin D3) synthesis in the kidney, which boosts intestinal calcium absorption; reduced synthesis would lower calcium. (Choice D) is incorrect: osteoclasts reside in bone, not the kidney, and the calcium-raising hormone stimulates rather than inhibits osteoclast activity to release skeletal calcium. Reasoning from the low-calcium perturbation to the hormone''s corrective renal action requires applying the direction of calcium regulation rather than recalling a definition (Skill 2).', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'Applies calcitonin''s calcium-lowering renal action (more excretion) when the correction requires calcium retention' FROM q
  UNION ALL
  SELECT id, 'A', 'reversed_relationship', 'Reverses the hormone''s stimulatory effect on renal calcitriol synthesis' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'Misplaces osteoclasts in the kidney and inverts the hormone''s stimulatory bone effect' FROM q;

-- Q10 [Thyroid & Parathyroid] medium skill2 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A researcher administers a compound that locks vitamin D in the same activated form that parathyroid hormone causes the kidney to generate. Compared with untreated controls, how would intestinal epithelial handling of dietary calcium most likely change in the treated animals?', '[{"label": "A", "text": "Greater sodium uptake, as with aldosterone"}, {"label": "B", "text": "Reduced calcium uptake, mimicking calcitonin"}, {"label": "C", "text": "Unchanged calcium uptake but increased phosphate loss"}, {"label": "D", "text": "Greater calcium uptake across the gut lining"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the activated form of vitamin D described in the stem is calcitriol (1,25-dihydroxyvitamin D), the metabolite that intestinal epithelial cells require in order to absorb dietary calcium; supplying more of this active form therefore drives greater calcium uptake across the gut lining. (Choice D) is correct: calcitriol stimulates increased absorption of dietary calcium by the intestines, so a compound that maintains vitamin D in this active state enhances, rather than diminishes, calcium uptake across the intestinal epithelium. (Choice B) is incorrect: it confuses the effect of active vitamin D with that of calcitonin, the thyroid parafollicular-cell hormone that opposes calcium accumulation and reduces absorption of dietary calcium; active vitamin D promotes absorption rather than suppressing it. (Choice C) is incorrect: increased renal phosphate loss is a direct effect of parathyroid hormone on the kidney, not a consequence of activating vitamin D, which acts on the intestine to raise calcium absorption rather than leaving it unchanged. (Choice A) is incorrect: sodium reabsorption is governed by aldosterone from the adrenal cortex and is unrelated to the vitamin D pathway, which selectively enhances calcium handling rather than sodium handling. Skill 2 is demonstrated by tracing a perturbation of the vitamin D activation pathway to its predicted downstream physiological outcome at the intestinal epithelium rather than recalling a definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 80, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'opposing hormone (calcitonin) reverses the direction of the effect' FROM q
  UNION ALL
  SELECT id, 'C', 'process_step_confusion', 'attributes PTH''s renal phosphate action to the vitamin D / intestinal step' FROM q
  UNION ALL
  SELECT id, 'A', 'scale_unit_error', 'wrong electrolyte — sodium/aldosterone substituted for calcium' FROM q;

-- Q11 [Thyroid & Parathyroid] hard skill2 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'During a thyroidectomy, a surgeon inadvertently excises all four small glands embedded on the posterior thyroid surface, and the patient''s serum shows the change days later. What is the most likely direction of the patient''s blood calcium, and why?', '[{"label": "A", "text": "Falls; three calcium-raising pathways are lost"}, {"label": "B", "text": "Rises; unopposed calcitonin frees skeletal calcium"}, {"label": "C", "text": "Falls; aldosterone secretion is now suppressed"}, {"label": "D", "text": "Rises; renal calcium excretion is blocked"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because the excised glands are the parathyroid glands, whose hormone (PTH) is the principal defender of blood calcium: it stimulates osteoclast-mediated bone resorption, promotes calcium reabsorption from the renal tubules, and initiates renal synthesis of calcitriol (active vitamin D), which drives intestinal calcium absorption. Removing the glands eliminates all three calcium-raising actions at once, so serum calcium falls (hypocalcemia). (Choice A) is correct: with PTH gone, bone release, renal reabsorption, and vitamin-D-mediated gut uptake of calcium all cease, and the net result is a drop in blood calcium. (Choice B) is incorrect: calcitonin (from the thyroid''s parafollicular C cells) lowers blood calcium; even if calcitonin were left unopposed, it would push calcium down, not up, and its physiologic role in humans is minor compared with PTH. (Choice C) is incorrect: aldosterone is an adrenal mineralocorticoid governing sodium and potassium, not calcium, and its secretion is unaffected by parathyroid removal, so it is the wrong hormonal axis. (Choice D) is incorrect: loss of PTH reduces renal calcium reabsorption, meaning more calcium is lost in the urine rather than less, which would lower calcium and cannot explain a rise. Answering requires chaining the identity of the removed glands to the coordinated loss of three PTH-dependent pathways and predicting the net effect on serum calcium, a Skill 2 multi-step application of endocrine physiology.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 100, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'Treats the removed gland''s hormone as calcium-raising and calcitonin as unopposed calcium-raiser, reversing both directions' FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', 'Invokes a real adrenal hormone (aldosterone) on the wrong ion axis (Na+/K+, not Ca2+)' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'Assumes PTH loss blocks urinary calcium excretion, when it actually reduces reabsorption and increases excretion' FROM q;

-- Q12 [Thyroid & Parathyroid] medium skill2 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Thyroid & Parathyroid', 'A patient''s serum calcium reading falls to 7.8 mg/dL (normal 8.5–10.2 mg/dL) after several weeks of dietary calcium deficiency. Homeostatic feedback triggers secretion of the hormone that will drive this value back toward the normal range. Which hormone is secreted?', '[{"label": "A", "text": "Calcitonin"}, {"label": "B", "text": "Parathyroid hormone"}, {"label": "C", "text": "Calcitriol (active vitamin D)"}, {"label": "D", "text": "Aldosterone"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because the patient''s serum calcium has dropped below the normal range, and the correction required is an increase in blood calcium; parathyroid hormone (PTH) is the hormone secreted in response to low blood calcium, and it raises the concentration by stimulating osteoclasts to resorb bone, promoting renal calcium reabsorption, and indirectly increasing intestinal calcium absorption. (Choice B) is correct: PTH, secreted by the chief cells of the parathyroid glands in response to falling blood calcium, elevates serum calcium and is therefore the hormone that would move a low value back toward normal. (Choice A) is incorrect: calcitonin, released by the parafollicular (C) cells of the thyroid, is secreted in response to elevated blood calcium and lowers it, which is the opposite of the correction this hypocalcemic patient requires. (Choice C) is incorrect: calcitriol does raise blood calcium by increasing intestinal absorption, but its formation is a downstream step triggered by PTH rather than the primary hormone secreted directly in response to the low-calcium signal; the discriminating hormone the feedback loop secretes is PTH. (Choice D) is incorrect: aldosterone is a mineralocorticoid that regulates sodium retention, potassium excretion, and blood volume, and it does not govern the blood calcium set point. Answering requires applying the concept that a hormone secreted to correct hypocalcemia must be one that raises calcium, then selecting the source hormone whose secretion is triggered directly by the low-calcium signal.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'reversed_relationship', 'Confuses the calcium-lowering hormone with the calcium-raising hormone (opposite direction of correction)' FROM q
  UNION ALL
  SELECT id, 'C', 'process_step_confusion', 'Selects the downstream PTH-triggered effector (calcitriol) instead of the primary hormone secreted in response to the low-calcium signal' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'Substitutes a hormone from the wrong regulatory axis (Na+/volume) for the calcium axis' FROM q;

-- Q13 [Adrenal Glands] medium skill2 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'The adrenal cortex is arranged in three concentric zones, each specializing in one class of steroid hormone. A toxin selectively destroys only the deepest cortical zone, the layer lying just outside the medulla. Which hormones'' production is most directly lost?', '[{"label": "A", "text": "Catecholamines"}, {"label": "B", "text": "Mineralocorticoids"}, {"label": "C", "text": "Glucocorticoids"}, {"label": "D", "text": "Adrenal androgens"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.''

The answer is D because the three zones of the adrenal cortex are layered outer to inner as the zona glomerulosa (mineralocorticoids), the zona fasciculata (glucocorticoids), and the deepest zona reticularis, which produces the adrenal androgens. Destroying only the deepest zone therefore removes androgen production.

(Choice D) is correct: the zona reticularis is the deepest cortical zone and is the source of the adrenal androgens, so its destruction most directly abolishes androgen output.

(Choice B) is incorrect: mineralocorticoids such as aldosterone come from the OUTERMOST zone, the zona glomerulosa, which the toxin spares.

(Choice C) is incorrect: glucocorticoids such as cortisol come from the MIDDLE zone, the zona fasciculata, not the deepest layer.

(Choice A) is incorrect: catecholamines are made by the adrenal MEDULLA, not by any zone of the cortex, so they are not a cortical-zone product at all.

This Skill 2 item requires mapping the described cortical-zone position (deepest, adjacent to the medulla) onto the specific steroid class that zone produces.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'assigns the outermost zone''s product (mineralocorticoids) to the deepest zone' FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', 'assigns the middle zone''s product (glucocorticoids) to the deepest zone' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'confuses a medullary product (catecholamines) with a cortical-zone steroid' FROM q;

-- Q14 [Adrenal Glands] medium skill2 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A patient takes a daily prescription steroid for years to control chronic joint inflammation, and physicians note the drug mimics a hormone the adrenal cortex secretes during prolonged stress. During routine monitoring, which additional systemic change would clinicians most expect to find?', '[{"label": "A", "text": "Elevated fasting blood glucose"}, {"label": "B", "text": "Reduced fasting blood glucose"}, {"label": "C", "text": "Decreased blood sodium concentration"}, {"label": "D", "text": "Heightened antibody response to infection"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because the described drug mimics cortisol, the principal glucocorticoid of the adrenal cortex (zona fasciculata), and glucocorticoids drive the catabolism of stored nutrients and stimulate gluconeogenesis to synthesize new glucose; chronically elevated glucocorticoid activity therefore raises circulating glucose, which is why patients on long-term steroids and those with cortisol excess (Cushing''s) develop hyperglycemia. (Choice A) is correct: sustained glucocorticoid exposure promotes gluconeogenesis and inhibits tissue building, elevating blood glucose. (Choice B) is incorrect: lowering blood glucose is the action of insulin from the pancreas, not of a glucocorticoid, which raises glucose in the opposite direction. (Choice C) is incorrect: sodium regulation is governed by the mineralocorticoid aldosterone, which increases blood Na+ levels; it is a distinct adrenal cortical hormone and does not describe the glucose-raising, anti-inflammatory drug in question. (Choice D) is incorrect: glucocorticoids downregulate the immune system and inhibit the inflammatory response—the very reason the drug is prescribed—so they compromise, rather than heighten, antibody-based defenses, and chronically elevated levels impair resistance to infection. Applying knowledge of glucocorticoid function to a novel clinical scenario, one predicts the combined effect of elevated glucose alongside suppressed immunity, identifying elevated fasting blood glucose as the expected finding.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'confusing cortisol''s glucose-raising action with insulin''s glucose-lowering action' FROM q
  UNION ALL
  SELECT id, 'C', 'adjacent_fact', 'attributing the mineralocorticoid aldosterone''s sodium effect (and wrong direction) to the glucocorticoid' FROM q
  UNION ALL
  SELECT id, 'D', 'reversed_relationship', 'assuming a stress hormone boosts immunity rather than suppressing it' FROM q;

-- Q15 [Adrenal Glands] easy skill1 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'During a prolonged emotional crisis, a person''s blood glucose rises as stored glycogen, fats, and proteins are broken down to supply fuel. Which hormone is chiefly responsible for this sustained glucose mobilization during long-term stress?', '[{"label": "A", "text": "Aldosterone"}, {"label": "B", "text": "Cortisol"}, {"label": "C", "text": "Epinephrine"}, {"label": "D", "text": "Glucagon"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because cortisol is the principal glucocorticoid secreted by the zona fasciculata of the adrenal cortex, and in response to long-term stress it promotes the catabolism of glycogen, triglycerides, and muscle protein so those raw materials can be used to synthesize glucose, sustaining elevated blood glucose as a ready fuel. (Choice A) is incorrect: aldosterone is a mineralocorticoid that regulates sodium and potassium balance, blood volume, and blood pressure; it does not mobilize glucose or drive nutrient catabolism. (Choice B) is correct: cortisol is the hormone that raises blood glucose during sustained stress by driving the breakdown of stored glycogen, fats, and proteins for gluconeogenesis. (Choice C) is incorrect: epinephrine does raise blood glucose, but it is the adrenal-medulla catecholamine of the acute, short-term fight-or-flight response and acts mainly by converting liver and muscle glycogen to glucose, so it does not account for the sustained mobilization of fats and proteins seen in prolonged stress. (Choice D) is incorrect: glucagon raises blood glucose, but it is a pancreatic hormone whose principal action is stimulating hepatic glycogen breakdown and gluconeogenesis; it is not the hormone that drives the broad, sustained catabolism of stored triglycerides and muscle protein during long-term stress. This question assesses Skill 1 by requiring the student to recall and identify the hormone that matches a described sustained-stress and glucose-mobilization scenario.', 'easy', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 1, 60, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'adjacent_fact', 'same-gland-wrong-function' FROM q
  UNION ALL
  SELECT id, 'C', 'process_step_confusion', 'acute-vs-chronic-stress-confusion' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'right-effect-wrong-source-gland' FROM q;

-- Q16 [Adrenal Glands] hard skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A patient with a chronic inflammatory condition takes daily high doses of a synthetic steroid drug for several months. The drug binds and activates the same intracellular receptors as the principal stress steroid made by the outer region of the adrenal glands — including the receptors in the hypothalamus and pituitary that sense that steroid''s level. After several months, what happens to the anterior pituitary''s output of the tropic hormone that normally drives the adrenal cortex, and to the size of the cortex itself?', '[{"label": "A", "text": "Tropic hormone rises; the cortex atrophies"}, {"label": "B", "text": "Tropic hormone rises; the cortex enlarges"}, {"label": "C", "text": "Tropic hormone falls; the cortex atrophies"}, {"label": "D", "text": "Tropic hormone falls; the cortex enlarges"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because the synthetic drug occupies the same glucocorticoid receptors as cortisol and therefore mimics its downstream effects, including the negative-feedback signal that suppresses the hypothalamic-pituitary-adrenal (HPA) axis; the hypothalamus and anterior pituitary sense an ''adequate'' glucocorticoid state and reduce their signaling, so the pituitary''s tropic hormone (ACTH) falls. Because ACTH is also the trophic stimulus that maintains the cortex, its chronic withdrawal starves the zona fasciculata of stimulation and the cortex atrophies. (Choice C) is correct: high sustained glucocorticoid-receptor activation drives negative feedback that lowers ACTH, and loss of trophic ACTH support causes the adrenal cortex to shrink. (Choice B) is incorrect: rising tropic hormone with an enlarging cortex describes an ACTH-secreting pituitary tumor (a cause of Cushing''s disease), in which the pituitary is the source of excess signal; here the excess glucocorticoid comes from an outside drug, which suppresses—rather than raises—ACTH, so this is a partial-truth trap that confuses two different high-cortisol scenarios. (Choice A) is incorrect: it correctly predicts cortical atrophy but reverses the feedback direction, since negative feedback from a glucocorticoid signal lowers ACTH rather than raising it. (Choice D) is incorrect: it correctly predicts that ACTH falls, but a fall in trophic ACTH cannot enlarge the cortex; without ACTH stimulation the cortex loses mass. Skill 2: this item requires chaining exogenous receptor activation to feedback suppression of ACTH and then to loss of trophic support and cortical atrophy, distinguishing a drug-driven perturbation from a tumor-driven one.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 100, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'partial_truth', 'Confuses an ACTH-secreting pituitary tumor (high ACTH, cortical hyperplasia) with exogenous-steroid suppression; assumes more glucocorticoid means more of everything upstream' FROM q
  UNION ALL
  SELECT id, 'A', 'reversed_relationship', 'Correctly predicts cortical atrophy but reverses the feedback direction, treating high glucocorticoid as raising ACTH rather than suppressing it' FROM q
  UNION ALL
  SELECT id, 'D', 'process_step_confusion', 'Correctly predicts ACTH falls but fails to link loss of trophic ACTH to cortical atrophy, incorrectly pairing low ACTH with an enlarged cortex' FROM q;

-- Q17 [Adrenal Glands] medium skill2 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A diuretic drug binds and blocks receptors on the principal cells of the distal nephron. After the patient takes it, urinalysis shows that Na+ excretion has risen while K+ is now retained in the blood. The normal action of which adrenal cortex hormone is this drug opposing?', '[{"label": "A", "text": "Aldosterone"}, {"label": "B", "text": "Cortisol"}, {"label": "C", "text": "Atrial natriuretic peptide"}, {"label": "D", "text": "Antidiuretic hormone"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because the drug produces the exact opposite of aldosterone''s normal effect on the distal nephron: aldosterone drives Na+ reabsorption while simultaneously driving K+ secretion into the forming urine, so blocking its receptor causes Na+ to be lost in the urine and K+ to be retained in the blood, precisely the pattern described. (Choice A) is correct: aldosterone, the major mineralocorticoid of the adrenal cortex, acts on principal cells to increase Na+ recovery and increase K+ excretion, so a receptor blocker reverses both effects, yielding Na+ wasting with K+ retention. (Choice B) is incorrect: cortisol is a glucocorticoid whose primary role is regulating glucose and fat metabolism and the stress response, not the coupled Na+-reabsorption/K+-secretion action at distal-nephron principal cells described here. (Choice C) is incorrect: atrial natriuretic peptide already promotes Na+ excretion (it inhibits aldosterone), so blocking it would tend to retain Na+, the opposite of the observed rise in Na+ excretion, and it is secreted by cardiac atria, not the adrenal cortex. (Choice D) is incorrect: antidiuretic hormone governs water reabsorption via the posterior pituitary, not the coupled Na+/K+ handling described, and blocking it would primarily increase water loss rather than reverse Na+ and K+ movement. Skill 2: this item requires translating an observed, reversed electrolyte-handling pattern back to the hormone whose defined mechanism, when opposed, produces it.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'same-gland-wrong-hormone: cortisol is also an adrenal cortex steroid but is a glucocorticoid, not the mineralocorticoid governing distal Na+/K+ handling' FROM q
  UNION ALL
  SELECT id, 'C', 'reversed_relationship', 'opposite-effector: ANP also promotes Na+ excretion, so a student who fixates on the Na+ clue may pick it, but blocking ANP would retain Na+ and it is not adrenal-cortex-derived' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'conflates-water-with-electrolytes: student assumes the kidney-fluid hormone ADH also controls Na+/K+, when ADH regulates water, not the coupled Na+ reabsorption/K+ secretion' FROM q;

-- Q18 [Adrenal Glands] hard skill2 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A hypertensive patient begins a drug that inhibits a lung-localized enzyme responsible for cleaving a circulating peptide into its vasoactive form. After several days on the drug, which change in adrenal cortex output and blood pressure would be expected?', '[{"label": "A", "text": "Reduced cortisol; lowered blood pressure"}, {"label": "B", "text": "Reduced aldosterone; lowered blood pressure"}, {"label": "C", "text": "Elevated aldosterone; raised blood pressure"}, {"label": "D", "text": "Reduced epinephrine; lowered blood pressure"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because the described drug is an angiotensin-converting enzyme (ACE) inhibitor: ACE, located in the lungs, converts inactive angiotensin I into active angiotensin II. Angiotensin II is the direct stimulus that signals the adrenal cortex (zona glomerulosa) to secrete aldosterone. Blocking ACE therefore lowers angiotensin II, so aldosterone secretion falls; because aldosterone normally drives Na+ (and thus water) reabsorption and angiotensin II normally drives vasoconstriction, losing both effects reduces blood volume and vascular tone, lowering blood pressure. (Choice B) is correct: less angiotensin II removes the stimulus for aldosterone, and the combined loss of Na+/water retention plus vasoconstriction lowers blood pressure, which is precisely why ACE inhibitors treat hypertension. (Choice A) is incorrect: cortisol is a glucocorticoid from the zona fasciculata whose secretion is governed by the hypothalamic CRH to anterior-pituitary ACTH axis, not by angiotensin II; blocking ACE does not remove cortisol''s stimulus, so cortisol output is not the hormone that changes here, even though it also originates in the adrenal cortex. (Choice C) is incorrect: this reverses the causal chain. Blocking the enzyme reduces angiotensin II, so aldosterone falls rather than rises, and blood pressure decreases; a rise in both would occur only if angiotensin II production increased. (Choice D) is incorrect: epinephrine is a catecholamine released by the adrenal medulla, not a hormone of the adrenal cortex, and its release is controlled by sympathetic (preganglionic) input rather than the angiotensin pathway, so it is unaffected by ACE inhibition. This question requires Skill 2 reasoning because the student must trace a multi-step signaling chain from a blocked enzyme through the missing peptide to the downstream hormone and then predict the integrated physiological outcome, rather than recalling a single stated fact.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 105, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'adjacent_fact', 'same-gland-wrong-hormone (cortisol from zona fasciculata regulated by CRH/ACTH, not angiotensin II)' FROM q
  UNION ALL
  SELECT id, 'C', 'reversed_relationship', 'inverts the effect of enzyme inhibition (aldosterone and BP rise instead of fall)' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'wrong adrenal region and hormone class (medullary catecholamine treated as RAAS-controlled cortical output)' FROM q;

-- Q19 [Adrenal Glands] medium skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'In a post-menopausal patient whose ovaries have ceased functioning, an adrenal steroid secreted by the deepest region of the cortex becomes the principal precursor that peripheral tissues convert into estrogens, and it neither raises blood glucose nor promotes sodium retention. This steroid is best classified as which of the following?', '[{"label": "A", "text": "A glucocorticoid"}, {"label": "B", "text": "A mineralocorticoid"}, {"label": "C", "text": "An adrenal androgen"}, {"label": "D", "text": "A medullary catecholamine"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because the deepest cortical region, the zona reticularis, secretes a class of steroid sex hormones called adrenal androgens; these supplement gonadal androgens and are converted in peripheral tissues to testosterone or estrogens, which is why they become the main source of estrogens after the ovaries decline. (Choice C) is correct: adrenal androgens are the cortical sex hormones produced by the zona reticularis, and because they serve as the estrogen precursor in a post-menopausal patient and act on neither glucose nor salt balance, this classification matches every feature described. (Choice B) is incorrect: mineralocorticoids such as aldosterone come from the zona glomerulosa and regulate sodium and potassium balance, but the stem specifies the steroid does not promote sodium retention, ruling out this class. (Choice A) is incorrect: glucocorticoids such as cortisol come from the zona fasciculata and raise blood glucose, yet the stem states the steroid does not raise blood glucose, so it cannot belong to this class. (Choice D) is incorrect: catecholamines such as epinephrine originate in the adrenal medulla and are amino-acid-derived, not steroids of the cortex, so a medullary catecholamine cannot be the cortical precursor described. Reaching the answer requires applying knowledge of which cortical zone produces which hormone class to a steroid defined only by its function, rather than recalling a stated definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'misconception', 'confuses cortical zone/product, defaulting to the salt-regulating mineralocorticoid' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'assumes any adrenal cortex steroid is the dominant glucocorticoid cortisol' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'source confusion between adrenal cortex steroids and adrenal medulla catecholamines' FROM q;

-- Q20 [Adrenal Glands] easy skill1 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'During an acute fright, sympathetic input triggers the chromaffin cells at the core of an adrenal gland to dump a fast-acting signal into the bloodstream within seconds. Which hormones are released, and to which chemical class do they belong?', '[{"label": "A", "text": "Insulin and glucagon; proteins"}, {"label": "B", "text": "Cortisol and aldosterone; steroids"}, {"label": "C", "text": "Thyroxine and triiodothyronine; amines"}, {"label": "D", "text": "Epinephrine and norepinephrine; amines"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the chromaffin cells of the adrenal medulla—the inner core of the adrenal gland driven by the sympathetic nervous system during acute stress—secrete epinephrine and norepinephrine directly into the systemic circulation, and because these two hormones are synthesized from the amino acid tyrosine, they are chemically classified as catecholamines, a type of amine hormone. (Choice D) is correct: the adrenal medulla''s chromaffin cells release epinephrine and norepinephrine as the rapid fight-or-flight signal, and Table 17.5 lists both under the chemical class "Amine." (Choice B) is incorrect: cortisol and aldosterone are steroids, but they are produced by the adrenal cortex (the outer region), and cortisol is the slow-acting long-term stress hormone, not the seconds-fast medullary signal. (Choice C) is incorrect: thyroxine (T4) and triiodothyronine (T3) are indeed amine-class hormones, but they are secreted by the thyroid gland to set basal metabolic rate over hours to days, not by the adrenal medulla during acute fright. (Choice A) is incorrect: insulin and glucagon are protein/peptide hormones from the pancreatic islets that regulate blood glucose, not catecholamines released by the adrenal medulla. As a Skill 1 item, this question asks the student to recall the specific hormones secreted by the adrenal medulla and their chemical classification.', 'easy', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 1, 45, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'same_gland_wrong_region' FROM q
  UNION ALL
  SELECT id, 'C', 'partial_truth', 'correct_class_wrong_source' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'wrong_gland_wrong_class' FROM q;

-- Q21 [Adrenal Glands] medium skill2 ans=B
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A driver narrowly avoids a highway collision. In the seconds afterward, which combination of changes would best characterize the acute physiological response mobilizing her body for immediate exertion?', '[{"label": "A", "text": "Slowed heart rate, narrowed airways, lowered blood glucose"}, {"label": "B", "text": "Faster heart rate, widened airways, elevated blood glucose"}, {"label": "C", "text": "Elevated blood glucose, slowed heart rate, narrowed airways"}, {"label": "D", "text": "Sodium retention, increased blood volume, raised blood pressure"}]'::jsonb, 'B', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because an acute, short-term stressor triggers the sympathomedullary (SAM) pathway, prompting the adrenal medulla''s chromaffin cells to release the catecholamines epinephrine and norepinephrine into circulation; these hormones increase heart rate, dilate the airways to raise blood oxygen, and signal the liver and skeletal muscle to convert glycogen into glucose, raising blood glucose to fuel immediate exertion. (Choice B) is correct: rising heart rate, bronchodilation, and elevated blood glucose are precisely the systemic effects of medullary catecholamines during the fight-or-flight (alarm) reaction. (Choice A) is incorrect: a slowed heart rate, constricted airways, and falling blood glucose describe the opposite, rest-and-digest direction (parasympathetic tone plus insulin action), which is suppressed—not activated—during acute stress. (Choice C) is incorrect: it correctly pairs elevated glucose with stress but reverses the cardiac and respiratory effects; catecholamines speed the heart and open the airways rather than slowing the heart and narrowing bronchioles. (Choice D) is incorrect: sodium retention, expanded blood volume, and raised pressure are effects of aldosterone from the adrenal cortex (a mineralocorticoid governing fluid balance) acting over minutes to hours, not the seconds-scale medullary catecholamines that drive the rapid exertion response. Reasoning from the described acute perturbation to the coordinated set of downstream target-organ effects, rather than recalling a single fact, is the Skill 2 demand here.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'A', 'reversed_relationship', 'Applies the opposite (parasympathetic/rest-and-digest) direction to every target organ' FROM q
  UNION ALL
  SELECT id, 'C', 'partial_truth', 'Keeps the correct glucose effect but reverses the cardiac and respiratory directions' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'Substitutes adrenal cortex (aldosterone) fluid-balance effects for medullary catecholamine effects' FROM q;

-- Q22 [Adrenal Glands] medium skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'Two hormones are extracted from a single adrenal gland. One is synthesized from cholesterol and exerts effects that build over hours; the other is synthesized from the amino acid tyrosine and takes effect within seconds. From which parts of the gland do these two hormones originate, in that order?', '[{"label": "A", "text": "Both from the cortex"}, {"label": "B", "text": "The medulla, then the cortex"}, {"label": "C", "text": "The cortex, then the medulla"}, {"label": "D", "text": "Both from the medulla"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.''

The answer is C because the adrenal cortex builds steroid hormones from cholesterol, and because these act by changing gene transcription their effects develop slowly over hours; the adrenal medulla builds catecholamines from the amino acid tyrosine, and because these act through rapid second-messenger signaling their effects appear within seconds. The cholesterol-derived, slow hormone is thus cortical and the tyrosine-derived, fast hormone is medullary.

(Choice C) is correct: the cholesterol-derived, slow-acting hormone comes from the cortex, and the tyrosine-derived, fast-acting hormone comes from the medulla.

(Choice B) is incorrect: this reverses the two regions; the cortex (not the medulla) makes the cholesterol-based steroid, and the medulla (not the cortex) makes the tyrosine-based catecholamine.

(Choice A) is incorrect: the cortex makes only the steroid; the fast, tyrosine-derived catecholamine is a medullary product, so both cannot originate in the cortex.

(Choice D) is incorrect: the medulla makes only the catecholamine; the slow, cholesterol-derived steroid is a cortical product, so both cannot originate in the medulla.

This Skill 2 item asks the student to infer each hormone''s source region from its chemical precursor and time course rather than from a stated label.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'swaps the two source regions for the steroid and the catecholamine' FROM q
  UNION ALL
  SELECT id, 'A', 'misconception', 'attributes both hormones to the cortex, ignoring the medulla''s catecholamines' FROM q
  UNION ALL
  SELECT id, 'D', 'misconception', 'attributes both hormones to the medulla, ignoring the cortex''s steroids' FROM q;

-- Q23 [Adrenal Glands] medium skill2 ans=D
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'During a near-miss car accident, a driver''s blood glucose spikes within seconds, well before any change in pancreatic secretion could take effect. Which hormone drives this near-instantaneous rise, and by what action?', '[{"label": "A", "text": "Insulin, releasing glucose from adipose tissue"}, {"label": "B", "text": "Glucagon, breaking down stored glycogen"}, {"label": "C", "text": "Cortisol, synthesizing new glucose molecules"}, {"label": "D", "text": "Epinephrine, breaking down stored glycogen"}]'::jsonb, 'D', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the scenario describes an acute, seconds-scale stress response driven by the sympathetic nervous system, which directly stimulates the chromaffin cells of the adrenal medulla to release epinephrine; epinephrine signals the liver and skeletal muscle to convert stored glycogen into glucose (glycogenolysis), producing the near-instantaneous rise in blood glucose. (Choice D) is correct: epinephrine, a catecholamine from the adrenal medulla, is released via a rapid neural pathway and triggers glycogen breakdown, matching both the source and the mechanism required by the described time course. (Choice B) is incorrect: glucagon also raises blood glucose through glycogenolysis, but it originates from the alpha cells of the pancreas and is secreted in response to declining glucose during fasting, not through the seconds-scale sympathetic pathway that the stem''s timing excludes. (Choice C) is incorrect: cortisol, an adrenal cortex glucocorticoid, raises glucose largely by promoting gluconeogenesis and nutrient catabolism during long-term stress via the slower CRH-ACTH pathway, so both its speed and its stated mechanism (synthesizing new glucose) are wrong for an immediate spike. (Choice A) is incorrect: insulin lowers rather than raises blood glucose and promotes glycogen storage, and glucose is not mobilized from adipose tissue, so this reverses the direction of the effect. Answering requires interpreting the described time course and stress context to deduce which gland is activated and which biochemical action fits, rather than recalling a definition.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 75, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'correct_mechanism_wrong_source' FROM q
  UNION ALL
  SELECT id, 'C', 'process_step_confusion', 'gluconeogenesis_vs_glycogenolysis' FROM q
  UNION ALL
  SELECT id, 'A', 'reversed_relationship', 'glucose_lowering_hormone_confused_for_raising' FROM q;

-- Q24 [Adrenal Glands] medium skill2 ans=A
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'During a fright, a sympathetic preganglionic fiber synapses directly on chromaffin cells in the core of the adrenal gland, which then empty their secretory product into the capillaries draining the gland rather than onto a specific postsynaptic target. Compared with a postganglionic sympathetic neuron releasing its transmitter at a discrete synapse, how does this arrangement most likely shape the onset and reach of the adrenal core''s output?', '[{"label": "A", "text": "Rapid onset, with effects spread across many distant organs at once"}, {"label": "B", "text": "Delayed onset, but effects confined to one target organ"}, {"label": "C", "text": "Rapid onset, but effects restricted to a single adjacent organ"}, {"label": "D", "text": "Delayed onset, then permanent effects on all tissues"}]'::jsonb, 'A', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is A because the chromaffin cells are triggered by a sympathetic nerve impulse, giving the response the rapid onset of the nervous system, yet they dump their secretory product into the bloodstream rather than at a synapse, so those molecules travel widely and act on distant cells throughout the body at once, combining nervous-system speed with endocrine breadth. (Choice A) is correct: neural stimulation drives fast release, and because the product enters the systemic circulation it exerts effects broadly on many organs simultaneously, exactly as the fight-or-flight response requires. (Choice B) is incorrect: it treats the output as a slow hormone acting on only one organ, but a nerve impulse triggers the release, so onset is fast, not delayed, and blood-borne delivery reaches many organs, not one. (Choice C) is incorrect: it correctly recognizes the fast onset but wrongly assumes the product stays local like a neurotransmitter at a synapse, ignoring that release into the bloodstream carries it to widely distributed targets. (Choice D) is incorrect: it confuses the medullary output with the slow, sustained steroid response of the adrenal cortex; the medulla''s catecholamines have a very short half-life (about one minute) and are cleared quickly rather than acting permanently. To arrive at this answer, a student must reason from the described anatomy—a nerve-triggered cell secreting into blood—rather than recall a memorized definition, integrating that neural triggering yields speed while circulatory delivery yields body-wide reach.', 'medium', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 80, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'reversed_relationship', 'assumes all hormonal signaling is slow and narrowly targeted, reversing both the onset (nerve-triggered = fast) and the reach (blood-borne = broad)' FROM q
  UNION ALL
  SELECT id, 'C', 'misconception', 'treats blood-borne catecholamines like a neurotransmitter confined to a single synapse/adjacent organ, missing that circulation delivers them body-wide' FROM q
  UNION ALL
  SELECT id, 'D', 'process_step_confusion', 'confuses the fast, short-lived medullary catecholamine response with the slow, sustained steroid (cortisol) response of the adrenal cortex' FROM q;

-- Q25 [Adrenal Glands] hard skill2 ans=C
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds, figure_svg)
  VALUES ('bio_biochem', 'The Endocrine System', 'Adrenal Glands', 'A patient has a tumor in the inner region of one adrenal gland whose cells are anatomically continuous with postganglionic sympathetic neurons. The tumor autonomously secretes its signaling molecule into the blood. Which cluster of findings would this tumor most likely produce?', '[{"label": "A", "text": "Central obesity, hyperglycemia, and immune suppression"}, {"label": "B", "text": "Hypertension with sodium retention and hypokalemia"}, {"label": "C", "text": "Hypertension, tachycardia, and hyperglycemia"}, {"label": "D", "text": "Deepening voice and increased body hair"}]'::jsonb, 'C', 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is C because the tumor arises in the adrenal medulla—the inner region composed of chromaffin cells that are modified postganglionic sympathetic neurons—so its secreted product is the catecholamines epinephrine and norepinephrine. These hormones increase heart rate, pulse, and blood pressure and signal the liver and skeletal muscle to convert glycogen into glucose, raising blood glucose. (Choice C) is correct: hypertension, tachycardia, and elevated blood glucose together map directly onto the fight-or-flight actions of medullary catecholamines, and no other adrenal product produces that exact triad. (Choice B) is incorrect: sodium retention with potassium loss reflects excess aldosterone, a mineralocorticoid made by the zona glomerulosa of the adrenal cortex, not by the medulla; aldosterone drives Na+ retention and K+ excretion but does not cause tachycardia or hyperglycemia. (Choice A) is incorrect: central (truncal) adiposity, hyperglycemia, and immune suppression describe cortisol excess (Cushing pattern) from the zona fasciculata of the cortex; although both cortisol and catecholamines can raise glucose, the fat redistribution and immunosuppression are glucocorticoid-specific and do not arise from the medulla. (Choice D) is incorrect: virilizing signs such as a deepening voice and increased body hair result from excess androgens produced by the zona reticularis of the adrenal cortex, again a cortical rather than medullary product. A Skill 2 solver must first localize the tumor to the medulla from the anatomical clues, identify catecholamines as the secreted product, and then predict the downstream cardiovascular and metabolic picture, discriminating it from the three cortical-excess syndromes.', 'hard', '3A', 'Endocrine System: Hormones and Their Sources', 'biology', 2, 100, NULL)
  RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
  SELECT id, 'B', 'adjacent_fact', 'Attributes the medullary tumor''s effects to aldosterone (zona glomerulosa) — sodium retention and hypokalemia — instead of catecholamines' FROM q
  UNION ALL
  SELECT id, 'A', 'partial_truth', 'Cortisol excess also raises blood glucose, making this Cushing pattern a tempting partial overlap, but central obesity and immunosuppression are glucocorticoid-specific and cortical, not medullary' FROM q
  UNION ALL
  SELECT id, 'D', 'adjacent_fact', 'Assigns virilization from zona reticularis androgen excess to the tumor instead of the medullary catecholamine product' FROM q;

