-- ════════════════════════════════════════════════════════════════════
-- Bio Ch5 Endocrine — cross-batch audit remediation (11 questions)
-- 3 answer-leak fixes (idx34 cortisol, idx50 ACTH, idx94 ANP), 1 ambiguous fix (idx95 ANP->aldosterone),
-- 7 near-duplicate differentiations (idx36,42,9,64,29,58,92). UPDATE by id (student history preserved).
-- Answer letters rebalanced to keep the 100-question chapter even. Idempotent; safe to re-run.
-- ════════════════════════════════════════════════════════════════════

BEGIN;

-- idx34 [Hormone Transport, Specificity & Kinetics] leak_fix -> easy skill2 ans=B
UPDATE questions SET
  question_text = 'Cortisol is a steroid hormone synthesized from cholesterol by the adrenal cortex. When researchers sample blood from a healthy person, they find that essentially all of the circulating cortisol is attached to a plasma transport protein (corticosteroid-binding globulin), whereas epinephrine from the adrenal medulla circulates in the free, unbound state. Which property of cortisol''s chemistry most directly explains why it must be carried by a transport protein in the bloodstream?',
  options = '[{"label": "A", "text": "It carries a strong net negative electric charge"}, {"label": "B", "text": "It is lipophilic, being derived from cholesterol"}, {"label": "C", "text": "It is too large a molecule to remain suspended in plasma"}, {"label": "D", "text": "It has an unusually short circulating half-life"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Mechanisms of Hormone Action.'' The answer is B because cortisol is a steroid hormone made from cholesterol, so it is lipophilic (hydrophobic); such nonpolar molecules mix poorly with the aqueous plasma, so they must ride on a carrier protein to be transported efficiently in blood, unlike the catecholamine epinephrine, which circulates freely. (Choice B) is correct: steroids are synthesized from cholesterol and inherit its nonpolar, lipid-loving character; because they do not associate well with the watery plasma, they are transported bound to plasma proteins such as corticosteroid-binding globulin and albumin. (Choice A) is incorrect: cortisol is a neutral, uncharged steroid molecule, not a strongly charged ion; a net charge would actually increase its compatibility with water, so it is not the reason a carrier is needed. (Choice C) is incorrect: cortisol (about 362 g/mol) is a small molecule, far smaller than the plasma proteins that carry it, so molecular size is not what prevents it from traveling free. (Choice D) is incorrect: binding to a transport protein actually lengthens cortisol''s half-life by protecting it from degradation and clearance; a short half-life is characteristic of free catecholamines like epinephrine and is not the reason cortisol needs a carrier. This item exercises the skill of linking a hormone''s biosynthetic origin to its chemical character and the transport mechanism it requires.',
  difficulty = 'easy',
  cognitive_skill = 2,
  estimated_time_seconds = 70
WHERE id = '094f675e-046e-4afb-b60e-a83df7b678ab';
DELETE FROM question_distractor_metadata WHERE question_id = '094f675e-046e-4afb-b60e-a83df7b678ab';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('094f675e-046e-4afb-b60e-a83df7b678ab', 'A', 'misconception', 'attributes a net ionic charge to a neutral steroid'),
  ('094f675e-046e-4afb-b60e-a83df7b678ab', 'C', 'misconception', 'confuses need for a carrier with molecular size rather than polarity'),
  ('094f675e-046e-4afb-b60e-a83df7b678ab', 'D', 'reversed_relationship', 'reverses the effect of protein binding on half-life');

-- idx50 [Hypothalamus & Pituitary] leak_fix -> medium skill2 ans=B
UPDATE questions SET
  question_text = 'A researcher tracks the endocrine cascade triggered by weeks of unrelenting psychological stress. The hypothalamus releases a peptide into the hypophyseal portal system, which prompts the anterior pituitary to secrete a tropic hormone. This tropic hormone travels through the bloodstream to a pair of glands perched on top of the kidneys, stimulating them to release a steroid that raises and sustains blood glucose by driving the breakdown of glycogen, triglycerides, and muscle protein. Which anterior-pituitary hormone directly stimulates the steroid-producing glands in this pathway?',
  options = '[{"label": "A", "text": "Growth hormone"}, {"label": "B", "text": "Adrenocorticotropic hormone (ACTH)"}, {"label": "C", "text": "Thyroid-stimulating hormone"}, {"label": "D", "text": "Luteinizing hormone"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because the stress pathway described is the hypothalamic-pituitary-adrenal (HPA) axis: corticotropin-releasing hormone from the hypothalamus stimulates the anterior pituitary to secrete adrenocorticotropic hormone, which acts on the paired glands atop the kidneys to release the glucocorticoid that mobilizes fuel and sustains blood glucose during prolonged stress. (Choice B) is correct: Adrenocorticotropic hormone is the anterior-pituitary tropic hormone that stimulates the paired glands sitting on the kidneys to synthesize and release the stress steroid, which drives glycogenolysis, lipolysis, and protein catabolism to keep blood glucose elevated. (Choice A) is incorrect: Growth hormone does raise blood glucose and promote lipolysis, but it acts broadly and directly on the liver, muscle, and adipose tissue (partly via IGF-1) and does not use a tropic gland-on-the-kidney intermediary; it is not the signal in the described stress axis. (Choice C) is incorrect: Thyroid-stimulating hormone targets the thyroid gland in the neck to release thyroid hormones that set basal metabolic rate; it does not act on the glands atop the kidneys or drive the acute stress steroid response. (Choice D) is incorrect: Luteinizing hormone is a gonadotropin that acts on the ovaries and testes to regulate sex-steroid production and ovulation/spermatogenesis; it plays no role in the stress-driven glucose-mobilizing pathway. This question exercises the skill of tracing a multi-step endocrine axis from hypothalamic signal to end-organ product to identify the correct tropic hormone by function rather than by lexical cues.',
  difficulty = 'medium',
  cognitive_skill = 2,
  estimated_time_seconds = 90
WHERE id = '692ccbf6-2534-4293-b288-a0039d3ff37a';
DELETE FROM question_distractor_metadata WHERE question_id = '692ccbf6-2534-4293-b288-a0039d3ff37a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('692ccbf6-2534-4293-b288-a0039d3ff37a', 'A', 'adjacent_fact', 'Another anterior-pituitary hormone that also raises blood glucose but acts directly, not through a tropic adrenal intermediary'),
  ('692ccbf6-2534-4293-b288-a0039d3ff37a', 'C', 'adjacent_fact', 'Correct structural class (anterior-pituitary tropic hormone) but wrong target gland (thyroid, not adrenal)'),
  ('692ccbf6-2534-4293-b288-a0039d3ff37a', 'D', 'adjacent_fact', 'Anterior-pituitary tropic hormone directed at the gonads, unrelated to the stress-glucose axis');

-- idx94 [Gonads, Pineal & Other Tissues] leak_fix -> medium skill3 ans=B
UPDATE questions SET
  question_text = 'A patient with severe blood loss is resuscitated with an overly aggressive, rapid intravenous infusion of isotonic saline. Circulating blood volume and venous return rise well above normal. Assuming the patient''s kidneys respond appropriately to this expanded volume, which hormone is most directly responsible for the resulting change in renal handling of sodium and water, and what is that change?',
  options = '[{"label": "A", "text": "Aldosterone; it increases sodium and water reabsorption in the distal nephron"}, {"label": "B", "text": "Atrial natriuretic peptide; it increases sodium and water excretion in the urine"}, {"label": "C", "text": "Antidiuretic hormone; it increases water reabsorption in the collecting ducts"}, {"label": "D", "text": "Angiotensin II; it increases sodium and water reabsorption in the proximal tubule"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is B because an expansion of blood volume must be corrected by INCREASING the excretion of sodium and water, and atrial natriuretic peptide (ANP) is the only listed hormone that promotes natriuresis (sodium loss) and diuresis (water loss) rather than retention. (Choice B) is correct: When venous return and blood volume rise, the atrial myocardium releases ANP; ANP acts on the kidney to increase glomerular filtration and reduce sodium reabsorption, so more sodium and its accompanying water are excreted, lowering blood volume back toward normal — the physiologically appropriate correction for volume overload. (Choice A) is incorrect: Aldosterone from the adrenal cortex increases sodium (and thus water) REABSORPTION, which would worsen volume overload; it is secreted in response to low volume/low sodium, the opposite of this scenario. (Choice C) is incorrect: Antidiuretic hormone increases water REABSORPTION in the collecting ducts and is released when volume/osmolarity signals call for water conservation; retaining water is the wrong direction for a fluid-overloaded patient. (Choice D) is incorrect: Angiotensin II drives sodium and water REABSORPTION (directly in the proximal tubule and by stimulating aldosterone) and is part of the retention system activated by LOW volume, not high volume. This question exercises the skill of predicting the direction of a homeostatic renal response (excretion vs. retention) and then matching it to the correct hormone rather than relying on the source organ.',
  difficulty = 'medium',
  cognitive_skill = 3,
  estimated_time_seconds = 90
WHERE id = '15d92e5c-0d8f-4711-82d3-4502a666b1e2';
DELETE FROM question_distractor_metadata WHERE question_id = '15d92e5c-0d8f-4711-82d3-4502a666b1e2';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('15d92e5c-0d8f-4711-82d3-4502a666b1e2', 'A', 'reversed_relationship', 'retention hormone offered where excretion is required; aldosterone reabsorbs sodium/water, worsening overload'),
  ('15d92e5c-0d8f-4711-82d3-4502a666b1e2', 'C', 'reversed_relationship', 'ADH promotes water reabsorption (conservation), the wrong direction for a volume-overloaded patient'),
  ('15d92e5c-0d8f-4711-82d3-4502a666b1e2', 'D', 'reversed_relationship', 'angiotensin II drives proximal-tubule sodium/water reabsorption as part of the low-volume retention system, opposite of the needed response');

-- idx95 [Gonads, Pineal & Other Tissues] ambiguous_fix -> hard skill3 ans=D
UPDATE questions SET
  question_text = 'A cardiac atrial peptide released during atrial stretch is known to act directly on the juxtaglomerular cells of the kidney, blunting their secretory activity independent of any change in renal perfusion pressure. In a study, healthy volunteers receive an infusion of this peptide at a dose sufficient to produce this direct renal action. Following the peptide''s downstream effects along the renin-angiotensin pathway to its terminal hormonal target, which change in adrenal cortical hormone secretion would investigators most likely record?',
  options = '[{"label": "A", "text": "Increased aldosterone secretion, because the fall in circulating volume drives compensatory angiotensin II formation"}, {"label": "B", "text": "Increased cortisol secretion, because the peptide stimulates the hypothalamic-pituitary-adrenal axis"}, {"label": "C", "text": "Unchanged aldosterone secretion, because rising plasma potassium offsets the loss of angiotensin II signaling"}, {"label": "D", "text": "Decreased aldosterone secretion, because reduced angiotensin II generation lowers stimulation of the zona glomerulosa"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the atrial peptide directly suppresses renin secretion from the juxtaglomerular cells, so less renin generates less angiotensin II, and because angiotensin II is the principal stimulus for aldosterone release from the zona glomerulosa, aldosterone secretion falls. (Choice D) is correct: with renin secretion directly inhibited, the renin-angiotensin cascade is throttled at its first enzymatic step; plasma angiotensin II declines, removing the main trophic signal to the adrenal zona glomerulosa, so mineralocorticoid (aldosterone) output decreases. (Choice A) is incorrect: it applies the reflex that operates when pressure/volume truly falls without the peptide, in which baroreceptor- and volume-driven renin release would raise angiotensin II and aldosterone; here the peptide''s direct suppression of renin overrides that reflex, so angiotensin II and aldosterone go down, not up. (Choice B) is incorrect: the atrial natriuretic peptide axis acts on the RAAS and the zona glomerulosa, not on the hypothalamic-pituitary-adrenal axis that governs cortisol from the zona fasciculata; cortisol is not the mineralocorticoid target of this pathway. (Choice C) is incorrect: aldosterone secretion is stimulated, not inhibited, by rising extracellular potassium, so a hyperkalemic change would add to zona glomerulosa drive rather than offset the loss of angiotensin II, and the peptide''s natriuretic action does not produce a compensatory potassium rise that holds aldosterone constant. This item exercises causal tracing of a multi-step endocrine signaling cascade from an upstream enzymatic trigger to its terminal hormonal output.',
  difficulty = 'hard',
  cognitive_skill = 3,
  estimated_time_seconds = 100
WHERE id = '4eaa6d02-119a-4fa4-af2e-1cdd686a13c5';
DELETE FROM question_distractor_metadata WHERE question_id = '4eaa6d02-119a-4fa4-af2e-1cdd686a13c5';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4eaa6d02-119a-4fa4-af2e-1cdd686a13c5', 'A', 'misconception', 'falling pressure/volume must raise aldosterone via compensatory angiotensin II'),
  ('4eaa6d02-119a-4fa4-af2e-1cdd686a13c5', 'B', 'adjacent_fact', 'wrong adrenal product and wrong axis (cortisol/HPA instead of aldosterone/RAAS)'),
  ('4eaa6d02-119a-4fa4-af2e-1cdd686a13c5', 'C', 'reversed_relationship', 'treats potassium as an inhibitory offset when it is actually a stimulator of aldosterone');

-- idx36 [Feedback & Neuroendocrine Integration] differentiate -> hard skill3 ans=B
UPDATE questions SET
  question_text = 'An endocrinologist evaluates a fatigued patient whose morning plasma cortisol is well below the normal range. The clinician needs to determine whether the problem lies in the adrenal cortex itself or in the pituitary gland that normally drives it. From a single additional blood test, which measurement and interpretation would allow the clinician to localize the defect to the adrenal cortex rather than the pituitary?',
  options = '[{"label": "A", "text": "Measure plasma cortisol a second time; a value that remains low confirms the adrenal cortex is the site of failure."}, {"label": "B", "text": "Measure plasma ACTH; a markedly elevated ACTH accompanying the low cortisol points to failure of the adrenal cortex itself."}, {"label": "C", "text": "Measure plasma ACTH; a suppressed, low ACTH accompanying the low cortisol points to failure of the adrenal cortex itself."}, {"label": "D", "text": "Measure hypothalamic CRH in the peripheral blood; a low CRH accompanying the low cortisol points to failure of the adrenal cortex itself."}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Mechanisms of Hormone Action.'' The answer is B because cortisol exerts negative feedback on the anterior pituitary''s secretion of ACTH; when the adrenal cortex itself fails (primary insufficiency), cortisol is low and can no longer suppress the pituitary, so ACTH rises markedly, whereas if the pituitary is the failing organ (secondary insufficiency) it cannot make ACTH, so ACTH is inappropriately low. Measuring ACTH therefore separates the two: a high ACTH with low cortisol localizes the defect to the adrenal gland. (Choice B) is correct: a high plasma ACTH with low cortisol reflects intact pituitary drive that has lost its cortisol-mediated negative feedback, meaning the adrenal cortex cannot respond — the hallmark of primary adrenal failure. (Choice A) is incorrect: repeating the cortisol measurement confirms only that cortisol is low; it gives no information about which organ in the axis is responsible, because low cortisol occurs in both primary and secondary insufficiency. (Choice C) is incorrect: a low, suppressed ACTH with low cortisol indicates the pituitary is not providing tropic drive, which localizes the defect to the pituitary (secondary), not to the adrenal cortex. (Choice D) is incorrect: CRH is released into the hypophyseal portal circulation and is not reliably measurable in peripheral blood, and even conceptually a low CRH would implicate the hypothalamus/pituitary axis rather than the adrenal gland. This item exercises the skill of using a tropic hormone level and the direction of negative feedback to localize a lesion within an endocrine axis.',
  difficulty = 'hard',
  cognitive_skill = 3,
  estimated_time_seconds = 100
WHERE id = 'bff43e8c-228f-4965-89ca-065896048515';
DELETE FROM question_distractor_metadata WHERE question_id = 'bff43e8c-228f-4965-89ca-065896048515';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('bff43e8c-228f-4965-89ca-065896048515', 'A', 'partial_truth', 're-measuring the downstream hormone that is already known to be low, which cannot localize the lesion'),
  ('bff43e8c-228f-4965-89ca-065896048515', 'C', 'reversed_relationship', 'assigning the low-ACTH (secondary/pituitary) pattern to primary adrenal failure — feedback direction reversed'),
  ('bff43e8c-228f-4965-89ca-065896048515', 'D', 'misconception', 'treating portal-restricted hypothalamic CRH as a measurable peripheral marker for adrenal localization');

-- idx42 [Feedback & Neuroendocrine Integration] differentiate -> medium skill3 ans=B
UPDATE questions SET
  question_text = 'A competitive athlete injects high supraphysiologic doses of an anabolic-androgenic steroid (a synthetic analog of testosterone) for several months while his reproductive regulatory axis remains structurally intact. Compared with baseline, which combination best describes the change in the anterior pituitary gonadotropins and in the testes over this period?',
  options = '[{"label": "A", "text": "LH and FSH secretion increases, and the testes enlarge as spermatogenesis is stimulated"}, {"label": "B", "text": "LH and FSH secretion decreases, and the testes atrophy as endogenous testosterone output falls"}, {"label": "C", "text": "LH and FSH secretion increases, but the testes atrophy despite the elevated drive"}, {"label": "D", "text": "LH and FSH secretion decreases, yet the testes enlarge as sperm production rises"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Mechanisms of Hormone Action.'' The answer is B because the synthetic androgen is sensed by the hypothalamic-pituitary-gonadal axis as an elevated circulating testosterone signal, so negative feedback suppresses GnRH and therefore pituitary LH and FSH release; with LH withdrawn, the Leydig cells lose their trophic drive and endogenous testosterone production plummets, and with FSH low and intratesticular testosterone collapsed, spermatogenesis fails and the testes shrink. (Choice B) is correct: high exogenous androgen mimics the gonad''s own end-product hormone, driving negative feedback that lowers LH and FSH; the resulting loss of trophic stimulation causes Leydig-cell testosterone output and Sertoli-cell-supported spermatogenesis to decline, producing testicular atrophy. (Choice A) is incorrect: it reverses the feedback direction, claiming gonadotropins rise; an elevated androgen signal inhibits rather than stimulates GnRH/LH/FSH, and without trophic drive the testes cannot enlarge. (Choice C) is incorrect: it correctly predicts atrophy but wrongly claims LH and FSH increase; the atrophy occurs precisely because gonadotropins are suppressed, not because they rise. (Choice D) is incorrect: it correctly identifies falling gonadotropins but then contradicts itself by claiming the testes enlarge and sperm production rises; low LH/FSH and low intratesticular testosterone impair spermatogenesis and shrink the gonads. This item exercises the skill of predicting the downstream consequences of negative feedback in a hormonal axis when the end-product signal is supplied exogenously.',
  difficulty = 'medium',
  cognitive_skill = 3,
  estimated_time_seconds = 90
WHERE id = '01a865c6-6ca1-40e3-af7c-08b58f294f91';
DELETE FROM question_distractor_metadata WHERE question_id = '01a865c6-6ca1-40e3-af7c-08b58f294f91';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('01a865c6-6ca1-40e3-af7c-08b58f294f91', 'A', 'reversed_relationship', 'Treats exogenous hormone as an additional stimulatory drive, reversing the sign of feedback so gonadotropins and the end organ both rise'),
  ('01a865c6-6ca1-40e3-af7c-08b58f294f91', 'C', 'partial_truth', 'Correctly predicts testicular atrophy but pairs it with rising gonadotropins, missing that the atrophy is caused by suppressed LH/FSH'),
  ('01a865c6-6ca1-40e3-af7c-08b58f294f91', 'D', 'partial_truth', 'Correctly predicts falling gonadotropins but pairs it with enlarged testes and increased sperm, ignoring the loss of trophic and intratesticular testosterone support');

-- idx9 [Receptors & Signal Transduction] differentiate -> medium skill3 ans=B
UPDATE questions SET
  question_text = 'A cell line is cultured for several days in medium containing a fixed, persistently high concentration of a peptide hormone. Investigators confirm that the hormone concentration in the medium does not fall during the experiment, yet the magnitude of the intracellular signaling response triggered by the hormone declines steadily over this period. Which of the following best explains the cells'' progressively diminished response?',
  options = '[{"label": "A", "text": "The cells synthesize and display additional receptors for the hormone in response to the sustained exposure"}, {"label": "B", "text": "The cells reduce the number of surface receptors available for the hormone by internalizing and degrading them"}, {"label": "C", "text": "Enzymes in the medium degrade the hormone faster, lowering the effective dose reaching the cells"}, {"label": "D", "text": "The intracellular second-messenger cascade is amplified with each successive exposure to the hormone"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Mechanisms of Hormone Action.'' The answer is B because chronic exposure to a persistently high hormone concentration triggers downregulation, in which target cells internalize and degrade a portion of their receptors, lowering receptor number so the same hormone level produces a weaker response. (Choice B) is correct: Downregulation is the standard adaptive mechanism by which a cell becomes less sensitive to a hormone that is chronically elevated; by reducing the number of available receptors (via receptor-mediated internalization and degradation), the cell blunts its response even though hormone concentration remains high. (Choice A) is incorrect: Making more receptors is upregulation, which increases sensitivity and typically occurs when a hormone is chronically low, not high; it would raise, not lower, the response. (Choice C) is incorrect: The stem explicitly states the hormone concentration in the medium does not fall, so accelerated hormone degradation is ruled out as the cause of the declining response. (Choice D) is incorrect: Amplification of the second-messenger cascade would increase the signaling output per hormone molecule, producing a larger response, which is the opposite of the observed decline. This item exercises the skill of inferring a cellular regulatory mechanism from a functional (dose-response) observation while excluding alternatives incompatible with the stated conditions.',
  difficulty = 'medium',
  cognitive_skill = 3,
  estimated_time_seconds = 90
WHERE id = 'fa613fcc-9c40-4182-b377-f8fafc6d4018';
DELETE FROM question_distractor_metadata WHERE question_id = 'fa613fcc-9c40-4182-b377-f8fafc6d4018';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('fa613fcc-9c40-4182-b377-f8fafc6d4018', 'A', 'reversed_relationship', 'Upregulation confused with downregulation (raising vs lowering receptor number)'),
  ('fa613fcc-9c40-4182-b377-f8fafc6d4018', 'C', 'misconception', 'Attributing reduced response to falling ligand dose despite stem stating concentration is stable'),
  ('fa613fcc-9c40-4182-b377-f8fafc6d4018', 'D', 'reversed_relationship', 'Signal amplification would increase, not decrease, the response');

-- idx64 [Thyroid & Parathyroid] differentiate -> medium skill2 ans=D
UPDATE questions SET
  question_text = 'A patient with chronic dietary calcium deficiency has a chronically low serum calcium concentration, and this has driven a sustained elevation in the patient''s parathyroid hormone (PTH) level. Circulating PTH acts on the skeleton to help return the blood calcium concentration toward normal. Which cellular event in bone accounts for PTH''s ability to raise blood calcium?',
  options = '[{"label": "A", "text": "PTH stimulates osteoblasts to deposit calcium phosphate into new bone matrix, drawing calcium out of the blood"}, {"label": "B", "text": "PTH directly mineralizes unmineralized osteoid, incorporating circulating calcium into the bone matrix"}, {"label": "C", "text": "PTH suppresses overall bone turnover, sparing calcium within the matrix so that none is exchanged with the blood"}, {"label": "D", "text": "PTH stimulates osteoclasts to resorb mineralized bone matrix, releasing stored calcium into the blood"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because parathyroid hormone raises blood calcium in part by promoting osteoclast activity, and osteoclasts break down (resorb) the mineralized bone matrix, liberating the calcium stored there into the circulation. (Choice D) is correct: PTH increases the number and activity of osteoclasts, the bone-resorbing cells; as they dissolve the mineralized matrix, calcium and phosphate are released from bone into the blood, which raises serum calcium toward normal. (Choice A) is incorrect: this describes the opposite (reversed) action—osteoblasts deposit calcium into new matrix, which would lower blood calcium, whereas PTH''s net skeletal effect is to mobilize calcium out of bone. (Choice B) is incorrect: PTH does not act by directly mineralizing osteoid; mineralization deposits calcium into bone and would lower, not raise, serum calcium, and PTH''s calcium-raising bone effect is resorptive rather than mineralizing. (Choice C) is incorrect: PTH increases bone remodeling toward net resorption rather than suppressing turnover; suppression of resorption to conserve matrix calcium describes calcitonin''s action, which lowers blood calcium and is functionally opposite to PTH. This question exercises mechanistic reasoning about how a hormone''s effect on a specific cell type (osteoclasts) produces a whole-body change in calcium homeostasis.',
  difficulty = 'medium',
  cognitive_skill = 2,
  estimated_time_seconds = 90
WHERE id = '512684d6-245e-4da3-826c-02edbe9d82ed';
DELETE FROM question_distractor_metadata WHERE question_id = '512684d6-245e-4da3-826c-02edbe9d82ed';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('512684d6-245e-4da3-826c-02edbe9d82ed', 'A', 'reversed_relationship', 'Osteoblast deposition (bone formation) offered in place of osteoclast resorption — reverses the direction of calcium flux and the effector cell type'),
  ('512684d6-245e-4da3-826c-02edbe9d82ed', 'B', 'process_step_confusion', 'Confuses mineralization (calcium into bone) with PTH''s resorptive action, and misattributes a direct mineralizing role to PTH'),
  ('512684d6-245e-4da3-826c-02edbe9d82ed', 'C', 'misconception', 'Ascribes calcitonin-like suppression of bone turnover to PTH — functionally opposite hormone effect');

-- idx29 [Hormone Transport, Specificity & Kinetics] differentiate -> medium skill3 ans=D
UPDATE questions SET
  question_text = 'During the fight-or-flight response, a surge of epinephrine circulates and reaches the smooth muscle of the skin''s blood vessels and the smooth muscle of the bronchioles at comparable concentrations. In the cutaneous vessels the muscle contracts (vasoconstriction), whereas in the bronchioles the muscle relaxes (bronchodilation). Which of the following best explains how one hormone produces these opposite effects in the two tissues?',
  options = '[{"label": "A", "text": "Epinephrine is enzymatically converted to a different active molecule as it travels from the skin vessels to the bronchioles"}, {"label": "B", "text": "The bronchiolar tissue is exposed to a far higher local concentration of epinephrine than the cutaneous tissue"}, {"label": "C", "text": "Only the cutaneous smooth muscle possesses receptors for epinephrine, while the bronchioles respond nonspecifically"}, {"label": "D", "text": "The two tissues express different adrenergic receptor subtypes that are coupled to different intracellular signaling pathways"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Mechanisms of Hormone Action.'' The answer is D because a single hormone can bind more than one class of receptor, and the physiological effect is determined by which receptor subtype a target cell expresses and the intracellular pathway that subtype activates. Cutaneous vascular smooth muscle is dominated by alpha-adrenergic receptors whose signaling raises intracellular calcium and drives contraction (vasoconstriction), whereas bronchiolar smooth muscle is dominated by beta-2-adrenergic receptors that couple through Gs to cAMP and drive relaxation (bronchodilation). Same hormone, equal exposure, opposite outcome — determined by receptor-subtype and pathway diversity, not by the hormone itself. (Choice D) is correct: opposite responses to the same equally-delivered hormone are explained by the two tissues expressing distinct adrenergic receptor subtypes linked to distinct downstream signaling cascades. (Choice A) is incorrect: epinephrine is not chemically transformed en route into a second active messenger; the identical molecule reaches both tissues, so a "conversion" cannot account for the divergent responses. (Choice B) is incorrect: the stem states both tissues are exposed at comparable concentrations, and in any case a difference in dose would scale the magnitude of a response, not reverse its direction from contraction to relaxation. (Choice C) is incorrect: both tissues clearly bind and respond to epinephrine (both change their contractile state), so this is not a case of one tissue simply lacking any receptor, and smooth muscle does not respond to a hormone "nonspecifically" without receptors. This question exercises the skill of distinguishing receptor-subtype/pathway diversity from mere receptor presence as the basis of tissue-specific hormone action.',
  difficulty = 'medium',
  cognitive_skill = 3,
  estimated_time_seconds = 90
WHERE id = '4b0b5dd0-63f3-4562-a9fb-b4de5f1cf586';
DELETE FROM question_distractor_metadata WHERE question_id = '4b0b5dd0-63f3-4562-a9fb-b4de5f1cf586';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4b0b5dd0-63f3-4562-a9fb-b4de5f1cf586', 'A', 'misconception', 'hormone chemically modified en route changes its action'),
  ('4b0b5dd0-63f3-4562-a9fb-b4de5f1cf586', 'B', 'adjacent_fact', 'concentration/dose difference drives divergent effect'),
  ('4b0b5dd0-63f3-4562-a9fb-b4de5f1cf586', 'C', 'misconception', 'receptor presence vs absence (the twin''s concept) as explanation');

-- idx58 [Thyroid & Parathyroid] differentiate -> easy skill2 ans=D
UPDATE questions SET
  question_text = 'A researcher notes that the thyroid follicular cells of a healthy adult release predominantly a hormone carrying four iodine atoms. However, this circulating hormone is only weakly active, and inside peripheral tissues such as the liver and kidney an enzyme removes a single iodine atom to generate the form that binds nuclear receptors most strongly and drives cellular metabolism. Which hormone is produced by this enzymatic conversion in the target tissues?',
  options = '[{"label": "A", "text": "Thyroxine"}, {"label": "B", "text": "Thyroid-stimulating hormone"}, {"label": "C", "text": "Calcitonin"}, {"label": "D", "text": "Triiodothyronine"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the thyroid secretes mostly thyroxine (T4), which carries four iodine atoms and is relatively weak; peripheral deiodinase enzymes remove one iodine atom to form triiodothyronine (T3), the more metabolically active hormone that binds thyroid hormone receptors with far greater affinity. (Choice D) is correct: T3 (triiodothyronine) has three iodine atoms and is the product of removing one iodine from T4; it is several times more potent than T4 and is the principal form acting on target cells. (Choice A) is incorrect: Thyroxine (T4) is the four-iodine hormone actually secreted and described in the stem as weakly active — it is the substrate for the conversion, not its product. (Choice B) is incorrect: Thyroid-stimulating hormone is a pituitary glycoprotein that stimulates the thyroid to make and release thyroid hormones; it is not an iodinated hormone and is not made by deiodination in peripheral tissues. (Choice C) is incorrect: Calcitonin is a peptide hormone from the thyroid''s parafollicular (C) cells that lowers blood calcium; it contains no iodine and is unrelated to metabolic rate or deiodinase activity. This item exercises the skill of tracing a hormone''s peripheral activation pathway rather than matching vocabulary in the stem.',
  difficulty = 'easy',
  cognitive_skill = 2,
  estimated_time_seconds = 70
WHERE id = '1180cc2b-7108-4b51-9a34-ab2c6d7bff25';
DELETE FROM question_distractor_metadata WHERE question_id = '1180cc2b-7108-4b51-9a34-ab2c6d7bff25';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('1180cc2b-7108-4b51-9a34-ab2c6d7bff25', 'A', 'partial_truth', 'Substrate mistaken for product (names the secreted T4 that the stem describes rather than its more active conversion product)'),
  ('1180cc2b-7108-4b51-9a34-ab2c6d7bff25', 'B', 'adjacent_fact', 'Wrong axis level (pituitary tropic hormone that regulates the thyroid, not an iodinated hormone made by peripheral deiodination)'),
  ('1180cc2b-7108-4b51-9a34-ab2c6d7bff25', 'C', 'adjacent_fact', 'Same-gland, wrong-function hormone (thyroid C-cell calcium hormone, non-iodinated and unrelated to metabolic activation)');

-- idx92 [Gonads, Pineal & Other Tissues] differentiate -> medium skill2 ans=D
UPDATE questions SET
  question_text = 'A climber who has lived for several weeks at 4,500 m develops a rising erythrocyte count. Interstitial cells of her kidneys, sensing the persistently low oxygen tension, release a peptide hormone into the circulation. This hormone must reach a specific target tissue to produce the increase in oxygen-carrying capacity. On which tissue does the hormone act, and what does it do there?',
  options = '[{"label": "A", "text": "It acts on the spleen, slowing the removal of aging erythrocytes from circulation"}, {"label": "B", "text": "It acts on the liver, stimulating hepatocytes to synthesize additional hemoglobin"}, {"label": "C", "text": "It acts on the kidney tubules, increasing the reabsorption of filtered iron"}, {"label": "D", "text": "It acts on the red bone marrow, driving progenitor cells to mature into additional erythrocytes"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a Biology question that falls under the content category ''Endocrine System: Hormones and Their Sources.'' The answer is D because the hormone described is erythropoietin (EPO), and its principal action is on the red bone marrow, where it stimulates erythroid progenitor cells to proliferate and differentiate into mature erythrocytes, thereby raising the blood''s oxygen-carrying capacity. (Choice D) is correct: EPO travels from the kidney to the red (hematopoietic) bone marrow, where it binds receptors on committed erythroid progenitor cells and promotes their survival, proliferation, and maturation into red blood cells; more erythrocytes means more hemoglobin available to carry oxygen, which is the adaptive response to chronic hypoxia. (Choice A) is incorrect: the spleen is a site of erythrocyte destruction and recycling, but EPO does not act there to prolong red-cell lifespan; the adaptive rise in red-cell number is driven by increased production in marrow, not by slowed destruction in the spleen. (Choice B) is incorrect: hemoglobin is synthesized inside developing erythrocytes in the marrow, not manufactured by hepatocytes and exported; the liver is not the target of EPO, and EPO''s effect is to increase erythrocyte number rather than to have another organ mass-produce free hemoglobin. (Choice C) is incorrect: although the kidney is the source of EPO, EPO is not a hormone that acts back on the renal tubules, and iron reabsorption there is not its mechanism; confusing the organ that secretes the hormone with the organ it targets is the trap. This item exercises the skill of distinguishing an endocrine hormone''s target tissue and action from its site of secretion.',
  difficulty = 'medium',
  cognitive_skill = 2,
  estimated_time_seconds = 75
WHERE id = '8877fcaf-e89a-43b4-bc04-4a5b5e1b643b';
DELETE FROM question_distractor_metadata WHERE question_id = '8877fcaf-e89a-43b4-bc04-4a5b5e1b643b';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8877fcaf-e89a-43b4-bc04-4a5b5e1b643b', 'A', 'adjacent_fact', 'spleen as site of erythrocyte destruction confused with an EPO target'),
  ('8877fcaf-e89a-43b4-bc04-4a5b5e1b643b', 'B', 'misconception', 'liver/hepatocytes imagined to mass-produce free hemoglobin instead of marrow making red cells'),
  ('8877fcaf-e89a-43b4-bc04-4a5b5e1b643b', 'C', 'reversed_relationship', 'source organ (kidney) mistaken for the target organ of its own hormone');

COMMIT;
