-- GenChem Ch11 (Oxidation-Reduction Reactions) — Batch 4 of 4: Reaction Types & Classification + Redox Titrations
-- 10 questions, all confidence >=4 (verified vs OpenStax Chemistry: Atoms First 2e Ch.7; every oxidation number, electron count, and balancing coefficient independently re-computed).
-- Cross-batch + cross-chapter deduped (esp. vs Ch4 Types-of-Reactions / Balancing-redox / Ions-Electrolytes); final dedup audit PASS (0 genuine conflicts) after a systematic recall-answer-leak sweep.
-- AAMC foundations in this batch: 4E, 5A (per-row foundation/content_category below). Answer key balanced A/B/C/D = 18/18/18/18 across the full 72-question chapter.
-- Re-runnable: subtopic-scoped DELETE. Run the four batches in any order in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Oxidation-Reduction Reactions' AND subtopic IN ('Reaction Types & Classification', 'Redox Titrations');

-- Q1 [Reaction Types & Classification · easy · Skill 3 · 4E Stoichiometry (GC) · ans C] (g63)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Reaction Types & Classification',
    $qt63$A chemistry student carries out the single-displacement reaction \(\text{Fe(s)} + \text{CuCl}_2\text{(aq)} \rightarrow \text{FeCl}_2\text{(aq)} + \text{Cu(s)}\) and is asked to explain why this metal-replacement reaction must also be classified as an oxidation-reduction (redox) reaction. Which statement best justifies that classification?$qt63$,
    $op63$[{"label":"A","text":"Both metals keep the same oxidation state throughout, and it is the rearrangement of the \\(\\text{Cl}^-\\) partners alone that defines the reaction as redox."},{"label":"B","text":"The chloride ions are transferred intact from copper to iron, and this transfer of the \\(\\text{Cl}^-\\) ions between the two metals is what constitutes the oxidation and reduction."},{"label":"C","text":"The free element \\(\\text{Fe}\\) enters with an oxidation state of 0 and leaves bonded in \\(\\text{FeCl}_2\\) with an oxidation state of \\(+2\\), so its oxidation state necessarily changes and electrons are transferred."},{"label":"D","text":"The dissolved \\(\\text{Cu}^{2+}\\) is oxidized to \\(\\text{Cu(s)}\\) while the free \\(\\text{Fe}\\) is reduced to \\(\\text{Fe}^{2+}\\), and this pairing of oxidation with reduction makes it redox."}]$op63$::jsonb,
    'C',
    $ex63$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because a single-displacement (metal-replacement) reaction always involves a free element, and a free element by definition has an oxidation state of 0; when that element becomes part of a compound its oxidation state must change, which is the very definition of a redox process. Here the free iron begins as \(\text{Fe}\) with oxidation state 0 and ends bonded in \(\text{FeCl}_2\) as \(\text{Fe}^{2+}\) (oxidation state \(+2\)), so iron is oxidized, losing 2 electrons. Those 2 electrons are gained by copper, whose oxidation state falls from \(+2\) in \(\text{CuCl}_2\) to 0 in the free metal \(\text{Cu(s)}\), so copper is reduced. Chlorine is the spectator: it is \(-1\) in \(\text{CuCl}_2\) and remains \(-1\) in \(\text{FeCl}_2\), so its oxidation state does not change and it is neither oxidized nor reduced. Because at least one element (the free \(\text{Fe}\)) changes oxidation state from 0 to a positive value, the reaction must be redox, which is why single-displacement reactions are necessarily oxidation-reduction reactions. (Choice A) This is factually wrong on the central point: the metals do not keep the same oxidation state, since iron goes from 0 to \(+2\) and copper from \(+2\) to 0, and it is precisely these changes (not any rearrangement of the unchanged \(\text{Cl}^-\)) that make the reaction redox. (Choice B) This treats the carrying-over of the intact \(\text{Cl}^-\) ions as the oxidation and reduction, but the chloride ions keep their \(-1\) oxidation state on both sides and are spectators; a redox event requires a change in oxidation state, which the chloride does not undergo. (Choice D) This correctly recognizes that an oxidation is paired with a reduction but reverses which species undergoes which: the free \(\text{Fe}\) (0) loses electrons and is oxidized to \(\text{Fe}^{2+}\), while \(\text{Cu}^{2+}\) gains electrons and is reduced to \(\text{Cu(s)}\), the opposite of what this choice states. Skill 3$ex63$,
    'easy', '4E', $cc63$Stoichiometry (GC)$cc63$, 'general-chemistry', 3, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a63A$denies-any-oxidation-state-change-occurs$a63A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a63B$spectator-ion-mistaken-for-redox$a63B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a63D$oxidation-and-reduction-assignments-swapped$a63D$ FROM q;

-- Q2 [Reaction Types & Classification · easy · Skill 3 · 4E Stoichiometry (GC) · ans D] (g64)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Reaction Types & Classification',
    $qt64$A student mixes aqueous barium chloride with aqueous sodium sulfate, and a white solid forms according to the balanced equation \(\text{BaCl}_2(aq) + \text{Na}_2\text{SO}_4(aq) \rightarrow \text{BaSO}_4(s) + 2\,\text{NaCl}(aq)\). Based on how the oxidation states of the elements change (or do not change) from reactants to products, how is this reaction best classified?$qt64$,
    $op64$[{"label":"A","text":"A single-displacement redox reaction, because barium displaces sodium and is thereby reduced from \\(+2\\) to \\(0\\)."},{"label":"B","text":"An oxidation-reduction reaction, because barium is oxidized from \\(+2\\) to \\(+6\\) while sulfur is reduced from \\(+6\\) to \\(+2\\)."},{"label":"C","text":"An oxidation-reduction reaction, because chloride ions are oxidized from \\(-1\\) to \\(0\\) when they pair with sodium."},{"label":"D","text":"A double-displacement (precipitation) reaction that is not a redox reaction, because every element keeps the same oxidation state across the arrow."}]$op64$::jsonb,
    'D',
    $ex64$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because a redox reaction requires at least one element to change oxidation state (electron transfer), and here none does. Assigning oxidation numbers on both sides: barium is \(+2\) in \(\text{BaCl}_2\) and \(+2\) in \(\text{BaSO}_4\); chlorine is \(-1\) in \(\text{BaCl}_2\) and \(-1\) in \(\text{NaCl}\); sodium is \(+1\) in \(\text{Na}_2\text{SO}_4\) and \(+1\) in \(\text{NaCl}\); within the intact sulfate ion \(\text{SO}_4^{2-}\), sulfur is \(+6\) and oxygen is \(-2\) on both sides. Because every element retains its oxidation state, no electrons are transferred. Instead, the cations and anions simply swap partners and \(\text{BaSO}_4\) precipitates out, which is the definition of a double-displacement (precipitation) reaction; the \(\text{Na}^+\) and \(\text{Cl}^-\) are spectator ions. (Choice A) This misidentifies the reaction type and the chemistry: ions exchange partners (double displacement), not a single-displacement of one element by another, and barium remains \(+2\) throughout rather than being reduced to neutral metal. (Choice B) This reverses and fabricates oxidation-state changes: barium does not rise to \(+6\) (that is sulfur's value, which itself does not change), and sulfur is not reduced to \(+2\); the sulfate ion stays intact. (Choice C) Chloride is not oxidized; it remains \(-1\) in both \(\text{BaCl}_2\) and \(\text{NaCl}\) and never reaches the elemental \(0\) state, so no electron transfer occurs. Skill 3$ex64$,
    'easy', '4E', $cc64$Stoichiometry (GC)$cc64$, 'general-chemistry', 3, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a64A$Confuses double-displacement with single-displacement and claims metal reduction$a64A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a64B$Invents oxidation/reduction by swapping S and Ba oxidation numbers$a64B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a64C$Thinks pairing chloride with a new cation oxidizes it to elemental state$a64C$ FROM q;

-- Q3 [Reaction Types & Classification · medium · Skill 4 · 4E Stoichiometry (GC) · ans A] (g65)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Reaction Types & Classification',
    $qt65$When calcium oxide reacts with carbon dioxide, it forms calcium carbonate according to \(\text{CaO}(s) + \text{CO}_2(g) \rightarrow \text{CaCO}_3(s)\). Which of the following best classifies this reaction?$qt65$,
    $op65$[{"label":"A","text":"A combination reaction that is not an oxidation-reduction reaction, because no element changes oxidation number"},{"label":"B","text":"A combination reaction that is also an oxidation-reduction reaction, because the calcium is oxidized from \\(+2\\) to a higher state"},{"label":"C","text":"A decomposition reaction that is not an oxidation-reduction reaction, because a single compound breaks into two products"},{"label":"D","text":"A combination reaction that is also an oxidation-reduction reaction, because the carbon is reduced from \\(+4\\) to \\(+2\\)"}]$op65$::jsonb,
    'A',
    $ex65$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because two reactants combine into a single product, \(\text{CaCO}_3\), which makes it a combination (synthesis) reaction; to test whether it is also redox, assign oxidation numbers to every element. In \(\text{CaO}\), calcium is \(+2\) and oxygen is \(-2\). In \(\text{CO}_2\), oxygen is \(-2\) (two oxygens give \(-4\)), so carbon must be \(+4\). In the product \(\text{CaCO}_3\), oxygen is \(-2\) (three oxygens give \(-6\)) and calcium is \(+2\), so carbon must be \(+4\) to make the neutral formula balance: \((+2) + (+4) + 3(-2) = 0\). Comparing reactants to product: calcium stays \(+2 \rightarrow +2\), carbon stays \(+4 \rightarrow +4\), and oxygen stays \(-2 \rightarrow -2\). Because no element's oxidation number changes, no electrons are transferred, so the reaction is a combination reaction that is NOT an oxidation-reduction reaction. (Choice B) Calcium does not change oxidation state; it is \(+2\) in \(\text{CaO}\) and \(+2\) in \(\text{CaCO}_3\), so it is neither oxidized nor reduced, and \(+2\) is already calcium's maximum (group 2) state. (Choice C) This misreads the direction of the reaction; two separate reactants combine into one product, which is the defining pattern of a combination reaction, not a decomposition in which one compound splits into two or more products. (Choice D) Carbon remains \(+4\) in both \(\text{CO}_2\) and \(\text{CaCO}_3\) and is not reduced; this choice invents an oxidation-number change that does not occur. Skill 4$ex65$,
    'medium', '4E', $cc65$Stoichiometry (GC)$cc65$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a65B$assumes any combination reaction must be redox and invents calcium oxidation$a65B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a65C$reverses combination as decomposition by misreading reactant/product direction$a65C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a65D$fabricates a carbon oxidation-number change during oxidation-number bookkeeping$a65D$ FROM q;

-- Q4 [Reaction Types & Classification · medium · Skill 4 · 4E Stoichiometry (GC) · ans B] (g66)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Reaction Types & Classification',
    $qt66$Solid ammonium nitrate decomposes on heating according to \(\text{NH}_4\text{NO}_3(s) \rightarrow \text{N}_2\text{O}(g) + 2\,\text{H}_2\text{O}(g)\). A student claims this cannot be an oxidation-reduction reaction because it is a decomposition and "only one substance is involved." Assigning oxidation numbers to nitrogen in each species, which statement most accurately classifies the reaction?$qt66$,
    $op66$[{"label":"A","text":"It is not a redox reaction, because nitrogen has the same oxidation number, \\(+1\\), on both sides of the equation."},{"label":"B","text":"It is a redox reaction: the nitrogen originating in the ammonium part is oxidized while the nitrogen originating in the nitrate part is reduced, the two converging to the single oxidation state that nitrogen has in \\(\\text{N}_2\\text{O}\\)."},{"label":"C","text":"It is a redox reaction in which both nitrogen atoms are oxidized, the ammonium nitrogen from \\(-3\\) to \\(+1\\) and the nitrate nitrogen from \\(+3\\) to \\(+5\\)."},{"label":"D","text":"It is a redox reaction: the ammonium nitrogen (\\(+5\\)) is reduced to \\(+1\\) while the nitrate nitrogen (\\(-3\\)) is oxidized to \\(+1\\)."}]$op66$::jsonb,
    'B',
    $ex66$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because the two nitrogen atoms in \(\text{NH}_4\text{NO}_3\) occupy two distinct chemical environments with different oxidation states, and tracking each separately shows electrons are transferred. In the ammonium ion \(\text{NH}_4^+\), each H is \(+1\) (total \(+4\)) and the ion charge is \(+1\), so N \(= +1 - 4 = -3\). In the nitrate ion \(\text{NO}_3^-\), each O is \(-2\) (total \(-6\)) and the ion charge is \(-1\), so N \(= -1 - (-6) = +5\). In the product \(\text{N}_2\text{O}\), O is \(-2\), so the two N atoms sum to \(+2\), giving an average of \(+1\) each. The ammonium nitrogen goes \(-3 \rightarrow +1\) (loses 4 electrons; oxidized), and the nitrate nitrogen goes \(+5 \rightarrow +1\) (gains 4 electrons; reduced). Electron bookkeeping balances exactly: 4 electrons lost equals 4 electrons gained. Because one element undergoes both oxidation and reduction, this is an internal disproportionation (comproportionation of two N states to a common value), confirming that a single-reactant decomposition can indeed be redox. (Choice A) This treats the two pre-existing nitrogen environments as if they had already been \(+1\); it ignores that the reactant contains nitrogen at \(-3\) (ammonium) and \(+5\) (nitrate), so a change in oxidation state clearly occurs. (Choice C) This correctly identifies the ammonium nitrogen as oxidized but assigns nitrate nitrogen as \(+3 \rightarrow +5\); nitrate nitrogen is actually \(+5\) and must decrease to \(+1\) (reduction), not increase, and both atoms cannot be oxidized while charge and electrons remain balanced. (Choice D) This reverses the two nitrogen environments, swapping the oxidation numbers of the ammonium and nitrate nitrogens; ammonium nitrogen is \(-3\) (not \(+5\)) and nitrate nitrogen is \(+5\) (not \(-3\)), so the oxidized/reduced roles are inverted. Skill 4$ex66$,
    'medium', '4E', $cc66$Stoichiometry (GC)$cc66$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a66A$Decomposition assumed non-redox; product oxidation state read back onto reactants$a66A$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a66C$Correct oxidation identified but nitrate N start-state miscomputed, both atoms wrongly oxidized$a66C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a66D$Ammonium and nitrate nitrogen oxidation numbers swapped, reversing oxidized/reduced roles$a66D$ FROM q;

-- Q5 [Reaction Types & Classification · hard · Skill 4 · 4E Stoichiometry (GC) · ans C] (g67)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Reaction Types & Classification',
    $qt67$Gaseous sulfur trioxide is bubbled through water, producing concentrated sulfuric acid in a strongly exothermic process that fumes visibly and sharply lowers the solution's pH: \(\text{SO}_3(g) + \text{H}_2\text{O}(l) \rightarrow \text{H}_2\text{SO}_4(aq)\). A student under time pressure must classify this transformation. Which statement correctly identifies the reaction type, and why?$qt67$,
    $op67$[{"label":"A","text":"It is an oxidation-reduction reaction, because oxygen from water is reduced from \\(0\\) to \\(-2\\) as it adds to the sulfur center."},{"label":"B","text":"It is an oxidation-reduction reaction, because sulfur is oxidized from \\(+4\\) in \\(\\text{SO}_3\\) to \\(+6\\) in \\(\\text{H}_2\\text{SO}_4\\)."},{"label":"C","text":"It is not an oxidation-reduction reaction, because sulfur remains at \\(+6\\) and oxygen at \\(-2\\) on both sides, so no oxidation numbers change."},{"label":"D","text":"It is an oxidation-reduction reaction, because the sharp drop in pH shows protons are transferred, which is the hallmark of electron transfer."}]$op67$::jsonb,
    'C',
    $ex67$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because the only way to decide redox versus non-redox is to assign oxidation numbers to every element and check whether any change. Assign oxygen its usual \(-2\) and hydrogen \(+1\). In \(\text{SO}_3\), three oxygens contribute \(3(-2) = -6\), and since the neutral molecule must sum to \(0\), sulfur is \(+6\). In \(\text{H}_2\text{O}\), hydrogen is \(+1\) and oxygen is \(-2\). In \(\text{H}_2\text{SO}_4\), the two hydrogens give \(2(+1) = +2\) and the four oxygens give \(4(-2) = -8\); for the neutral molecule \(+2 + S - 8 = 0\), so sulfur is again \(+6\). Across the arrow, sulfur stays \(+6\), oxygen stays \(-2\), and hydrogen stays \(+1\): no oxidation number changes, so no electrons are transferred and the reaction is not redox. Despite the dramatic, acid-generating chemistry, it is a non-redox combination — the hydration of an acid anhydride (a Lewis acid-base addition), not an oxidation-reduction. (Choice A) Oxygen in liquid water is \(-2\), not \(0\); free element oxygen \(\text{O}_2\) would be \(0\), but no \(\text{O}_2\) appears here, so there is no \(0 \rightarrow -2\) reduction. (Choice B) This invents a wrong starting oxidation number: sulfur in \(\text{SO}_3\) is \(+6\), not \(+4\) (\(+4\) is sulfur in \(\text{SO}_2\)), so the claimed \(+4 \rightarrow +6\) oxidation does not occur. (Choice D) This confuses proton transfer (an acid-base, Brønsted concept) with electron transfer (redox); a falling pH signals \(\text{H}^+\) release, not any change in oxidation number, so it does not establish a redox process. Skill 4$ex67$,
    'hard', '4E', $cc67$Stoichiometry (GC)$cc67$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a67A$treats bound water-oxygen as elemental O2 at 0 to manufacture a reduction$a67A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a67B$wrong assumed oxidation state of S in SO3 (confused with SO2)$a67B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a67D$conflates proton (acid-base) transfer with electron (redox) transfer$a67D$ FROM q;

-- Q6 [Redox Titrations · easy · Skill 1 · 5A Titration (GC) · ans D] (g68)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Redox Titrations',
    $qt68$A student titrates an acidic solution of \(\text{Fe}^{2+}\) with standardized \(\text{KMnO}_4\), in which manganese is reduced according to \(\text{MnO}_4^- + 8\,\text{H}^+ + 5\,e^- \rightarrow \text{Mn}^{2+} + 4\,\text{H}_2\text{O}\). No starch, ferroin, or other indicator is added to the flask. What observation directly signals that the equivalence point has just been reached?$qt68$,
    $op68$[{"label":"A","text":"A sharp color change of an added indicator, because permanganate titrations require ferroin to mark the endpoint"},{"label":"B","text":"The disappearance of the deep purple color of the solution, because all of the added \\(\\text{MnO}_4^-\\) has finally been reduced to \\(\\text{Mn}^{2+}\\)"},{"label":"C","text":"The formation of a brown \\(\\text{MnO}_2\\) precipitate, because \\(\\text{Mn}^{2+}\\) is oxidized back to \\(\\text{MnO}_4^-\\) at the endpoint"},{"label":"D","text":"The first faint purple tint that persists in the flask, because the next drop of \\(\\text{MnO}_4^-\\) is no longer decolorized once the \\(\\text{Fe}^{2+}\\) is consumed"}]$op68$::jsonb,
    'D',
    $ex68$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is D because permanganate is self-indicating: the \(\text{MnO}_4^-\) ion is intensely purple (Mn at the +7 oxidation state), whereas its reduction product \(\text{Mn}^{2+}\) is essentially colorless (only very faintly pink). Before the equivalence point, unreacted \(\text{Fe}^{2+}\) immediately reduces each added drop of purple \(\text{MnO}_4^-\) (Mn going +7 \(\rightarrow\) +2 by gaining 5 electrons, while Fe goes +2 \(\rightarrow\) +3), so the solution stays colorless. The instant all the \(\text{Fe}^{2+}\) is consumed, the very next drop of titrant has nothing to reduce it, so a slight excess of \(\text{MnO}_4^-\) lingers and tints the solution a faint, persistent purple/pink. That first lasting color is the endpoint, so no separate indicator is needed. (Choice A) is incorrect because the whole point of permanganate is that it serves as its own indicator, so adding ferroin is unnecessary; ferroin is used in cerium(IV) titrations, not as a requirement for \(\text{MnO}_4^-\). (Choice B) reverses the relationship: the solution is colorless before the endpoint and turns purple at it, not the other way around — disappearance of color cannot mark the endpoint because the titrant is what supplies the color. (Choice C) is a misconception; at the endpoint \(\text{MnO}_4^-\) is in slight excess and \(\text{Mn}^{2+}\) is not re-oxidized, and brown \(\text{MnO}_2\) forms only in neutral/basic conditions, not in the acidic medium specified here. Skill 1$ex68$,
    'easy', '5A', $cc68$Titration (GC)$cc68$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a68A$Recalls a real redox-titration indicator (ferroin) but wrongly requires it for the self-indicating permanganate system$a68A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a68B$Treats loss of color (not appearance of color) as the endpoint, inverting which species carries the purple$a68B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a68C$Imagines Mn2+ re-oxidizing to MnO2 at the endpoint, confusing acidic-medium products with neutral/basic permanganate behavior$a68C$ FROM q;

-- Q7 [Redox Titrations · medium · Skill 2 · 5A Titration (GC) · ans A] (g69)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Redox Titrations',
    $qt69$A 25.00 mL aliquot of an acidified iron(II) solution is titrated with standardized cerium(IV), which oxidizes iron(II) to iron(III) in a 1:1 mole ratio according to \(\text{Ce}^{4+} + \text{Fe}^{2+} \rightarrow \text{Ce}^{3+} + \text{Fe}^{3+}\). Reaching the equivalence point requires 24.00 mL of 0.100 M \(\text{Ce}^{4+}\). What is the molar concentration of \(\text{Fe}^{2+}\) in the original aliquot?$qt69$,
    $op69$[{"label":"A","text":"\\(0.0960\\ \\text{M}\\)"},{"label":"B","text":"\\(0.104\\ \\text{M}\\)"},{"label":"C","text":"\\(0.0480\\ \\text{M}\\)"},{"label":"D","text":"\\(0.100\\ \\text{M}\\)"}]$op69$::jsonb,
    'A',
    $ex69$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is A because the stoichiometry is 1:1 in electrons: each \(\text{Ce}^{4+}\) gains one electron (\(\text{Ce}^{4+} + e^- \rightarrow \text{Ce}^{3+}\)) and each \(\text{Fe}^{2+}\) loses one electron (\(\text{Fe}^{2+} \rightarrow \text{Fe}^{3+} + e^-\)), so at the equivalence point the moles of \(\text{Fe}^{2+}\) equal the moles of \(\text{Ce}^{4+}\). Moles of \(\text{Ce}^{4+}\) delivered \(= 0.100\ \text{M} \times 0.02400\ \text{L} = 2.40 \times 10^{-3}\ \text{mol}\), so moles \(\text{Fe}^{2+} = 2.40 \times 10^{-3}\ \text{mol}\). Dividing by the analyte volume gives \([\text{Fe}^{2+}] = 2.40 \times 10^{-3}\ \text{mol} \div 0.02500\ \text{L} = 0.0960\ \text{M}\). (Choice B) This value, \(0.104\ \text{M}\), comes from swapping the two volumes: multiplying the titrant concentration by the analyte volume (\(0.100\ \text{M} \times 0.02500\ \text{L} = 2.50 \times 10^{-3}\ \text{mol}\)) and then dividing by the titrant volume (\(2.50 \times 10^{-3}\ \text{mol} \div 0.02400\ \text{L} = 0.104\ \text{M}\)); the titrant volume must be used to find moles delivered and the analyte volume must be used as the final divisor. (Choice C) This value, \(0.0480\ \text{M}\), results from incorrectly assuming a 2:1 ratio of \(\text{Fe}^{2+}\) to \(\text{Ce}^{4+}\) and halving the moles of iron(II) (\(1.20 \times 10^{-3}\ \text{mol} \div 0.02500\ \text{L}\)) before dividing by the analyte volume; the balanced reaction transfers only one electron per pair, so the ratio is 1:1. (Choice D) This value simply restates the titrant concentration, \(0.100\ \text{M}\), and ignores that the analyte concentration depends on the moles delivered and the analyte volume rather than on the titrant concentration alone. Skill 2$ex69$,
    'medium', '5A', $cc69$Titration (GC)$cc69$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'process_step_confusion', $a69B$swapped the analyte and titrant volumes in the dilution calculation$a69B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a69C$assumed a 2:1 mole ratio instead of the correct 1:1 electron transfer$a69C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a69D$reported the titrant concentration as the analyte concentration$a69D$ FROM q;

-- Q8 [Redox Titrations · medium · Skill 3 · 5A Titration (GC) · ans B] (g70)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Redox Titrations',
    $qt70$In an acidic redox titration, \(\text{Fe}^{2+}\) (analyte) is titrated with standardized \(\text{KMnO}_4\) (titrant). The two half-reactions are \(\text{Fe}^{2+} \rightarrow \text{Fe}^{3+} + \text{e}^-\) and \(\text{MnO}_4^- + 8\,\text{H}^+ + 5\,\text{e}^- \rightarrow \text{Mn}^{2+} + 4\,\text{H}_2\text{O}\). Which statement correctly identifies the condition that defines the equivalence point of this titration?$qt70$,
    $op70$[{"label":"A","text":"The equivalence point is reached when the moles of \\(\\text{MnO}_4^-\\) added equal the moles of \\(\\text{Fe}^{2+}\\) initially present, because titrant and analyte always react in a 1:1 mole ratio."},{"label":"B","text":"The equivalence point is reached when the moles of electrons donated by \\(\\text{Fe}^{2+}\\) equal the moles of electrons accepted by \\(\\text{MnO}_4^-\\), which corresponds to \\(5\\) mol \\(\\text{Fe}^{2+}\\) per \\(1\\) mol \\(\\text{MnO}_4^-\\)."},{"label":"C","text":"The equivalence point is defined as the moment the solution first turns a persistent faint purple, because the equivalence point is set by the appearance of the indicator color."},{"label":"D","text":"The equivalence point is reached when the moles of \\(\\text{MnO}_4^-\\) added equal five times the moles of \\(\\text{Fe}^{2+}\\) present, because each \\(\\text{Fe}^{2+}\\) must supply five electrons to reduce one \\(\\text{MnO}_4^-\\)."}]$op70$::jsonb,
    'B',
    $ex70$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is B because the equivalence point of any redox titration is defined by electron balance: the moles of electrons released by the reducing agent must equal the moles of electrons consumed by the oxidizing agent. Tracking oxidation numbers, Fe goes from \(+2\) to \(+3\), so each \(\text{Fe}^{2+}\) donates exactly \(1\) electron; Mn goes from \(+7\) in \(\text{MnO}_4^-\) to \(+2\) in \(\text{Mn}^{2+}\), so each \(\text{MnO}_4^-\) accepts exactly \(5\) electrons. Setting electrons donated equal to electrons accepted, \(1 \times (\text{mol Fe}^{2+}) = 5 \times (\text{mol MnO}_4^-)\), which rearranges to \(5\) mol \(\text{Fe}^{2+}\) reacting per \(1\) mol \(\text{MnO}_4^-\). Equivalence is therefore the point of equal electron transfer, not a one-to-one matching of titrant and analyte moles. (Choice A) This is the central misconception the question targets: titrant and analyte do not always react 1:1. A 1:1 mole match holds only when each species transfers the same number of electrons; here \(\text{Fe}^{2+}\) transfers \(1\) and \(\text{MnO}_4^-\) transfers \(5\), so the equivalence point occurs at a 5:1 mole ratio (\(\text{Fe}^{2+}\) to \(\text{MnO}_4^-\)), not 1:1. (Choice C) The persistent faint purple is the endpoint — the experimentally observed signal that \(\text{MnO}_4^-\) is in slight excess and acts as its own indicator. The endpoint approximates but does not define the equivalence point; the equivalence point is the stoichiometric condition of equal electron transfer, an inherent property of the reaction rather than of the color change. (Choice D) This reverses the electron bookkeeping: it is \(\text{MnO}_4^-\) that accepts \(5\) electrons, while each \(\text{Fe}^{2+}\) supplies only \(1\). Requiring five times as much \(\text{MnO}_4^-\) as \(\text{Fe}^{2+}\) inverts the ratio; correct electron balance requires five times as much \(\text{Fe}^{2+}\) as \(\text{MnO}_4^-\). Skill 3$ex70$,
    'medium', '5A', $cc70$Titration (GC)$cc70$, 'general-chemistry', 3, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a70A$assumes titrant and analyte always react in a 1:1 mole ratio, ignoring unequal electron transfer$a70A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a70C$confuses the experimental endpoint (indicator color change) with the equivalence point defined by electron balance$a70C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a70D$inverts the electron bookkeeping, requiring 5 mol titrant per mol analyte instead of the reverse$a70D$ FROM q;

-- Q9 [Redox Titrations · medium · Skill 2 · 5A Titration (GC) · ans C] (g71)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Redox Titrations',
    $qt71$During a redox titration of \(\text{Fe}^{2+}\) with standardized \(\text{Ce}^{4+}\), no chemical indicator is added. Instead, a platinum indicator electrode and a reference electrode are immersed in the beaker and connected to a voltmeter, and the measured cell potential is recorded after each small addition of titrant. Which observation in the recorded potential signals that the endpoint has been reached?$qt71$,
    $op71$[{"label":"A","text":"The moment the cell potential first reaches exactly \\(0\\ \\text{V}\\), at which point oxidized and reduced species are present in equal amounts."},{"label":"B","text":"A cell potential that holds at a constant nonzero value once enough titrant has been added to begin the reaction."},{"label":"C","text":"A large, abrupt change in cell potential produced by a single small addition of titrant near the equivalence volume."},{"label":"D","text":"A steady, linear rise in cell potential whose slope per added milliliter is largest at the very start of the titration."}]$op71$::jsonb,
    'C',
    $ex71$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is C because in a potentiometric titration the platinum indicator electrode senses the solution's redox potential, which by the Nernst equation depends on the logarithm of the ratio of oxidized to reduced species (for the iron couple, \(E = E^\circ_{\text{Fe}^{3+}/\text{Fe}^{2+}} - \tfrac{RT}{F}\ln\frac{[\text{Fe}^{2+}]}{[\text{Fe}^{3+}]}\)). Before the equivalence point this ratio changes only gradually as \(\text{Ce}^{4+}\) oxidizes \(\text{Fe}^{2+}\) to \(\text{Fe}^{3+}\), so the potential drifts slowly. At the equivalence volume the last trace of the limiting species is consumed, the controlling couple switches from \(\text{Fe}^{3+}/\text{Fe}^{2+}\) to \(\text{Ce}^{4+}/\text{Ce}^{3+}\), and one small drop of titrant swings the relevant concentration ratio by orders of magnitude. Because the potential depends on the logarithm of that ratio, this produces a large, abrupt jump in voltage — the steep inflection in the potential-versus-volume curve — which locates the endpoint without any chemical indicator. (Choice A) The cell potential need not pass through \(0\ \text{V}\) at the endpoint — its value is set by the standard potentials of the two couples and is generally nonzero — and equal amounts of oxidized and reduced species correspond to the half-equivalence point of a couple, not to the equivalence point of the titration. (Choice B) A constant nonzero potential is what is seen during the gradual pre-equivalence buffering region, not at the endpoint; the endpoint is marked by the sudden change in potential, not by a plateau. (Choice D) The slope of the potential-versus-volume curve is smallest, not largest, at the start; the maximum slope occurs at the equivalence point, so a linear rise that is steepest at the beginning misidentifies where the endpoint signal appears. Skill 2$ex71$,
    'medium', '5A', $cc71$Titration (GC)$cc71$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a71A$endpoint-assumed-at-zero-volts-with-equal-oxidized-and-reduced species$a71A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a71B$constant-potential-plateau-mistaken-for-endpoint signal$a71B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a71D$maximum-potential-slope-placed-at-start-instead-of-equivalence point$a71D$ FROM q;

-- Q10 [Redox Titrations · hard · Skill 4 · 5A Titration (GC) · ans D] (g72)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Redox Titrations',
    $qt72$A KMnO\(_4\) solution is standardized against a primary standard of sodium oxalate, Na\(_2\)C\(_2\)O\(_4\) (molar mass \(134.00\ \text{g/mol}\)), in acidic solution, where permanganate and oxalate react in a \(2{:}5\) mole ratio (two \(\text{MnO}_4^-\) per five \(\text{C}_2\text{O}_4^{2-}\)). A \(1.0150\ \text{g}\) sample of impure (none of the impurities are redox-active) sodium oxalate is dissolved and titrated to the faint-pink endpoint, requiring \(30.00\ \text{mL}\) of \(0.1000\ \text{M}\) KMnO\(_4\). What is the mass percent of Na\(_2\)C\(_2\)O\(_4\) in the sample?$qt72$,
    $op72$[{"label":"A","text":"\\(65.04\\%\\)"},{"label":"B","text":"\\(39.61\\%\\)"},{"label":"C","text":"\\(15.84\\%\\)"},{"label":"D","text":"\\(99.01\\%\\)"}]$op72$::jsonb,
    'D',
    $ex72$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is D because the calculation chains the titrant moles through the balanced redox stoichiometry to the analyte mass and finally to mass percent. First, the moles of permanganate delivered are \(n_{\text{MnO}_4^-} = (0.1000\ \text{M})(0.03000\ \text{L}) = 3.000\times10^{-3}\ \text{mol}\). The balanced half-reaction bookkeeping confirms the \(2{:}5\) ratio: manganese is reduced from \(+7\) in \(\text{MnO}_4^-\) to \(+2\) in \(\text{Mn}^{2+}\) (a \(5\)-electron gain per Mn), while each carbon in oxalate is oxidized from \(+3\) in \(\text{C}_2\text{O}_4^{2-}\) to \(+4\) in \(\text{CO}_2\) (a \(2\)-electron loss per oxalate). Balancing electrons requires \(2\,\text{MnO}_4^- \times 5\,e^- = 5\,\text{C}_2\text{O}_4^{2-} \times 2\,e^- = 10\,e^-\), giving the mole ratio \(\text{MnO}_4^- : \text{C}_2\text{O}_4^{2-} = 2:5\). Therefore \(n_{\text{C}_2\text{O}_4^{2-}} = \tfrac{5}{2}(3.000\times10^{-3}) = 7.500\times10^{-3}\ \text{mol}\), all of which comes from the sodium oxalate. Converting to mass with the molar mass of the full compound: \(m_{\text{Na}_2\text{C}_2\text{O}_4} = (7.500\times10^{-3}\ \text{mol})(134.00\ \text{g/mol}) = 1.005\ \text{g}\). The mass percent is then \(\dfrac{1.005\ \text{g}}{1.0150\ \text{g}}\times100\% = 99.01\%\), a value consistent with a high-purity primary standard. (Choice A) \(65.04\%\) carries the correct \(7.500\times10^{-3}\ \text{mol}\) of oxalate but converts to mass using the molar mass of only the oxalate ion \(\text{C}_2\text{O}_4^{2-}\) (\(88.02\ \text{g/mol}\)) rather than that of the weighed compound \(\text{Na}_2\text{C}_2\text{O}_4\) (\(134.00\ \text{g/mol}\)); the sample mass in the denominator is the full sodium salt, so its full molar mass must be used in the numerator. (Choice B) \(39.61\%\) ignores the redox stoichiometry entirely and assumes a \(1{:}1\) mole ratio, using \(n_{\text{C}_2\text{O}_4^{2-}} = n_{\text{MnO}_4^-} = 3.000\times10^{-3}\ \text{mol}\) to obtain \(0.402\ \text{g}\); this fails to balance the \(10\) transferred electrons, which mandate \(5\) oxalates per \(2\) permanganates. (Choice C) \(15.84\%\) inverts the ratio, multiplying the permanganate moles by \(\tfrac{2}{5}\) instead of \(\tfrac{5}{2}\) to get \(1.200\times10^{-3}\ \text{mol}\) oxalate and \(0.1608\ \text{g}\); the \(2:5\) ratio of \(\text{MnO}_4^-\) to \(\text{C}_2\text{O}_4^{2-}\) means oxalate is the more abundant species, so the titrant moles must be scaled up by \(\tfrac{5}{2}\), not down. Skill 4$ex72$,
    'hard', '5A', $cc72$Titration (GC)$cc72$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'scale_unit_error', $a72A$Uses the oxalate ion molar mass (88.02) instead of the Na2C2O4 compound molar mass (134.00)$a72A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a72B$Assumes a 1:1 MnO4-:C2O4^2- mole ratio, ignoring the redox electron balance$a72B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a72C$Inverts the 2:5 ratio, scaling titrant moles by 2/5 instead of 5/2$a72C$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch4_questions FROM questions WHERE topic='Oxidation-Reduction Reactions' AND subtopic IN ('Reaction Types & Classification', 'Redox Titrations');
