-- GenChem Ch11 (Oxidation-Reduction Reactions) — Batch 2 of 4: Common Oxidizing & Reducing Agents + Balancing Redox (Half-Reaction Method)
-- 21 questions, all confidence >=4 (verified vs OpenStax Chemistry: Atoms First 2e Ch.7; every oxidation number, electron count, and balancing coefficient independently re-computed).
-- Cross-batch + cross-chapter deduped (esp. vs Ch4 Types-of-Reactions / Balancing-redox / Ions-Electrolytes); final dedup audit PASS (0 genuine conflicts) after a systematic recall-answer-leak sweep.
-- AAMC foundations in this batch: 4E (per-row foundation/content_category below). Answer key balanced A/B/C/D = 18/18/18/18 across the full 72-question chapter.
-- Re-runnable: subtopic-scoped DELETE. Run the four batches in any order in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Oxidation-Reduction Reactions' AND subtopic IN ('Common Oxidizing & Reducing Agents', 'Balancing Redox (Half-Reaction Method)');

-- Q1 [Common Oxidizing & Reducing Agents · easy · Skill 1 · 4E Stoichiometry (GC) · ans C] (g27)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt27$Sodium metal reacts vigorously with water according to \(2\,\text{Na} + 2\,\text{H}_2\text{O} \rightarrow 2\,\text{NaOH} + \text{H}_2\). Which species acts as the reducing agent in this reaction?$qt27$,
    $op27$[{"label":"A","text":"\\(\\text{H}_2\\text{O}\\), because it donates electrons to the sodium."},{"label":"B","text":"\\(\\text{NaOH}\\), one of the products of the reaction."},{"label":"C","text":"\\(\\text{Na}\\), because it is oxidized from \\(0\\) to \\(+1\\), donating electrons."},{"label":"D","text":"\\(\\text{H}_2\\), one of the products of the reaction."}]$op27$::jsonb,
    'C',
    $ex27$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because the reducing agent is the species that is itself oxidized, donating the electrons that reduce something else. Sodium goes from an oxidation state of \(0\) in \(\text{Na}\) to \(+1\) in \(\text{NaOH}\), losing one electron per atom, so it is oxidized and serves as the reducing agent. The hydrogen of water is reduced (from \(+1\) to \(0\) in \(\text{H}_2\)), which makes water the oxidizing agent. (Choice A) Water is reduced in this reaction, gaining the electrons; a species that is reduced is the oxidizing agent, not the reducing agent. (Choice B) \(\text{NaOH}\) is a product of the reaction, not a reactant that supplies electrons. (Choice D) \(\text{H}_2\) is a product formed when hydrogen is reduced, not the species that donates electrons. Skill 1$ex27$,
    'easy', '4E', $cc27$Stoichiometry (GC)$cc27$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a27A$names water (the oxidizing agent) as the electron donor$a27A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a27B$picks a product instead of the oxidized reactant$a27B$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a27D$picks a product instead of the oxidized reactant$a27D$ FROM q;

-- Q2 [Common Oxidizing & Reducing Agents · easy · Skill 1 · 4E Stoichiometry (GC) · ans D] (g28)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt28$Lithium aluminum hydride, \(\text{LiAlH}_4\), is widely used in chemical synthesis. In this compound, each hydrogen carries an oxidation state of \(-1\), making it a hydride donor. Based on this property, how does \(\text{LiAlH}_4\) typically behave when it reacts with another species?$qt28$,
    $op28$[{"label":"A","text":"It acts as a strong oxidizing agent, donating hydride ions that remove electrons from the other species."},{"label":"B","text":"It acts as a strong oxidizing agent, accepting electrons from the other species as its hydrogens are reduced."},{"label":"C","text":"It acts as a strong reducing agent because its aluminum center readily accepts electrons from the other species."},{"label":"D","text":"It acts as a strong reducing agent, donating hydride ions and thereby supplying electrons to the other species."}]$op28$::jsonb,
    'D',
    $ex28$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because a reducing agent is the species that donates electrons (and is itself oxidized) during a redox reaction. In \(\text{LiAlH}_4\), lithium is \(+1\) and aluminum is \(+3\); since the molecule is neutral, the four hydrogens must collectively account for \(-4\), so each hydrogen is \(-1\) (a hydride ion, \(\text{H}^-\)). These hydride ions are electron-rich and are readily transferred to electron-poor centers, supplying electrons to the species being reduced. By furnishing \(\text{H}^-\) and electrons, \(\text{LiAlH}_4\) functions as a strong reducing agent. (Choice A) This choice contains two errors: it mislabels \(\text{LiAlH}_4\) as an oxidizing agent, and it describes hydride donation as removing electrons; donating electron-rich \(\text{H}^-\) supplies electrons, making \(\text{LiAlH}_4\) a reducing agent. (Choice B) This reverses the role of \(\text{LiAlH}_4\): an oxidizing agent accepts electrons, but \(\text{LiAlH}_4\) donates electrons via its hydride ions, so it is a reducing agent, not an oxidizing agent. (Choice C) Although this choice correctly labels \(\text{LiAlH}_4\) as a reducing agent, its mechanism is wrong; the reducing power comes from the donation of hydride ions, not from the aluminum center accepting electrons, and a reducing agent donates rather than accepts electrons. Skill 1$ex28$,
    'easy', '4E', $cc28$Stoichiometry (GC)$cc28$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a28A$Believes hydride donation removes electrons, mislabeling the agent as oxidizing$a28A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a28B$Swaps reducing-agent role for oxidizing-agent role (donor treated as acceptor)$a28B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a28C$Correct reducing-agent label but wrong mechanism (Al accepting electrons instead of H- donation)$a28C$ FROM q;

-- Q3 [Common Oxidizing & Reducing Agents · easy · Skill 2 · 4E Stoichiometry (GC) · ans A] (g29)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt29$In an acidic redox titration, potassium dichromate, \(\text{K}_2\text{Cr}_2\text{O}_7\), is consumed as each chromium atom changes from an oxidation state of \(+6\) in the dichromate ion, \(\text{Cr}_2\text{O}_7^{2-}\), to \(+3\) in \(\text{Cr}^{3+}\). Based on this change, how should \(\text{K}_2\text{Cr}_2\text{O}_7\) be classified in this reaction?$qt29$,
    $op29$[{"label":"A","text":"It is the oxidizing agent, because the chromium is reduced."},{"label":"B","text":"It is the reducing agent, because the chromium is oxidized."},{"label":"C","text":"It is the reducing agent, because the chromium is reduced."},{"label":"D","text":"It is the oxidizing agent, because the chromium is oxidized."}]$op29$::jsonb,
    'A',
    $ex29$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because the chromium oxidation state decreases from \(+6\) to \(+3\), which is a gain of three electrons per chromium atom and therefore a reduction. (In \(\text{Cr}_2\text{O}_7^{2-}\), each oxygen is \(-2\) and the overall charge is \(-2\), so \(2(\text{Cr}) + 7(-2) = -2\), giving \(\text{Cr} = +6\); in \(\text{Cr}^{3+}\) the oxidation state is \(+3\).) The species that is reduced is, by definition, the oxidizing agent—it accepts electrons and thereby oxidizes another species. Since the chromium in \(\text{K}_2\text{Cr}_2\text{O}_7\) is reduced, \(\text{K}_2\text{Cr}_2\text{O}_7\) is the oxidizing agent. (Choice B) This both mislabels the agent and misidentifies the direction of change: a drop from \(+6\) to \(+3\) is a decrease in oxidation number, so the chromium is reduced, not oxidized, and the species is therefore not the reducing agent. (Choice C) The direction of electron transfer is correctly identified as reduction, but the classification is reversed—the species that is reduced is the oxidizing agent, not the reducing agent. (Choice D) The classification as the oxidizing agent is correct, but the stated reason is wrong: a change from \(+6\) to \(+3\) is a gain of electrons (reduction), not oxidation. Skill 2$ex29$,
    'easy', '4E', $cc29$Stoichiometry (GC)$cc29$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a29B$Calls the species reduced the reducing agent and reverses the direction of oxidation-state change$a29B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a29C$Correct that Cr is reduced but swaps oxidizing agent for reducing agent$a29C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a29D$Correct oxidizing-agent label paired with the wrong reason (oxidation instead of reduction)$a29D$ FROM q;

-- Q4 [Common Oxidizing & Reducing Agents · medium · Skill 2 · 4E Stoichiometry (GC) · ans B] (g30)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt30$In many catabolic pathways, an enzyme oxidizes a substrate by removing two hydrogen atoms; one is transferred to \(\text{NAD}^+\) as a hydride ion (\(\text{H}^-\), a proton carrying two electrons) while the second leaves as a free proton, according to the net transfer \(\text{NAD}^+ + \text{H}^- \rightarrow \text{NADH}\). On the basis of the electrons exchanged in this step, what role does \(\text{NAD}^+\) play in the reaction?$qt30$,
    $op30$[{"label":"A","text":"It is the reducing agent, because it accepts the two electrons of the hydride and is itself oxidized to \\(\\text{NADH}\\)."},{"label":"B","text":"It is the oxidizing agent, because it accepts the two electrons of the hydride and is itself reduced to \\(\\text{NADH}\\)."},{"label":"C","text":"It is the reducing agent, because by donating the hydride to the substrate it is itself oxidized to \\(\\text{NADH}\\)."},{"label":"D","text":"It is the oxidizing agent, because the free proton released to solution carries away two electrons and oxidizes \\(\\text{NAD}^+\\)."}]$op30$::jsonb,
    'B',
    $ex30$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because the oxidizing agent is the species that causes another species to be oxidized and is itself reduced by gaining electrons. A hydride ion, \(\text{H}^-\), is a single proton accompanied by two electrons, so the transfer \(\text{NAD}^+ + \text{H}^- \rightarrow \text{NADH}\) delivers two electrons to \(\text{NAD}^+\). Gaining electrons is reduction, so \(\text{NAD}^+\) is reduced to \(\text{NADH}\); a species that is reduced is by definition the oxidizing agent (it oxidizes the substrate, which loses the hydride and is therefore oxidized). The charge bookkeeping confirms this: \(\text{NAD}^+\) (net \(+1\)) plus \(\text{H}^-\) (net \(-1\)) gives neutral \(\text{NADH}\), consistent with the addition of two electrons along with one proton. (Choice A) This choice correctly identifies that \(\text{NAD}^+\) accepts the two electrons but then mislabels electron gain as oxidation; gaining electrons is reduction, and a species that is reduced is the oxidizing agent, not the reducing agent. (Choice C) This choice reverses the direction of hydride transfer: in dehydrogenation the substrate donates the hydride and \(\text{NAD}^+\) accepts it, so \(\text{NAD}^+\) is reduced (oxidizing agent), not oxidized (reducing agent). (Choice D) This choice reaches the correct label by faulty reasoning; the released species is a bare proton (\(\text{H}^+\)) that carries no electrons, and \(\text{NAD}^+\) is reduced by accepting the hydride's two electrons rather than being oxidized by the proton. Skill 2$ex30$,
    'medium', '4E', $cc30$Stoichiometry (GC)$cc30$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a30A$Equates electron gain with oxidation, mislabeling the reduced species as the reducing agent$a30A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a30C$Reverses the direction of hydride transfer so NAD+ is treated as donor and thus oxidized$a30C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a30D$Right label via wrong step: attributes electron carriage to the released proton instead of the hydride$a30D$ FROM q;

-- Q5 [Common Oxidizing & Reducing Agents · medium · Skill 3 · 4E Stoichiometry (GC) · ans C] (g31)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt31$Hydrogen peroxide, \(\text{H}_2\text{O}_2\), is unusual in that it can behave either as an oxidizing agent or as a reducing agent, depending on its reaction partner. Consider the acidic reaction \(\text{H}_2\text{O}_2 + 2\,\text{I}^- + 2\,\text{H}^+ \rightarrow \text{I}_2 + 2\,\text{H}_2\text{O}\). Based on the oxidation-state changes that occur, what role does \(\text{H}_2\text{O}_2\) play in this specific reaction?$qt31$,
    $op31$[{"label":"A","text":"It acts as the reducing agent, because its oxygen is reduced from \\(-1\\) to \\(-2\\) while it donates electrons to iodide."},{"label":"B","text":"It acts as the reducing agent, because its oxygen is oxidized from \\(-1\\) to \\(0\\) as it is converted to \\(\\text{O}_2\\)."},{"label":"C","text":"It acts as the oxidizing agent, because its oxygen is reduced (gaining electrons) as it is converted to \\(\\text{H}_2\\text{O}\\)."},{"label":"D","text":"It acts as the oxidizing agent, because its hydrogen is oxidized from \\(+1\\) to \\(0\\) as the peroxide bond breaks."}]$op31$::jsonb,
    'C',
    $ex31$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. In \(\text{H}_2\text{O}_2\) each hydrogen is \(+1\) and, for the neutral molecule to sum to zero, each oxygen must be \(-1\); this intermediate value (between \(0\) in \(\text{O}_2\) and \(-2\) in \(\text{H}_2\text{O}\)) is what lets peroxide act either way. The answer to this question is C because the oxygen-bookkeeping for this reaction shows oxygen being reduced: in the product \(\text{H}_2\text{O}\) each oxygen is \(-2\) (H is \(+1\), so \(2(+1)+x=0\) gives \(x=-2\)), a drop from \(-1\) to \(-2\). A species whose own element gains electrons (is reduced) is the oxidizing agent, so \(\text{H}_2\text{O}_2\) is the oxidizing agent here. The partner confirms this: iodine in \(\text{I}^-\) goes from \(-1\) to \(0\) in \(\text{I}_2\) (oxidized), making iodide the reducing agent. The half-reaction \(\text{H}_2\text{O}_2 + 2\,\text{H}^+ + 2\,e^- \rightarrow 2\,\text{H}_2\text{O}\) explicitly shows peroxide consuming electrons, the defining behavior of an oxidizing agent. (Choice A) The oxidation-state change is read correctly as a reduction from \(-1\) to \(-2\), but the label is reversed: a species that is itself reduced acts as the oxidizing agent, not the reducing agent, since it accepts the electrons that iodide donates. (Choice B) This correctly describes peroxide's other possible role, in which oxygen is oxidized from \(-1\) to \(0\) and \(\text{O}_2\) is released, but that is not what happens in this reaction; here the product is \(\text{H}_2\text{O}\) (oxygen \(-2\)), not \(\text{O}_2\), so peroxide is reduced rather than oxidized. (Choice D) Hydrogen remains \(+1\) on both sides (it is \(+1\) in \(\text{H}_2\text{O}_2\) and \(+1\) in \(\text{H}_2\text{O}\)); it is never reduced to \(0\), so the redox change is carried by oxygen, not hydrogen, and this reasoning misidentifies which atom changes oxidation state. Skill 3$ex31$,
    'medium', '4E', $cc31$Stoichiometry (GC)$cc31$, 'general-chemistry', 3, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a31A$correct reduction read but oxidizing/reducing-agent labels swapped$a31A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a31B$describes peroxide's other (reducing-agent) role not occurring in this reaction$a31B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a31D$assigns the redox change to hydrogen instead of oxygen$a31D$ FROM q;

-- Q6 [Common Oxidizing & Reducing Agents · medium · Skill 3 · 4E Stoichiometry (GC) · ans D] (g32)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt32$A synthetic chemist needs a reagent that will oxidize a primary alcohol to an aldehyde without carrying the oxidation further to the carboxylic acid. The chemist must select an agent in which the metal center is a chromium(VI) species. Which of the following reagents satisfies both requirements?$qt32$,
    $op32$[{"label":"A","text":"Aqueous chromic acid (Jones reagent), \\(\\text{H}_2\\text{CrO}_4\\)"},{"label":"B","text":"Acidic potassium permanganate, \\(\\text{KMnO}_4/\\text{H}^+\\)"},{"label":"C","text":"Lithium aluminum hydride, \\(\\text{LiAlH}_4\\)"},{"label":"D","text":"Pyridinium chlorochromate, \\(\\text{C}_5\\text{H}_5\\text{NH}^+[\\text{ClCrO}_3]^-\\) (PCC)"}]$op32$::jsonb,
    'D',
    $ex32$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because pyridinium chlorochromate (PCC) contains chromium in the \(+6\) state and is the mild, anhydrous oxidant that stops a primary alcohol at the aldehyde. The oxidation state of Cr in the chlorochromate anion \([\text{ClCrO}_3]^-\) is found by setting the sum of oxidation numbers equal to the ion charge: chlorine contributes \(-1\) and the three oxygens contribute \(3\times(-2)=-6\), so \(x + (-1) + (-6) = -1\), giving \(x = +6\). PCC is therefore a Cr(VI) oxidant. Because PCC is used under anhydrous (non-aqueous) conditions, the aldehyde formed from a primary alcohol cannot be hydrated to the gem-diol intermediate required for further oxidation, so the reaction halts cleanly at the aldehyde and satisfies both stated requirements. (Choice A) Aqueous chromic acid (Jones reagent) does contain chromium(VI) (in \(\text{H}_2\text{CrO}_4\): \(2(+1) + x + 4(-2) = 0\), so \(x=+6\)), but because it is used in water it overoxidizes a primary alcohol past the aldehyde to the carboxylic acid; it meets the metal requirement yet fails the selectivity requirement. (Choice B) Acidic \(\text{KMnO}_4\) is a strong oxidizing agent, but its metal center is manganese in the \(+7\) state (in \(\text{MnO}_4^-\): \(x + 4(-2) = -1\), so \(x=+7\)), not chromium(VI); moreover, as a strong aqueous oxidant it would overoxidize the primary alcohol all the way to the carboxylic acid, failing both conditions. (Choice C) \(\text{LiAlH}_4\) is a hydride source and acts as a reducing agent, not an oxidizing agent; it would drive the reaction in the opposite direction (e.g., reducing a carbonyl to an alcohol) and contains aluminum, not chromium, so it cannot oxidize an alcohol to an aldehyde at all. Skill 3$ex32$,
    'medium', '4E', $cc32$Stoichiometry (GC)$cc32$, 'general-chemistry', 3, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a32A$Correct Cr(VI) metal but aqueous conditions overoxidize to carboxylic acid, failing selectivity$a32A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a32B$Cites a strong oxidant whose metal is Mn(+7), not Cr(VI), and which overoxidizes$a32B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a32C$Selects a hydride reducing agent for an oxidation, reversing the redox direction$a32C$ FROM q;

-- Q7 [Common Oxidizing & Reducing Agents · medium · Skill 3 · 4E Stoichiometry (GC) · ans A] (g33)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt33$A laboratory chemist is ranking the four common diatomic halogens by their strength as oxidizing agents. Recall that an oxidizing agent is the species that is itself reduced during a redox reaction, and that the greater a species' tendency to be reduced, the stronger an oxidizing agent it is. Among elemental \(\text{F}_2\), \(\text{Cl}_2\), \(\text{Br}_2\), and \(\text{I}_2\), which one is the strongest oxidizing agent, and on what basis?$qt33$,
    $op33$[{"label":"A","text":"\\(\\text{F}_2\\), because it has the strongest tendency among the halogens to be reduced, gaining electrons to form \\(\\text{F}^-\\) (each fluorine going from \\(0\\) to \\(-1\\))."},{"label":"B","text":"\\(\\text{I}_2\\), because iodine has the largest atomic radius among the halogens, so \\(\\text{I}_2\\) most readily accepts electrons to form \\(\\text{I}^-\\)."},{"label":"C","text":"\\(\\text{F}_2\\), because it has the strongest tendency among the halogens to be oxidized, losing electrons to form \\(\\text{F}^+\\) (each fluorine going from \\(0\\) to \\(+1\\))."},{"label":"D","text":"\\(\\text{I}_2\\), because it is the most easily oxidized halogen, and the most easily oxidized species is by definition the strongest oxidizing agent."}]$op33$::jsonb,
    'A',
    $ex33$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because the oxidizing agent in a redox reaction is the species that is reduced (it accepts electrons and causes the oxidation of something else), so the strongest oxidizing agent is the species with the greatest tendency to be reduced. Among the halogens, the half-reaction \(\text{X}_2 + 2e^- \rightarrow 2\,\text{X}^-\) has its most positive standard reduction potential for fluorine: \(\text{F}_2 + 2e^- \rightarrow 2\,\text{F}^-\) at \(E^\circ = +2.87\ \text{V}\), versus \(\text{Cl}_2\) at \(+1.36\ \text{V}\), \(\text{Br}_2\) at \(+1.07\ \text{V}\), and \(\text{I}_2\) at \(+0.54\ \text{V}\). In this reduction each fluorine atom gains one electron, dropping from an oxidation state of \(0\) in elemental \(\text{F}_2\) to \(-1\) in \(\text{F}^-\). Because \(\text{F}_2\) is reduced more readily than any other halogen, it is the strongest common oxidizing agent. (Choice B) Although \(\text{I}_2\) is correctly described as having the largest atomic radius, the relationship is backward: the large, weakly held valence shell of iodine gives \(\text{I}_2\) the lowest tendency to be reduced (\(E^\circ = +0.54\ \text{V}\)), making it the weakest oxidizing agent of the four, not the strongest. (Choice C) This choice identifies \(\text{F}_2\) but misstates the process: an oxidizing agent is reduced, not oxidized. Fluorine, the most electronegative element, gains an electron to reach \(-1\); it does not lose an electron to form \(\text{F}^+\) (a species that does not occur in ordinary chemistry), so the oxidation-state change described here is the reverse of what defines an oxidizing agent. (Choice D) This choice inverts the definition: the species most easily oxidized (most easily losing electrons) is the strongest reducing agent, not the strongest oxidizing agent. The strongest oxidizing agent is instead the species most easily reduced, so naming the most easily oxidized halogen contradicts the role being asked about. Skill 3$ex33$,
    'medium', '4E', $cc33$Stoichiometry (GC)$cc33$, 'general-chemistry', 3, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a33B$Cites iodine's largest atomic radius as making it most easily reduced, reversing the actual trend in which the largest halogen is the weakest oxidizing agent$a33B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a33C$Correctly picks F2 but claims the oxidizing agent is oxidized to F+, confusing being reduced with being oxidized$a33C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a33D$Defines the strongest oxidizing agent as the most easily oxidized species, swapping the definitions of oxidizing and reducing agent$a33D$ FROM q;

-- Q8 [Common Oxidizing & Reducing Agents · medium · Skill 2 · 4E Stoichiometry (GC) · ans B] (g34)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt34$A reagent consists of finely divided palladium metal supported on \(\text{CaCO}_3\) that has been treated with lead salts and quinoline, then exposed to \(\text{H}_2\) gas in the presence of an internal alkyne \(\text{R}-\text{C}\equiv\text{C}-\text{R}\). Exactly one equivalent of \(\text{H}_2\) is taken up. Which statement correctly identifies this reagent and the oxidation-number bookkeeping for the carbons and hydrogens involved when one \(\text{H}_2\) is added?$qt34$,
    $op34$[{"label":"A","text":"It is Lindlar's catalyst; each former alkyne carbon loses a bond to hydrogen and is oxidized (its oxidation number rises by \\(1\\)), while each H of \\(\\text{H}_2\\) goes from \\(0\\) to \\(-1\\), for a net transfer of \\(2\\) electrons per \\(\\text{H}_2\\)."},{"label":"B","text":"It is Lindlar's catalyst; each former alkyne carbon gains one new \\(\\text{C}-\\text{H}\\) bond and is reduced (its oxidation number drops by \\(1\\)), while each H of \\(\\text{H}_2\\) goes from \\(0\\) to \\(+1\\), for a net transfer of \\(2\\) electrons per \\(\\text{H}_2\\)."},{"label":"C","text":"It is Lindlar's catalyst; each former alkyne carbon gains one new \\(\\text{C}-\\text{H}\\) bond and is reduced (its oxidation number drops by \\(1\\)), while each H of \\(\\text{H}_2\\) goes from \\(0\\) to \\(-1\\), for a net transfer of \\(4\\) electrons per \\(\\text{H}_2\\)."},{"label":"D","text":"It is Lindlar's catalyst; each former alkyne carbon is unchanged in oxidation number because \\(\\text{C}-\\text{H}\\) bonds are nonpolar, while each H of \\(\\text{H}_2\\) goes from \\(0\\) to \\(+1\\), for a net transfer of \\(2\\) electrons per \\(\\text{H}_2\\)."}]$op34$::jsonb,
    'B',
    $ex34$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because the reagent (Pd on \(\text{CaCO}_3\) deactivated with lead salts and quinoline) is Lindlar's catalyst, and the oxidation-number bookkeeping for adding one \(\text{H}_2\) across the triple bond is as follows. Oxidation numbers are assigned by giving each shared bonding pair to the more electronegative atom: in a \(\text{C}-\text{H}\) bond, carbon (\(2.55\) on the Pauling scale) is more electronegative than hydrogen (\(2.20\)), so the bonding pair is assigned to carbon, meaning each \(\text{C}-\text{H}\) bond contributes \(-1\) to carbon and \(+1\) to that hydrogen. When \(\text{H}_2\) adds, each of the two former alkyne carbons forms exactly one new bond to hydrogen, so each carbon's oxidation number decreases by \(1\) (the carbons are reduced). Each hydrogen atom in \(\text{H}_2\) starts at \(0\) (an element) and ends bonded to carbon at \(+1\), so each H is oxidized by losing one electron. With two H atoms changing from \(0\) to \(+1\), the net electron transfer is \(2\) electrons per \(\text{H}_2\) molecule, matched by the two carbons each gaining one electron. Thus \(\text{H}_2\) is the reducing agent and the alkyne is reduced. (Choice A) This reverses the direction of every change: carbons gaining \(\text{C}-\text{H}\) bonds are reduced, not oxidized, and hydrogen bonded to the less-electronegative-than-carbon position is \(+1\), not \(-1\) (hydrogen is only \(-1\) in hydrides such as \(\text{NaH}\) where it is bonded to a less electronegative element), so this option inverts both the carbon and hydrogen oxidation-number trends. (Choice C) The carbon assignment is correct, but assigning each hydrogen an oxidation number of \(-1\) is wrong because carbon is more electronegative than hydrogen; this also inflates the electron count to \(4\) per \(\text{H}_2\) by double-counting a change of \(2\) per H that does not occur, mixing up the per-atom and per-molecule bookkeeping. (Choice D) Treating \(\text{C}-\text{H}\) bonds as nonpolar leaves carbon's oxidation number unchanged, but oxidation-number rules assign the shared pair entirely to the more electronegative atom rather than splitting it, so the carbons do change (each by \(-1\)); the stated H change of \(0\) to \(+1\) is correct, which would be inconsistent with no change at carbon since electrons are conserved. Skill 2$ex34$,
    'medium', '4E', $cc34$Stoichiometry (GC)$cc34$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a34A$Reverses both redox directions: calls the carbons oxidized and assigns the added hydrogens -1 instead of +1$a34A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a34C$Misassigns hydrogen as -1 (ignoring C > H electronegativity) and inflates the electron count to 4 per H2$a34C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a34D$Correct on hydrogen but wrongly treats C-H bonds as nonpolar, leaving carbon oxidation number unchanged$a34D$ FROM q;

-- Q9 [Common Oxidizing & Reducing Agents · hard · Skill 4 · 4E Stoichiometry (GC) · ans C] (g35)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt35$Copper metal does not react with hydrochloric acid, yet it dissolves readily in concentrated nitric acid, \(\text{HNO}_3\), producing a brown gas. A student attributes this difference to the behavior of the acids' protons. Which statement best explains the dissolution of copper in concentrated \(\text{HNO}_3\) and correctly identifies the brown gas produced?$qt35$,
    $op35$[{"label":"A","text":"The dissolving agent is nitrogen in the nitrate ion, whose oxidation state falls from \\(+5\\) to \\(+2\\) as it is reduced to \\(\\text{NO}\\)."},{"label":"B","text":"The dissolving agent is the \\(\\text{H}^+\\) ion, which is reduced from \\(+1\\) to \\(0\\), liberating \\(\\text{H}_2\\) gas just as in a non-oxidizing acid."},{"label":"C","text":"The dissolving agent is the nitrate ion, whose nitrogen is reduced as it is converted to the brown gas \\(\\text{NO}_2\\), while the copper is oxidized to \\(\\text{Cu}^{2+}\\)."},{"label":"D","text":"The dissolving agent is nitrogen in the nitrate ion, which is oxidized from \\(+5\\) to \\(+6\\), and the brown gas is \\(\\text{NO}_2\\)."}]$op35$::jsonb,
    'C',
    $ex35$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because the oxidizing power of nitric acid comes from the nitrogen center, not from \(\text{H}^+\). In \(\text{HNO}_3\) the nitrogen oxidation state is fixed by the rest of the formula: each O is \(-2\) (total \(-6\)) and H is \(+1\), so for the neutral molecule N must be \(+5\). Copper lies below hydrogen in the activity series, so \(\text{H}^+\) cannot oxidize it; this is why copper is inert toward \(\text{HCl}\). Concentrated \(\text{HNO}_3\) succeeds because the \(+5\) nitrogen of the nitrate ion is itself a strong oxidizer. With concentrated acid the reduction product is \(\text{NO}_2\): in \(\text{NO}_2\) the two O atoms are \(-2\) each (\(-4\) total) on a neutral molecule, so N is \(+4\). Nitrogen therefore drops from \(+5\) to \(+4\), gaining one electron per N. The balanced half-reactions are oxidation \(\text{Cu} \rightarrow \text{Cu}^{2+} + 2\text{e}^-\) and reduction \(\text{NO}_3^- + 2\text{H}^+ + \text{e}^- \rightarrow \text{NO}_2 + \text{H}_2\text{O}\); combining them (doubling the reduction) gives \(\text{Cu} + 4\text{HNO}_3 \rightarrow \text{Cu(NO}_3)_2 + 2\text{NO}_2 + 2\text{H}_2\text{O}\), and the \(\text{NO}_2\) accounts for the observed brown gas. (Choice A) names the correct oxidizing center and a real reduction product but gives the wrong species for concentrated acid: \(\text{NO}\) (N at \(+2\)) is the product of dilute nitric acid, whereas concentrated \(\text{HNO}_3\) yields \(\text{NO}_2\), and \(\text{NO}\) is colorless rather than brown. (Choice B) is incorrect because \(\text{H}^+\) reduction to \(\text{H}_2\) is the mechanism of a non-oxidizing acid such as \(\text{HCl}\); copper cannot reduce \(\text{H}^+\), which is precisely why \(\text{HCl}\) fails to dissolve it, so this choice misattributes the oxidizing role to the proton. (Choice D) reverses the direction of the electron transfer: a substance that dissolves copper must be reduced, not oxidized, and nitrogen cannot reach \(+6\) here; furthermore an oxidation state of \(+6\) is inconsistent with the \(+4\) nitrogen actually present in \(\text{NO}_2\). Skill 4$ex35$,
    'hard', '4E', $cc35$Stoichiometry (GC)$cc35$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a35A$dilute-acid product NO (N +2) applied to the concentrated-acid case$a35A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a35B$treats nitric acid like a non-oxidizing acid, reducing H+ to H2$a35B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a35D$claims the dissolving agent is oxidized rather than reduced$a35D$ FROM q;

-- Q10 [Common Oxidizing & Reducing Agents · hard · Skill 4 · 4E Stoichiometry (GC) · ans D] (g36)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Common Oxidizing & Reducing Agents',
    $qt36$A chemist treats 4-oxopentanoic acid (levulinic acid), \(\text{CH}_3\text{C(=O)CH}_2\text{CH}_2\text{COOH}\), with one molar equivalent of sodium borohydride, \(\text{NaBH}_4\), in methanol at \(0\,^\circ\text{C}\). Lithium aluminum hydride, \(\text{LiAlH}_4\), reduces both functional groups in this molecule under analogous conditions. Given that \(\text{NaBH}_4\) is the reducing agent (donating hydride and being oxidized), which product predominates, and why?$qt36$,
    $op36$[{"label":"A","text":"Neither group is reduced; \\(\\text{NaBH}_4\\) instead acts as an oxidizing agent, accepting electrons from the carbonyls and being itself reduced."},{"label":"B","text":"Both the ketone and the carboxylic acid are reduced to alcohols, because any reagent that supplies hydride reduces every carbonyl in the molecule indiscriminately."},{"label":"C","text":"The carboxylic acid is reduced to a primary alcohol while the ketone is left intact, because the more electrophilic acid carbonyl is preferentially attacked by hydride."},{"label":"D","text":"The ketone is reduced to a secondary alcohol while the carboxylic acid is left intact, because \\(\\text{NaBH}_4\\) is a milder hydride donor that reduces aldehydes and ketones but not carboxylic acids."}]$op36$::jsonb,
    'D',
    $ex36$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because sodium borohydride is the reducing agent throughout: each \(\text{B}-\text{H}\) bond delivers a hydride ion (\(\text{H}^-\), formal oxidation state \(-1\)) to a carbonyl carbon. In donating hydride, \(\text{NaBH}_4\) is itself oxidized (boron, originally bonded to four reducing \(\text{H}\) atoms, ends up in \(\text{B}(\text{OR})\)-type species), which is the defining behavior of a reducing agent. However, \(\text{NaBH}_4\) is a comparatively mild hydride donor: it is reactive enough to add hydride to the relatively electrophilic carbon of aldehydes and ketones, but not to the much less electrophilic carbon of a carboxylic acid (whose carbonyl is deactivated by resonance donation from the \(-\text{OH}\) oxygen and which, under these conditions, is first deprotonated to the even less electrophilic carboxylate). Therefore the ketone of levulinic acid is reduced to a secondary alcohol, \(\text{CH}_3\text{CH(OH)CH}_2\text{CH}_2\text{COOH}\), while the carboxylic acid survives. The stronger hydride donor \(\text{LiAlH}_4\) is required to reduce the carboxylic acid (and esters/amides) all the way to a primary alcohol, which is why it reduces both groups. (Choice A) This inverts the redox roles: a species that donates hydride to carbonyl carbons is oxidized and is the reducing agent, not an oxidizing agent; \(\text{NaBH}_4\) does not accept electrons from the carbonyls. (Choice B) This overgeneralizes: not every hydride source reduces every carbonyl. Reducing strength is graded, and \(\text{NaBH}_4\) specifically cannot reduce carboxylic acids, so reduction is chemoselective rather than indiscriminate. (Choice C) This reverses the true reactivity order. The carboxylic acid carbonyl is the harder, not the easier, group to reduce because resonance from the hydroxyl oxygen lowers its electrophilicity (and the acid is deprotonated to carboxylate), whereas the ketone is the group \(\text{NaBH}_4\) actually reduces. Skill 4$ex36$,
    'hard', '4E', $cc36$Stoichiometry (GC)$cc36$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a36A$NaBH4 cast as oxidizing agent$a36A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a36B$hydride reduces every carbonyl indiscriminately$a36B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a36C$acid carbonyl reduced preferentially over ketone$a36C$ FROM q;

-- Q11 [Balancing Redox (Half-Reaction Method) · easy · Skill 1 · 4E Stoichiometry (GC) · ans A] (g37)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt37$Consider the reduction of molecular oxygen to water in acidic solution, represented by the skeleton half-reaction \(\text{O}_2 \rightarrow \text{H}_2\text{O}\) (acidic). When this half-reaction is fully balanced, how many electrons must be supplied per \(\text{O}_2\) molecule reduced?$qt37$,
    $op37$[{"label":"A","text":"\\(4\\) electrons"},{"label":"B","text":"\\(2\\) electrons"},{"label":"C","text":"\\(1\\) electron"},{"label":"D","text":"\\(8\\) electrons"}]$op37$::jsonb,
    'A',
    $ex37$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because each oxygen atom is reduced from an oxidation state of \(0\) in \(\text{O}_2\) to \(-2\) in \(\text{H}_2\text{O}\), a gain of \(2\) electrons per atom; since one \(\text{O}_2\) molecule contains two oxygen atoms, the molecule gains \(2 \times 2 = 4\) electrons, giving the balanced half-reaction \(\text{O}_2 + 4\text{H}^+ + 4e^- \rightarrow 2\text{H}_2\text{O}\). (Choice B) \(2\) electrons counts only the change for a single oxygen atom and forgets that \(\text{O}_2\) contains two oxygen atoms, each gaining two electrons. (Choice C) \(1\) electron matches neither the per-atom change (which is \(2\)) nor the per-molecule total (which is \(4\)). (Choice D) \(8\) electrons doubles the correct count, as if each oxygen gained four electrons, but the change from \(0\) to \(-2\) is only two electrons per atom. Skill 1$ex37$,
    'easy', '4E', $cc37$Stoichiometry (GC)$cc37$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a37B$counts the per-atom 2-electron change, forgetting O2 has two atoms$a37B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a37C$neither the per-atom nor per-molecule electron count$a37C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a37D$doubles the correct electron count$a37D$ FROM q;

-- Q12 [Balancing Redox (Half-Reaction Method) · easy · Skill 2 · 4E Stoichiometry (GC) · ans B] (g38)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt38$In acidic solution, chlorate ion is reduced to chloride ion. A student balancing the skeleton half-reaction \(\text{ClO}_3^- \rightarrow \text{Cl}^-\) (acidic) by the half-reaction method must account for the oxygen atoms with water and then balance the resulting hydrogen atoms with \(\text{H}^+\). How many \(\text{H}^+\) ions are required to balance this half-reaction, and on which side are they added?$qt38$,
    $op38$[{"label":"A","text":"\\(3\\;\\text{H}^+\\) on the left (reactant) side"},{"label":"B","text":"\\(6\\;\\text{H}^+\\) on the left (reactant) side"},{"label":"C","text":"\\(6\\;\\text{H}^+\\) on the right (product) side"},{"label":"D","text":"\\(6\\;\\text{OH}^-\\) on the left (reactant) side"}]$op38$::jsonb,
    'B',
    $ex38$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because in acidic medium the half-reaction is balanced by first balancing the element other than O and H (chlorine is already \(1\) on each side), then balancing oxygen with water, and finally balancing hydrogen with \(\text{H}^+\). The reactant \(\text{ClO}_3^-\) carries \(3\) oxygen atoms while the product \(\text{Cl}^-\) carries none, so \(3\,\text{H}_2\text{O}\) are added on the right to balance oxygen: \(\text{ClO}_3^- \rightarrow \text{Cl}^- + 3\,\text{H}_2\text{O}\). Those \(3\,\text{H}_2\text{O}\) introduce \(6\) hydrogen atoms on the right, so \(6\,\text{H}^+\) must be added on the left to balance hydrogen, giving \(\text{ClO}_3^- + 6\,\text{H}^+ + 6e^- \rightarrow \text{Cl}^- + 3\,\text{H}_2\text{O}\). The \(\text{H}^+\) belong on the reactant (left) side. (Choice A) \(3\,\text{H}^+\) on the left matches the number of oxygen atoms rather than the number of hydrogen atoms supplied by \(3\,\text{H}_2\text{O}\); each water contributes two hydrogens, so \(6\,\text{H}^+\) are needed, not \(3\). (Choice C) Placing \(6\,\text{H}^+\) on the right doubles the hydrogen on the product side instead of balancing it, leaving the equation with \(12\) H on the right and none on the left. (Choice D) Hydroxide ions are used to balance hydrogen in basic solution; in acidic solution hydrogen is balanced with \(\text{H}^+\), so \(\text{OH}^-\) is not the appropriate species here. Skill 2$ex38$,
    'easy', '4E', $cc38$Stoichiometry (GC)$cc38$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a38A$matches H+ count to the number of oxygen atoms instead of hydrogen atoms$a38A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a38C$places H+ on the same side as the water rather than the opposite side$a38C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a38D$uses OH- (basic-solution balancing) in an acidic half-reaction$a38D$ FROM q;

-- Q13 [Balancing Redox (Half-Reaction Method) · medium · Skill 2 · 4E Stoichiometry (GC) · ans C] (g39)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt39$When the half-reaction method is used to balance the reduction of nitrate ion to nitric oxide in acidic solution, the unbalanced skeleton half-reaction is \(\text{NO}_3^- \rightarrow \text{NO}\). After the half-reaction is fully balanced for mass and charge in acidic medium, what is the coefficient of \(\text{H}_2\text{O}\)?$qt39$,
    $op39$[{"label":"A","text":"3"},{"label":"B","text":"1"},{"label":"C","text":"2"},{"label":"D","text":"4"}]$op39$::jsonb,
    'C',
    $ex39$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because balancing \(\text{NO}_3^- \rightarrow \text{NO}\) by the half-reaction method in acid proceeds in a fixed order. First balance the atom undergoing redox: nitrogen is already balanced (1 N on each side). Next balance oxygen by adding \(\text{H}_2\text{O}\): the left side has 3 O (in \(\text{NO}_3^-\)) and the right side has 1 O (in \(\text{NO}\)), a difference of 2 O, so 2 \(\text{H}_2\text{O}\) must be added to the right, giving \(\text{NO}_3^- \rightarrow \text{NO} + 2\,\text{H}_2\text{O}\). Then balance hydrogen with \(\text{H}^+\): the right now has 4 H (from 2 \(\text{H}_2\text{O}\)), so add 4 \(\text{H}^+\) to the left, giving \(4\,\text{H}^+ + \text{NO}_3^- \rightarrow \text{NO} + 2\,\text{H}_2\text{O}\). Finally balance charge with electrons: the left has a net charge of \(4(+1) + (-1) = +3\) and the right is \(0\), so add 3 \(e^-\) to the left: \(3\,e^- + 4\,\text{H}^+ + \text{NO}_3^- \rightarrow \text{NO} + 2\,\text{H}_2\text{O}\). This 3-electron gain is consistent with nitrogen being reduced from \(+5\) in \(\text{NO}_3^-\) to \(+2\) in \(\text{NO}\). Therefore the coefficient of \(\text{H}_2\text{O}\) is 2. (Choice A) A coefficient of 3 incorrectly sets the number of \(\text{H}_2\text{O}\) equal to the 3 electrons transferred (the \(+5 \rightarrow +2\) change), confusing the electron count with the water coefficient. (Choice B) A coefficient of 1 would only balance one oxygen atom on the right, leaving the oxygen mass unbalanced (3 O on the left versus 2 O on the right); it reflects adding a single water molecule without matching the full oxygen deficit. (Choice D) A coefficient of 4 mistakes the number of \(\text{H}^+\) ions (4) for the number of water molecules, swapping the hydrogen-balancing step with the oxygen-balancing step. Skill 2$ex39$,
    'medium', '4E', $cc39$Stoichiometry (GC)$cc39$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a39A$equates water coefficient with electron count$a39A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a39B$adds one water, ignores full oxygen deficit$a39B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a39D$mistakes the H+ count for the H2O count$a39D$ FROM q;

-- Q14 [Balancing Redox (Half-Reaction Method) · medium · Skill 2 · 4E Stoichiometry (GC) · ans D] (g40)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt40$In acidic solution, nitrate ion can be reduced all the way to ammonium ion according to the unbalanced skeleton half-reaction \(\text{NO}_3^- \rightarrow \text{NH}_4^+\). When this half-reaction is balanced by the half-reaction method, how many electrons are transferred per nitrate ion reduced?$qt40$,
    $op40$[{"label":"A","text":"\\(3\\) electrons"},{"label":"B","text":"\\(5\\) electrons"},{"label":"C","text":"\\(6\\) electrons"},{"label":"D","text":"\\(8\\) electrons"}]$op40$::jsonb,
    'D',
    $ex40$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because the number of electrons transferred equals the magnitude of the change in nitrogen's oxidation state. In \(\text{NO}_3^-\), each oxygen is \(-2\) (total \(-6\)) and the ion charge is \(-1\), so nitrogen is \(+5\). In \(\text{NH}_4^+\), each hydrogen is \(+1\) (total \(+4\)) and the ion charge is \(+1\), so nitrogen is \(-3\). Going from \(+5\) to \(-3\) is a gain of \(8\) units of negative charge, meaning \(8\) electrons are added per nitrogen atom; this is confirmed by the balanced reduction half-reaction \(\text{NO}_3^- + 10\,\text{H}^+ + 8e^- \rightarrow \text{NH}_4^+ + 3\,\text{H}_2\text{O}\). (Choice A) \(3\) electrons reflects only the magnitude of the final oxidation state \(-3\) itself rather than the full \(+5\) to \(-3\) change. (Choice B) \(5\) electrons would correspond to a change from \(+5\) only down to \(0\), which is the nitrogen oxidation state in \(\text{N}_2\), not the \(-3\) of ammonium. (Choice C) \(6\) electrons would arise from incorrectly using \(-1\) (rather than \(-3\)) as nitrogen's final oxidation state, miscounting the change as \(+5\) to \(-1\). Skill 2$ex40$,
    'medium', '4E', $cc40$Stoichiometry (GC)$cc40$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a40A$reports only the magnitude of the final oxidation state rather than the total change in oxidation state$a40A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a40B$stops the reduction at elemental nitrogen (0) instead of going to -3$a40B$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a40C$uses an incorrect final oxidation state of -1 for nitrogen, undercounting the electron change$a40C$ FROM q;

-- Q15 [Balancing Redox (Half-Reaction Method) · medium · Skill 2 · 4E Stoichiometry (GC) · ans A] (g41)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt41$In acidic aqueous solution, sulfur dioxide can be oxidized to sulfate ion, \(\text{SO}_4^{2-}\). A student writes the unbalanced skeleton for this oxidation half-reaction as \(\text{SO}_2 \rightarrow \text{SO}_4^{2-}\) and balances it using the half-reaction method (adding \(\text{H}_2\text{O}\), \(\text{H}^+\), and \(e^-\) as needed for an acidic medium). Which of the following is the correctly balanced oxidation half-reaction?$qt41$,
    $op41$[{"label":"A","text":"\\(\\text{SO}_2 + 2\\text{H}_2\\text{O} \\rightarrow \\text{SO}_4^{2-} + 4\\text{H}^+ + 2e^-\\)"},{"label":"B","text":"\\(\\text{SO}_2 \\rightarrow \\text{SO}_4^{2-} + 2e^-\\)"},{"label":"C","text":"\\(\\text{SO}_2 + 2\\text{H}_2\\text{O} \\rightarrow \\text{SO}_4^{2-} + 4\\text{H}^+ + 4e^-\\)"},{"label":"D","text":"\\(\\text{SO}_2 + 2\\text{H}_2\\text{O} \\rightarrow \\text{SO}_4^{2-} + 4\\text{H}^+\\)"}]$op41$::jsonb,
    'A',
    $ex41$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because sulfur is oxidized from \(+4\) in \(\text{SO}_2\) (oxygen is \(-2\), so \(\text{S} + 2(-2) = 0\) gives \(\text{S} = +4\)) to \(+6\) in \(\text{SO}_4^{2-}\) (\(\text{S} + 4(-2) = -2\) gives \(\text{S} = +6\)), a loss of \(2\) electrons per sulfur. Applying the half-reaction method in acid: balance oxygen by adding \(2\,\text{H}_2\text{O}\) to the left (left has \(2\) O, right has \(4\) O), giving \(\text{SO}_2 + 2\text{H}_2\text{O} \rightarrow \text{SO}_4^{2-}\); balance hydrogen by adding \(4\,\text{H}^+\) to the right, giving \(\text{SO}_2 + 2\text{H}_2\text{O} \rightarrow \text{SO}_4^{2-} + 4\text{H}^+\); then balance charge by adding \(2e^-\) to the right. The mass balance is correct (S: \(1=1\); O: \(2+2=4\); H: \(4=4\)) and the charge balance is correct (left \(=0\); right \(= -2 + 4 - 2 = 0\)). (Choice B) This skeleton conserves neither oxygen nor hydrogen: the left side has \(2\) oxygens while the right side has \(4\), and no \(\text{H}_2\text{O}\) or \(\text{H}^+\) is included to account for the added oxygen, so mass is not balanced. (Choice C) The atoms are balanced, but the electron count is wrong: sulfur only changes by \(2\) units of oxidation state (\(+4\) to \(+6\)), so only \(2\) electrons are released; writing \(4e^-\) also leaves the charge unbalanced (left \(=0\), right \(= -2 + 4 - 4 = -2\)). (Choice D) The atoms are balanced, but no electrons are shown; without the \(2e^-\) on the right the charge is unbalanced (left \(=0\), right \(= -2 + 4 = +2\)) and the species lost during oxidation is not represented. Skill 2$ex41$,
    'medium', '4E', $cc41$Stoichiometry (GC)$cc41$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'process_step_confusion', $a41B$skips the water/proton steps and balances only electrons, leaving O and H unaccounted for$a41B$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a41C$uses the total oxygens added (4) as the electron count instead of the oxidation-state change of sulfur$a41C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a41D$correctly balances mass with water and protons but omits the electrons, ignoring charge balance$a41D$ FROM q;

-- Q16 [Balancing Redox (Half-Reaction Method) · medium · Skill 2 · 4E Stoichiometry (GC) · ans B] (g42)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt42$When permanganate ion is reduced to manganese(IV) oxide in basic solution, the balanced half-reaction is written as \(\text{MnO}_4^- + x\,\text{H}_2\text{O} + 3e^- \rightarrow \text{MnO}_2 + 4\,\text{OH}^-\). What is the value of the coefficient \(x\) on \(\text{H}_2\text{O}\) as a reactant?$qt42$,
    $op42$[{"label":"A","text":"\\(1\\)"},{"label":"B","text":"\\(2\\)"},{"label":"C","text":"\\(3\\)"},{"label":"D","text":"\\(4\\)"}]$op42$::jsonb,
    'B',
    $ex42$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because manganese is reduced from \(+7\) in \(\text{MnO}_4^-\) (each O is \(-2\), so \(\text{Mn} + 4(-2) = -1 \Rightarrow \text{Mn} = +7\)) to \(+4\) in \(\text{MnO}_2\) (\(\text{Mn} + 2(-2) = 0 \Rightarrow \text{Mn} = +4\)), a gain of \(3\) electrons. Balancing first in acid gives \(\text{MnO}_4^- + 4\,\text{H}^+ + 3e^- \rightarrow \text{MnO}_2 + 2\,\text{H}_2\text{O}\). Converting to base, add \(4\,\text{OH}^-\) to both sides to neutralize the \(4\,\text{H}^+\): the \(4\,\text{H}^+ + 4\,\text{OH}^-\) become \(4\,\text{H}_2\text{O}\) on the left, leaving \(\text{MnO}_4^- + 4\,\text{H}_2\text{O} + 3e^- \rightarrow \text{MnO}_2 + 2\,\text{H}_2\text{O} + 4\,\text{OH}^-\). Canceling \(2\,\text{H}_2\text{O}\) common to both sides yields \(\text{MnO}_4^- + 2\,\text{H}_2\text{O} + 3e^- \rightarrow \text{MnO}_2 + 4\,\text{OH}^-\), so \(x = 2\). Checking: O is \(4+2=6\) on the left and \(2+4=6\) on the right; H is \(4\) on each side; charge is \(-1 + (-3) = -4\) on the left and \(4(-1) = -4\) on the right. (Choice A) A coefficient of \(1\) leaves oxygen and hydrogen unbalanced (only \(2\) O and \(2\) H supplied by water, insufficient to produce \(4\,\text{OH}^-\) while balancing the lost oxygens) and reflects under-counting the water needed. (Choice C) A coefficient of \(3\) confuses the water coefficient with the \(3\) electrons transferred in the reduction, which are unrelated quantities. (Choice D) A coefficient of \(4\) mistakenly carries over the \(4\,\text{H}^+\) (or the \(4\,\text{OH}^-\)) count to water rather than performing the acid-to-base conversion and canceling the duplicated water molecules. Skill 2$ex42$,
    'medium', '4E', $cc42$Stoichiometry (GC)$cc42$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a42A$Under-balances water, leaving O and H atoms uncounted$a42A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a42C$Sets water coefficient equal to the electron count (3 e-)$a42C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a42D$Carries the 4 H+/4 OH- count onto water without canceling duplicates$a42D$ FROM q;

-- Q17 [Balancing Redox (Half-Reaction Method) · medium · Skill 2 · 4E Stoichiometry (GC) · ans C] (g43)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt43$In strongly basic solution, chromium(III) hydroxide is oxidized to chromate ion according to the unbalanced half-reaction \(\text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-}\). When this half-reaction is balanced in base using the half-reaction method (balancing O with \(\text{H}_2\text{O}\) and H with \(\text{OH}^-\)), how many hydroxide ions \((\text{OH}^-)\) appear, and on which side do they appear?$qt43$,
    $op43$[{"label":"A","text":"\\(4\\;\\text{OH}^-\\) on the product (right) side"},{"label":"B","text":"\\(3\\;\\text{OH}^-\\) on the reactant (left) side"},{"label":"C","text":"\\(5\\;\\text{OH}^-\\) on the reactant (left) side"},{"label":"D","text":"\\(8\\;\\text{OH}^-\\) on the reactant (left) side"}]$op43$::jsonb,
    'C',
    $ex43$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because balancing the half-reaction in base yields \(5\;\text{OH}^-\) on the reactant side. Chromium is \(+3\) in \(\text{Cr(OH)}_3\) and \(+6\) in \(\text{CrO}_4^{2-}\), so \(3\) electrons are lost per chromium. Balancing stepwise: Cr is already \(1{:}1\). Oxygen goes from \(3\) (left) to \(4\) (right), so add one \(\text{H}_2\text{O}\) to the left, giving \(\text{H}_2\text{O} + \text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-}\), which now has \(4\) O on each side. Hydrogen is then \(5\) on the left (\(2\) from water plus \(3\) from hydroxide) and \(0\) on the right, so add \(5\;\text{H}^+\) to the right (acidic intermediate): \(\text{H}_2\text{O} + \text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-} + 5\text{H}^+\). Charge is \(0\) on the left and \(+3\) on the right, so add \(3\;e^-\) to the right: \(\text{H}_2\text{O} + \text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-} + 5\text{H}^+ + 3e^-\) (the \(3\) electrons confirm the \(+3 \rightarrow +6\) oxidation). To convert to base, add \(5\;\text{OH}^-\) to both sides to neutralize the \(5\;\text{H}^+\): \(5\text{OH}^- + \text{H}_2\text{O} + \text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-} + 5\text{H}_2\text{O} + 3e^-\). Cancelling the one \(\text{H}_2\text{O}\) on the left against one of the five on the right gives the final balanced half-reaction \(5\text{OH}^- + \text{Cr(OH)}_3 \rightarrow \text{CrO}_4^{2-} + 4\text{H}_2\text{O} + 3e^-\), with \(5\;\text{OH}^-\) on the reactant side. (Choice A) \(4\;\text{OH}^-\) on the right confuses the hydroxide coefficient with the coefficient of \(\text{H}_2\text{O}\) (\(4\;\text{H}_2\text{O}\)), which appears on the product side; the hydroxide ions are added to neutralize \(\text{H}^+\) and end up on the reactant side. (Choice B) \(3\;\text{OH}^-\) on the left mistakes the hydroxide coefficient for the number of electrons transferred (\(3\;e^-\) from the \(+3 \rightarrow +6\) change); the electron count and the \(\text{OH}^-\) count are determined by separate balancing steps and need not match. (Choice D) \(8\;\text{OH}^-\) results from failing to cancel the common \(\text{H}_2\text{O}\) and instead summing all hydrogen-bearing species, overcounting the hydroxide added during neutralization. Skill 2$ex43$,
    'medium', '4E', $cc43$Stoichiometry (GC)$cc43$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a43A$Confuses OH- coefficient with the H2O coefficient and its product-side placement$a43A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a43B$Mistakes OH- coefficient for the electron-transfer count (3 e-)$a43B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a43D$Fails to cancel common water, overcounting added hydroxide$a43D$ FROM q;

-- Q18 [Balancing Redox (Half-Reaction Method) · hard · Skill 4 · 4E Stoichiometry (GC) · ans D] (g44)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt44$In an acidic titration, permanganate oxidizes oxalate \(\text{C}_2\text{O}_4^{2-}\) to carbon dioxide while \(\text{MnO}_4^-\) is reduced to \(\text{Mn}^{2+}\). A student balances the process with the half-reaction method, writing the reduction half-reaction as \(\text{MnO}_4^- + 8\text{H}^+ + 5e^- \rightarrow \text{Mn}^{2+} + 4\text{H}_2\text{O}\) and the oxidation half-reaction as \(\text{C}_2\text{O}_4^{2-} \rightarrow 2\text{CO}_2 + 2e^-\). After equalizing the electrons and combining the two half-reactions into a single overall equation written with the smallest whole-number coefficients, what is the coefficient of \(\text{H}^+\) in that overall equation?$qt44$,
    $op44$[{"label":"A","text":"5"},{"label":"B","text":"8"},{"label":"C","text":"10"},{"label":"D","text":"16"}]$op44$::jsonb,
    'D',
    $ex44$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is D because the two half-reactions can be added only after the electrons lost equal the electrons gained, and the half-reaction containing \(\text{H}^+\) must itself be scaled to reach that common electron count. In the reduction half-reaction, manganese goes from \(+7\) in \(\text{MnO}_4^-\) to \(+2\) in \(\text{Mn}^{2+}\), a gain of 5 electrons: \(\text{MnO}_4^- + 8\text{H}^+ + 5e^- \rightarrow \text{Mn}^{2+} + 4\text{H}_2\text{O}\). In the oxidation half-reaction, each carbon in \(\text{C}_2\text{O}_4^{2-}\) goes from \(+3\) to \(+4\) in \(\text{CO}_2\), so the two carbons lose 2 electrons total: \(\text{C}_2\text{O}_4^{2-} \rightarrow 2\text{CO}_2 + 2e^-\). The least common multiple of 5 and 2 is 10, so the reduction half-reaction is multiplied by 2 and the oxidation half-reaction by 5: \(2\text{MnO}_4^- + 16\text{H}^+ + 10e^- \rightarrow 2\text{Mn}^{2+} + 8\text{H}_2\text{O}\) and \(5\text{C}_2\text{O}_4^{2-} \rightarrow 10\text{CO}_2 + 10e^-\). Adding these and cancelling the 10 electrons gives the overall equation \(2\text{MnO}_4^- + 16\text{H}^+ + 5\text{C}_2\text{O}_4^{2-} \rightarrow 2\text{Mn}^{2+} + 8\text{H}_2\text{O} + 10\text{CO}_2\). Because the original \(8\text{H}^+\) was multiplied by 2 when the reduction half-reaction was scaled, the \(\text{H}^+\) coefficient is 16, and the equation balances for all atoms and for charge \((+4\) on each side\()\) with no common factor to reduce. (Choice A) 5 is the coefficient of the oxalate ion \(\text{C}_2\text{O}_4^{2-}\) in the overall equation, not the coefficient of \(\text{H}^+\). (Choice B) 8 is the number of \(\text{H}^+\) in the unscaled reduction half-reaction; it ignores that this half-reaction must be doubled to supply 10 electrons, so its \(\text{H}^+\) must be doubled as well. (Choice C) 10 is the equalized number of electrons transferred (the least common multiple of 5 and 2), not the number of protons that appear in the balanced equation. Skill 4$ex44$,
    'hard', '4E', $cc44$Stoichiometry (GC)$cc44$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a44A$Gives the oxalate coefficient instead of the H+ coefficient$a44A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a44B$Uses the unscaled reduction half-reaction's H+ count, forgetting it is doubled when that half-reaction is scaled to 10 electrons$a44B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a44C$Reports the equalized electron count (LCM of 5 and 2) as the H+ coefficient$a44C$ FROM q;

-- Q19 [Balancing Redox (Half-Reaction Method) · hard · Skill 4 · 4E Stoichiometry (GC) · ans A] (g45)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt45$Consider the balanced redox reaction \(2\,\text{S}_2\text{O}_3^{2-} + \text{I}_2 \rightarrow \text{S}_4\text{O}_6^{2-} + 2\,\text{I}^-\), used in iodometric titrations. How many electrons are transferred in this reaction as written?$qt45$,
    $op45$[{"label":"A","text":"\\(2\\) electrons"},{"label":"B","text":"\\(1\\) electron"},{"label":"C","text":"\\(4\\) electrons"},{"label":"D","text":"\\(6\\) electrons"}]$op45$::jsonb,
    'A',
    $ex45$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is A because the electrons gained by the species reduced equal the electrons lost by the species oxidized. Each iodine atom in \(\text{I}_2\) (oxidation state \(0\)) becomes \(\text{I}^-\) (\(-1\)), gaining one electron, so the two iodine atoms gain \(2\) electrons in total. Correspondingly, the sulfur of two thiosulfate ions (average \(+2\)) is oxidized to tetrathionate \(\text{S}_4\text{O}_6^{2-}\) (average \(+2.5\)), releasing \(2\) electrons in total. Thus \(2\) electrons are transferred. (Choice B) \(1\) electron accounts for only a single iodine atom, but \(\text{I}_2\) contains two iodine atoms, each gaining one electron. (Choice C) \(4\) electrons doubles the correct count. (Choice D) \(6\) electrons does not match the one-electron-per-iodine change across the two iodine atoms. Skill 4$ex45$,
    'hard', '4E', $cc45$Stoichiometry (GC)$cc45$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a45B$counts only one iodine atom instead of the two in I2$a45B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a45C$doubles the correct electron count$a45C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a45D$electron count unrelated to the per-iodine change$a45D$ FROM q;

-- Q20 [Balancing Redox (Half-Reaction Method) · hard · Skill 4 · 4E Stoichiometry (GC) · ans B] (g46)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt46$Acidic dichromate is a strong oxidant frequently used to titrate iron(II). When dichromate ion oxidizes iron(II) to iron(III) in acidic solution, the unbalanced skeleton is \(\text{Cr}_2\text{O}_7^{2-} + \text{Fe}^{2+} + \text{H}^+ \rightarrow \text{Cr}^{3+} + \text{Fe}^{3+} + \text{H}_2\text{O}\). Using the half-reaction method, what is the stoichiometric coefficient of \(\text{Fe}^{3+}\) in the fully balanced overall equation (smallest whole-number coefficients)?$qt46$,
    $op46$[{"label":"A","text":"3"},{"label":"B","text":"6"},{"label":"C","text":"2"},{"label":"D","text":"14"}]$op46$::jsonb,
    'B',
    $ex46$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is B because the two half-reactions must transfer equal numbers of electrons. In the reduction half-reaction, each chromium goes from \(+6\) in \(\text{Cr}_2\text{O}_7^{2-}\) to \(+3\) in \(\text{Cr}^{3+}\); with two chromium atoms that is \(2 \times 3 = 6\) electrons gained: \(\text{Cr}_2\text{O}_7^{2-} + 14\text{H}^+ + 6e^- \rightarrow 2\text{Cr}^{3+} + 7\text{H}_2\text{O}\). In the oxidation half-reaction, iron goes from \(+2\) to \(+3\), losing one electron each: \(\text{Fe}^{2+} \rightarrow \text{Fe}^{3+} + e^-\). To balance the 6 electrons released by the reduction, the iron half-reaction is multiplied by 6: \(6\text{Fe}^{2+} \rightarrow 6\text{Fe}^{3+} + 6e^-\). Adding the half-reactions gives \(\text{Cr}_2\text{O}_7^{2-} + 6\text{Fe}^{2+} + 14\text{H}^+ \rightarrow 2\text{Cr}^{3+} + 6\text{Fe}^{3+} + 7\text{H}_2\text{O}\), so the coefficient of \(\text{Fe}^{3+}\) is \(6\). (Choice A) 3 is the number of electrons gained per single chromium atom (\(+6 \rightarrow +3\)); it would be the electron transfer for only one Cr rather than the total 6 electrons that fix the iron coefficient. (Choice C) 2 is the coefficient of \(\text{Cr}^{3+}\), obtained from the two chromium atoms in \(\text{Cr}_2\text{O}_7^{2-}\); it is mismatched to \(\text{Fe}^{3+}\), which is set by the 6-electron requirement. (Choice D) 14 is the coefficient of \(\text{H}^+\) needed to balance the seven oxygen atoms as water in the reduction half-reaction, not the iron coefficient. Skill 4$ex46$,
    'hard', '4E', $cc46$Stoichiometry (GC)$cc46$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a46A$Uses electrons-per-single-Cr (3) instead of total 6-electron transfer$a46A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a46C$Copies the Cr3+ coefficient (2) onto Fe3+$a46C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a46D$Mistakes the H+ balancing coefficient (14) for the Fe3+ coefficient$a46D$ FROM q;

-- Q21 [Balancing Redox (Half-Reaction Method) · hard · Skill 3 · 4E Stoichiometry (GC) · ans C] (g47)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Oxidation-Reduction Reactions', 'Balancing Redox (Half-Reaction Method)',
    $qt47$In basic solution, elemental bromine disproportionates to bromide ion and bromate ion according to the unbalanced skeleton reaction \(\text{Br}_2 \rightarrow \text{Br}^- + \text{BrO}_3^-\). A student balances this process with the half-reaction method, balancing oxygen with \(\text{H}_2\text{O}\) and hydrogen with \(\text{OH}^-\) as appropriate for basic medium, then equalizes the electrons and combines the half-reactions into a single overall equation written with the smallest whole-number coefficients. In that balanced overall equation, what is the coefficient of \(\text{OH}^-\)?$qt47$,
    $op47$[{"label":"A","text":"\\(3\\)"},{"label":"B","text":"\\(12\\)"},{"label":"C","text":"\\(6\\)"},{"label":"D","text":"\\(5\\)"}]$op47$::jsonb,
    'C',
    $ex47$This is a General Chemistry question that falls under the content category 'Stoichiometry (GC)'. The answer to this question is C because separating the disproportionation into half-reactions and balancing in base yields a coefficient of \(6\) on \(\text{OH}^-\). Bromine begins at oxidation state \(0\) in \(\text{Br}_2\). In the reduction half-reaction it falls to \(-1\): \(\text{Br}_2 + 2e^- \rightarrow 2\,\text{Br}^-\). In the oxidation half-reaction it rises to \(+5\); balancing O with water and H with hydroxide in base gives \(\text{Br}_2 + 12\,\text{OH}^- \rightarrow 2\,\text{BrO}_3^- + 6\,\text{H}_2\text{O} + 10e^-\). Multiplying the reduction half-reaction by \(5\) makes both half-reactions exchange \(10e^-\); adding them and cancelling electrons gives \(6\,\text{Br}_2 + 12\,\text{OH}^- \rightarrow 10\,\text{Br}^- + 2\,\text{BrO}_3^- + 6\,\text{H}_2\text{O}\). Dividing every coefficient by \(2\) to reach the smallest whole numbers gives \(3\,\text{Br}_2 + 6\,\text{OH}^- \rightarrow 5\,\text{Br}^- + \text{BrO}_3^- + 3\,\text{H}_2\text{O}\), in which \(\text{OH}^-\) carries a coefficient of \(6\). This balances: Br \(6 = 5 + 1\); O \(6 = 3 + 3\); H \(6 = 6\); and charge \(-6 = -6\) on each side. (Choice A) \(3\) is the coefficient of \(\text{Br}_2\) (and of \(\text{H}_2\text{O}\)) in the final balanced equation, not the coefficient of \(\text{OH}^-\). (Choice B) \(12\) is the \(\text{OH}^-\) coefficient in the combined equation before it is reduced to smallest whole numbers; failing to divide the entire equation by the common factor of \(2\) leaves every coefficient doubled. (Choice D) \(5\) is the coefficient of \(\text{Br}^-\) in the final balanced equation, not the coefficient of \(\text{OH}^-\). Skill 3$ex47$,
    'hard', '4E', $cc47$Stoichiometry (GC)$cc47$, 'general-chemistry', 3, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a47A$reads off the Br2/H2O coefficient instead of the hydroxide coefficient$a47A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a47B$reports the pre-reduction coefficient by omitting the final division to smallest whole numbers$a47B$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a47D$reports the bromide product coefficient instead of the hydroxide coefficient$a47D$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch2_questions FROM questions WHERE topic='Oxidation-Reduction Reactions' AND subtopic IN ('Common Oxidizing & Reducing Agents', 'Balancing Redox (Half-Reaction Method)');
