-- GenChem Ch3 (Bonding & Chemical Interactions) — Batch 4 of 4: Orbitals, Intermolecular Forces & Stereochemistry
-- 24 questions, all confidence >=4 (OpenStax Atoms First 2e; stereochemistry verified vs standard organic conventions); AAMC foundation 5B; cross-batch + cross-chapter deduped, audit clean (PASS, 0 genuine conflicts).
-- Re-runnable. Run the four batches IN ORDER (1->2->3->4) in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Bonding & Chemical Interactions' AND subtopic IN ('Sigma/Pi Bonds & Hybridization', 'Intermolecular Forces', 'Stereochemistry');

-- Q1 [Sigma/Pi Bonds & Hybridization · easy · Skill 1 · general-chemistry · ans A] (g67)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt67$In gaseous beryllium chloride, \(\text{BeCl}_2\), the central beryllium atom forms two \(\text{Be}-\text{Cl}\) bonds and carries no lone pairs. Based on the hybridization of this central atom, the molecule is most likely to adopt which molecular geometry?$qt67$,
    $op67$[{"label":"A","text":"Linear, with a \\(\\text{Cl}-\\text{Be}-\\text{Cl}\\) bond angle of \\(180^\\circ\\), because beryllium is \\(sp\\) hybridized"},{"label":"B","text":"Bent, with a \\(\\text{Cl}-\\text{Be}-\\text{Cl}\\) bond angle near \\(109.5^\\circ\\), because beryllium is \\(sp^3\\) hybridized"},{"label":"C","text":"Trigonal planar, with \\(\\text{Cl}-\\text{Be}-\\text{Cl}\\) bond angles of \\(120^\\circ\\), because beryllium is \\(sp^2\\) hybridized"},{"label":"D","text":"Bent, with a \\(\\text{Cl}-\\text{Be}-\\text{Cl}\\) bond angle near \\(120^\\circ\\), because beryllium is \\(sp^2\\) hybridized"}]$op67$::jsonb,
    'A',
    $ex67$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the number of regions of electron density around the central atom fixes both its hybridization and the molecule's geometry. In \(\text{BeCl}_2\), beryllium is surrounded by exactly two regions of electron density (the two \(\text{Be}-\text{Cl}\) bonding regions) and has no lone pairs. Two electron-density regions require two equivalent hybrid orbitals, formed by mixing one \(s\) and one \(p\) orbital, so beryllium is \(sp\) hybridized. Two \(sp\) hybrid orbitals point in opposite directions to minimize electron–electron repulsion, giving a linear arrangement with a \(\text{Cl}-\text{Be}-\text{Cl}\) bond angle of \(180^\circ\). (Choice B) An \(sp^3\) hybridization with a \(\sim 109.5^\circ\) angle arises from four regions of electron density, not two; assigning four regions to a central atom that has only two bonds and no lone pairs overcounts the electron-density regions. (Choice C) An \(sp^2\) hybridization corresponds to three regions of electron density and yields a trigonal planar shape only when all three regions are bonding; with just two \(\text{Be}-\text{Cl}\) bonds and no lone pairs there are only two regions, so the geometry is not trigonal planar. (Choice D) A bent geometry with a \(\sim 120^\circ\) angle requires three regions of electron density of which one is a lone pair; because beryllium in \(\text{BeCl}_2\) has no lone pair, no region is available to bend the molecule away from linear. Skill 1$ex67$,
    'easy', '5B', $cc67$Nature of molecules and intermolecular interactions$cc67$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a67B$assigns sp3 hybridization and a tetrahedral-derived bent angle to a two-region central atom by overcounting electron-density regions$a67B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a67C$applies the three-region sp2 trigonal planar result to a central atom that has only two bonding regions$a67C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a67D$treats one of only two bonding regions as if accompanied by a lone pair, producing a bent sp2 geometry from a linear case$a67D$ FROM q;

-- Q2 [Sigma/Pi Bonds & Hybridization · medium · Skill 2 · general-chemistry · ans C] (g68)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt68$Ethyne, \(\text{HC}\equiv\text{CH}\), contains a carbon-carbon triple bond and two terminal \(\text{C}-\text{H}\) bonds. How many \(\sigma\) bonds and how many \(\pi\) bonds does this molecule contain?$qt68$,
    $op68$[{"label":"A","text":"\\(2\\) \\(\\sigma\\) bonds and \\(3\\) \\(\\pi\\) bonds"},{"label":"B","text":"\\(3\\) \\(\\sigma\\) bonds and \\(3\\) \\(\\pi\\) bonds"},{"label":"C","text":"\\(3\\) \\(\\sigma\\) bonds and \\(2\\) \\(\\pi\\) bonds"},{"label":"D","text":"\\(5\\) \\(\\sigma\\) bonds and \\(2\\) \\(\\pi\\) bonds"}]$op68$::jsonb,
    'C',
    $ex68$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the \(\text{C}\equiv\text{C}\) triple bond is one \(\sigma\) plus two \(\pi\) bonds, and adding the two \(\text{C}-\text{H}\) single bonds gives \(3\) \(\sigma\) and \(2\) \(\pi\) total. Any single bond between two atoms is always a \(\sigma\) bond formed by head-on orbital overlap; a multiple bond consists of exactly one \(\sigma\) bond plus one \(\pi\) bond for each additional shared pair, where each \(\pi\) bond arises from sideways overlap of unhybridized \(p\) orbitals. In ethyne each carbon is \(sp\) hybridized, using one \(sp\) hybrid for the \(\text{C}-\text{H}\) \(\sigma\) bond and one for the \(\text{C}-\text{C}\) \(\sigma\) bond, leaving two unhybridized \(p\) orbitals on each carbon to form the two \(\pi\) bonds of the triple bond. (Choice A) Counting only the two \(\text{C}-\text{H}\) bonds as \(\sigma\) and assigning all three lines of the triple bond to \(\pi\) bonds gives \(2\) \(\sigma\) and \(3\) \(\pi\), but the first bond of any multiple bond must be a \(\sigma\) bond. (Choice B) Treating the triple bond as three \(\pi\) bonds while still counting three \(\sigma\) bonds double-assigns the central bond, since the triple bond contributes one \(\sigma\) and only two \(\pi\) bonds. (Choice D) Counting every one of the five bond lines as a \(\sigma\) bond in addition to the two \(\pi\) bonds overcounts the framework; the two \(\pi\) bonds are part of the triple bond, not separate from its single \(\sigma\) bond. Skill 2$ex68$,
    'medium', '5B', $cc68$Nature of molecules and intermolecular interactions$cc68$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a68A$Assigns every line of the triple bond to a pi bond, forgetting that the first bond of any multiple bond is always a sigma bond$a68A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a68B$Correctly counts three sigma bonds but treats the triple bond as three pi bonds, double-counting the central sigma as both sigma and pi$a68B$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a68D$Correctly identifies two pi bonds but counts all five bonding lines as sigma bonds, overcounting the sigma framework$a68D$ FROM q;

-- Q3 [Sigma/Pi Bonds & Hybridization · medium · Skill 2 · general-chemistry · ans B] (g69)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt69$At \(25\,^{\circ}\text{C}\), \(cis\text{-}2\text{-butene}\) does not interconvert with \(trans\text{-}2\text{-butene}\), so the two methyl groups stay locked on fixed sides of the \(\text{C}=\text{C}\). Which feature of the double bond is most directly responsible for this restricted rotation?$qt69$,
    $op69$[{"label":"A","text":"The \\(sp^2\\) hybridization of the alkene carbons makes the \\(\\sigma\\) framework itself too rigid to twist."},{"label":"B","text":"Rotation about the \\(\\text{C}=\\text{C}\\) axis would force the two parallel \\(p\\) orbitals out of alignment, breaking the \\(\\pi\\)-bond overlap at a large energy cost."},{"label":"C","text":"The \\(\\sigma\\) bond locks the carbons in place while the \\(\\pi\\) bond freely permits the two ends to rotate relative to each other."},{"label":"D","text":"Steric clash between the two methyl groups, rather than any orbital overlap, prevents the carbons from rotating past each other."}]$op69$::jsonb,
    'B',
    $ex69$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because the \(\pi\) bond is formed by side-on overlap of two parallel unhybridized \(p\) orbitals, and twisting about the \(\text{C}=\text{C}\) axis misaligns those orbitals and destroys the overlap, which costs roughly the energy of the \(\pi\) bond and therefore blocks rotation at ordinary temperatures. In a \(\text{C}=\text{C}\) double bond the first bond is a \(\sigma\) bond (cylindrically symmetric about the internuclear axis, so it alone would allow free rotation) and the second is a \(\pi\) bond whose two lobes lie above and below the molecular plane; because intact \(\pi\) overlap demands that the \(p\) orbitals stay parallel, the four substituents on the two alkene carbons are held coplanar and the \(cis\)/\(trans\) arrangement is locked in. (Choice A) The \(sp^2\) hybridization fixes the trigonal-planar geometry and the bond angles, but a single \(\sigma\) bond between \(sp^2\) carbons (as in a \(\text{C}-\text{C}\) single bond) permits essentially free rotation; \(\sigma\) symmetry does not by itself restrict twisting, so hybridization is not the direct cause. (Choice C) This reverses the roles of the two bonds: the \(\sigma\) bond is the one whose cylindrical symmetry would allow rotation, whereas it is the \(\pi\) bond that resists it, so attributing the locking to \(\sigma\) and free rotation to \(\pi\) inverts the actual relationship. (Choice D) Although the methyl groups do experience some steric interaction, restricted rotation about \(\text{C}=\text{C}\) arises even in simple alkenes with no bulky substituents, so the barrier is the energetic cost of breaking \(\pi\) overlap rather than steric clash. Skill 2$ex69$,
    'medium', '5B', $cc69$Nature of molecules and intermolecular interactions$cc69$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a69A$sp2-sigma-framework-credited-for-rigidity$a69A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a69C$sigma-restricts-pi-rotates role swap$a69C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a69D$steric-clash-substituted-for-pi-overlap-barrier$a69D$ FROM q;

-- Q4 [Sigma/Pi Bonds & Hybridization · easy · Skill 1 · general-chemistry · ans D] (g70)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt70$In gaseous boron trichloride \(\text{BCl}_3\), the central boron atom forms three bonds to chlorine and carries no lone pairs. Which hybridization is most consistent with this bonding arrangement on boron?$qt70$,
    $op70$[{"label":"A","text":"\\(sp^3d\\)"},{"label":"B","text":"\\(sp\\)"},{"label":"C","text":"\\(sp^3\\)"},{"label":"D","text":"\\(sp^2\\)"}]$op70$::jsonb,
    'D',
    $ex70$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the boron atom in \(\text{BCl}_3\) is surrounded by three bonding regions and no lone pairs, giving three regions of electron density. Three electron regions are accommodated by mixing one \(s\) orbital with two \(p\) orbitals to form three equivalent \(sp^2\) hybrid orbitals, which point toward the corners of a trigonal-planar arrangement with \(\text{Cl-B-Cl}\) angles of about \(120^\circ\). (Choice A) \(sp^3d\) hybridization corresponds to five regions of electron density, more than the three present on boron. (Choice B) \(sp\) hybridization corresponds to only two regions of electron density, fewer than the three bonding regions on boron. (Choice C) \(sp^3\) hybridization corresponds to four regions of electron density; boron has only three bonds and no lone pairs, so a fourth region is not present. Skill 1$ex70$,
    'easy', '5B', $cc70$Nature of molecules and intermolecular interactions$cc70$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'scale_unit_error', $a70A$Overcounts electron regions, assigning a higher hybridization than the three regions present$a70A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a70B$Undercounts electron regions, treating the molecule as having only two bonding regions$a70B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a70C$Defaults to the more familiar four-region sp3 case despite boron having only three bonds and no lone pairs$a70C$ FROM q;

-- Q5 [Sigma/Pi Bonds & Hybridization · hard · Skill 2 · general-chemistry · ans A] (g71)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt71$In acetamide, \(\text{CH}_3\text{-C(=O)-NH}_2\), the methyl carbon forms only single bonds while the carbonyl carbon carries the \(\text{C=O}\) double bond. What is the hybridization of the methyl carbon and the carbonyl carbon, respectively?$qt71$,
    $op71$[{"label":"A","text":"Methyl C is \\(sp^3\\); carbonyl C is \\(sp^2\\)"},{"label":"B","text":"Methyl C is \\(sp^2\\); carbonyl C is \\(sp^3\\)"},{"label":"C","text":"Methyl C is \\(sp^3\\); carbonyl C is \\(sp^3\\)"},{"label":"D","text":"Methyl C is \\(sp^3\\); carbonyl C is \\(sp\\)"}]$op71$::jsonb,
    'A',
    $ex71$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the methyl carbon has four single-bond electron domains (\(sp^3\)) while the carbonyl carbon has three electron domains around a \(\text{C=O}\) double bond (\(sp^2\)). Hybridization is set by the number of sigma-bond plus lone-pair domains on an atom: the methyl carbon forms three \(\text{C-H}\) sigma bonds and one \(\text{C-C}\) sigma bond for four domains, requiring four equivalent \(sp^3\) hybrids in a tetrahedral arrangement; the carbonyl carbon forms three sigma bonds (to \(\text{CH}_3\), to \(\text{N}\), and to \(\text{O}\)) plus one pi bond to oxygen, and because the pi bond uses an unhybridized \(p\) orbital rather than a hybrid orbital, only the three sigma domains count, giving \(sp^2\) trigonal planar geometry. (Choice B) reverses the assignments, placing \(sp^2\) on the carbon with four single bonds and \(sp^3\) on the carbon bearing the double bond, which contradicts the domain count for each center. (Choice C) treats the carbonyl carbon as \(sp^3\) by overlooking that a \(\text{C=O}\) double bond reduces the number of hybrid-orbital domains to three. (Choice D) counts the pi bond of the \(\text{C=O}\) double bond as an additional hybridized electron domain, yielding two domains and \(sp\); however, the pi bond resides in an unhybridized \(p\) orbital and does not add a hybrid domain, so the carbonyl carbon remains \(sp^2\). Skill 2$ex71$,
    'hard', '5B', $cc71$Nature of molecules and intermolecular interactions$cc71$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a71B$Swaps the sp3/sp2 assignments between the single-bonded carbon and the double-bonded carbon$a71B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a71C$Assigns sp3 to every carbon, ignoring that a C=O double bond lowers the carbonyl carbon to sp2$a71C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a71D$Counts the pi bond as a separate hybrid electron domain, over-reducing the carbonyl carbon to sp$a71D$ FROM q;

-- Q6 [Sigma/Pi Bonds & Hybridization · medium · Skill 2 · general-chemistry · ans B] (g72)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt72$Hydrogen cyanide has the connectivity \(\text{H}-\text{C}\equiv\text{N}\), so its carbon atom is bonded to a hydrogen and triple-bonded to nitrogen and bears no lone pairs. Applying valence bond theory to this carbon, its hybridization and the geometric arrangement of the atoms around it are most likely$qt72$,
    $op72$[{"label":"A","text":"\\(sp^2\\) hybridized, with a trigonal planar arrangement and an \\(\\text{H}-\\text{C}-\\text{N}\\) angle near \\(120^\\circ\\)."},{"label":"B","text":"\\(sp\\) hybridized, with a linear arrangement and an \\(\\text{H}-\\text{C}-\\text{N}\\) angle of \\(180^\\circ\\)."},{"label":"C","text":"\\(sp^3\\) hybridized, with a tetrahedral arrangement and an \\(\\text{H}-\\text{C}-\\text{N}\\) angle near \\(109.5^\\circ\\)."},{"label":"D","text":"\\(sp\\) hybridized, with a bent arrangement and an \\(\\text{H}-\\text{C}-\\text{N}\\) angle near \\(120^\\circ\\)."}]$op72$::jsonb,
    'B',
    $ex72$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because the carbon in hydrogen cyanide has only two regions of electron density: one \(\sigma\) bond to hydrogen and one \(\sigma\) bond to nitrogen (the triple bond \(\text{C}\equiv\text{N}\) counts as a single region, comprising one \(\sigma\) and two \(\pi\) bonds), with no lone pairs on carbon. In valence bond theory, two electron domains require two equivalent hybrid orbitals, which are formed by mixing one \(s\) and one \(p\) atomic orbital to give two \(sp\) hybrids; the two remaining unhybridized \(p\) orbitals on carbon form the two \(\pi\) bonds of the triple bond. Two \(sp\) hybrids orient \(180^\circ\) apart to minimize electron-pair repulsion, producing a linear arrangement, so the \(\text{H}-\text{C}-\text{N}\) atoms lie in a straight line at \(180^\circ\). (Choice A) Trigonal planar geometry and \(sp^2\) hybridization arise from three regions of electron density, but counting three domains on this carbon overcounts the single \(\text{C}\equiv\text{N}\) region as more than one, so the \(\sim120^\circ\) angle does not apply. (Choice C) Tetrahedral geometry with \(sp^3\) hybridization corresponds to four electron domains; treating each of the three bonds within the triple bond as a separate region inflates the domain count to four and incorrectly yields \(\sim109.5^\circ\). (Choice D) The \(sp\) hybridization is correctly identified, but a bent shape with a \(\sim120^\circ\) angle would require a lone pair or additional domain on carbon to compress the geometry; carbon here has no lone pair, so two \(sp\) hybrids remain \(180^\circ\) apart and the arrangement is linear, not bent. Skill 2$ex72$,
    'medium', '5B', $cc72$Nature of molecules and intermolecular interactions$cc72$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a72A$triple bond miscounted as two electron regions, giving three domains and sp2 trigonal planar$a72A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a72C$each of the three bonds in the triple bond counted as a separate domain, giving four domains and sp3 tetrahedral$a72C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a72D$correct sp hybridization paired with an invented lone pair that bends the geometry to ~120 degrees$a72D$ FROM q;

-- Q7 [Sigma/Pi Bonds & Hybridization · medium · Skill 2 · general-chemistry · ans C] (g73)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt73$Formaldehyde, \(\text{H}_2\text{C}=\text{O}\), has both \(\text{C}-\text{H}\) bonds and the \(\text{C}=\text{O}\) bond emanating from a single \(sp^2\) carbon. Counting every bond in the molecule, which tally of sigma and pi bonds is correct?$qt73$,
    $op73$[{"label":"A","text":"\\(2\\) sigma bonds and \\(2\\) pi bonds"},{"label":"B","text":"\\(4\\) sigma bonds and \\(0\\) pi bonds"},{"label":"C","text":"\\(3\\) sigma bonds and \\(1\\) pi bond"},{"label":"D","text":"\\(1\\) sigma bond and \\(3\\) pi bonds"}]$op73$::jsonb,
    'C',
    $ex73$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because each of the two \(\text{C}-\text{H}\) single bonds is one sigma bond, and the \(\text{C}=\text{O}\) double bond consists of one sigma bond plus one pi bond, giving \(3\) sigma and \(1\) pi total. Any single covalent bond is a sigma bond formed by head-on orbital overlap; a double bond is one sigma bond plus one pi bond, where the pi bond arises from side-on overlap of the unhybridized \(p\) orbitals on carbon and oxygen, so the molecule contains \(2 + 1 = 3\) sigma bonds and exactly \(1\) pi bond. (Choice A) Counting \(2\) sigma and \(2\) pi treats only the double bond as the source of sigma bonds and assigns the \(\text{C}-\text{H}\) bonds to the pi category, but single bonds are always sigma bonds, not pi bonds. (Choice B) Counting \(4\) sigma and \(0\) pi correctly identifies four bonding connections as containing a sigma component but ignores the pi bond that must accompany the sigma bond within the \(\text{C}=\text{O}\) double bond. (Choice D) Counting \(1\) sigma and \(3\) pi reverses the roles of single and multiple bonds, treating each line in the structure as a pi bond and recognizing only one sigma bond, whereas every bond has a sigma component and only the double bond adds a pi. Skill 2$ex73$,
    'medium', '5B', $cc73$Nature of molecules and intermolecular interactions$cc73$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a73A$Counts the pi bond from the double bond but miscounts single bonds as pi bonds, keeping only the double bond's sigma$a73A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a73B$Counts every bonding connection as sigma but omits the additional pi bond inside the C=O double bond$a73B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a73D$Reverses sigma/pi roles, treating single bonds as pi and recognizing only one sigma bond$a73D$ FROM q;

-- Q8 [Sigma/Pi Bonds & Hybridization · hard · Skill 2 · general-chemistry · ans D] (g74)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Sigma/Pi Bonds & Hybridization',
    $qt74$Acetonitrile has the connectivity \( \text{H}_3\text{C-C} \equiv \text{N} \), in which a methyl carbon is single-bonded to a second carbon that is triple-bonded to a terminal nitrogen. Counting every bond in the molecule, how many \( \sigma \) (sigma) bonds and how many \( \pi \) (pi) bonds does acetonitrile contain?$qt74$,
    $op74$[{"label":"A","text":"\\( 4\\ \\sigma \\) bonds and \\( 3\\ \\pi \\) bonds"},{"label":"B","text":"\\( 6\\ \\sigma \\) bonds and \\( 2\\ \\pi \\) bonds"},{"label":"C","text":"\\( 5\\ \\sigma \\) bonds and \\( 3\\ \\pi \\) bonds"},{"label":"D","text":"\\( 5\\ \\sigma \\) bonds and \\( 2\\ \\pi \\) bonds"}]$op74$::jsonb,
    'D',
    $ex74$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because every single bond is one \( \sigma \) bond, and a triple bond is always one \( \sigma \) bond plus two \( \pi \) bonds. In acetonitrile the three C-H bonds contribute three \( \sigma \) bonds, the \( \text{C-C} \) single bond contributes one \( \sigma \) bond, and the \( \text{C} \equiv \text{N} \) triple bond contributes one \( \sigma \) bond and two \( \pi \) bonds, for a total of \( 3 + 1 + 1 = 5\ \sigma \) bonds and \( 2\ \pi \) bonds. The OpenStax treatment of valence bond theory specifies that the first bond between two atoms is always a \( \sigma \) bond (end-to-end orbital overlap) and that any additional bonds in a multiple bond are \( \pi \) bonds (side-by-side overlap of unhybridized p orbitals); a triple bond is therefore one \( \sigma \) and two \( \pi \). (Choice A) This counts the \( \text{C} \equiv \text{N} \) triple bond as three \( \pi \) bonds and drops one \( \sigma \) bond, which contradicts the rule that the first bond of any multiple bond is a \( \sigma \) bond, so a triple bond is one \( \sigma \) plus two \( \pi \), not three \( \pi \). (Choice B) This treats the connectivity as containing a separate \( \text{C-N} \) linkage in addition to the \( \text{C} \equiv \text{N} \) triple bond, double-counting one \( \sigma \) bond; the triple bond's single \( \sigma \) component is the only carbon-nitrogen \( \sigma \) bond present. (Choice C) This correctly tallies the five \( \sigma \) bonds but assigns three \( \pi \) bonds to the triple bond, whereas a triple bond contains exactly two \( \pi \) bonds because only two unhybridized p orbitals on each atom are available for side-by-side overlap. Skill 2$ex74$,
    'hard', '5B', $cc74$Nature of molecules and intermolecular interactions$cc74$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a74A$treats a triple bond as three pi bonds and loses a sigma bond$a74A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a74B$double-counts a carbon-nitrogen sigma bond separate from the triple bond$a74B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a74C$correct sigma count but assigns three pi bonds to the triple bond$a74C$ FROM q;

-- Q9 [Intermolecular Forces · easy · Skill 1 · general-chemistry · ans A] (g75)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt75$In liquid hydrogen fluoride, \(\text{HF}\), each molecule holds one \(\text{H}\) atom bonded directly to \(\text{F}\). Which intermolecular force most likely dominates the attractions between neighboring \(\text{HF}\) molecules?$qt75$,
    $op75$[{"label":"A","text":"Hydrogen bonding, because \\(\\text{H}\\) is bonded to the highly electronegative \\(\\text{F}\\) atom"},{"label":"B","text":"Dipole-dipole attraction, with no hydrogen bonding present because \\(\\text{HF}\\) has only one \\(\\text{H}\\) atom"},{"label":"C","text":"London dispersion forces, because \\(\\text{HF}\\) is a small, easily polarizable molecule"},{"label":"D","text":"Hydrogen bonding, because the \\(\\text{H}\\)-\\(\\text{F}\\) covalent bond itself links one molecule to the next"}]$op75$::jsonb,
    'A',
    $ex75$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the \(\text{H}\) atom in \(\text{HF}\) is bonded to fluorine, one of the three highly electronegative atoms (\(\text{N}\), \(\text{O}\), \(\text{F}\)) whose direct bond to hydrogen produces hydrogen bonding. A hydrogen bond is the strong attraction between an \(\text{H}\) covalently bonded to \(\text{N}\), \(\text{O}\), or \(\text{F}\) and a lone pair on an electronegative atom of a neighboring molecule; the large \(\Delta\text{EN}\) of the \(\text{H}-\text{F}\) bond leaves the \(\text{H}\) strongly partially positive and the \(\text{F}\) strongly partially negative with available lone pairs, so the dominant attraction between \(\text{HF}\) molecules is hydrogen bonding, which is far stronger than ordinary dipole-dipole or dispersion attractions in a molecule this small. (Choice B) Dipole-dipole attraction is present in \(\text{HF}\), but hydrogen bonding is a specific, much stronger subset of dipole-dipole interaction that occurs precisely because \(\text{H}\) is bonded to \(\text{F}\); having only one \(\text{H}\) per molecule does not prevent hydrogen bonding, so naming plain dipole-dipole as dominant understates the controlling force. (Choice C) London dispersion forces act in every molecule but are weak for a small molecule like \(\text{HF}\) and are overwhelmed by the much stronger hydrogen bonding arising from the \(\text{H}-\text{F}\) bond. (Choice D) Hydrogen bonding is correctly named, but it is an intermolecular attraction between separate molecules, not the intramolecular \(\text{H}-\text{F}\) covalent bond that holds a single molecule together. Skill 1$ex75$,
    'easy', '5B', $cc75$Nature of molecules and intermolecular interactions$cc75$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a75B$plain dipole-dipole named as dominant while hydrogen bonding is denied on the false ground of a single H atom$a75B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a75C$London dispersion treated as dominant in a small molecule that hydrogen bonds$a75C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a75D$intramolecular H-F covalent bond confused with the intermolecular hydrogen bond$a75D$ FROM q;

-- Q10 [Intermolecular Forces · medium · Skill 2 · general-chemistry · ans D] (g76)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt76$A flask holds a mixture of the monatomic noble gases \(\text{He}\), \(\text{Ne}\), \(\text{Ar}\), and \(\text{Xe}\), where the only operative intermolecular force is London dispersion. Ranking these gases from lowest to highest normal boiling point most likely gives which order?$qt76$,
    $op76$[{"label":"A","text":"\\(\\text{Xe} < \\text{Ar} < \\text{Ne} < \\text{He}\\)"},{"label":"B","text":"\\(\\text{Ne} < \\text{He} < \\text{Ar} < \\text{Xe}\\)"},{"label":"C","text":"\\(\\text{He} < \\text{Ne} < \\text{Xe} < \\text{Ar}\\)"},{"label":"D","text":"\\(\\text{He} < \\text{Ne} < \\text{Ar} < \\text{Xe}\\)"}]$op76$::jsonb,
    'D',
    $ex76$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because boiling point rises with the strength of London dispersion forces, and dispersion strength increases with atomic size and polarizability in the order \(\text{He} < \text{Ne} < \text{Ar} < \text{Xe}\). For nonpolar monatomic species, the only intermolecular attraction available is the London dispersion force, which arises from instantaneous, fluctuating dipoles in the electron cloud. A larger atom holds more electrons in a larger, more loosely held cloud, so it is more polarizable; this produces stronger instantaneous induced dipoles, greater interatomic attraction, and a higher temperature required to overcome those attractions and boil. Down the noble-gas series \(\text{He} \to \text{Ne} \to \text{Ar} \to \text{Xe}\), atomic radius and electron count both grow, so dispersion strength and therefore boiling point increase monotonically. (Choice A) This is the exact reverse of the correct trend, treating the smallest, least polarizable atom as having the strongest dispersion forces and highest boiling point. (Choice B) This places \(\text{Ne}\) below \(\text{He}\), which inverts the size/polarizability relationship for that pair while keeping the rest of the order intact; \(\text{Ne}\) is larger and more polarizable than \(\text{He}\) and therefore boils higher. (Choice C) This swaps \(\text{Ar}\) and \(\text{Xe}\), ranking the smaller \(\text{Ar}\) above the larger \(\text{Xe}\); because \(\text{Xe}\) has the most electrons and the greatest polarizability, it has the strongest dispersion forces and the highest boiling point. Skill 2$ex76$,
    'medium', '5B', $cc76$Nature of molecules and intermolecular interactions$cc76$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a76A$Inverts the polarizability-boiling point relationship, ranking the smallest atom highest$a76A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a76B$Confuses relative size/polarizability of the He-Ne pair, placing the smaller atom above the larger$a76B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a76C$Correct general trend but transposes the two heaviest atoms (Ar above Xe)$a76C$ FROM q;

-- Q11 [Intermolecular Forces · medium · Skill 2 · general-chemistry · ans B] (g77)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt77$Chloromethane \(\text{CH}_3\text{Cl}\) (molar mass \(50.5\ \text{g/mol}\)) boils at \(-24\,^\circ\text{C}\), well above propane \(\text{C}_3\text{H}_8\) (molar mass \(44\ \text{g/mol}\)) at \(-42\,^\circ\text{C}\). Given that neither molecule has hydrogen bonded to N, O, or F, which intermolecular force accounts for the elevated boiling point of \(\text{CH}_3\text{Cl}\)?$qt77$,
    $op77$[{"label":"A","text":"Hydrogen bonding, because the C–H bonds in \\(\\text{CH}_3\\text{Cl}\\) act as hydrogen-bond donors to the chlorine lone pairs of neighboring molecules"},{"label":"B","text":"Dipole–dipole forces, because the net molecular dipole of \\(\\text{CH}_3\\text{Cl}\\) lets neighboring molecules align oppositely-charged ends, adding attraction beyond dispersion alone"},{"label":"C","text":"London dispersion forces, because the larger, more polarizable electron cloud of \\(\\text{CH}_3\\text{Cl}\\) is the only force present in both molecules"},{"label":"D","text":"Ion–dipole forces, because the polar C–Cl bond places a full negative charge on chlorine that attracts the partial positive ends of neighbors"}]$op77$::jsonb,
    'B',
    $ex77$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because \(\text{CH}_3\text{Cl}\) is a polar molecule whose permanent net dipole permits dipole-dipole attraction between molecules, an extra cohesive force that nonpolar propane lacks. Both molecules experience London dispersion forces of roughly comparable strength given their similar molar masses, so dispersion cannot explain the higher boiling point; the difference comes from the additional dipole-dipole attraction in \(\text{CH}_3\text{Cl}\), where the polar \(\text{C-Cl}\) bond produces a molecular dipole pointing toward chlorine, letting the partial-negative \(\text{Cl}\) end of one molecule align with the partial-positive end of a neighbor and raising the energy needed to separate molecules into the gas phase. (Choice A) Hydrogen bonding requires hydrogen covalently bonded to N, O, or F; \(\text{CH}_3\text{Cl}\) has only \(\text{C-H}\) bonds, so it cannot serve as a hydrogen-bond donor regardless of chlorine's lone pairs. (Choice C) London dispersion forces are present in both molecules and are similar in magnitude here because the molar masses are close, so dispersion alone does not distinguish the two boiling points; it ignores the permanent dipole unique to the polar molecule. (Choice D) Ion-dipole forces require an actual ion, but the \(\text{C-Cl}\) bond is polar covalent and bears only a partial negative charge on chlorine, not a full ionic charge, so no ion-dipole interaction exists between neutral \(\text{CH}_3\text{Cl}\) molecules. Skill 2$ex77$,
    'medium', '5B', $cc77$Nature of molecules and intermolecular interactions$cc77$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a77A$Treats polar C–H bonds adjacent to an electronegative atom as capable of hydrogen bonding, ignoring the strict N/O/F-H donor requirement$a77A$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a77C$Correctly identifies dispersion as present in both molecules but wrongly concludes it is the distinguishing force, overlooking the permanent dipole$a77C$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a77D$Upgrades a partial charge on a polar covalent bond to a full ionic charge, invoking ion–dipole forces where only dipole–dipole applies$a77D$ FROM q;

-- Q12 [Intermolecular Forces · medium · Skill 2 · general-chemistry · ans C] (g78)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt78$Water (\(\text{H}_2\text{O}\), molar mass \(18\ \text{g/mol}\)) boils at \(100\,^\circ\text{C}\), whereas the heavier \(\text{H}_2\text{S}\) (molar mass \(34\ \text{g/mol}\)) boils at \(-60\,^\circ\text{C}\). Given that both are bent molecules, the dominant intermolecular force that most likely accounts for water's far higher boiling point is$qt78$,
    $op78$[{"label":"A","text":"stronger London dispersion forces in \\(\\text{H}_2\\text{O}\\), because its lower molar mass concentrates its electron cloud and raises its polarizability."},{"label":"B","text":"a more polar S-H bond than O-H bond, which gives \\(\\text{H}_2\\text{S}\\) dipole-dipole forces that water lacks."},{"label":"C","text":"hydrogen bonding between water molecules, made possible because H is bonded to the small, highly electronegative O atom."},{"label":"D","text":"the higher molar mass of \\(\\text{H}_2\\text{S}\\), which increases its dipole-dipole attractions above those of \\(\\text{H}_2\\text{O}\\)."}]$op78$::jsonb,
    'C',
    $ex78$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the O-H bonds of water let each molecule hydrogen bond through H attached to a small, highly electronegative O, an interaction far stronger than any force available to \(\text{H}_2\text{S}\). Hydrogen bonding requires an H atom covalently bonded to N, O, or F; oxygen's high electronegativity and small atomic radius create a large bond dipole and allow close approach of the partially positive H to a lone pair on a neighboring O, producing an exceptionally strong dipole-dipole attraction. Sulfur is much less electronegative and larger, so \(\text{H}_2\text{S}\) cannot hydrogen bond and is held together mainly by weak dipole-dipole and dispersion forces; this is why water boils \(160\,^\circ\text{C}\) higher despite being the lighter molecule, since hydrogen bonding overwhelms the modest rise in dispersion forces expected from greater molar mass. (Choice A) London dispersion forces increase with greater molar mass and a larger, more polarizable electron cloud, so the heavier \(\text{H}_2\text{S}\) actually has stronger dispersion forces than \(\text{H}_2\text{O}\); a lower molar mass does not concentrate the electron cloud to raise polarizability. (Choice B) The S-H bond is less polar than the O-H bond because sulfur is less electronegative than oxygen, so this misstates the relative bond polarity and incorrectly denies that the more polar molecule, water, has dipole-dipole forces. (Choice D) Higher molar mass strengthens dispersion forces rather than dipole-dipole attractions, and even so the increase does not exceed water's hydrogen bonding; attributing water's higher boiling point to a property that favors \(\text{H}_2\text{S}\) reverses the actual trend. Skill 2$ex78$,
    'medium', '5B', $cc78$Nature of molecules and intermolecular interactions$cc78$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a78A$lower molar mass claimed to raise polarizability and dispersion strength$a78A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a78B$S-H asserted as more polar than O-H, reversing the electronegativity order$a78B$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a78D$molar mass treated as boosting dipole-dipole rather than dispersion forces$a78D$ FROM q;

-- Q13 [Intermolecular Forces · hard · Skill 2 · general-chemistry · ans A] (g79)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt79$A sealed flask of liquid \(\text{H}_2\text{O}\) is cooled until it freezes solid, and the resulting ice (density \(\approx 0.92\ \text{g/cm}^3\)) is observed to float in the remaining liquid water (density \(\approx 1.0\ \text{g/cm}^3\)). Given that hydrogen bonding dominates the intermolecular interactions in both phases, the lower density of the solid is best explained by which structural consequence of those hydrogen bonds?$qt79$,
    $op79$[{"label":"A","text":"On freezing, hydrogen bonds lock the \\(\\text{H}_2\\text{O}\\) molecules into a more open arrangement that spaces them farther apart than in the liquid."},{"label":"B","text":"On freezing, hydrogen bonds add extra bonding mass to each \\(\\text{H}_2\\text{O}\\) molecule without changing how the molecules are spaced."},{"label":"C","text":"On freezing, hydrogen bonds draw the \\(\\text{H}_2\\text{O}\\) molecules into closer contact so they pack more tightly than in the liquid."},{"label":"D","text":"On freezing, the slowing of molecular motion lets the \\(\\text{H}_2\\text{O}\\) molecules settle closer together, an effect hydrogen bonds do not oppose."}]$op79$::jsonb,
    'A',
    $ex79$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because, as OpenStax describes for water, the extensive hydrogen bonding present in ice holds the \(\text{H}_2\text{O}\) molecules in a more open arrangement than exists in the liquid; spacing the molecules farther apart spreads the same mass over a larger volume, so the solid has a lower density (about \(0.92\ \text{g/cm}^3\)) than the liquid (about \(1.0\ \text{g/cm}^3\)) and floats. Density is mass per unit volume, so the lower density of ice must come from the molecules occupying more space, not from any change in the molecules' mass. (Choice B) A hydrogen bond is an intermolecular attraction between an \(\text{H}\) bonded to \(\text{N}\), \(\text{O}\), or \(\text{F}\) and a lone pair on a neighboring electronegative atom; it does not add mass to a molecule, and because the molecular mass is unchanged on freezing, an unchanged spacing would leave the density unchanged rather than lowered. (Choice C) This inverts the actual structural effect: hydrogen bonding in ice produces a more open, not a more tightly packed, arrangement, and closer packing would raise the density above that of the liquid, making the solid sink rather than float. (Choice D) Although molecular motion does slow on freezing, in most substances closer packing in the solid does raise density above the liquid; for water the hydrogen bonds specifically resist this by holding the molecules in the open arrangement, which is precisely why ice is less dense than liquid water. Skill 2$ex79$,
    'hard', '5B', $cc79$Nature of molecules and intermolecular interactions$cc79$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a79B$hydrogen-bonds-add-mass-not-volume$a79B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a79C$hydrogen-bonding-causes-tighter-packing$a79C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a79D$slowed-motion-closer-packing-ignoring-open-lattice$a79D$ FROM q;

-- Q14 [Intermolecular Forces · easy · Skill 1 · general-chemistry · ans D] (g80)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt80$In liquid water, each \(\text{H}_2\text{O}\) molecule is attracted to neighboring \(\text{H}_2\text{O}\) molecules through hydrogen bonding. What is the nature of the hydrogen bond linking one water molecule to the next?$qt80$,
    $op80$[{"label":"A","text":"A covalent bond, in which the hydrogen of one \\(\\text{H}_2\\text{O}\\) shares an electron pair with the oxygen of the adjacent \\(\\text{H}_2\\text{O}\\)."},{"label":"B","text":"An ionic bond, formed by complete transfer of an electron from the hydrogen of one \\(\\text{H}_2\\text{O}\\) to the oxygen of the adjacent \\(\\text{H}_2\\text{O}\\)."},{"label":"C","text":"A nonpolar London dispersion interaction arising from momentary fluctuations in the electron clouds of the two \\(\\text{H}_2\\text{O}\\) molecules."},{"label":"D","text":"An intermolecular electrostatic attraction between the partially positive H of one \\(\\text{H}_2\\text{O}\\) and a lone pair on the partially negative O of the adjacent \\(\\text{H}_2\\text{O}\\)."}]$op80$::jsonb,
    'D',
    $ex80$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because a hydrogen bond is an intermolecular electrostatic attraction between a partially positive H (bonded to N, O, or F) on one molecule and a lone pair on a partially negative N, O, or F on another molecule, not a shared-electron-pair bond. Within each \(\text{H}_2\text{O}\), the large electronegativity difference between O and H makes the O-H bonds polar, leaving each H with a partial positive charge (\(\delta^+\)) and the O with a partial negative charge (\(\delta^-\)); the \(\delta^+\) hydrogen of one molecule is then drawn to a lone pair on the \(\delta^-\) oxygen of a neighbor, which is simply a strong dipole-type attraction between separate molecules rather than a new chemical bond holding atoms together within a molecule. (Choice A) Hydrogen bonding does not share an electron pair between the two molecules; the H retains its covalent bond to its own oxygen, and the attraction to the neighboring oxygen is an intermolecular force, not a covalent bond. (Choice B) No electron is transferred and no ions are produced between the two water molecules; the interaction is a partial-charge attraction between intact neutral molecules, not an ionic bond. (Choice C) London dispersion forces stem from instantaneous, induced dipoles in nonpolar regions and are far weaker than hydrogen bonding, which instead relies on the permanent O-H bond dipoles and the oxygen lone pair. Skill 1$ex80$,
    'easy', '5B', $cc80$Nature of molecules and intermolecular interactions$cc80$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a80A$hydrogen bond treated as a covalent shared-electron-pair bond between molecules$a80A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a80B$hydrogen bond mislabeled as an ionic bond from full electron transfer$a80B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a80C$hydrogen bond confused with the weaker London dispersion intermolecular force$a80C$ FROM q;

-- Q15 [Intermolecular Forces · hard · Skill 2 · general-chemistry · ans B] (g81)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt81$Decane (\(\text{C}_{10}\text{H}_{22}\), a nonpolar straight-chain alkane) boils at \(174\,^\circ\text{C}\), whereas the polar molecule chloromethane (\(\text{CH}_3\text{Cl}\)) boils at \(-24\,^\circ\text{C}\). What most likely accounts for the far higher boiling point of the nonpolar species?$qt81$,
    $op81$[{"label":"A","text":"Decane molecules engage in hydrogen bonding through their many C-H bonds, which chloromethane cannot do."},{"label":"B","text":"Decane's much larger, more polarizable electron cloud produces London dispersion forces that exceed the dipole-dipole attractions in chloromethane."},{"label":"C","text":"Chloromethane is held together by weak ionic attractions between \\(\\text{C}\\) and \\(\\text{Cl}\\), which break more easily than decane's covalent bonds."},{"label":"D","text":"Because chloromethane is polar, its permanent dipole always generates stronger total intermolecular attraction than any dispersion force, so its higher boiling point reflects experimental error."}]$op81$::jsonb,
    'B',
    $ex81$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because decane's large, extended electron cloud is highly polarizable, generating London dispersion forces strong enough to outweigh the permanent dipole-dipole attraction in the much smaller chloromethane. London dispersion forces arise from instantaneous, induced dipoles and scale with molecular size and polarizability; a \(\text{C}_{10}\) alkane has far more electrons and surface area for transient dipoles than \(\text{CH}_3\text{Cl}\), so even though it lacks a permanent dipole, the cumulative dispersion attraction dominates and raises the boiling point well above that of the smaller polar molecule. (Choice A) Hydrogen bonding requires \(\text{H}\) bonded to \(\text{N}\), \(\text{O}\), or \(\text{F}\); C-H bonds are nonpolar and do not participate in hydrogen bonding, so this attraction is not present in decane. (Choice C) The \(\text{C-Cl}\) bond in chloromethane is a polar covalent bond, not an ionic attraction, and intermolecular forces (not the intramolecular bonds) are what break during boiling, so this misidentifies both the bonding and the process. (Choice D) A permanent dipole does not guarantee a larger total attraction; dispersion forces can exceed dipole-dipole forces when one molecule is much larger and more polarizable, so the data reflect real physical behavior rather than error. Skill 2$ex81$,
    'hard', '5B', $cc81$Nature of molecules and intermolecular interactions$cc81$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a81A$Believing C-H bonds enable hydrogen bonding$a81A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a81C$Mistaking a polar covalent bond for an ionic attraction and conflating intramolecular bonds with intermolecular forces$a81C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a81D$Asserting permanent dipoles always outweigh dispersion forces$a81D$ FROM q;

-- Q16 [Intermolecular Forces · medium · Skill 2 · general-chemistry · ans C] (g82)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Intermolecular Forces',
    $qt82$The diatomic halogens \(\text{F}_2\), \(\text{Cl}_2\), \(\text{Br}_2\), and \(\text{I}_2\) are all nonpolar. At \(1\,\text{atm}\), which one has the highest normal boiling point, and why?$qt82$,
    $op82$[{"label":"A","text":"\\(\\text{F}_2\\), because fluorine is the most electronegative halogen and therefore holds its electrons most tightly, giving the strongest intermolecular attractions."},{"label":"B","text":"\\(\\text{Cl}_2\\), because the small \\(\\Delta\\text{EN}\\) within the molecule produces dipole-dipole forces that peak near the middle of the group."},{"label":"C","text":"\\(\\text{I}_2\\), because its large, easily polarized electron cloud gives the strongest London dispersion forces among the four."},{"label":"D","text":"\\(\\text{I}_2\\), because its high molar mass is itself the property that determines the strength of the intermolecular forces."}]$op82$::jsonb,
    'C',
    $ex82$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because \(\text{I}_2\) has the largest, most easily distorted electron cloud, so it experiences the strongest London dispersion forces and thus the highest boiling point. All four halogens are homonuclear and nonpolar, so the only intermolecular force available is London dispersion; the strength of dispersion forces rises with polarizability, which increases with the size of the electron cloud, so the boiling points climb in the order \(\text{F}_2 < \text{Cl}_2 < \text{Br}_2 < \text{I}_2\) (from roughly \(-188\,^\circ\text{C}\) to about \(+184\,^\circ\text{C}\)). (Choice A) Electronegativity governs polarity within a heteronuclear bond, not the attraction between identical nonpolar molecules, and tighter electron binding lowers polarizability, so this reasoning predicts the boiling-point trend in the reverse of the observed direction. (Choice B) A homonuclear \(\text{Cl}_2\) molecule has \(\Delta\text{EN}=0\) and no net molecular dipole, so dipole-dipole forces do not operate between \(\text{Cl}_2\) molecules at all. (Choice D) The heaviest halogen does have the highest boiling point, but molar mass only correlates with the trend; the causal factor is the larger, more polarizable electron cloud that accompanies the heavier atom, not the mass itself. Skill 2$ex82$,
    'medium', '5B', $cc82$Nature of molecules and intermolecular interactions$cc82$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a82A$Treats higher electronegativity (tighter electron binding) as producing stronger intermolecular attraction, inverting the actual polarizability-driven trend$a82A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a82B$Attributes dipole-dipole forces to a nonpolar homonuclear diatomic molecule$a82B$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a82D$Correctly identifies the heaviest halogen but credits molar mass itself rather than electron-cloud polarizability as the causal property$a82D$ FROM q;

-- Q17 [Stereochemistry · easy · Skill 1 · organic-chemistry · ans C] (g83)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt83$2-Bromobutane, \(\text{CH}_3\text{-CHBr-CH}_2\text{-CH}_3\), has exactly one carbon bonded to four different groups. Which carbon is that stereocenter?$qt83$,
    $op83$[{"label":"A","text":"C1, the terminal \\(\\text{CH}_3\\) adjacent to the brominated carbon"},{"label":"B","text":"C3, the \\(\\text{CH}_2\\) group between the brominated carbon and the terminal methyl"},{"label":"C","text":"C2, the carbon bearing \\(\\text{Br}\\), bonded to \\(\\text{H}\\), \\(\\text{Br}\\), a methyl group, and an ethyl group"},{"label":"D","text":"C4, the terminal \\(\\text{CH}_3\\) farthest from the brominated carbon"}]$op83$::jsonb,
    'C',
    $ex83$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because C2 carries four nonidentical substituents, \(\text{H}\), \(\text{Br}\), \(\text{CH}_3\) (the C1 side), and \(\text{CH}_2\text{CH}_3\) (the C3-C4 side), which is the defining requirement for a stereocenter. A chiral center is a carbon attached to four different groups, so the molecule must be scanned carbon by carbon: only C2 satisfies the rule, making 2-bromobutane chiral with one stereocenter and a single pair of enantiomers. (Choice A) C1 is a terminal \(\text{CH}_3\) bonded to three hydrogens and one carbon; three identical \(\text{H}\) substituents disqualify it regardless of its position next to the bromine. (Choice B) C3 is bonded to two carbon chains that do differ, but it also carries two hydrogens, and those two identical \(\text{H}\) atoms mean it is bonded to only three distinct groups rather than four. (Choice D) C4 is a terminal \(\text{CH}_3\) with three identical hydrogens; being the carbon farthest from \(\text{Br}\) has no bearing on whether it bonds four different groups. Skill 1$ex83$,
    'easy', '5B', $cc83$Nature of molecules and intermolecular interactions$cc83$, 'organic-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a83A$Assuming a carbon adjacent to the substituent-bearing carbon is itself the stereocenter, ignoring that it carries three identical hydrogens$a83A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a83B$Recognizing the two attached chains differ but failing the four-different-groups test because the carbon also bears two identical hydrogens$a83B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a83D$Selecting a terminal methyl carbon by position relative to bromine, overlooking its three identical hydrogens$a83D$ FROM q;

-- Q18 [Stereochemistry · medium · Skill 1 · organic-chemistry · ans A] (g84)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt84$Tartaric acid (2,3-dihydroxybutanedioic acid) has two stereocenters at C2 and C3. Consider the isomer with the \((2R,3R)\) configuration and the isomer with the \((2S,3S)\) configuration. The stereochemical relationship between these two specific isomers is best described as which of the following?$qt84$,
    $op84$[{"label":"A","text":"Enantiomers"},{"label":"B","text":"Diastereomers"},{"label":"C","text":"The same compound in two orientations"},{"label":"D","text":"Constitutional isomers"}]$op84$::jsonb,
    'A',
    $ex84$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the \((2R,3R)\) and \((2S,3S)\) isomers have every stereocenter inverted relative to one another, which makes them nonsuperimposable mirror images, and that is the defining relationship of enantiomers. Tartaric acid has two stereocenters, so its stereoisomers are \((2R,3R)\), \((2S,3S)\), and \((2R,3S)\); the first two are the chiral pair that rotate plane-polarized light in equal and opposite directions, while \((2R,3S)\) is the achiral meso form. Inverting both stereocenters (R→S at C2 and R→S at C3) reflects the entire molecule, so \((2R,3R)\) and \((2S,3S)\) are mirror images that cannot be overlaid, satisfying the definition of enantiomers. (Choice B) Diastereomers are stereoisomers that are not mirror images, such as \((2R,3R)\) compared with the meso \((2R,3S)\) form where only one stereocenter is inverted; because \((2R,3R)\) and \((2S,3S)\) have both centers inverted, they are mirror images and therefore are not diastereomers. (Choice C) The two configurations are not the same compound, because neither one is meso and each has a true nonsuperimposable mirror image; a molecule and its mirror image are identical only when an internal mirror plane makes the molecule achiral, which is not the case for \((2R,3R)\) tartaric acid. (Choice D) Constitutional isomers differ in the connectivity of their atoms, whereas these two isomers share identical bonding and connectivity and differ only in the three-dimensional spatial arrangement at the stereocenters, making them stereoisomers rather than constitutional isomers. Skill 1$ex84$,
    'medium', '5B', $cc84$Nature of molecules and intermolecular interactions$cc84$, 'organic-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a84B$calls a fully-inverted mirror-image pair diastereomers$a84B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a84C$treats nonsuperimposable mirror images as the identical/superimposable compound$a84C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a84D$labels stereoisomers as constitutional isomers despite identical connectivity$a84D$ FROM q;

-- Q19 [Stereochemistry · hard · Skill 2 · organic-chemistry · ans B] (g85)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt85$Consider the single, pure compound (2R,3S)-2,3-dibromobutane, \(\text{CH}_3\text{CHBrCHBrCH}_3\), in which C2 and C3 are each bonded to four different groups. A sample of this isolated stereoisomer shows no measurable optical rotation. Which of the following best accounts for this observation?$qt85$,
    $op85$[{"label":"A","text":"The sample is optically inactive because it is necessarily a 1:1 racemic mixture of two enantiomers whose rotations cancel."},{"label":"B","text":"The molecule possesses an internal mirror plane that makes it superimposable on its own mirror image, so despite having two stereocenters it is achiral and rotates plane-polarized light by a net of zero."},{"label":"C","text":"Because the molecule contains two stereocenters, it must be chiral and optically active, so the absence of rotation indicates the sample was contaminated or measured incorrectly."},{"label":"D","text":"Rapid rotation about the C2–C3 single bond interconverts conformers whose opposite rotations average to zero over time."}]$op85$::jsonb,
    'B',
    $ex85$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because (2R,3S)-2,3-dibromobutane is a meso compound: it contains two stereocenters yet is achiral because an internal mirror plane bisecting the C2–C3 bond relates the (2R) half to the (3S) half, making the molecule superimposable on its mirror image. An achiral molecule cannot rotate plane-polarized light, so a pure sample is optically inactive (internal compensation). Note that 2,3-dibromobutane therefore has only three stereoisomers, not 2^2=4: the (2R,3R)/(2S,3S) pair of enantiomers plus the single meso (2R,3S) form. (Choice A) The sample is a single, pure stereoisomer as stated, not a mixture of two enantiomers; its inactivity arises from an internal mirror plane within one molecule (internal compensation), not from the external averaging of two molecules in a racemate. (Choice C) Having two stereocenters does not guarantee chirality; when an internal mirror plane is present the molecule is meso and achiral, so the absence of rotation is the expected result rather than an artifact. (Choice D) Optical activity is determined by molecular symmetry, not by conformational populations; rotation about a single bond does not convert a chiral molecule into an inactive one, and conformers of a chiral molecule do not have canceling rotations. Skill 2: Reasoning about scientific principles to draw conclusions.$ex85$,
    'hard', '5B', $cc85$Nature of molecules and intermolecular interactions$cc85$, 'organic-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a85A$confusing internal compensation (a single meso molecule) with external compensation (a racemic mixture)$a85A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a85C$asserting that the presence of stereocenters necessarily implies chirality/optical activity$a85C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a85D$attributing loss of optical activity to conformational averaging about a single bond rather than to molecular symmetry$a85D$ FROM q;

-- Q20 [Stereochemistry · medium · Skill 2 · organic-chemistry · ans D] (g86)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt86$Cis-trans isomerism demands both restricted rotation and two different substituents on each of the relevant carbons. Which molecule satisfies these conditions and therefore exists as distinct cis and trans forms?$qt86$,
    $op86$[{"label":"A","text":"\\(1,2\\text{-dichloroethane}\\), \\(\\text{ClCH}_2\\text{-CH}_2\\text{Cl}\\)"},{"label":"B","text":"\\(1,1\\text{-dichloroethene}\\), \\(\\text{Cl}_2\\text{C=CH}_2\\)"},{"label":"C","text":"propene, \\(\\text{CH}_2\\text{=CH-CH}_3\\)"},{"label":"D","text":"\\(2\\text{-butene}\\), \\(\\text{CH}_3\\text{-CH=CH-CH}_3\\)"}]$op86$::jsonb,
    'D',
    $ex86$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because each \(sp^2\) carbon of the \(\text{C=C}\) bond in \(2\text{-butene}\) carries two different groups (one \(\text{H}\) and one \(\text{CH}_3\)), so the \(\pi\) bond's restricted rotation locks the two methyl groups into either the same side (cis) or opposite sides (trans). Cis-trans isomerism requires a barrier to rotation, supplied here by the \(\pi\) bond of the double bond, plus two distinct substituents on each doubly bonded carbon so that the two spatial arrangements are non-identical; both criteria are met only in \(2\text{-butene}\). (Choice A) \(1,2\text{-dichloroethane}\) contains only a \(\text{C-C}\) single bond, which permits free rotation, so the differing arrangements are merely interconverting conformers rather than separable geometric isomers. (Choice B) \(1,1\text{-dichloroethene}\) does have a rotation-restricting \(\text{C=C}\) bond, but one carbon bears two identical \(\text{Cl}\) atoms, so swapping them yields the same molecule and no distinct cis and trans forms exist. (Choice C) Propene has a \(\text{C=C}\) bond, yet the terminal carbon carries two identical \(\text{H}\) atoms, which fails the requirement that each doubly bonded carbon hold two different groups. Skill 2$ex86$,
    'medium', '5B', $cc86$Nature of molecules and intermolecular interactions$cc86$, 'organic-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a86A$Treats free-rotation single-bond conformers as separable cis/trans isomers, ignoring the restricted-rotation requirement$a86A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a86B$Recognizes the restricted-rotation criterion from the C=C bond but overlooks that two identical substituents on one carbon prevent distinct isomers$a86B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a86C$Equates the mere presence of a double bond with cis-trans isomerism, skipping the two-different-groups-per-carbon check$a86C$ FROM q;

-- Q21 [Stereochemistry · hard · Skill 2 · organic-chemistry · ans C] (g87)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt87$A trisubstituted alkene has the connectivity \((\text{HO})(\text{CH}_3)\text{C}=\text{C}(\text{CH}_2\text{Cl})(\text{CH}_2\text{CH}_3)\), and the \(-\text{OH}\) group and the \(-\text{CH}_2\text{Cl}\) group lie on opposite sides of the \(\text{C}=\text{C}\) axis. A chemist must assign the double-bond configuration using CIP priority on each alkene carbon.$qt87$,
    $op87$[{"label":"A","text":"\\(Z\\), because the two carbon-containing substituents \\(-\\text{CH}_3\\) and \\(-\\text{CH}_2\\text{CH}_3\\) lie on the same side."},{"label":"B","text":"\\(Z\\), because \\(-\\text{OH}\\) outranks \\(-\\text{CH}_3\\) and \\(-\\text{CH}_2\\text{CH}_3\\) outranks \\(-\\text{CH}_2\\text{Cl}\\), placing the higher-priority groups on the same side."},{"label":"C","text":"\\(E\\), because \\(-\\text{OH}\\) outranks \\(-\\text{CH}_3\\) and \\(-\\text{CH}_2\\text{Cl}\\) outranks \\(-\\text{CH}_2\\text{CH}_3\\), placing the higher-priority groups on opposite sides."},{"label":"D","text":"\\(E\\), because \\(-\\text{CH}_2\\text{CH}_3\\) is the longest chain and therefore the highest-priority group on its carbon, ranking it opposite the \\(-\\text{OH}\\)."}]$op87$::jsonb,
    'C',
    $ex87$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because on the left carbon \(-\text{OH}\) (first atom O) outranks \(-\text{CH}_3\) (first atom C), while on the right carbon \(-\text{CH}_2\text{Cl}\) outranks \(-\text{CH}_2\text{CH}_3\), and these two higher-priority groups sit on opposite sides, defining the \(E\) configuration. By the CIP rules, priority is set by the first point of difference: at the left carbon the choice is decided immediately because O (Z = 8) beats C (Z = 6), so \(-\text{OH}\) wins; at the right carbon both substituents have C as their first atom, so one compares the atoms attached to that carbon — \(-\text{CH}_2\text{Cl}\) presents the set \((\text{Cl}, \text{H}, \text{H})\) whereas \(-\text{CH}_2\text{CH}_3\) presents \((\text{C}, \text{H}, \text{H})\), and Cl (Z = 17) outranks C, so \(-\text{CH}_2\text{Cl}\) wins. With \(-\text{OH}\) and \(-\text{CH}_2\text{Cl}\) on opposite sides of the double bond, the higher-priority groups are trans to one another, which is the definition of \(E\). (Choice A) Configuration is assigned by ranking the two substituents on each carbon, not by tracking whether the carbon-containing groups happen to be on the same side, so grouping \(-\text{CH}_3\) and \(-\text{CH}_2\text{CH}_3\) does not determine \(E\)/\(Z\). (Choice B) The left-carbon ranking is correct, but on the right carbon the comparison \((\text{Cl}, \text{H}, \text{H})\) versus \((\text{C}, \text{H}, \text{H})\) makes \(-\text{CH}_2\text{Cl}\) the higher priority, reversing the conclusion to opposite sides and \(E\). (Choice D) Priority is not decided by chain length; it is decided by the first point of difference in atomic number, where the chlorine on \(-\text{CH}_2\text{Cl}\) outranks the carbon continuation of \(-\text{CH}_2\text{CH}_3\). Skill 2$ex87$,
    'hard', '5B', $cc87$Nature of molecules and intermolecular interactions$cc87$, 'organic-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a87A$Assigning E/Z by whether carbon-chain substituents are cis/trans rather than by CIP priority ranking on each carbon$a87A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a87B$Correct left-carbon ranking but wrong right-carbon CIP comparison, treating longer carbon chain as higher priority than CH2Cl$a87B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a87D$Believing CIP priority is set by longest chain length instead of first point of difference in atomic number$a87D$ FROM q;

-- Q22 [Stereochemistry · medium · Skill 1 · organic-chemistry · ans A] (g88)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt88$A sample of pure \((R)\)-2-bromobutane has a measured specific rotation of \(+23.1^\circ\), and an equal number of moles of \((S)\)-2-bromobutane is dissolved into it. What is the observed specific rotation of the resulting solution?$qt88$,
    $op88$[{"label":"A","text":"\\(0^\\circ\\), because the rotations of the two enantiomers are equal in magnitude and opposite in sign"},{"label":"B","text":"\\(+23.1^\\circ\\), because the \\((R)\\) enantiomer fixes the sign of the observed rotation"},{"label":"C","text":"\\(+46.2^\\circ\\), because the rotations of the two enantiomers add together"},{"label":"D","text":"\\(-23.1^\\circ\\), because the added \\((S)\\) enantiomer rotates light in the opposite direction"}]$op88$::jsonb,
    'A',
    $ex88$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because mixing equal moles of \((R)\)- and \((S)\)-2-bromobutane forms a racemic mixture whose components rotate plane-polarized light by equal magnitudes in opposite directions, giving a net rotation of \(0^\circ\). A pair of enantiomers are nonsuperimposable mirror images that are physically identical except in their interaction with plane-polarized light: one rotates the plane by \(+\alpha\) and the other by \(-\alpha\). In a 1:1 (racemic) mixture the contribution of each enantiomer exactly cancels the other, so the sample is optically inactive even though every individual molecule is chiral. (Choice B) The \((R)\) enantiomer does not dominate; an equal amount of the \((S)\) enantiomer is present and its opposite rotation cancels the \((R)\) contribution rather than leaving \(+23.1^\circ\). (Choice C) Equal and opposite rotations subtract to zero rather than adding, so \(+46.2^\circ\) would require two samples rotating light in the same direction. (Choice D) A residual \(-23.1^\circ\) would occur only if the \((S)\) enantiomer were in excess, but the amounts are equal, so the \((R)\) contribution is not left uncanceled in the opposite direction. Skill 1$ex88$,
    'medium', '5B', $cc88$Nature of molecules and intermolecular interactions$cc88$, 'organic-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a88B$treats one enantiomer as setting the net sign while ignoring the equal opposite contribution$a88B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a88C$adds the two rotation magnitudes instead of recognizing they cancel$a88C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a88D$assumes the added enantiomer leaves a net opposite rotation rather than canceling to zero$a88D$ FROM q;

-- Q23 [Stereochemistry · easy · Skill 1 · organic-chemistry · ans B] (g89)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt89$The open-chain aldopentose 2,3,4-trihydroxypentanal contains three tetrahedral stereocenters, none of which are related to one another by internal symmetry. What is the maximum number of stereoisomers possible for this molecule?$qt89$,
    $op89$[{"label":"A","text":"\\(6\\)"},{"label":"B","text":"\\(8\\)"},{"label":"C","text":"\\(4\\)"},{"label":"D","text":"\\(16\\)"}]$op89$::jsonb,
    'B',
    $ex89$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because a molecule with \(n\) stereocenters has a maximum of \(2^n\) stereoisomers, and \(2^3 = 8\). Each tetrahedral stereocenter can adopt either of two configurations (\(R\) or \(S\)), so three independent stereocenters give \(2 \times 2 \times 2 = 2^3 = 8\) possible configurational combinations; because the stem specifies that none of the centers are related by internal symmetry, no combinations collapse into meso forms and the full \(2^n\) maximum is reached. (Choice A) The value \(6\) comes from multiplying the number of stereocenters by two (\(2 \times 3\)) instead of raising two to the power of the number of stereocenters, which treats the relationship as linear rather than exponential. (Choice C) The value \(4\) is \(2^2\), the maximum for a molecule with only two stereocenters, and undercounts by treating the molecule as having one fewer stereocenter than the three given. (Choice D) The value \(16\) is \(2^4\), the maximum for four stereocenters, and overcounts by applying the exponent for one extra stereocenter beyond the three present. Skill 1$ex89$,
    'easy', '5B', $cc89$Nature of molecules and intermolecular interactions$cc89$, 'organic-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a89A$Multiplying the count of stereocenters by two (2 x 3 = 6) instead of computing 2 raised to the number of stereocenters$a89A$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a89C$Applying 2^n with n = 2 instead of n = 3, the maximum for two stereocenters$a89C$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a89D$Applying 2^n with n = 4 instead of n = 3, the maximum for four stereocenters$a89D$ FROM q;

-- Q24 [Stereochemistry · medium · Skill 2 · organic-chemistry · ans D] (g90)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Stereochemistry',
    $qt90$Constitutional (structural) isomers share a molecular formula but differ in the connectivity of their atoms, whereas stereoisomers share both formula and connectivity and conformational isomers interconvert by rotation about single bonds. Which of the following pairs of compounds is best classified as a pair of constitutional isomers?$qt90$,
    $op90$[{"label":"A","text":"cis-2-butene and trans-2-butene"},{"label":"B","text":"The anti and gauche rotamers of butane about the C2-C3 bond"},{"label":"C","text":"(R)-2-bromobutane and (S)-2-bromobutane"},{"label":"D","text":"1-propanol and 2-propanol"}]$op90$::jsonb,
    'D',
    $ex90$This is an Organic Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because 1-propanol and 2-propanol share the molecular formula \(\text{C}_3\text{H}_8\text{O}\) yet differ in how their atoms are connected: in 1-propanol the hydroxyl is bonded to a terminal carbon (\(\mathrm{CH_3CH_2CH_2OH}\)), while in 2-propanol it is bonded to the central carbon (\(\mathrm{CH_3CH(OH)CH_3}\)). Because the bonding sequence itself differs, the pair are constitutional (structural) isomers, not stereoisomers or conformers. Constitutional isomers are defined by identical formula but distinct connectivity, which is precisely what distinguishes them from stereoisomers (same connectivity, different spatial arrangement) and conformational isomers (same molecule sampled at different rotations about single bonds). (Choice A) cis-2-butene and trans-2-butene have identical connectivity (\(\mathrm{CH_3CH{=}CHCH_3}\)) and differ only in the fixed spatial arrangement of groups about the restricted C=C double bond, making them geometric stereoisomers rather than constitutional isomers. (Choice B) The anti and gauche forms of butane are the same molecule with the same connectivity, interconverting freely by rotation about the C2-C3 single bond; they are conformational isomers (rotamers), not constitutional isomers. (Choice C) (R)- and (S)-2-bromobutane have identical connectivity and are nonsuperimposable mirror images, so they are enantiomers, a subtype of stereoisomer, not constitutional isomers. Skill 2: Scientific Reasoning and Problem-Solving.$ex90$,
    'medium', '5B', $cc90$Nature of molecules and intermolecular interactions$cc90$, 'organic-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a90A$Confusing geometric (cis-trans) stereoisomers with constitutional isomers$a90A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a90B$Treating rotamers (conformational isomers) as distinct constitutional isomers$a90B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a90C$Mistaking enantiomers (a stereoisomer subtype) for constitutional isomers$a90C$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch4_questions FROM questions WHERE topic='Bonding & Chemical Interactions' AND subtopic IN ('Sigma/Pi Bonds & Hybridization', 'Intermolecular Forces', 'Stereochemistry');
