-- GenChem Ch3 (Bonding & Chemical Interactions) — Batch 2 of 4: Ionic Character, Resonance & Bond Properties
-- 20 questions, all confidence >=4 (OpenStax Atoms First 2e; stereochemistry verified vs standard organic conventions); AAMC foundation 5B; cross-batch + cross-chapter deduped, audit clean (PASS, 0 genuine conflicts).
-- Re-runnable. Run the four batches IN ORDER (1->2->3->4) in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Bonding & Chemical Interactions' AND subtopic IN ('Ionic Character & Bond Type', 'Resonance & Delocalization', 'Bond Length & Bond Energy');

-- Q1 [Ionic Character & Bond Type · easy · Skill 2 · general-chemistry · ans B] (g25)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt25$A chemist compares four diatomic hydrogen halide molecules using the Pauling electronegativity values \(\text{H} = 2.1\), \(\text{F} = 4.0\), \(\text{Cl} = 3.0\), \(\text{Br} = 2.8\), and \(\text{I} = 2.5\). Assuming bond ionic character increases monotonically with the electronegativity difference between the bonded atoms, which bond is expected to have the greatest ionic character?$qt25$,
    $op25$[{"label":"A","text":"The \\(\\text{H--Br}\\) bond"},{"label":"B","text":"The \\(\\text{H--F}\\) bond"},{"label":"C","text":"The \\(\\text{H--Cl}\\) bond"},{"label":"D","text":"The \\(\\text{H--I}\\) bond"}]$op25$::jsonb,
    'B',
    $ex25$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because the \(\text{H--F}\) bond has the largest electronegativity difference of the four bonds, \(\left|2.1 - 4.0\right| = 1.9\), and OpenStax describes ionic character as rising continuously with \(\Delta\text{EN}\): the larger the difference, the more unequally the bonding electrons are shared and the more ionic (more polar) the bond. Ranking the differences gives \(\text{H--I} = 0.4\), \(\text{H--Br} = 0.7\), \(\text{H--Cl} = 0.9\), and \(\text{H--F} = 1.9\), so \(\text{H--F}\) sits at the top. OpenStax treats the relationship as a rough qualitative guide with many exceptions rather than a set of fixed numeric cutoffs, so only the monotonic ordering is needed here. (Choice A) The \(\text{H--Br}\) bond has \(\Delta\text{EN} = 0.7\), which is polar covalent but smaller than the \(\text{H--F}\) value, so its ionic character is not the greatest. (Choice C) The \(\text{H--Cl}\) bond has \(\Delta\text{EN} = 0.9\), the second largest difference, but it still falls short of the \(\text{H--F}\) difference and therefore has less ionic character. (Choice D) The \(\text{H--I}\) bond has the smallest difference, \(\Delta\text{EN} = 0.4\), so it is the least ionic; selecting it inverts the monotonic rule by treating the smallest \(\Delta\text{EN}\) as the most ionic. Skill 2: Scientific Reasoning and Problem-Solving.$ex25$,
    'easy', '5B', $cc25$Nature of molecules and intermolecular interactions$cc25$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a25A$Identifies a genuinely polar bond but not the one with the maximum electronegativity difference$a25A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a25C$Selects the second-largest electronegativity difference as if it were the largest$a25C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a25D$Inverts the monotonic rule, treating the smallest electronegativity difference as the most ionic$a25D$ FROM q;

-- Q2 [Ionic Character & Bond Type · medium · Skill 2 · general-chemistry · ans C] (g26)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt26$Using the Pauling electronegativities \(\text{H} = 2.20\), \(\text{C} = 2.55\), \(\text{O} = 3.44\), \(\text{P} = 2.19\), \(\text{Cl} = 3.16\), and \(\text{K} = 0.82\), the bonds \(\text{C}-\text{H}\), \(\text{C}-\text{O}\), \(\text{P}-\text{Cl}\), and \(\text{K}-\text{Cl}\) are ranked by increasing percent ionic character. Which ordering is correct?$qt26$,
    $op26$[{"label":"A","text":"\\(\\text{K}-\\text{Cl} < \\text{P}-\\text{Cl} < \\text{C}-\\text{O} < \\text{C}-\\text{H}\\)"},{"label":"B","text":"\\(\\text{C}-\\text{H} < \\text{P}-\\text{Cl} < \\text{C}-\\text{O} < \\text{K}-\\text{Cl}\\)"},{"label":"C","text":"\\(\\text{C}-\\text{H} < \\text{C}-\\text{O} < \\text{P}-\\text{Cl} < \\text{K}-\\text{Cl}\\)"},{"label":"D","text":"\\(\\text{K}-\\text{Cl} < \\text{C}-\\text{H} < \\text{C}-\\text{O} < \\text{P}-\\text{Cl}\\)"}]$op26$::jsonb,
    'C',
    $ex26$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because percent ionic character rises monotonically with the absolute electronegativity difference \(\Delta\text{EN}\), which for these bonds is \(0.35\), \(0.89\), \(0.97\), and \(2.34\) in exactly that order. Computing each difference from the given values gives \(\text{C}-\text{H} = |2.55 - 2.20| = 0.35\), \(\text{C}-\text{O} = |2.55 - 3.44| = 0.89\), \(\text{P}-\text{Cl} = |2.19 - 3.16| = 0.97\), and \(\text{K}-\text{Cl} = |0.82 - 3.16| = 2.34\); since ionic character is a monotonically increasing function of \(\Delta\text{EN}\), increasing \(\Delta\text{EN}\) is increasing ionic character, and the large \(\text{K}-\text{Cl}\) gap (above the \(\approx 1.7\) cutoff) marks it as the most ionic. The hinge is the close \(\text{C}-\text{O}\) versus \(\text{P}-\text{Cl}\) pair, which must be separated by actually subtracting \((0.89 < 0.97)\) rather than by intuition. (Choice A) This lists the bonds from most to least ionic, inverting the requested increasing order; it places the strongly ionic \(\text{K}-\text{Cl}\) (\(\Delta\text{EN} = 2.34\)) first and the nearly nonpolar \(\text{C}-\text{H}\) (\(\Delta\text{EN} = 0.35\)) last, which is the exact reverse of increasing ionic character. (Choice B) This order correctly anchors \(\text{C}-\text{H}\) lowest and \(\text{K}-\text{Cl}\) highest but transposes the middle pair, ranking \(\text{P}-\text{Cl}\) below \(\text{C}-\text{O}\); the differences \(0.97\) for \(\text{P}-\text{Cl}\) and \(0.89\) for \(\text{C}-\text{O}\) require explicit subtraction to separate, and \(\text{P}-\text{Cl}\) is in fact the larger. (Choice D) This treats a partner's small absolute electronegativity as if it lowered ionic character, demoting \(\text{K}-\text{Cl}\) to least ionic because potassium's value (\(0.82\)) is the smallest in the set; ionic character depends on the magnitude of the difference between the two atoms, not on either atom's absolute electronegativity, and the large \(\text{K}-\text{Cl}\) difference makes it the most ionic, not the least. Skill 2$ex26$,
    'medium', '5B', $cc26$Nature of molecules and intermolecular interactions$cc26$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a26A$ranks bonds from most to least ionic, inverting the requested increasing order$a26A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a26B$transposes the close middle pair (P-Cl vs C-O) by estimating instead of computing the differences$a26B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a26D$uses a partner's small absolute electronegativity rather than the EN difference, demoting K-Cl to least ionic$a26D$ FROM q;

-- Q3 [Ionic Character & Bond Type · easy · Skill 1 · general-chemistry · ans A] (g27)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt27$Cesium and fluorine combine in \(\text{CsF}\), where the electronegativity difference \(\Delta\text{EN}\) is about 3.3. Given this very large \(\Delta\text{EN}\), how is the bonding in \(\text{CsF}\) most accurately described?$qt27$,
    $op27$[{"label":"A","text":"Essentially complete transfer of an electron from \\(\\text{Cs}\\) to \\(\\text{F}\\), giving \\(\\text{Cs}^{+}\\) and \\(\\text{F}^{-}\\)"},{"label":"B","text":"Roughly equal sharing of the bonding pair between \\(\\text{Cs}\\) and \\(\\text{F}\\)"},{"label":"C","text":"Unequal sharing of the bonding pair with partial negative charge on \\(\\text{Cs}\\)"},{"label":"D","text":"Essentially complete transfer of an electron from \\(\\text{F}\\) to \\(\\text{Cs}\\), giving \\(\\text{Cs}^{-}\\) and \\(\\text{F}^{+}\\)"}]$op27$::jsonb,
    'A',
    $ex27$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because a \(\Delta\text{EN}\) of about 3.3 lies far above the threshold for essentially ionic bonding, so fluorine pulls the electron away from cesium almost completely to give \(\text{Cs}^{+}\) and \(\text{F}^{-}\). As \(\Delta\text{EN}\) grows, the bonding pair shifts increasingly toward the more electronegative atom; once the difference becomes very large, the pair is no longer shared at all but is effectively held by the more electronegative atom, which constitutes ionic bonding rather than covalent sharing. Cesium is one of the least electronegative elements and fluorine is the most electronegative, so \(\text{CsF}\) represents one of the most ionic of all bonds. (Choice B) Roughly equal sharing describes a nonpolar covalent bond, which requires \(\Delta\text{EN}\) near zero, the opposite of the large value given. (Choice C) Unequal sharing describes a polar covalent bond, but it also places partial negative charge on the wrong atom; the more electronegative fluorine, not cesium, carries the negative charge. (Choice D) Complete transfer in this direction reverses the roles of the atoms, since the more electronegative fluorine gains the electron to become \(\text{F}^{-}\) while cesium loses it to become \(\text{Cs}^{+}\). Skill 1$ex27$,
    'easy', '5B', $cc27$Nature of molecules and intermolecular interactions$cc27$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a27B$Treats any chemical bond as electron sharing, ignoring that a very large electronegativity difference produces ionic (transfer) bonding$a27B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a27C$Correctly recognizes charge separation but understates it as polar covalent sharing and assigns the partial negative charge to the less electronegative atom$a27C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a27D$Reverses the direction of electron transfer, sending the electron to the less electronegative cesium instead of to fluorine$a27D$ FROM q;

-- Q4 [Ionic Character & Bond Type · medium · Skill 2 · general-chemistry · ans D] (g28)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt28$A chemist comparing four binary bonds is given the Pauling electronegativities \( \text{Ca} = 1.0 \), \( \text{Al} = 1.6 \), \( \text{C} = 2.6 \), \( \text{S} = 2.6 \), \( \text{Cl} = 3.2 \), and \( \text{O} = 3.4 \). Using only the rule that a larger electronegativity difference corresponds to greater ionic character, which of the bonds \( \text{Ca-O} \), \( \text{Al-Cl} \), \( \text{S-O} \), and \( \text{C-Cl} \) is most likely the most ionic?$qt28$,
    $op28$[{"label":"A","text":"\\( \\text{C-Cl} \\)"},{"label":"B","text":"\\( \\text{S-O} \\)"},{"label":"C","text":"\\( \\text{Al-Cl} \\)"},{"label":"D","text":"\\( \\text{Ca-O} \\)"}]$op28$::jsonb,
    'D',
    $ex28$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the ionic character of a bond rises with the absolute electronegativity difference \( |\Delta\text{EN}| \) between the two bonded atoms: the larger the difference, the more unequally the bonding electrons are shared and the closer the bond sits to the ionic end of the bonding continuum. Computing each difference from the given values gives \( \text{Ca-O} = |1.0 - 3.4| = 2.4 \), \( \text{Al-Cl} = |1.6 - 3.2| = 1.6 \), \( \text{S-O} = |2.6 - 3.4| = 0.8 \), and \( \text{C-Cl} = |2.6 - 3.2| = 0.6 \). The \( \text{Ca-O} \) bond has the largest \( |\Delta\text{EN}| \), so it is the most ionic, pairing a low-electronegativity metal with a highly electronegative nonmetal. (Choice A) \( \text{C-Cl} \) has the smallest difference of the set, \( |2.6 - 3.2| = 0.6 \), so it is the most nearly covalent of the four rather than the most ionic. (Choice B) \( \text{S-O} \) has \( |\Delta\text{EN}| = 0.8 \), only slightly larger than \( \text{C-Cl} \) and far below \( \text{Ca-O} \); both atoms are electronegative nonmetals, so the difference stays small. (Choice C) \( \text{Al-Cl} \) has the second-largest difference, \( |1.6 - 3.2| = 1.6 \), which makes it strongly polar but still smaller than the \( 2.4 \) gap in \( \text{Ca-O} \), so it is not the most ionic. Skill 2$ex28$,
    'medium', '5B', $cc28$Nature of molecules and intermolecular interactions$cc28$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a28A$selects the bond with the smallest electronegativity difference as most ionic, inverting the larger-difference-more-ionic rule$a28A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a28B$judges ionic character from an absolute electronegativity value rather than the difference between the two bonded atoms$a28B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a28C$correctly identifies a strongly polar bond with a large difference but stops at the second-largest difference instead of the maximum$a28C$ FROM q;

-- Q5 [Ionic Character & Bond Type · medium · Skill 1 · general-chemistry · ans B] (g29)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt29$In gaseous \(\text{HCl}\), the \(\text{H-Cl}\) bond has an electronegativity difference of about \(0.9\), placing it in the polar covalent range. How is the bonding electron pair distributed between the two atoms?$qt29$,
    $op29$[{"label":"A","text":"It is transferred completely to chlorine, leaving a full \\(+1\\) charge on hydrogen and a full \\(-1\\) charge on chlorine."},{"label":"B","text":"It is shared but drawn closer to chlorine, giving chlorine a partial negative charge \\((\\delta^-)\\) and hydrogen a partial positive charge \\((\\delta^+)\\)."},{"label":"C","text":"It is shared exactly equally between the two atoms, so neither atom carries any net or partial charge."},{"label":"D","text":"It is shared but drawn closer to hydrogen, giving hydrogen a partial negative charge \\((\\delta^-)\\) and chlorine a partial positive charge \\((\\delta^+)\\)."}]$op29$::jsonb,
    'B',
    $ex29$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because an intermediate electronegativity difference produces a polar covalent bond in which the shared pair is pulled toward the more electronegative atom, generating partial charges rather than full ion charges. With \(\Delta\text{EN} \approx 0.9\), the \(\text{H-Cl}\) bond lies in the polar covalent regime (roughly \(0.4\) to \(1.7\)), so the electrons are not transferred outright but remain shared while spending more time near chlorine; this unequal sharing leaves chlorine with a partial negative charge \((\delta^-)\) and hydrogen with a partial positive charge \((\delta^+)\), which is what is meant by partial ionic character. (Choice A) Complete transfer of the electron pair to give full \(+1\) and \(-1\) charges describes a purely ionic bond, which would require a much larger \(\Delta\text{EN}\) (generally above about \(1.7\)); at \(\Delta\text{EN} \approx 0.9\) the electrons are still shared, so only partial charges develop. (Choice C) Exactly equal sharing with no charges occurs only in a nonpolar covalent bond between atoms of equal electronegativity \((\Delta\text{EN} \approx 0)\); a difference of \(0.9\) guarantees unequal sharing and therefore partial charges. (Choice D) This places the partial negative charge on the wrong atom: electron density is drawn toward the more electronegative atom, and chlorine is more electronegative than hydrogen, so chlorine bears the \(\delta^-\) and hydrogen the \(\delta^+\). Skill 1$ex29$,
    'medium', '5B', $cc29$Nature of molecules and intermolecular interactions$cc29$, 'general-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a29A$polar covalent bond mistaken for full electron transfer producing complete ion charges$a29A$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a29C$correctly identifies sharing but assumes it is equal, ignoring the nonzero electronegativity difference$a29C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a29D$partial charges assigned with polarity reversed, placing delta-minus on the less electronegative atom$a29D$ FROM q;

-- Q6 [Ionic Character & Bond Type · easy · Skill 2 · general-chemistry · ans A] (g30)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt30$In carbon disulfide \(\text{CS}_2\) (connectivity S=C=S), each carbon-sulfur bond joins atoms whose electronegativities are \(2.55\) for carbon and \(2.58\) for sulfur. Classify each \(\text{C}{-}\text{S}\) bond by type.$qt30$,
    $op30$[{"label":"A","text":"Nonpolar covalent, because \\(\\Delta\\text{EN}\\approx 0.03\\) is essentially zero"},{"label":"B","text":"Polar covalent, because the two atoms are different elements"},{"label":"C","text":"Ionic, because sulfur is more electronegative than carbon"},{"label":"D","text":"Polar covalent, because the bond is part of a \\(\\text{C}{=}\\text{S}\\) double bond"}]$op30$::jsonb,
    'A',
    $ex30$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the electronegativity difference \(\Delta\text{EN}=2.58-2.55=0.03\) is far below the \(\approx 0.4\) threshold, so the bonding electrons are shared essentially equally and the bond is nonpolar covalent. Bond character is determined by \(\Delta\text{EN}\): values near \(0\) (roughly \(0.0\)-\(0.4\)) give nonpolar covalent bonds, intermediate values give polar covalent bonds, and large values (roughly \(\geq 1.7\)) give predominantly ionic bonds; with \(\Delta\text{EN}\approx 0.03\), \(\text{C}{-}\text{S}\) sits at the nonpolar covalent end despite carbon and sulfur being different elements. (Choice B) Two different elements do not automatically make a polar bond; polarity depends on the magnitude of \(\Delta\text{EN}\), which here is negligibly small. (Choice C) An \(\text{ionic}\) classification requires a large \(\Delta\text{EN}\) (roughly \(\geq 1.7\)); a difference of \(0.03\) is nowhere near that range, so no appreciable charge transfer occurs. (Choice D) Bond order (single versus double) sets bond length and strength but does not by itself create polarity; the shared electrons in the \(\text{C}{=}\text{S}\) bond are still divided almost equally because \(\Delta\text{EN}\) remains \(\approx 0.03\). Skill 2$ex30$,
    'easy', '5B', $cc30$Nature of molecules and intermolecular interactions$cc30$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a30B$assumes any bond between two different elements must be polar, ignoring the magnitude of the electronegativity difference$a30B$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a30C$treats any nonzero electronegativity difference as sufficient for ionic character, misjudging the size of \(\Delta\text{EN}\) needed$a30C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a30D$conflates the multiple-bond effect on bond length/energy with bond polarity$a30D$ FROM q;

-- Q7 [Ionic Character & Bond Type · hard · Skill 2 · general-chemistry · ans C] (g31)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Ionic Character & Bond Type',
    $qt31$In solid \(\text{MgO}\), magnesium has an electronegativity of about \(1.3\) and oxygen about \(3.4\). Using the electronegativity-difference scheme that places the polar-covalent/ionic boundary near \(\Delta\text{EN} \approx 2.0\), classify the \(\text{Mg-O}\) interaction and its dominant cause.$qt31$,
    $op31$[{"label":"A","text":"Polar covalent, because \\(\\Delta\\text{EN} \\approx 2.1\\) lies in the range where shared electrons are merely unequally distributed rather than transferred"},{"label":"B","text":"Nonpolar covalent, because oxygen and magnesium both achieve a noble-gas configuration by equally sharing the bonding pair"},{"label":"C","text":"Ionic, because \\(\\Delta\\text{EN} \\approx 2.1\\) exceeds the threshold, so oxygen's far greater attraction for electrons drives essentially complete transfer to form \\(\\text{Mg}^{2+}\\) and \\(\\text{O}^{2-}\\)"},{"label":"D","text":"Ionic, because magnesium's higher electronegativity pulls the bonding electrons fully onto magnesium to give \\(\\text{Mg}^{2-}\\) and \\(\\text{O}^{2+}\\)"}]$op31$::jsonb,
    'C',
    $ex31$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because \(\Delta\text{EN} = 3.4 - 1.3 \approx 2.1\) exceeds the \(\approx 2.0\) ionic threshold, so the bonding pair is effectively transferred rather than shared. When the electronegativity difference is this large, the more electronegative atom (oxygen) attracts the valence electrons so strongly that the bond is best modeled as full electron transfer producing discrete ions; oxygen, having the greater electronegativity, gains electrons to become the anion \(\text{O}^{2-}\) while magnesium loses its two valence electrons to become the cation \(\text{Mg}^{2+}\), consistent with the partial-ionic-character trend in which increasing \(\Delta\text{EN}\) raises ionic character. (Choice A) A \(\Delta\text{EN}\) near \(2.1\) sits above, not within, the polar-covalent window, so describing the electrons as unequally shared rather than transferred understates the degree of charge separation at this difference. (Choice B) Equal sharing requires \(\Delta\text{EN} \approx 0\); with a difference of about \(2.1\) the bonding electrons are not shared equally, so a nonpolar covalent description is inconsistent with the given values. (Choice D) The direction of charge is reversed: the more electronegative atom takes the electrons, so oxygen becomes \(\text{O}^{2-}\) and magnesium becomes \(\text{Mg}^{2+}\), not the cation/anion assignment stated. Skill 2$ex31$,
    'hard', '5B', $cc31$Nature of molecules and intermolecular interactions$cc31$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a31A$treats a difference above the ionic threshold as still polar covalent (unequal sharing) instead of transfer$a31A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a31B$assumes octet satisfaction implies equal covalent sharing, ignoring the large electronegativity gap$a31B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a31D$assigns electron gain to the less electronegative atom, inverting which atom becomes the cation vs anion$a31D$ FROM q;

-- Q8 [Resonance & Delocalization · medium · Skill 2 · general-chemistry · ans C] (g32)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt32$The nitrate ion \(\text{NO}_3^-\) has a central nitrogen single-bonded to two oxygens and double-bonded to a third, with each oxygen chemically equivalent. Counting only contributors that are equivalent in energy, how many resonance structures describe \(\text{NO}_3^-\)?$qt32$,
    $op32$[{"label":"A","text":"Two equivalent resonance structures, because the negative charge alternates between the two single-bonded oxygens"},{"label":"B","text":"Four equivalent resonance structures, because three place the \\(\\text{N=O}\\) double bond and one places three \\(\\text{N=O}\\) double bonds"},{"label":"C","text":"Three equivalent resonance structures, because the \\(\\text{N=O}\\) double bond can occupy any of the three equivalent oxygen positions"},{"label":"D","text":"Six equivalent resonance structures, because each of the three oxygens can host either the double bond or the extra lone pair independently"}]$op32$::jsonb,
    'C',
    $ex32$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the single \(\text{N=O}\) double bond can be drawn to any one of the three equivalent oxygens, generating exactly three resonance contributors that are identical in energy. In \(\text{NO}_3^-\) the central nitrogen forms four bonds (one double, two single) with no lone pair, and because all three oxygens are chemically equivalent, each placement of the double bond produces a structure superimposable by symmetry on the others; the delocalization spreads the charge and double-bond character equally, giving a resonance-averaged \(\text{N-O}\) bond intermediate between a single and double bond. (Choice A) Two contributors describes a species with only two equivalent terminal atoms involved in the delocalization, such as a carboxylate \(\text{RCO}_2^-\), not the three-oxygen nitrate framework. (Choice B) Counting four wrongly appends an extra "contributor" with three \(\text{N=O}\) double bonds, which would require an expanded octet on nitrogen and is not a valid Lewis structure, so it cannot be one of the equivalent contributors. (Choice D) Counting six treats the double-bond placement and a lone-pair placement as independent variations, double-counting positions that actually describe the same three structures. Skill 2$ex32$,
    'medium', '5B', $cc32$Nature of molecules and intermolecular interactions$cc32$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a32A$applies the two-equivalent-contributor count of a carboxylate/diatomic-terminal system to a three-equivalent-oxygen ion$a32A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a32B$appends an invalid expanded-octet structure as an extra contributor when enumerating resonance forms$a32B$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a32D$over-counts contributors by treating double-bond and lone-pair placements as independent, inflating three structures to six$a32D$ FROM q;

-- Q9 [Resonance & Delocalization · hard · Skill 2 · general-chemistry · ans D] (g33)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt33$The cyanate ion \(\text{OCN}^-\) (connectivity N-C-O, carbon central) has several resonance contributors that differ only in where the multiple bonds sit. Constrained to the rules of formal charge, the major (most favorable) contributor is most likely the structure with$qt33$,
    $op33$[{"label":"A","text":"a cumulated arrangement \\(\\text{N}{=}\\text{C}{=}\\text{O}\\), giving formal charges of \\(-1\\) on N, \\(0\\) on C, and \\(0\\) on O, placing the negative charge on nitrogen."},{"label":"B","text":"a single N-C bond and a C-O triple bond, \\(\\text{N}{-}\\text{C}{\\equiv}\\text{O}\\), giving formal charges of \\(-2\\) on N, \\(0\\) on C, and \\(+1\\) on O, since maximizing C-O bonding lowers the structure's energy."},{"label":"C","text":"a cumulated arrangement \\(\\text{N}{=}\\text{C}{=}\\text{O}\\) in which every atom carries a formal charge of \\(0\\), satisfying the rule that an all-zero distribution is preferred."},{"label":"D","text":"an N-C triple bond and a single C-O bond, \\(\\text{N}{\\equiv}\\text{C}{-}\\text{O}\\), giving formal charges of \\(0\\) on N, \\(0\\) on C, and \\(-1\\) on O, placing the negative charge on oxygen."}]$op33$::jsonb,
    'D',
    $ex33$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the \(\text{N}{\equiv}\text{C}{-}\text{O}\) contributor minimizes the number and magnitude of nonzero formal charges and places the single \(-1\) on oxygen, the more electronegative terminal atom. Using \(\text{FC} = V - (\text{nonbonding } e^-) - \tfrac{1}{2}(\text{bonding } e^-)\): in \(\text{N}{\equiv}\text{C}{-}\text{O}\), nitrogen has one lone pair and a triple bond \((5 - 2 - 3 = 0)\), carbon has a triple plus a single bond \((4 - 0 - 4 = 0)\), and oxygen has three lone pairs and a single bond \((6 - 6 - 1 = -1)\); the charges sum to \(-1\), the ion's charge. By Guideline 2 the favorable structures are those with the smallest nonzero formal charges, leaving only \(\text{N}{\equiv}\text{C}{-}\text{O}\) (charges \(0,0,-1\)) and \(\text{N}{=}\text{C}{=}\text{O}\) (charges \(-1,0,0\)); the tiebreaker is Guideline 4, which prefers the negative formal charge on the more electronegative atom, and oxygen (\(\Delta\text{EN}\) larger) outranks nitrogen, so \(\text{N}{\equiv}\text{C}{-}\text{O}\) is the major contributor. (Choice A) This structure \(\text{N}{=}\text{C}{=}\text{O}\) does tie for the smallest formal-charge magnitude, but it locates the \(-1\) on nitrogen rather than oxygen; because oxygen is the more electronegative terminal atom, Guideline 4 makes this a minor contributor, not the major one. (Choice B) The \(\text{N}{-}\text{C}{\equiv}\text{O}\) arrangement carries a \(-2\) on nitrogen and a \(+1\) on oxygen, the largest charge separation of the set and a positive charge on the more electronegative atom; greater multiple bonding to one atom does not override the rule that smaller formal charges are preferred, so this is the least favorable structure. (Choice C) The cumulated \(\text{N}{=}\text{C}{=}\text{O}\) structure does not have all-zero formal charges; with two lone pairs and a double bond on each terminal atom the charges are \(-1\) on nitrogen and \(0\) on oxygen, so the claimed all-zero distribution misstates the formal-charge calculation. Skill 2$ex33$,
    'hard', '5B', $cc33$Nature of molecules and intermolecular interactions$cc33$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a33A$applies the smallest-formal-charge rule but reverses Guideline 4, putting the negative charge on the less electronegative atom (N instead of O)$a33A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a33B$treats more multiple bonding as inherently stabilizing, ignoring that larger-magnitude formal charges (-2/+1) make the structure less favorable$a33B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a33C$miscomputes the formal charges of N=C=O as all zero and selects it via the all-zero guideline$a33C$ FROM q;

-- Q10 [Resonance & Delocalization · medium · Skill 2 · general-chemistry · ans A] (g34)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt34$A single Lewis structure of the carbonate ion \(\text{CO}_3^{2-}\) shows one C=O double bond and two C–O single bonds. Considering all equivalent resonance contributors, which prediction about the three carbon–oxygen bonds is correct?$qt34$,
    $op34$[{"label":"A","text":"All three bonds are identical, each shorter than a C–O single bond but longer than a C=O double bond."},{"label":"B","text":"All three bonds are identical, each equal in length to a full C=O double bond."},{"label":"C","text":"Two bonds are short like C=O double bonds and one is long like a C–O single bond."},{"label":"D","text":"All three bonds are identical, each equal in length to a full C–O single bond."}]$op34$::jsonb,
    'A',
    $ex34$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because resonance delocalizes the double bond equally over all three positions, so each C–O bond is an average of a single and a double bond and therefore lies intermediate in length between the two. The carbonate ion has three equivalent resonance contributors, each placing the C=O double bond on a different oxygen; the true structure is the resonance hybrid in which the extra bonding pair is shared equally, giving every bond a length and strength between those of a pure single bond and a pure double bond. (Choice B) Treating every bond as a full double bond ignores that only one double bond's worth of pi electron density is distributed across three positions, so no bond reaches full double-bond character. (Choice C) Predicting two short and one long bond corresponds to taking a single static Lewis structure literally, whereas the equivalence of the resonance contributors makes all three positions identical. (Choice D) Treating every bond as a full single bond neglects the shared pi pair entirely, which would leave the delocalized double-bond character unaccounted for. Skill 2$ex34$,
    'medium', '5B', $cc34$Nature of molecules and intermolecular interactions$cc34$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a34B$Recognizes bond equivalence from resonance but overestimates each bond as full double-bond character$a34B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a34C$Reads a single static Lewis structure literally, predicting localized distinct bond lengths$a34C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a34D$Recognizes bond equivalence but underestimates each bond as full single-bond character, ignoring delocalized pi pair$a34D$ FROM q;

-- Q11 [Resonance & Delocalization · medium · Skill 1 · general-chemistry · ans B] (g35)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt35$The carbonate ion \(\text{CO}_3^{2-}\) is described by three equivalent resonance structures, each placing the \(\text{C=O}\) double bond on a different oxygen. Relative to any single one of these contributing structures, the actual energy of \(\text{CO}_3^{2-}\) is most likely$qt35$,
    $op35$[{"label":"A","text":"higher, because spreading the \\(\\pi\\) electrons over three \\(\\text{C-O}\\) bonds raises the energy above that of any single contributing structure"},{"label":"B","text":"lower, because delocalizing the \\(\\pi\\) electrons over all three \\(\\text{C-O}\\) bonds stabilizes the ion below any single contributing structure"},{"label":"C","text":"equal to the numerical average of the energies of the three contributing structures, since the ion spends equal time as each form"},{"label":"D","text":"equal to the energy of whichever single contributing structure is most stable, since resonance only relabels that structure"}]$op35$::jsonb,
    'B',
    $ex35$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because delocalizing the \(\pi\) electrons over all three \(\text{C-O}\) bonds spreads electron density and lowers the actual ion's energy below that of any single contributing structure. No single Lewis structure of \(\text{CO}_3^{2-}\) is real; each one localizes the \(\text{C=O}\) double bond on one oxygen, but the true ion has three equivalent \(\text{C-O}\) bonds of resonance-averaged character (between a single and a double bond) because the bonding electrons are delocalized over the whole \(\pi\) system. This delocalization is energetically favorable, so the resonance hybrid lies lower in energy (is more stable) than any individual contributing structure, and the energy difference is the resonance stabilization. (Choice A) This reverses the relationship: delocalizing electrons over more atoms lowers, rather than raises, the energy of the actual species, which is precisely why resonance is a stabilizing feature. (Choice C) The hybrid is not a time average in which the molecule flickers among the contributing forms; the contributing structures do not exist as real, interconverting species, and the actual energy is lower than the average rather than equal to it. (Choice D) Resonance is not a mere relabeling of one structure; the delocalized hybrid is genuinely lower in energy than the best single contributing structure, so equating the two ignores the resonance stabilization. Skill 1$ex35$,
    'medium', '5B', $cc35$Nature of molecules and intermolecular interactions$cc35$, 'general-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a35A$Treats delocalization as destabilizing, raising the hybrid above a single structure instead of lowering it$a35A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a35C$Time-averaging / flickering misconception: hybrid energy set equal to the mean of contributing structures$a35C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a35D$Acknowledges resonance but equates the hybrid with the most stable single structure, omitting the extra resonance stabilization$a35D$ FROM q;

-- Q12 [Resonance & Delocalization · easy · Skill 1 · general-chemistry · ans B] (g36)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt36$A chemist compares four neutral molecules: \(\text{CH}_4\), \(\text{SO}_2\) (connectivity O-S-O), \(\text{H}_2\text{O}\), and \(\text{NH}_3\). Only one requires more than one equivalent Lewis structure to represent its bonding. Which molecule exhibits resonance?$qt36$,
    $op36$[{"label":"A","text":"\\(\\text{CH}_4\\)"},{"label":"B","text":"\\(\\text{SO}_2\\)"},{"label":"C","text":"\\(\\text{H}_2\\text{O}\\)"},{"label":"D","text":"\\(\\text{NH}_3\\)"}]$op36$::jsonb,
    'B',
    $ex36$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because \(\text{SO}_2\) has one \(\text{S=O}\) double bond and one \(\text{S-O}\) single bond that can be drawn in two equivalent ways, so its true structure is a resonance hybrid with the second bonding pair delocalized over both S-O positions. Because the two arrangements are equivalent, neither alone describes the molecule, and the actual S-O bonds are identical with a length and energy intermediate between a single and a double bond. (Choice A) \(\text{CH}_4\) contains only four equivalent \(\text{C-H}\) single bonds with no double bond or lone pair to relocate, so a single Lewis structure is sufficient and no resonance exists. (Choice C) \(\text{H}_2\text{O}\) has two \(\text{O-H}\) single bonds and two lone pairs on oxygen with no multiple bond to shift, so it is fully described by one Lewis structure. (Choice D) \(\text{NH}_3\) has three \(\text{N-H}\) single bonds and one lone pair on nitrogen, and with no multiple bonding to delocalize it requires only a single Lewis structure. Skill 1$ex36$,
    'easy', '5B', $cc36$Nature of molecules and intermolecular interactions$cc36$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a36A$Assumes a highly symmetric molecule with multiple identical bonds must have resonance$a36A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a36C$Treats the presence of lone pairs as sufficient to create resonance without a multiple bond to delocalize$a36C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a36D$Believes a lone pair on the central atom alone enables resonance even with only single bonds present$a36D$ FROM q;

-- Q13 [Resonance & Delocalization · medium · Skill 2 · general-chemistry · ans D] (g37)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt37$In the acetate ion \(\text{CH}_3\text{COO}^-\), one resonance structure draws the carboxyl carbon double-bonded to one oxygen and single-bonded to the other (the one bearing the negative charge), while the second structure swaps those two roles. Predict how the two carbon–oxygen bond lengths in the actual ion most likely compare.$qt37$,
    $op37$[{"label":"A","text":"They differ measurably, with the \\(\\text{C=O}\\) bond shorter than the \\(\\text{C-O}^-\\) bond, because the molecule rapidly interconverts between the two structures."},{"label":"B","text":"They differ measurably, with the \\(\\text{C-O}^-\\) bond shorter, because the negative charge contracts the bond to the oxygen that carries it."},{"label":"C","text":"They are equal, each matching a full carbon–oxygen double-bond length, because every \\(\\text{C-O}\\) linkage gains a complete second bonding pair."},{"label":"D","text":"They are equal, each intermediate between a single and a double bond, because the negative charge and the extra bonding pair are delocalized equally over both oxygens."}]$op37$::jsonb,
    'D',
    $ex37$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the two equivalent resonance structures contribute equally, so each carbon–oxygen bond is identical and has a length between that of a single and a double bond. Resonance means the real acetate ion is a single delocalized structure that is the weighted average of the contributors, not a molecule flipping back and forth between them. Because the two drawn structures are equivalent (they differ only in which oxygen holds the double bond and the negative charge), they contribute equally; the second bonding pair and the negative charge are spread evenly over both oxygens. Each \(\text{C-O}\) bond therefore carries about one and a half bonds' worth of bonding density, giving two equal bonds whose length lies between a pure \(\text{C-O}\) single bond and a pure \(\text{C=O}\) double bond. (Choice A) This treats resonance as a physical interconversion ("rapidly interconverts") between two distinct species, but resonance describes one averaged structure, so the bonds do not alternate in length and are not unequal. (Choice B) A localized negative charge does not shorten the bond to the oxygen carrying it; in the real ion the charge is delocalized over both oxygens, so neither \(\text{C-O}\) bond is distinguished as shorter on that basis. (Choice C) Delocalizing one extra bonding pair over two bonds gives each bond only a partial (about one-half) share of a second pair, not a full double bond apiece, so the bonds are intermediate in length rather than full double bonds. Skill 2$ex37$,
    'medium', '5B', $cc37$Nature of molecules and intermolecular interactions$cc37$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a37A$resonance treated as rapid physical interconversion between two real species, predicting unequal alternating bonds$a37A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a37B$localized negative charge claimed to contract the bond to the charge-bearing oxygen, making it shorter$a37B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a37C$recognizes equal bonds but over-assigns a full double bond to each instead of a delocalized half-pair$a37C$ FROM q;

-- Q14 [Resonance & Delocalization · hard · Skill 2 · general-chemistry · ans C] (g38)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Resonance & Delocalization',
    $qt38$Ozone \(\left(\text{O}_3,\ \text{connectivity O-O-O, bent}\right)\) is described by two equivalent resonance structures, in each of which one terminal O-O linkage is a double bond and the other a single bond. Treating these two structures as equal contributors, how do the two O-O bonds in the actual molecule most likely compare?$qt38$,
    $op38$[{"label":"A","text":"The two bonds differ: one is a short \\(\\text{O=O}\\) double bond and the other a longer \\(\\text{O-O}\\) single bond, as drawn in either single structure."},{"label":"B","text":"The two bonds are identical and each is a full \\(\\text{O-O}\\) single bond, because delocalizing the \\(\\pi\\) pair removes the double-bond character entirely."},{"label":"C","text":"The two bonds are identical and each is intermediate in length between a typical \\(\\text{O-O}\\) single bond and an \\(\\text{O=O}\\) double bond."},{"label":"D","text":"The two bonds are identical and each is intermediate in length between an \\(\\text{O=O}\\) double bond and an \\(\\text{O}\\equiv\\text{O}\\) triple bond."}]$op38$::jsonb,
    'C',
    $ex38$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because averaging two equivalent resonance structures, each with one \(\text{O=O}\) and one \(\text{O-O}\) linkage, delocalizes the single \(\pi\) pair over both positions and gives two identical bonds of order \(\approx 1.5\), intermediate between a single and a double bond. Neither resonance structure of \(\text{O}_3\) is a real, separate species; the true molecule is a single resonance hybrid in which the \(\pi\) electron pair is shared equally across both O-O regions. Because each bond therefore carries an average of one single-bond and one double-bond contribution, both bonds are equivalent and their length falls between that of a pure \(\text{O-O}\) single bond (longer, weaker) and a pure \(\text{O=O}\) double bond (shorter, stronger), consistent with the experimental observation that the two O-O distances in ozone are equal. (Choice A) Taking either individual Lewis structure literally predicts one short double bond and one long single bond, but the existence of two equivalent contributors means the hybrid has neither a localized double nor a localized single bond; the measured bond lengths are equal, not distinct. (Choice B) Delocalizing the \(\pi\) pair distributes double-bond character over both positions rather than erasing it; each bond retains roughly half of a double bond's character (order \(\approx 1.5\)), so the bonds are not pure single bonds and are shorter than a typical \(\text{O-O}\) single bond. (Choice C is keyed correct.) (Choice D) Resonance averages a single bond and a double bond to give an order of about 1.5, which lies between a single and a double bond; it does not place the bonds between a double and a triple bond, an assignment that would require double- and triple-bonded contributors that \(\text{O}_3\) does not possess. Skill 2$ex38$,
    'hard', '5B', $cc38$Nature of molecules and intermolecular interactions$cc38$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a38A$reads a single Lewis structure literally, predicting one localized double and one localized single bond instead of equivalent resonance-averaged bonds$a38A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a38B$treats delocalization as canceling double-bond character entirely, yielding pure single bonds rather than fractional (order ~1.5) bonds$a38B$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a38D$places the resonance-averaged bond between a double and a triple bond instead of between a single and a double bond$a38D$ FROM q;

-- Q15 [Bond Length & Bond Energy · easy · Skill 1 · general-chemistry · ans A] (g39)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt39$Hydrogen peroxide \( \text{H}_2\text{O}_2 \) contains an oxygen-oxygen single bond, whereas molecular oxygen \( \text{O}_2 \) contains an oxygen-oxygen double bond. Which oxygen-oxygen bond is most likely the longer of the two?$qt39$,
    $op39$[{"label":"A","text":"The oxygen-oxygen single bond in \\( \\text{H}_2\\text{O}_2 \\)"},{"label":"B","text":"The oxygen-oxygen double bond in \\( \\text{O}_2 \\)"},{"label":"C","text":"Both bonds have the same length because each joins two oxygen atoms"},{"label":"D","text":"The oxygen-oxygen double bond in \\( \\text{O}_2 \\), because the second shared pair stretches the bond"}]$op39$::jsonb,
    'A',
    $ex39$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the oxygen-oxygen bond in \( \text{H}_2\text{O}_2 \) is a single bond (one shared electron pair), while the bond in \( \text{O}_2 \) is a double bond (two shared electron pairs). As OpenStax describes, increasing the number of shared electron pairs between two given atoms increases the bond order and draws the nuclei closer together, so a double bond is shorter (and stronger) than a single bond between the same two atoms. Because the single bond in \( \text{H}_2\text{O}_2 \) has the lower bond order, its nuclei are held farther apart, making it the longer oxygen-oxygen bond. (Choice B) This reverses the relationship: the double bond in \( \text{O}_2 \) has the higher bond order, so its two shared pairs pull the oxygen nuclei closer and make it the shorter bond, not the longer one. (Choice C) Bond length is not fixed by atomic identity alone; for the same pair of atoms, length depends on bond order, so a single bond and a double bond between two oxygens are not equal in length. (Choice D) This contains a process error: adding a second shared electron pair raises the bond order and shortens the bond rather than stretching it, so the double bond in \( \text{O}_2 \) is shorter, not longer. Skill 1$ex39$,
    'easy', '5B', $cc39$Nature of molecules and intermolecular interactions$cc39$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a39B$Assigns the longer bond to the higher-bond-order species, inverting the bond order vs bond length relationship$a39B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a39C$Believes bond length depends only on which atoms are bonded, ignoring bond order$a39C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a39D$Correctly notes a second shared pair but reasons it lengthens rather than shortens the bond$a39D$ FROM q;

-- Q16 [Bond Length & Bond Energy · medium · Skill 2 · general-chemistry · ans B] (g40)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt40$Hydrazine contains an \(\text{N-N}\) single bond, the diazene fragment contains an \(\text{N=N}\) double bond, and molecular nitrogen gas contains an \(\text{N}\equiv\text{N}\) triple bond. Considering only how the number of shared electron pairs between the two nitrogen atoms governs the internuclear distance, which sequence most likely orders these three nitrogen-nitrogen bonds from longest to shortest?$qt40$,
    $op40$[{"label":"A","text":"\\(\\text{N}\\equiv\\text{N} > \\text{N=N} > \\text{N-N}\\)"},{"label":"B","text":"\\(\\text{N-N} > \\text{N=N} > \\text{N}\\equiv\\text{N}\\)"},{"label":"C","text":"\\(\\text{N=N} > \\text{N}\\equiv\\text{N} > \\text{N-N}\\)"},{"label":"D","text":"\\(\\text{N-N} = \\text{N=N} = \\text{N}\\equiv\\text{N}\\), since all three join the same pair of nitrogen atoms"}]$op40$::jsonb,
    'B',
    $ex40$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because, for two bonded atoms of a given element, bond length decreases as bond order increases: each additional shared electron pair pulls the two nuclei closer together, so a single bond is longer than a double bond, which is longer than a triple bond. Between two nitrogen atoms the single bond \(\text{N-N}\) shares one pair, the double bond \(\text{N=N}\) shares two pairs, and the triple bond \(\text{N}\equiv\text{N}\) shares three pairs; the greater the number of shared pairs, the stronger the net attraction drawing the nuclei together and the shorter the internuclear distance. Ordering from longest to shortest therefore gives \(\text{N-N} > \text{N=N} > \text{N}\equiv\text{N}\), with the triple bond in \(\text{N}_2\) being the shortest of the three. (Choice A) This sequence places the triple bond as longest and the single bond as shortest, which inverts the bond-order/bond-length relationship; adding shared pairs shortens, not lengthens, the bond, so the triple bond \(\text{N}\equiv\text{N}\) is the shortest rather than the longest. (Choice C) This sequence treats the double bond as longest and misranks the triple bond above the single bond; while it correctly recognizes that bond order changes length, it does not apply the monotonic rule that length falls steadily as shared pairs increase, so the relative positions of all three are scrambled. (Choice D) Holding the two nuclei to be the same atoms does not make the bond lengths equal; bond length is set by bond order, not merely by the identity of the bonded atoms, so increasing the number of shared electron pairs progressively shortens the bond even though both atoms remain nitrogen. Skill 2$ex40$,
    'medium', '5B', $cc40$Nature of molecules and intermolecular interactions$cc40$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a40A$inverts the bond-order/bond-length relationship, ranking the triple bond as longest and the single bond as shortest$a40A$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a40C$recognizes that bond order affects length but scrambles the monotonic ordering, placing the double bond longest and the triple above the single$a40C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a40D$assumes identical bonded atoms force identical bond lengths, ignoring that bond order sets internuclear distance$a40D$ FROM q;

-- Q17 [Bond Length & Bond Energy · medium · Skill 2 · general-chemistry · ans D] (g41)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt41$The carbon-nitrogen bond is a single bond in methylamine \(\text{CH}_3\text{NH}_2\), a double bond in methanimine \(\text{CH}_2{=}\text{NH}\), and a triple bond in hydrogen cyanide \(\text{H}{-}\text{C}{\equiv}\text{N}\). Ranked by the energy required to break that carbon-nitrogen bond, these three molecules most likely order as$qt41$,
    $op41$[{"label":"A","text":"\\(\\text{CH}_3\\text{NH}_2 > \\text{CH}_2{=}\\text{NH} > \\text{H}{-}\\text{C}{\\equiv}\\text{N}\\)"},{"label":"B","text":"\\(\\text{CH}_3\\text{NH}_2 = \\text{CH}_2{=}\\text{NH} = \\text{H}{-}\\text{C}{\\equiv}\\text{N}\\)"},{"label":"C","text":"\\(\\text{H}{-}\\text{C}{\\equiv}\\text{N} > \\text{CH}_3\\text{NH}_2 > \\text{CH}_2{=}\\text{NH}\\)"},{"label":"D","text":"\\(\\text{H}{-}\\text{C}{\\equiv}\\text{N} > \\text{CH}_2{=}\\text{NH} > \\text{CH}_3\\text{NH}_2\\)"}]$op41$::jsonb,
    'D',
    $ex41$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the carbon-nitrogen triple bond in \(\text{H}{-}\text{C}{\equiv}\text{N}\) shares three electron pairs, the double bond in \(\text{CH}_2{=}\text{NH}\) shares two, and the single bond in \(\text{CH}_3\text{NH}_2\) shares one, and bond energy rises with the number of shared pairs. Each additional shared pair adds bonding electron density between the same two nuclei, so more energy must be supplied to separate the atoms; the triple bond is therefore the strongest and the single bond the weakest, giving \(\text{C}{\equiv}\text{N} > \text{C}{=}\text{N} > \text{C}{-}\text{N}\). The same trend that shortens the bond (more shared pairs pull the nuclei closer) also strengthens it, so bond length and bond energy run in opposite directions across this series. (Choice A) This ordering reverses the relationship by treating the single bond as strongest and the triple bond as weakest, but fewer shared electron pairs give a lower, not higher, bond energy. (Choice B) Equal bond energies would require the three carbon-nitrogen bonds to be identical, yet a single, double, and triple bond share different numbers of electron pairs and therefore differ in strength. (Choice C) This correctly places the triple bond as strongest but then inverts the remaining two, ranking the single bond above the double bond, whereas the double bond shares more electron pairs than the single bond and is the stronger of the two. Skill 2$ex41$,
    'medium', '5B', $cc41$Nature of molecules and intermolecular interactions$cc41$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a41A$fewer shared pairs treated as stronger bond$a41A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a41B$all carbon-nitrogen bonds assumed equal in energy$a41B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a41C$triple ranked strongest but single and double inverted$a41C$ FROM q;

-- Q18 [Bond Length & Bond Energy · hard · Skill 2 · general-chemistry · ans A] (g42)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt42$Acetylene is hydrogenated to ethylene: \(\text{C}_2\text{H}_2(g) + \text{H}_2(g) \rightarrow \text{C}_2\text{H}_4(g)\). Using only the average bond energies \(\text{C}\equiv\text{C} = 839\), \(\text{C}-\text{H} = 413\), \(\text{H}-\text{H} = 436\), and \(\text{C}=\text{C} = 614\) (all in \(\text{kJ}\,\text{mol}^{-1}\)), the estimated \(\Delta H\) for this reaction is closest to which value?$qt42$,
    $op42$[{"label":"A","text":"\\(-165\\ \\text{kJ}\\)"},{"label":"B","text":"\\(+165\\ \\text{kJ}\\)"},{"label":"C","text":"\\(+225\\ \\text{kJ}\\)"},{"label":"D","text":"\\(-601\\ \\text{kJ}\\)"}]$op42$::jsonb,
    'A',
    $ex42$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because \(\Delta H = \sum(\text{bonds broken}) - \sum(\text{bonds formed}) = [839 + 2(413) + 436] - [614 + 4(413)] = 2101 - 2266 = -165\ \text{kJ}\). In the reactants, \(\text{C}_2\text{H}_2\) (connectivity \(\text{H}-\text{C}\equiv\text{C}-\text{H}\)) contributes one \(\text{C}\equiv\text{C}\) and two \(\text{C}-\text{H}\) bonds, and \(\text{H}_2\) contributes one \(\text{H}-\text{H}\) bond, all of which are broken; in the product \(\text{C}_2\text{H}_4\) (connectivity \(\text{H}_2\text{C}=\text{CH}_2\)) one \(\text{C}=\text{C}\) and four \(\text{C}-\text{H}\) bonds are formed, so energy released on bond formation exceeds energy absorbed on bond breaking, giving an exothermic estimate. (Choice B) reverses the sign convention by computing \(\sum(\text{bonds formed}) - \sum(\text{bonds broken})\), which yields \(+165\ \text{kJ}\) and contradicts the defined relationship \(\Delta H = \text{broken} - \text{formed}\). (Choice C) of \(+225\ \text{kJ}\) results from accounting only for the change in the carbon-carbon multiple bond, \(839 - 614\), while ignoring the \(\text{H}-\text{H}\) bond broken and the two additional \(\text{C}-\text{H}\) bonds formed. (Choice D) of \(-601\ \text{kJ}\) omits the \(\text{H}-\text{H}\) bond from the bonds-broken sum, using \([839 + 2(413)] - [614 + 4(413)]\) and thereby undercounting the energy absorbed during bond breaking. Skill 2$ex42$,
    'hard', '5B', $cc42$Nature of molecules and intermolecular interactions$cc42$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a42B$Applies formed minus broken instead of broken minus formed, flipping the sign of an exothermic reaction$a42B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a42C$Considers only the changing carbon multiple bond and ignores the H-H bond broken and the new C-H bonds formed$a42C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a42D$Omits the H-H reactant bond from the bonds-broken tally, undercounting energy absorbed$a42D$ FROM q;

-- Q19 [Bond Length & Bond Energy · hard · Skill 4 · general-chemistry · ans C] (g43)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt43$A reference table lists three carbon-carbon bonds: \(\text{C-C}\) at \(154\ \text{pm}\) and \(348\ \text{kJ/mol}\), \(\text{C=C}\) at \(134\ \text{pm}\) and \(614\ \text{kJ/mol}\), and \(\text{C} \equiv \text{C}\) at \(120\ \text{pm}\) and \(839\ \text{kJ/mol}\). Constrained to these data alone, which conclusion about the relationship among bond length, bond energy, and bond multiplicity is best supported?$qt43$,
    $op43$[{"label":"A","text":"As the number of shared electron pairs rises, the bond lengthens and the bond energy falls, so the triple bond is the longest and weakest of the three."},{"label":"B","text":"Bond energy rises with multiplicity while bond length stays essentially constant near \\(135\\ \\text{pm}\\), because added \\(\\pi\\) bonds add strength without affecting the internuclear distance."},{"label":"C","text":"As the number of shared electron pairs rises, the bond shortens and the bond energy increases, so the shortest bond \\((120\\ \\text{pm})\\) is also the strongest \\((839\\ \\text{kJ/mol})\\)."},{"label":"D","text":"Bond length and bond energy both increase together with multiplicity, so the triple bond is simultaneously the longest and the strongest of the three."}]$op43$::jsonb,
    'C',
    $ex43$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the data show that as bond multiplicity rises from one to three shared pairs the length drops monotonically (\(154 \to 134 \to 120\ \text{pm}\)) while the energy climbs monotonically (\(348 \to 614 \to 839\ \text{kJ/mol}\)), so the shortest bond is also the strongest. Increasing the number of shared electron pairs between the same two atoms pulls the nuclei closer and requires more energy to break, which is exactly the inverse length-energy correlation the tabulated triple, double, and single carbon-carbon bonds display. (Choice A) This reverses both trends: it claims more shared pairs lengthen and weaken the bond, but the table shows the triple bond is the shortest (\(120\ \text{pm}\)) and the highest in energy (\(839\ \text{kJ/mol}\)), not the longest and weakest. (Choice B) Bond length is not constant across the series; it decreases by \(34\ \text{pm}\) from single to triple, so the data contradict the assertion that added \(\pi\) bonds leave the internuclear distance near \(135\ \text{pm}\) unchanged. (Choice C is correct.) (Choice D) Although it correctly pairs higher multiplicity with higher energy, it incorrectly couples that with increasing length; the strongest bond is the shortest, not the longest, so length and energy move in opposite directions rather than together. Skill 4$ex43$,
    'hard', '5B', $cc43$Nature of molecules and intermolecular interactions$cc43$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a43A$more shared pairs read as longer and weaker bond$a43A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a43B$energy rises with multiplicity but length wrongly held constant$a43B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a43D$length and energy assumed to increase together$a43D$ FROM q;

-- Q20 [Bond Length & Bond Energy · medium · Skill 4 · general-chemistry · ans D] (g44)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Length & Bond Energy',
    $qt44$A chemist tabulates the bond dissociation energies of the four hydrogen halides measured in the gas phase: \(\text{H-F}\) at \(570\ \text{kJ/mol}\), \(\text{H-Cl}\) at \(432\ \text{kJ/mol}\), \(\text{H-Br}\) at \(366\ \text{kJ/mol}\), and \(\text{H-I}\) at \(298\ \text{kJ/mol}\). Based on these data, which bond is most easily broken into its constituent atoms?$qt44$,
    $op44$[{"label":"A","text":"The \\(\\text{H-F}\\) bond"},{"label":"B","text":"The \\(\\text{H-Cl}\\) bond"},{"label":"C","text":"The \\(\\text{H-Br}\\) bond"},{"label":"D","text":"The \\(\\text{H-I}\\) bond"}]$op44$::jsonb,
    'D',
    $ex44$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the bond dissociation energy is the energy required to break one mole of a bond homolytically in the gas phase, so the bond with the smallest tabulated value is the weakest and most easily broken. Among the listed values, \(\text{H-I}\) at \(298\ \text{kJ/mol}\) is the lowest, meaning the least energy must be supplied to cleave it; this reflects the trend down the halogen group, where the larger, more diffuse iodine valence orbital overlaps the hydrogen \(1s\) orbital less effectively, lengthening the bond and lowering its dissociation energy. (Choice A) The \(\text{H-F}\) value of \(570\ \text{kJ/mol}\) is the largest in the table, so this is the strongest, hardest-to-break bond rather than the weakest; selecting it reverses the relationship between bond dissociation energy and bond strength. (Choice B) The \(\text{H-Cl}\) value of \(432\ \text{kJ/mol}\) is intermediate and well above the minimum, so this bond is more difficult to break than \(\text{H-I}\). (Choice C) The \(\text{H-Br}\) value of \(366\ \text{kJ/mol}\) is lower than \(\text{H-Cl}\) but still exceeds the \(298\ \text{kJ/mol}\) of \(\text{H-I}\), so it is not the most easily broken; it is the next-weakest, a near-miss that stops one position short of the true minimum. Skill 4$ex44$,
    'medium', '5B', $cc44$Nature of molecules and intermolecular interactions$cc44$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a44A$highest bond dissociation energy chosen as weakest bond$a44A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a44B$intermediate halide cited instead of the minimum$a44B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a44C$next-weakest bond selected, stopping one value short of the lowest$a44C$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch2_questions FROM questions WHERE topic='Bonding & Chemical Interactions' AND subtopic IN ('Ionic Character & Bond Type', 'Resonance & Delocalization', 'Bond Length & Bond Energy');
