-- GenChem Ch3 (Bonding & Chemical Interactions) — Batch 3 of 4: Geometry, Polarity & Dipoles
-- 22 questions, all confidence >=4 (OpenStax Atoms First 2e; stereochemistry verified vs standard organic conventions); AAMC foundation 5B; cross-batch + cross-chapter deduped, audit clean (PASS, 0 genuine conflicts).
-- Re-runnable. Run the four batches IN ORDER (1->2->3->4) in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Bonding & Chemical Interactions' AND subtopic IN ('VSEPR & Molecular Geometry', 'Molecular Polarity', 'Bond Polarity & Dipole Moment');

-- Q1 [VSEPR & Molecular Geometry · medium · Skill 2 · general-chemistry · ans A] (g45)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt45$In gaseous ammonia, \(\text{NH}_3\), the nitrogen atom forms three \(\text{N}-\text{H}\) bonds. Which pairing correctly assigns the electron-pair (electron-domain) geometry and the molecular geometry about that nitrogen?$qt45$,
    $op45$[{"label":"A","text":"Tetrahedral electron-pair geometry; trigonal pyramidal molecular geometry"},{"label":"B","text":"Tetrahedral electron-pair geometry; tetrahedral molecular geometry"},{"label":"C","text":"Trigonal pyramidal electron-pair geometry; trigonal pyramidal molecular geometry"},{"label":"D","text":"Trigonal planar electron-pair geometry; bent molecular geometry"}]$op45$::jsonb,
    'A',
    $ex45$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the four electron domains around nitrogen (three bonding pairs plus one lone pair) arrange tetrahedrally, but only the three bonded atoms define the molecular shape, giving a trigonal pyramidal geometry. VSEPR counts every electron domain when assigning the electron-pair geometry, so four domains always give a tetrahedral electron-pair geometry; the molecular geometry is then read from the positions of the bonded atoms alone, and removing one vertex of the tetrahedron (the lone pair) leaves a trigonal pyramid with bond angles compressed to roughly \(107^\circ\) by the more repulsive lone pair. (Choice B) The electron-pair geometry is correctly identified as tetrahedral, but the molecular geometry is not tetrahedral because one of the four domains is a lone pair rather than a bonded atom, so only three atoms remain to define the shape. (Choice C) Electron-pair geometry is named only from the spatial arrangement of the four domains, which is tetrahedral; trigonal pyramidal is a molecular-geometry term and cannot serve as the electron-pair geometry when four domains are present. (Choice D) Trigonal planar requires only three electron domains, but nitrogen here has four domains, and treating ammonia as having a bent shape understates the number of bonded atoms (three, not two) around the central nitrogen. Skill 2$ex45$,
    'medium', '5B', $cc45$Nature of molecules and intermolecular interactions$cc45$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a45B$Correct electron-pair geometry but fails to subtract the lone pair when naming molecular shape$a45B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a45C$Applies the molecular-geometry label to the electron-pair geometry step$a45C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a45D$Miscounts electron domains, omitting the lone pair to get only three domains$a45D$ FROM q;

-- Q2 [VSEPR & Molecular Geometry · easy · Skill 1 · general-chemistry · ans B] (g46)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt46$In methane, \(\text{CH}_4\), the central carbon holds four bonding regions and zero lone pairs. According to VSEPR theory, the molecular geometry of \(\text{CH}_4\) is$qt46$,
    $op46$[{"label":"A","text":"trigonal pyramidal, with bond angles of roughly \\(107^\\circ\\)"},{"label":"B","text":"tetrahedral, with bond angles of roughly \\(109.5^\\circ\\)"},{"label":"C","text":"square planar, with bond angles of \\(90^\\circ\\)"},{"label":"D","text":"trigonal planar, with bond angles of \\(120^\\circ\\)"}]$op46$::jsonb,
    'B',
    $ex46$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because four bonding regions and zero lone pairs around a central atom force a tetrahedral arrangement with bond angles of about \(109.5^\circ\). VSEPR theory treats the molecular geometry as the shape traced by the bonded atoms once the electron-domain geometry is set: four electron domains spread as far apart as possible adopt a tetrahedron, and because every domain in \(\text{CH}_4\) is a bonding pair (no lone pairs occupy a vertex), the positions of the bonding domains and the positions of the atoms coincide, so the molecular geometry is also tetrahedral. (Choice A) Trigonal pyramidal arises when one of four electron domains is a lone pair, as in \(\text{NH}_3\); methane has zero lone pairs, so no domain is hidden and the angle is not compressed to \(\sim 107^\circ\). (Choice C) Square planar is a six-domain (four bonding, two lone pair) geometry with \(90^\circ\) angles; it requires more than four electron domains, which the carbon in \(\text{CH}_4\) does not have. (Choice D) Trigonal planar corresponds to three electron domains at \(120^\circ\), not four; counting only three bonding regions undercounts the domains present on carbon. Skill 1$ex46$,
    'easy', '5B', $cc46$Nature of molecules and intermolecular interactions$cc46$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a46A$four-domain geometry of a molecule with one lone pair (NH3, trigonal pyramidal) substituted for the zero-lone-pair case$a46A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a46C$square planar geometry applied to a four-bond central atom without recognizing it requires six electron domains$a46C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a46D$electron-domain count read as three instead of four, giving trigonal planar$a46D$ FROM q;

-- Q3 [VSEPR & Molecular Geometry · medium · Skill 2 · general-chemistry · ans C] (g47)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt47$A gaseous hydrogen sulfide molecule, \(\text{H}_2\text{S}\), has a central sulfur atom bonded to two hydrogen atoms and bearing two lone pairs. Given that sulfur sits one period below oxygen and undergoes comparatively little \(s\)-\(p\) mixing, the measured H-S-H bond angle is most likely closest to$qt47$,
    $op47$[{"label":"A","text":"\\(180^\\circ\\)"},{"label":"B","text":"\\(120^\\circ\\)"},{"label":"C","text":"\\(92^\\circ\\)"},{"label":"D","text":"\\(109.5^\\circ\\)"}]$op47$::jsonb,
    'C',
    $ex47$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because \(\text{H}_2\text{S}\) has four regions of electron density around sulfur (two bonding pairs and two lone pairs), giving a tetrahedral electron-pair arrangement and a bent molecular shape. According to OpenStax, lone-pair–lone-pair and lone-pair–bonding-pair repulsions push the bonding pairs together so the angle falls below the ideal tetrahedral value. For sulfur, the larger central atom has poor \(s\)-\(p\) orbital mixing, so its bonding orbitals retain nearly pure \(p\) character; pure \(p\) orbitals are oriented near \(90^\circ\), and the two lone pairs further compress the angle, leaving an H-S-H angle of roughly \(92^\circ\). (Choice A) An angle of \(180^\circ\) describes a linear geometry with two electron domains and no lone pairs on the central atom, which does not match a four-domain bent species carrying two lone pairs. (Choice B) An angle of \(120^\circ\) corresponds to a trigonal-planar arrangement of three electron domains, overcounting the bonding pairs and ignoring the two lone pairs that force a bent, sub-tetrahedral angle. (Choice D) An angle of \(109.5^\circ\) is the ideal tetrahedral angle expected only when all four domains are equivalent bonding pairs; it neglects both the extra lone-pair repulsion and the diminished \(s\)-\(p\) mixing that pull the sulfur angle well below tetrahedral. Skill 2$ex47$,
    'medium', '5B', $cc47$Nature of molecules and intermolecular interactions$cc47$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a47A$linear-geometry-ignores-lone-pairs$a47A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a47B$domain-count-undercounted-to-trigonal-planar$a47B$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a47D$ideal-tetrahedral-angle-ignores-lone-pair-and-orbital-effects$a47D$ FROM q;

-- Q4 [VSEPR & Molecular Geometry · medium · Skill 2 · general-chemistry · ans D] (g48)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt48$In \(\text{SO}_2\) (connectivity O-S-O), the central sulfur retains one lone pair while its two \(\text{S=O}\) linkages count as two bonding regions. Predict the molecular geometry and approximate bond angle at sulfur.$qt48$,
    $op48$[{"label":"A","text":"Trigonal planar, ~120°"},{"label":"B","text":"Trigonal pyramidal, ~107°"},{"label":"C","text":"Linear, ~180°"},{"label":"D","text":"Bent, ~120°"}]$op48$::jsonb,
    'D',
    $ex48$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because sulfur carries three electron regions (two \(\text{S=O}\) bonding regions plus one lone pair), giving a trigonal planar electron-domain arrangement whose lone pair leaves the atoms in a bent shape near \(120^\circ\). Under VSEPR, each multiple bond counts as a single region, so the two \(\text{S=O}\) bonds and the lone pair total three regions; three regions set an ideal trigonal planar electron geometry of \(120^\circ\), but because one region is a lone pair only two of the three positions hold atoms, so the molecular geometry is bent (angular) with an angle slightly compressed from \(120^\circ\) by the more repulsive lone pair (experimentally ~119°). (Choice A) Trigonal planar at \(~120^\circ\) is the electron-domain geometry of the three regions, but it names the arrangement of all regions rather than the arrangement of the atoms, ignoring that the lone pair occupies one position and leaves the two oxygens in a bent atomic shape. (Choice B) Trigonal pyramidal at \(~107^\circ\) corresponds to four electron regions with one lone pair (an \(\text{AX}_3\text{E}\) center such as \(\text{NH}_3\)), which would require treating each \(\text{S=O}\) as contributing a separate region, overcounting to four regions instead of three. (Choice C) Linear at \(~180^\circ\) describes a center with two bonding regions and no lone pair (an \(\text{AX}_2\) center such as \(\text{CO}_2\)), which omits the sulfur lone pair that forces the bond angle closed below \(180^\circ\). Skill 2$ex48$,
    'medium', '5B', $cc48$Nature of molecules and intermolecular interactions$cc48$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a48A$Reports the electron-domain (steric) geometry instead of the molecular geometry of the atoms$a48A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a48B$Counts each double bond as two separate electron regions, inflating three regions to four$a48B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a48C$Applies the AX2 linear result by overlooking the central-atom lone pair$a48C$ FROM q;

-- Q5 [VSEPR & Molecular Geometry · hard · Skill 2 · general-chemistry · ans A] (g49)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt49$In \(\text{SF}_4\), sulfur is the central atom bonded to four fluorine atoms while retaining one lone pair that occupies an equatorial position of the trigonal bipyramidal electron-pair arrangement. Given that constraint, what is the molecular geometry of \(\text{SF}_4\)?$qt49$,
    $op49$[{"label":"A","text":"Seesaw"},{"label":"B","text":"Trigonal bipyramidal"},{"label":"C","text":"Square planar"},{"label":"D","text":"Trigonal pyramidal"}]$op49$::jsonb,
    'A',
    $ex49$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because sulfur in \(\text{SF}_4\) has five electron-pair domains (four bonding pairs plus one lone pair) arranged in a trigonal bipyramid, and removing the lone pair from the count leaves four bonded atoms in the distinctive seesaw shape. The lone pair is placed in an equatorial site, where it experiences only two 90° interactions with the axial bonding pairs rather than the three 90° interactions it would suffer in an axial site; this minimizes lone-pair–bonding-pair repulsion and forces the two axial \(\text{S-F}\) bonds and two equatorial \(\text{S-F}\) bonds into the seesaw arrangement. (Choice B) Trigonal bipyramidal describes the electron-pair geometry of all five domains, but the molecular geometry counts only the four bonded fluorines, so it cannot be the shape of the atoms themselves. (Choice C) Square planar arises from six total domains with two lone pairs (as in \(\text{XeF}_4\)), not from the five-domain, one-lone-pair situation present in \(\text{SF}_4\). (Choice D) Trigonal pyramidal corresponds to four total domains with one lone pair (a tetrahedral electron geometry, as in \(\text{NH}_3\)), which has the wrong number of electron domains for \(\text{SF}_4\). Skill 2$ex49$,
    'hard', '5B', $cc49$Nature of molecules and intermolecular interactions$cc49$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'process_step_confusion', $a49B$reports the electron-pair geometry of all five domains instead of the molecular geometry that ignores the lone pair$a49B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a49C$geometry of a different five-to-six-domain species (XeF4, six domains with two lone pairs) substituted for the target$a49C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a49D$applies a four-domain/one-lone-pair (tetrahedral-derived) result, miscounting total electron domains$a49D$ FROM q;

-- Q6 [VSEPR & Molecular Geometry · hard · Skill 2 · general-chemistry · ans B] (g50)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt50$In \(\text{ClF}_3\), the central chlorine atom is bonded to three fluorine atoms and carries two lone pairs that both occupy equatorial sites of a trigonal bipyramidal electron-pair arrangement. Given this placement of the lone pairs, the molecular geometry of \(\text{ClF}_3\) is most likely$qt50$,
    $op50$[{"label":"A","text":"trigonal planar, with all three \\(\\text{Cl}\\text{-}\\text{F}\\) bonds separated by \\(120^\\circ\\)"},{"label":"B","text":"T-shaped, with the \\(\\text{F}\\text{-}\\text{Cl}\\text{-}\\text{F}\\) angles slightly less than \\(90^\\circ\\)"},{"label":"C","text":"trigonal pyramidal, like \\(\\text{NH}_3\\), with bond angles near \\(107^\\circ\\)"},{"label":"D","text":"trigonal bipyramidal, with two axial and three equatorial \\(\\text{Cl}\\text{-}\\text{F}\\) bonds"}]$op50$::jsonb,
    'B',
    $ex50$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because placing the two equatorial lone pairs in a trigonal bipyramid leaves the three fluorine atoms in the two axial positions and one equatorial position, producing a T-shaped molecule. Chlorine in \(\text{ClF}_3\) has a steric number of 5 (three \(\text{Cl}\text{-}\text{F}\) bonds plus two lone pairs), so its electron-pair geometry is trigonal bipyramidal; the lone pairs preferentially take equatorial sites because that minimizes the strongly repulsive \(90^\circ\) lone-pair interactions, and the remaining bonding pairs span the two axial directions plus one equatorial direction, which describes a T shape. Because the two equatorial lone pairs press the axial \(\text{Cl}\text{-}\text{F}\) bonds toward the equatorial bond, the \(\text{F}\text{-}\text{Cl}\text{-}\text{F}\) angles are compressed to slightly less than \(90^\circ\) rather than the ideal \(90^\circ\). (Choice A) Trigonal planar with \(120^\circ\) angles is the \(\text{AX}_3\) shape obtained by counting only the three bonding pairs; it ignores the two lone pairs on chlorine, which raise the steric number to 5 and change both the electron-pair and molecular geometry. (Choice C) Trigonal pyramidal with angles near \(107^\circ\) is the \(\text{AX}_3\text{E}_1\) geometry of \(\text{NH}_3\), which has only one lone pair and a steric number of 4; \(\text{ClF}_3\) has two lone pairs and a steric number of 5, so it does not adopt the ammonia shape. (Choice D) Trigonal bipyramidal describes the electron-pair geometry of all five electron domains, not the molecular geometry, which counts only the positions of the three bonded fluorine atoms; reporting the arrangement of electron domains instead of the atom framework overstates the shape. Skill 2$ex50$,
    'hard', '5B', $cc50$Nature of molecules and intermolecular interactions$cc50$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a50A$counts only the three bonding pairs (AX3) and ignores the two lone pairs$a50A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a50C$applies the one-lone-pair AX3E1 ammonia geometry to a two-lone-pair AX3E2 species$a50C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a50D$reports the electron-pair geometry instead of the molecular geometry$a50D$ FROM q;

-- Q7 [VSEPR & Molecular Geometry · hard · Skill 2 · general-chemistry · ans C] (g51)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt51$In \(\text{XeF}_2\) the central xenon holds five electron domains, three of which are lone pairs that occupy the equatorial sites of the trigonal bipyramidal electron-pair arrangement. Given that constraint on lone-pair placement, what is the molecular geometry of \(\text{XeF}_2\)?$qt51$,
    $op51$[{"label":"A","text":"Trigonal pyramidal"},{"label":"B","text":"Bent, with an \\(\\text{F}-\\text{Xe}-\\text{F}\\) angle near \\(120^\\circ\\)"},{"label":"C","text":"Linear, with an \\(\\text{F}-\\text{Xe}-\\text{F}\\) angle of \\(180^\\circ\\)"},{"label":"D","text":"T-shaped"}]$op51$::jsonb,
    'C',
    $ex51$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because, with the three lone pairs filling the three equatorial positions of the trigonal bipyramid, the two \(\text{Xe}-\text{F}\) bonding pairs are forced into the axial positions, which lie \(180^\circ\) apart and give a linear molecule. Xenon supplies eight valence electrons; two are used in the two \(\text{Xe}-\text{F}\) single bonds, leaving six electrons as three lone pairs, so the steric number is \(2 + 3 = 5\), an exception to the octet rule giving trigonal bipyramidal electron-pair geometry. VSEPR places lone pairs equatorially because that arrangement gives each lone pair only two close (\(90^\circ\)) neighbors instead of three, minimizing the strongest lone-pair repulsions; the remaining axial sites hold the two fluorines, so the molecular geometry described by the atom positions alone is linear. (Choice A) Trigonal pyramidal arises from a steric number of four with one lone pair (an \(\text{AX}_3\text{E}_1\) case such as \(\text{NH}_3\)); \(\text{XeF}_2\) has only two bonded atoms and a steric number of five, so it cannot be trigonal pyramidal. (Choice B) A bent geometry with an angle near \(120^\circ\) would result if the two fluorines occupied two equatorial sites and a single lone pair the third, but here three lone pairs claim all equatorial sites, pushing the fluorines axial rather than equatorial. (Choice D) A T-shape is the shape of an \(\text{AX}_3\text{E}_2\) species (such as \(\text{ClF}_3\)) with three bonded atoms and two equatorial lone pairs; \(\text{XeF}_2\) has only two bonded fluorines and three lone pairs, so it reduces past the T-shape to a linear arrangement. Skill 2$ex51$,
    'hard', '5B', $cc51$Nature of molecules and intermolecular interactions$cc51$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a51A$applies the steric-number-4 one-lone-pair shape (AX3E) to a steric-number-5 species$a51A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a51B$places the bonding pairs equatorially and a lone pair axially, inverting the lone-pair-equatorial rule to give a ~120 degree bent shape$a51B$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a51D$cites the AX3E2 T-shaped geometry of a neighboring interhalogen instead of the AX2E3 linear case$a51D$ FROM q;

-- Q8 [VSEPR & Molecular Geometry · medium · Skill 2 · general-chemistry · ans D] (g52)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt52$A chemist counts the electron-density regions on the central iodine of the tetrachloroiodate ion \(\text{ICl}_4^-\) and finds four iodine–chlorine bonds together with two nonbonding electron pairs on iodine. Treating this as an \(\text{AX}_4\text{E}_2\) arrangement, the molecular geometry that minimizes electron-pair repulsion is most likely$qt52$,
    $op52$[{"label":"A","text":"tetrahedral, with all four \\(\\text{I}{-}\\text{Cl}\\) bonds directed toward the corners of a tetrahedron at about \\(109.5^\\circ\\)"},{"label":"B","text":"seesaw, with the two lone pairs placed in axial positions of a trigonal bipyramid"},{"label":"C","text":"octahedral, counting all six electron-density regions as \\(\\text{I}{-}\\text{Cl}\\) bonds"},{"label":"D","text":"square planar, with the four chlorine atoms in one plane and the two lone pairs above and below it"}]$op52$::jsonb,
    'D',
    $ex52$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because six regions of electron density around a central atom adopt an octahedral electron-domain arrangement, and for an \(\text{AX}_4\text{E}_2\) species the two lone pairs occupy positions \(180^\circ\) apart (trans, one above and one below the plane) to minimize the stronger lone-pair–lone-pair repulsion, leaving the four \(\text{I}{-}\text{Cl}\) bonding pairs in a single plane. The resulting molecular geometry (the shape defined by atom positions only) is square planar with \(\text{Cl}{-}\text{I}{-}\text{Cl}\) angles of \(90^\circ\). (Choice A) Tetrahedral at \(109.5^\circ\) is the geometry for an \(\text{AX}_4\) center with no lone pairs and only four electron-density regions; \(\text{ICl}_4^-\) has six regions, so its bonding pairs cannot spread to \(109.5^\circ\). (Choice B) Seesaw arises from an \(\text{AX}_4\text{E}_1\) center with five electron-density regions in a trigonal bipyramid; this both miscounts the electron domains as five rather than six and places lone pairs incorrectly, since in any bipyramidal count the single lone pair favors an equatorial site, not an axial one. (Choice C) Treating all six regions as \(\text{I}{-}\text{Cl}\) bonds ignores the two lone pairs that the iodine electron count requires, converting the \(\text{AX}_4\text{E}_2\) case into an \(\text{AX}_6\) case and yielding the wrong octahedral molecular shape. Skill 2.$ex52$,
    'medium', '5B', $cc52$Nature of molecules and intermolecular interactions$cc52$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a52A$counts only the four bonds and ignores the two lone pairs, defaulting to AX4 tetrahedral$a52A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a52B$miscounts electron domains as five (AX4E) and assigns seesaw with lone pairs misplaced axially$a52B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a52C$correct octahedral electron-domain arrangement but neglects the two lone pairs, giving AX6 octahedral molecular shape$a52C$ FROM q;

-- Q9 [VSEPR & Molecular Geometry · medium · Skill 1 · general-chemistry · ans A] (g53)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'VSEPR & Molecular Geometry',
    $qt53$Bromine pentafluoride \(\left(\text{BrF}_5\right)\) has a central bromine atom surrounded by six regions of electron density: five \(\text{Br}-\text{F}\) bonding regions and one lone pair. Assuming the lone pair and the five bonding regions arrange to minimize repulsion, which molecular geometry is expected for \(\text{BrF}_5\)?$qt53$,
    $op53$[{"label":"A","text":"Square pyramidal"},{"label":"B","text":"Octahedral"},{"label":"C","text":"Trigonal bipyramidal"},{"label":"D","text":"Seesaw"}]$op53$::jsonb,
    'A',
    $ex53$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because six regions of electron density around a central atom adopt an octahedral electron-domain arrangement, and when one of those regions is a lone pair, the five bonding regions are left in a square pyramidal molecular geometry. In OpenStax VSEPR terms, an \(\text{AX}_5\text{E}_1\) species (five bonded atoms plus one lone pair) keeps the octahedral electron geometry but the molecular shape is named only from the positions of the bonded atoms, giving a square base of four fluorines with one fluorine at the apex above bromine. (Choice B) Octahedral names the electron-domain geometry produced by all six regions, but the molecular geometry must be assigned from the five bonded atoms only, so the lone pair removes one vertex and the shape is not octahedral. (Choice C) Trigonal bipyramidal is the molecular geometry for five total regions of electron density with no lone pair; it results from counting only the five bonding regions and omitting the lone pair, which undercounts the regions to five. (Choice D) Seesaw is the molecular geometry of an \(\text{AX}_4\text{E}_1\) species built from five regions (four bonding plus one lone pair), a related hypervalent shape but one with a different region count than the six present here. Skill 1.$ex53$,
    'medium', '5B', $cc53$Nature of molecules and intermolecular interactions$cc53$, 'general-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'partial_truth', $a53B$names electron-domain geometry instead of molecular geometry$a53B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a53C$omits the lone pair and counts only five regions$a53C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a53D$recalls a different hypervalent shape from an adjacent region count$a53D$ FROM q;

-- Q10 [Molecular Polarity · easy · Skill 1 · general-chemistry · ans B] (g54)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt54$Carbon dioxide, \(\text{CO}_2\), has a linear O=C=O geometry in which each \(\text{C=O}\) bond is polar. Given this constraint, the net molecular dipole moment of \(\text{CO}_2\) is most accurately described as$qt54$,
    $op54$[{"label":"A","text":"nonzero, because each \\(\\text{C=O}\\) bond is individually polar."},{"label":"B","text":"zero, because the two opposed \\(\\text{C=O}\\) bond dipoles cancel."},{"label":"C","text":"nonzero, because the lone pairs on oxygen create an asymmetric charge distribution."},{"label":"D","text":"zero, because the \\(\\text{C}\\) and \\(\\text{O}\\) atoms have nearly equal electronegativities."}]$op54$::jsonb,
    'B',
    $ex54$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because the molecular dipole is the vector sum of the bond dipoles, and in a linear geometry the two \(\text{C=O}\) bond dipoles point in exactly opposite directions and are equal in magnitude, so they cancel to zero. Molecular polarity depends on both bond polarity and molecular geometry: although each \(\text{C=O}\) bond carries a dipole pointing from \(\text{C}\) toward the more electronegative \(\text{O}\), the \(180^\circ\) O=C=O arrangement places these two vectors antiparallel, giving a net dipole moment of zero. (Choice A) The presence of polar bonds is necessary but not sufficient for a net molecular dipole; the geometric arrangement of those bond dipoles must also be asymmetric, which is not the case for linear \(\text{CO}_2\). (Choice C) The terminal oxygens in \(\text{CO}_2\) do bear lone pairs, but they are symmetrically disposed about the central carbon and do not generate a net asymmetric charge distribution that would produce a molecular dipole. (Choice D) Carbon and oxygen differ appreciably in electronegativity, so each \(\text{C=O}\) bond is genuinely polar; the molecule is nonpolar because of geometric cancellation, not because the bonds are nonpolar. Skill 1$ex54$,
    'easy', '5B', $cc54$Nature of molecules and intermolecular interactions$cc54$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a54A$Assumes polar bonds always yield a net molecular dipole, ignoring geometric vector cancellation$a54A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a54C$Invokes oxygen lone pairs as a source of asymmetry, true for bent molecules but not for symmetric linear CO2$a54C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a54D$Reaches the correct zero-dipole conclusion via the wrong cause, claiming the C-O bonds are nonpolar$a54D$ FROM q;

-- Q11 [Molecular Polarity · medium · Skill 2 · general-chemistry · ans C] (g55)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt55$In \(\text{BF}_3\), boron has no lone pairs and bonds to three fluorine atoms whose higher electronegativity makes each \(\text{B}-\text{F}\) bond polar. Given this electron arrangement, which property most accurately characterizes the molecule overall?$qt55$,
    $op55$[{"label":"A","text":"It is polar because the three \\(\\text{B}-\\text{F}\\) bond dipoles add to a net dipole pointing away from boron."},{"label":"B","text":"It is polar because boron is electron-deficient and carries a partial negative charge relative to fluorine."},{"label":"C","text":"It is nonpolar because the trigonal planar geometry places the three equal \\(\\text{B}-\\text{F}\\) bond dipoles at \\(120^\\circ\\), so they cancel."},{"label":"D","text":"It is nonpolar because the \\(\\text{B}-\\text{F}\\) bonds are essentially nonpolar covalent, leaving no dipoles to sum."}]$op55$::jsonb,
    'C',
    $ex55$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the molecule's three equal \(\text{B}-\text{F}\) bond dipoles are arranged symmetrically at \(120^\circ\) in one plane, so their vector sum is zero. With three bonding pairs and no lone pairs on boron, \(\text{BF}_3\) adopts a trigonal planar geometry; each \(\text{B}-\text{F}\) bond is polar with the dipole pointing toward the more electronegative fluorine, but three identical vectors separated by \(120^\circ\) in a single plane cancel exactly, leaving zero net molecular dipole even though every bond is polar. (Choice A) Three equal coplanar dipoles separated by \(120^\circ\) sum to zero rather than reinforcing into a net dipole, so the symmetry produces a nonpolar molecule. (Choice B) Boron is the less electronegative atom and carries a partial positive charge while fluorine is partial negative, and in any case a uniform redistribution of charge does not by itself make a symmetric molecule polar. (Choice D) The \(\text{B}-\text{F}\) bonds are strongly polar because of the large electronegativity difference between boron and fluorine; the molecule is nonpolar from geometric cancellation of real dipoles, not from an absence of dipoles. Skill 2$ex55$,
    'medium', '5B', $cc55$Nature of molecules and intermolecular interactions$cc55$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a55A$Treats bond dipoles as additively reinforcing instead of performing the geometric vector sum that cancels them$a55A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a55B$Reverses the dipole direction by assigning partial negative charge to boron rather than to the more electronegative fluorine$a55B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a55D$Reaches the correct nonpolar conclusion via the wrong premise that B-F bonds are nonpolar covalent$a55D$ FROM q;

-- Q12 [Molecular Polarity · medium · Skill 2 · general-chemistry · ans D] (g56)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt56$A chemist examining phosphorus trichloride \(\text{PCl}_3\) notes that the central phosphorus atom forms three \(\text{P-Cl}\) bonds and retains one lone pair, giving a trigonal-pyramidal arrangement of the four electron domains. Each \(\text{P-Cl}\) bond is individually polar. Based on this structure, which statement most accurately predicts the net molecular polarity of \(\text{PCl}_3\)?$qt56$,
    $op56$[{"label":"A","text":"It is nonpolar, because the trigonal-pyramidal arrangement directs the three \\(\\text{P-Cl}\\) bond dipoles so that they cancel one another exactly."},{"label":"B","text":"It is nonpolar, because the lone pair on phosphorus produces a dipole that exactly opposes and cancels the sum of the three \\(\\text{P-Cl}\\) bond dipoles."},{"label":"C","text":"It is nonpolar, because phosphorus and chlorine differ too little in electronegativity for the \\(\\text{P-Cl}\\) bonds to carry any appreciable dipole."},{"label":"D","text":"It is polar, because the asymmetric trigonal-pyramidal geometry and the lone pair prevent the three \\(\\text{P-Cl}\\) bond dipoles from canceling, leaving a net dipole."}]$op56$::jsonb,
    'D',
    $ex56$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the overall polarity of a molecule is the vector sum of its individual bond dipoles, and that sum depends on molecular geometry. In \(\text{PCl}_3\) the central phosphorus has four electron domains—three bonding \(\text{P-Cl}\) pairs and one lone pair—so the bonding atoms adopt a trigonal-pyramidal shape rather than a symmetric trigonal-planar one. Because chlorine is more electronegative than phosphorus, each \(\text{P-Cl}\) bond is polar with the negative end toward chlorine. In the trigonal-pyramidal arrangement these three bond dipoles point downward toward the same side of the molecule and do not oppose one another symmetrically, so they fail to cancel; the lone pair adds to this asymmetry. The result is a nonzero net dipole moment directed along the axis through phosphorus, making \(\text{PCl}_3\) a polar molecule. (Choice A) Exact cancellation of three identical bond dipoles requires a symmetric, planar 120-degree arrangement (trigonal planar); the trigonal-pyramidal geometry forced by the lone pair is asymmetric, so the dipoles reinforce rather than cancel. (Choice B) The lone pair does not cancel the bond dipoles—it reinforces the asymmetry by occupying one domain and pushing the bonding pairs to one side, contributing to the net dipole rather than nullifying it. (Choice C) Chlorine (\(\approx 3.0\)) is substantially more electronegative than phosphorus (\(\approx 2.1\)), so each \(\text{P-Cl}\) bond carries a real dipole; the bonds are clearly polar, and the molecular polarity question hinges on geometry, not on a vanishing bond dipole. Skill 2$ex56$,
    'medium', '5B', $cc56$Nature of molecules and intermolecular interactions$cc56$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a56A$treats the asymmetric trigonal-pyramidal geometry as if it produced the exact dipole cancellation that only a symmetric trigonal-planar arrangement gives$a56A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a56B$correctly notes the lone pair but claims it cancels the bond dipoles rather than reinforcing the molecular asymmetry$a56B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a56C$assumes the P-Cl electronegativity difference is negligible, making the bonds nonpolar, instead of recognizing chlorine is far more electronegative$a56C$ FROM q;

-- Q13 [Molecular Polarity · hard · Skill 2 · general-chemistry · ans A] (g57)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt57$Chloroform, \(\text{CHCl}_3\), adopts a tetrahedral arrangement around carbon yet carries a net molecular dipole, unlike \(\text{CCl}_4\). Which feature of \(\text{CHCl}_3\) accounts for its polarity?$qt57$,
    $op57$[{"label":"A","text":"The three \\(\\text{C}-\\text{Cl}\\) bond dipoles and the one \\(\\text{C}-\\text{H}\\) bond dipole are nonequivalent in magnitude, so they cannot vectorially cancel."},{"label":"B","text":"The lone pairs on the three chlorine atoms occupy a fourth tetrahedral position, distorting the geometry into a polar trigonal-pyramidal shape."},{"label":"C","text":"Replacing one chlorine with hydrogen lowers the symmetry to a bent geometry, and bent molecules are always polar."},{"label":"D","text":"The \\(\\text{C}-\\text{H}\\) bond is more polar than each \\(\\text{C}-\\text{Cl}\\) bond, leaving a net dipole pointed from carbon toward hydrogen."}]$op57$::jsonb,
    'A',
    $ex57$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the four bonds radiating from carbon are not all the same, so their individual bond dipoles are unequal and fail to sum to zero. In \(\text{CCl}_4\) the four identical \(\text{C}-\text{Cl}\) dipoles point toward the four vertices of a tetrahedron and cancel exactly by symmetry, giving a nonpolar molecule. In \(\text{CHCl}_3\) one vertex is occupied by an \(\text{H}\) atom: the three \(\text{C}-\text{Cl}\) bonds are strongly polar (\(\text{Cl}\) is much more electronegative than \(\text{C}\), so each dipole points from \(\text{C}\) toward \(\text{Cl}\)), while the \(\text{C}-\text{H}\) bond is only weakly polar. Because these vectors differ in magnitude, the vector sum is nonzero and the molecule is polar, with the net dipole oriented along the \(\text{H}-\text{C}\) axis toward the chlorine-rich side. (Choice B) Although each \(\text{Cl}\) carries lone pairs, those lone pairs do not occupy a bonding position on carbon; the central-atom geometry stays tetrahedral because carbon has four bonding pairs and no lone pairs, so the geometry is not distorted to trigonal pyramidal. (Choice C) Swapping one \(\text{Cl}\) for \(\text{H}\) leaves four electron domains on carbon, so the shape remains tetrahedral, not bent, and "bent molecules are always polar" overstates a geometry rule rather than identifying the operative cause. (Choice D) The polarity assignment is reversed: \(\text{Cl}\) (electronegativity \(\approx 3.0\)) is far more electronegative than \(\text{H}\) (\(\approx 2.1\)) relative to \(\text{C}\) (\(\approx 2.5\)), so the \(\text{C}-\text{Cl}\) bonds are the more polar ones and the net dipole points away from \(\text{H}\) toward the \(\text{Cl}\) atoms. Skill 2$ex57$,
    'hard', '5B', $cc57$Nature of molecules and intermolecular interactions$cc57$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a57B$treating terminal-atom lone pairs as if they alter central-atom VSEPR geometry$a57B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a57C$overgeneralized geometry-to-polarity rule applied with the wrong shape assignment$a57C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a57D$inverted electronegativity ordering giving the wrong net dipole direction$a57D$ FROM q;

-- Q14 [Molecular Polarity · hard · Skill 2 · general-chemistry · ans B] (g58)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt58$Carbon disulfide \( \text{CS}_2 \) and carbonyl sulfide \( \text{OCS} \) are both linear triatomic molecules with the carbon atom in the center. Based on how their bond dipoles combine along the molecular axis, which molecule is expected to possess a net molecular dipole moment?$qt58$,
    $op58$[{"label":"A","text":"\\( \\text{CS}_2 \\), because the two \\( \\text{C}{=}\\text{S} \\) bonds are polar and a molecule containing polar bonds is necessarily polar."},{"label":"B","text":"\\( \\text{OCS} \\), because the \\( \\text{C}{=}\\text{O} \\) and \\( \\text{C}{=}\\text{S} \\) bond dipoles differ in magnitude and do not cancel along the axis."},{"label":"C","text":"\\( \\text{CS}_2 \\), because its bent geometry prevents the two \\( \\text{C}{=}\\text{S} \\) dipoles from pointing in opposite directions."},{"label":"D","text":"\\( \\text{OCS} \\), because oxygen and sulfur sit on opposite ends and their equal but opposite dipoles reinforce each other."}]$op58$::jsonb,
    'B',
    $ex58$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because \( \text{OCS} \) is linear (O=C=S) yet asymmetric: the \( \text{C}{=}\text{O} \) bond dipole and the \( \text{C}{=}\text{S} \) bond dipole point along the same axis but differ in magnitude because oxygen is considerably more electronegative than sulfur. Since the two opposing vectors are unequal, they do not cancel, and a net dipole moment remains directed toward the oxygen end. By contrast, \( \text{CS}_2 \) (S=C=S) is also linear but symmetric: its two identical \( \text{C}{=}\text{S} \) bond dipoles are equal in magnitude and point in exactly opposite directions, so they cancel and the molecule is nonpolar. Molecular polarity is the vector sum of bond dipoles together with molecular shape, as developed in OpenStax Chemistry, so a molecule with polar bonds can still be nonpolar when symmetry makes the dipoles cancel. (Choice A) is incorrect because possessing polar bonds is not sufficient for molecular polarity; in symmetric \( \text{CS}_2 \) the two polar \( \text{C}{=}\text{S} \) dipoles cancel exactly, leaving a nonpolar molecule. (Choice C) is incorrect because \( \text{CS}_2 \) is not bent; with two regions of electron density and no lone pairs on carbon it is linear, and that linear symmetry is precisely what allows the equal \( \text{C}{=}\text{S} \) dipoles to oppose and cancel. (Choice D) names the correct molecule but for a reversed reason: the oxygen and sulfur dipoles do not reinforce, and they are not equal; their unequal opposing magnitudes are exactly why a residual net dipole survives. Skill 2$ex58$,
    'hard', '5B', $cc58$Nature of molecules and intermolecular interactions$cc58$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a58A$polar-bonds-imply-polar-molecule$a58A$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a58C$wrong-geometry-attributed-to-symmetric-triatomic$a58C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a58D$right-molecule-dipoles-reinforce-instead-of-residual$a58D$ FROM q;

-- Q15 [Molecular Polarity · medium · Skill 2 · general-chemistry · ans C] (g59)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Molecular Polarity',
    $qt59$In \(\text{SF}_6\), the central sulfur atom forms six equivalent polar \(\text{S-F}\) bonds with no lone pairs on sulfur. Given this constraint, what is the net molecular dipole moment of \(\text{SF}_6\)?$qt59$,
    $op59$[{"label":"A","text":"Nonzero, because each \\(\\text{S-F}\\) bond is polar and six polar bonds reinforce one another."},{"label":"B","text":"Nonzero, because sulfur exceeds the octet and the expanded valence shell creates an asymmetric charge distribution."},{"label":"C","text":"Zero, because the six identical bond dipoles are arranged octahedrally and their vector sum cancels."},{"label":"D","text":"Zero, because fluorine and sulfur have nearly equal electronegativities, so the individual \\(\\text{S-F}\\) bonds are essentially nonpolar."}]$op59$::jsonb,
    'C',
    $ex59$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the six equivalent \(\text{S-F}\) bond dipoles point toward the six vertices of an octahedron, and this symmetric arrangement makes the vector sum of the dipoles equal to zero. With six bonding regions and no lone pairs on sulfur, VSEPR predicts an octahedral geometry, in which each bond dipole is directly opposed by an identical bond dipole on the opposite side; opposing pairs cancel exactly, so the resultant (net) molecular dipole is zero and \(\text{SF}_6\) is nonpolar even though every \(\text{S-F}\) bond is individually polar. (Choice A) Polar bonds do not "reinforce" simply because there are many of them; molecular polarity depends on the vector sum over the geometry, and in the symmetric octahedral arrangement the bond dipoles oppose and cancel rather than add. (Choice B) Sulfur does expand its valence shell to accommodate six bonds, but exceeding the octet does not by itself create a net dipole; the determining factor is the symmetry of the bond-dipole arrangement, which here is fully symmetric. (Choice D) Sulfur (≈2.6) and fluorine (≈4.0) differ substantially in electronegativity, so the \(\text{S-F}\) bonds are strongly polar; the molecule is nonpolar because of dipole cancellation, not because the bonds lack polarity. Skill 2$ex59$,
    'medium', '5B', $cc59$Nature of molecules and intermolecular interactions$cc59$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a59A$Believing that multiple polar bonds always add to give a nonzero molecular dipole, ignoring vector cancellation by symmetry.$a59A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a59B$Invoking a true but irrelevant fact (expanded octet on sulfur) and wrongly linking it to net polarity.$a59B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a59D$Reaching the correct 'zero' conclusion via a false premise that S-F bonds are nonpolar, reversing the true electronegativity relationship.$a59D$ FROM q;

-- Q16 [Bond Polarity & Dipole Moment · easy · Skill 1 · general-chemistry · ans D] (g60)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt60$In the diatomic molecule \(\text{HF}\), fluorine is more electronegative than hydrogen. Which way does the bond dipole point along the \(\text{H}-\text{F}\) bond?$qt60$,
    $op60$[{"label":"A","text":"From \\(\\text{F}\\) toward \\(\\text{H}\\), because the smaller \\(\\text{H}\\) atom pulls the shared electrons closer to itself"},{"label":"B","text":"The bond has no net dipole, because both atoms share the bonding electrons equally"},{"label":"C","text":"From \\(\\text{F}\\) toward \\(\\text{H}\\), because the more electronegative atom carries the positive end of the dipole"},{"label":"D","text":"From \\(\\text{H}\\) toward \\(\\text{F}\\), because the more electronegative \\(\\text{F}\\) draws the shared electrons toward itself"}]$op60$::jsonb,
    'D',
    $ex60$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the bond dipole points from the partially positive \(\text{H}\) end toward the partially negative \(\text{F}\) end, since the more electronegative \(\text{F}\) pulls the shared bonding pair toward itself. In a polar covalent bond the more electronegative atom acquires the partial negative charge (\(\delta-\)) and the less electronegative atom acquires the partial positive charge (\(\delta+\)); the bond dipole vector by convention points from the \(\delta+\) atom to the \(\delta-\) atom. Because \(\text{F}\) has the higher electronegativity, electron density is displaced toward \(\text{F}\), making \(\text{F}\) the \(\delta-\) end and \(\text{H}\) the \(\delta+\) end, so the dipole points from \(\text{H}\) to \(\text{F}\). (Choice A) Pointing from \(\text{F}\) toward \(\text{H}\) reverses the displacement of electron density; atomic size does not override electronegativity here, and the shared electrons are drawn toward \(\text{F}\), not \(\text{H}\). (Choice B) Equal sharing applies only to a bond between identical atoms with equal electronegativity, whereas \(\text{H}\) and \(\text{F}\) differ substantially in electronegativity, so the bond is polar and does carry a net dipole. (Choice C) The direction is reversed: the more electronegative atom bears the \(\delta-\) (negative) end of the dipole, not the positive end, so the dipole cannot point away from \(\text{F}\) on the basis stated. Skill 1$ex60$,
    'easy', '5B', $cc60$Nature of molecules and intermolecular interactions$cc60$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a60A$dipole direction reversed via atomic-size reasoning$a60A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a60B$polar bond treated as equally shared$a60B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a60C$electronegative atom assigned positive end$a60C$ FROM q;

-- Q17 [Bond Polarity & Dipole Moment · easy · Skill 1 · general-chemistry · ans A] (g61)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt61$In methanol, \(\text{CH}_3\text{OH}\), the carbon and oxygen are directly bonded. For this isolated \(\text{C}-\text{O}\) bond, the partial negative charge resides on which atom, and toward which atom does the bond dipole point?$qt61$,
    $op61$[{"label":"A","text":"The partial negative charge resides on \\(\\text{O}\\), and the bond dipole points from \\(\\text{C}\\) toward \\(\\text{O}\\)."},{"label":"B","text":"The partial negative charge resides on \\(\\text{C}\\), and the bond dipole points from \\(\\text{O}\\) toward \\(\\text{C}\\)."},{"label":"C","text":"The partial negative charge resides on \\(\\text{O}\\), and the bond dipole points from \\(\\text{O}\\) toward \\(\\text{C}\\)."},{"label":"D","text":"The partial negative charge is shared equally, so the \\(\\text{C}-\\text{O}\\) bond carries no net dipole."}]$op61$::jsonb,
    'A',
    $ex61$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because oxygen is more electronegative than carbon, so it draws the shared bonding electrons toward itself, placing the partial negative charge (\(\delta^-\)) on \(\text{O}\) and directing the bond dipole from \(\text{C}\) toward \(\text{O}\). By convention the dipole arrow points from the partial positive end (\(\delta^+\), the less electronegative \(\text{C}\)) toward the partial negative end (\(\delta^-\), the more electronegative \(\text{O}\)); because the electronegativity difference \(\Delta\text{EN}\) between \(\text{C}\) and \(\text{O}\) is nonzero, the bond is polar and a net bond dipole exists. (Choice B) This reverses the polarity, incorrectly placing \(\delta^-\) on \(\text{C}\) and pointing the dipole toward \(\text{C}\), which would only hold if carbon were the more electronegative atom. (Choice C) This correctly locates \(\delta^-\) on \(\text{O}\) but draws the arrow toward \(\text{C}\); the dipole arrow must point toward the partial-negative atom, not away from it. (Choice D) A \(\text{C}-\text{O}\) bond joins atoms of unequal electronegativity, so the electrons are not shared equally and the bond is polar rather than dipole-free. Skill 1$ex61$,
    'easy', '5B', $cc61$Nature of molecules and intermolecular interactions$cc61$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a61B$Swaps which atom is more electronegative, placing the partial negative charge on carbon and reversing the dipole direction$a61B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a61C$Identifies the partial-negative atom correctly but draws the dipole arrow pointing away from it toward the partial-positive atom$a61C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a61D$Treats a bond between atoms of unequal electronegativity as nonpolar with equal electron sharing$a61D$ FROM q;

-- Q18 [Bond Polarity & Dipole Moment · medium · Skill 2 · general-chemistry · ans B] (g62)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt62$Using Pauling electronegativities \(\text{H}=2.20\), \(\text{C}=2.55\), \(\text{N}=3.04\), and \(\text{O}=3.44\), a chemist compares the single bonds \(\text{C}-\text{H}\), \(\text{N}-\text{H}\), and \(\text{O}-\text{H}\). Which bond is most polar?$qt62$,
    $op62$[{"label":"A","text":"\\(\\text{C}-\\text{H}\\), because its small \\(\\Delta\\text{EN}\\) of \\(0.35\\) concentrates the bonding electrons most sharply toward one atom"},{"label":"B","text":"\\(\\text{O}-\\text{H}\\), because its \\(\\Delta\\text{EN}\\) of \\(1.24\\) is the largest of the three"},{"label":"C","text":"\\(\\text{N}-\\text{H}\\), because its \\(\\Delta\\text{EN}\\) of \\(0.84\\) is large enough to make it the most polar of the set"},{"label":"D","text":"All three are equally polar, because each bond shares the identical \\(\\text{H}\\) atom as one partner"}]$op62$::jsonb,
    'B',
    $ex62$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because \(\text{O}-\text{H}\) has the largest electronegativity difference (\(\Delta\text{EN}=3.44-2.20=1.24\)), so its bonding electrons are pulled most strongly toward one atom, giving the greatest bond polarity. Bond polarity scales with the magnitude of \(\Delta\text{EN}\) between the two bonded atoms: a larger difference means a more unequal sharing of the bonding pair and a larger bond dipole. Computing each difference gives \(\text{C}-\text{H}=2.55-2.20=0.35\), \(\text{N}-\text{H}=3.04-2.20=0.84\), and \(\text{O}-\text{H}=3.44-2.20=1.24\), so \(\text{O}-\text{H}>\text{N}-\text{H}>\text{C}-\text{H}\) and \(\text{O}-\text{H}\) is most polar. (Choice A) \(\text{C}-\text{H}\) has the smallest \(\Delta\text{EN}\) of the set, so it is the least polar, not the most; greater polarity corresponds to a larger \(\Delta\text{EN}\), not a smaller one. (Choice C) \(\text{N}-\text{H}\) is genuinely polar and is intermediate in the series, but its \(\Delta\text{EN}\) of \(0.84\) is smaller than the \(1.24\) of \(\text{O}-\text{H}\), so it is not the most polar bond. (Choice D) The bonds are not equally polar, because polarity is governed by the difference in electronegativity between the two partners, and the second atom (\(\text{C}\), \(\text{N}\), or \(\text{O}\)) differs in each case even though \(\text{H}\) is common to all three. Skill 2$ex62$,
    'medium', '5B', $cc62$Nature of molecules and intermolecular interactions$cc62$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a62A$smallest-EN-difference-taken-as-most-polar$a62A$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a62C$intermediate-polar-bond-mistaken-for-the-extreme$a62C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a62D$shared-atom-fixes-polarity-ignoring-the-difference$a62D$ FROM q;

-- Q19 [Bond Polarity & Dipole Moment · easy · Skill 1 · general-chemistry · ans C] (g63)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt63$Within an amino acid backbone, three single bonds connect carbon to its neighbors: \(\text{C}-\text{N}\), \(\text{C}-\text{O}\), and \(\text{C}-\text{C}\). Given the electronegativity values \(\text{C} = 2.5\), \(\text{N} = 3.0\), and \(\text{O} = 3.5\), which of these bonds is the least polar?$qt63$,
    $op63$[{"label":"A","text":"The \\(\\text{C}-\\text{N}\\) bond, because its electronegativity difference of \\(0.5\\) is the smallest nonzero value among the three."},{"label":"B","text":"The \\(\\text{C}-\\text{O}\\) bond, because oxygen's high electronegativity pulls electron density so strongly that the bond behaves as nonpolar."},{"label":"C","text":"The \\(\\text{C}-\\text{C}\\) bond, because its electronegativity difference of \\(0\\) leaves the bonding electrons shared equally."},{"label":"D","text":"The \\(\\text{C}-\\text{N}\\) bond, because nitrogen lies between carbon and oxygen and therefore cancels the bond dipole."}]$op63$::jsonb,
    'C',
    $ex63$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is C because the two bonded carbons have identical electronegativities, giving an electronegativity difference of \(0\) and a bond in which the shared electrons are distributed equally. Bond polarity scales with the absolute electronegativity difference \(\Delta\text{EN}\) between the two bonded atoms: the larger the \(\Delta\text{EN}\), the more the shared pair is displaced toward the more electronegative atom and the more polar the bond. Here \(\text{C}-\text{N}\) has \(\Delta\text{EN} = |2.5 - 3.0| = 0.5\) and \(\text{C}-\text{O}\) has \(\Delta\text{EN} = |2.5 - 3.5| = 1.0\), while \(\text{C}-\text{C}\) has \(\Delta\text{EN} = |2.5 - 2.5| = 0\); a bond between two atoms of the same element is purely covalent (nonpolar), so \(\text{C}-\text{C}\) is the least polar. (Choice A) The \(\text{C}-\text{N}\) bond has the smallest nonzero \(\Delta\text{EN}\) of \(0.5\), but it is still larger than the \(0\) difference of \(\text{C}-\text{C}\), so \(\text{C}-\text{N}\) is more polar, not the least polar. (Choice B) A large electronegativity difference such as the \(1.0\) for \(\text{C}-\text{O}\) makes a bond more polar, not nonpolar; strong unequal sharing produces the greatest partial charges and the largest bond dipole among the three. (Choice D) The polarity of a single \(\text{C}-\text{N}\) bond is set by the \(\Delta\text{EN}\) of its two atoms alone; an intermediate electronegativity for nitrogen relative to oxygen does not cancel that bond's dipole, and there is no separate \(\text{C}-\text{O}\) dipole acting along the \(\text{C}-\text{N}\) bond to oppose it. Skill 1$ex63$,
    'easy', '5B', $cc63$Nature of molecules and intermolecular interactions$cc63$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a63A$smallest-nonzero-EN-difference-mistaken-for-least-polar$a63A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a63B$large-EN-difference-equated-with-nonpolar$a63B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a63D$intermediate-electronegativity-cancels-single-bond-dipole$a63D$ FROM q;

-- Q20 [Bond Polarity & Dipole Moment · medium · Skill 2 · general-chemistry · ans D] (g64)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt64$In the gas-phase diatomics \(\text{H}-\text{Cl}\), \(\text{H}-\text{Br}\), and \(\text{H}-\text{I}\), the Pauling electronegativities are \(\text{H} = 2.1\), \(\text{Cl} = 3.0\), \(\text{Br} = 2.8\), and \(\text{I} = 2.5\). Ranked from largest to smallest bond-dipole magnitude, the three bonds most likely fall in which order?$qt64$,
    $op64$[{"label":"A","text":"\\(\\text{H}-\\text{I} > \\text{H}-\\text{Br} > \\text{H}-\\text{Cl}\\)"},{"label":"B","text":"\\(\\text{H}-\\text{Cl} > \\text{H}-\\text{I} > \\text{H}-\\text{Br}\\)"},{"label":"C","text":"\\(\\text{H}-\\text{Cl} \\approx \\text{H}-\\text{Br} \\approx \\text{H}-\\text{I}\\) (all essentially equal)"},{"label":"D","text":"\\(\\text{H}-\\text{Cl} > \\text{H}-\\text{Br} > \\text{H}-\\text{I}\\)"}]$op64$::jsonb,
    'D',
    $ex64$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is D because the bond-dipole magnitude tracks the absolute electronegativity difference \(|\Delta\text{EN}|\) between the bonded atoms, and these differences fall as \(\text{H}-\text{Cl} (0.9) > \text{H}-\text{Br} (0.7) > \text{H}-\text{I} (0.4)\). For a two-atom bond the dipole points toward the more electronegative atom and grows as the partner atoms share the bonding electrons more unequally; here hydrogen is common to all three bonds, so the ranking is set entirely by how electronegative the halogen is relative to hydrogen. Computing \(|\Delta\text{EN}|\) gives \(|2.1-3.0| = 0.9\) for \(\text{H}-\text{Cl}\), \(|2.1-2.8| = 0.7\) for \(\text{H}-\text{Br}\), and \(|2.1-2.5| = 0.4\) for \(\text{H}-\text{I}\), so the bond dipole is largest for \(\text{H}-\text{Cl}\) and smallest for \(\text{H}-\text{I}\). (Choice A) This is the exact reverse ordering, which would follow from ranking by increasing halogen size or polarizability rather than by \(|\Delta\text{EN}|\); a larger, more diffuse halogen actually has a smaller electronegativity difference with hydrogen and therefore a smaller, not larger, bond dipole. (Choice B) This correctly identifies \(\text{H}-\text{Cl}\) as the largest but transposes the lower two, placing \(\text{H}-\text{I}\) above \(\text{H}-\text{Br}\); the differences \(0.7\) for \(\text{H}-\text{Br}\) and \(0.4\) for \(\text{H}-\text{I}\) show \(\text{H}-\text{Br}\) is the more polar of the pair. (Choice C) Treating the three bond dipoles as equal ignores that the halogen electronegativities differ \((3.0, 2.8, 2.5)\); because hydrogen is shared while the halogen varies, the \(|\Delta\text{EN}|\) values are distinct and the dipoles are not equal. Skill 2$ex64$,
    'medium', '5B', $cc64$Nature of molecules and intermolecular interactions$cc64$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a64A$ranks bond dipole by increasing halogen size/polarizability, fully inverting the electronegativity-difference trend$a64A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a64B$identifies the largest dipole correctly but transposes the two smaller halogens from a faulty difference comparison$a64B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a64C$assumes a shared hydrogen makes all H-halogen bond dipoles equal, ignoring the varying halogen electronegativity$a64C$ FROM q;

-- Q21 [Bond Polarity & Dipole Moment · hard · Skill 4 · general-chemistry · ans A] (g65)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt65$A chemist uses the Pauling electronegativity values \(\text{C}=2.55\), \(\text{F}=3.98\), \(\text{Cl}=3.16\), \(\text{Br}=2.96\), and \(\text{I}=2.66\) to compare the four isolated carbon-halogen bonds \(\text{C}-\text{F}\), \(\text{C}-\text{Cl}\), \(\text{C}-\text{Br}\), and \(\text{C}-\text{I}\). Ranking these bonds from largest to smallest bond-dipole magnitude gives which order?$qt65$,
    $op65$[{"label":"A","text":"\\(\\text{C}-\\text{F} > \\text{C}-\\text{Cl} > \\text{C}-\\text{Br} > \\text{C}-\\text{I}\\)"},{"label":"B","text":"\\(\\text{C}-\\text{I} > \\text{C}-\\text{Br} > \\text{C}-\\text{Cl} > \\text{C}-\\text{F}\\)"},{"label":"C","text":"\\(\\text{C}-\\text{Cl} > \\text{C}-\\text{F} > \\text{C}-\\text{Br} > \\text{C}-\\text{I}\\)"},{"label":"D","text":"\\(\\text{C}-\\text{F} > \\text{C}-\\text{I} > \\text{C}-\\text{Cl} > \\text{C}-\\text{Br}\\)"}]$op65$::jsonb,
    'A',
    $ex65$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is A because the bond-dipole magnitude of a two-atom bond scales with the electronegativity difference \(\Delta\text{EN}\) between the bonded atoms, and the given values yield \(\Delta\text{EN}\) of \(1.43\) for \(\text{C}-\text{F}\), \(0.61\) for \(\text{C}-\text{Cl}\), \(0.41\) for \(\text{C}-\text{Br}\), and \(0.11\) for \(\text{C}-\text{I}\). In every one of these bonds the halogen is more electronegative than carbon, so each bond is polarized as \(\text{C}^{\delta+}-\text{X}^{\delta-}\); the larger the \(\Delta\text{EN}\), the greater the partial-charge separation and thus the larger the bond dipole. Because \(1.43 > 0.61 > 0.41 > 0.11\), the dipole magnitudes decrease in the order \(\text{C}-\text{F} > \text{C}-\text{Cl} > \text{C}-\text{Br} > \text{C}-\text{I}\), matching the decreasing electronegativity of the halogen down the group. (Choice B) This reverses the relationship by ordering the bonds from smallest to largest \(\Delta\text{EN}\); iodine has the electronegativity closest to carbon, so \(\text{C}-\text{I}\) is the least polar bond, not the most. (Choice C) Placing \(\text{C}-\text{Cl}\) above \(\text{C}-\text{F}\) ignores that fluorine has the largest electronegativity (\(3.98\)) and therefore the largest \(\Delta\text{EN}\) with carbon; chlorine cannot produce a larger bond dipole than fluorine. (Choice D) Inserting \(\text{C}-\text{I}\) into second place conflates the long \(\text{C}-\text{I}\) bond length with a large dipole, but bond-dipole magnitude here is governed by the small \(\Delta\text{EN}\) of \(0.11\), making \(\text{C}-\text{I}\) the smallest, not the second-largest, dipole. Skill 4$ex65$,
    'hard', '5B', $cc65$Nature of molecules and intermolecular interactions$cc65$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a65B$Orders bonds by increasing rather than decreasing electronegativity difference, inverting the dipole ranking$a65B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a65C$Treats chlorine as more polarizing than fluorine toward carbon, contradicting the larger fluorine electronegativity$a65C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a65D$Substitutes bond length for electronegativity difference as the determinant of bond-dipole magnitude$a65D$ FROM q;

-- Q22 [Bond Polarity & Dipole Moment · hard · Skill 4 · general-chemistry · ans B] (g66)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Bonding & Chemical Interactions', 'Bond Polarity & Dipole Moment',
    $qt66$A reference card lists electronegativity-difference values for four covalent bonds: \(\text{S}-\text{H}\) at \(\Delta\text{EN} = 0.38\), \(\text{C}-\text{F}\) at \(\Delta\text{EN} = 1.43\), \(\text{Si}-\text{O}\) at \(\Delta\text{EN} = 1.54\), and \(\text{H}-\text{F}\) at \(\Delta\text{EN} = 1.78\). Using only these tabulated values, the bond that most likely carries the greatest partial charge separation is$qt66$,
    $op66$[{"label":"A","text":"the \\(\\text{C}-\\text{F}\\) bond, because fluorine is the most electronegative element listed."},{"label":"B","text":"the \\(\\text{H}-\\text{F}\\) bond, whose \\(\\Delta\\text{EN} = 1.78\\) is the largest tabulated value."},{"label":"C","text":"the \\(\\text{Si}-\\text{O}\\) bond, whose \\(\\Delta\\text{EN} = 1.54\\) is the second-largest tabulated value."},{"label":"D","text":"the \\(\\text{S}-\\text{H}\\) bond, whose \\(\\Delta\\text{EN} = 0.38\\) is the smallest tabulated value."}]$op66$::jsonb,
    'B',
    $ex66$This is a General Chemistry question that falls under the content category 'Nature of molecules and intermolecular interactions'. The answer to this question is B because the partial charge separation of a covalent bond grows with the electronegativity difference between the bonded atoms, and \(\text{H}-\text{F}\) carries the largest tabulated \(\Delta\text{EN}\) of \(1.78\). A larger \(\Delta\text{EN}\) means the more electronegative atom pulls the shared electron pair more strongly toward itself, building up a larger partial negative charge (\(\delta^-\)) on that atom and a matching partial positive charge (\(\delta^+\)) on its partner; this unequal sharing is precisely what a more polar bond, with greater partial ionic character, expresses. Among the four values given, the ranking is \(\text{H}-\text{F}\,(1.78) > \text{Si}-\text{O}\,(1.54) > \text{C}-\text{F}\,(1.43) > \text{S}-\text{H}\,(0.38)\), so the bond with the maximum \(\Delta\text{EN}\) is \(\text{H}-\text{F}\). (Choice A) Partial charge separation is set by the difference in electronegativity between the two bonded atoms, not by the absolute electronegativity of either atom alone; although fluorine is the most electronegative element listed, the \(\text{C}-\text{F}\) value of \(1.43\) is smaller than \(\Delta\text{EN}\) for \(\text{H}-\text{F}\), so the presence of fluorine does not by itself maximize the charge separation. (Choice C) This correctly identifies \(\Delta\text{EN}\) as the governing quantity but selects the second-largest tabulated value, \(1.54\) for \(\text{Si}-\text{O}\), rather than the maximum; greatest partial charge separation tracks the single largest \(\Delta\text{EN}\), which is the \(1.78\) of \(\text{H}-\text{F}\). (Choice D) The smallest \(\Delta\text{EN}\) corresponds to the most nearly equal sharing and therefore the least partial charge separation; treating the smallest value, \(0.38\) for \(\text{S}-\text{H}\), as the most polar inverts the relationship between \(\Delta\text{EN}\) and bond polarity. Skill 4$ex66$,
    'hard', '5B', $cc66$Nature of molecules and intermolecular interactions$cc66$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a66A$absolute electronegativity of the most electronegative atom used in place of the electronegativity difference$a66A$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a66C$correct criterion applied but second-largest delta-EN selected instead of the maximum$a66C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a66D$smallest delta-EN treated as greatest partial charge separation, inverting polarity-vs-delta-EN$a66D$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch3_questions FROM questions WHERE topic='Bonding & Chemical Interactions' AND subtopic IN ('VSEPR & Molecular Geometry', 'Molecular Polarity', 'Bond Polarity & Dipole Moment');
