-- GenChem Ch10 (Acids & Bases) — Batch 2 of 4: Acid-Base Definitions & Conjugate Pairs + Salt Hydrolysis
-- 26 questions, all confidence >=4 (verified vs OpenStax Chemistry: Atoms First 2e + standard MCAT references; every calculation independently re-computed).
-- Cross-batch + cross-chapter deduped; final dedup audit PASS (0 genuine conflicts) after the systematic recall-answer-leak sweep.
-- AAMC foundations in this batch: 5A (per-row foundation/content_category/discipline below). Answer key balanced A/B/C/D = 24/24/24/24 across the full 96-question chapter.
-- Out of MCAT scope and deliberately excluded: normality / equivalents / gram-equivalent weight (Ch10.3 polyvalence-in-normality).
-- Re-runnable: subtopic-scoped DELETE. Run the four batches in any order in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Acids & Bases' AND subtopic IN ('Definitions & Conjugate Acid-Base Pairs', 'Salt Hydrolysis & pH of Salt Solutions');

-- Q1 [Definitions & Conjugate Acid-Base Pairs · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g33)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt33$Four substances are each dissolved separately in pure water. By the Arrhenius definition, which one is an acid because dissolving it raises \([\text{H}^+]\) (i.e., \([\text{H}_3\text{O}^+]\)) above its value in pure water?$qt33$,
    $op33$[{"label":"A","text":"\\(\\text{HCl}\\)"},{"label":"B","text":"\\(\\text{NaOH}\\)"},{"label":"C","text":"\\(\\text{NaCl}\\)"},{"label":"D","text":"\\(\\text{C}_6\\text{H}_{12}\\text{O}_6\\) (glucose)"}]$op33$::jsonb,
    'A',
    $ex33$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because the Arrhenius definition of an acid is a substance that increases the concentration of hydrogen ions, \([\text{H}^+]\) (equivalently \([\text{H}_3\text{O}^+]\)), when dissolved in water. Hydrogen chloride dissociates essentially completely in water, \(\text{HCl} \rightarrow \text{H}^+ + \text{Cl}^-\), so it releases \(\text{H}^+\) and drives \([\text{H}^+]\) above the \(10^{-7}\ \text{M}\) value of pure water, lowering the \(\text{pH}\). That is exactly the behavior the Arrhenius definition labels an acid. (Choice B) \(\text{NaOH}\) dissolves to give \(\text{Na}^+\) and \(\text{OH}^-\); by raising the hydroxide concentration it is the Arrhenius definition of a base, not an acid, and it lowers \([\text{H}^+]\) rather than raising it. (Choice C) \(\text{NaCl}\) is the salt of a strong acid and a strong base; neither \(\text{Na}^+\) nor \(\text{Cl}^-\) hydrolyzes, so the solution stays neutral and \([\text{H}^+]\) is unchanged from pure water, making it neither an Arrhenius acid nor base. (Choice D) Glucose is a nonelectrolyte that dissolves as intact neutral molecules without releasing any ions, so it does not change \([\text{H}^+]\) and cannot be an Arrhenius acid. Skill 1$ex33$,
    'easy', '5A', $cc33$Acid-Base Equilibria (GC, BC)$cc33$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a33B$Identifying a strong base (raises [OH-], lowers [H+]) as the acid by reversing the acid/base relationship$a33B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a33C$Treating a neutral salt of a strong acid and strong base as an acid because it dissociates into ions$a33C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a33D$Mistaking a soluble nonelectrolyte that dissolves but does not ionize for an acid$a33D$ FROM q;

-- Q2 [Definitions & Conjugate Acid-Base Pairs · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g34)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt34$A chemistry student dissolves ammonia (\(\text{NH}_3\)) in water and observes that the resulting solution turns red litmus blue, a hallmark of a basic solution. The student is puzzled because the formula \(\text{NH}_3\) contains no hydroxide (\(\text{OH}^-\)) group, so the Arrhenius framework offers no way to classify it as a base, even though a broader framework does. Which statement correctly explains why the Arrhenius definition fails here while a broader definition succeeds?$qt34$,
    $op34$[{"label":"A","text":"The litmus result is misleading and \\(\\text{NH}_3\\) is not actually basic; because its formula contains no \\(\\text{OH}^-\\), neither the Arrhenius nor any broader definition can treat \\(\\text{NH}_3\\) as a base."},{"label":"B","text":"The Arrhenius definition recognizes a base only if it dissociates to release \\(\\text{OH}^-\\) ions, and \\(\\text{NH}_3\\) has no \\(\\text{OH}^-\\) to release; the broader Brønsted–Lowry definition classifies \\(\\text{NH}_3\\) as a base because it accepts a proton from water, generating \\(\\text{NH}_4^+\\) and \\(\\text{OH}^-\\)."},{"label":"C","text":"The Arrhenius definition does in fact classify \\(\\text{NH}_3\\) as a base, because the nitrogen atom carries a lone pair of electrons that the definition counts as the source of basicity."},{"label":"D","text":"The solution is basic only because the dissolved water itself supplies \\(\\text{OH}^-\\), so the basic character has nothing to do with the \\(\\text{NH}_3\\) and no acid–base definition needs to invoke the \\(\\text{NH}_3\\) at all."}]$op34$::jsonb,
    'B',
    $ex34$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because the Arrhenius model is restricted to substances that, when dissolved in water, dissociate to release \(\text{OH}^-\) (for a base) or \(\text{H}^+\) (for an acid). Ammonia contains no \(\text{OH}^-\) group within its formula, so the Arrhenius framework has no mechanism to label it a base, even though the solution is observably basic. The broader Brønsted–Lowry definition removes this limitation by defining a base as a proton acceptor: \(\text{NH}_3\) accepts a proton from a water molecule (\(\text{NH}_3 + \text{H}_2\text{O} \rightleftharpoons \text{NH}_4^+ + \text{OH}^-\)), and the \(\text{OH}^-\) liberated from the water is what raises the pH and turns litmus blue. (Choice A) Ammonia is genuinely basic; the litmus test, the elevated \([\text{OH}^-]\), and the measured pH all confirm this, so the premise that it is not actually a base is false. (Choice C) Recognizing basicity from a lone pair of electrons is the criterion of the Lewis definition, not the Arrhenius definition; the Arrhenius framework says nothing about lone pairs and cannot classify \(\text{NH}_3\) at all. (Choice D) Pure water is neutral, with equal \([\text{H}_3\text{O}^+]\) and \([\text{OH}^-]\); the excess \(\text{OH}^-\) that makes the solution basic arises specifically because \(\text{NH}_3\) accepts protons from water and shifts that balance, so the \(\text{NH}_3\) is the cause of the basicity. Skill 1$ex34$,
    'easy', '5A', $cc34$Acid-Base Equilibria (GC, BC)$cc34$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a34A$denying an observed property because the expected functional group is absent from the formula$a34A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a34C$attributing the lone-pair (Lewis) criterion to the Arrhenius definition$a34C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a34D$crediting the solvent rather than the solute for the solution's acid-base character$a34D$ FROM q;

-- Q3 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g35)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt35$When formic acid and cyanide ion are combined in aqueous solution, the proton-transfer reaction \(\text{HCOOH} + \text{CN}^- \rightarrow \text{HCOO}^- + \text{HCN}\) takes place, and monitoring of the mixture shows formate \((\text{HCOO}^-)\) and \(\text{HCN}\) steadily accumulating. Which assignment of the Brønsted–Lowry acid and the Brønsted–Lowry base among the two reactants is consistent with this observed proton transfer?$qt35$,
    $op35$[{"label":"A","text":"\\(\\text{HCOOH}\\) is the base, because its more electronegative oxygen makes it the proton acceptor, and \\(\\text{CN}^-\\) is the acid that supplies the proton."},{"label":"B","text":"\\(\\text{CN}^-\\) is the acid, donating a proton to become \\(\\text{HCN}\\), and \\(\\text{HCOOH}\\) is the base, accepting that proton to become \\(\\text{HCOO}^-\\)."},{"label":"C","text":"\\(\\text{CN}^-\\) is the acid, because it ends up bearing the transferred proton as \\(\\text{HCN}\\), and \\(\\text{HCOOH}\\) is the base it took the proton from."},{"label":"D","text":"\\(\\text{HCOOH}\\) is the acid, donating a proton to become \\(\\text{HCOO}^-\\), and \\(\\text{CN}^-\\) is the base, accepting that proton to become \\(\\text{HCN}\\)."}]$op35$::jsonb,
    'D',
    $ex35$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because a Brønsted–Lowry acid is the proton donor and a Brønsted–Lowry base is the proton acceptor in a single proton-transfer event. Tracking the atoms across the arrow shows that \(\text{HCOOH}\) loses its acidic proton to become \(\text{HCOO}^-\); having donated a proton, \(\text{HCOOH}\) is therefore the acid. The \(\text{CN}^-\) ion gains that proton to become \(\text{HCN}\); having accepted a proton, \(\text{CN}^-\) is therefore the base. The accumulation of \(\text{HCOO}^-\) and \(\text{HCN}\) confirms this direction of transfer, with \(\text{HCOOH}/\text{HCOO}^-\) and \(\text{HCN}/\text{CN}^-\) forming the two conjugate pairs. (Choice A) This claims \(\text{HCOOH}\) is the base because oxygen is highly electronegative, but Brønsted–Lowry classification depends on whether a species donates or accepts a proton, not on the electronegativity of an atom it contains; \(\text{HCOOH}\) releases its proton and is the acid (misconception). (Choice B) This reverses the roles: it labels the proton acceptor \(\text{CN}^-\) as the donor and the proton donor \(\text{HCOOH}\) as the acceptor. The species that loses a proton is the acid and the species that gains one is the base, so this assignment inverts both definitions (reversed_relationship). (Choice C) This identifies \(\text{CN}^-\) as the acid by pointing to the product \(\text{HCN}\) that carries the proton, but the acid is defined by the act of donating a proton during the reaction, not by which species ends up holding the proton afterward; \(\text{CN}^-\) acquires the proton, so it is the base, not the acid (process_step_confusion). Skill 4$ex35$,
    'medium', '5A', $cc35$Acid-Base Equilibria (GC, BC)$cc35$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a35A$Uses oxygen's electronegativity to assign the base role instead of proton-transfer behavior$a35A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a35B$Acid and base roles swapped (donor labeled acceptor and vice versa)$a35B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a35C$Calls the proton-gaining product's parent the acid by tracking where the proton lands rather than which species donated it$a35C$ FROM q;

-- Q4 [Definitions & Conjugate Acid-Base Pairs · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g36)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt36$Methylamine, \(\text{CH}_3\text{NH}_2\), is a weak base that reacts with water by accepting exactly one proton at its nitrogen atom. What is the conjugate acid formed when methylamine accepts this single proton?$qt36$,
    $op36$[{"label":"A","text":"\\(\\text{OH}^-\\)"},{"label":"B","text":"\\(\\text{CH}_3\\text{NH}^-\\)"},{"label":"C","text":"\\(\\text{CH}_3\\text{NH}_3^+\\)"},{"label":"D","text":"\\(\\text{CH}_2\\text{NH}_2^-\\)"}]$op36$::jsonb,
    'C',
    $ex36$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. A Bronsted-Lowry base accepts a proton (\(\text{H}^+\)), and its conjugate acid is the species formed after that proton has been added. Adding one \(\text{H}^+\) increases the hydrogen count by one and the overall charge by one unit. The answer to this question is C because adding a single proton to neutral \(\text{CH}_3\text{NH}_2\) at the nitrogen gives \(\text{CH}_3\text{NH}_3^+\) (the methylammonium ion), which has one more hydrogen and a charge of \(+1\), exactly as required for the conjugate acid of a base. (Choice A) \(\text{OH}^-\) is the partner species generated from the water molecule that donates the proton (\(\text{CH}_3\text{NH}_2 + \text{H}_2\text{O} \rightleftharpoons \text{CH}_3\text{NH}_3^+ + \text{OH}^-\)); it is the conjugate base of water in this reaction, not the conjugate acid of methylamine. (Choice B) \(\text{CH}_3\text{NH}^-\) results from removing a proton from methylamine rather than adding one; that species is the conjugate base of methylamine, not its conjugate acid. (Choice D) \(\text{CH}_2\text{NH}_2^-\) is formed by stripping a hydrogen from the carbon atom, which is neither the site of proton acceptance nor an acid-base conjugate of methylamine. Skill 1$ex36$,
    'easy', '5A', $cc36$Acid-Base Equilibria (GC, BC)$cc36$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a36A$Selected the water-derived partner species (OH-) rather than the protonated base itself$a36A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a36B$Lost a proton instead of gaining one (formed the conjugate base, not the conjugate acid)$a36B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a36D$Removed a hydrogen from carbon instead of adding a proton to nitrogen$a36D$ FROM q;

-- Q5 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g37)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt37$In a buffered solution the bicarbonate ion \(\text{HCO}_3^-\) acts as a Brønsted–Lowry acid by donating one proton to a surrounding water molecule. Which species is the conjugate base produced by this single proton donation?$qt37$,
    $op37$[{"label":"A","text":"\\(\\text{CO}_3^{2-}\\)"},{"label":"B","text":"\\(\\text{H}_2\\text{CO}_3\\)"},{"label":"C","text":"\\(\\text{CO}_3^{-}\\)"},{"label":"D","text":"\\(\\text{OH}^-\\)"}]$op37$::jsonb,
    'A',
    $ex37$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because a Brønsted–Lowry conjugate base is what remains after an acid donates exactly one proton (\(\text{H}^+\)), and removing one \(\text{H}^+\) from \(\text{HCO}_3^-\) yields the carbonate ion \(\text{CO}_3^{2-}\). When \(\text{HCO}_3^-\) acts as the acid, the proton it donates is a bare \(\text{H}^+\): the hydrogen leaves without its electron, so the fragment retains that electron and the species becomes one unit more negative. Starting charge \(-1\) plus the \(-1\) left behind by the departed \(\text{H}^+\) gives a net charge of \(-2\), and the atom count drops by one hydrogen, so \(\text{HCO}_3^- \rightarrow \text{H}^+ + \text{CO}_3^{2-}\). The conjugate acid–base pair therefore differs by exactly one proton, \(\text{HCO}_3^-/\text{CO}_3^{2-}\). (Choice B) \(\text{H}_2\text{CO}_3\) is the conjugate acid of \(\text{HCO}_3^-\), formed when bicarbonate gains a proton while acting as a base; it is the reverse of the donation described, so it cannot be the conjugate base. (Choice C) \(\text{CO}_3^{-}\) results from removing the hydrogen as a neutral H atom (carrying its electron away) rather than as \(\text{H}^+\), which leaves the charge unchanged at \(-1\); a true proton donation removes only \(\text{H}^+\), so the charge must increase in magnitude to \(-2\). (Choice D) \(\text{OH}^-\) is not generated by deprotonating \(\text{HCO}_3^-\); it would arise from cleaving the ion into other fragments, whereas a conjugate base must be the original species minus one proton, preserving the carbon and the remaining oxygens. Skill 4$ex37$,
    'medium', '5A', $cc37$Acid-Base Equilibria (GC, BC)$cc37$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a37B$names the conjugate acid (proton gained) instead of the conjugate base (proton lost)$a37B$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a37C$removes hydrogen as a neutral atom, leaving charge at -1 instead of -2$a37C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a37D$treats deprotonation as producing hydroxide rather than the deprotonated parent ion$a37D$ FROM q;

-- Q6 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g38)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt38$The amphiprotic dihydrogen phosphate ion, \(\text{H}_2\text{PO}_4^-\), can donate a proton in aqueous solution. What is the conjugate base produced when \(\text{H}_2\text{PO}_4^-\) acts as a Bronsted-Lowry acid?$qt38$,
    $op38$[{"label":"A","text":"\\(\\text{H}_3\\text{PO}_4\\)"},{"label":"B","text":"\\(\\text{PO}_4^{3-}\\)"},{"label":"C","text":"\\(\\text{HPO}_4^{2-}\\)"},{"label":"D","text":"\\(\\text{HPO}_4^{-}\\)"}]$op38$::jsonb,
    'C',
    $ex38$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because a Bronsted-Lowry acid donates exactly one proton to form its conjugate base, so removing a single \(\text{H}^+\) from \(\text{H}_2\text{PO}_4^-\) leaves \(\text{HPO}_4^{2-}\). Removing one proton subtracts one hydrogen atom (from two H to one H) and removes one positive charge from the species, so the charge becomes more negative by one unit: \(-1 \rightarrow -2\). The conjugate acid-base pair \(\text{H}_2\text{PO}_4^- / \text{HPO}_4^{2-}\) therefore differs by exactly one \(\text{H}^+\), which is the defining relationship between an acid and its conjugate base. (Choice A) \(\text{H}_3\text{PO}_4\) is the conjugate acid of \(\text{H}_2\text{PO}_4^-\); it is formed by adding a proton rather than donating one, which reverses the acid-base relationship the question asks for. (Choice B) \(\text{PO}_4^{3-}\) results from removing two protons from \(\text{H}_2\text{PO}_4^-\) (or one proton from \(\text{HPO}_4^{2-}\)); a single proton-donation step cannot strip both remaining hydrogens at once. (Choice D) \(\text{HPO}_4^-\) correctly shows the loss of one hydrogen but fails to adjust the charge, leaving it at \(-1\); donating an \(\text{H}^+\) must make the species one unit more negative, giving \(-2\), not \(-1\). Skill 4$ex38$,
    'medium', '5A', $cc38$Acid-Base Equilibria (GC, BC)$cc38$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a38A$Names the conjugate acid (proton added) instead of the conjugate base (proton removed)$a38A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a38B$Removes two protons in a single deprotonation step, skipping the intermediate species$a38B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a38D$Removes one H atom but does not change the charge, ignoring that losing H+ makes the species one unit more negative$a38D$ FROM q;

-- Q7 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g39)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt39$In a solution where sulfate ion \((\text{SO}_4^{2-})\) acts as a Bronsted-Lowry base by accepting exactly one proton, what is its conjugate acid?$qt39$,
    $op39$[{"label":"A","text":"\\(\\text{SO}_3^{2-}\\)"},{"label":"B","text":"\\(\\text{HSO}_4^-\\)"},{"label":"C","text":"\\(\\text{SO}_4^{3-}\\)"},{"label":"D","text":"\\(\\text{H}_2\\text{SO}_4\\)"}]$op39$::jsonb,
    'B',
    $ex39$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because the conjugate acid of a Bronsted-Lowry base is the species formed when that base gains exactly one proton \((\text{H}^+)\). Adding one \(\text{H}^+\) to \(\text{SO}_4^{2-}\) adds one hydrogen and raises the charge by \(+1\): \(\text{SO}_4^{2-} + \text{H}^+ \rightarrow \text{HSO}_4^-\). The resulting hydrogen sulfate (bisulfate) ion, \(\text{HSO}_4^-\), differs from sulfate by a single \(\text{H}^+\), which is the defining feature of a conjugate acid-base pair. (Choice A) \(\text{SO}_3^{2-}\) (sulfite) is reached by removing an oxygen atom, not by adding a proton; conjugate pairs differ only by \(\text{H}^+\), and the number of oxygen atoms is unchanged. (Choice C) \(\text{SO}_4^{3-}\) keeps the same atoms but lowers the charge by \(+1\) in the wrong direction; gaining a proton must increase the charge from \(2-\) to \(1-\), not decrease it to \(3-\). (Choice D) \(\text{H}_2\text{SO}_4\) results from adding two protons to \(\text{SO}_4^{2-}\); the stem specifies acceptance of exactly one proton, so the species one step removed from sulfate is \(\text{HSO}_4^-\), with \(\text{H}_2\text{SO}_4\) being the conjugate acid of \(\text{HSO}_4^-\) rather than of \(\text{SO}_4^{2-}\). Skill 4$ex39$,
    'medium', '5A', $cc39$Acid-Base Equilibria (GC, BC)$cc39$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a39A$Confuses adding a proton with changing the oxygen count (sulfate to sulfite)$a39A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a39C$Lowers the charge instead of raising it when a proton is gained$a39C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a39D$Adds two protons (skips a step) to reach the fully protonated parent acid$a39D$ FROM q;

-- Q8 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g40)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt40$A chemist must sort the species \(\text{Ag}^+\), \(\text{NH}_3\), and \(\text{HCl}\) by the broadest acid-base definition under which each one can act, given the constraint that Arrhenius behavior counts only in aqueous solution. Which species is classified as a Lewis acid yet qualifies as neither a Brønsted-Lowry acid nor an Arrhenius acid?$qt40$,
    $op40$[{"label":"A","text":"\\(\\text{HCl}\\), because it is the only species that releases \\(\\text{H}^+\\) in water"},{"label":"B","text":"\\(\\text{NH}_3\\), because its lone pair lets it accept a proton from solution"},{"label":"C","text":"All three, because every acid-base species is ultimately a Lewis acid"},{"label":"D","text":"\\(\\text{Ag}^+\\), because it accepts an electron pair without donating or releasing any \\(\\text{H}^+\\)"}]$op40$::jsonb,
    'D',
    $ex40$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because the three acid-base definitions are nested categories: every Arrhenius acid is also a Brønsted-Lowry acid, and every Brønsted-Lowry acid is also a Lewis acid, so the Lewis definition is the broadest and includes species that the narrower definitions exclude. An Arrhenius acid must release \(\text{H}^+\) in aqueous solution, and a Brønsted-Lowry acid must donate a proton (\(\text{H}^+\)) to another species; both definitions therefore require the species to contain and give up a proton. The Lewis definition only requires accepting an electron pair, which does not involve a proton at all. The bare cation \(\text{Ag}^+\) has empty orbitals and accepts a lone pair (for example from \(\text{NH}_3\) to form \([\text{Ag}(\text{NH}_3)_2]^+\)), so it is a Lewis acid; but because it has no proton to release or donate, it is neither an Arrhenius acid nor a Brønsted-Lowry acid. \(\text{Ag}^+\) is the species that sits only in the broadest (outermost) category. (Choice A) \(\text{HCl}\) does release \(\text{H}^+\) in water, so it is an Arrhenius acid and therefore also a Brønsted-Lowry acid and a Lewis acid; it qualifies under all three definitions, not under Lewis alone, so it fails the constraint. (Choice B) \(\text{NH}_3\) accepts a proton, which makes it a Brønsted-Lowry and Lewis base, not an acid of any kind, so it does not fit the requested classification. (Choice C) While it is true that every acid is a Lewis acid, this choice ignores the constraint that the target species must be excluded from the two narrower acid definitions; \(\text{HCl}\) is an Arrhenius and Brønsted-Lowry acid and \(\text{NH}_3\) is not an acid at all, so "all three" is not defensible. Skill 1$ex40$,
    'medium', '5A', $cc40$Acid-Base Equilibria (GC, BC)$cc40$, 'general-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'partial_truth', $a40A$Correctly identifies HCl as an Arrhenius/proton acid but misses that it therefore belongs to all three nested categories, not the Lewis-only category required by the constraint$a40A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a40B$Confuses lone-pair donation with acid behavior, labeling a Lewis/Bronsted base as the target acid$a40B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a40C$Over-applies the true 'all acids are Lewis acids' nesting while ignoring the exclusion constraint and that NH3 is not an acid$a40C$ FROM q;

-- Q9 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g41)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt41$When a bare proton combines with water to form hydronium, \(\text{H}^+ + \text{H}_2\text{O} \rightarrow \text{H}_3\text{O}^+\), the new \(\text{O}\!-\!\text{H}\) linkage is a coordinate covalent bond in which both shared electrons originate from the oxygen. Classifying this single act of bond formation under the Lewis model, which species is the Lewis acid and why?$qt41$,
    $op41$[{"label":"A","text":"\\(\\text{H}_2\\text{O}\\), because it donates the proton that initiates the reaction"},{"label":"B","text":"\\(\\text{H}_3\\text{O}^+\\), because the positive charge resides on it after the bond forms"},{"label":"C","text":"\\(\\text{H}^+\\), because it accepts the lone pair that oxygen supplies to form the bond"},{"label":"D","text":"\\(\\text{H}_2\\text{O}\\), because it accepts the proton into its lone pair"}]$op41$::jsonb,
    'C',
    $ex41$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the Lewis model defines an acid as the electron-pair acceptor and a base as the electron-pair donor, and in this coordinate covalent bond the proton is the species that accepts the pair. The bare proton \(\text{H}^+\) has no electrons of its own and an empty \(1s\) orbital; oxygen in \(\text{H}_2\text{O}\) carries lone pairs and donates one of them into that empty orbital, so \(\text{H}^+\) is the electron-pair acceptor (\(\text{Lewis acid}\)) and \(\text{H}_2\text{O}\) is the electron-pair donor (\(\text{Lewis base}\)). The newly formed bond is described as coordinate covalent precisely because both shared electrons came from a single atom, the oxygen of water. (Choice A) misreads the Lewis criterion by using proton transfer rather than electron-pair direction; in the Lewis framework the relevant arrow is the electron pair, which moves from oxygen toward the proton, and water is the donor, not the species that makes \(\text{H}^+\) an acid. (Choice B) attributes the acid label to formal charge on the product, but \(\text{H}_3\text{O}^+\) is the adduct formed by the acid-base combination, and Lewis classification is assigned to the reactant that accepts the pair, not to whichever product bears a positive charge. (Choice D) correctly notes that water uses its lone pair but then mislabels water as the acceptor; water donates the lone pair, which makes it the Lewis base, while the proton is the acceptor and therefore the Lewis acid. Skill 4$ex41$,
    'medium', '5A', $cc41$Acid-Base Equilibria (GC, BC)$cc41$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a41A$applies Bronsted proton-donor logic to a Lewis classification, calling the proton source the acid$a41A$ FROM q
UNION ALL SELECT id, 'B', 'adjacent_fact', $a41B$uses formal positive charge on the product adduct to assign the Lewis acid label$a41B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a41D$identifies the lone-pair donor as the acceptor, swapping Lewis acid and Lewis base roles$a41D$ FROM q;

-- Q10 [Definitions & Conjugate Acid-Base Pairs · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g42)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt42$Dissolved in water, the bare \(\text{Fe}^{3+}\) cation binds six water molecules to form \([\text{Fe}(\text{H}_2\text{O})_6]^{3+}\), yet the \(\text{Fe}^{3+}\) center holds no ionizable protons of its own. Which classification correctly captures the role the \(\text{Fe}^{3+}\) center plays as those six water molecules coordinate to it?$qt42$,
    $op42$[{"label":"A","text":"A Lewis acid, because the \\(\\text{Fe}^{3+}\\) center accepts a lone pair from each coordinating water oxygen to form coordinate covalent bonds."},{"label":"B","text":"A Lewis base, because the \\(\\text{Fe}^{3+}\\) center donates a pair of electrons to each coordinating water molecule."},{"label":"C","text":"A Brønsted-Lowry acid, because the bare \\(\\text{Fe}^{3+}\\) cation transfers a proton to each coordinating water molecule."},{"label":"D","text":"A Lewis acid, because the \\(\\text{Fe}^{3+}\\) center releases a proton to the surrounding water once the six bonds have formed."}]$op42$::jsonb,
    'A',
    $ex42$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because a Lewis acid is defined as an electron-pair acceptor, and the \(\text{Fe}^{3+}\) center has empty valence orbitals and a high positive charge that let it accept a lone pair from the oxygen of each coordinating water, forming six coordinate covalent (dative) bonds. In this coordination step the water oxygens are the electron-pair donors (Lewis bases) and \(\text{Fe}^{3+}\) is the electron-pair acceptor (Lewis acid); no proton is involved at this stage, which is why the metal center can be a Lewis acid even though the bare cation carries no protons of its own. Only after the complex \([\text{Fe}(\text{H}_2\text{O})_6]^{3+}\) is assembled do the now-polarized bound water molecules go on to donate protons, which is a separate Brønsted-Lowry step attributable to the bound water, not to the bare metal center. (Choice B) This reverses the donor and acceptor roles: \(\text{Fe}^{3+}\) accepts the electron pairs rather than donating them, so it is the Lewis acid, while the water oxygens are the Lewis bases that donate. (Choice C) The bare \(\text{Fe}^{3+}\) cation has no protons to transfer, so it cannot itself be a Brønsted-Lowry acid in the coordination step; the proton donation that follows comes from the bound water molecules, not from the metal center. (Choice D) The Lewis-acid label is assigned to the wrong step: \(\text{Fe}^{3+}\) earns it by accepting electron pairs as the bonds form, not by releasing a proton, and the bare metal center has no proton to release in any case. Skill 4$ex42$,
    'medium', '5A', $cc42$Acid-Base Equilibria (GC, BC)$cc42$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a42B$Inverts the electron-pair donor/acceptor roles, calling the metal center a Lewis base that donates electrons rather than the Lewis acid that accepts them$a42B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a42C$Forces the metal into the Brønsted-Lowry framework, treating the protonless bare cation as a proton donor$a42C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a42D$Keeps the correct Lewis-acid label but attaches it to the later proton-release step instead of the electron-pair-acceptance step$a42D$ FROM q;

-- Q11 [Definitions & Conjugate Acid-Base Pairs · hard · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g43)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt43$In aqueous solution, \(\text{Fe}^{3+}\) reacts with six cyanide ions to form the hexacyanoferrate(III) complex \([\text{Fe(CN)}_6]^{3-}\), in which each carbon end of \(\text{CN}^-\) is bonded to the central iron and both bonding electrons of every \(\text{Fe–C}\) linkage originate from the cyanide. On the Lewis definition, which species acts as the Lewis base in this reaction, and why?$qt43$,
    $op43$[{"label":"A","text":"\\(\\text{Fe}^{3+}\\), because as the positively charged center it pulls electron density toward itself and donates that density into the coordinate covalent bonds."},{"label":"B","text":"\\(\\text{CN}^-\\), because it donates a lone pair of electrons to the \\(\\text{Fe}^{3+}\\) center, forming a coordinate covalent bond."},{"label":"C","text":"\\(\\text{Fe}^{3+}\\), because it accepts the lone pair of electrons supplied by each cyanide ion."},{"label":"D","text":"\\(\\text{CN}^-\\), because it donates a proton (\\(\\text{H}^+\\)) to the iron center, which makes it the Brønsted–Lowry base in the complex."}]$op43$::jsonb,
    'B',
    $ex43$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because a Lewis base is defined as an electron-pair donor, and the stem states that both bonding electrons of every \(\text{Fe–C}\) linkage originate from the cyanide ion. Each \(\text{CN}^-\) carries a lone pair on its carbon atom and supplies that pair to the empty orbitals of the \(\text{Fe}^{3+}\) center, forming a coordinate (dative) covalent bond in which one partner provides both shared electrons. The species furnishing the electron pair is the Lewis base, so \(\text{CN}^-\) is the Lewis base; the electron-pair-accepting \(\text{Fe}^{3+}\) is correspondingly the Lewis acid. (Choice A) This misstates the direction of electron flow: \(\text{Fe}^{3+}\) does not donate electron density into the bonds — its valence orbitals are empty, and it instead accepts the lone pairs from cyanide, making it the Lewis acid rather than the base. (Choice C) The reason given describes \(\text{Fe}^{3+}\) accurately as the electron-pair acceptor, but accepting a lone pair is the definition of a Lewis acid, not a Lewis base, so identifying \(\text{Fe}^{3+}\) as the base reverses the acid–base roles. (Choice D) Although \(\text{CN}^-\) is correctly named, the justification invokes the Brønsted–Lowry framework: no proton is transferred in forming \([\text{Fe(CN)}_6]^{3-}\), so the species is acting as a Lewis base by donating an electron pair, not by donating an \(\text{H}^+\). Skill 4$ex43$,
    'hard', '5A', $cc43$Acid-Base Equilibria (GC, BC)$cc43$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a43A$Identifies the metal cation as the base and reverses the direction of electron-pair flow, claiming Fe3+ donates electron density$a43A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a43C$Correctly describes Fe3+ as the electron-pair acceptor but mislabels an electron-pair acceptor as a Lewis base instead of a Lewis acid$a43C$ FROM q
UNION ALL SELECT id, 'D', 'adjacent_fact', $a43D$Names the correct species but justifies it with the Brønsted–Lowry proton-donor definition rather than the Lewis electron-pair-donor definition$a43D$ FROM q;

-- Q12 [Definitions & Conjugate Acid-Base Pairs · easy · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g44)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt44$In the reaction \(\text{NH}_3 + \text{H}_2\text{O} \rightleftharpoons \text{NH}_4^+ + \text{OH}^-\), water reacts with ammonia, whereas in \(\text{HCl} + \text{H}_2\text{O} \rightarrow \text{H}_3\text{O}^+ + \text{Cl}^-\) water reacts with hydrogen chloride. Identify the Bronsted role water plays in each reaction and the conjugate species it becomes.$qt44$,
    $op44$[{"label":"A","text":"With \\(\\text{NH}_3\\) water acts as a base and becomes \\(\\text{H}_3\\text{O}^+\\); with \\(\\text{HCl}\\) water acts as an acid and becomes \\(\\text{OH}^-\\)."},{"label":"B","text":"In both reactions water acts as a Bronsted acid, donating \\(\\text{H}^+\\) to become \\(\\text{OH}^-\\)."},{"label":"C","text":"With \\(\\text{NH}_3\\) water acts as an acid and becomes \\(\\text{H}_3\\text{O}^+\\); with \\(\\text{HCl}\\) water acts as a base and becomes \\(\\text{OH}^-\\)."},{"label":"D","text":"With \\(\\text{NH}_3\\) water acts as an acid, donating \\(\\text{H}^+\\) to become \\(\\text{OH}^-\\); with \\(\\text{HCl}\\) water acts as a base, accepting \\(\\text{H}^+\\) to become \\(\\text{H}_3\\text{O}^+\\)."}]$op44$::jsonb,
    'D',
    $ex44$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because water is amphoteric (amphiprotic): it can donate a proton to act as a Bronsted acid or accept a proton to act as a Bronsted base, depending on the other reactant. In \(\text{NH}_3 + \text{H}_2\text{O} \rightleftharpoons \text{NH}_4^+ + \text{OH}^-\), ammonia takes a proton, so water is the proton donor (the Bronsted acid); losing one \(\text{H}^+\) leaves \(\text{OH}^-\), which is therefore water's conjugate base. In \(\text{HCl} + \text{H}_2\text{O} \rightarrow \text{H}_3\text{O}^+ + \text{Cl}^-\), \(\text{HCl}\) donates a proton, so water is the proton acceptor (the Bronsted base); gaining one \(\text{H}^+\) gives \(\text{H}_3\text{O}^+\), which is water's conjugate acid. A conjugate base always has one fewer proton than its acid, and a conjugate acid always has one more proton than its base, so an acidic water becomes \(\text{OH}^-\) and a basic water becomes \(\text{H}_3\text{O}^+\). (Choice A) The roles are correctly split between the two reactions but the conjugate species are swapped: an acid donates \(\text{H}^+\) and must become \(\text{OH}^-\) (not \(\text{H}_3\text{O}^+\)), and a base accepts \(\text{H}^+\) and must become \(\text{H}_3\text{O}^+\) (not \(\text{OH}^-\)). (Choice B) Water does not act as an acid in both reactions; with \(\text{HCl}\) the proton flows from \(\text{HCl}\) to water, so water accepts a proton and acts as a base, producing \(\text{H}_3\text{O}^+\) rather than \(\text{OH}^-\). (Choice C) The acid/base labels are correct (acid with \(\text{NH}_3\), base with \(\text{HCl}\)) but the conjugate species are interchanged: donating a proton to \(\text{NH}_3\) yields \(\text{OH}^-\), and accepting a proton from \(\text{HCl}\) yields \(\text{H}_3\text{O}^+\). Skill 4$ex44$,
    'easy', '5A', $cc44$Acid-Base Equilibria (GC, BC)$cc44$, 'general-chemistry', 4, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a44A$Reverses the conjugate product of each role, pairing acid-water with H3O+ and base-water with OH-, inverting which species results from losing versus gaining a proton$a44A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a44B$Treats water as fixed in one Bronsted role (always an acid), failing to recognize amphoteric behavior that depends on the partner reactant$a44B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a44C$Assigns the correct acid/base role in each reaction but confuses the proton-transfer step, mismatching the conjugate species (OH- vs H3O+) to the roles$a44C$ FROM q;

-- Q13 [Definitions & Conjugate Acid-Base Pairs · hard · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g45)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt45$The bisulfite ion \(\text{HSO}_3^-\) is amphiprotic, so it can function as a Bronsted-Lowry acid in one proton transfer and as a Bronsted-Lowry base in another. Which option correctly pairs a reaction in which \(\text{HSO}_3^-\) acts as an acid (donating a proton) with a reaction in which the same ion acts as a base (accepting a proton), with the products in each case being the species produced by that single proton transfer?$qt45$,
    $op45$[{"label":"A","text":"Acid: \\(\\text{HSO}_3^- + \\text{OH}^- \\rightleftharpoons \\text{H}_2\\text{SO}_3 + \\text{OH}^-\\); Base: \\(\\text{HSO}_3^- + \\text{H}_3\\text{O}^+ \\rightleftharpoons \\text{H}_2\\text{SO}_3 + \\text{H}_2\\text{O}\\)"},{"label":"B","text":"Acid: \\(\\text{HSO}_3^- + \\text{H}_3\\text{O}^+ \\rightleftharpoons \\text{H}_2\\text{SO}_3 + \\text{H}_2\\text{O}\\); Base: \\(\\text{HSO}_3^- + \\text{OH}^- \\rightleftharpoons \\text{SO}_3^{2-} + \\text{H}_2\\text{O}\\)"},{"label":"C","text":"Acid: \\(\\text{HSO}_3^- + \\text{OH}^- \\rightleftharpoons \\text{SO}_3^{2-} + \\text{H}_2\\text{O}\\); Base: \\(\\text{HSO}_3^- + \\text{H}_2\\text{O} \\rightleftharpoons \\text{O}^{2-} + \\text{H}_2\\text{SO}_3\\)"},{"label":"D","text":"Acid: \\(\\text{HSO}_3^- + \\text{OH}^- \\rightleftharpoons \\text{SO}_3^{2-} + \\text{H}_2\\text{O}\\); Base: \\(\\text{HSO}_3^- + \\text{H}_3\\text{O}^+ \\rightleftharpoons \\text{H}_2\\text{SO}_3 + \\text{H}_2\\text{O}\\)"}]$op45$::jsonb,
    'D',
    $ex45$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because an amphiprotic species can either donate or accept a single proton, and each role must conserve both mass and charge. When \(\text{HSO}_3^-\) acts as a Bronsted-Lowry acid, it donates one proton to a base such as \(\text{OH}^-\); losing \(\text{H}^+\) from \(\text{HSO}_3^-\) leaves \(\text{SO}_3^{2-}\) (sulfite), and the abstracted proton joins \(\text{OH}^-\) to form \(\text{H}_2\text{O}\), giving \(\text{HSO}_3^- + \text{OH}^- \rightleftharpoons \text{SO}_3^{2-} + \text{H}_2\text{O}\) (charge: \(-1 + -1 = -2 + 0\), balanced). When the same ion acts as a Bronsted-Lowry base, it accepts one proton from an acid such as \(\text{H}_3\text{O}^+\); gaining \(\text{H}^+\) converts \(\text{HSO}_3^-\) into \(\text{H}_2\text{SO}_3\) (sulfurous acid), and \(\text{H}_3\text{O}^+\) that donated the proton becomes \(\text{H}_2\text{O}\), giving \(\text{HSO}_3^- + \text{H}_3\text{O}^+ \rightleftharpoons \text{H}_2\text{SO}_3 + \text{H}_2\text{O}\) (charge: \(-1 + +1 = 0 + 0\), balanced). Only option D assigns the correct product to each role. (Choice A) contains an acid reaction that is mass- and charge-inconsistent: writing \(\text{HSO}_3^- + \text{OH}^- \rightleftharpoons \text{H}_2\text{SO}_3 + \text{OH}^-\) adds a proton to \(\text{HSO}_3^-\) while leaving \(\text{OH}^-\) unchanged, which conserves neither hydrogen count nor charge and confuses the proton-donation step with proton gain. (Choice B) reverses the two roles: the reaction with \(\text{H}_3\text{O}^+\) (in which \(\text{HSO}_3^-\) gains a proton to become \(\text{H}_2\text{SO}_3\)) is proton acceptance, which is the base role, not the acid role; likewise the reaction with \(\text{OH}^-\) producing \(\text{SO}_3^{2-}\) is proton donation, the acid role, so the acid and base labels are swapped. (Choice C) keeps the correct acid reaction but invents an impossible product for the base step: an oxide ion \(\text{O}^{2-}\) does not arise from \(\text{HSO}_3^-\) accepting a proton, and the written equation conserves neither hydrogen count nor charge (the left side carries a net charge of \(-1\) while the right side carries \(-2\)), so it cannot represent any Bronsted-Lowry proton transfer. Skill 4$ex45$,
    'hard', '5A', $cc45$Acid-Base Equilibria (GC, BC)$cc45$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a45A$Acid step that adds rather than removes a proton, violating mass/charge balance$a45A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a45B$Acid and base roles swapped between the two reactions$a45B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a45C$Invents an impossible oxide ion O^2- as a proton-transfer product$a45C$ FROM q;

-- Q14 [Definitions & Conjugate Acid-Base Pairs · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g46)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Definitions & Conjugate Acid-Base Pairs',
    $qt46$Lactic acid (\(\text{HC}_3\text{H}_5\text{O}_3\)) is a weak monoprotic acid with \(K_a = 1.4 \times 10^{-3}\) at 25 °C. For its conjugate base, the lactate ion (\(\text{C}_3\text{H}_5\text{O}_3^-\)), what is \(K_b\)?$qt46$,
    $op46$[{"label":"A","text":"\\(7.1 \\times 10^{-12}\\)"},{"label":"B","text":"\\(7.1 \\times 10^{-17}\\)"},{"label":"C","text":"\\(1.4 \\times 10^{-17}\\)"},{"label":"D","text":"\\(7.1 \\times 10^{11}\\)"}]$op46$::jsonb,
    'A',
    $ex46$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because for any conjugate acid-base pair at 25 °C the ion-product of water links the two ionization constants by \(K_a \times K_b = K_w = 1.0 \times 10^{-14}\), so \(K_b\) of the conjugate base is found by dividing: \(K_b = K_w / K_a = (1.0 \times 10^{-14}) / (1.4 \times 10^{-3})\). Dividing the mantissas gives \(1.0 / 1.4 = 0.71\), and subtracting the exponents gives \(10^{-14 - (-3)} = 10^{-11}\), so \(K_b = 0.71 \times 10^{-11} = 7.1 \times 10^{-12}\). This small \(K_b\) reflects the inverse-strength relationship within a conjugate pair: lactic acid is a comparatively strong weak acid (\(K_a\) on the order of \(10^{-3}\)), so its conjugate base lactate is correspondingly very weak (\(K_b\) on the order of \(10^{-12}\)). (Choice B) \(7.1 \times 10^{-17}\) keeps the correct mantissa \(0.71\) but adds the exponents \((-14) + (-3) = -17\) instead of subtracting them; dividing powers of ten requires subtracting the divisor's exponent, which yields \(-11\), not \(-17\). (Choice C) \(1.4 \times 10^{-17}\) comes from multiplying \(K_a \times K_w\) rather than dividing, treating the relationship as \(K_b = K_a \cdot K_w\); the defining relation is \(K_a \cdot K_b = K_w\), so \(K_b\) must be obtained by division. (Choice D) \(7.1 \times 10^{11}\) uses the correct mantissa but inverts the sign of \(K_w\)'s exponent, computing \(10^{+14 - 3}\); because \(K_w = 1.0 \times 10^{-14}\) the exponent is negative, giving \(10^{-11}\) and a tiny (not enormous) \(K_b\). Skill 2$ex46$,
    'hard', '5A', $cc46$Acid-Base Equilibria (GC, BC)$cc46$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'process_step_confusion', $a46B$Added the powers of ten instead of subtracting them when dividing Kw by Ka$a46B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a46C$Multiplied Ka by Kw instead of dividing, misapplying Ka x Kb = Kw$a46C$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a46D$Flipped the sign of the Kw exponent, treating Kw as 10^+14 and producing a huge Kb$a46D$ FROM q;

-- Q15 [Salt Hydrolysis & pH of Salt Solutions · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g47)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt47$Solid \(\text{NaCl}\), the salt produced by neutralizing \(\text{HCl}\) with \(\text{NaOH}\), is dissolved in pure water at \(25^\circ\text{C}\) to give a \(0.10\ \text{M}\) solution. The resulting solution is neutral because$qt47$,
    $op47$[{"label":"A","text":"neither \\(\\text{Na}^+\\) nor \\(\\text{Cl}^-\\) hydrolyzes appreciably, since they come from a strong base and a strong acid, so neither shifts \\([\\text{H}_3\\text{O}^+]\\)."},{"label":"B","text":"\\(\\text{Cl}^-\\) hydrolyzes to form \\(\\text{HCl}\\) while \\(\\text{Na}^+\\) hydrolyzes to form \\(\\text{NaOH}\\), and these two effects cancel to leave the \\(\\text{pH}\\) at \\(7\\)."},{"label":"C","text":"\\(\\text{Cl}^-\\) is the conjugate base of the strong acid \\(\\text{HCl}\\), so it accepts a proton from water and is balanced by an equal release of \\(\\text{OH}^-\\)."},{"label":"D","text":"\\(\\text{Na}^+\\) is a strong Lewis acid that consumes \\(\\text{OH}^-\\), an effect that is exactly offset by \\(\\text{Cl}^-\\) consuming \\(\\text{H}_3\\text{O}^+\\)."}]$op47$::jsonb,
    'A',
    $ex47$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because \(\text{NaCl}\) is the salt of a strong base (\(\text{NaOH}\)) and a strong acid (\(\text{HCl}\)), so both of its ions are spectator ions that do not react measurably with water. \(\text{Na}^+\) is the cation of a strong base, so it has no tendency to accept or donate protons; \(\text{Cl}^-\) is the conjugate base of the strong acid \(\text{HCl}\), and conjugates of strong acids are such weak bases that their reaction with water is negligible. With neither ion altering \([\text{H}_3\text{O}^+]\) or \([\text{OH}^-]\), the autoionization of water alone sets \([\text{H}_3\text{O}^+] = [\text{OH}^-]\) and \(\text{pH} = 7\) at \(25^\circ\text{C}\). (Choice B) This reverses the actual behavior: neither \(\text{Cl}^-\) nor \(\text{Na}^+\) hydrolyzes to regenerate the parent acid and base, so there are no opposing reactions to cancel; the solution is neutral because no hydrolysis occurs, not because two hydrolysis reactions offset. (Choice C) \(\text{Cl}^-\) is indeed the conjugate base of \(\text{HCl}\), but because \(\text{HCl}\) is a strong acid its conjugate base is exceedingly weak and does not accept a proton from water appreciably; it does not generate \(\text{OH}^-\). (Choice D) \(\text{Na}^+\) is not an acid that consumes \(\text{OH}^-\); the cation of a strong base is a spectator, so there is no acid-base effect to be offset, and the premise of two canceling reactions is incorrect. Skill 1$ex47$,
    'easy', '5A', $cc47$Acid-Base Equilibria (GC, BC)$cc47$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a47B$Believes both ions of a strong-acid/strong-base salt hydrolyze and that two opposing hydrolysis reactions cancel, rather than recognizing that no hydrolysis occurs$a47B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a47C$Correctly identifies Cl- as the conjugate base of HCl but wrongly concludes it accepts a proton and releases OH-, ignoring that a strong acid's conjugate is a negligibly weak base$a47C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a47D$Recasts spectator Na+ as a Lewis acid that consumes OH- and pairs it with a fictitious offsetting reaction, inverting the true spectator role of both ions$a47D$ FROM q;

-- Q16 [Salt Hydrolysis & pH of Salt Solutions · easy · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g48)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt48$Solid ammonium chloride, \(\text{NH}_4\text{Cl}\) — the salt of the strong acid HCl and the weak base \(\text{NH}_3\) — is dissolved in pure water to give a \(0.10\,\text{M}\) solution. Predict whether the resulting solution is acidic, basic, or neutral, and identify the species responsible.$qt48$,
    $op48$[{"label":"A","text":"Basic, because \\(\\text{NH}_4^+\\) accepts a proton from water to release \\(\\text{OH}^-\\)."},{"label":"B","text":"Acidic, because \\(\\text{NH}_4^+\\) is a weak acid that donates a proton to water while \\(\\text{Cl}^-\\) is a spectator."},{"label":"C","text":"Neutral, because both \\(\\text{NH}_4^+\\) and \\(\\text{Cl}^-\\) are spectator ions that do not react with water."},{"label":"D","text":"Acidic, because \\(\\text{Cl}^-\\) hydrolyzes to donate a proton to water while \\(\\text{NH}_4^+\\) is a spectator."}]$op48$::jsonb,
    'B',
    $ex48$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because the cation of a salt comes from the base and the anion comes from the acid, and only an ion derived from a weak parent will hydrolyze. \(\text{NH}_4\text{Cl}\) dissolves completely into \(\text{NH}_4^+\) and \(\text{Cl}^-\). The cation \(\text{NH}_4^+\) is the conjugate acid of the weak base \(\text{NH}_3\), so it has a measurable \(K_a > 0\) and acts as a weak acid, donating a proton to water: \(\text{NH}_4^+ + \text{H}_2\text{O} \rightleftharpoons \text{NH}_3 + \text{H}_3\text{O}^+\). The anion \(\text{Cl}^-\) is the conjugate base of the strong acid HCl; because HCl is essentially fully ionized, \(\text{Cl}^-\) is an exceedingly weak base that does not hydrolyze and is an inert spectator. With only \(\text{NH}_4^+\) reacting, the solution accumulates \(\text{H}_3\text{O}^+\), so \([\text{H}_3\text{O}^+] > [\text{OH}^-]\) and the \(\text{pH}\) falls below 7: a salt of a strong acid and a weak base is acidic. (Choice A) This reverses the role of \(\text{NH}_4^+\): an acidic cation donates a proton, it does not accept one, so it cannot generate \(\text{OH}^-\); accepting a proton to make base describes the parent \(\text{NH}_3\), not the ammonium ion. (Choice C) Treating both ions as inert spectators is the rule for a salt of a strong acid and a strong base (such as \(\text{NaCl}\)); here the cation derives from a weak base, so \(\text{NH}_4^+\) is not a spectator and the solution is not neutral. (Choice D) The acidic prediction is correct, but the responsible species is misassigned: \(\text{Cl}^-\) is the conjugate base of a strong acid and does not hydrolyze, whereas \(\text{NH}_4^+\) is the proton donor that lowers the \(\text{pH}\). Skill 4$ex48$,
    'easy', '5A', $cc48$Acid-Base Equilibria (GC, BC)$cc48$, 'general-chemistry', 4, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a48A$Treats the acidic cation NH4+ as a proton acceptor that releases OH-, reversing its acid role and predicting basic$a48A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a48C$Applies the strong-acid + strong-base (both-spectator) rule, wrongly treating NH4+ as inert and predicting neutral$a48C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a48D$Reaches the correct acidic verdict but assigns the hydrolysis to the spectator Cl- instead of NH4+$a48D$ FROM q;

-- Q17 [Salt Hydrolysis & pH of Salt Solutions · easy · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g49)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt49$Solid sodium acetate \(\text{NaC}_2\text{H}_3\text{O}_2\), the salt of acetic acid (a weak acid) and \(\text{NaOH}\) (a strong base), is dissolved in pure water at \(25\,^{\circ}\text{C}\) to make a \(0.10\ \text{M}\) solution. Which prediction about the resulting solution is best supported by the ions it produces?$qt49$,
    $op49$[{"label":"A","text":"The solution is acidic (\\(\\text{pH} < 7\\)) because \\(\\text{Na}^+\\) hydrolyzes water to release \\(\\text{H}_3\\text{O}^+\\)."},{"label":"B","text":"The solution is neutral (\\(\\text{pH} = 7\\)) because both \\(\\text{Na}^+\\) and \\(\\text{C}_2\\text{H}_3\\text{O}_2^-\\) are spectator ions that do not react with water."},{"label":"C","text":"The solution is basic (\\(\\text{pH} > 7\\)) because \\(\\text{C}_2\\text{H}_3\\text{O}_2^-\\) is a weak base (\\(K_b > 0\\)) while \\(\\text{Na}^+\\) is an inert spectator."},{"label":"D","text":"The solution is basic (\\(\\text{pH} > 7\\)) because \\(\\text{Na}^+\\) is the conjugate base of the strong base \\(\\text{NaOH}\\) and reacts with water to release \\(\\text{OH}^-\\)."}]$op49$::jsonb,
    'C',
    $ex49$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the pH of a salt solution is set by which dissolved ion, if any, exchanges a proton with water, and for sodium acetate only the acetate anion does so. When \(\text{NaC}_2\text{H}_3\text{O}_2\) dissolves it dissociates completely into \(\text{Na}^+\) and \(\text{C}_2\text{H}_3\text{O}_2^-\). Acetate is the conjugate base of the weak acid acetic acid; because acetic acid holds its proton appreciably, its conjugate base is strong enough to accept a proton from water, \(\text{C}_2\text{H}_3\text{O}_2^- + \text{H}_2\text{O} \rightleftharpoons \text{HC}_2\text{H}_3\text{O}_2 + \text{OH}^-\), a hydrolysis with \(K_b = K_w/K_a > 0\). This reaction generates excess \(\text{OH}^-\), so \([\text{OH}^-] > [\text{H}_3\text{O}^+]\) and \(\text{pH} > 7\). The cation \(\text{Na}^+\) comes from the strong base \(\text{NaOH}\); cations of strong bases are inert spectators that do not hydrolyze, so they leave the pH unchanged. The general rule for a salt of a weak acid and a strong base is therefore a basic solution. (Choice A) \(\text{Na}^+\) is the cation of a strong base and does not react with water; it cannot generate \(\text{H}_3\text{O}^+\), so the solution is not acidic on this basis. (Choice B) Only salts of a strong acid and a strong base give neutral solutions; here acetate is not a spectator but a weak base that hydrolyzes, so the solution is not neutral. (Choice D) The conclusion that the solution is basic is correct, but the reasoning is reversed: \(\text{Na}^+\) is the spectator cation of \(\text{NaOH}\) and does not react with water, whereas it is the acetate anion that produces \(\text{OH}^-\). Skill 4$ex49$,
    'easy', '5A', $cc49$Acid-Base Equilibria (GC, BC)$cc49$, 'general-chemistry', 4, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a49A$spectator cation wrongly hydrolyzed to give acidic solution$a49A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a49B$both ions treated as spectators yielding neutral pH$a49B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a49D$correct basic prediction attributed to wrong ion (Na+ instead of acetate)$a49D$ FROM q;

-- Q18 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g50)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt50$Solid \(\text{KCN}\), the salt of the weak acid \(\text{HCN}\) (\(K_a = 4.9\times10^{-10}\)) and the strong base \(\text{KOH}\), is dissolved in pure water to make a \(0.10\ \text{M}\) solution. Which prediction about the resulting \(\text{pH}\), and the ion responsible for it, is correct?$qt50$,
    $op50$[{"label":"A","text":"Acidic, because \\(\\text{K}^+\\) is a small, highly charged cation that hydrolyzes water to release \\(\\text{H}_3\\text{O}^+\\)."},{"label":"B","text":"Neutral (\\(\\text{pH} = 7\\)), because \\(\\text{KCN}\\) is the product of an acid reacting completely with a base, so its ions cannot shift the water equilibrium."},{"label":"C","text":"Basic, because the spectator ion \\(\\text{CN}^-\\) holds \\(\\text{K}^+\\) in solution while \\(\\text{K}^+\\) abstracts a proton from water to generate \\(\\text{OH}^-\\)."},{"label":"D","text":"Basic, because \\(\\text{CN}^-\\) is the conjugate base of a weak acid and hydrolyzes (\\(\\text{CN}^- + \\text{H}_2\\text{O} \\rightleftharpoons \\text{HCN} + \\text{OH}^-\\)), while \\(\\text{K}^+\\) is a spectator."}]$op50$::jsonb,
    'D',
    $ex50$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because the only ion in \(\text{KCN}\) that disturbs the water equilibrium is \(\text{CN}^-\), the conjugate base of the weak acid \(\text{HCN}\), so it hydrolyzes to give a basic solution. To classify a salt, split it into its parent ions and ask whether each came from a strong or weak partner. \(\text{K}^+\) is the conjugate acid of the strong base \(\text{KOH}\); a cation derived from a strong base is a spectator and does not affect \(\text{pH}\). \(\text{CN}^-\) is the conjugate base of the weak acid \(\text{HCN}\), and because \(\text{HCN}\) is weak, \(\text{CN}^-\) is appreciably basic. It reacts with water as \(\text{CN}^- + \text{H}_2\text{O} \rightleftharpoons \text{HCN} + \text{OH}^-\), with \(K_b = K_w/K_a = (1.0\times10^{-14})/(4.9\times10^{-10}) \approx 2.0\times10^{-5}\). Producing \(\text{OH}^-\) drives the solution basic (\(\text{pH} > 7\)). (Choice A) is a misconception: \(\text{K}^+\) is the conjugate of a strong base and is too large with too low a charge density to hydrolyze water; only small, highly charged cations (e.g. \(\text{Al}^{3+}\)) acidify a solution, and \(\text{K}^+\) is not one of them. (Choice B) is the "salt always equals neutral" fallacy; a neutralization can produce a salt whose ions do shift the water equilibrium, and here \(\text{CN}^-\) clearly does, so the solution is not \(\text{pH} = 7\). (Choice C) reverses the roles of the two ions: it correctly predicts a basic solution but credits the proton abstraction to \(\text{K}^+\) and labels \(\text{CN}^-\) the spectator, whereas it is \(\text{CN}^-\) that accepts the proton and \(\text{K}^+\) that is inert. Skill 4$ex50$,
    'medium', '5A', $cc50$Acid-Base Equilibria (GC, BC)$cc50$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a50A$Treats the spectator cation of a strong base as an acidic hydrolyzing ion$a50A$ FROM q
UNION ALL SELECT id, 'B', 'partial_truth', $a50B$Salt-of-acid-and-base must be neutral fallacy$a50B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a50C$Correct basic pH but assigns the hydrolyzing role to the spectator ion$a50C$ FROM q;

-- Q19 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g51)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt51$Solid sodium fluoride (NaF) is dissolved in pure water at 25 °C, given that \(K_a\) for HF is \(6.8\times10^{-4}\). Which ion drives the resulting solution's pH away from 7, and in which direction does the pH move?$qt51$,
    $op51$[{"label":"A","text":"\\(\\text{F}^-\\) hydrolyzes as a weak base while \\(\\text{Na}^+\\) is a spectator, so the pH rises above 7"},{"label":"B","text":"\\(\\text{Na}^+\\) hydrolyzes as a weak acid while \\(\\text{F}^-\\) is a spectator, so the pH falls below 7"},{"label":"C","text":"\\(\\text{F}^-\\) hydrolyzes as a weak acid while \\(\\text{Na}^+\\) is a spectator, so the pH falls below 7"},{"label":"D","text":"Both \\(\\text{Na}^+\\) and \\(\\text{F}^-\\) are spectator ions, so the pH stays at 7"}]$op51$::jsonb,
    'A',
    $ex51$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because \(\text{F}^-\) is the conjugate base of the weak acid HF and therefore hydrolyzes water, while \(\text{Na}^+\) is the conjugate of the strong base NaOH and does nothing. NaF dissociates completely into \(\text{Na}^+\) and \(\text{F}^-\). To decide whether an ion affects pH, trace it back to its parent acid or base. \(\text{Na}^+\) comes from NaOH, a strong base that is fully dissociated and has no tendency to re-form; an ion whose parent is a strong electrolyte does not hydrolyze, so \(\text{Na}^+\) is an inert spectator. \(\text{F}^-\) comes from HF, a weak acid (\(K_a = 6.8\times10^{-4}\)) that only partially ionizes; because HF holds onto protons appreciably, its conjugate base \(\text{F}^-\) is strong enough to pull a proton from water: \(\text{F}^- + \text{H}_2\text{O} \rightleftharpoons \text{HF} + \text{OH}^-\). This reaction generates \(\text{OH}^-\), so \([\text{OH}^-] > [\text{H}_3\text{O}^+]\) and the \(\text{pH}\) rises above 7. Quantitatively, \(K_b\) for \(\text{F}^-\) is \(K_w/K_a = (1.0\times10^{-14})/(6.8\times10^{-4}) \approx 1.5\times10^{-11}\), small but nonzero, confirming a weakly basic solution. The general rule: a salt of a strong base and a weak acid gives a basic solution. This is a Knowledge of Scientific Concepts and Principles question.

(Choice B) This reverses both roles, claiming \(\text{Na}^+\) hydrolyzes as a weak acid and \(\text{F}^-\) is the spectator. In fact \(\text{Na}^+\) is the conjugate of the strong base NaOH and is the spectator; it cannot donate a proton. \(\text{F}^-\) is the species that reacts with water. The predicted acidic pH is also wrong because no proton-donating ion is present.

(Choice C) This correctly identifies \(\text{F}^-\) as the reactive ion and \(\text{Na}^+\) as the spectator, but mislabels \(\text{F}^-\) as a weak acid. \(\text{F}^-\) is the conjugate base of HF and acts as a weak base, accepting a proton to release \(\text{OH}^-\); it has no acidic proton to donate. Because it produces \(\text{OH}^-\), the pH rises above 7 rather than falling below it.

(Choice D) Treating both ions as spectators describes a salt of a strong acid and a strong base (for example, NaCl), which gives a neutral solution. NaF is not that case: although \(\text{Na}^+\) is indeed a spectator, \(\text{F}^-\) is the conjugate base of a weak acid and does hydrolyze, so the solution is not neutral. Skill 1$ex51$,
    'medium', '5A', $cc51$Acid-Base Equilibria (GC, BC)$cc51$, 'general-chemistry', 1, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a51B$Swaps the hydrolyzing and spectator ions, assigning reactivity to the strong-base cation and inertness to the weak-acid anion$a51B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a51C$Correctly picks the reactive ion but treats the conjugate base of a weak acid as itself acidic, inverting the pH direction$a51C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a51D$Applies the strong-acid/strong-base neutral-salt rule, correct for Na+ but wrong for F-, concluding a neutral solution$a51D$ FROM q;

-- Q20 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g52)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt52$Solid ammonium fluoride, \(\text{NH}_4\text{F}\), is dissolved in pure water at \(25\,^\circ\text{C}\) to give a \(0.10\,\text{M}\) solution. Unlike the chloride salt, both ions of this salt react with water: the cation has \(K_a(\text{NH}_4^+) = 5.6\times10^{-10}\) and the anion has \(K_b(\text{F}^-) = 1.5\times10^{-11}\). Predict whether the resulting solution is acidic, basic, or neutral, and identify the reason.$qt52$,
    $op52$[{"label":"A","text":"Basic, because \\(K_b(\\text{F}^-) > K_a(\\text{NH}_4^+)\\), so anion hydrolysis producing \\(\\text{OH}^-\\) outcompetes cation hydrolysis."},{"label":"B","text":"Acidic, because \\(K_a(\\text{NH}_4^+) > K_b(\\text{F}^-)\\), so cation hydrolysis producing \\(\\text{H}_3\\text{O}^+\\) outcompetes anion hydrolysis."},{"label":"C","text":"Neutral, because both ions hydrolyze, so the \\(\\text{H}_3\\text{O}^+\\) and \\(\\text{OH}^-\\) they generate cancel exactly."},{"label":"D","text":"Acidic, because \\(\\text{NH}_4^+\\) is a weak acid while \\(\\text{F}^-\\) is an inert spectator that does not react with water."}]$op52$::jsonb,
    'B',
    $ex52$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because \(\text{NH}_4\text{F}\) is the salt of a weak base (\(\text{NH}_3\)) and a weak acid (\(\text{HF}\)), so both of its ions react with water: the cation as a weak acid, \(\text{NH}_4^+ + \text{H}_2\text{O} \rightleftharpoons \text{NH}_3 + \text{H}_3\text{O}^+\) with \(K_a = 5.6\times10^{-10}\), and the anion as a weak base, \(\text{F}^- + \text{H}_2\text{O} \rightleftharpoons \text{HF} + \text{OH}^-\) with \(K_b = 1.5\times10^{-11}\). Because the two ions are present at equal concentration, the larger equilibrium constant determines the dominant process. Since \(K_a(\text{NH}_4^+) = 5.6\times10^{-10}\) exceeds \(K_b(\text{F}^-) = 1.5\times10^{-11}\) by a factor of roughly \(38\), cation hydrolysis generates more \(\text{H}_3\text{O}^+\) than anion hydrolysis generates \(\text{OH}^-\), leaving a net excess of \(\text{H}_3\text{O}^+\) and a pH below \(7\). (Choice A) reverses the comparison: it asserts that the anion's constant is larger, but \(K_b(\text{F}^-)\) is actually the smaller value, so anion hydrolysis is the weaker process and cannot dominate. (Choice C) incorrectly assumes the two hydrolysis reactions offset exactly; cancellation would require \(K_a = K_b\), but the constants here differ by more than an order of magnitude, so the products do not balance and the solution cannot be neutral. (Choice D) reaches the right classification by faulty reasoning: it treats \(\text{F}^-\) as an inert spectator like \(\text{Cl}^-\), but \(\text{F}^-\) is the conjugate base of the weak acid \(\text{HF}\) and does hydrolyze; the solution is acidic because \(K_a > K_b\), not because the anion is unreactive. Skill 4$ex52$,
    'medium', '5A', $cc52$Acid-Base Equilibria (GC, BC)$cc52$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a52A$swaps which constant is larger and concludes basic instead of acidic$a52A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a52C$assumes dual hydrolysis always cancels to neutral, ignoring unequal Ka and Kb$a52C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a52D$treats F- as an inert spectator like Cl-, overlooking that F- itself hydrolyzes$a52D$ FROM q;

-- Q21 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g53)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt53$Sodium acetate dissolves to release acetate, the conjugate base of acetic acid \((K_a = 1.8 \times 10^{-5})\). Before computing the solution's pH, a student must find \(K_b\) for acetate using \(K_a \times K_b = K_w = 1.0 \times 10^{-14}\) at 25 °C. What is \(K_b\) of the acetate ion?$qt53$,
    $op53$[{"label":"A","text":"\\(1.8 \\times 10^{-19}\\)"},{"label":"B","text":"\\(5.6 \\times 10^{-3}\\)"},{"label":"C","text":"\\(5.6 \\times 10^{-10}\\)"},{"label":"D","text":"\\(1.8 \\times 10^{9}\\)"}]$op53$::jsonb,
    'C',
    $ex53$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the conjugate base \(K_b\) is obtained by dividing \(K_w\) by the parent acid's \(K_a\). For any conjugate acid–base pair, \(K_a \times K_b = K_w\), so \(K_b = \dfrac{K_w}{K_a} = \dfrac{1.0 \times 10^{-14}}{1.8 \times 10^{-5}}\). Dividing the coefficients gives \(1.0 / 1.8 = 0.56\), and subtracting exponents gives \(10^{-14 - (-5)} = 10^{-9}\), so \(K_b = 0.56 \times 10^{-9} = 5.6 \times 10^{-10}\). This small \(K_b\) correctly reflects that acetate is only a weak base. (Choice A) \(1.8 \times 10^{-19}\) comes from multiplying \(K_a\) by \(K_w\) \((1.8 \times 10^{-5})(1.0 \times 10^{-14})\) instead of dividing; the relationship \(K_a \times K_b = K_w\) must be solved for \(K_b\) by division, not by multiplying the two known constants together. (Choice B) \(5.6 \times 10^{-3}\) results from using \(1.0 \times 10^{-7}\) for \(K_w\); \(1.0 \times 10^{-7}\) is the neutral hydronium concentration \([\text{H}_3\text{O}^+]\) at 25 °C, whereas \(K_w = [\text{H}_3\text{O}^+][\text{OH}^-] = 1.0 \times 10^{-14}\). (Choice D) \(1.8 \times 10^{9}\) inverts the division, computing \(K_a / K_w\) rather than \(K_w / K_a\); this would imply acetate is an extremely strong base, contradicting the rule that the conjugate of a weak acid is itself weak. Skill 2$ex53$,
    'medium', '5A', $cc53$Acid-Base Equilibria (GC, BC)$cc53$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a53A$Multiplies Ka by Kw instead of dividing Kw by Ka when solving Ka*Kb = Kw for Kb$a53A$ FROM q
UNION ALL SELECT id, 'B', 'scale_unit_error', $a53B$Uses Kw = 1.0e-7 (the neutral [H3O+]) in place of the true Kw = 1.0e-14$a53B$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a53D$Inverts the quotient, computing Ka/Kw rather than Kw/Ka, yielding an implausibly large Kb$a53D$ FROM q;

-- Q22 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g54)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt54$A \(0.10\ \text{M}\) solution of sodium acetate, \(\text{CH}_3\text{COONa}\), is prepared in water; the acetate ion is the conjugate base of acetic acid, for which \(K_a = 1.8\times10^{-5}\) (with \(K_w = 1.0\times10^{-14}\)). Treating dissociation of the dissolved salt as complete and the resulting \(0.10\ \text{M}\ \text{CH}_3\text{COO}^-\) as the only species that reacts with water, what is the \(\text{pH}\) of the solution?$qt54$,
    $op54$[{"label":"A","text":"\\(\\text{pH} = 7.00\\)"},{"label":"B","text":"\\(\\text{pH} = 2.87\\)"},{"label":"C","text":"\\(\\text{pH} = 5.13\\)"},{"label":"D","text":"\\(\\text{pH} = 8.87\\)"}]$op54$::jsonb,
    'D',
    $ex54$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because the acetate ion is the conjugate base of a weak acid paired with the spectator cation \(\text{Na}^+\), so it hydrolyzes water to make the solution basic, and the \(\text{pH}\) works out to \(8.87\). The governing equilibrium is \(\text{CH}_3\text{COO}^- + \text{H}_2\text{O} \rightleftharpoons \text{CH}_3\text{COOH} + \text{OH}^-\), described by \(K_b = K_w/K_a = (1.0\times10^{-14})/(1.8\times10^{-5}) = 5.6\times10^{-10}\). Because \(K_b\) is tiny, the small-\(x\) approximation gives \([\text{OH}^-] = \sqrt{K_b\,C} = \sqrt{(5.6\times10^{-10})(0.10)} = \sqrt{5.6\times10^{-11}} = 7.5\times10^{-6}\ \text{M}\). Then \(\text{pOH} = -\log(7.5\times10^{-6}) = 5.13\), and \(\text{pH} = 14.00 - \text{pOH} = 14.00 - 5.13 = 8.87\), correctly basic. (Choice A) \(\text{pH} = 7.00\) treats the salt as neutral, as if it came from a strong acid and strong base; sodium acetate derives from a weak acid (acetic) and a strong base, so its conjugate-base anion hydrolyzes and the solution is basic, not neutral. (Choice B) \(\text{pH} = 2.87\) comes from treating acetate as a weak acid and using \([\text{H}^+] = \sqrt{K_a\,C} = \sqrt{(1.8\times10^{-5})(0.10)} = 1.3\times10^{-3}\ \text{M}\); acetate is a base, so \(K_b = K_w/K_a\) must be used and the result must be basic, not acidic. (Choice C) \(\text{pH} = 5.13\) is the \(\text{pOH}\) reported as the \(\text{pH}\); the \([\text{OH}^-]\) was found correctly, but the final step \(\text{pH} = 14.00 - \text{pOH}\) was skipped, leaving an acidic value for what is in fact a basic solution. Skill 2$ex54$,
    'medium', '5A', $cc54$Acid-Base Equilibria (GC, BC)$cc54$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a54A$salt-of-weak-acid-strong-base assumed neutral like NaCl$a54A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a54B$conjugate base treated as a weak acid using Ka instead of Kb$a54B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a54C$pOH reported as pH, skipping pH = 14 - pOH$a54C$ FROM q;

-- Q23 [Salt Hydrolysis & pH of Salt Solutions · medium · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g55)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt55$A \(0.10\ \text{M}\) solution of ammonium chloride, \(\text{NH}_4\text{Cl}\), is prepared at \(25\,^\circ\text{C}\), where \(K_w = 1.0\times10^{-14}\) and the base ionization constant of ammonia is \(K_b = 1.8\times10^{-5}\). Treating the dissolved salt as the only solute, what is the \(\text{pH}\) of this solution?$qt55$,
    $op55$[{"label":"A","text":"\\(\\text{pH} = 5.13\\)"},{"label":"B","text":"\\(\\text{pH} = 11.13\\)"},{"label":"C","text":"\\(\\text{pH} = 10.25\\)"},{"label":"D","text":"\\(\\text{pH} = 2.87\\)"}]$op55$::jsonb,
    'A',
    $ex55$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because \(\text{NH}_4\text{Cl}\) is the salt of a strong acid (\(\text{HCl}\)) and a weak base (\(\text{NH}_3\)): the chloride ion is the conjugate base of a strong acid and does not hydrolyze, while the ammonium ion \(\text{NH}_4^+\) is the conjugate acid of the weak base ammonia and donates a proton to water, making the solution acidic. First convert the supplied \(K_b\) of ammonia into the acid ionization constant of \(\text{NH}_4^+\): \(K_a = \dfrac{K_w}{K_b} = \dfrac{1.0\times10^{-14}}{1.8\times10^{-5}} = 5.6\times10^{-10}\). For the equilibrium \(\text{NH}_4^+ + \text{H}_2\text{O} \rightleftharpoons \text{NH}_3 + \text{H}_3\text{O}^+\), the small \(K_a\) justifies the approximation \([\text{H}_3\text{O}^+] = \sqrt{K_a\,C} = \sqrt{(5.6\times10^{-10})(0.10)} = \sqrt{5.6\times10^{-11}} = 7.5\times10^{-6}\ \text{M}\). Then \(\text{pH} = -\log(7.5\times10^{-6}) = 5.13\), confirming a mildly acidic solution. (Choice B) \(\text{pH} = 11.13\) treats the salt as basic by applying \(K_b = 1.8\times10^{-5}\) directly to the salt to find \([\text{OH}^-] = \sqrt{K_b\,C} = 1.3\times10^{-3}\ \text{M}\) and then converting \(\text{pOH} = 2.87\) to \(\text{pH}\); this reverses the chemistry, since the ammonium ion acts as an acid, not a base, and the solution cannot be basic. (Choice C) \(\text{pH} = 10.25\) omits the square root and sets \([\text{H}_3\text{O}^+] = K_a\,C = 5.6\times10^{-11}\ \text{M}\), so \(-\log(5.6\times10^{-11}) = 10.25\); the equilibrium expression \(K_a = x^2/C\) requires solving for \(x = \sqrt{K_a\,C}\) rather than equating \(x\) with the product \(K_a\,C\). (Choice D) \(\text{pH} = 2.87\) skips the \(K_a = K_w/K_b\) conversion and uses the ammonia \(K_b = 1.8\times10^{-5}\) itself as the acid ionization constant, giving \([\text{H}_3\text{O}^+] = \sqrt{(1.8\times10^{-5})(0.10)} = 1.3\times10^{-3}\ \text{M}\) and \(\text{pH} = 2.87\); using the base constant in place of the much smaller derived \(K_a\) overstates the acidity by several orders of magnitude. Skill 2$ex55$,
    'medium', '5A', $cc55$Acid-Base Equilibria (GC, BC)$cc55$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a55B$treats ammonium salt as basic and converts pOH to pH$a55B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a55C$omits square root, sets [H3O+] equal to Ka times C$a55C$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a55D$uses Kb directly as Ka without the Kw/Kb conversion$a55D$ FROM q;

-- Q24 [Salt Hydrolysis & pH of Salt Solutions · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g56)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt56$A \(0.10\ \text{M}\) solution of sodium cyanide (\(\text{NaCN}\)) is prepared at \(25\,^\circ\text{C}\), where \(K_w = 1.0\times10^{-14}\) and the parent acid \(\text{HCN}\) has \(K_a = 4.9\times10^{-10}\). Assuming \(x\) is small relative to the initial salt concentration, what is the \(\text{pH}\) of this solution?$qt56$,
    $op56$[{"label":"A","text":"\\(\\text{pH} = 2.85\\)"},{"label":"B","text":"\\(\\text{pH} = 11.15\\)"},{"label":"C","text":"\\(\\text{pH} = 5.15\\)"},{"label":"D","text":"\\(\\text{pH} = 7.00\\)"}]$op56$::jsonb,
    'B',
    $ex56$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. \(\text{NaCN}\) dissociates completely into \(\text{Na}^+\) (the cation of a strong base, spectator) and \(\text{CN}^-\) (the conjugate base of the weak acid \(\text{HCN}\)), so \(\text{CN}^-\) hydrolyzes water and the solution is basic. The answer to this question is B because solving the base-hydrolysis equilibrium gives \(\text{pH} = 11.15\). First convert \(K_a\) to the base ionization constant of \(\text{CN}^-\): \(K_b = \dfrac{K_w}{K_a} = \dfrac{1.0\times10^{-14}}{4.9\times10^{-10}} = 2.0\times10^{-5}\). For \(\text{CN}^- + \text{H}_2\text{O} \rightleftharpoons \text{HCN} + \text{OH}^-\), the small-\(x\) approximation gives \([\text{OH}^-] = \sqrt{K_b\,C} = \sqrt{(2.0\times10^{-5})(0.10)} = \sqrt{2.0\times10^{-6}} = 1.4\times10^{-3}\ \text{M}\). Then \(\text{pOH} = -\log(1.4\times10^{-3}) = 2.85\), so \(\text{pH} = 14.00 - 2.85 = 11.15\), consistent with a strongly basic salt of a very weak acid. (Choice A) \(2.85\) is the \(\text{pOH}\), not the \(\text{pH}\); reporting \(-\log[\text{OH}^-]\) as the \(\text{pH}\) skips the final \(\text{pH} = 14 - \text{pOH}\) conversion and wrongly labels a basic solution as strongly acidic. (Choice C) \(5.15\) results from incorrectly using \(K_a\) of \(\text{HCN}\) to compute \([\text{H}^+] = \sqrt{K_a\,C} = \sqrt{(4.9\times10^{-10})(0.10)} = 7.0\times10^{-6}\ \text{M}\); this treats the cyanide ion as a weak acid rather than as a conjugate base, ignoring that the species in solution is \(\text{CN}^-\), not \(\text{HCN}\). (Choice D) \(7.00\) assumes the salt is neutral, which would be true only for the salt of a strong acid and strong base; it overlooks that \(\text{CN}^-\) derives from the weak acid \(\text{HCN}\) and therefore hydrolyzes to raise the \(\text{pH}\). Skill 2$ex56$,
    'hard', '5A', $cc56$Acid-Base Equilibria (GC, BC)$cc56$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a56A$Reports pOH (2.85) as the final pH, omitting the pH = 14 - pOH conversion$a56A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a56C$Treats CN- as a weak acid using Ka directly instead of as a conjugate base via Kb$a56C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a56D$Assumes the salt is neutral (pH 7), ignoring hydrolysis of the conjugate base of a weak acid$a56D$ FROM q;

-- Q25 [Salt Hydrolysis & pH of Salt Solutions · hard · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g57)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt57$Two salts are dissolved separately at the same concentration, \(0.10\ \text{M}\): sodium hypochlorite (\(\text{NaOCl}\), whose parent acid \(\text{HClO}\) has \(K_a = 2.9\times10^{-8}\)) and sodium nitrite (\(\text{NaNO}_2\), whose parent acid \(\text{HNO}_2\) has \(K_a = 4.6\times10^{-4}\)). In each case the cation is the spectator \(\text{Na}^+\) from a strong base and only the anion undergoes hydrolysis. Which solution is the more basic (higher \(\text{pH}\)), and why?$qt57$,
    $op57$[{"label":"A","text":"The \\(\\text{NaNO}_2\\) solution, because its larger parent-acid \\(K_a\\) means more of the \\(\\text{NO}_2^-\\) anion is available to react with water and generate \\(\\text{OH}^-\\)."},{"label":"B","text":"The \\(\\text{NaNO}_2\\) solution, because the stronger parent acid \\(\\text{HNO}_2\\) furnishes the stronger conjugate base \\(\\text{NO}_2^-\\), giving it the larger \\(K_b\\)."},{"label":"C","text":"The \\(\\text{NaOCl}\\) solution, because the weaker parent acid \\(\\text{HClO}\\) furnishes the stronger conjugate base \\(\\text{OCl}^-\\), giving it the larger \\(K_b\\)."},{"label":"D","text":"Neither; both are salts of a weak acid and a strong base, so both anions hydrolyze to the same extent and the two solutions reach equal \\(\\text{pH}\\)."}]$op57$::jsonb,
    'C',
    $ex57$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the basicity of a salt of a weak acid and a strong base is set by the conjugate-base strength of the anion, and conjugate-base strength runs inverse to the strength of the parent acid through the relation \(K_a \times K_b = K_w\). Rearranged, \(K_b = K_w / K_a\), so the anion of the weaker acid has the larger \(K_b\). Here \(\text{HClO}\) (\(K_a = 2.9\times10^{-8}\)) is the weaker of the two parent acids, so \(\text{OCl}^-\) is the stronger conjugate base: \(K_b(\text{OCl}^-) = 1.0\times10^{-14} / 2.9\times10^{-8} = 3.4\times10^{-7}\). For \(\text{NO}_2^-\), \(K_b = 1.0\times10^{-14} / 4.6\times10^{-4} = 2.2\times10^{-11}\). Because \(K_b(\text{OCl}^-) \approx 3.4\times10^{-7}\) is about four orders of magnitude larger than \(K_b(\text{NO}_2^-) \approx 2.2\times10^{-11}\), \(\text{OCl}^-\) hydrolyzes far more extensively at the same \(0.10\ \text{M}\), producing a higher \([\text{OH}^-]\) and therefore a higher \(\text{pH}\). The \(\text{NaOCl}\) solution is the more basic. (Choice A) The amount of anion delivered is fixed by the dissolved salt concentration (\(0.10\ \text{M}\)) and the complete dissociation of the strong-base salt, not by the parent acid's \(K_a\); a larger parent \(K_a\) does not put more \(\text{NO}_2^-\) into solution, and in any case it would mean weaker, not stronger, hydrolysis. (Choice B) This reverses the inverse relationship between an acid and its conjugate base: a stronger parent acid holds its proton less tightly only in the dissociation sense, but its conjugate base is correspondingly weaker (smaller \(K_b\)), so \(\text{HNO}_2\) being the stronger acid makes \(\text{NO}_2^-\) the weaker base, not the stronger one. (Choice D) Both anions do come from weak acids and so both make basic solutions, but the extent of hydrolysis is governed by each anion's \(K_b\), and these differ by roughly \(10^4\); the two solutions cannot reach the same \(\text{pH}\). Skill 4$ex57$,
    'hard', '5A', $cc57$Acid-Base Equilibria (GC, BC)$cc57$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a57A$conflates parent-acid Ka with the quantity of anion delivered, treating larger Ka as more hydrolyzable anion rather than as weaker conjugate-base strength$a57A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a57B$inverts the Ka-Kb inverse relationship, claiming the stronger parent acid yields the stronger conjugate base$a57B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a57D$assumes all weak-acid/strong-base salts hydrolyze to equal extent regardless of the parent acid's Ka$a57D$ FROM q;

-- Q26 [Salt Hydrolysis & pH of Salt Solutions · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g58)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Salt Hydrolysis & pH of Salt Solutions',
    $qt58$Two salts are each dissolved to \(0.10\ \text{M}\) in separate beakers of water: ammonium chloride (\(\text{NH}_4\text{Cl}\), whose parent base \(\text{NH}_3\) has \(K_b = 1.8\times10^{-5}\)) and anilinium chloride (\(\text{C}_6\text{H}_5\text{NH}_3\text{Cl}\), whose parent base aniline has \(K_b = 4.3\times10^{-10}\)). In both salts the chloride is a spectator. Which solution is more acidic, and why?$qt58$,
    $op58$[{"label":"A","text":"The \\(\\text{NH}_4\\text{Cl}\\) solution, because \\(\\text{NH}_3\\) has the larger \\(K_b\\), so its cation \\(\\text{NH}_4^+\\) is the stronger conjugate acid."},{"label":"B","text":"The \\(\\text{C}_6\\text{H}_5\\text{NH}_3\\text{Cl}\\) solution, because the chloride from aniline's salt makes the solution acidic while ammonium's chloride is neutral."},{"label":"C","text":"Neither; both cations come from weak bases, so the two solutions reach the same pH at equal concentration."},{"label":"D","text":"The \\(\\text{C}_6\\text{H}_5\\text{NH}_3\\text{Cl}\\) solution, because aniline's smaller \\(K_b\\) gives anilinium the larger \\(K_a\\) via \\(K_a = K_w/K_b\\)."}]$op58$::jsonb,
    'D',
    $ex58$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because the more acidic salt solution is the one whose cation is the stronger conjugate acid, and conjugate-acid strength is set by \(K_a = K_w/K_b\) of the parent base. For ammonium, \(K_a(\text{NH}_4^+) = K_w/K_b = (1.0\times10^{-14})/(1.8\times10^{-5}) = 5.6\times10^{-10}\). For anilinium, \(K_a(\text{C}_6\text{H}_5\text{NH}_3^+) = (1.0\times10^{-14})/(4.3\times10^{-10}) = 2.3\times10^{-5}\). Because \(K_a\) and \(K_b\) are inversely related, the weaker parent base (aniline, with the smaller \(K_b\)) gives the stronger conjugate-acid cation: anilinium's \(K_a\) is about \(4\times10^{4}\) times larger than ammonium's. At equal \(0.10\ \text{M}\) concentration the cation with the larger \(K_a\) hydrolyzes more extensively, producing a higher \([\text{H}^+]\) and lower \(\text{pH}\), so the anilinium chloride solution is more acidic. (Choice A) This reverses the relationship: a larger parent-base \(K_b\) means a weaker, not stronger, conjugate acid, since \(K_a = K_w/K_b\) is inversely proportional to \(K_b\). (Choice B) Chloride is the conjugate base of the strong acid \(\text{HCl}\) in both salts and is a spectator in both, so it contributes nothing to acidity; it cannot distinguish the two solutions. (Choice C) Equal concentration does not give equal pH here, because the two cations have very different \(K_a\) values (\(2.3\times10^{-5}\) versus \(5.6\times10^{-10}\)), and the cation with the larger \(K_a\) yields the lower pH. Skill 2$ex58$,
    'hard', '5A', $cc58$Acid-Base Equilibria (GC, BC)$cc58$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a58A$Treats larger parent-base Kb as producing the stronger conjugate acid, inverting Ka = Kw/Kb$a58A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a58B$Attributes acidity to the spectator chloride ion rather than to cation hydrolysis$a58B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a58C$Correctly notes both cations are weak acids but wrongly concludes equal concentration yields equal pH$a58C$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch2_questions FROM questions WHERE topic='Acids & Bases' AND subtopic IN ('Definitions & Conjugate Acid-Base Pairs', 'Salt Hydrolysis & pH of Salt Solutions');
