-- GenChem Ch10 (Acids & Bases) — Batch 3 of 4: Titration & Titration Curves + Buffers / Henderson-Hasselbalch
-- 24 questions, all confidence >=4 (verified vs OpenStax Chemistry: Atoms First 2e + standard MCAT references; every calculation independently re-computed).
-- Cross-batch + cross-chapter deduped; final dedup audit PASS (0 genuine conflicts) after the systematic recall-answer-leak sweep.
-- AAMC foundations in this batch: 5A (per-row foundation/content_category/discipline below). Answer key balanced A/B/C/D = 24/24/24/24 across the full 96-question chapter.
-- Out of MCAT scope and deliberately excluded: normality / equivalents / gram-equivalent weight (Ch10.3 polyvalence-in-normality).
-- Re-runnable: subtopic-scoped DELETE. Run the four batches in any order in the Supabase SQL editor.
BEGIN;
DELETE FROM questions WHERE topic = 'Acids & Bases' AND subtopic IN ('Titration & Titration Curves', 'Buffers & Henderson-Hasselbalch');

-- Q1 [Titration & Titration Curves · easy · Skill 1 · 5A Titration (GC) · general-chemistry · ans A] (g59)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt59$A \(50.0\ \text{mL}\) sample of \(\text{HCl}\) of unknown concentration is titrated with \(0.100\ \text{M}\) \(\text{NaOH}\) delivered from a buret. The equivalence point of this titration is the moment at which$qt59$,
    $op59$[{"label":"A","text":"the moles of \\(\\text{NaOH}\\) added equal the moles of \\(\\text{HCl}\\) originally present."},{"label":"B","text":"the solution reaches \\(\\text{pH}\\) \\(7\\) regardless of the acid and base involved."},{"label":"C","text":"the indicator first changes color, signaling the buret reading to record."},{"label":"D","text":"the volume of \\(\\text{NaOH}\\) added equals the \\(50.0\\ \\text{mL}\\) volume of the \\(\\text{HCl}\\) sample."}]$op59$::jsonb,
    'A',
    $ex59$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is A because the equivalence point is defined stoichiometrically: it is the point at which the titrant added has supplied an amount of base chemically equivalent to the amount of acid initially present in the titrand. In this acid-base titration, \(\text{NaOH}\) (the titrant of known concentration delivered from the buret) reacts with \(\text{HCl}\) (the analyte) in a \(1{:}1\) ratio, so the equivalence point occurs exactly when \(\text{moles of NaOH added} = \text{moles of HCl originally present}\). This definition is what makes titration a quantitative method, because the known moles of titrant at that point reveal the unknown moles of analyte. (Choice B) A \(\text{pH}\) of \(7\) at the equivalence point holds only for a strong acid titrated with a strong base, where the salt formed does not hydrolyze; for a weak acid or weak base the equivalence-point \(\text{pH}\) is above or below \(7\), so neutral \(\text{pH}\) is not the general defining feature. (Choice C) The indicator color change marks the endpoint, an experimental approximation of the equivalence point chosen so the two nearly coincide; the equivalence point is the underlying stoichiometric condition, not the observed signal. (Choice D) Equal volumes of titrant and analyte coincide with the equivalence point only when their molar concentrations happen to be equal; because the equivalence point depends on equal moles rather than equal volumes, matching the \(50.0\ \text{mL}\) sample volume is generally incorrect. Skill 1$ex59$,
    'easy', '5A', $cc59$Titration (GC)$cc59$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a59B$equivalence-point-always-pH-7$a59B$ FROM q
UNION ALL SELECT id, 'C', 'adjacent_fact', $a59C$endpoint-conflated-with-equivalence-point$a59C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a59D$equal-volumes-mistaken-for-equal-moles$a59D$ FROM q;

-- Q2 [Titration & Titration Curves · easy · Skill 2 · 5A Titration (GC) · general-chemistry · ans B] (g60)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt60$A 40.0 mL sample of 0.100 M \(\text{HCl}\) is titrated with 0.200 M \(\text{NaOH}\). What volume of \(\text{NaOH}\) is required to reach the equivalence point?$qt60$,
    $op60$[{"label":"A","text":"10.0 mL"},{"label":"B","text":"20.0 mL"},{"label":"C","text":"40.0 mL"},{"label":"D","text":"80.0 mL"}]$op60$::jsonb,
    'B',
    $ex60$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is B because at the equivalence point of a monoprotic strong acid–strong base titration the moles of added \(\text{OH}^-\) exactly equal the moles of \(\text{H}^+\) initially present, so \(M_\text{acid}V_\text{acid} = M_\text{base}V_\text{base}\). Compute the moles of acid: \((0.100\ \text{M})(40.0\ \text{mL}) = 4.00\ \text{mmol}\ \text{HCl}\). At equivalence this requires \(4.00\ \text{mmol}\ \text{NaOH}\). Solving for the base volume, \(V_\text{base} = \dfrac{M_\text{acid}V_\text{acid}}{M_\text{base}} = \dfrac{(0.100)(40.0)}{0.200} = 20.0\ \text{mL}\). Because the base is twice as concentrated as the acid, it takes half the acid's volume to neutralize it. (Choice A) 10.0 mL comes from dividing the 20.0 mL result by an extra factor of two, as if the base were four times as concentrated as the acid; only one factor of \(\tfrac{0.200}{0.100} = 2\) applies, giving 20.0 mL, not 10.0 mL. (Choice C) 40.0 mL assumes the equivalence point occurs when equal volumes of acid and base are mixed, which is true only for equal concentrations; here \(M_\text{base} = 0.200\ \text{M} \neq M_\text{acid} = 0.100\ \text{M}\), so equal volumes would deliver twice the needed \(\text{OH}^-\). (Choice D) 80.0 mL comes from inverting the formula and computing \(\dfrac{M_\text{base}V_\text{acid}}{M_\text{acid}} = \dfrac{(0.200)(40.0)}{0.100}\); this misplaces the base molarity in the numerator, whereas the more concentrated base must require a smaller, not larger, volume. Skill 2$ex60$,
    'easy', '5A', $cc60$Titration (GC)$cc60$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'scale_unit_error', $a60A$Applied an extra factor-of-two division, treating the concentration ratio as 4 instead of 2$a60A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a60C$Assumed equivalence occurs at equal volumes, ignoring the unequal concentrations$a60C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a60D$Inverted the dilution formula, placing base molarity in the numerator so the more concentrated base appears to need more volume$a60D$ FROM q;

-- Q3 [Titration & Titration Curves · easy · Skill 2 · 5A Titration (GC) · general-chemistry · ans C] (g61)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt61$A 25.00 mL sample of 0.0500 M acetic acid, a monoprotic acid, is titrated with a strong base until it reaches the equivalence point. How many moles of strong base have been added at the equivalence point?$qt61$,
    $op61$[{"label":"A","text":"\\(1.25\\,\\text{mol}\\)"},{"label":"B","text":"\\(2.50\\times10^{-3}\\,\\text{mol}\\)"},{"label":"C","text":"\\(1.25\\times10^{-3}\\,\\text{mol}\\)"},{"label":"D","text":"\\(6.25\\times10^{-4}\\,\\text{mol}\\)"}]$op61$::jsonb,
    'C',
    $ex61$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is C because at the equivalence point the moles of strong base added exactly equal the moles of acid originally present, and the acid is monoprotic so each mole of acid neutralizes one mole of base. First convert the analyte volume from milliliters to liters: \(25.00\,\text{mL} = 0.02500\,\text{L}\). Then moles of acetic acid \(= M \times V = (0.0500\,\text{mol/L})(0.02500\,\text{L}) = 1.25\times10^{-3}\,\text{mol}\). Because the equivalence point is defined by \(\text{moles base} = \text{moles acid}\) for a 1:1 monoprotic neutralization, the base added equals \(1.25\times10^{-3}\,\text{mol}\). (Choice A) \(1.25\,\text{mol}\) results from multiplying \(0.0500\) by \(25.00\) without converting milliliters to liters, inflating the answer by a factor of 1000. (Choice B) \(2.50\times10^{-3}\,\text{mol}\) results from doubling the moles of acid as if a second equivalent of base were required, which would only apply to a diprotic acid, not a monoprotic acid like acetic acid. (Choice D) \(6.25\times10^{-4}\,\text{mol}\) results from incorrectly halving the moles of acid, as if the equivalence point were reached after adding only half an equivalent of base. Skill 2$ex61$,
    'easy', '5A', $cc61$Titration (GC)$cc61$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'scale_unit_error', $a61A$Multiplied molarity by volume in mL without converting to L, off by 1000$a61A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a61B$Treated monoprotic acid as diprotic and doubled the required moles of base$a61B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a61D$Halved the moles of acid, as if equivalence occurs at half-neutralization$a61D$ FROM q;

-- Q4 [Titration & Titration Curves · easy · Skill 1 · 5A Titration (GC) · general-chemistry · ans D] (g62)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt62$A 25.0 mL sample of 0.100 M HCl is titrated with 0.100 M NaOH at 25 °C. What is the pH of the solution at the equivalence point, where exactly 25.0 mL of titrant has been added?$qt62$,
    $op62$[{"label":"A","text":"\\(\\text{pH} = 1.00\\)"},{"label":"B","text":"\\(\\text{pH} = 4.00\\)"},{"label":"C","text":"\\(\\text{pH} = 13.00\\)"},{"label":"D","text":"\\(\\text{pH} = 7.00\\)"}]$op62$::jsonb,
    'D',
    $ex62$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is D because the equivalence point of a strong acid–strong base titration is exactly neutral at 25 °C. At the equivalence point the moles of \(\text{NaOH}\) added equal the moles of \(\text{HCl}\) present: \((0.100\ \text{M})(0.0250\ \text{L}) = 2.50 \times 10^{-3}\ \text{mol}\) of each, so all \(\text{HCl}\) is consumed and neither acid nor base is in excess. The only species remaining besides water is the salt \(\text{NaCl}\). Because \(\text{Na}^+\) is the cation of a strong base and \(\text{Cl}^-\) is the anion of a strong acid, neither ion hydrolyzes, so the salt is pH-neutral and the pH is fixed solely by water autoionization: \([\text{H}^+] = [\text{OH}^-] = 1.0 \times 10^{-7}\ \text{M}\), giving \(\text{pH} = -\log(1.0 \times 10^{-7}) = 7.00\). (Choice A) \(\text{pH} = 1.00\) is \(-\log(0.100)\), the pH of the original \(\text{HCl}\) before any base is added; it ignores that the titration has reached the equivalence point and the acid has been fully neutralized. (Choice B) \(\text{pH} = 4.00\) assumes the salt hydrolyzes to give an acidic solution, but \(\text{Cl}^-\) is the conjugate base of a strong acid and is far too weak to hydrolyze, so no acidity is generated. (Choice C) \(\text{pH} = 13.00\) treats the titrant base as if it were in excess, computing \(\text{pOH} = -\log(0.100) = 1.00\) and \(\text{pH} = 14.00 - 1.00 = 13.00\); at the exact equivalence point, however, the base is not in excess—stoichiometric amounts have reacted. Skill 1$ex62$,
    'easy', '5A', $cc62$Titration (GC)$cc62$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a62A$Reports the initial pH of the analyte acid (\(-\log 0.100 = 1.00\)) instead of the equivalence-point pH$a62A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a62B$Believes the spectator salt NaCl undergoes hydrolysis to produce an acidic solution$a62B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a62C$Treats the strong-base titrant as being in excess at the equivalence point, yielding a strongly basic pH$a62C$ FROM q;

-- Q5 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans A] (g63)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt63$Two monoprotic weak acids of equal concentration are each titrated with \( \text{NaOH} \) of the same concentration, and their titration curves are recorded: \( \text{HA} \) has \( K_a = 1\times10^{-5} \), and \( \text{HB} \) has \( K_a = 1\times10^{-3} \). Which titration shows the larger, sharper vertical \( \text{pH} \) jump in the region surrounding its equivalence point, and why?$qt63$,
    $op63$[{"label":"A","text":"The titration of \\( \\text{HB} \\), because its buffer plateau just before equivalence sits at a lower \\( \\text{pH} \\) while the \\( \\text{pH} \\) just past equivalence is set by the same excess strong base, so the vertical rise spans a wider \\( \\text{pH} \\) range."},{"label":"B","text":"The titration of \\( \\text{HA} \\), because its buffer plateau just before equivalence sits at a lower \\( \\text{pH} \\) while the \\( \\text{pH} \\) just past equivalence is set by the same excess strong base, so the vertical rise spans a wider \\( \\text{pH} \\) range."},{"label":"C","text":"Neither; both curves show the same size of jump, because just past the equivalence point each solution contains the same excess of strong base and reaches the same \\( \\text{pH} \\)."},{"label":"D","text":"Neither; both curves show the same size of jump, because the magnitude of the jump is fixed by the concentrations of acid and titrant and does not depend on the acid's \\( K_a \\)."}]$op63$::jsonb,
    'A',
    $ex63$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is A because the size of the steep jump near the equivalence point is the difference between the \( \text{pH} \) just before equivalence and the \( \text{pH} \) just after it. Just before equivalence the solution is a buffer whose \( \text{pH} \) tracks the acid's \( \text{p}K_a \): the stronger acid \( \text{HB} \) (larger \( K_a \), so lower \( \text{p}K_a \)) holds its buffer plateau at a lower \( \text{pH} \) than the weaker acid \( \text{HA} \). Just after equivalence, the \( \text{pH} \) of both solutions is governed by the same small excess of identical strong base, so both rise to essentially the same high \( \text{pH} \). Because \( \text{HB} \) starts the climb from a lower buffer \( \text{pH} \) and ends at the same point, its vertical jump spans a wider \( \text{pH} \) range and is sharper; \( \text{HA} \)'s plateau lies closer to its endpoint, so its jump is smaller and more gradual. (Choice B) reverses the relationship: the weaker acid \( \text{HA} \) has the higher buffer plateau, so its climb to the common post-equivalence \( \text{pH} \) is shorter, giving the smaller jump rather than the larger one. (Choice C) correctly notes that the post-equivalence \( \text{pH} \) is the same for both, but it ignores the pre-equivalence buffer level, which differs with \( \text{p}K_a \); equal endpoints with different starting plateaus give jumps of different size. (Choice D) is wrong because the jump magnitude does depend on \( K_a \): for fixed concentrations, the buffer \( \text{pH} \) just before equivalence is set by \( \text{p}K_a \), so two acids of different \( K_a \) produce jumps of different size. Skill 4$ex63$,
    'medium', '5A', $cc63$Titration (GC)$cc63$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a63B$weaker acid wrongly assigned the larger/sharper equivalence-point jump$a63B$ FROM q
UNION ALL SELECT id, 'C', 'partial_truth', $a63C$correct that post-equivalence pH matches but ignores the differing pre-equivalence buffer plateau$a63C$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a63D$believes the jump magnitude depends only on concentration and is independent of Ka$a63D$ FROM q;

-- Q6 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans D] (g64)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt64$A \(25.0\,\text{mL}\) sample of \(0.10\,\text{M}\) aqueous ammonia (a weak base) and a separate \(25.0\,\text{mL}\) sample of \(0.10\,\text{M}\) \(\text{NaOH}\) (a strong base) are each titrated with the same \(0.10\,\text{M}\) \(\text{HCl}\) solution. How do the volumes of \(\text{HCl}\) required to reach the equivalence point in the two titrations compare?$qt64$,
    $op64$[{"label":"A","text":"The volumes cannot be compared without knowing the \\(K_b\\) of ammonia, since the strength of the base sets the amount of titrant needed."},{"label":"B","text":"The ammonia sample requires less \\(\\text{HCl}\\), because as a weak base it is only partially ionized and so presents fewer moles to neutralize."},{"label":"C","text":"The ammonia sample requires more \\(\\text{HCl}\\), because additional titrant is needed to drive the incomplete ionization of the weak base to completion."},{"label":"D","text":"The volumes are equal, because reaching the equivalence point depends only on the stoichiometric mole ratio of acid to base, not on the strength of the base."}]$op64$::jsonb,
    'D',
    $ex64$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is D because the equivalence point is reached when the moles of added acid equal the moles of base originally present, and that mole count is fixed entirely by the stoichiometry of the samples. Each sample contains \((0.0250\,\text{L})(0.10\,\text{M}) = 2.5\times10^{-3}\,\text{mol}\) of base, so each requires \(2.5\times10^{-3}\,\text{mol}\) of \(\text{HCl}\), which at \(0.10\,\text{M}\) is exactly \(25.0\,\text{mL}\) in both cases. The strength of the base governs the pH at the equivalence point (the ammonia titration gives an acidic equivalence point because \(\text{NH}_4^+\) remains, while the \(\text{NaOH}\) titration gives a neutral one), but it does not change the volume of titrant needed to get there. (Choice A) The \(K_b\) value affects only the pH profile of the curve and the pH at equivalence, not the equivalence volume, which is determined solely by the moles of base present. (Choice B) This reflects the common misconception that partial ionization reduces the moles available to react; in fact, as protons are removed by the acid, the equilibrium continually replenishes the reactive base, so the full \(2.5\times10^{-3}\,\text{mol}\) is ultimately neutralized. (Choice C) This is the opposite misconception, assuming extra titrant is consumed to overcome incomplete ionization, but the stoichiometric mole ratio—not the rate or extent of ionization—sets the endpoint volume. Skill 4$ex64$,
    'medium', '5A', $cc64$Titration (GC)$cc64$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a64A$equivalence volume cannot be found without Kb because strength sets titrant amount$a64A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a64B$weak base is only partially ionized so fewer moles need neutralizing$a64B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a64C$extra titrant needed to drive incomplete weak-base ionization to completion$a64C$ FROM q;

-- Q7 [Titration & Titration Curves · hard · Skill 2 · 5A Titration (GC) · general-chemistry · ans C] (g65)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt65$A \(25.00\,\text{mL}\) sample of \(0.100\,\text{M}\) \(\text{HCl}\) is titrated with \(0.100\,\text{M}\) \(\text{NaOH}\). After exactly \(12.50\,\text{mL}\) of the \(\text{NaOH}\) has been added (before the equivalence point), what is the \(\text{pH}\) of the solution? Both species are strong, so treat the neutralization as complete.$qt65$,
    $op65$[{"label":"A","text":"\\(\\text{pH} = 1.30\\)"},{"label":"B","text":"\\(\\text{pH} = 1.18\\)"},{"label":"C","text":"\\(\\text{pH} = 1.48\\)"},{"label":"D","text":"\\(\\text{pH} = 7.00\\)"}]$op65$::jsonb,
    'C',
    $ex65$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is C because at a pre-equivalence point in a strong acid-strong base titration the \(\text{pH}\) is set by the leftover excess strong acid, whose concentration must be computed using the total combined volume. First find the moles present: \(\text{HCl} = 0.02500\,\text{L} \times 0.100\,\text{M} = 2.50\times10^{-3}\,\text{mol}\) and \(\text{NaOH} = 0.01250\,\text{L} \times 0.100\,\text{M} = 1.25\times10^{-3}\,\text{mol}\). The added \(\text{OH}^-\) neutralizes an equal amount of \(\text{H}^+\), leaving excess \(\text{H}^+ = 2.50\times10^{-3} - 1.25\times10^{-3} = 1.25\times10^{-3}\,\text{mol}\). The total volume is now \(25.00 + 12.50 = 37.50\,\text{mL} = 0.03750\,\text{L}\), so \([\text{H}^+] = \dfrac{1.25\times10^{-3}}{0.03750} = 0.0333\,\text{M}\). Then \(\text{pH} = -\log(0.0333) = 1.48\). (Choice A) \(\text{pH} = 1.30\) comes from dividing the excess \(1.25\times10^{-3}\,\text{mol}\) of \(\text{H}^+\) by the original acid volume \(0.02500\,\text{L}\) to get \(0.0500\,\text{M}\); this ignores that the added base volume dilutes the solution, so the total volume \(0.03750\,\text{L}\) must be used. (Choice B) \(\text{pH} = 1.18\) comes from dividing the original \(2.50\times10^{-3}\,\text{mol}\) of \(\text{H}^+\) by the total volume \(0.03750\,\text{L}\) to get \(0.0667\,\text{M}\); this fails to subtract the moles of acid neutralized by the added base before computing the concentration. (Choice D) \(\text{pH} = 7.00\) treats the solution as if it had reached the equivalence point where strong acid and strong base exactly cancel to give a neutral salt solution, but only half of the acid has been neutralized at \(12.50\,\text{mL}\), so excess acid remains and the \(\text{pH}\) is well below \(7\). Skill 2$ex65$,
    'hard', '5A', $cc65$Titration (GC)$cc65$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a65A$divides excess H+ moles by the original acid volume instead of the total combined volume, ignoring dilution by the added base$a65A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a65B$divides the original (un-neutralized) moles of acid by the total volume, failing to subtract the H+ consumed by the added OH-$a65B$ FROM q
UNION ALL SELECT id, 'D', 'misconception', $a65D$assumes the pre-equivalence point is the equivalence point and reports a neutral pH of 7 for the strong acid-strong base mixture$a65D$ FROM q;

-- Q8 [Titration & Titration Curves · hard · Skill 2 · 5A Titration (GC) · general-chemistry · ans D] (g66)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt66$A 25.00 mL sample of 0.100 M \(\text{HCl}\) is titrated with 0.100 M \(\text{NaOH}\). After a total of 37.50 mL of titrant has been delivered — 12.50 mL beyond the equivalence point — what is the \(\text{pH}\) of the resulting solution at 25 °C?$qt66$,
    $op66$[{"label":"A","text":"\\(\\text{pH} = 1.70\\)"},{"label":"B","text":"\\(\\text{pH} = 12.78\\)"},{"label":"C","text":"\\(\\text{pH} = 13.00\\)"},{"label":"D","text":"\\(\\text{pH} = 12.30\\)"}]$op66$::jsonb,
    'D',
    $ex66$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is D because the strong-base titrant is in excess past the equivalence point, so the leftover \(\text{OH}^-\) sets the \(\text{pH}\). Initial acid: \(25.00\,\text{mL} \times 0.100\,\text{M} = 2.500\,\text{mmol}\ \text{H}^+\). Titrant added: \(37.50\,\text{mL} \times 0.100\,\text{M} = 3.750\,\text{mmol}\ \text{OH}^-\). The first \(2.500\,\text{mmol}\ \text{OH}^-\) neutralizes all the \(\text{H}^+\) (equivalence at 25.00 mL), leaving excess \(\text{OH}^-\) of \(3.750 - 2.500 = 1.250\,\text{mmol}\). The total volume is \(25.00 + 37.50 = 62.50\,\text{mL}\), so \([\text{OH}^-] = 1.250\,\text{mmol} / 62.50\,\text{mL} = 0.0200\,\text{M}\). Then \(\text{pOH} = -\log(0.0200) = 1.70\), and \(\text{pH} = 14.00 - 1.70 = 12.30\). (Choice A) \(1.70\) is the \(\text{pOH}\) of the solution reported as if it were the \(\text{pH}\); past the equivalence point the solution is strongly basic, so \(\text{pH} = 14.00 - \text{pOH} = 12.30\), not the \(\text{pOH}\) value itself. (Choice B) \(12.78\) results from dividing the total titrant (\(3.750\,\text{mmol}\)) by 62.50 mL to get \([\text{OH}^-] = 0.0600\,\text{M}\), failing to subtract the \(2.500\,\text{mmol}\) consumed in neutralizing the acid. (Choice C) \(13.00\) comes from dividing the correct excess \(1.250\,\text{mmol}\) by only the 12.50 mL added past equivalence rather than the full 62.50 mL solution volume, giving \(0.100\,\text{M}\) instead of \(0.0200\,\text{M}\). Skill 2$ex66$,
    'hard', '5A', $cc66$Titration (GC)$cc66$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a66A$Reports pOH as pH$a66A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a66B$Uses total titrant moles without subtracting neutralized acid$a66B$ FROM q
UNION ALL SELECT id, 'C', 'scale_unit_error', $a66C$Divides excess base by post-equivalence volume instead of total volume$a66C$ FROM q;

-- Q9 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans B] (g67)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt67$A titration curve is recorded as a solution of unknown composition is titrated. The curve begins well up in the basic range, at a high \(\text{pH}\) far above 7, then falls only gradually through an early, nearly flat plateau as titrant is added and the dissolved species is steadily converted to its conjugate partner. After this buffer-like region the curve drops almost vertically through a narrow steep zone, and the equivalence point lands in the acidic range, below \(\text{pH}\) 7, because the species present at equivalence is a weak conjugate acid that donates protons to water. Which acid-base pairing produced this curve?$qt67$,
    $op67$[{"label":"A","text":"A strong acid titrated with a strong base"},{"label":"B","text":"A weak base titrated with a strong acid"},{"label":"C","text":"A weak acid titrated with a strong base"},{"label":"D","text":"A strong base titrated with a strong acid"}]$op67$::jsonb,
    'B',
    $ex67$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is B because every recorded feature matches a weak base being titrated with a strong acid. The solution starts in the basic range because the analyte in the flask is a weak base, giving an initial \(\text{pH}\) above 7. As strong acid is added, the weak base is progressively converted to its conjugate acid, and the coexistence of the weak base with its conjugate acid creates a buffer region that appears as the early, nearly flat plateau where \(\text{pH}\) changes only slowly. Past the steep region the equivalence point falls in the acidic range, below 7, because at equivalence essentially all of the weak base has been converted to its conjugate acid, and that conjugate acid undergoes the ionization \(\text{BH}^+ + \text{H}_2\text{O} \rightleftharpoons \text{B} + \text{H}_3\text{O}^+\), generating \(\text{H}_3\text{O}^+\) and depressing the \(\text{pH}\) below 7. (Choice A) A strong acid titrated with a strong base would begin at a very low \(\text{pH}\) near 1, not in the basic range, would show no buffer plateau because neither species has a conjugate equilibrium, and its equivalence point would be neutral rather than acidic; this choice reverses the entire shape of the curve. (Choice C) A weak acid titrated with a strong base produces the mirror-image curve: it begins in the acidic range at low \(\text{pH}\), rises through a buffer plateau, and reaches an equivalence point in the basic range above 7 because the conjugate base hydrolyzes; the described curve runs in the opposite direction. (Choice D) A strong base titrated with a strong acid does begin in the basic range, which matches the start, but it lacks a buffer plateau and its equivalence point is neutral rather than acidic, so the basic starting point alone cannot account for the conjugate-acid equivalence in the acidic range. Skill 4$ex67$,
    'medium', '5A', $cc67$Titration (GC)$cc67$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a67A$strong-strong curve has neutral equivalence and low acidic start, the reverse shape of the described basic-start acidic-equivalence curve$a67A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a67C$confuses the curve with its mirror image (acidic start rising to basic equivalence) for a weak acid titrated with strong base$a67C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a67D$correct basic starting point but wrong neutral equivalence, ignoring that the acidic equivalence requires a weak conjugate acid$a67D$ FROM q;

-- Q10 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans B] (g68)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt68$A titration curve is recorded for a solution of unknown composition. From the very start the \(\text{pH}\) changes only gradually; the curve is shallow throughout, and—unlike the other titration types—it shows no steep, near-vertical jump anywhere. Near the point where stoichiometrically equivalent amounts have reacted, the \(\text{pH}\) passes gently through a value close to neutral with only a slight, poorly defined inflection. Which acid-base combination produces a curve that lacks any sharp equivalence-point jump like this?$qt68$,
    $op68$[{"label":"A","text":"A strong acid titrated with a strong base"},{"label":"B","text":"A weak acid titrated with a weak base"},{"label":"C","text":"A weak acid titrated with a strong base"},{"label":"D","text":"A weak base titrated with a strong acid"}]$op68$::jsonb,
    'B',
    $ex68$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is B because only a weak-acid/weak-base titration lacks a sharp, near-vertical jump at the equivalence point. Both the analyte and the titrant are only partially ionized, so near the equivalence point neither a large excess of \(\text{H}_3\text{O}^+\) nor of \(\text{OH}^-\) builds up; the \(\text{pH}\) changes only slightly and gradually, passing through a poorly defined inflection near neutral. This shallow shape, with no steep rise or fall, is exactly why weak/weak titrations are difficult to follow with an indicator. (Choice A) A strong acid titrated with a strong base gives the SHARPEST, tallest near-vertical jump of all, passing through \(\text{pH}\) 7 at equivalence — the opposite of the shallow, jumpless curve described. (Choice C) A weak acid titrated with a strong base does show a steep rise at equivalence (to a basic equivalence point well above 7) after its buffer region, so it has the sharp jump this curve lacks. (Choice D) A weak base titrated with a strong acid starts basic and drops through a steep jump to an acidic equivalence point, so it too has a sharp jump that the described curve does not. Skill 4$ex68$,
    'medium', '5A', $cc68$Titration (GC)$cc68$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a68A$expects the sharp strong/strong jump even for the shallow, jumpless curve described$a68A$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a68C$weak acid + strong base does have a steep jump to a basic equivalence point$a68C$ FROM q
UNION ALL SELECT id, 'D', 'reversed_relationship', $a68D$mirror case: weak base + strong acid has a steep jump to an acidic equivalence point$a68D$ FROM q;

-- Q11 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans C] (g69)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt69$A 0.10 M acetic acid solution (\(\text{p}K_a = 4.74\)) is titrated with 0.10 M NaOH, producing a curve that starts near \(\text{pH}\) 3, rises steeply at first, then enters a long region where the \(\text{pH}\) climbs only slowly and is flattest near \(\text{pH}\) 4.7 midway toward the equivalence point, after which it rises sharply through an equivalence point near \(\text{pH}\) 9 and then levels off again at high \(\text{pH}\). The titration possesses its greatest buffering capacity in the region where$qt69$,
    $op69$[{"label":"A","text":"the \\(\\text{pH}\\) rises most steeply through the equivalence point near \\(\\text{pH}\\) 9, because the largest change in \\(\\text{pH}\\) marks the point of greatest resistance to added base."},{"label":"B","text":"the very start of the titration before any base is added, because the solution there is essentially pure acetic acid and is therefore most able to neutralize added base."},{"label":"C","text":"the \\(\\text{pH}\\) is flattest near \\(\\text{pH}\\) 4.7 midway toward the equivalence point, because \\([\\text{CH}_3\\text{COOH}]\\) and \\([\\text{CH}_3\\text{COO}^-]\\) are comparable there so the \\(\\text{pH}\\) changes least per increment of base."},{"label":"D","text":"the curve levels off again at high \\(\\text{pH}\\) past the equivalence point, because a flat \\(\\text{pH}\\) there shows the solution is resisting further change from added base."}]$op69$::jsonb,
    'C',
    $ex69$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is C because buffering capacity is greatest where the titration curve is flattest before the equivalence point, and for a weak acid that flat plateau is centered on the half-equivalence point. Between the start and the equivalence point, added \(\text{OH}^-\) converts \(\text{CH}_3\text{COOH}\) into \(\text{CH}_3\text{COO}^-\), so the solution contains a mixture of the weak acid and its conjugate base, the defining condition of a buffer. By the Henderson-Hasselbalch relationship \(\text{pH} = \text{p}K_a + \log\frac{[\text{CH}_3\text{COO}^-]}{[\text{CH}_3\text{COOH}]}\), the \(\text{pH}\) sits at \(\text{p}K_a = 4.74\) when the two species are present in equal amounts (the half-equivalence point), and near that point the log ratio changes only slightly per increment of base, so the \(\text{pH}\) barely moves. That minimal change in \(\text{pH}\) per added base is exactly what maximum buffering capacity means, which is why the described flat region near \(\text{pH}\) 4.7 is the answer. (Choice A) The steep rise through the equivalence point is the region of least buffering, not most: there the weak acid is nearly exhausted, so a small amount of added base produces a very large \(\text{pH}\) jump; this reverses the relationship between curve steepness and buffering capacity. (Choice B) At the very start the solution is almost pure acetic acid with very little conjugate base present, so the buffer ratio is far from 1 and the \(\text{pH}\) changes relatively rapidly with the first additions of base; a buffer requires comparable amounts of both members of the conjugate pair, which has not yet been established. (Choice D) The flat region past the equivalence point reflects excess strong base (\(\text{NaOH}\)) dominating the \(\text{pH}\), not a weak-acid/conjugate-base buffer; the curve is shallow there simply because \(\text{pH}\) is a logarithmic scale and added strong base changes \([\text{OH}^-]\) only modestly, so it does not represent buffering by the acetate system. Skill 4$ex69$,
    'medium', '5A', $cc69$Titration (GC)$cc69$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'reversed_relationship', $a69A$Equates the steepest part of the curve (equivalence point) with greatest buffering, reversing the true relationship between curve flatness and buffering capacity$a69A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a69B$Believes pure weak acid before any base is added is the best buffer, ignoring that a buffer requires comparable amounts of conjugate acid and base$a69B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a69D$Confuses the post-equivalence flat region (excess strong base on a log scale) with buffering by the weak-acid/conjugate-base pair$a69D$ FROM q;

-- Q12 [Titration & Titration Curves · medium · Skill 4 · 5A Titration (GC) · general-chemistry · ans B] (g70)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt70$A \(0.10\ \text{M}\) solution of the weak acid propanoic acid is titrated with \(0.10\ \text{M}\ \text{NaOH}\), and the equivalence point falls at \(\text{pH}\) near \(9\). An indicator changes color over the interval \(\text{p}K_{a(\text{In})} \pm 1\). Which indicator's transition range correctly brackets this equivalence point so the color change signals it?$qt70$,
    $op70$[{"label":"A","text":"Methyl orange, transition range \\(\\text{pH}\\ 3.2\\text{–}4.4\\)"},{"label":"B","text":"Phenolphthalein, transition range \\(\\text{pH}\\ 8.3\\text{–}10.0\\)"},{"label":"C","text":"Bromothymol blue, transition range \\(\\text{pH}\\ 6.0\\text{–}7.6\\)"},{"label":"D","text":"Methyl red, transition range \\(\\text{pH}\\ 4.4\\text{–}6.2\\)"}]$op70$::jsonb,
    'B',
    $ex70$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is B because the indicator's color-change interval must bracket the equivalence-point \(\text{pH}\), and only phenolphthalein's range of \(\text{pH}\ 8.3\text{–}10.0\) contains the equivalence point near \(\text{pH}\ 9\). An acid–base indicator is itself a weak acid \(\text{HIn}\) whose protonated and deprotonated conjugate forms differ in color; the visible color shifts over roughly \(\text{p}K_{a(\text{In})} \pm 1\), so a phenolphthalein \(\text{p}K_{a(\text{In})}\) near \(9\) gives a transition centered on the equivalence \(\text{pH}\). A weak acid titrated with a strong base yields a basic equivalence point because the conjugate base remaining in solution hydrolyzes, so the steep portion of the curve passes through \(\text{pH}\ 9\), where the \(8.3\text{–}10.0\) window sits squarely on the vertical region and changes color sharply. (Choice A) Methyl orange transitions at \(\text{pH}\ 3.2\text{–}4.4\), well below the equivalence point; it would change color early on the slowly rising buffer region and never bracket \(\text{pH}\ 9\). (Choice C) Bromothymol blue spans \(\text{pH}\ 6.0\text{–}7.6\), appropriate for a strong-acid–strong-base titration that equilibrates near \(\text{pH}\ 7\), but it lies below the basic equivalence point of this weak-acid system. (Choice D) Methyl red transitions at \(\text{pH}\ 4.4\text{–}6.2\), which brackets the half-equivalence buffer region near the acid's \(\text{p}K_a\) rather than the equivalence point, so it would change color far too soon. Skill 4$ex70$,
    'medium', '5A', $cc70$Titration (GC)$cc70$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'adjacent_fact', $a70A$Selects a real indicator whose acidic-range transition fits a strong-acid endpoint, not the basic weak-acid equivalence point$a70A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a70C$Assumes every equivalence point occurs at neutral pH 7 and picks the indicator centered there$a70C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a70D$Confuses the half-equivalence (pH = pKa buffer) region with the equivalence point and matches the indicator to the wrong curve feature$a70D$ FROM q;

-- Q13 [Titration & Titration Curves · hard · Skill 4 · 5A Titration (GC) · general-chemistry · ans A] (g71)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Titration & Titration Curves',
    $qt71$A chemist titrates the diprotic acid malonic acid (\(\text{p}K_{a1}=2.8\), \(\text{p}K_{a2}=5.7\)) with standardized \(\text{NaOH}\) and selects an indicator whose color change is centered on the steep portion of the second jump. The recorded titration curve starts near \(\text{pH}\) 2, rises through a half-equivalence plateau near \(\text{pH}\) 2.8, climbs to a first steep rise, levels off again near \(\text{pH}\) 5.7, then rises steeply a second time. Which statement correctly distinguishes the endpoint from the equivalence point and accounts for the two plateaus on this curve?$qt71$,
    $op71$[{"label":"A","text":"The equivalence point is where stoichiometrically equal moles of base have neutralized the acid, while the endpoint is the observed indicator color change; the two plateaus are buffer regions, one centered near each \\(\\text{p}K_a\\), reflecting the two stepwise deprotonations."},{"label":"B","text":"The endpoint is where stoichiometrically equal moles have reacted, while the equivalence point is the observed indicator color change; the two plateaus are the two equivalence points, one at each \\(\\text{p}K_a\\)."},{"label":"C","text":"The equivalence point and the endpoint are identical by definition, so the two plateaus simply mark where the indicator changes color twice as each proton is removed."},{"label":"D","text":"The equivalence point is the observed indicator color change, while the endpoint is the steep vertical region; the two plateaus are the first and second equivalence points where \\(\\text{pH}=\\text{p}K_a\\)."}]$op71$::jsonb,
    'A',
    $ex71$This is a General Chemistry question that falls under the content category 'Titration (GC)'. The answer to this question is A because the equivalence point is a stoichiometric quantity defined by equal moles of titrant and analyte having reacted, whereas the endpoint is the experimentally observed signal (the indicator color change); a well-chosen indicator merely makes the endpoint fall close to the equivalence point but does not make them the same thing. For malonic acid, a diprotic acid, neutralization proceeds in two stepwise stages, so the described curve shows two steep rises (two equivalence points) separated by two flat buffer regions. Each plateau is a half-equivalence region in which a weak acid and its conjugate base coexist; by Henderson-Hasselbalch \(\text{pH}=\text{p}K_a+\log\left(\dfrac{[\text{A}^-]}{[\text{HA}]}\right)\), the midpoint of each plateau occurs where \([\text{A}^-]=[\text{HA}]\) and \(\text{pH}=\text{p}K_a\), giving plateaus centered near \(\text{pH}\) 2.8 and \(\text{pH}\) 5.7. Thus the flat regions are buffer regions tied to the two \(\text{p}K_a\) values, not the equivalence points themselves. (Choice B) This reverses the definitions: the equivalence point is the stoichiometric quantity and the endpoint is the indicator-based observation, not the other way around; it also misidentifies the flat plateaus as the equivalence points, when equivalence points lie on the steep rises. (Choice C) The equivalence point and endpoint are not identical by definition; they are conceptually distinct and only approximately coincide when the indicator is well chosen, and the plateaus are buffer regions rather than points of color change. (Choice D) This again swaps the two definitions and incorrectly places \(\text{pH}=\text{p}K_a\) at the equivalence points; \(\text{pH}=\text{p}K_a\) holds at the half-equivalence midpoints of the buffer plateaus, while the equivalence points sit on the steep portions of the curve. Skill 1$ex71$,
    'hard', '5A', $cc71$Titration (GC)$cc71$, 'general-chemistry', 4, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'reversed_relationship', $a71B$endpoint and equivalence-point definitions swapped$a71B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a71C$endpoint and equivalence point treated as identical by definition$a71C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a71D$pH=pKa misplaced at equivalence point instead of half-equivalence$a71D$ FROM q;

-- Q14 [Buffers & Henderson-Hasselbalch · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g72)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt72$A student wants to prepare a beaker of solution that resists a change in \(\text{pH}\) when small amounts of acid or base are added. To build this buffer, which pair of solutes, both present in appreciable amounts, should be combined in the water?$qt72$,
    $op72$[{"label":"A","text":"A weak acid together with its conjugate base, such as \\(\\text{CH}_3\\text{COOH}\\) and \\(\\text{CH}_3\\text{COO}^-\\)"},{"label":"B","text":"A strong acid together with its conjugate base, such as \\(\\text{HCl}\\) and \\(\\text{Cl}^-\\)"},{"label":"C","text":"Two strong acids, such as \\(\\text{HCl}\\) and \\(\\text{HNO}_3\\)"},{"label":"D","text":"A weak acid and a strong base mixed in equal (stoichiometric) amounts, such as \\(\\text{CH}_3\\text{COOH}\\) and \\(\\text{NaOH}\\)"}]$op72$::jsonb,
    'A',
    $ex72$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because a buffer is composed of a weak acid together with its conjugate base (or a weak base together with its conjugate acid), both present in appreciable amounts. The weak acid \(\text{CH}_3\text{COOH}\) neutralizes added base, while its conjugate base \([\text{CH}_3\text{COO}^-]\) neutralizes added acid; because the conjugate pair interconverts through the equilibrium \(\text{CH}_3\text{COOH} \rightleftharpoons \text{H}^+ + \text{CH}_3\text{COO}^-\), the ratio \([\text{A}^-]/[\text{HA}]\) shifts only slightly and the \(\text{pH}\) stays near \(\text{p}K_a\), as expressed by the Henderson-Hasselbalch relation \(\text{pH} = \text{p}K_a + \log\frac{[\text{A}^-]}{[\text{HA}]}\). (Choice B) A strong acid such as \(\text{HCl}\) ionizes essentially completely, so its conjugate base \(\text{Cl}^-\) is an exceedingly weak base that does not appreciably accept protons; there is no reservoir of un-ionized acid and no working equilibrium, so the pair cannot resist \(\text{pH}\) change. (Choice C) Two strong acids supply only \(\text{H}^+\) and provide no conjugate base reservoir to neutralize added acid, so the mixture is simply a strongly acidic solution rather than a buffer. (Choice D) Combining a weak acid with a strong base in equal stoichiometric amounts runs the neutralization to completion, consuming essentially all of the \(\text{CH}_3\text{COOH}\) and leaving only \(\text{CH}_3\text{COO}^-\); with the weak-acid component gone, no conjugate pair remains and the solution has no buffering capacity (a buffer requires a sub-stoichiometric amount of strong base so that both species coexist). Skill 1$ex72$,
    'easy', '5A', $cc72$Acid-Base Equilibria (GC, BC)$cc72$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'misconception', $a72B$strong-acid-conjugate-base-can-buffer$a72B$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a72C$no-conjugate-base-reservoir$a72C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a72D$stoichiometric-neutralization-leaves-no-weak-acid$a72D$ FROM q;

-- Q15 [Buffers & Henderson-Hasselbalch · medium · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g73)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt73$An acetic-acid/acetate buffer is prepared containing \(0.30\ \text{M}\ \text{CH}_3\text{COOH}\) and \(0.030\ \text{M}\ \text{CH}_3\text{COO}^-\), where acetic acid has \(\text{p}K_a = 4.74\). What is the \(\text{pH}\) of this buffer?$qt73$,
    $op73$[{"label":"A","text":"\\(\\text{pH} = 4.74\\)"},{"label":"B","text":"\\(\\text{pH} = 3.74\\)"},{"label":"C","text":"\\(\\text{pH} = 5.74\\)"},{"label":"D","text":"\\(\\text{pH} = 4.04\\)"}]$op73$::jsonb,
    'B',
    $ex73$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because the Henderson-Hasselbalch equation, \(\text{pH} = \text{p}K_a + \log\frac{[\text{A}^-]}{[\text{HA}]}\), gives \(\text{pH} = 4.74 + \log\frac{0.030}{0.30} = 4.74 + \log(0.10) = 4.74 + (-1.00) = 3.74\). Because the conjugate base \(\text{CH}_3\text{COO}^-\) is present at one-tenth the concentration of the acid \(\text{CH}_3\text{COOH}\), the buffer sits one \(\log\) unit below \(\text{p}K_a\), making it more acidic than the half-neutralized point. (Choice A) \(\text{pH} = 4.74\) results from dropping the \(\log\) term entirely and equating \(\text{pH}\) to \(\text{p}K_a\); that equality only holds when \([\text{A}^-] = [\text{HA}]\), which is not the case here since the ratio is \(0.10\), not \(1\). (Choice C) \(\text{pH} = 5.74\) comes from a sign error, adding \(1.00\) to \(\text{p}K_a\) instead of subtracting; this would correspond to \([\text{A}^-]\) being ten times the acid, the reverse of the given ratio. (Choice D) \(\text{pH} = 4.04\) reflects an arithmetic slip in evaluating the logarithm (treating \(\log(0.10)\) as roughly \(-0.70\) rather than exactly \(-1.00\)); \(\log(0.10)\) equals \(-1.00\) because \(0.10 = 10^{-1}\). Skill 2$ex73$,
    'medium', '5A', $cc73$Acid-Base Equilibria (GC, BC)$cc73$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a73A$Ignores the concentration ratio term and sets pH equal to pKa$a73A$ FROM q
UNION ALL SELECT id, 'C', 'misconception', $a73C$Sign error: adds the log term instead of subtracting it$a73C$ FROM q
UNION ALL SELECT id, 'D', 'scale_unit_error', $a73D$Arithmetic slip evaluating log(0.10) as about -0.70 instead of -1.00$a73D$ FROM q;

-- Q16 [Buffers & Henderson-Hasselbalch · easy · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g74)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt74$A formic-acid buffer is prepared containing 0.15 M formic acid (\(\text{HCOOH}\), \(\text{p}K_a = 3.75\)) and 0.15 M sodium formate (\(\text{HCOO}^-\)) in the same solution. What is the \(\text{pH}\) of this buffer?$qt74$,
    $op74$[{"label":"A","text":"\\(\\text{pH} = 7.00\\)"},{"label":"B","text":"\\(\\text{pH} = 1.00\\)"},{"label":"C","text":"\\(\\text{pH} = 3.75\\)"},{"label":"D","text":"\\(\\text{pH} = 4.75\\)"}]$op74$::jsonb,
    'C',
    $ex74$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the Henderson-Hasselbalch equation, \(\text{pH} = \text{p}K_a + \log\!\left(\frac{[\text{A}^-]}{[\text{HA}]}\right)\), reduces to \(\text{pH} = \text{p}K_a\) whenever the conjugate base and weak acid are present at equal concentrations. Here \([\text{HCOO}^-] = [\text{HCOOH}] = 0.15\ \text{M}\), so the ratio \(\frac{[\text{A}^-]}{[\text{HA}]} = \frac{0.15}{0.15} = 1\) and \(\log(1) = 0\). Therefore \(\text{pH} = 3.75 + \log(1) = 3.75 + 0 = 3.75\). Note that the buffer is acidic, not neutral, even though the two species are at equal concentration, because the \(\text{pH}\) is fixed by the acid's \(\text{p}K_a\). (Choice A) \(\text{pH} = 7.00\) assumes that equal concentrations of the acid and its conjugate base produce a neutral solution; in fact, equal concentrations make the log term zero so the \(\text{pH}\) equals the \(\text{p}K_a\) of the weak acid, which here is acidic at 3.75. (Choice B) \(\text{pH} = 1.00\) comes from taking the negative log of a concentration, e.g. \(-\log(0.15) \approx 0.8\) rounded toward 1, treating the buffer as if \([\text{H}^+]\) equaled a stated concentration rather than applying the Henderson-Hasselbalch relationship. (Choice D) \(\text{pH} = 4.75\) is the result of adding 1 to the \(\text{p}K_a\) (\(3.75 + 1 = 4.75\)), an off-by-one error that would correspond to a tenfold excess of conjugate base over acid (\(\log 10 = 1\)) rather than the equal concentrations given. Skill 2$ex74$,
    'easy', '5A', $cc74$Acid-Base Equilibria (GC, BC)$cc74$, 'general-chemistry', 2, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a74A$Believes equal concentrations of acid and conjugate base give a neutral pH of 7$a74A$ FROM q
UNION ALL SELECT id, 'B', 'process_step_confusion', $a74B$Takes the negative log of a concentration instead of applying Henderson-Hasselbalch$a74B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a74D$Off-by-one: adds 1 to the pKa, treating the equal-concentration log term as log(10) instead of log(1)$a74D$ FROM q;

-- Q17 [Buffers & Henderson-Hasselbalch · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g75)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt75$A 1.00 L buffer initially holds 0.50 mol propionic acid (\(\text{HA}\), \(\text{p}K_a = 4.87\)) and 0.50 mol propionate (\([\text{A}^-]\)). A chemist adds 0.10 mol solid \(\text{NaOH}\), which reacts completely and converts that much \(\text{HA}\) to \(\text{A}^-\) (treat the volume change as negligible). What is the \(\text{pH}\) after the addition?$qt75$,
    $op75$[{"label":"A","text":"\\(\\text{pH} = 4.87\\)"},{"label":"B","text":"\\(\\text{pH} = 4.69\\)"},{"label":"C","text":"\\(\\text{pH} = 5.65\\)"},{"label":"D","text":"\\(\\text{pH} = 5.05\\)"}]$op75$::jsonb,
    'D',
    $ex75$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is D because the added strong base consumes \(\text{HA}\) and generates an equal amount of \(\text{A}^-\), shifting the conjugate ratio and raising the \(\text{pH}\) by \(\log(1.5)\). The strong base \(\text{NaOH}\) reacts essentially to completion: \(\text{HA} + \text{OH}^- \rightarrow \text{A}^- + \text{H}_2\text{O}\). It destroys 0.10 mol \(\text{HA}\) and creates 0.10 mol \(\text{A}^-\), so the new amounts are \(\text{HA} = 0.50 - 0.10 = 0.40\ \text{mol}\) and \([\text{A}^-] = 0.50 + 0.10 = 0.60\ \text{mol}\). Because both species share the same 1.00 L volume, the mole ratio equals the concentration ratio, and the Henderson-Hasselbalch equation gives \(\text{pH} = \text{p}K_a + \log\!\left(\dfrac{[\text{A}^-]}{[\text{HA}]}\right) = 4.87 + \log\!\left(\dfrac{0.60}{0.40}\right) = 4.87 + \log(1.5) = 4.87 + 0.18 = 5.05\). (Choice A) \(4.87\) is the value obtained by leaving the ratio at \(0.50/0.50 = 1\) so that \(\log(1) = 0\); this ignores that the added \(\text{OH}^-\) perturbs the buffer and changes the conjugate-base-to-acid ratio. (Choice B) \(4.69\) comes from inverting the ratio to \(\log(0.40/0.60) = -0.18\), placing the acid in the numerator and the base in the denominator; this reverses the direction of the shift, lowering rather than raising \(\text{pH}\) even though base was added. (Choice C) \(5.65\) results from using the 0.10 mol of added base as the new \(\text{HA}\) amount, giving \(\log(0.60/0.10) = \log(6) = 0.78\); this over-shifts the buffer by assuming nearly all of the acid was consumed instead of only 0.10 mol of the original 0.50 mol. Skill 2$ex75$,
    'hard', '5A', $cc75$Acid-Base Equilibria (GC, BC)$cc75$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a75A$ignores that strong base shifts the conjugate ratio, leaving pH at pKa$a75A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a75B$inverts the [A-]/[HA] ratio, shifting pH the wrong direction$a75B$ FROM q
UNION ALL SELECT id, 'C', 'process_step_confusion', $a75C$uses moles of added base as remaining HA, over-shifting the ratio to log(6)$a75C$ FROM q;

-- Q18 [Buffers & Henderson-Hasselbalch · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans A] (g76)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt76$A 1.00 L buffer contains 0.40 mol \(\text{NH}_3\) and 0.40 mol \(\text{NH}_4^+\), with \(\text{p}K_a(\text{NH}_4^+) = 9.25\). After 0.10 mol \(\text{HCl}\) is added (no volume change), what is the \(\text{pH}\)?$qt76$,
    $op76$[{"label":"A","text":"\\(\\text{pH} = 9.03\\)"},{"label":"B","text":"\\(\\text{pH} = 9.25\\)"},{"label":"C","text":"\\(\\text{pH} = 9.47\\)"},{"label":"D","text":"\\(\\text{pH} = 8.83\\)"}]$op76$::jsonb,
    'A',
    $ex76$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is A because the added strong acid is consumed by the weak base, shifting the buffer ratio toward the conjugate acid. The 0.10 mol \(\text{H}^+\) from \(\text{HCl}\) reacts essentially completely with \(\text{NH}_3\): \(\text{NH}_3 + \text{H}^+ \rightarrow \text{NH}_4^+\). This consumes 0.10 mol \(\text{NH}_3\) and produces 0.10 mol \(\text{NH}_4^+\), giving new amounts \([\text{NH}_3] = 0.40 - 0.10 = 0.30\ \text{mol}\) and \([\text{NH}_4^+] = 0.40 + 0.10 = 0.50\ \text{mol}\). Applying Henderson-Hasselbalch with these new amounts (the 1.00 L volume cancels in the ratio): \(\text{pH} = \text{p}K_a + \log\!\left(\frac{[\text{NH}_3]}{[\text{NH}_4^+]}\right) = 9.25 + \log\!\left(\frac{0.30}{0.50}\right) = 9.25 + \log(0.60) = 9.25 + (-0.22) = 9.03\). The \(\text{pH}\) drops slightly because adding acid increases the conjugate acid relative to the base. (Choice B) \(9.25\) is the result of ignoring the shift entirely and using the initial equal amounts, for which \(\log(0.40/0.40) = \log(1) = 0\); this skips the reaction of \(\text{H}^+\) with \(\text{NH}_3\). (Choice C) \(9.47\) comes from shifting the ratio in the wrong direction—treating the added acid as if it increased \(\text{NH}_3\) and decreased \(\text{NH}_4^+\), giving \(9.25 + \log(0.50/0.30) = 9.25 + 0.22\); adding acid cannot raise the \(\text{pH}\). (Choice D) \(8.83\) results from over-shifting the ratio, applying the \(0.10\ \text{mol}\) conversion twice (or doubling the log term to \(-0.44\)) so that the \(\text{pH}\) falls roughly twice as far as the correct single conversion warrants. Skill 2$ex76$,
    'hard', '5A', $cc76$Acid-Base Equilibria (GC, BC)$cc76$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'B', 'process_step_confusion', $a76B$Omits the neutralization step and uses the initial equal mole amounts, so log(1) = 0 leaves pH at the pKa$a76B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a76C$Shifts the buffer ratio in the wrong direction, raising pH after acid addition instead of lowering it$a76C$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a76D$Over-applies the conversion (doubles the moles shifted or the log term), pushing pH down twice as far as warranted$a76D$ FROM q;

-- Q19 [Buffers & Henderson-Hasselbalch · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans B] (g77)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt77$A researcher must hold a reaction mixture at \(\text{pH} = 7.2\) and intends to prepare the buffer using roughly equal concentrations of a weak acid and its conjugate base. Four candidate weak acids are available, with \(\text{p}K_a\) values of \(3.1\) (acid W), \(4.8\) (acid X), \(7.2\) (acid Y), and \(9.3\) (acid Z). Which conjugate acid/base pair should be chosen to buffer most effectively at the target \(\text{pH}\)?$qt77$,
    $op77$[{"label":"A","text":"Acid W \\((\\text{p}K_a = 3.1)\\) with its conjugate base"},{"label":"B","text":"Acid Y \\((\\text{p}K_a = 7.2)\\) with its conjugate base"},{"label":"C","text":"Acid Z \\((\\text{p}K_a = 9.3)\\) with its conjugate base"},{"label":"D","text":"Acid X \\((\\text{p}K_a = 4.8)\\) with its conjugate base"}]$op77$::jsonb,
    'B',
    $ex77$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is B because a buffer made from roughly equal concentrations of weak acid and conjugate base buffers most effectively when its \(\text{p}K_a\) matches the target \(\text{pH}\). The Henderson-Hasselbalch equation is \(\text{pH} = \text{p}K_a + \log\left(\frac{[\text{A}^-]}{[\text{HA}]}\right)\). When \([\text{A}^-] \approx [\text{HA}]\), the ratio is about \(1\), so \(\log(1) = 0\) and \(\text{pH} \approx \text{p}K_a\). To hit \(\text{pH} = 7.2\) with the acid and base near a \(1{:}1\) ratio, the acid whose \(\text{p}K_a = 7.2\) (acid Y) is required, because that choice sets \(\text{pH} = 7.2 + \log(1) = 7.2\) exactly while staying in the high-capacity region where the buffer resists added acid or base most strongly. (Choice A) Acid W has \(\text{p}K_a = 3.1\); at a near \(1{:}1\) ratio it buffers near \(\text{pH} = 3.1\), and forcing it up to \(\text{pH} = 7.2\) would require \(\log\left(\frac{[\text{A}^-]}{[\text{HA}]}\right) = 4.1\), a ratio over \(10{,}000{:}1\) that lies far outside the effective buffering window and contradicts the stated near-equal concentrations. (Choice C) Acid Z has \(\text{p}K_a = 9.3\), which is 2.1 units above the target; a near \(1{:}1\) mixture buffers near \(\text{pH} = 9.3\), and reaching \(\text{pH} = 7.2\) would need \(\log\left(\frac{[\text{A}^-]}{[\text{HA}]}\right) = -2.1\), again far from the equal-concentration condition. (Choice D) Acid X has \(\text{p}K_a = 4.8\), the second-closest value, but \(4.8\) is still 2.4 units below \(7.2\); choosing it because it is "closer than the extremes" overlooks that only the acid whose \(\text{p}K_a\) equals the target gives \(\text{pH} = \text{p}K_a\) at a \(1{:}1\) ratio. Skill 4$ex77$,
    'medium', '5A', $cc77$Acid-Base Equilibria (GC, BC)$cc77$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'scale_unit_error', $a77A$Picks the most acidic candidate, ignoring how far its pKa sits below the target pH and the impossible base/acid ratio required$a77A$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a77C$Selects a pKa above the target as though a higher pKa buffers a higher pH equally well, ignoring distance from the target$a77C$ FROM q
UNION ALL SELECT id, 'D', 'partial_truth', $a77D$Chooses the second-closest pKa, applying 'closest among the lower values' instead of requiring pKa to equal the target pH$a77D$ FROM q;

-- Q20 [Buffers & Henderson-Hasselbalch · easy · Skill 1 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g78)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt78$A buffer is prepared from equal concentrations of acetic acid \(\text{CH}_3\text{COOH}\) (\(K_a = 1.8 \times 10^{-5}\)) and its conjugate base acetate \(\text{CH}_3\text{COO}^-\). When a small amount of strong base \(\text{NaOH}\) is added, the \(\text{pH}\) rises only slightly. Which interaction keeps the \(\text{pH}\) nearly constant?$qt78$,
    $op78$[{"label":"A","text":"The added \\(\\text{OH}^-\\) is permanently destroyed by the buffer, so the system contains no hydroxide after mixing."},{"label":"B","text":"An acetate buffer contains no acidic species, so the added \\(\\text{OH}^-\\) has nothing to react with and the \\(\\text{pH}\\) is held by the salt alone."},{"label":"C","text":"The added \\(\\text{OH}^-\\) is consumed by the weak acid \\(\\text{CH}_3\\text{COOH}\\), converting a strong base into the much weaker acetate \\(\\text{CH}_3\\text{COO}^-\\), so \\([\\text{H}_3\\text{O}^+]\\) changes only slightly."},{"label":"D","text":"The water solvent neutralizes the added \\(\\text{OH}^-\\) on its own, so the dissolved acetic acid and acetate are not involved."}]$op78$::jsonb,
    'C',
    $ex78$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because a buffer resists \(\text{pH}\) change by having both members of a conjugate pair present, each able to consume an added strong species and convert it into a weak one. When \(\text{NaOH}\) is added, the hydroxide reacts with the weak acid: \(\text{CH}_3\text{COOH} + \text{OH}^- \rightarrow \text{CH}_3\text{COO}^- + \text{H}_2\text{O}\). The strong base \(\text{OH}^-\) is replaced by the weak conjugate base acetate \(\text{CH}_3\text{COO}^-\) (whose \(K_b = K_w/K_a = 1.0\times 10^{-14} / 1.8\times 10^{-5} \approx 5.6 \times 10^{-10}\), far weaker than \(\text{OH}^-\)). Because the \([\text{A}^-]/[\text{HA}]\) ratio shifts only modestly and \(\text{pH} = \text{p}K_a + \log\!\big([\text{A}^-]/[\text{HA}]\big)\) depends on the logarithm of that ratio, \([\text{H}_3\text{O}^+]\) and thus \(\text{pH}\) change only slightly. Were strong acid added instead, the conjugate base acetate would consume the \(\text{H}_3\text{O}^+\) by the analogous reaction, giving the same buffering effect. (Choice A) Neutralization does not "destroy" \(\text{OH}^-\); the hydroxide is converted into \(\text{H}_2\text{O}\) and acetate through a real chemical reaction, and the system retains its conjugate pair in equilibrium rather than ending with no base. (Choice B) An acetate-containing buffer made from acetic acid does contain an acidic species, \(\text{CH}_3\text{COOH}\); it is precisely that weak acid that reacts with the added \(\text{OH}^-\), so it is incorrect to claim nothing reacts. (Choice D) Pure water cannot neutralize an appreciable amount of added strong base while holding \(\text{pH}\) steady; without the weak acid \(\text{CH}_3\text{COOH}\) to consume the \(\text{OH}^-\), the \(\text{pH}\) would rise sharply, which is exactly why an un-buffered solution lacks this resistance. Skill 1$ex78$,
    'easy', '5A', $cc78$Acid-Base Equilibria (GC, BC)$cc78$, 'general-chemistry', 1, 75
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a78A$Believing neutralization annihilates the added ion rather than converting it into water plus the conjugate-pair member$a78A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a78B$Thinking a buffer named for its conjugate base contains no weak acid, so nothing can react with added base$a78B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a78D$Attributing the neutralization to the solvent (water) instead of to the weak-acid buffer component$a78D$ FROM q;

-- Q21 [Buffers & Henderson-Hasselbalch · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans D] (g79)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt79$A biochemist needs to prepare a buffer with a target \(\text{pH} = 5.04\) using a weak acid that has \(\text{p}K_a = 4.74\) and its conjugate base. Using the Henderson–Hasselbalch equation, what approximate ratio of conjugate base to weak acid, \([\text{A}^-]/[\text{HA}]\), must the biochemist establish in the solution?$qt79$,
    $op79$[{"label":"A","text":"\\([\\text{A}^-]/[\\text{HA}] \\approx 10\\) (about \\(10:1\\))"},{"label":"B","text":"\\([\\text{A}^-]/[\\text{HA}] \\approx 1.0\\) (about \\(1:1\\))"},{"label":"C","text":"\\([\\text{A}^-]/[\\text{HA}] \\approx 0.5\\) (about \\(1:2\\))"},{"label":"D","text":"\\([\\text{A}^-]/[\\text{HA}] \\approx 2.0\\) (about \\(2:1\\))"}]$op79$::jsonb,
    'D',
    $ex79$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The Henderson–Hasselbalch equation states that \(\text{pH} = \text{p}K_a + \log\!\left(\frac{[\text{A}^-]}{[\text{HA}]}\right)\). Rearranging to solve for the ratio gives \(\log\!\left(\frac{[\text{A}^-]}{[\text{HA}]}\right) = \text{pH} - \text{p}K_a\), so \(\frac{[\text{A}^-]}{[\text{HA}]} = 10^{(\text{pH} - \text{p}K_a)}\). The answer to this question is D because \(\text{pH} - \text{p}K_a = 5.04 - 4.74 = 0.30\), and \(10^{0.30} \approx 2.0\); the conjugate base must be present at roughly twice the concentration of the weak acid (about \(2:1\)) to push the pH 0.30 unit above the \(\text{p}K_a\). (Choice A) A ratio of \(10\) corresponds to \(10^{1}\), which would require the pH to lie a full unit (1.00) above the \(\text{p}K_a\), not the 0.30 unit that the actual target pH demands. (Choice B) A \(1:1\) ratio gives \(\log(1) = 0\), so the pH would equal the \(\text{p}K_a\) of 4.74; this choice ignores the required \(+0.30\) offset between the target pH and the \(\text{p}K_a\). (Choice C) A ratio of \(0.5\) corresponds to \(10^{-0.30}\), which would arise from computing \(\text{p}K_a - \text{pH}\) instead of \(\text{pH} - \text{p}K_a\), inverting the ratio and yielding a pH below the \(\text{p}K_a\) rather than above it. Skill 4$ex79$,
    'medium', '5A', $cc79$Acid-Base Equilibria (GC, BC)$cc79$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'process_step_confusion', $a79A$mis-reads the exponent as 1 instead of 0.30, using 10^1$a79A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a79B$assumes target pH must equal pKa, ignoring the log-ratio offset$a79B$ FROM q
UNION ALL SELECT id, 'C', 'reversed_relationship', $a79C$inverts the ratio by subtracting pH from pKa in the wrong order$a79C$ FROM q;

-- Q22 [Buffers & Henderson-Hasselbalch · medium · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g80)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt80$Two acetate buffers are prepared so that each is exactly equimolar in \(\text{CH}_3\text{COOH}\) and \(\text{CH}_3\text{COO}^-\) (a \(1:1\) conjugate ratio), and both therefore start at the same \(\text{pH}\) equal to the \(\text{p}K_a\) of \(4.74\). Buffer X is \(0.50\,\text{M}\) in each member of the pair, while Buffer Y is \(0.050\,\text{M}\) in each. The same small amount of strong acid (well below the moles of conjugate base in either solution) is added to each buffer. Which buffer undergoes the smaller change in \(\text{pH}\), and why?$qt80$,
    $op80$[{"label":"A","text":"Neither; both change by the same amount, because they share the same \\(\\text{p}K_a\\), the same \\(1:1\\) ratio, and therefore the same starting \\(\\text{pH}\\)."},{"label":"B","text":"Buffer Y, because its lower concentration of the conjugate pair makes the solution more reactive and therefore more sensitive in neutralizing the added acid."},{"label":"C","text":"Buffer X, because its higher total concentration of the conjugate pair gives it a larger reserve to neutralize the added acid before the conjugate ratio shifts appreciably."},{"label":"D","text":"Buffer X, but only if its \\(\\text{p}K_a\\) is higher than that of Buffer Y, since a larger \\(\\text{p}K_a\\) is what sets the greater resistance to the added acid."}]$op80$::jsonb,
    'C',
    $ex80$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because buffer capacity—the amount of added acid or base a buffer can absorb before its \(\text{pH}\) shifts substantially—increases with the total concentration of the conjugate acid-base pair. Both buffers begin at the same \(\text{pH}\) of \(4.74\) because the Henderson-Hasselbalch relation \(\text{pH} = \text{p}K_a + \log([\text{A}^-]/[\text{HA}])\) depends only on the \(\text{p}K_a\) and the ratio, both of which are identical here. When the same small number of moles of strong acid is added, it converts the same number of moles of \(\text{CH}_3\text{COO}^-\) to \(\text{CH}_3\text{COOH}\) in each beaker. In Buffer X, that fixed change is a much smaller fraction of the large \(0.50\,\text{M}\) reserves, so the \([\text{A}^-]/[\text{HA}]\) ratio barely moves and the \(\text{pH}\) changes very little. In Buffer Y, the identical change is a much larger fraction of the small \(0.050\,\text{M}\) amounts, so the ratio—and hence the \(\text{pH}\)—shifts more. The concentrated Buffer X therefore has the greater buffer capacity and undergoes the smaller \(\text{pH}\) change. (Choice A) is wrong because it confuses the factors that set the starting \(\text{pH}\) (the \(\text{p}K_a\) and the conjugate ratio) with the factor that sets buffer capacity (the absolute concentrations); two buffers can share an identical \(\text{pH}\) yet have very different capacities. (Choice B) is wrong because it reverses the actual relationship: a more dilute buffer holds fewer moles of conjugate base to consume the incoming \(\text{H}^+\), so it is overwhelmed sooner and its \(\text{pH}\) shifts more, not less; "more reactive" is not a meaningful basis for capacity. (Choice D) is wrong because the \(\text{p}K_a\) values are stated to be identical—both are acetate buffers—so \(\text{p}K_a\) cannot be the discriminating factor; capacity here is governed by concentration alone, not by any difference in \(\text{p}K_a\). Skill 2$ex80$,
    'medium', '5A', $cc80$Acid-Base Equilibria (GC, BC)$cc80$, 'general-chemistry', 2, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a80A$conflates equal starting pH (same pKa and ratio) with equal buffer capacity$a80A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a80B$believes lower concentration makes a buffer more reactive/sensitive and thus more resistant$a80B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a80D$attributes capacity to pKa difference when pKa is identical and concentration is the real variable$a80D$ FROM q;

-- Q23 [Buffers & Henderson-Hasselbalch · hard · Skill 2 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g81)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt81$A lactic-acid/lactate buffer is prepared so that \([\text{lactate}] = 0.080\ \text{M}\) and \([\text{lactic acid}] = 0.020\ \text{M}\), where lactic acid has \(\text{p}K_a = 3.86\). What is the \(\text{pH}\) of this buffer?$qt81$,
    $op81$[{"label":"A","text":"\\(\\text{pH} = 3.86\\)"},{"label":"B","text":"\\(\\text{pH} = 3.26\\)"},{"label":"C","text":"\\(\\text{pH} = 4.46\\)"},{"label":"D","text":"\\(\\text{pH} = 4.86\\)"}]$op81$::jsonb,
    'C',
    $ex81$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the Henderson-Hasselbalch equation, \(\text{pH} = \text{p}K_a + \log\frac{[\text{A}^-]}{[\text{HA}]}\), accounts for the excess of conjugate base over weak acid. Substituting the given values, \(\text{pH} = 3.86 + \log\frac{0.080}{0.020} = 3.86 + \log(4)\). Since \(\log(4) = 0.60\), the result is \(\text{pH} = 3.86 + 0.60 = 4.46\). Because the conjugate base lactate outnumbers the acid 4-to-1, the buffer sits above its \(\text{p}K_a\), consistent with a solution that is more basic than the point of equal concentrations. (Choice A) \(\text{pH} = 3.86\) ignores the concentration ratio entirely, treating the \(\log\) term as zero; this is only correct when \([\text{A}^-] = [\text{HA}]\), which is not the case here. (Choice B) \(\text{pH} = 3.26\) inverts the ratio, computing \(3.86 + \log\frac{0.020}{0.080} = 3.86 + \log(0.25) = 3.86 - 0.60\); placing the acid over the base wrongly drives the \(\text{pH}\) below the \(\text{p}K_a\). (Choice D) \(\text{pH} = 4.86\) takes \(\log\) of the wrong number, using \(\log(10) = 1\) so that \(3.86 + 1.00 = 4.86\); the true ratio is \(4\), not \(10\), so the \(\log\) term is \(0.60\), not \(1.00\). Skill 2$ex81$,
    'hard', '5A', $cc81$Acid-Base Equilibria (GC, BC)$cc81$, 'general-chemistry', 2, 160
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a81A$Ignores the concentration ratio and equates pH to pKa, assuming the log term is always zero$a81A$ FROM q
UNION ALL SELECT id, 'B', 'reversed_relationship', $a81B$Inverts the base/acid ratio in the log term, putting acid over conjugate base$a81B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a81D$Uses log(10)=1 instead of log(4)=0.60, miscomputing the logarithm of the ratio$a81D$ FROM q;

-- Q24 [Buffers & Henderson-Hasselbalch · medium · Skill 4 · 5A Acid-Base Equilibria (GC, BC) · general-chemistry · ans C] (g82)
WITH q AS (
  INSERT INTO questions (section, topic, subtopic, question_text, options, correct_answer, explanation, difficulty, foundation, content_category, discipline, cognitive_skill, estimated_time_seconds)
  VALUES (
    'chem_phys', 'Acids & Bases', 'Buffers & Henderson-Hasselbalch',
    $qt82$A chemist prepares an acetate buffer in which \([\text{CH}_3\text{COOH}]\) and \([\text{CH}_3\text{COO}^-]\) are present in equal concentration. The chemist then transfers the buffer to a larger flask and adds pure water until the total volume is ten times its original value, diluting the solution tenfold. Assuming the temperature is held constant and that activity effects are negligible, what happens to the \(\text{pH}\) of the buffer, and why?$qt82$,
    $op82$[{"label":"A","text":"The \\(\\text{pH}\\) change cannot be predicted without knowing the absolute concentrations of \\(\\text{CH}_3\\text{COOH}\\) and \\(\\text{CH}_3\\text{COO}^-\\), not merely their ratio."},{"label":"B","text":"The \\(\\text{pH}\\) rises toward 7, because diluting any aqueous solution with water moves it closer to the neutral value."},{"label":"C","text":"The \\(\\text{pH}\\) stays essentially unchanged, because the Henderson–Hasselbalch \\(\\text{pH}\\) depends on the ratio \\([\\text{A}^-]/[\\text{HA}]\\), and dilution lowers both concentrations by the same factor, leaving that ratio unchanged."},{"label":"D","text":"The \\(\\text{pH}\\) rises by about 1 unit, because a tenfold dilution lowers the hydrogen-ion concentration by a factor of ten, just as it does for a strong acid."}]$op82$::jsonb,
    'C',
    $ex82$This is a General Chemistry question that falls under the content category 'Acid-Base Equilibria (GC, BC)'. The answer to this question is C because the pH of a buffer is governed by the Henderson–Hasselbalch relation \(\text{pH} = \text{p}K_a + \log\frac{[\text{A}^-]}{[\text{HA}]}\), which depends only on the RATIO of conjugate base to weak acid, not on their absolute concentrations. Adding water dilutes both \(\text{CH}_3\text{COOH}\) and \(\text{CH}_3\text{COO}^-\) by the identical factor of ten, so the ratio \([\text{A}^-]/[\text{HA}]\) is preserved (here it stays at 1), the logarithm stays at 0, and the pH remains equal to \(\text{p}K_a\). Hence the pH is essentially unchanged by dilution. (Choice A) The Henderson–Hasselbalch pH depends only on the ratio \([\text{A}^-]/[\text{HA}]\), which here is fixed at 1:1 and is unchanged by dilution; the absolute concentrations are not needed to conclude that the pH stays essentially constant, so claiming the change is unpredictable without them is incorrect. (Choice B) The notion that any dilution drives a solution toward neutral pH 7 is a misconception; it holds only as a limiting tendency for extreme dilution of dilute non-buffered solutions, and a buffer specifically resists this because its conjugate ratio, not its absolute concentration, fixes the pH. (Choice D) A strong, fully ionized acid does have its pH rise by about one unit per tenfold dilution, because its \([\text{H}_3\text{O}^+]\) falls in step with its concentration, but a buffer is not a strong acid; equating the two confuses the strong-acid concentration dependence with the buffer's ratio dependence, so the predicted one-unit shift does not occur. Skill 4$ex82$,
    'medium', '5A', $cc82$Acid-Base Equilibria (GC, BC)$cc82$, 'general-chemistry', 4, 110
  ) RETURNING id
)
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype)
SELECT id, 'A', 'misconception', $a82A$thinks absolute concentrations, not just the [A-]/[HA] ratio, set a buffer’s pH$a82A$ FROM q
UNION ALL SELECT id, 'B', 'misconception', $a82B$dilution drives all solutions toward neutral pH 7$a82B$ FROM q
UNION ALL SELECT id, 'D', 'process_step_confusion', $a82D$applies the strong-acid one-pH-unit-per-tenfold-dilution rule to a buffer$a82D$ FROM q;

COMMIT;
SELECT COUNT(*) AS batch3_questions FROM questions WHERE topic='Acids & Bases' AND subtopic IN ('Titration & Titration Curves', 'Buffers & Henderson-Hasselbalch');
