-- GenChem "Atomic Structure" — HARD-question difficulty re-engineering (Praxist-Hard recalibration)
-- Updates 18 hard questions IN PLACE by id (question ids preserved, so any student answer-history stays intact).
-- Each was re-engineered to genuine Praxist Hard (2-3 concept synthesis / multi-step quantitative / controlling-constraint; ~120-180s; Skill 3-4),
-- adversarially verified (every value recomputed), kept on the same subtopic + answer-letter, and deduped (internal + cross-chapter).
-- Re-runnable. Run this file in the Supabase SQL editor.
BEGIN;

-- 1. [Electron Configurations · Skill 2 · ans D] id 83ed3339-fb76-4506-94cc-282549b8f14d
UPDATE questions SET
  question_text = $qt$A spectroscopist places a gaseous sample of \(\text{Cr}^+\) ions in a magnetic field and models the paramagnetism using the spin-only relation \(\mu = \sqrt{n(n+2)}\) (in Bohr magnetons), where \(n\) is the number of unpaired electrons in the ground-state ion. Neutral chromium is known to adopt the anomalous \([\text{Ar}]4s^1 3d^5\) configuration. Assuming each ion is in its ground state, the measured spin-only moment should fall closest to which value?$qt$,
  options = $op$[{"label":"A","text":"\\(4.90\\) BM, corresponding to \\(4\\) unpaired electrons"},{"label":"B","text":"\\(6.93\\) BM, corresponding to \\(6\\) unpaired electrons"},{"label":"C","text":"\\(3.87\\) BM, corresponding to \\(3\\) unpaired electrons"},{"label":"D","text":"\\(5.92\\) BM, corresponding to \\(5\\) unpaired electrons"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the result must be built in three chained steps. First, neutral chromium is given as the anomalous \([\text{Ar}]4s^1 3d^5\), where the lone \(4s\) electron and the five \(3d\) electrons each occupy a separate orbital, giving \(6\) unpaired electrons. Second, forming \(\text{Cr}^+\) removes exactly one electron, and for transition metals the \(4s\) electron is lost before any \(3d\) electron (once the \(3d\) orbitals are populated they drop below \(4s\) in energy); this empties the \(4s\) and leaves \([\text{Ar}]3d^5\). Third, the half-filled \(3d^5\) set carries five singly occupied orbitals by Hund's rule, so \(n = 5\). Substituting into \(\mu = \sqrt{n(n+2)} = \sqrt{5(7)} = \sqrt{35} \approx 5.92\) BM, so C is correct. (Choice A) \(4.90\ \text{BM} = \sqrt{4(6)}\) arises from \(n = 4\), i.e. the \([\text{Ar}]3d^4\) configuration. That configuration belongs to \(\text{Cr}^{2+}\), formed by removing two electrons; for a \(+1\) ion only one electron leaves, so this overcounts the charge by one electron and depletes the \(3d^5\) set by one. (Choice B) \(6.93\ \text{BM} = \sqrt{6(8)}\) arises from \(n = 6\), the unpaired count of the neutral \([\text{Ar}]4s^1 3d^5\) atom itself. This value omits the ionization step entirely and reports the moment of the atom rather than the \(\text{Cr}^+\) cation. (Choice C) \(3.87\ \text{BM} = \sqrt{3(5)}\) arises from \(n = 3\), the \([\text{Ar}]4s^2 3d^3\) configuration. This follows the mistaken view that the \(4s\) shell re-pairs to \(4s^2\) upon ionization while a \(3d\) electron is removed; in fact the \(4s\) is preferentially emptied, not filled, so the paired-\(4s\) picture inverts the true ionization order. This is a Scientific Reasoning and Problem Solving question because you must identify the controlling exception, apply the \(4s\)-before-\(3d\) ionization rule, translate the resulting configuration into an unpaired-electron count, and carry that intermediate value through the spin-only formula to a final number.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '83ed3339-fb76-4506-94cc-282549b8f14d';
DELETE FROM question_distractor_metadata WHERE question_id = '83ed3339-fb76-4506-94cc-282549b8f14d';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('83ed3339-fb76-4506-94cc-282549b8f14d', 'A', 'scale_unit_error', $a$Charge overcount: computes Cr2+ ([Ar]3d^4, n=4) instead of Cr+ by removing two electrons for a +1 ion$a$),
  ('83ed3339-fb76-4506-94cc-282549b8f14d', 'B', 'process_step_confusion', $a$Dropped the ionization step: reports the neutral Cr atom's 6 unpaired electrons instead of ionizing to Cr+$a$),
  ('83ed3339-fb76-4506-94cc-282549b8f14d', 'C', 'misconception', $a$Reversed ionization order: assumes 4s re-pairs to 4s^2 and a 3d electron is removed, giving [Ar]4s^2 3d^3 (n=3)$a$);

-- 2. [Isotopes & Atomic Weight · Skill 2 · ans C] id 8c69675a-fb5a-40b1-9c0d-bfd57f381b87
UPDATE questions SET
  question_text = $qt$A mass-spectrometry lab logs two monatomic ions on one calibration sheet. The first is written in full as \(^{80}_{34}\text{Se}^{2-}\). The second ion is a doubly charged cation that is isoelectronic with the first ion and whose nuclide carries a mass number of \(88\). For that second ion as it must be recorded, how many neutrons does it most likely contain?$qt$,
  options = $op$[{"label":"A","text":"42 neutrons"},{"label":"B","text":"52 neutrons"},{"label":"C","text":"50 neutrons"},{"label":"D","text":"54 neutrons"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is C because the neutron count cannot be read directly; it must be reached by chaining three steps. First, fix the electron count of the first ion: \(^{80}_{34}\text{Se}^{2-}\) has \(Z = 34\) protons and a \(2-\) charge, so electrons \(= Z - (\text{charge}) = 34 - (-2) = 36\). Second, apply the isoelectronic constraint: the second ion has the same \(36\) electrons. Because that ion is a \(2+\) cation, its electron count relates to its atomic number by \(\text{electrons} = Z - (\text{charge})\), giving \(36 = Z - (+2)\), so \(Z = 38\); the element with \(Z = 38\) is strontium. Third, use the given mass number of the second ion, \(A = 88\): neutrons \(= A - Z = 88 - 38 = 50\). So \(^{88}_{38}\text{Sr}^{2+}\) carries \(50\) neutrons. (Choice A) 42 results from correctly identifying strontium (\(Z = 38\)) but then subtracting \(Z\) from the first ion's mass number, \(80 - 38 = 42\), instead of from the second ion's own mass number of \(88\); the neutron count must use each ion's own \(A\). (Choice B) 52 results from ignoring the \(2-\) charge on the first ion, treating selenium as neutral with only \(34\) electrons; that would force the second ion to have \(34\) electrons, giving \(Z = 34 + 2 = 36\) and \(88 - 36 = 52\), but the anion charge adds two electrons, raising the isoelectronic target to \(36\). (Choice D) 54 results from mishandling the cation charge sign when back-calculating \(Z\), using \(Z = 36 - 2 = 34\) rather than \(36 + 2 = 38\); a cation has fewer electrons than protons, so the charge must be added to the electron count to recover \(Z\), yielding \(38\) and \(88 - 38 = 50\). This is a Scientific Reasoning and Problem Solving question because you must integrate charge-to-electron bookkeeping, the isoelectronic constraint, and the mass-number relation, carrying each intermediate result into the next step to reach the neutron count.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '8c69675a-fb5a-40b1-9c0d-bfd57f381b87';
DELETE FROM question_distractor_metadata WHERE question_id = '8c69675a-fb5a-40b1-9c0d-bfd57f381b87';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8c69675a-fb5a-40b1-9c0d-bfd57f381b87', 'A', 'process_step_confusion', $a$Identifies the correct element (Sr, Z=38) but subtracts Z from the wrong ion's mass number, using the first ion's A=80 instead of the second ion's A=88, giving 80-38=42.$a$),
  ('8c69675a-fb5a-40b1-9c0d-bfd57f381b87', 'B', 'misconception', $a$Drops the 2- charge on the first ion, treating Se as neutral with 36 electrons reduced to 34, which sets the isoelectronic target to 34 and yields Z=36 and 88-36=52.$a$),
  ('8c69675a-fb5a-40b1-9c0d-bfd57f381b87', 'D', 'reversed_relationship', $a$Reverses the cation charge sign when recovering Z from the electron count, computing Z=36-2=34 instead of 36+2=38, giving 88-34=54.$a$);

-- 3. [Isotopes & Atomic Weight · Skill 4 · ans D] id ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9
UPDATE questions SET
  question_text = $qt$A newly characterized element exists as exactly two stable isotopes, of masses \(120.90\ \text{u}\) (lighter) and \(122.90\ \text{u}\) (heavier), and its standard atomic weight is reported as \(121.70\ \text{u}\). A chemist isolates a sample containing exactly \(1.000\ \text{mol}\) of this element. Of the total mass of that sample, the portion contributed by the heavier isotope alone is most nearly$qt$,
  options = $op$[{"label":"A","text":"\\(73.74\\ \\text{g}\\)"},{"label":"B","text":"\\(48.36\\ \\text{g}\\)"},{"label":"C","text":"\\(61.45\\ \\text{g}\\)"},{"label":"D","text":"\\(49.16\\ \\text{g}\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the standard atomic weight is the abundance-weighted average of the isotope masses, and that relationship must first be inverted to recover the unknown abundances before the heavy-isotope mass can be found. Letting \(x_\text{L}\) be the fractional abundance of the lighter isotope, \(121.70 = (120.90)x_\text{L} + (122.90)(1 - x_\text{L})\). Solving, \(x_\text{L} = \frac{122.90 - 121.70}{122.90 - 120.90} = \frac{1.20}{2.00} = 0.600\), so the heavier isotope has abundance \(x_\text{H} = 1 - 0.600 = 0.400\). In a \(1.000\ \text{mol}\) sample, \(0.400\ \text{mol}\) is the heavier isotope, and its mass contribution is \((0.400\ \text{mol})(122.90\ \text{g/mol}) = 49.16\ \text{g}\). The intermediate abundance must be paired with the correct (heavier) isotope mass to finish. (Choice A) \(73.74\ \text{g}\) comes from reversing the abundance assignments and giving the heavier isotope the \(0.600\) fraction that belongs to the lighter one, \((0.600)(122.90)\); since the weighted average sits nearer the lighter mass, the heavier isotope must be the minority species, not the majority. (Choice B) \(48.36\ \text{g}\) uses the correct heavy-isotope abundance of \(0.400\) but multiplies it by the lighter isotope's mass, \((0.400)(120.90)\), pairing the right fraction with the wrong mass and slightly underestimating the contribution. (Choice C) \(61.45\ \text{g}\) results from skipping the inversion and assuming the two isotopes are equally abundant, \((0.500)(122.90)\); this ignores that the reported atomic weight of \(121.70\ \text{u}\) lies closer to the lighter mass, which requires the lighter isotope to dominate rather than a \(50/50\) split. This is a Data-Based and Statistical Reasoning question because you must invert the abundance-weighted average to extract an intermediate quantity and then carry that quantity into a second mass calculation paired with the correct isotope.$ex$,
  cognitive_skill = 4,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = 'ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9';
DELETE FROM question_distractor_metadata WHERE question_id = 'ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9', 'A', 'reversed_relationship', $a$Reverses the abundance assignment, giving the heavier isotope the lighter isotope's 0.600 majority fraction$a$),
  ('ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9', 'B', 'process_step_confusion', $a$Correct back-solved heavy abundance (0.400) paired with the lighter isotope mass instead of the heavier one$a$),
  ('ce0ce5e9-ca57-4b9b-a16f-0957aba8f6a9', 'C', 'misconception', $a$Skips the inversion and assumes equal 50/50 abundance, ignoring that the atomic weight lies closer to the lighter mass$a$);

-- 4. [Isotopes & Atomic Weight · Skill 2 · ans D] id d31063ad-66a4-4020-9422-89b76fb1a987
UPDATE questions SET
  question_text = $qt$A magnetic-sector mass spectrometer accelerates ions through a fixed potential difference \( V \) into a uniform field, where each ion follows a semicircular path of radius \( r = \frac{1}{B}\sqrt{\frac{2Vm}{q}} \) to a detector fixed at one radial position. With \( V \) and the detector position held constant, a \( ^{90}\text{Zr}^{+} \) ion is in focus at \( B = 0.480\ \text{T} \). The analyst now needs to bring the heavier \( ^{96}\text{Zr}^{2+} \) ion into focus at that same detector. The field should most likely be reset to which value?$qt$,
  options = $op$[{"label":"A","text":"\\( 0.657\\ \\text{T} \\), because the lighter \\( m/q \\) of \\( 48 \\) demands a stronger field, so \\( B \\) scales up as \\( \\sqrt{90/48} \\)."},{"label":"B","text":"\\( 0.496\\ \\text{T} \\), because the more massive \\( ^{96}\\text{Zr} \\) ion requires a stronger field, so \\( B \\) scales up as \\( \\sqrt{96/90} \\)."},{"label":"C","text":"\\( 0.256\\ \\text{T} \\), because the focused \\( m/q \\) drops from \\( 90 \\) to \\( 48 \\), so \\( B \\) falls in direct proportion to that ratio."},{"label":"D","text":"\\( 0.351\\ \\text{T} \\), because at fixed \\( V \\) and \\( r \\) the field scales as \\( B \\propto \\sqrt{m/q} \\), and \\( ^{96}\\text{Zr}^{2+} \\) has the smaller \\( m/q \\) of \\( 48 \\) versus \\( 90 \\)."}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the detector selects ions by mass-to-charge ratio, not by mass alone. Solving \( r = \frac{1}{B}\sqrt{\frac{2Vm}{q}} \) for the focused ratio gives \( \frac{m}{q} = \frac{B^2 r^2}{2V} \), so with \( V \), \( r \), and the detector position fixed, \( B \propto \sqrt{m/q} \). The controlling constraint is the charge: \( ^{90}\text{Zr}^{+} \) presents \( m/q = 90/1 = 90 \), but the target \( ^{96}\text{Zr}^{2+} \) presents \( m/q = 96/2 = 48 \) — a smaller ratio despite the larger mass. Scaling the field by \( \sqrt{48/90} \) gives \( B = 0.480\ \text{T} \times \sqrt{48/90} = 0.480 \times 0.730 = 0.351\ \text{T} \), a lower field. (Choice A) This inverts the dependence, reasoning that a smaller \( m/q \) needs a larger \( B \); since \( B \propto \sqrt{m/q} \), a smaller ratio requires a smaller field, so applying \( \sqrt{90/48} \) drives \( B \) the wrong direction to \( 0.657\ \text{T} \). (Choice B) This treats the second ion as singly charged \( ^{96}\text{Zr}^{+} \) and applies \( \sqrt{96/90} \); it captures the correct \( B \propto \sqrt{m/q} \) form but drops the \( 2+ \) charge, so it raises \( B \) to \( 0.496\ \text{T} \) when the doubling of \( q \) actually lowers \( m/q \) and the field. (Choice C) This uses the correct \( m/q \) values of \( 48 \) and \( 90 \) but scales \( B \) linearly with the ratio rather than with its square root; because \( m/q \propto B^2 \), the field must change by \( \sqrt{48/90} \), not \( 48/90 \), so \( 0.256\ \text{T} \) overshoots the reduction. This is a Scientific Reasoning and Problem Solving question because you must chain the isotope-and-charge identification to the correct \( m/q \) values, recognize that charge state governs the discriminator, and carry the squared-field relationship through a multi-step calculation to the correct magnitude and direction.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = 'd31063ad-66a4-4020-9422-89b76fb1a987';
DELETE FROM question_distractor_metadata WHERE question_id = 'd31063ad-66a4-4020-9422-89b76fb1a987';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d31063ad-66a4-4020-9422-89b76fb1a987', 'A', 'reversed_relationship', $a$Inverts the B-versus-m/q dependence, concluding a smaller m/q needs a larger field and scaling up by sqrt(90/48)$a$),
  ('d31063ad-66a4-4020-9422-89b76fb1a987', 'B', 'process_step_confusion', $a$Drops the 2+ charge state and treats the target as singly charged, computing B from the mass-number ratio sqrt(96/90) and raising the field$a$),
  ('d31063ad-66a4-4020-9422-89b76fb1a987', 'C', 'scale_unit_error', $a$Uses the correct m/q values 48 and 90 but scales B linearly with m/q instead of with its square root, forgetting that m/q is proportional to B^2$a$);

-- 5. [Periodic Trends · Skill 2 · ans D] id 078c3cf4-57dd-405f-a461-2b9577dd1d44
UPDATE questions SET
  question_text = $qt$A chemist needs the species with the largest radius from a set that mixes neutral atoms with monatomic ions: a neutral potassium atom \( \text{K} \), the calcium ion \( \text{Ca}^{2+} \), the chloride ion \( \text{Cl}^- \), and a neutral sulfur atom \( \text{S} \). Reasoning only from each species' position on the periodic table and how forming the ion changes its outermost occupied shell, which species will most likely have the largest radius?$qt$,
  options = $op$[{"label":"A","text":"\\( \\text{S} \\), because it lies one column to the left of chlorine in period 3, the direction of decreasing effective nuclear charge and increasing radius"},{"label":"B","text":"\\( \\text{Ca}^{2+} \\), because calcium lies in period 4 and a period-4 species sits lower on the table than any period-3 atom or ion in the set"},{"label":"C","text":"\\( \\text{Cl}^- \\), because adding an electron to chlorine increases electron-electron repulsion, making the anion larger than every neutral atom listed"},{"label":"D","text":"\\( \\text{K} \\), because its valence electron occupies the highest principal level present \\( (n = 4) \\) while group-1 placement gives it the lowest effective nuclear charge, so no shell-altering ionization shrinks it"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the largest radius is set by the highest principal quantum number \(n\) of the outermost occupied shell combined with the lowest effective nuclear charge \(Z_\text{eff}\), and one must track how ion formation changes the outermost shell. Step 1: neutral \(\text{K}\) is \([\text{Ar}]4s^1\), so its valence electron sits in the \(n = 4\) shell, the highest \(n\) of any species here, and its group-1 position gives it the lowest \(Z_\text{eff}\); it is the largest at \(227\ \text{pm}\). Step 2: \(\text{Ca}^{2+}\) comes from a period-4 element, but losing both \(4s\) electrons strips away the entire \(n = 4\) shell, leaving an \([\text{Ar}]\) core whose outermost shell is now \(n = 3\) held by \(Z = 20\); its radius collapses to about \(100\ \text{pm}\). Step 3: \(\text{Cl}^-\) is \([\text{Ar}]\) with an \(n = 3\) outer shell; the added electron does expand it relative to neutral \(\text{Cl}\) (\(99 \rightarrow 181\ \text{pm}\)), but it still cannot exceed an \(n = 4\) valence shell. Step 4: neutral \(\text{S}\) keeps an \(n = 3\) shell at about \(104\ \text{pm}\). Chaining position, charge, and shell occupancy gives \(\text{K} > \text{Cl}^- > \text{S} > \text{Ca}^{2+}\), so \(\text{K}\) is largest. (Choice A) Sulfur does lie left of chlorine and thus exceeds neutral chlorine in size, but it occupies the \(n = 3\) row, and moving down to the \(n = 4\) shell of potassium outweighs any horizontal gain within period 3. (Choice B) This applies the period-number heuristic without tracking the ion's outermost shell: removing the two \(4s\) electrons from calcium eliminates the \(n = 4\) shell entirely, so \(\text{Ca}^{2+}\) actually has an \(n = 3\) valence shell and is the smallest species listed, not the largest. (Choice C) Anion formation does enlarge chlorine relative to its neutral atom, but the comparison that matters is against a neutral atom whose valence shell is \(n = 4\); \(\text{Cl}^-\) remains an \(n = 3\) species and is smaller than \(\text{K}\). This is a Scientific Reasoning and Problem Solving question because you must integrate the down-group and across-period radius trends with the shell-altering consequences of cation versus anion formation to identify which species retains the highest-\(n\), lowest-\(Z_\text{eff}\) valence shell.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '078c3cf4-57dd-405f-a461-2b9577dd1d44';
DELETE FROM question_distractor_metadata WHERE question_id = '078c3cf4-57dd-405f-a461-2b9577dd1d44';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('078c3cf4-57dd-405f-a461-2b9577dd1d44', 'A', 'process_step_confusion', $a$Uses only the across-period (horizontal) decrease in Z_eff and neglects the dominant down-group increase in principal quantum number that makes the n=4 species larger$a$),
  ('078c3cf4-57dd-405f-a461-2b9577dd1d44', 'B', 'misconception', $a$Applies the 'lower period number means larger' heuristic to a cation without recognizing that removing the valence electrons strips the entire outermost (n=4) shell, dropping the ion to an n=3 core$a$),
  ('078c3cf4-57dd-405f-a461-2b9577dd1d44', 'C', 'partial_truth', $a$Correctly recalls that an anion is larger than its parent neutral atom but stops there, failing to compare the n=3 anion against a much larger neutral atom whose valence shell is n=4$a$);

-- 6. [Periodic Trends · Skill 2 · ans C] id 24148f17-4a09-4665-a041-6490640cc18a
UPDATE questions SET
  question_text = $qt$A neutral sulfur atom (\(Z = 16\)) is in its electronic ground state. Using Slater's rules to estimate the effective nuclear charge \(Z_\text{eff} = Z - S\) felt by one of its \(3p\) valence electrons, each other electron in the same \((3s,3p)\) group contributes \(0.35\) to the screening constant \(S\), each electron in the \(n = 2\) shell contributes \(0.85\), and each \(1s\) electron contributes \(1.00\). The \(Z_\text{eff}\) experienced by that \(3p\) electron is most nearly which value?$qt$,
  options = $op$[{"label":"A","text":"\\(5.10\\)"},{"label":"B","text":"\\(6.00\\)"},{"label":"C","text":"\\(5.45\\)"},{"label":"D","text":"\\(4.25\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is C because Slater's rules require partitioning the remaining electrons into screening groups and applying a different coefficient to each. For a \(3p\) electron in sulfur (\(1s^2\,2s^2\,2p^6\,3s^2\,3p^4\)), the \((3s,3p)\) group holds \(6\) electrons, but the electron under consideration is excluded, leaving \(5\) same-group electrons that each screen \(0.35\): \(5 \times 0.35 = 1.75\). The \(n = 2\) shell holds \(8\) electrons that each screen \(0.85\): \(8 \times 0.85 = 6.80\). The two \(1s\) electrons each screen \(1.00\): \(2 \times 1.00 = 2.00\). Summing gives \(S = 1.75 + 6.80 + 2.00 = 10.55\), so \(Z_\text{eff} = 16 - 10.55 = 5.45\). (Choice A) A value of \(5.10\) arises from counting all \(6\) electrons of the \((3s,3p)\) group at \(0.35\) (\(6 \times 0.35 = 2.10\)) instead of excluding the electron whose \(Z_\text{eff}\) is being computed, which inflates \(S\) to \(10.90\). (Choice B) A value of \(6.00\) results from the simplified shortcut \(Z_\text{eff} = Z - (\text{core electrons})\), treating all \(10\) inner electrons as perfectly shielding (coefficient \(1.00\)) and assigning no screening at all to the same-shell valence electrons; this ignores both the \(0.35\) same-group contribution and the reduced \(0.85\) weighting Slater assigns to the \(n-1\) shell. (Choice D) A value of \(4.25\) comes from giving the \(n = 2\) shell a full screening coefficient of \(1.00\) (\(8 \times 1.00 = 8.00\)) rather than the \(0.85\) Slater prescribes for electrons one principal level below the electron of interest, inflating \(S\) to \(11.75\). This is a Scientific Reasoning and Problem Solving question because you must apply Slater’s screening rules step by step — partitioning the electrons into screening groups, weighting each group correctly, and subtracting the total shielding from the nuclear charge — to compute the effective nuclear charge.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '24148f17-4a09-4665-a041-6490640cc18a';
DELETE FROM question_distractor_metadata WHERE question_id = '24148f17-4a09-4665-a041-6490640cc18a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('24148f17-4a09-4665-a041-6490640cc18a', 'A', 'process_step_confusion', $a$Fails to exclude the electron under consideration from the same (3s,3p) group, counting all 6 at 0.35 (2.10) instead of 5 (1.75), giving Zeff = 5.10$a$),
  ('24148f17-4a09-4665-a041-6490640cc18a', 'B', 'misconception', $a$Uses the simplified Z_eff = Z - (core electrons) shortcut, assigning full 1.00 shielding to all 10 inner electrons and zero shielding to same-shell valence electrons, yielding 16 - 10 = 6.00$a$),
  ('24148f17-4a09-4665-a041-6490640cc18a', 'D', 'scale_unit_error', $a$Applies the wrong Slater coefficient to the n=2 shell, treating those 8 electrons as fully shielding (1.00) instead of 0.85, giving S = 11.75 and Zeff = 4.25$a$);

-- 7. [Periodic Trends · Skill 2 · ans B] id 4099118a-4cdb-4aff-a8ac-5d2d81948ca8
UPDATE questions SET
  question_text = $qt$The first four successive ionization energies (in \(\text{kJ/mol}\)) of a neutral third-period element X are \(\text{IE}_1 = 738\), \(\text{IE}_2 = 1451\), \(\text{IE}_3 = 7733\), and \(\text{IE}_4 = 10{,}540\). A \(4.86\ \text{g}\) sample of X is burned to completion in excess \(\text{O}_2\), and X enters the product in the oxidation state implied by its ionization pattern. The mass of metal oxide formed is most nearly: \((\text{molar masses: X} = 24.31\ \text{g/mol},\ \text{O} = 16.00\ \text{g/mol})\)$qt$,
  options = $op$[{"label":"A","text":"\\(6.46\\ \\text{g}\\)"},{"label":"B","text":"\\(8.06\\ \\text{g}\\)"},{"label":"C","text":"\\(9.66\\ \\text{g}\\)"},{"label":"D","text":"\\(11.26\\ \\text{g}\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is B because the controlling clue is the location of the large jump in successive ionization energies, which fixes the oxidation state that then drives the stoichiometry. The first two ionizations rise gradually (\(738 \rightarrow 1451\ \text{kJ/mol}\)), but \(\text{IE}_3\) leaps to \(7733\ \text{kJ/mol}\), more than five times \(\text{IE}_2\). That jump marks the point where the next electron must be pulled from the noble-gas \([\text{Ne}]\) core rather than the valence shell, so exactly two electrons are valence-accessible. A neutral third-period element with two valence electrons is a Group 2 metal (magnesium, \(1s^2 2s^2 2p^6 3s^2\)), giving the most common oxidation state \(+2\). With a \(+2\) cation, the oxide is \(\text{XO}\) (a 1:1 metal-to-oxygen ratio), formed by \(2\,\text{X} + \text{O}_2 \rightarrow 2\,\text{XO}\). The sample provides \(n_\text{X} = 4.86\ \text{g} \div 24.31\ \text{g/mol} = 0.200\ \text{mol}\). Because the metal-to-oxide mole ratio is 1:1, \(0.200\ \text{mol}\) of \(\text{XO}\) forms, and \(M_\text{XO} = 24.31 + 16.00 = 40.31\ \text{g/mol}\), so the mass is \(0.200 \times 40.31 = 8.06\ \text{g}\), matching B. (Choice A) \(6.46\ \text{g}\) results from misreading the jump as occurring after \(\text{IE}_1\), assigning a \(+1\) state and the oxide \(\text{X}_2\text{O}\); that formula consumes the metal in a 2:1 ratio (\(0.100\ \text{mol}\) oxide, \(M = 64.62\ \text{g/mol}\)), but the smooth, low \(\text{IE}_2\) shows the second electron is still a valence electron, so \(+1\) undercounts the available valence electrons. (Choice C) \(9.66\ \text{g}\) follows from placing the jump after \(\text{IE}_3\), assigning a \(+3\) state and the oxide \(\text{X}_2\text{O}_3\) (\(0.100\ \text{mol}\) oxide, \(M = 96.62\ \text{g/mol}\)); however, removing a third electron already breaches the core, as the steep \(\text{IE}_3\) shows, so a \(+3\) state overcounts the valence electrons. (Choice D) \(11.26\ \text{g}\) keeps the correct \(+2\) reading but treats the diatomic \(\text{O}_2\) as a single bound oxygen unit, writing the oxide as \(\text{XO}_2\) (\(M = 56.31\ \text{g/mol}\)); the \(+2\) charge balances only one \(\text{O}^{2-}\), so the correct empirical formula is \(\text{XO}\), and adding a second oxygen overstates the mass. This is a Scientific Reasoning and Problem Solving question because you must read the ionization pattern to deduce the oxidation state, translate that state into the correct oxide formula, and then carry the mole count through a multi-step mass calculation.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '4099118a-4cdb-4aff-a8ac-5d2d81948ca8';
DELETE FROM question_distractor_metadata WHERE question_id = '4099118a-4cdb-4aff-a8ac-5d2d81948ca8';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4099118a-4cdb-4aff-a8ac-5d2d81948ca8', 'A', 'process_step_confusion', $a$Places the large IE jump after IE1 instead of IE2, assigning a +1 state and the X2O oxide, which changes both the formula molar mass and the 2:1 metal-to-oxide mole ratio.$a$),
  ('4099118a-4cdb-4aff-a8ac-5d2d81948ca8', 'C', 'process_step_confusion', $a$Places the large IE jump after IE3, assigning a +3 state and the X2O3 oxide, overcounting valence electrons and using a 2:1 metal-to-oxide ratio.$a$),
  ('4099118a-4cdb-4aff-a8ac-5d2d81948ca8', 'D', 'misconception', $a$Reads the +2 state correctly but treats diatomic O2 as one oxygen unit, writing the oxide as XO2 instead of the charge-balanced XO.$a$);

-- 8. [Periodic Trends · Skill 2 · ans B] id 50d636ea-09f3-4be3-b70e-749074d61d84
UPDATE questions SET
  question_text = $qt$A crystallography group tabulates four monatomic ions for a lattice-packing model: \(\text{O}^{2-}\), \(\text{Na}^+\), \(\text{Mg}^{2+}\), and \(\text{Cl}^-\). Three of these ions share a common electron count, but the fourth does not. To list them correctly from largest to smallest ionic radius, the modeler must first sort out which structural feature dominates the comparison. Which ordering should most likely be reported?$qt$,
  options = $op$[{"label":"A","text":"\\(\\text{O}^{2-} > \\text{Na}^+ > \\text{Mg}^{2+} > \\text{Cl}^-\\)"},{"label":"B","text":"\\(\\text{Cl}^- > \\text{O}^{2-} > \\text{Na}^+ > \\text{Mg}^{2+}\\)"},{"label":"C","text":"\\(\\text{Cl}^- > \\text{Mg}^{2+} > \\text{Na}^+ > \\text{O}^{2-}\\)"},{"label":"D","text":"\\(\\text{O}^{2-} > \\text{Cl}^- > \\text{Na}^+ > \\text{Mg}^{2+}\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is B because the comparison must be split into two regimes by first counting electrons. \(\text{O}^{2-}\) has \(8 + 2 = 10\) electrons, \(\text{Na}^+\) has \(11 - 1 = 10\), and \(\text{Mg}^{2+}\) has \(12 - 2 = 10\), so these three are isoelectronic with neon and their outermost electrons all reside in the \(n = 2\) shell. \(\text{Cl}^-\), however, has \(17 + 1 = 18\) electrons and an occupied \(n = 3\) shell. The number of occupied principal shells is the dominant size factor when it differs: \(\text{Cl}^-\) carries an entire additional shell, so it is the largest ion in the set regardless of nuclear charge. Within the isoelectronic \(n = 2\) subset, shell count and electron–electron repulsion are held constant, so the only variable is nuclear charge; a larger \(Z\) raises \(Z_\text{eff}\) and contracts the cloud, giving \(\text{O}^{2-}\) (\(Z = 8\)) > \(\text{Na}^+\) (\(Z = 11\)) > \(\text{Mg}^{2+}\) (\(Z = 12\)). Chaining the two regimes yields \(\text{Cl}^- > \text{O}^{2-} > \text{Na}^+ > \text{Mg}^{2+}\), making B correct. (Choice A) This treats all four ions as a single isoelectronic series and ranks by nuclear charge alone, placing \(\text{Cl}^-\) (\(Z = 17\)) last as the smallest. It drops the fact that \(\text{Cl}^-\) is not isoelectronic with the other three; its added \(n = 3\) shell makes it the largest, so the within-shell \(Z\) rule cannot be applied across the differing electron counts. (Choice C) This correctly places \(\text{Cl}^-\) largest on the strength of its extra shell but then reverses the isoelectronic trend within the \(n = 2\) subset, treating higher nuclear charge as producing a larger ion. At fixed electron count a greater proton number raises \(Z_\text{eff}\) and shrinks the radius, so \(\text{Mg}^{2+}\) is the smallest of that subset, not the largest. (Choice D) This ranks by ionic charge, pairing the \(2-\) and \(1-\) anions ahead of the \(1+\) and \(2+\) cations and ordering by charge magnitude, which puts \(\text{O}^{2-}\) first and \(\text{Cl}^-\) second. Charge sign and magnitude do not set size across species with different shell counts; the occupied-shell difference makes \(\text{Cl}^-\) larger than the \(n = 2\) anion \(\text{O}^{2-}\). This is a Scientific Reasoning and Problem Solving question because you must identify the controlling constraint—which ions share an electron count—and then chain the principal-shell rule with the isoelectronic nuclear-charge trend to produce a single ordering.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '50d636ea-09f3-4be3-b70e-749074d61d84';
DELETE FROM question_distractor_metadata WHERE question_id = '50d636ea-09f3-4be3-b70e-749074d61d84';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('50d636ea-09f3-4be3-b70e-749074d61d84', 'A', 'misconception', $a$Treats all four ions as one isoelectronic series and ranks purely by ascending nuclear charge, dropping the constraint that Cl- has an extra occupied principal shell, so it wrongly lands as the smallest.$a$),
  ('50d636ea-09f3-4be3-b70e-749074d61d84', 'C', 'reversed_relationship', $a$Applies the shell-count rule correctly to make Cl- largest but reverses the isoelectronic radius trend within the Ne-like subset, assuming higher nuclear charge yields a larger ion.$a$),
  ('50d636ea-09f3-4be3-b70e-749074d61d84', 'D', 'misconception', $a$Ranks by ionic charge (anions before cations, ordered by charge magnitude) instead of by occupied shells and nuclear charge, placing the 2- ion first and ignoring that Cl-'s extra shell makes it larger than O2-.$a$);

-- 9. [Periodic Trends · Skill 2 · ans D] id 79285ef2-7f18-4304-a62a-d79eca28c136
UPDATE questions SET
  question_text = $qt$Down group 14, metallic character rises from carbon to lead even as nuclear charge climbs steeply. For gaseous lead the successive ionization energies are \( \text{IE}_1 = 716 \), \( \text{IE}_2 = 1450 \), \( \text{IE}_3 = 3081 \), and \( \text{IE}_4 = 4083\ \text{kJ/mol} \), with no abrupt order-of-magnitude jump appearing until after the fourth electron is removed, yet the markedly steeper rise from \( \text{IE}_2 \) to \( \text{IE}_3 \) than from \( \text{IE}_1 \) to \( \text{IE}_2 \) tracks the difference between lead's \( 6p \) and \( 6s \) valence electrons. Given that lead is the most metallic group-14 element, which conclusion about lead's chemistry is most directly supported by combining its enhanced metallic character with this ionization pattern?$qt$,
  options = $op$[{"label":"A","text":"Lead resists losing any valence electrons, so it behaves as a nonmetal forming a \\(-4\\) anion, because the large nuclear charge of \\(Z = 82\\) raises the effective nuclear charge enough to hold all four valence electrons against removal"},{"label":"B","text":"Lead most readily loses all four valence electrons together, so the \\(+4\\) state is its most stable cation, because rising metallic character down the group lowers every ionization energy enough to strip the full \\(6s^2 6p^2\\) set with comparable ease"},{"label":"C","text":"Lead most readily loses only its two \\(6s\\) electrons, so the \\(+2\\) state is its most stable cation, because the lower-energy \\(6s\\) pair is delocalized first and the \\(6p\\) electrons are bound too tightly to leave"},{"label":"D","text":"Lead most readily loses only its two \\(6p\\) electrons, so the \\(+2\\) state is its most stable cation, because the higher \\(n\\) of the valence shell makes the \\(6p\\) pair easy to delocalize while the more tightly held \\(6s\\) pair resists removal"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the conclusion requires chaining three periodic ideas. First, metallic character measures how readily an atom loses or delocalizes its valence electrons, and it rises down group 14 because each step adds a principal energy level, placing the valence electrons farther from the nucleus and behind more core shielding so they are held less tightly; lead, the bottom member, is therefore the most metallic and loses valence electrons most readily. Second, the ionization data identify which electrons are the easy ones to lose: \(\text{IE}_1\) and \(\text{IE}_2\) remove the two \(6p\) electrons relatively cheaply, but the jump to \(\text{IE}_3\) is steeper because the third electron must come from the lower-energy, more tightly bound \(6s\) subshell, whose electrons are poorly shielded by the intervening filled \(4f\) and \(5d\) sets and so feel a high effective nuclear charge (the inert-pair effect). Third, combining these, lead readily gives up only the loosely held \(6p^2\) pair while the \(6s^2\) pair resists removal, so the \(+2\) oxidation state is lead's most stable cation and the \(+4\) state is comparatively unstable (strongly oxidizing). The data confirm the order of removal: \(6p\) before \(6s\), with the steeper \(\text{IE}_2 \rightarrow \text{IE}_3\) rise marking the boundary between them. (Choice A) Lead's added protons are largely offset by added core shielding, so its effective nuclear charge does not climb enough to suppress electron loss; lead is the most metallic group-14 element and forms cations rather than a \(-4\) anion, making nonmetallic anion formation inconsistent with both the trend and the low \(\text{IE}_1\) and \(\text{IE}_2\) values given. (Choice B) Although metallic character does lower lead's ionization energies relative to lighter group-14 atoms, it does not flatten the difference between the \(6p\) and \(6s\) electrons; the steeper \(\text{IE}_2 \rightarrow \text{IE}_3\) rise shows the \(6s\) pair is distinctly harder to remove, so the \(+4\) state is not the most stable, and lead in fact favors \(+2\) by the inert-pair effect. (Choice C) Removal order runs from highest-energy to lowest-energy valence electrons, so the higher-energy \(6p\) electrons leave before the lower-energy \(6s\) electrons; asserting that the \(6s\) pair is lost first while the \(6p\) electrons remain reverses the energetic ordering of the valence subshells. This is a Scientific Reasoning and Problem Solving question because you must integrate the group trend in metallic character with the interpretation of successive ionization-energy data to deduce lead's preferred oxidation state.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '79285ef2-7f18-4304-a62a-d79eca28c136';
DELETE FROM question_distractor_metadata WHERE question_id = '79285ef2-7f18-4304-a62a-d79eca28c136';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('79285ef2-7f18-4304-a62a-d79eca28c136', 'A', 'misconception', $a$Applies the period-3 effective-nuclear-charge argument from the original stem to a down-group case, wrongly letting Z=82 raise Zeff enough to make lead a nonmetal forming a -4 anion$a$),
  ('79285ef2-7f18-4304-a62a-d79eca28c136', 'B', 'misconception', $a$Treats rising metallic character as lowering all ionization energies uniformly, ignoring the 6s/6p distinction the data show, and concludes the full 6s2 6p2 set ionizes with comparable ease to give a stable +4 state$a$),
  ('79285ef2-7f18-4304-a62a-d79eca28c136', 'C', 'reversed_relationship', $a$Reverses the removal order of valence subshells, claiming the lower-energy 6s pair ionizes before the higher-energy 6p electrons; reaches the correct +2 charge but by inverting which electrons are lost$a$);

-- 10. [Periodic Trends · Skill 2 · ans A] id fcf88274-ce3f-4ea7-b996-d24b6f1893ad
UPDATE questions SET
  question_text = $qt$Across Period 3 the first ionization energy generally rises from left to right, but two separate downward breaks interrupt that rise: \(\text{IE}_1\) drops \(160\ \text{kJ/mol}\) from magnesium to aluminum and drops \(12\ \text{kJ/mol}\) from phosphorus to sulfur. A textbook claims that exactly one of these two breaks would disappear if, hypothetically, the electron removed at the lower-energy member were drawn from a singly occupied valence orbital instead of a doubly occupied one. Which break does the textbook most likely mean, and what governs it?$qt$,
  options = $op$[{"label":"A","text":"The \\(\\text{P} \\rightarrow \\text{S}\\) break, because sulfur's \\(3p^4\\) set has one doubly occupied \\(3p\\) orbital whose paired electrons repel, lowering the energy needed to remove that electron relative to phosphorus's singly occupied \\(3p^3\\) set."},{"label":"B","text":"The \\(\\text{Mg} \\rightarrow \\text{Al} \\) break, because aluminum's outermost electron sits in a doubly occupied \\(3p\\) orbital whose pairing repulsion makes it easier to remove than magnesium's \\(3s\\) electron."},{"label":"C","text":"The \\(\\text{P} \\rightarrow \\text{S}\\) break, because phosphorus's half-filled \\(3p^3\\) set is destabilized by exchange repulsion, so phosphorus loses an electron more readily than the more stable \\(3p^4\\) sulfur."},{"label":"D","text":"The \\(\\text{Mg} \\rightarrow \\text{Al}\\) break, because aluminum's \\(3p\\) electron lies in a higher-energy, less penetrating subshell than magnesium's filled \\(3s\\), so it is held less tightly even with no paired electron."}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The two Period-3 breaks have different physical origins, and the stem's constraint—the break would vanish only if the removed electron came from a singly occupied orbital rather than a doubly occupied one—selects the one driven by electron-pairing repulsion. The answer to this question is A because the magnesium-to-aluminum drop and the phosphorus-to-sulfur drop must first be assigned to distinct mechanisms, and only then can the constraint be applied. Aluminum is \([\text{Ne}]3s^2 3p^1\): the electron removed is the lone \(3p^1\), which sits in a singly occupied \(3p\) orbital that is higher in energy and less penetrating than magnesium's filled \(3s^2\); pairing plays no role there, so that break would persist even if every orbital held just one electron. Sulfur is \([\text{Ne}]3s^2 3p^4\): three of its \(3p\) electrons occupy separate orbitals and the fourth must pair in one of them, creating a doubly occupied \(3p\) orbital whose two electrons repel. Removing that paired electron relieves the repulsion and costs less energy than removing one of phosphorus's three unpaired \(3p^3\) electrons, producing the \(12\ \text{kJ/mol}\) dip. If sulfur's removed electron instead came from a singly occupied orbital, the pairing repulsion would be absent and the \(\text{P} \rightarrow \text{S}\) break would disappear—so the \(\text{P} \rightarrow \text{S}\) break is the one the constraint identifies, and electron-pairing repulsion in a doubly occupied \(3p\) orbital governs it. (Choice B) Correctly identifies that aluminum's electron does come from a singly occupied orbital but then attributes the Mg-to-Al drop to pairing repulsion; that drop arises from the \(3s\)-to-\(3p\) subshell-energy and penetration difference, not from any paired electron, so the stated mechanism is wrong and the constraint would not erase this break. (Choice C) Selects the correct break but reverses the stability argument: the half-filled \(3p^3\) of phosphorus is the stabilized, exchange-favored arrangement that makes phosphorus harder to ionize, whereas the \(3p^4\) of sulfur carries the destabilizing paired-electron repulsion, so the roles of phosphorus and sulfur are inverted. (Choice D) Gives the correct mechanism for the Mg-to-Al break—the higher-energy, less penetrating \(3p\) subshell with no pairing involved—but assigns it to the wrong break; because that mechanism does not depend on a doubly occupied orbital, the stem's pairing constraint does not point to this break. This is a Scientific Reasoning and Problem Solving question because you must distinguish two co-occurring periodic anomalies by their separate electronic causes and then apply the stem's controlling constraint to determine which mechanism governs.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = 'fcf88274-ce3f-4ea7-b996-d24b6f1893ad';
DELETE FROM question_distractor_metadata WHERE question_id = 'fcf88274-ce3f-4ea7-b996-d24b6f1893ad';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('fcf88274-ce3f-4ea7-b996-d24b6f1893ad', 'B', 'process_step_confusion', $a$Correctly notes aluminum's electron is singly occupied but transplants the pairing-repulsion mechanism onto the Mg-to-Al break, conflating the two distinct anomaly causes$a$),
  ('fcf88274-ce3f-4ea7-b996-d24b6f1893ad', 'C', 'reversed_relationship', $a$Picks the correct P-to-S break but inverts which species carries the stabilizing half-filled set versus the destabilizing paired set, swapping phosphorus and sulfur$a$),
  ('fcf88274-ce3f-4ea7-b996-d24b6f1893ad', 'D', 'misconception', $a$States the correct subshell-penetration mechanism but binds it to the wrong break, failing the constraint that requires a doubly occupied orbital$a$);

-- 11. [Quantization, Bohr & Spectra · Skill 2 · ans D] id 3dea91e1-9aa2-4b22-b12c-2f38014a2b34
UPDATE questions SET
  question_text = $qt$A clean metal photocathode has a threshold (cutoff) wavelength of \(280\ \text{nm}\): light of any longer wavelength ejects no electrons. The cathode is then illuminated with monochromatic ultraviolet light of wavelength \(200\ \text{nm}\), and a reverse voltage is applied until the photocurrent just falls to zero. Using \(h = 6.626 \times 10^{-34}\ \text{J}\cdot\text{s}\), \(c = 3.00 \times 10^{8}\ \text{m/s}\), and \(e = 1.602 \times 10^{-19}\ \text{C}\), which value is most nearly the stopping voltage?$qt$,
  options = $op$[{"label":"A","text":"\\(10.64\\ \\text{V}\\)"},{"label":"B","text":"\\(4.43\\ \\text{V}\\)"},{"label":"C","text":"\\(6.20\\ \\text{V}\\)"},{"label":"D","text":"\\(1.77\\ \\text{V}\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the stopping voltage measures the maximum kinetic energy of the ejected electrons, which must be built from two separate energy quantities. First, the work function is fixed by the threshold wavelength: \(\Phi = hc/\lambda_0 = (6.626 \times 10^{-34})(3.00 \times 10^{8})/(280 \times 10^{-9}) = 7.10 \times 10^{-19}\ \text{J}\) (about \(4.43\ \text{eV}\)). Second, the incident \(200\ \text{nm}\) photon carries \(E = hc/\lambda = (6.626 \times 10^{-34})(3.00 \times 10^{8})/(200 \times 10^{-9}) = 9.94 \times 10^{-19}\ \text{J}\) (about \(6.20\ \text{eV}\)). Because the incident wavelength is shorter than the threshold, emission does occur, and the maximum kinetic energy is the difference \(K_\text{max} = E - \Phi = 9.94 \times 10^{-19} - 7.10 \times 10^{-19} = 2.84 \times 10^{-19}\ \text{J}\) (about \(1.77\ \text{eV}\)). The stopping voltage is the potential that just halts these fastest electrons, \(eV_s = K_\text{max}\), so \(V_s = K_\text{max}/e = 2.84 \times 10^{-19}/1.602 \times 10^{-19} = 1.77\ \text{V}\). (Choice A) \(10.64\ \text{V}\) results from adding the work function to the photon energy, \((E + \Phi)/e\), a sign reversal of the photoelectric relation; the governing equation is \(K_\text{max} = E - \Phi\), so the work function must be subtracted, not added. (Choice B) \(4.43\ \text{V}\) is the work function expressed as a voltage, \(\Phi/e\). It treats the energy needed merely to liberate an electron as if it were the energy the electron retains, stopping at the intermediate quantity \(\Phi\) rather than carrying it forward into the difference \(E - \Phi\); the work function is consumed in escaping the surface, not delivered to the electron's kinetic energy. (Choice C) \(6.20\ \text{V}\) is the full incident photon energy expressed as a voltage, \(E/e\). It omits the subtraction of the work function entirely, assigning the electron all of the photon's energy as kinetic energy and ignoring that escaping the metal costs \(\Phi\). This is a Scientific Reasoning and Problem Solving question because you must chain two independent energy calculations from different wavelengths, subtract them in the correct order, and convert the resulting kinetic energy into a stopping potential.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '3dea91e1-9aa2-4b22-b12c-2f38014a2b34';
DELETE FROM question_distractor_metadata WHERE question_id = '3dea91e1-9aa2-4b22-b12c-2f38014a2b34';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('3dea91e1-9aa2-4b22-b12c-2f38014a2b34', 'A', 'reversed_relationship', $a$Reverses the sign of the photoelectric equation, adding the work function to the photon energy ((E+Phi)/e) instead of subtracting it$a$),
  ('3dea91e1-9aa2-4b22-b12c-2f38014a2b34', 'B', 'process_step_confusion', $a$Stops at the intermediate work-function value (Phi/e) and reports it as the stopping voltage instead of carrying it forward into Kmax = E - Phi$a$),
  ('3dea91e1-9aa2-4b22-b12c-2f38014a2b34', 'C', 'misconception', $a$Drops the work-function term entirely and equates the electron's kinetic energy with the full incident photon energy (E/e), ignoring the escape cost$a$);

-- 12. [Quantization, Bohr & Spectra · Skill 2 · ans B] id 6e3485c8-821d-46e5-8e46-a6033728880e
UPDATE questions SET
  question_text = $qt$A hydrogen atom initially in its ground state absorbs a single photon of energy \(1.94 \times 10^{-18}\ \text{J}\) and is left in an excited level. A second photon then strikes the excited atom and ejects the electron with negligible kinetic energy. Taking \(R_\text{H} = 2.18 \times 10^{-18}\ \text{J}\) and \(E_n = -R_\text{H}/n^2\), what is the minimum energy this second photon must carry?$qt$,
  options = $op$[{"label":"A","text":"\\(5.45 \\times 10^{-19}\\ \\text{J}\\)"},{"label":"B","text":"\\(2.42 \\times 10^{-19}\\ \\text{J}\\)"},{"label":"C","text":"\\(1.94 \\times 10^{-18}\\ \\text{J}\\)"},{"label":"D","text":"\\(2.18 \\times 10^{-18}\\ \\text{J}\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is B because the problem must be solved in three chained steps. First, identify the excited level reached by the first photon: an absorption from the ground state obeys \(\Delta E = R_\text{H}\left(\dfrac{1}{1^2} - \dfrac{1}{n^2}\right)\), so \(1.94 \times 10^{-18}\ \text{J} = 2.18 \times 10^{-18}\ \text{J}\left(1 - \dfrac{1}{n^2}\right)\). This gives \(1 - \dfrac{1}{n^2} = 0.889\), so \(\dfrac{1}{n^2} = 0.111\) and \(n = 3\). Second, recognize that the second photon must ionize the atom starting from \(n = 3\), not from the ground state; because the electron leaves with negligible kinetic energy, the minimum photon energy equals exactly the binding energy at that level, \(\Delta E = E_\infty - E_3 = 0 - \left(-\dfrac{R_\text{H}}{3^2}\right) = \dfrac{R_\text{H}}{9}\). Third, evaluate: \(\dfrac{2.18 \times 10^{-18}\ \text{J}}{9} = 2.42 \times 10^{-19}\ \text{J}\). (Choice A) \(5.45 \times 10^{-19}\ \text{J}\) is \(R_\text{H}/4\), the binding energy of the \(n = 2\) level. It results from misidentifying the excited state as \(n = 2\) rather than solving \(R_\text{H}(1 - 1/n^2) = 1.94 \times 10^{-18}\ \text{J}\) correctly for \(n = 3\); the \(n = 2\) level requires only \(1.64 \times 10^{-18}\ \text{J}\) of absorbed energy, not the \(1.94 \times 10^{-18}\ \text{J}\) stated. (Choice C) \(1.94 \times 10^{-18}\ \text{J}\) is simply the energy of the first (absorbed) photon restated. It corresponds to the upward \(n = 1 \rightarrow n = 3\) excitation rather than the subsequent removal of the electron from \(n = 3\) to \(n = \infty\), so it answers the wrong step of the process. (Choice D) \(2.18 \times 10^{-18}\ \text{J}\) equals \(R_\text{H}\), the binding energy of the ground state. It is obtained by ignoring the first absorption step entirely and computing ionization from \(n = 1\); once the atom is already excited to \(n = 3\), only \(R_\text{H}/9\) remains between the electron and the continuum. This is a Scientific Reasoning and Problem Solving question because you must chain a level-assignment from an absorption energy to a level-dependent ionization calculation and carry the intermediate quantum number forward into the final step.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '6e3485c8-821d-46e5-8e46-a6033728880e';
DELETE FROM question_distractor_metadata WHERE question_id = '6e3485c8-821d-46e5-8e46-a6033728880e';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6e3485c8-821d-46e5-8e46-a6033728880e', 'A', 'process_step_confusion', $a$Misidentifies the excited level as n=2 (uses RH/4 binding) instead of solving the absorption equation to find n=3$a$),
  ('6e3485c8-821d-46e5-8e46-a6033728880e', 'C', 'partial_truth', $a$Restates the absorbed first-photon energy (the n=1 to n=3 excitation) instead of computing the energy to ionize from the excited level$a$),
  ('6e3485c8-821d-46e5-8e46-a6033728880e', 'D', 'misconception', $a$Drops the absorption step and computes ground-state ionization energy RH (n=1 to infinity) rather than ionization from the already-excited n=3 level$a$);

-- 13. [Quantization, Bohr & Spectra · Skill 4 · ans C] id 7e6456da-9e51-4332-9392-ce65cc59ef77
UPDATE questions SET
  question_text = $qt$A sealed tube holds a single pure element whose four lowest electronic energy levels, measured above the ground state, are \( n=1 \) at \( 0.00\ \text{eV} \), \( n=2 \) at \( 1.89\ \text{eV} \), \( n=3 \) at \( 2.55\ \text{eV} \), and \( n=4 \) at \( 3.40\ \text{eV} \). A discharge excites many of the atoms into the \( n=4 \) level, and as they relax they emit photons. Using \( E = hc/\lambda \) with \( hc = 1240\ \text{eV}\cdot\text{nm} \), and treating the visible band as roughly \( 400\text{-}700\ \text{nm} \), which emission line will most likely appear as the longest-wavelength line falling within the visible region of this element's spectrum?$qt$,
  options = $op$[{"label":"A","text":"The \\( 486\\ \\text{nm} \\) line from the \\( n=3 \\rightarrow n=1 \\) transition."},{"label":"B","text":"The \\( 821\\ \\text{nm} \\) line from the \\( n=4 \\rightarrow n=2 \\) transition."},{"label":"C","text":"The \\( 656\\ \\text{nm} \\) line from the \\( n=2 \\rightarrow n=1 \\) transition."},{"label":"D","text":"The \\( 365\\ \\text{nm} \\) line from the \\( n=4 \\rightarrow n=1 \\) transition."}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is C because each emission line is set by the energy difference between two quantized levels, \( \Delta E = E_\text{high} - E_\text{low} \), and the wavelength follows from \( \lambda = hc/\Delta E \). From a populated \( n=4 \) level the possible downward steps and their photons are: \( n=4 \rightarrow n=3 \) (\( 0.85\ \text{eV} \), \( 1459\ \text{nm} \)); \( n=4 \rightarrow n=2 \) (\( 1.51\ \text{eV} \), \( 821\ \text{nm} \)); \( n=4 \rightarrow n=1 \) (\( 3.40\ \text{eV} \), \( 365\ \text{nm} \)); \( n=3 \rightarrow n=2 \) (\( 0.66\ \text{eV} \), \( 1879\ \text{nm} \)); \( n=3 \rightarrow n=1 \) (\( 2.55\ \text{eV} \), \( 486\ \text{nm} \)); and \( n=2 \rightarrow n=1 \) (\( 1.89\ \text{eV} \), \( 656\ \text{nm} \)). The controlling constraint is that only lines between \( 400\ \text{nm} \) and \( 700\ \text{nm} \) appear in the visible region, which admits only the \( 486\ \text{nm} \) and \( 656\ \text{nm} \) lines; of these two, \( 656\ \text{nm} \) is the longer wavelength because it comes from the smaller energy gap (\( 1.89\ \text{eV} \)). The \( n=2 \rightarrow n=1 \) line at \( 656\ \text{nm} \) is therefore the longest-wavelength visible line. (Choice A) The \( n=3 \rightarrow n=1 \) line at \( 486\ \text{nm} \) is a genuine visible line, but its larger energy gap of \( 2.55\ \text{eV} \) makes it shorter in wavelength than the \( 656\ \text{nm} \) line, so it is not the longest visible line. (Choice B) The \( n=4 \rightarrow n=2 \) gap of \( 1.51\ \text{eV} \) does give the longest wavelength of all downward transitions from \( n=4 \), \( 821\ \text{nm} \), but that wavelength lies in the near-infrared beyond \( 700\ \text{nm} \) and is not part of the visible spectrum, so it is excluded by the stated constraint. (Choice D) The \( n=4 \rightarrow n=1 \) drop has the largest energy difference, \( 3.40\ \text{eV} \), which by \( \lambda = hc/\Delta E \) produces the shortest wavelength, \( 365\ \text{nm} \), placing it in the ultraviolet rather than the visible region and making it neither visible nor the longest wavelength. This is a Data-Based and Statistical Reasoning question because you must enumerate the allowed quantized transitions, convert each energy difference to a wavelength, filter the results against the visible-band constraint, and then select the longest qualifying wavelength.$ex$,
  cognitive_skill = 4,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '7e6456da-9e51-4332-9392-ce65cc59ef77';
DELETE FROM question_distractor_metadata WHERE question_id = '7e6456da-9e51-4332-9392-ce65cc59ef77';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('7e6456da-9e51-4332-9392-ce65cc59ef77', 'A', 'partial_truth', $a$Correctly restricts to visible lines but selects the wrong one, confusing 'longest wavelength' with the larger-gap visible transition and reporting 486 nm.$a$),
  ('7e6456da-9e51-4332-9392-ce65cc59ef77', 'B', 'misconception', $a$Picks the overall longest-wavelength (lowest-energy) downward transition from n=4 while dropping the controlling visible-band constraint, landing on the 821 nm near-IR line.$a$),
  ('7e6456da-9e51-4332-9392-ce65cc59ef77', 'D', 'reversed_relationship', $a$Inverts the inverse relationship between energy gap and wavelength, treating the largest energy drop (n=4 to n=1) as the longest wavelength, yielding the 365 nm UV line.$a$);

-- 14. [Quantization, Bohr & Spectra · Skill 2 · ans C] id 9d5a9d4a-3491-4f17-a1cf-50edbc58323f
UPDATE questions SET
  question_text = $qt$An excited hydrogen sample emits along several Balmer- and Paschen-series transitions at once. The light falls on an InGaAs photodetector that registers a signal only for photons whose wavelength lies between \(900\ \text{nm}\) and \(1700\ \text{nm}\); photons outside that band leave no trace. Among the four transitions below, using \(\Delta E = R_\text{H}\left(\dfrac{1}{n_f^2} - \dfrac{1}{n_i^2}\right)\) with \(R_\text{H} = 13.6\ \text{eV}\) and \(\lambda = (1240\ \text{eV}\cdot\text{nm})/\Delta E\), the longest-wavelength line the detector will most likely record comes from which transition?$qt$,
  options = $op$[{"label":"A","text":"\\(n = 4 \\rightarrow n = 3\\)"},{"label":"B","text":"\\(n = 4 \\rightarrow n = 2\\)"},{"label":"C","text":"\\(n = 5 \\rightarrow n = 3\\)"},{"label":"D","text":"\\(n = 6 \\rightarrow n = 4\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is C because the recorded line must satisfy two conditions chained together: it must fall inside the detector's \(900\text{--}1700\ \text{nm}\) band, and among the lines that qualify it must have the longest wavelength. First compute each gap, then convert to wavelength. For \(n = 5 \rightarrow n = 3\): \(\Delta E = 13.6\left(\tfrac{1}{9} - \tfrac{1}{25}\right) = 13.6(0.0711) \approx 0.967\ \text{eV}\), so \(\lambda = 1240/0.967 \approx 1282\ \text{nm}\), which lies inside the band. Checking the other candidates: \(n = 6 \rightarrow n = 4\) gives \(\approx 0.472\ \text{eV}\) and \(\lambda \approx 2626\ \text{nm}\); \(n = 4 \rightarrow n = 3\) gives \(\approx 0.661\ \text{eV}\) and \(\lambda \approx 1876\ \text{nm}\); both have longer wavelengths than B but lie beyond the \(1700\ \text{nm}\) upper edge, so the detector records nothing for them. The Balmer line \(n = 4 \rightarrow n = 2\) gives \(\approx 2.55\ \text{eV}\) and \(\lambda \approx 486\ \text{nm}\), well below the \(900\ \text{nm}\) lower edge. Thus \(n = 5 \rightarrow n = 3\) is the only transition both detectable and, trivially, the longest detectable one. (Choice A) \(n = 4 \rightarrow n = 3\) produces \(\approx 1876\ \text{nm}\); this is the line a treatment that picks the longest wavelength still "near" the window would select, but \(1876\ \text{nm}\) exceeds the \(1700\ \text{nm}\) ceiling and produces no signal. (Choice B) \(n = 4 \rightarrow n = 2\) corresponds to \(\approx 486\ \text{nm}\), the result of reversing the energy–wavelength relationship and selecting the largest gap (shortest wavelength); this visible Balmer line sits far below the detector's near-infrared band. (Choice D) \(n = 6 \rightarrow n = 4\) carries the smallest gap of the four, \(\approx 0.472\ \text{eV}\), and therefore the longest wavelength overall, \(\approx 2626\ \text{nm}\); selecting it reflects applying the bare "smallest gap gives longest wavelength" rule while ignoring the detector window, but \(2626\ \text{nm}\) lies far beyond the \(1700\ \text{nm}\) edge. This is a Scientific Reasoning and Problem Solving question because you must compute and convert several level gaps to wavelengths and then apply a controlling instrumental constraint to identify which qualifying line is governing.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '9d5a9d4a-3491-4f17-a1cf-50edbc58323f';
DELETE FROM question_distractor_metadata WHERE question_id = '9d5a9d4a-3491-4f17-a1cf-50edbc58323f';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('9d5a9d4a-3491-4f17-a1cf-50edbc58323f', 'A', 'partial_truth', $a$Applies the detector window but mishandles its upper edge, picking the longest-wavelength candidate near the band (1876 nm) without verifying it is at or below 1700 nm.$a$),
  ('9d5a9d4a-3491-4f17-a1cf-50edbc58323f', 'B', 'reversed_relationship', $a$Reverses the inverse energy-wavelength relationship, selecting the largest gap / shortest wavelength (486 nm) instead of the longest detectable wavelength.$a$),
  ('9d5a9d4a-3491-4f17-a1cf-50edbc58323f', 'D', 'misconception', $a$Applies the bare heuristic 'smallest gap gives longest wavelength' to pick the overall longest line (2626 nm) while dropping the controlling detector-window constraint.$a$);

-- 15. [Quantization, Bohr & Spectra · Skill 2 · ans A] id f70d2581-e19f-430e-ac30-d6fa33c7c6e1
UPDATE questions SET
  question_text = $qt$A vacuum-UV spectrometer records a single sharp hydrogen emission line at \(97.3\ \text{nm}\), which the operator identifies as belonging to the Lyman series (every Lyman line terminates at \(n = 1\)). The atoms that produced this line then relax through any allowed downward steps to the ground state. Taking \(R_\text{H} = 2.18 \times 10^{-18}\ \text{J}\), \(h = 6.63 \times 10^{-34}\ \text{J}\cdot\text{s}\), and \(c = 3.00 \times 10^{8}\ \text{m/s}\), which value is closest to the longest wavelength a photon emitted during that relaxation could have?$qt$,
  options = $op$[{"label":"A","text":"1877 nm"},{"label":"B","text":"657 nm"},{"label":"C","text":"487 nm"},{"label":"D","text":"122 nm"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is A because the problem must be solved in three chained steps. First, the energy of the recorded photon is \(E = \dfrac{hc}{\lambda} = \dfrac{(6.63\times10^{-34})(3.00\times10^{8})}{97.3\times10^{-9}} = 2.04\times10^{-18}\ \text{J}\). Second, because the line is a Lyman transition it terminates at \(n_f = 1\), so \(E = R_\text{H}\left(\dfrac{1}{1^2} - \dfrac{1}{n_i^2}\right)\); dividing by \(R_\text{H}\) gives \(\dfrac{2.04\times10^{-18}}{2.18\times10^{-18}} = 0.9375\), so \(\dfrac{1}{n_i^2} = 1 - 0.9375 = 0.0625 = \dfrac{1}{16}\), which fixes the emitting upper level at \(n_i = 4\). Third, an atom in \(n = 4\) can shed energy through several downward steps on its way to the ground state, and the photon with the longest wavelength is the one carrying the least energy, i.e., the smallest energy gap. The smallest single-step gap available from \(n = 4\) is \(n = 4 \rightarrow 3\): \(\Delta E = R_\text{H}\left(\dfrac{1}{3^2} - \dfrac{1}{4^2}\right) = R_\text{H}\left(\dfrac{7}{144}\right) = 1.06\times10^{-19}\ \text{J}\), giving \(\lambda = \dfrac{hc}{\Delta E} = \dfrac{(6.63\times10^{-34})(3.00\times10^{8})}{1.06\times10^{-19}} \approx 1.88\times10^{-6}\ \text{m} = 1877\ \text{nm}\), an infrared (Paschen) line. (Choice B) 657 nm is the \(n = 3 \rightarrow 2\) (H-alpha) line; it is the longest-wavelength line that lies in the visible region, but restricting the cascade to visible/Balmer transitions ignores the still smaller \(n = 4 \rightarrow 3\) gap, whose photon has a longer wavelength. (Choice C) 487 nm is the \(n = 4 \rightarrow 2\) (H-beta) line; it correctly retains the upper level \(n = 4\) but selects the largest energy drop emitted from that level as though a larger gap yielded a longer wavelength, reversing the inverse relationship \(\lambda \propto 1/\Delta E\). (Choice D) 122 nm is the \(n = 2 \rightarrow 1\) (Lyman-alpha) line, the longest-wavelength member of the Lyman series; choosing it treats "longest wavelength" as confined to Lyman lines and overlooks that the populated upper level permits non-Lyman steps of smaller energy and therefore longer wavelength. This is a Scientific Reasoning and Problem Solving question because you must convert a measured wavelength to a photon energy, back-solve the Bohr expression to identify the emitting level, and then determine which subsequent transition carries the least energy.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = 'f70d2581-e19f-430e-ac30-d6fa33c7c6e1';
DELETE FROM question_distractor_metadata WHERE question_id = 'f70d2581-e19f-430e-ac30-d6fa33c7c6e1';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('f70d2581-e19f-430e-ac30-d6fa33c7c6e1', 'B', 'partial_truth', $a$Picks the longest VISIBLE (Balmer) line, n=3->2 H-alpha, after dropping the constraint that the n=4->3 infrared step has an even smaller gap and longer wavelength.$a$),
  ('f70d2581-e19f-430e-ac30-d6fa33c7c6e1', 'C', 'reversed_relationship', $a$Retains the correct upper level n=4 but inverts lambda proportional to 1/DeltaE, selecting the largest energy drop from n=4 (n=4->2) as if a bigger gap gave a longer wavelength.$a$),
  ('f70d2581-e19f-430e-ac30-d6fa33c7c6e1', 'D', 'process_step_confusion', $a$Restricts the answer to the Lyman series and reports its longest member (n=2->1, 122 nm), failing to recognize that the n=4 upper level enables non-Lyman cascade steps of lower energy.$a$);

-- 16. [Quantum Model & Quantum Numbers · Skill 2 · ans D] id 74db8355-917a-45a2-bc77-f41b91b8d745
UPDATE questions SET
  question_text = $qt$A single atom is restricted so that no electron may occupy any shell beyond \(n = 4\). Across all of its allowed shells, consider every orbital whose magnetic quantum number equals \(m_l = +2\). Counting both spin orientations, what is the maximum number of electrons this atom could distribute among those orbitals?$qt$,
  options = $op$[{"label":"A","text":"3"},{"label":"B","text":"4"},{"label":"C","text":"12"},{"label":"D","text":"6"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is D because the count must be built up through the dependency chain \(n \rightarrow l \rightarrow m_l\) and then closed with the Pauli capacity of each orbital. First, an orbital can carry \(m_l = +2\) only if \(l \ge 2\), because \(m_l\) is bounded by \(-l \le m_l \le +l\); thus \(s\) (\(l = 0\)) and \(p\) (\(l = 1\)) subshells are excluded entirely. Second, within each shell the orbital quantum number is limited to \(l = 0, 1, \ldots, n-1\), so a subshell with \(l \ge 2\) exists only for \(n \ge 3\): the \(n = 3\) shell supplies \(3d\) (\(l = 2\)); the \(n = 4\) shell supplies \(4d\) (\(l = 2\)) and \(4f\) (\(l = 3\)). The \(n = 1\) and \(n = 2\) shells contribute nothing because their largest \(l\) is \(0\) and \(1\), respectively. Third, each of these three subshells contains exactly one orbital with \(m_l = +2\), giving the intermediate result of \(3\) qualifying orbitals. Finally, by the Pauli exclusion principle each orbital holds at most two electrons (\(m_s = +\tfrac{1}{2}\) and \(m_s = -\tfrac{1}{2}\)), so the maximum is \(3 \times 2 = 6\) electrons. (Choice A) 3 stops at the intermediate orbital count and omits the factor of two for spin, treating each \(m_l = +2\) orbital as holding a single electron rather than a Pauli pair. (Choice B) 4 results from restricting the search to the \(n = 4\) shell alone, capturing only \(4d\) and \(4f\) (\(2\) orbitals \(\times 2 = 4\)) while overlooking that the \(3d\) orbital in the \(n = 3\) shell also reaches \(m_l = +2\). (Choice C) 12 arises from misstating the orbital-quantum-number ceiling as \(l_\text{max} = n\) instead of \(l_\text{max} = n - 1\), which fabricates nonexistent \(2d\), \(3f\), and \(4g\) subshells and inflates the orbital count from \(3\) to \(6\) before applying the spin factor. This is a Scientific Reasoning and Problem Solving question because you must chain the allowed-value rules for three quantum numbers across multiple shells, carry an intermediate orbital count, and then apply the Pauli capacity to reach the final electron total.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '74db8355-917a-45a2-bc77-f41b91b8d745';
DELETE FROM question_distractor_metadata WHERE question_id = '74db8355-917a-45a2-bc77-f41b91b8d745';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('74db8355-917a-45a2-bc77-f41b91b8d745', 'A', 'process_step_confusion', $a$Dropped Pauli spin factor: reports the intermediate count of qualifying orbitals (3) as if each holds one electron, omitting the times-two spin capacity.$a$),
  ('74db8355-917a-45a2-bc77-f41b91b8d745', 'B', 'misconception', $a$Dropped a shell: restricts the analysis to the n=4 shell only and overlooks that the 3d orbital in the n=3 shell also reaches m_l=+2.$a$),
  ('74db8355-917a-45a2-bc77-f41b91b8d745', 'C', 'scale_unit_error', $a$Off-by-one on the l ceiling: uses l_max = n instead of n-1, fabricating 2d/3f/4g subshells and doubling the orbital count before applying spin.$a$);

-- 17. [Subatomic Particles · Skill 2 · ans A] id 8edbc86b-d5a4-4956-8009-3529ac1f9d69
UPDATE questions SET
  question_text = $qt$A chromium-containing salt is prepared in which the metal appears as a monatomic cation drawn from a single isotope whose nuclide has a mass number of \(52\) and contains \(28\) neutrons. In the salt the cation is balanced only by oxide ions, \(\text{O}^{2-}\), and the compound has the empirical formula \(\text{Cr}_2\text{O}_3\). For one such cation as it exists in this salt, the number of electrons present is most likely$qt$,
  options = $op$[{"label":"A","text":"\\(21\\)"},{"label":"B","text":"\\(24\\)"},{"label":"C","text":"\\(27\\)"},{"label":"D","text":"\\(18\\)"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is A because three results must be chained. First, the nuclide is fixed from its nucleons: the mass number counts protons plus neutrons, so the proton count (atomic number) is \(Z = A - \text{neutrons} = 52 - 28 = 24\), confirming chromium. Second, the cation charge is set by electroneutrality of \(\text{Cr}_2\text{O}_3\): each oxide is \(2-\), so three oxides supply \(3 \times (-2) = -6\); this must be canceled by two chromium cations, giving \(2x = +6\) and \(x = +3\) per cation. Third, electrons follow from charge: a \(3+\) cation has three fewer electrons than protons, so electrons \(= Z - \text{charge} = 24 - 3 = 21\). (Choice B) The value \(24\) is the electron count of a neutral chromium atom; it is reached by deducing \(Z = 24\) correctly but then never applying the charge, ignoring that the \(\text{Cr}_2\text{O}_3\) framework forces a positive cation deficient in electrons. (Choice C) The value \(27\) results from adding the charge magnitude to the proton count (\(24 + 3\)); this treats the \(3+\) species as though three electrons were gained, which would describe an anion, whereas a cation carries fewer electrons than protons. (Choice D) The value \(18\) arises from assigning the cation a \(+6\) charge—obtained by placing the entire \(-6\) from the three oxide ions onto a single chromium rather than splitting it between the two cations—then computing \(24 - 6\); the resulting count coincidentally equals that of neutral argon, reinforcing the trap, but the correct per-cation charge in \(\text{Cr}_2\text{O}_3\) is \(+3\), not \(+6\). This is a Scientific Reasoning and Problem Solving question because you must integrate nucleon bookkeeping, an electroneutrality constraint on a stated formula, and the charge-to-electron relationship in sequence, with each intermediate value feeding the next.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = '8edbc86b-d5a4-4956-8009-3529ac1f9d69';
DELETE FROM question_distractor_metadata WHERE question_id = '8edbc86b-d5a4-4956-8009-3529ac1f9d69';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('8edbc86b-d5a4-4956-8009-3529ac1f9d69', 'B', 'partial_truth', $a$Correctly derives Z=24 but omits the final charge step, reporting the neutral-atom electron count$a$),
  ('8edbc86b-d5a4-4956-8009-3529ac1f9d69', 'C', 'reversed_relationship', $a$Adds the charge magnitude to Z (treats the cation as having gained electrons), reversing the cation electron-deficit relationship$a$),
  ('8edbc86b-d5a4-4956-8009-3529ac1f9d69', 'D', 'process_step_confusion', $a$Mis-distributes the oxide charge by assigning the full -6 to one chromium, yielding a +6 cation and the Ar-isoelectronic count of 18$a$);

-- 18. [Subatomic Particles · Skill 2 · ans A] id e1f745d0-0def-438d-b471-c60ffdcdbfa9
UPDATE questions SET
  question_text = $qt$A metal M is the only cationic species in an oxide of empirical formula \(\text{M}_2\text{O}_3\). The neutral parent atom of M has 21 protons and 24 neutrons. For one M ion exactly as it exists in this oxide, how many electrons does it most likely carry, and which noble gas is it isoelectronic with?$qt$,
  options = $op$[{"label":"A","text":"18 electrons, isoelectronic with argon"},{"label":"B","text":"19 electrons, isoelectronic with argon"},{"label":"C","text":"21 electrons, isoelectronic with argon"},{"label":"D","text":"24 electrons, isoelectronic with krypton"}]$op$::jsonb,
  explanation = $ex$This is a General Chemistry question that falls under the content category 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior'. The answer to this question is A because the charge on M must first be fixed by the oxide formula, then the electron count is obtained from the atomic number, and only then is the isoelectronic partner identified. In \(\text{M}_2\text{O}_3\) each oxide ion carries a \(-2\) charge, so charge neutrality requires \(2(x) + 3(-2) = 0\), giving \(x = +3\); the cation is therefore \(\text{M}^{3+}\). The neutral parent has 21 protons, so its atomic number is \(Z = 21\) (with 24 neutrons giving mass number 45, consistent with scandium). For any monatomic ion the electron count equals \(Z\) minus the net charge, so \(\text{M}^{3+}\) holds \(21 - 3 = 18\) electrons. Eighteen electrons is exactly the electron count of argon \((Z = 18)\), so the ion is isoelectronic with argon. (Choice B) An electron count of 19 results from assigning M a \(+2\) charge, the default oxidation state for a divalent metal, rather than reading \(+3\) from the \(\text{M}_2\text{O}_3\) stoichiometry; \(21 - 2 = 19\) electrons does not match any noble gas and is not isoelectronic with argon. (Choice C) An electron count of 21 results from omitting the ionic charge entirely and counting electrons for the neutral atom, \(21 - 0 = 21\); this is the configuration of neutral scandium, which exceeds argon by three electrons. (Choice D) An electron count of 24 results from adding the charge to the atomic number instead of subtracting it, \(21 + 3 = 24\), a reversed-sign error; 24 electrons is neither the count of argon nor of krypton (which requires 36 electrons), so the krypton pairing is incorrect. This is a Scientific Reasoning and Problem Solving question because you must chain the oxidation state implied by an empirical formula to the atomic number and net charge before counting electrons and identifying the isoelectronic noble gas.$ex$,
  cognitive_skill = 2,
  difficulty = 'hard',
  estimated_time_seconds = 160
WHERE id = 'e1f745d0-0def-438d-b471-c60ffdcdbfa9';
DELETE FROM question_distractor_metadata WHERE question_id = 'e1f745d0-0def-438d-b471-c60ffdcdbfa9';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('e1f745d0-0def-438d-b471-c60ffdcdbfa9', 'B', 'partial_truth', $a$Assigns the metal its default +2 oxidation state instead of deriving +3 from the M2O3 stoichiometry, then correctly computes 21 - 2 = 19 electrons$a$),
  ('e1f745d0-0def-438d-b471-c60ffdcdbfa9', 'C', 'process_step_confusion', $a$Drops the ionic-charge constraint entirely and counts electrons for the neutral atom (21 - 0 = 21), the configuration of neutral scandium$a$),
  ('e1f745d0-0def-438d-b471-c60ffdcdbfa9', 'D', 'reversed_relationship', $a$Adds the charge to Z instead of subtracting it (21 + 3 = 24), a reversed-sign slip, and pairs the inflated count with the next-larger noble gas$a$);

COMMIT;
SELECT count(*) AS atomic_hard_updated FROM questions WHERE topic='Atomic Structure' AND difficulty='hard';
