-- General Chemistry: Bonding & Chemical Interactions — REMEDIATED (quality + scope sweep); grounded in OpenStax Atoms First 2e
-- Remediated 12/12 flagged questions in place (UPDATE by id, ids preserved). 12 re-engineered, 0 scope-flagged.
-- distractor_category mapped to the question_distractor_metadata CHECK set. Idempotent; safe to re-run.

BEGIN;

-- [Lewis Acids & Bases] ans=B medium skill2
UPDATE questions SET
  question_text = 'Boron trifluoride reacts with ammonia in the gas phase to form a single adduct: \(\text{BF}_3 + \text{NH}_3 \rightarrow \text{F}_3\text{B}\text{-}\text{NH}_3\). In the product, a new bond joins boron to nitrogen. Which statement correctly identifies the Lewis acid in this reaction and the structural feature responsible for that role?',
  options = '[{"label": "A", "text": "\\(\\text{NH}_3\\) is the Lewis acid, because nitrogen bears the lone pair used to form the new bond"}, {"label": "B", "text": "\\(\\text{BF}_3\\) is the Lewis acid, because boron has an incomplete octet and an empty valence orbital"}, {"label": "C", "text": "\\(\\text{NH}_3\\) is the Lewis acid, because the electronegative nitrogen pulls electron density from boron"}, {"label": "D", "text": "\\(\\text{BF}_3\\) is the Lewis acid, because the three fluorine atoms make boron the most electronegative center"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' In the Lewis model, an acid is any species that accepts a pair of electrons to form a coordinate covalent bond, while a base is the species that donates that pair; identifying the acid therefore requires locating the species with a vacant orbital rather than reading off charges or electronegativities. (Choice B) is correct: boron in \(\text{BF}_3\) has only six valence electrons (three \(\text{B}\text{-}\text{F}\) bonds and no lone pair), so it has an empty valence orbital and can accept the lone pair on nitrogen, making \(\text{BF}_3\) the electron-pair acceptor and thus the Lewis acid. (Choice A) is incorrect: nitrogen in \(\text{NH}_3\) does hold the lone pair used to form the bond, but donating that pair is the defining behavior of a Lewis base, so this feature identifies \(\text{NH}_3\) as the base, not the acid. (Choice C) is incorrect: it also mislabels \(\text{NH}_3\) as the acid, and although nitrogen is more electronegative than boron, pulling electron density is not the same as accepting a lone pair into an empty orbital, and \(\text{NH}_3\) is in fact the donor. (Choice D) is incorrect: it reaches the right species but for a false reason—fluorine, not boron, is the electronegative element in \(\text{BF}_3\); boron acts as the acid because of its empty orbital and incomplete octet, not because it is electron-rich. This is a Scientific Reasoning and Problem Solving question because you must apply the Lewis acid-base definition to a novel reactant pair and reason from each species'' electron structure to assign the acceptor role.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'ce64d613-c297-4b9c-87e6-899a504dc5d7';
DELETE FROM question_distractor_metadata WHERE question_id = 'ce64d613-c297-4b9c-87e6-899a504dc5d7';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('ce64d613-c297-4b9c-87e6-899a504dc5d7', 'A', 'reversed_relationship', 'confuses donor (base) with acceptor (acid)'),
  ('ce64d613-c297-4b9c-87e6-899a504dc5d7', 'C', 'misconception', 'equates electronegativity/electron-pulling with Lewis acidity'),
  ('ce64d613-c297-4b9c-87e6-899a504dc5d7', 'D', 'adjacent_fact', 'right species, false structural justification');

-- [Stereochemistry] ans=A medium skill2
UPDATE questions SET
  question_text = 'A newly synthesized drug is a chiral molecule, and a chemist isolates its two enantiomers as separate pure samples. Testing each sample against the other under identical conditions, which measured property is expected to differ between the two enantiomers?',
  options = '[{"label": "A", "text": "The direction in which each sample rotates plane-polarized light"}, {"label": "B", "text": "The boiling point measured at atmospheric pressure"}, {"label": "C", "text": "The solubility of each sample in pure water"}, {"label": "D", "text": "The normal melting point of each crystalline solid"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is an Organic Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Enantiomers are nonsuperimposable mirror-image isomers; because each molecule has the same set of bonds and the same atoms, the two forms share identical scalar physical properties such as boiling point, melting point, density, and solubility in an ordinary (achiral) solvent. They diverge only in properties that depend on a chiral reference frame: how they rotate plane-polarized light and how they interact with other chiral species. (Choice A) is correct: rotation of plane-polarized light is a chiral property, so one enantiomer rotates the plane one way and its mirror image rotates it by the same magnitude in the opposite direction. (Choice B) is incorrect: boiling point reflects the strength of intermolecular forces between identical molecules, which is unchanged by mirror-imaging, so both enantiomers boil at the same temperature. (Choice C) is incorrect: water is achiral, so it cannot distinguish the two mirror images, and both enantiomers dissolve to the same extent. (Choice D) is incorrect: melting point depends on how identical molecules pack in the crystal, an achiral property that is the same for a pure sample of either enantiomer. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that enantiomers differ only in chiral-dependent behavior to predict which measured property changes.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '2eabd2b2-6c63-48f4-a6d1-dba0edf13e69';
DELETE FROM question_distractor_metadata WHERE question_id = '2eabd2b2-6c63-48f4-a6d1-dba0edf13e69';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('2eabd2b2-6c63-48f4-a6d1-dba0edf13e69', 'B', 'misconception', 'enantiomers-have-different-physical-properties'),
  ('2eabd2b2-6c63-48f4-a6d1-dba0edf13e69', 'C', 'misconception', 'chiral-molecule-implies-different-solubility'),
  ('2eabd2b2-6c63-48f4-a6d1-dba0edf13e69', 'D', 'misconception', 'enantiomers-have-different-physical-properties');

-- [Lewis Structures] ans=A medium skill2
UPDATE questions SET
  question_text = 'The cyanate ion is made from one carbon, one nitrogen, and one oxygen atom (16 valence electrons total) and can in principle be assembled with any of the three atoms in the central position. A student draws each of the three possible skeletons, fills in octets, and computes the formal charge on every atom. Which arrangement is the most reasonable Lewis structure for the ion?',
  options = '[{"label": "A", "text": "Carbon in the center, giving \\([\\text{O}=\\text{C}=\\text{N}]^-\\) with formal charges of 0, 0, and \\(-1\\)"}, {"label": "B", "text": "Nitrogen in the center, giving \\([\\text{O}=\\text{N}=\\text{C}]^-\\) with formal charges of 0, \\(+1\\), and \\(-2\\)"}, {"label": "C", "text": "Oxygen in the center, giving \\([\\text{C}=\\text{O}=\\text{N}]^-\\) with formal charges of \\(-2\\), \\(+2\\), and \\(-1\\)"}, {"label": "D", "text": "Carbon in the center, but placing the \\(-1\\) formal charge on carbon rather than on a terminal atom"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' When more than one skeletal arrangement is possible, formal charge is the tool used to decide which Lewis structure is most reasonable: the preferred structure minimizes the number of atoms bearing nonzero formal charge, keeps any nonzero charges as small as possible, and places negative formal charge on the most electronegative atom. Formal charge is calculated as (valence electrons) − (nonbonding electrons) − (number of bonds), and the formal charges must sum to the ion''s overall charge of \(-1\). (Choice A) is correct: with carbon (the least electronegative of the three) central, the structure \([\text{O}=\text{C}=\text{N}]^-\) leaves only one atom with a nonzero formal charge, that charge is only \(-1\), and it sits on nitrogen/oxygen rather than carbon — satisfying all of the preference guidelines. This is also the arrangement isoelectronic with \(\text{CO}_2\), the textbook model for a well-behaved linear triatomic. (Choice B) is incorrect: putting nitrogen in the center forces a central \(+1\) plus a large \(-2\) onto the terminal carbon, giving two atoms with nonzero formal charge — a much less favorable distribution than a single \(-1\). (Choice C) is incorrect: once octets are filled, a central oxygen is forced to \(+2\) (a large-magnitude positive charge stranded on the most electronegative atom), with the two terminal atoms carrying \(-2\) and \(-1\); this places three atoms at nonzero charge and directly violates the guideline that negative charge belongs on the most electronegative atom. (Choice D) is incorrect: even with the correct carbon-central skeleton, deliberately assigning the \(-1\) to carbon rather than to the more electronegative terminal atom gives a worse formal-charge distribution and is not what the octet-filled structure actually yields. This is a Scientific Reasoning and Problem Solving question because you must apply the formal-charge guidelines to compare candidate structures and identify the one with the most favorable charge distribution.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '6c4038e2-32b7-4ea4-8196-f2138562c76c';
DELETE FROM question_distractor_metadata WHERE question_id = '6c4038e2-32b7-4ea4-8196-f2138562c76c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('6c4038e2-32b7-4ea4-8196-f2138562c76c', 'B', 'misconception', 'central-atom-by-position-not-electronegativity'),
  ('6c4038e2-32b7-4ea4-8196-f2138562c76c', 'C', 'misconception', 'electronegative-atom-central'),
  ('6c4038e2-32b7-4ea4-8196-f2138562c76c', 'D', 'misconception', 'misplaced-formal-charge');

-- [Bond Length & Bond Energy] ans=A medium skill2
UPDATE questions SET
  question_text = 'A chemist compares three carbon-containing bonds: the carbon-carbon single bond in ethane \(\text{(C-C)}\), the carbon-carbon triple bond in ethyne \(\text{(C}\equiv\text{C)}\), and the carbon-iodine single bond in iodomethane \(\text{(C-I)}\). Recall that bond length reflects both the number of shared electron pairs and the sizes of the bonded atoms, and that iodine lies far below carbon in the periodic table. Which sequence correctly orders these three bonds from longest to shortest?',
  options = '[{"label": "A", "text": "\\(\\text{C-I} > \\text{C-C} > \\text{C}\\equiv\\text{C}\\)"}, {"label": "B", "text": "\\(\\text{C-C} > \\text{C-I} > \\text{C}\\equiv\\text{C}\\)"}, {"label": "C", "text": "\\(\\text{C}\\equiv\\text{C} > \\text{C-C} > \\text{C-I}\\)"}, {"label": "D", "text": "\\(\\text{C-C} > \\text{C}\\equiv\\text{C} > \\text{C-I}\\)"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Bond length is governed by two factors: for a bond between the same two atoms, adding shared electron pairs (higher bond order) pulls the nuclei closer and shortens the bond, so a triple bond is shorter than a single bond; and for bonds of the same order, larger atoms keep the nuclei farther apart, so a bond to an atom low in a group (like iodine, a large period-5 atom) is longer than a bond to a small period-2 atom. Ranking these three requires applying both ideas at once rather than counting shared pairs alone. (Choice A) is correct: the \(\text{C-I}\) single bond is longest because iodine is a large atom that holds the nuclei far apart despite being a single bond; the \(\text{C-C}\) single bond is intermediate (two small carbons, one shared pair); and the \(\text{C}\equiv\text{C}\) triple bond is shortest because three shared pairs draw the two small carbons closest together. (Choice B) is incorrect: it assumes bond order alone sets length, ranking the \(\text{C-C}\) single bond as longest and overlooking that iodine''s large atomic size makes \(\text{C-I}\) longer than \(\text{C-C}\) even though both are single bonds. (Choice C) is incorrect: it inverts the bond-order/length relationship by placing the triple bond as longest; adding shared pairs shortens, not lengthens, a bond, so \(\text{C}\equiv\text{C}\) is the shortest of the three, not the longest. (Choice D) is incorrect: it correctly makes \(\text{C-C}\) longer than \(\text{C}\equiv\text{C}\) but mistakenly ranks the large-atom \(\text{C-I}\) bond as shortest, ignoring that iodine''s size makes this single bond the longest of the set. This is a Scientific Reasoning and Problem Solving question because you must apply two competing determinants of bond length—bond order and atomic size—to rank bonds that differ in both, rather than recall a single ordering.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'e59abddc-09e7-4ed5-8064-bcd2d936d046';
DELETE FROM question_distractor_metadata WHERE question_id = 'e59abddc-09e7-4ed5-8064-bcd2d936d046';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('e59abddc-09e7-4ed5-8064-bcd2d936d046', 'B', 'misconception', 'applies bond-order rule while ignoring atomic-size effect'),
  ('e59abddc-09e7-4ed5-8064-bcd2d936d046', 'C', 'reversed_relationship', 'inverts bond-order/bond-length relationship'),
  ('e59abddc-09e7-4ed5-8064-bcd2d936d046', 'D', 'misconception', 'treats large-atom single bond as short because it is single');

-- [Lewis Acids & Bases] ans=B medium skill2
UPDATE questions SET
  question_text = 'Diethyl ether (\(\text{Et}_2\text{O}\)) reacts with \(\text{BF}_3\) to form the stable adduct \(\text{Et}_2\text{O}\text{-}\text{BF}_3\). When gaseous \(\text{NH}_3\) is then bubbled through this adduct, the ether is released and \(\text{F}_3\text{B}\text{-}\text{NH}_3\) forms instead. In the second step, what is the role of the diethyl ether?',
  options = '[{"label": "A", "text": "It is the Lewis acid that is displaced from boron"}, {"label": "B", "text": "It is the Lewis base that is displaced from boron"}, {"label": "C", "text": "It is the Brønsted base that accepts a proton"}, {"label": "D", "text": "It is the Lewis acid that displaces ammonia"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' A Lewis base donates a lone pair, a Lewis acid accepts it, and the product is a Lewis acid-base adduct; a stronger Lewis base can displace a weaker one from the same acid. (Choice B) is correct: in the first adduct, the ether oxygen donated a lone pair to the electron-deficient boron, so ether is a Lewis base bound to the Lewis acid \(\text{BF}_3\); when the stronger base \(\text{NH}_3\) donates its nitrogen lone pair to that same boron, the ether''s oxygen lone pair is pushed off, so ether is the Lewis base that gets displaced. (Choice A) is incorrect: ether does bind boron, but as the electron-pair donor it is the Lewis base, not the acid — the acid is \(\text{BF}_3\), whose boron accepts the pair. (Choice C) is incorrect: no proton moves in this step; boron, not hydrogen, is transferred between bases, so the Brønsted framework does not apply and ether is not accepting an \(\text{H}^+\). (Choice D) is incorrect: this reverses the chemistry — the incoming stronger base \(\text{NH}_3\) is what displaces the ether, and both ether and ammonia are electron-pair donors (Lewis bases), not acids. This is a Scientific Reasoning and Problem Solving question because you must apply the Lewis definitions to a displacement scenario and infer which reactant loses its bond to boron.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'eb7d1692-7242-447b-abdd-fc7ab260744c';
DELETE FROM question_distractor_metadata WHERE question_id = 'eb7d1692-7242-447b-abdd-fc7ab260744c';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('eb7d1692-7242-447b-abdd-fc7ab260744c', 'A', 'reversed_relationship', 'swaps electron-pair donor/acceptor roles (calls the donor a Lewis acid)'),
  ('eb7d1692-7242-447b-abdd-fc7ab260744c', 'C', 'misconception', 'applies Brønsted proton-transfer framework where no proton moves'),
  ('eb7d1692-7242-447b-abdd-fc7ab260744c', 'D', 'reversed_relationship', 'reverses which species is displaced and mislabels a base as an acid');

-- [Bond Polarity & Dipole Moment] ans=D medium skill2
UPDATE questions SET
  question_text = 'Each of the following molecules contains covalent bonds that are individually polar: carbon dioxide (\(\text{CO}_2\)), boron trifluoride (\(\text{BF}_3\)), tetrachloromethane (\(\text{CCl}_4\)), and ammonia (\(\text{NH}_3\)). Which of these molecules has a nonzero net dipole moment?',
  options = '[{"label": "A", "text": "\\(\\text{CO}_2\\)"}, {"label": "B", "text": "\\(\\text{BF}_3\\)"}, {"label": "C", "text": "\\(\\text{CCl}_4\\)"}, {"label": "D", "text": "\\(\\text{NH}_3\\)"}]'::jsonb,
  correct_answer = 'D',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' A molecule is polar only if it contains polar bonds AND its molecular geometry is such that the individual bond dipole vectors do not cancel; each bond dipole points from the less electronegative atom toward the more electronegative one, and the net molecular dipole is their vector sum in three dimensions. When identical polar bonds are arranged symmetrically around a central atom, their vectors cancel and the molecule is nonpolar despite having polar bonds. (Choice D) is correct: \(\text{NH}_3\) is trigonal pyramidal because the central nitrogen carries a lone pair, so the three polar N–H bond dipoles do not cancel and add to a nonzero net dipole moment, making ammonia polar. (Choice A) is incorrect: \(\text{CO}_2\) is linear, so its two equal but oppositely directed C=O bond dipoles point \(180^\circ\) apart and cancel exactly, leaving a nonpolar molecule despite the polar bonds. (Choice B) is incorrect: \(\text{BF}_3\) is trigonal planar with three identical B–F bond dipoles separated by \(120^\circ\); by symmetry their vector sum is zero, so the molecule is nonpolar. (Choice C) is incorrect: \(\text{CCl}_4\) is tetrahedral with four identical C–Cl bond dipoles arranged symmetrically, so they cancel and the molecule has no net dipole moment even though each bond is polar. This is a Scientific Reasoning and Problem Solving question because you must apply VSEPR-derived molecular geometry to the vector sum of bond dipoles to decide which molecule has a net dipole, rather than judging bond polarity alone.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '75f5137e-fcc8-46a8-9e0a-fd8881753cd4';
DELETE FROM question_distractor_metadata WHERE question_id = '75f5137e-fcc8-46a8-9e0a-fd8881753cd4';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('75f5137e-fcc8-46a8-9e0a-fd8881753cd4', 'A', 'misconception', 'polar bonds imply polar molecule'),
  ('75f5137e-fcc8-46a8-9e0a-fd8881753cd4', 'B', 'misconception', 'ignores symmetric cancellation of bond dipoles'),
  ('75f5137e-fcc8-46a8-9e0a-fd8881753cd4', 'C', 'misconception', 'ignores symmetric cancellation of bond dipoles');

-- [Intermolecular Forces] ans=B medium skill2
UPDATE questions SET
  question_text = 'Chloromethane \(\text{CH}_3\text{Cl}\) (molar mass \(50.5\ \text{g/mol}\)) boils at \(-24\,^\circ\text{C}\), well above propane \(\text{C}_3\text{H}_8\) (molar mass \(44\ \text{g/mol}\)) at \(-42\,^\circ\text{C}\). Which intermolecular interaction best accounts for the higher boiling point of \(\text{CH}_3\text{Cl}\)?',
  options = '[{"label": "A", "text": "Hydrogen bonding between \\(\\text{CH}_3\\text{Cl}\\) molecules"}, {"label": "B", "text": "Dipole–dipole attraction between \\(\\text{CH}_3\\text{Cl}\\) molecules"}, {"label": "C", "text": "Stronger London dispersion forces in \\(\\text{CH}_3\\text{Cl}\\) due to its greater molar mass"}, {"label": "D", "text": "The greater strength of the polar \\(\\text{C-Cl}\\) covalent bond within \\(\\text{CH}_3\\text{Cl}\\)"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Boiling point reflects the strength of the intermolecular forces that must be overcome to move molecules into the gas phase, and comparing molecules of similar mass isolates the effect of molecular polarity: \(\text{CH}_3\text{Cl}\) is polar (a net dipole points toward the electronegative Cl), whereas \(\text{C}_3\text{H}_8\) is nonpolar. Because their molar masses are close, both experience comparable London dispersion forces, so the extra cohesion in \(\text{CH}_3\text{Cl}\) must come from a force propane lacks. (Choice B) is correct: the permanent dipole of \(\text{CH}_3\text{Cl}\) lets the partial-negative Cl end of one molecule attract the partial-positive end of a neighbor, a dipole-dipole attraction that adds to dispersion and raises the boiling point above that of nonpolar propane of similar mass. (Choice A) is incorrect: hydrogen bonding requires hydrogen covalently bonded to N, O, or F; \(\text{CH}_3\text{Cl}\) has only \(\text{C-H}\) bonds and its H atoms are not bonded to those elements, so it cannot hydrogen bond despite chlorine''s lone pairs. (Choice C) is incorrect: dispersion forces scale with polarizability and molar mass, but the two molar masses (\(50.5\) vs \(44\ \text{g/mol}\)) are too close for dispersion to account for an \(18\,^\circ\text{C}\) difference; treating the small mass gap as the cause ignores the permanent dipole unique to the polar molecule. (Choice D) is incorrect: the strength of the intramolecular \(\text{C-Cl}\) bond governs how hard it is to break the molecule apart chemically, not how strongly separate molecules attract one another; boiling breaks intermolecular forces, not covalent bonds. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between molecular polarity, molar mass, and intermolecular forces to explain a boiling-point difference rather than recall a definition.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'db10e131-c0f6-46ab-82f7-4c5f531b09bd';
DELETE FROM question_distractor_metadata WHERE question_id = 'db10e131-c0f6-46ab-82f7-4c5f531b09bd';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('db10e131-c0f6-46ab-82f7-4c5f531b09bd', 'A', 'misconception', 'chlorine enables hydrogen bonding like F/O/N'),
  ('db10e131-c0f6-46ab-82f7-4c5f531b09bd', 'C', 'misconception', 'attributes higher boiling point to greater mass/dispersion'),
  ('db10e131-c0f6-46ab-82f7-4c5f531b09bd', 'D', 'misconception', 'confuses intramolecular bond strength with intermolecular force');

-- [Bond Length & Bond Energy] ans=C medium skill2
UPDATE questions SET
  question_text = 'A student is comparing the carbon–carbon bonds in three simple hydrocarbons: ethane (\(\text{C}_2\text{H}_6\)), ethene (\(\text{C}_2\text{H}_4\)), and ethyne (\(\text{C}_2\text{H}_2\)). No bond-length data are provided. Using the Lewis structures of these molecules, which carbon–carbon bond is expected to be the shortest?',
  options = '[{"label": "A", "text": "The carbon–carbon bond in ethane"}, {"label": "B", "text": "The carbon–carbon bond in ethene"}, {"label": "C", "text": "The carbon–carbon bond in ethyne"}, {"label": "D", "text": "All three carbon–carbon bonds have equal length"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Between the same two atoms, bond length is governed by bond order: as the number of shared electron pairs increases, the bond becomes both stronger and shorter, so triple bonds are shorter than double bonds, which are shorter than single bonds. Drawing the Lewis structures shows that each carbon needs four bonds, so with fewer hydrogens available the carbons must share more electron pairs with each other. (Choice A) is incorrect: ethane, \(\text{C}_2\text{H}_6\), places three hydrogens on each carbon, leaving a single carbon–carbon bond (bond order 1); a single bond is the longest of the three, not the shortest, so this is the reversed choice. (Choice B) is incorrect: ethene, \(\text{C}_2\text{H}_4\), has two hydrogens per carbon and a carbon–carbon double bond (bond order 2), which is shorter than ethane''s single bond but still longer than a triple bond, making it an intermediate near-miss. (Choice C) is correct: ethyne, \(\text{C}_2\text{H}_2\), has only one hydrogen per carbon, forcing the carbons to share three electron pairs in a triple bond (bond order 3); the highest bond order gives the shortest carbon–carbon bond. (Choice D) is incorrect: the three molecules differ in bond order, so their carbon–carbon bonds cannot be equal in length; equal lengths would require equal bond order, as seen only in resonance-averaged bonds, which does not apply here. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship between bond order and bond length to Lewis structures you derive from the molecular formulas, rather than reading a value from a table.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '998931b7-8fd8-4cdd-b4c7-fe011ff9facb';
DELETE FROM question_distractor_metadata WHERE question_id = '998931b7-8fd8-4cdd-b4c7-fe011ff9facb';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('998931b7-8fd8-4cdd-b4c7-fe011ff9facb', 'A', 'reversed_relationship', 'picks lowest bond order as shortest, reversing the bond-order/bond-length rule'),
  ('998931b7-8fd8-4cdd-b4c7-fe011ff9facb', 'B', 'adjacent_fact', 'intermediate bond order, near-miss one step short of the shortest bond'),
  ('998931b7-8fd8-4cdd-b4c7-fe011ff9facb', 'D', 'misconception', 'believes C-C bonds are identical across molecules regardless of bond order');

-- [Ionic Character & Bond Type] ans=A medium skill2
UPDATE questions SET
  question_text = 'A common rule of thumb classifies a bond as ionic once the electronegativity difference \(\Delta\text{EN}\) between the two atoms exceeds about 1.7. A student applies this cutoff to the four substances below:

\(\text{HF}\) (H–F, \(\Delta\text{EN} = 1.9\)); \(\text{NH}_3\) (N–H, \(\Delta\text{EN} = 0.9\)); \(\text{MnI}_2\) (Mn–I, \(\Delta\text{EN} = 1.0\)); \(\text{CCl}_4\) (C–Cl, \(\Delta\text{EN} = 0.5\)).

For which substance does the \(\Delta\text{EN}\) cutoff give the wrong bond-type classification?',
  options = '[{"label": "A", "text": "\\(\\text{MnI}_2\\), because it is ionic even though its \\(\\Delta\\text{EN}\\) falls below the cutoff"}, {"label": "B", "text": "\\(\\text{HF}\\), because it is nonpolar even though its \\(\\Delta\\text{EN}\\) is above the cutoff"}, {"label": "C", "text": "\\(\\text{NH}_3\\), because it is ionic even though its \\(\\Delta\\text{EN}\\) is below the cutoff"}, {"label": "D", "text": "\\(\\text{CCl}_4\\), because it is polar covalent even though its \\(\\Delta\\text{EN}\\) is the smallest listed"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' The absolute value of \(\Delta\text{EN}\) is only a rough guide to bond type and has many exceptions; the more reliable predictor is the identity of the bonded atoms, since a bond between a metal and a nonmetal is typically ionic while a bond between two nonmetals is covalent. (Choice A) is correct: \(\text{MnI}_2\) has \(\Delta\text{EN} = 1.0\), which is below the 1.7 cutoff, so the rule of thumb would predict a covalent bond, yet manganese is a metal and iodine a nonmetal, so \(\text{MnI}_2\) is in fact ionic — the cutoff misclassifies it. (Choice B) is incorrect: \(\text{HF}\) does have \(\Delta\text{EN}\) above the cutoff, but H and F are both nonmetals and HF is polar covalent, not nonpolar; the bond is highly polar, so calling it nonpolar misstates the chemistry. (Choice C) is incorrect: \(\text{NH}_3\) contains two nonmetals with a modest \(\Delta\text{EN}\) of 0.9, so both the cutoff and the atom-type reasoning agree it is polar covalent, not ionic; there is no misclassification here. (Choice D) is incorrect: \(\text{CCl}_4\) has the smallest \(\Delta\text{EN}\), and the cutoff correctly classifies its C–Cl bonds as covalent (polar covalent), so the rule of thumb is not wrong for this substance. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that atom identity, not the \(\Delta\text{EN}\) value alone, determines ionic versus covalent character and detect the case where the numeric cutoff conflicts with the metal–nonmetal classification.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '24fcd73a-9876-4dc3-8a10-b7e3222ca536';
DELETE FROM question_distractor_metadata WHERE question_id = '24fcd73a-9876-4dc3-8a10-b7e3222ca536';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('24fcd73a-9876-4dc3-8a10-b7e3222ca536', 'B', 'misconception', 'confusing polar covalent with nonpolar'),
  ('24fcd73a-9876-4dc3-8a10-b7e3222ca536', 'C', 'misconception', 'assuming any polar bond becomes ionic'),
  ('24fcd73a-9876-4dc3-8a10-b7e3222ca536', 'D', 'partial_truth', 'smallest-value-must-be-the-exception');

-- [Octet Rule & Exceptions] ans=A medium skill2
UPDATE questions SET
  question_text = 'Sulfur forms the stable neutral molecule \(\text{SF}_6\), in which the central sulfur shares six bonding pairs (twelve electrons). A student wants to predict which other elements could serve as the central atom of an analogous stable neutral molecule \(\text{XF}_6\). For which of the following elements is such a molecule NOT expected to form?',
  options = '[{"label": "A", "text": "Oxygen"}, {"label": "B", "text": "Selenium"}, {"label": "C", "text": "Tellurium"}, {"label": "D", "text": "Xenon"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Forming \(\text{XF}_6\) requires the central atom to hold six bonding pairs (twelve electrons), an expanded octet. Second-period elements (\(n=2\)) have only four valence orbitals (one \(2s\) and three \(2p\)) and can therefore accommodate a maximum of eight valence electrons, so they cannot be hypervalent; elements in the third period and beyond (\(n\ge 3\)) have additional accessible orbitals and can share more than four pairs. (Choice A) is correct: oxygen is a second-period element limited to four valence orbitals and eight electrons, so it cannot expand its octet to hold the twelve electrons an \(\text{XF}_6\) molecule requires — no stable neutral \(\text{OF}_6\) forms. (Choice B) is incorrect: selenium sits directly below sulfur in the fourth period, has orbitals available beyond an octet, and forms \(\text{SeF}_6\), so it can serve as the central atom. (Choice C) is incorrect: tellurium is a fifth-period element that likewise exceeds an octet and forms \(\text{TeF}_6\), so a stable molecule is expected. (Choice D) is incorrect: even though xenon is a noble gas, it is a fifth-period element with orbitals to expand its valence shell and forms hypervalent fluorides such as \(\text{XeF}_6\), so it can be the central atom. This is a Scientific Reasoning and Problem Solving question because you must apply the principle that only elements in period 3 or higher can expand beyond an octet to a set of candidate central atoms, distinguishing them by period rather than by counting the electrons the stem already supplies.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'f38747a2-57a2-4094-aa0e-3bf37573f408';
DELETE FROM question_distractor_metadata WHERE question_id = 'f38747a2-57a2-4094-aa0e-3bf37573f408';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('f38747a2-57a2-4094-aa0e-3bf37573f408', 'B', 'misconception', 'believes a period-3+ element cannot expand its octet'),
  ('f38747a2-57a2-4094-aa0e-3bf37573f408', 'C', 'misconception', 'believes only sulfur (the stem element) can be hypervalent'),
  ('f38747a2-57a2-4094-aa0e-3bf37573f408', 'D', 'misconception', 'believes a noble gas cannot form covalent hypervalent fluorides');

-- [Lewis Structures] ans=B medium skill2
UPDATE questions SET
  question_text = 'The cyanate ion \(\text{OCN}^-\) can be drawn as a Lewis structure in which nitrogen is triple-bonded to carbon and carbon is single-bonded to oxygen: \([:\!\text{N}\!\equiv\!\text{C}\!-\!\ddot{\text{O}}\!:]^-\). In this structure the terminal oxygen carries three lone pairs and one single bond to carbon. What is the formal charge on that oxygen atom?',
  options = '[{"label": "A", "text": "\\(0\\)"}, {"label": "B", "text": "\\(-1\\)"}, {"label": "C", "text": "\\(+1\\)"}, {"label": "D", "text": "\\(-2\\)"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Formal charge is a bookkeeping tool calculated as the number of valence electrons on the neutral atom minus the nonbonding electrons minus the number of bonds to that atom: \(\text{FC} = V - N - B\). For the terminal oxygen in this cyanate structure, neutral oxygen has \(6\) valence electrons, the three lone pairs contribute \(6\) nonbonding electrons, and there is \(1\) single bond to carbon. (Choice B) is correct: applying the formula gives \(\text{FC} = 6 - 6 - 1 = -1\), which also matches the requirement that the formal charges over the whole ion must sum to the \(-1\) ionic charge (here N and C each carry \(0\)). (Choice A) is incorrect: a formal charge of \(0\) is what oxygen carries only when it has two lone pairs and two bonds (as in a neutral C=O), but here the single-bonded oxygen with three lone pairs has one extra nonbonding pair, making it electron-rich relative to neutral oxygen. (Choice C) is incorrect: \(+1\) reverses the sign of the bookkeeping — it would arise from subtracting valence electrons from the assigned electrons rather than the other way around, or from giving oxygen too few nonbonding electrons; oxygen here has more electrons than a neutral atom, so it must be negative, not positive. (Choice D) is incorrect: \(-2\) double-counts by treating the shared bonding pair as if both electrons belonged solely to oxygen (\(6 - 8 = -2\)); in formal-charge bookkeeping each atom is assigned only one electron from each bond, so the bond counts as \(1\), not \(2\). This is a Scientific Reasoning and Problem Solving question because you must apply the formal-charge formula to a specified Lewis structure rather than recall a memorized value.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'de376b50-fa62-4c15-9798-bfd3ee16e7c0';
DELETE FROM question_distractor_metadata WHERE question_id = 'de376b50-fa62-4c15-9798-bfd3ee16e7c0';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('de376b50-fa62-4c15-9798-bfd3ee16e7c0', 'A', 'misconception', 'assumes_neutral_default'),
  ('de376b50-fa62-4c15-9798-bfd3ee16e7c0', 'C', 'reversed_relationship', 'sign_reversal'),
  ('de376b50-fa62-4c15-9798-bfd3ee16e7c0', 'D', 'misconception', 'double_counts_bonding_pair');

-- [Octet Rule & Exceptions] ans=B medium skill2
UPDATE questions SET
  question_text = 'A student is classifying four neutral molecules by how many electrons surround the central atom in the preferred Lewis structure: \(\text{BF}_3\), \(\text{NH}_3\), \(\text{PCl}_5\), and \(\text{CO}_2\). In exactly one of these, the central atom is electron-deficient, holding fewer than eight electrons. Which molecule is it?',
  options = '[{"label": "A", "text": "\\(\\text{NH}_3\\), because nitrogen forms only three single bonds to hydrogen and no fourth bond."}, {"label": "B", "text": "\\(\\text{BF}_3\\), because boron forms three single bonds to fluorine and carries no lone pair."}, {"label": "C", "text": "\\(\\text{PCl}_5\\), because phosphorus forms five single bonds and thus breaks the octet rule."}, {"label": "D", "text": "\\(\\text{CO}_2\\), because each oxygen shares a double bond, leaving carbon short of an octet."}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Nature of molecules and intermolecular interactions.'' Exceptions to the octet rule fall into three textbook categories: electron-deficient central atoms (fewer than eight electrons, common for groups 2 and 13), hypervalent central atoms (more than eight, only possible for period-3 and heavier atoms), and odd-electron free radicals. Identifying the electron-deficient molecule requires counting the electrons around each central atom, not just noting that a structure looks unusual. (Choice B) is correct: in the preferred Lewis structure of \(\text{BF}_3\), boron forms three \(\text{B}-\text{F}\) single bonds and holds no lone pair, giving it only six electrons; experiment favors three single bonds over a double-bonded octet structure, so boron is genuinely electron-deficient, which is why \(\text{BF}_3\) acts as a strong Lewis acid. (Choice A) is incorrect: in \(\text{NH}_3\) nitrogen forms three \(\text{N}-\text{H}\) bonds and keeps one lone pair, which totals eight electrons, so nitrogen has a complete octet rather than a deficiency. (Choice C) is incorrect: \(\text{PCl}_5\) does violate the octet rule, but phosphorus holds ten electrons across five \(\text{P}-\text{Cl}\) bonds, so it is hypervalent (more than eight), not electron-deficient. (Choice D) is incorrect: the two \(\text{C}=\text{O}\) double bonds give carbon four shared pairs, which is exactly eight electrons, so carbon satisfies the octet rather than falling short of it. This is a Scientific Reasoning and Problem Solving question because you must apply the electron-counting rules for octet exceptions to distinguish an electron-deficient central atom from hypervalent and complete-octet cases.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'd735e1e6-5f13-4eb1-a1c6-96b145d24f8a';
DELETE FROM question_distractor_metadata WHERE question_id = 'd735e1e6-5f13-4eb1-a1c6-96b145d24f8a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d735e1e6-5f13-4eb1-a1c6-96b145d24f8a', 'A', 'misconception', 'assumes fewer bonds than four means an incomplete octet, ignoring the lone pair'),
  ('d735e1e6-5f13-4eb1-a1c6-96b145d24f8a', 'C', 'reversed_relationship', 'conflates octet violation by expansion (hypervalent) with deficiency'),
  ('d735e1e6-5f13-4eb1-a1c6-96b145d24f8a', 'D', 'misconception', 'miscounts double-bond electrons as leaving carbon below an octet');

COMMIT;
