-- General Chemistry Ch12: Electrochemistry — REMEDIATED (quality + scope sweep); grounded in OpenStax Atoms First 2e
-- Remediated 6/6 flagged questions in place (UPDATE by id, ids preserved). 6 re-engineered, 0 scope-flagged.
-- distractor_category mapped to the question_distractor_metadata CHECK set. Idempotent; safe to re-run.

BEGIN;

-- [Cell Diagram Notation] ans=A medium skill2
UPDATE questions SET
  question_text = 'A galvanic cell is represented by the cell diagram \(\text{Zn(s)}\,|\,\text{Zn}^{2+}\text{(aq)}\,||\,\text{Fe}^{3+}\text{(aq)},\ \text{Fe}^{2+}\text{(aq)}\,|\,\text{Pt(s)}\). Solid platinum appears as the electrode in the right half-cell, even though platinum does not appear anywhere in the overall cell reaction. Why must platinum be included in the notation for this half-cell?',
  options = '[{"label": "A", "text": "Both members of the right half-cell''s redox couple are dissolved species, so an inert conductor is needed to exchange electrons with them."}, {"label": "B", "text": "Platinum is more easily oxidized than iron, so it supplies the electrons that reduce the iron ions during cell operation."}, {"label": "C", "text": "Platinum catalyzes the transfer of electrons across the salt bridge that connects the two half-cells."}, {"label": "D", "text": "Platinum sets the right half-cell as the cathode, since the more noble metal is always written as the cathode."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' In cell notation, each half-cell must end in an electrode: a solid, electrically conductive phase distinct from the solution where electrons enter or leave the cell. When a half-cell''s redox couple includes a solid metal (like the \(\text{Zn}^{2+}/\text{Zn}\) couple on the left), that metal serves as an active electrode. But when neither member of the couple can serve as an electrode, an inert electrode such as \(\text{Pt}\) is required. (Choice A) is correct: in the right half-cell, both \(\text{Fe}^{3+}\) and \(\text{Fe}^{2+}\) are aqueous solute species, so neither can be the solid conductive electrode; platinum is added as an inert electrode that simply provides or accepts electrons to and from the dissolved redox couple without participating in the reaction. (Choice B) is incorrect: platinum is chemically inert here and is not oxidized; the electrons that reduce \(\text{Fe}^{3+}\) come from the zinc anode through the external circuit, not from the platinum. (Choice C) is incorrect: electrons never travel through the salt bridge, which conducts only ions to maintain charge balance, so platinum cannot catalyze electron transfer there; its role is to conduct electrons between the external wire and the dissolved couple. (Choice D) is incorrect: an electrode''s role as anode or cathode is fixed by the relative reduction potentials and the left-to-right anode-to-cathode convention of the diagram, not by choosing the more noble metal; platinum is present because the couple is entirely in solution, not to assign the cathode. This is a Scientific Reasoning and Problem Solving question because you must apply the cell-notation conventions for active versus inert electrodes to a novel half-cell in which both members of the redox couple are dissolved species.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '4f89a87d-d7ef-47a1-a63d-0d98f440e734';
DELETE FROM question_distractor_metadata WHERE question_id = '4f89a87d-d7ef-47a1-a63d-0d98f440e734';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('4f89a87d-d7ef-47a1-a63d-0d98f440e734', 'B', 'misconception', 'treats inert electrode as a reactive participant'),
  ('4f89a87d-d7ef-47a1-a63d-0d98f440e734', 'C', 'misconception', 'believes electrons flow through the salt bridge'),
  ('4f89a87d-d7ef-47a1-a63d-0d98f440e734', 'D', 'reversed_relationship', 'assigns electrode role from nobility instead of potentials/convention');

-- [Batteries] ans=A medium skill2
UPDATE questions SET
  question_text = 'Two zinc-carbon dry cells of the same design—a large D cell and a small AAA cell—are each connected to an identical small motor. A voltmeter reads about 1.5 V across each cell, yet the D cell keeps its motor running many times longer than the AAA cell before the motor stops. Which statement best accounts for both observations?',
  options = '[{"label": "A", "text": "Both cells read about 1.5 V because voltage is set by their shared redox chemistry, and the D cell lasts longer because its larger size holds more reactant and can deliver more total charge."}, {"label": "B", "text": "The D cell reads about 1.5 V only at rest but supplies a higher voltage once current is drawn, and this higher operating voltage is what makes it last longer."}, {"label": "C", "text": "The D cell has a higher cell potential because its larger electrodes and greater amount of reactant raise the voltage, which is why it stores more energy and lasts longer."}, {"label": "D", "text": "Both cells hold the same total charge because they share the same chemistry, and the D cell lasts longer only because the AAA cell has greater internal resistance."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' The voltage (cell potential) of a battery is fixed by the standard reduction potentials of the two half-reactions in its redox couple, so it does not depend on how large the cell is; all sizes of a given dry cell (AAA, AA, C, D) use the same components and therefore exhibit the same voltage of about 1.5 V. What changes with size is the amount of reactant: a larger cell packs in more of the redox reactants and can therefore transfer correspondingly more total charge before the reaction is exhausted. (Choice A) is correct: because both cells run the same zinc/manganese(IV) oxide chemistry, both produce the same ~1.5 V regardless of size, and the D cell outlasts the AAA cell because its greater mass of reactant lets it deliver more total charge. (Choice B) is incorrect: cell voltage is an intensive property set by the redox couple and does not rise when current is drawn—if anything, real cells sag slightly under load—so a larger cell does not operate at a higher voltage. (Choice C) is incorrect: adding more of the same reactant or using larger electrodes increases capacity, not cell potential; the potential is fixed by the identity of the half-reactions, which is why the voltmeter reads the same ~1.5 V for both cells. (Choice D) is incorrect: the two cells do not hold the same total charge—capacity scales with the amount of reactant, so the physically larger D cell stores far more charge; internal resistance affects how much current a cell can supply, not how long it lasts on the same small load. This is a Scientific Reasoning and Problem Solving question because you must apply the distinction that battery voltage is set by the redox chemistry (intensive) while total charge capacity is set by the quantity of reactant (extensive) to explain equal voltage but unequal lifetime.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '5f6a316b-b532-4b98-b4f1-14485ff7988a';
DELETE FROM question_distractor_metadata WHERE question_id = '5f6a316b-b532-4b98-b4f1-14485ff7988a';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('5f6a316b-b532-4b98-b4f1-14485ff7988a', 'B', 'misconception', 'believes cell voltage rises with size or under load'),
  ('5f6a316b-b532-4b98-b4f1-14485ff7988a', 'C', 'misconception', 'assumes more reactant or bigger electrodes raise cell potential'),
  ('5f6a316b-b532-4b98-b4f1-14485ff7988a', 'D', 'reversed_relationship', 'treats capacity as independent of cell size, blaming internal resistance');

-- [Standard Reduction Potentials] ans=A medium skill2
UPDATE questions SET
  question_text = 'A galvanic cell is constructed from a nickel electrode in \(\text{Ni}^{2+}(aq)\) and a zinc electrode in \(\text{Zn}^{2+}(aq)\), both under standard conditions. The relevant standard reduction potentials are \(\text{Ni}^{2+}(aq) + 2e^- \rightarrow \text{Ni}(s)\), \(E^{\circ}_{\text{red}} = -0.26\ \text{V}\) and \(\text{Zn}^{2+}(aq) + 2e^- \rightarrow \text{Zn}(s)\), \(E^{\circ}_{\text{red}} = -0.76\ \text{V}\). What is the standard cell potential, \(E^{\circ}_{\text{cell}}\), for the spontaneous cell reaction?',
  options = '[{"label": "A", "text": "\\(+0.50\\ \\text{V}\\)"}, {"label": "B", "text": "\\(-0.50\\ \\text{V}\\)"}, {"label": "C", "text": "\\(-1.02\\ \\text{V}\\)"}, {"label": "D", "text": "\\(+1.02\\ \\text{V}\\)"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' In a galvanic cell the electrode with the more positive (greater) standard reduction potential serves as the cathode, and the standard cell potential is found from \(E^{\circ}_{\text{cell}} = E^{\circ}_{\text{cathode}} - E^{\circ}_{\text{anode}}\), using the tabulated reduction potentials directly without flipping any signs by hand. Here \(\text{Ni}^{2+}/\text{Ni}\) (\(-0.26\ \text{V}\)) is more positive than \(\text{Zn}^{2+}/\text{Zn}\) (\(-0.76\ \text{V}\)), so nickel is the cathode and zinc is the anode. (Choice A) is correct: \(E^{\circ}_{\text{cell}} = E^{\circ}_{\text{cathode}} - E^{\circ}_{\text{anode}} = (-0.26\ \text{V}) - (-0.76\ \text{V}) = +0.50\ \text{V}\), a positive value consistent with the spontaneous galvanic process. (Choice B) is incorrect: \(-0.50\ \text{V}\) results from reversing the cathode and anode assignments, computing \(E^{\circ}_{\text{anode}} - E^{\circ}_{\text{cathode}}\); this is the potential of the reverse (nonspontaneous) reaction, not the spontaneous galvanic cell. (Choice C) is incorrect: \(-1.02\ \text{V}\) comes from adding the two reduction potentials, \((-0.26) + (-0.76)\), instead of subtracting anode from cathode, a common error that ignores that only the anode half-reaction is reversed. (Choice D) is incorrect: \(+1.02\ \text{V}\) results from adding the magnitudes of the two potentials, \(0.26 + 0.76\), which mishandles the signs of both reduction potentials. This is a Scientific Reasoning and Problem Solving question because you must apply the relationship \(E^{\circ}_{\text{cell}} = E^{\circ}_{\text{cathode}} - E^{\circ}_{\text{anode}}\), first identifying the cathode as the couple with the more positive reduction potential and then combining the tabulated values with correct signs.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '3329ff20-bab3-4293-a431-e4728123a487';
DELETE FROM question_distractor_metadata WHERE question_id = '3329ff20-bab3-4293-a431-e4728123a487';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('3329ff20-bab3-4293-a431-e4728123a487', 'B', 'reversed_relationship', 'swapped cathode and anode in the cell potential formula'),
  ('3329ff20-bab3-4293-a431-e4728123a487', 'C', 'misconception', 'added reduction potentials instead of subtracting anode from cathode'),
  ('3329ff20-bab3-4293-a431-e4728123a487', 'D', 'misconception', 'added magnitudes, mishandling the signs of the reduction potentials');

-- [Cell Potential & EMF] ans=B hard skill2
UPDATE questions SET
  question_text = 'A concentration cell is built from two copper half-cells, each a \(\text{Cu}(s)\) electrode dipped in aqueous \(\text{Cu}^{2+}\), joined by a salt bridge. Half-cell 1 contains \([\text{Cu}^{2+}] = 1.0\ \text{M}\) and half-cell 2 contains \([\text{Cu}^{2+}] = 1.0\times10^{-3}\ \text{M}\); the relevant reduction is \(\text{Cu}^{2+} + 2e^- \rightarrow \text{Cu}(s)\). Using the Nernst equation \(E_{\text{cell}} = E^{\circ}_{\text{cell}} - \frac{0.0592}{n}\log Q\) at 298 K, what is the cell potential \(E_{\text{cell}}\)?',
  options = '[{"label": "A", "text": "\\(0\\ \\text{V}\\)"}, {"label": "B", "text": "\\(+0.089\\ \\text{V}\\)"}, {"label": "C", "text": "\\(-0.089\\ \\text{V}\\)"}, {"label": "D", "text": "\\(+0.18\\ \\text{V}\\)"}]'::jsonb,
  correct_answer = 'B',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' In a concentration cell both half-cells use the same electrode and the same redox couple, so the two standard reduction potentials are identical and \(E^{\circ}_{\text{cell}} = 0\ \text{V}\); the entire measured potential arises from the concentration difference and must be found with the Nernst equation. The cell runs spontaneously in the direction that equalizes the two concentrations: \(\text{Cu}^{2+}\) is reduced in the concentrated half-cell (the cathode, where \([\text{Cu}^{2+}]\) falls) and \(\text{Cu}\) is oxidized in the dilute half-cell (the anode, where \([\text{Cu}^{2+}]\) rises). The reaction quotient is \(Q = \frac{[\text{Cu}^{2+}]_{\text{anode}}}{[\text{Cu}^{2+}]_{\text{cathode}}} = \frac{1.0\times10^{-3}}{1.0} = 1.0\times10^{-3}\), with \(n = 2\). (Choice B) is correct: \(E_{\text{cell}} = 0 - \frac{0.0592}{2}\log(1.0\times10^{-3}) = -0.0296(-3) = +0.089\ \text{V}\), a small positive value consistent with the spontaneous concentration-driven process. (Choice A) is incorrect: it assumes that because both electrodes are copper with identical \(E^{\circ}\), the cell potential must be zero; this ignores that a difference in ion concentration creates a real, nonzero potential through the \(\log Q\) term of the Nernst equation. (Choice C) is incorrect: \(-0.089\ \text{V}\) results from inverting the reaction quotient (placing the concentrated half-cell over the dilute one) or assigning the concentrated half-cell as the anode; a concentration cell is always spontaneous as written, so a negative potential signals a reversed assignment. (Choice D) is incorrect: \(+0.18\ \text{V}\) comes from using \(n = 1\) instead of \(n = 2\) in the Nernst prefactor (\(\frac{0.0592}{1}\times 3\)), the wrong electron count for the \(\text{Cu}^{2+}/\text{Cu}\) couple. This is a Scientific Reasoning and Problem Solving question because you must apply the Nernst equation to a concentration cell—recognizing \(E^{\circ}_{\text{cell}} = 0\), assigning cathode and anode from the concentrations, constructing \(Q\), and using \(n = 2\)—rather than reading a value from a table.',
  difficulty = 'hard',
  cognitive_skill = 2
WHERE id = 'bf7d8e7d-0f7d-4f4c-abee-739a12428e1d';
DELETE FROM question_distractor_metadata WHERE question_id = 'bf7d8e7d-0f7d-4f4c-abee-739a12428e1d';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('bf7d8e7d-0f7d-4f4c-abee-739a12428e1d', 'A', 'misconception', 'identical-electrodes-imply-zero-potential'),
  ('bf7d8e7d-0f7d-4f4c-abee-739a12428e1d', 'C', 'reversed_relationship', 'inverted-Q-or-swapped-electrodes'),
  ('bf7d8e7d-0f7d-4f4c-abee-739a12428e1d', 'D', 'misconception', 'wrong-electron-count-in-Nernst');

-- [Batteries] ans=A medium skill2
UPDATE questions SET
  question_text = 'During normal use, a nickel-cadmium (Ni-Cd) cell discharges spontaneously to power a device. When the cell is later connected to a charger, it is restored to its original state. Which statement best describes the cell while it is being charged?',
  options = '[{"label": "A", "text": "It operates as an electrolytic cell, with an external source driving the non-spontaneous reverse reaction."}, {"label": "B", "text": "It operates as a galvanic cell, releasing free energy as the spontaneous discharge reaction continues."}, {"label": "C", "text": "It operates as a concentration cell, with the charger equalizing ion concentrations between the two electrodes."}, {"label": "D", "text": "It operates as a fuel cell, with the charger supplying fresh reactants to the electrodes as they are consumed."}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' A secondary (rechargeable) cell such as a Ni-Cd cell discharges spontaneously, functioning as a galvanic cell with \(E_{\text{cell}}>0\) and \(\Delta G<0\). Recharging requires running that same chemistry in reverse, which is non-spontaneous (\(E_{\text{cell}}<0\), \(\Delta G>0\)), so it cannot happen on its own; an external power source must supply energy to force it. (Choice A) is correct: during charging the external source drives current backward against the cell''s spontaneous tendency, regenerating the discharge reactants — this is precisely how an electrolytic cell operates, so the cell is functioning electrolytically while charging. (Choice B) is incorrect: the galvanic (spontaneous) mode is what happens during discharge; if charging were simply the spontaneous reaction continuing, the cell would keep draining rather than being restored, and no external source would be needed. (Choice C) is incorrect: a concentration cell generates voltage from a difference in ion concentration between two otherwise identical half-cells, which is unrelated to how a Ni-Cd cell is recharged — the charger reverses redox reactions at chemically distinct cadmium and nickel electrodes, it does not merely equalize concentrations. (Choice D) is incorrect: a fuel cell continuously receives fuel and oxidant fed from outside and is not recharged; a Ni-Cd cell holds a fixed amount of reactant that is regenerated in place by reversing the reaction, not replenished by new reactants from the charger. This is a Scientific Reasoning and Problem Solving question because you must apply the distinction between spontaneous galvanic operation and forced electrolytic operation to determine what mode the cell is in during charging.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '398d8548-0356-4b45-9c83-9bf859f2d168';
DELETE FROM question_distractor_metadata WHERE question_id = '398d8548-0356-4b45-9c83-9bf859f2d168';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('398d8548-0356-4b45-9c83-9bf859f2d168', 'B', 'misconception', 'conflates charging with discharge (both spontaneous)'),
  ('398d8548-0356-4b45-9c83-9bf859f2d168', 'C', 'adjacent_fact', 'applies concentration-cell concept where it does not belong'),
  ('398d8548-0356-4b45-9c83-9bf859f2d168', 'D', 'adjacent_fact', 'confuses recharging with fuel-cell reactant feeding');

-- [Free Energy & Cell Potential] ans=A medium skill2
UPDATE questions SET
  question_text = 'Under standard conditions, the overall reaction in a hydrogen–oxygen fuel cell, \(2\,\text{H}_2(g) + \text{O}_2(g) \rightarrow 2\,\text{H}_2\text{O}(l)\), has a standard Gibbs free energy change of \(\Delta G^{\circ} = -474\ \text{kJ/mol}\) and transfers \(n = 4\) moles of electrons per mole of reaction as written. Using \(F = 96{,}485\ \text{C/mol e}^-\), what is the standard cell potential, \(E^{\circ}_{\text{cell}}\), for this cell?',
  options = '[{"label": "A", "text": "\\(E^{\\circ}_{\\text{cell}} \\approx +1.23\\ \\text{V}\\)"}, {"label": "B", "text": "\\(E^{\\circ}_{\\text{cell}} \\approx -1.23\\ \\text{V}\\)"}, {"label": "C", "text": "\\(E^{\\circ}_{\\text{cell}} \\approx +2.46\\ \\text{V}\\)"}, {"label": "D", "text": "\\(E^{\\circ}_{\\text{cell}} \\approx +4.91\\ \\text{V}\\)"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a General Chemistry question that falls under the content category ''Electrochemistry (GC).'' The standard free energy change and the standard cell potential are linked by \(\Delta G^{\circ} = -nFE^{\circ}_{\text{cell}}\), so solving for the potential gives \(E^{\circ}_{\text{cell}} = -\Delta G^{\circ}/(nF)\). Because \(\Delta G^{\circ}\) is negative for a spontaneous cell, the leading negative sign makes \(E^{\circ}_{\text{cell}}\) positive, and the number of moles of electrons transferred, \(n\), must be carried correctly through the denominator. (Choice A) is correct: \(E^{\circ}_{\text{cell}} = -(-474{,}000\ \text{J/mol})/[(4)(96{,}485\ \text{C/mol e}^-)] = 474{,}000/385{,}940 = +1.23\ \text{V}\), a positive value consistent with the spontaneous, galvanic operation of a fuel cell. (Choice B) is incorrect: this reverses the sign by dropping the leading negative in \(E^{\circ}_{\text{cell}} = -\Delta G^{\circ}/(nF)\) and computing \(\Delta G^{\circ}/(nF)\) directly; a negative potential would indicate a nonspontaneous reaction, contradicting the negative \(\Delta G^{\circ}\) given. (Choice C) is incorrect: this uses \(n = 2\) instead of \(n = 4\), a common error from miscounting the electrons transferred, which doubles the potential to \(474{,}000/[(2)(96{,}485)] \approx 2.46\ \text{V}\). (Choice D) is incorrect: this omits \(n\) entirely, applying \(E^{\circ}_{\text{cell}} = -\Delta G^{\circ}/F\) and yielding \(474{,}000/96{,}485 \approx 4.91\ \text{V}\); the moles of electrons transferred must appear in the denominator. This is a Scientific Reasoning and Problem Solving question because you must apply the relation \(\Delta G^{\circ} = -nFE^{\circ}_{\text{cell}}\), rearrange it for \(E^{\circ}_{\text{cell}}\), and correctly track both the sign of \(\Delta G^{\circ}\) and the value of \(n\).',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = '60cdcd41-5625-4e00-a70f-e228923b61ab';
DELETE FROM question_distractor_metadata WHERE question_id = '60cdcd41-5625-4e00-a70f-e228923b61ab';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('60cdcd41-5625-4e00-a70f-e228923b61ab', 'B', 'misconception', 'sign-error: drops the leading negative when rearranging deltaG = -nFE, wrongly giving a spontaneous cell a negative potential'),
  ('60cdcd41-5625-4e00-a70f-e228923b61ab', 'C', 'misconception', 'wrong-n: uses n=2 instead of the correct n=4 electrons transferred'),
  ('60cdcd41-5625-4e00-a70f-e228923b61ab', 'D', 'misconception', 'omitted-variable: drops n from the denominator, using E = -deltaG/F');

COMMIT;
