-- ════════════════════════════════════════════════════════════════════
-- Question stem fixes — 2026-07-15: DUPLICATED-OPTIONS bug
-- Older authoring artifact: the four A/B/C/D options were baked into question_text AND stored
-- in the options JSONB, so they rendered twice. Fix strips the inline block from the stem only
-- (options JSONB + correct_answer unchanged). 12 questions across 4 chapters.
-- IDEMPOTENT: UPDATE-by-id with current production question_text; preserves question ids
-- (student answer-history stays linked). Safe to re-run.
-- ════════════════════════════════════════════════════════════════════

BEGIN;

-- ── Amino Acids, Peptides, and Proteins ──
UPDATE questions SET question_text = 'A researcher purifies an intact 40-residue polypeptide and attempts to determine its sequence by Edman degradation. Amino acid composition analysis confirms the protein is full-length and undegraded, yet the very first cycle of the procedure releases no identifiable PTH-amino acid. Which feature of the polypeptide best explains this result?' WHERE id = '1528fdcc-1d62-4484-ac59-bab7f1d2b936';
UPDATE questions SET question_text = 'A typical aspartate side chain exposed to solvent on a protein''s surface has a carboxyl pKa near 4. In one enzyme, however, an aspartate residue packed into the protein''s hydrophobic core is measured to have a pKa near 9, meaning it stays protonated (neutral) across most of the physiological pH range. Which effect of the nonpolar microenvironment best explains this elevated pKa?' WHERE id = 'cfe53a9a-ebd4-4433-9aa0-735ca9249c72';
-- ── Carbohydrate Structure and Function ──
UPDATE questions SET question_text = 'A chemist synthesizes methyl α-D-glucopyranoside by reacting D-glucose with methanol under acidic conditions. In the product, the ring carbon that was the anomeric center in free glucose now bears the ring oxygen and a newly attached methoxy (–OCH₃) group, with no hydroxyl group remaining on that carbon. A sample of this product is added to hot Benedict''s reagent (a mild Cu²⁺ oxidizing solution). What is the most likely outcome, and why?' WHERE id = '427f5633-8161-4d69-bc26-a4c9f671499b';
UPDATE questions SET question_text = 'D-glucose and D-mannose are two aldohexoses that can be interconverted in the laboratory by inverting the configuration at a single carbon while leaving every other carbon untouched. A student examining this transformation wants to classify the relationship between the two sugars. Which set of stereochemical labels correctly describes the D-glucose/D-mannose pair?' WHERE id = '490f4d84-303a-4964-96e5-2980a2fd4f40';
UPDATE questions SET question_text = 'A student mixes three separate disaccharide solutions with Benedict''s reagent and heats each tube. She has been told only how each disaccharide is assembled: in the first, the C1 of one glucose is bonded to the C4 of a second glucose; in the second, the C1 of galactose is bonded to the C4 of glucose; and in the third, the C1 of glucose is bonded to the C2 of fructose. One tube fails to produce the brick-red precipitate that signals a positive result. Which disaccharide gives the negative result, and what accounts for it?' WHERE id = '5483a0f3-90ab-4755-9e00-7ffb05801261';
UPDATE questions SET question_text = 'A chemist dissolves D-glucose in excess anhydrous methanol and adds a trace of dry HCl. Under these conditions, methanol reacts selectively at the anomeric carbon of the glucopyranose ring, and the product is isolated after the reaction reaches completion. Which description correctly characterizes the functional-group change at the anomeric carbon and the small molecule, if any, that is released?' WHERE id = '5d5a6aa6-5f14-4a42-8aa9-1ab6d3b8433e';
UPDATE questions SET question_text = 'A chemist dissolves crystals of pure α-D-glucopyranose in water and immediately begins tracking the solution''s observed optical rotation with a polarimeter. Over the next hour the reading drifts steadily and then holds constant at a value between those of the two pure anomers. In a second trial, the chemist first converts the same glucose to methyl α-D-glucopyranoside (the anomeric hydroxyl replaced by a methoxy group), dissolves it, and again monitors the rotation. Which outcome should the chemist predict for the second trial, and why?' WHERE id = '621f9db6-c3c9-4150-bde5-d8fa93729938';
UPDATE questions SET question_text = 'A chemist dissolves freshly prepared methyl α-D-glucopyranoside — glucose whose anomeric hydroxyl has been converted to a methyl glycoside — in water. Over several hours she monitors the solution''s optical rotation and finds that it does not drift toward a stable intermediate value, remaining fixed at the rotation of the α form. She then heats an aliquot with a mild cupric ion test reagent and observes no brick-red precipitate. Which single feature of this molecule accounts for BOTH the constant optical rotation and the failure of the copper test?' WHERE id = '85937471-0bd2-4c97-b231-aec0db81ba1d';
UPDATE questions SET question_text = 'A researcher treats a solution of D-glucose with a mild reducing agent that converts the molecule''s single carbonyl carbon into a hydroxyl-bearing carbon, yielding an acyclic hexahydroxy product. When this product is dissolved in fresh water and its behavior is compared with that of ordinary D-glucose, which property that glucose displays is NOT observed for the product?' WHERE id = '8b6ad828-b9c9-4d7f-a5d9-a2d543949aa0';
UPDATE questions SET question_text = 'The figure above shows two cyclic representations of D-glucose, labeled structure A and structure B. A student compares the two Haworth projections carbon by carbon and finds that they are identical at every ring position except one. Based on the location of the single point of difference between structures A and B, how are the two structures best classified?' WHERE id = 'ca543e7d-7a60-4221-880a-f9d78ec308ee';
-- ── Non-enzymatic Protein Function and Protein Analysis ──
UPDATE questions SET question_text = 'A purification protocol calls for capturing a recombinant enzyme (isoelectric point pI = 9.4) directly from a clarified cell lysate. The technician equilibrates a chromatography column and loads the sample in a buffer held at pH 7.4, then washes with several column volumes of the same low-salt buffer. To ensure the enzyme is retained on the resin (rather than washing straight through with the flow-through fraction), which resin should the technician have packed into the column?' WHERE id = '151b0406-aaa8-4041-bd5a-0ba5f89df3e1';
-- ── The Musculoskeletal System ──
UPDATE questions SET question_text = 'An isolated skeletal muscle is stimulated at a fixed 15 Hz. The myogram shows tension rising to about twice a single twitch, but the trace still oscillates and dips partway toward baseline between stimuli. Without changing the stimulus frequency, a researcher then applies a drug that partially inhibits the sarcoplasmic reticulum \(\text{Ca}^{2+}\) pump. How is the myogram most likely to change, and why?' WHERE id = '4030b821-2be9-4416-b26f-174770ed5101';

COMMIT;
