-- Readback remediation (round-2 stubborn cases) — REMEDIATED; grounded in per-topic textbooks
-- Remediated 3/3 flagged questions in place (UPDATE by id, ids preserved). 3 re-engineered, 0 scope-flagged.
-- distractor_category mapped to the question_distractor_metadata CHECK set. Idempotent; safe to re-run.

BEGIN;

-- [Active Site, Lock-and-Key & Induced Fit] ans=A medium skill2
UPDATE questions SET
  question_text = 'A biochemist characterizes two purified enzymes, X and Y, that catalyze the same reaction on the same small-molecule substrate. Using X-ray crystallography, she solves each enzyme''s structure both alone (free) and bound to substrate. Enzyme X has an identical active-site geometry in its free and substrate-bound structures. Enzyme Y''s active site is measurably more open in the free structure and closes down around the substrate in the bound structure, and only in that closed form do several catalytic residues come into contact with the bond being broken. Based on these observations, which prediction is best supported?',
  options = '[{"label": "A", "text": "Enzyme Y''s substrate binding is coupled to a conformational change that positions catalytic residues, so mutations that stiffen its active site into the open form would impair catalysis even if substrate still binds"}, {"label": "B", "text": "Enzyme X must be the faster catalyst of the two, because an active site whose geometry never changes commits none of the binding energy to reshaping the protein"}, {"label": "C", "text": "Enzyme Y cannot achieve true substrate specificity, because an active site that changes shape will close around almost any small molecule that enters it"}, {"label": "D", "text": "Enzyme X relies on a transition-state intermediate to bind its substrate, whereas enzyme Y binds its substrate directly in a single rigid step"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biochemistry question that falls under the content category ''Structure and Function of Proteins and Their Constituent Amino Acids.'' Enzyme shape determines substrate binding and catalysis: in one mode of binding the reactant fits the active site with no change to enzyme shape, while in the other, contact between the reactant and the protein changes the protein''s shape so that the closed form can position residues to convert substrate to product (LibreTexts 730-742). The crystallography shows enzyme X''s site is unchanged on binding (a rigid, preformed site) and enzyme Y''s site closes around the substrate, bringing catalytic residues to the reacting bond — the flexible closure is not decorative but is what assembles the functional catalytic geometry. (Choice A) is correct: because enzyme Y''s catalytic residues only reach the scissile bond in the closed, substrate-induced conformation, a mutation that locks the site open would leave those residues out of position; the enzyme could still bind substrate yet fail to catalyze efficiently, which is exactly what the data (catalytic contacts form only in the closed form) predict. (Choice B) is incorrect: nothing in the data ties an unchanging active site to faster turnover, and the reasoning is spurious — a rigid site is not inherently faster, and enzyme Y''s induced closure is what organizes catalysis, so a rigid enzyme is not guaranteed to out-run a flexible one. (Choice C) is incorrect: a shape-changing site does not abolish specificity; selectivity comes from which ligands can productively trigger and stabilize the closed, catalytically competent conformation, not merely from whether the site can move, so ''closes around almost anything'' does not follow. (Choice D) is incorrect: it inverts the roles — the enzyme that reshapes around its substrate (Y) is the one whose closure enables transition-state chemistry, whereas the rigid enzyme (X) binds without a shape change; the option assigns transition-state dependence to the wrong enzyme. This is a Scientific Reasoning and Problem Solving question because you must apply the structural criterion distinguishing the two binding modes to crystallographic data and predict a functional consequence of disrupting a substrate-induced conformational change.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'c8f6b0d4-23af-4a8e-a01d-f6c9ed2e25c5';
DELETE FROM question_distractor_metadata WHERE question_id = 'c8f6b0d4-23af-4a8e-a01d-f6c9ed2e25c5';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('c8f6b0d4-23af-4a8e-a01d-f6c9ed2e25c5', 'B', 'misconception', 'rigid-equals-faster leap'),
  ('c8f6b0d4-23af-4a8e-a01d-f6c9ed2e25c5', 'C', 'misconception', 'flexibility-destroys-specificity misconception'),
  ('c8f6b0d4-23af-4a8e-a01d-f6c9ed2e25c5', 'D', 'reversed_relationship', 'transition-state role assigned to the wrong enzyme');

-- [Types of Elements] ans=C medium skill2
UPDATE questions SET
  question_text = 'Four newly isolated elements were characterized in the lab, and their measured properties are summarized below:

- Element W: shiny surface; can be hammered into thin sheets; electrical conductivity ~6 × 10⁷ S/m (comparable to copper).
- Element X: dull, brittle solid that shatters when struck; electrical conductivity ~1 × 10⁻¹⁰ S/m; forms an acidic oxide.
- Element Y: metallic-gray sheen but brittle; electrical conductivity ~1 × 10³ S/m that rises sharply when the sample is warmed; used experimentally in a transistor.
- Element Z: soft, shiny solid that dents easily; electrical conductivity ~1 × 10⁷ S/m; reacts vigorously with water to give a basic solution.

On a periodic table, which single element would be positioned directly on the metalloid "staircase" rather than to one side of it?',
  options = '[{"label": "A", "text": "Element W"}, {"label": "B", "text": "Element X"}, {"label": "C", "text": "Element Y"}, {"label": "D", "text": "Element Z"}]'::jsonb,
  correct_answer = 'C',
  explanation = 'This is a General Chemistry question that falls under the content category ''The Periodic Table: Classification of Elements Into Groups by Electronic Structure.'' Elements are sorted into three classes by their physical behavior: metals are shiny, malleable, and excellent conductors of heat and electricity; nonmetals are dull, brittle, and poor conductors; and metalloids conduct only moderately and share some properties of each, so they occupy the stepped diagonal ''staircase'' with metals to its left and nonmetals to its right. A defining fingerprint of a metalloid (a semiconductor such as Si, Ge, or As) is an intermediate conductivity that increases with temperature, unlike a true metal, whose conductivity falls slightly as it warms. (Choice A) is incorrect: Element W is lustrous, malleable, and conducts as well as copper, making it a metal that sits well to the left of the staircase, not on it. (Choice B) is incorrect: Element X is dull, brittle, an insulator (~10⁻¹⁰ S/m), and forms an acidic oxide—these are nonmetal traits placing it to the right of the staircase. (Choice C) is correct: Element Y has a metallic sheen yet is brittle, conducts only moderately (~10³ S/m), and that conductivity rises when warmed and enables transistor behavior—the semiconductor signature of a metalloid, the class that lies along the staircase itself. (Choice D) is incorrect: Element Z is soft, shiny, highly conductive, and reacts with water to form a base, which are the hallmarks of a reactive metal (an alkali or alkaline earth metal) far to the left of the staircase, not on it. This is a Scientific Reasoning and Problem Solving question because you must apply the property criteria that define metals, metalloids, and nonmetals to quantitative and behavioral data and then translate that classification into a position relative to the metalloid staircase.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'd40dc1c9-79ed-4c07-8cbd-9a4f25dbdced';
DELETE FROM question_distractor_metadata WHERE question_id = 'd40dc1c9-79ed-4c07-8cbd-9a4f25dbdced';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('d40dc1c9-79ed-4c07-8cbd-9a4f25dbdced', 'A', 'misconception', 'treats any lustrous, highly conductive element as belonging on the staircase'),
  ('d40dc1c9-79ed-4c07-8cbd-9a4f25dbdced', 'B', 'misconception', 'confuses a poorly conducting nonmetal with a metalloid because both can be brittle solids'),
  ('d40dc1c9-79ed-4c07-8cbd-9a4f25dbdced', 'D', 'adjacent_fact', 'selects a reactive metal by focusing on shine/softness rather than the moderate, temperature-dependent conductivity that defines a metalloid');

-- [Bacterial Shapes] ans=A medium skill2
UPDATE questions SET
  question_text = 'A researcher characterizes two bacterial isolates. Isolate 1 is spherical and Isolate 2 is spiral, yet 16S rRNA sequencing places both in the same bacterial phylum. In a separate experiment, the researcher treats a normally rod-shaped isolate with a compound that blocks peptidoglycan cross-linking during growth; over several generations, the descendants lose their elongated form and become nearly round. Which conclusion is best supported by these two observations together?',
  options = '[{"label": "A", "text": "Cell shape is imposed by the cell wall rather than by phylogeny, so an intact wall is required to maintain a non-spherical form and members of one phylum can differ in shape"}, {"label": "B", "text": "Cell shape is a reliable marker of evolutionary relationship, so the sequencing result that grouped a spherical and a spiral cell in one phylum most likely reflects a contamination or identification error"}, {"label": "C", "text": "Cell shape is set by the plasma membrane, so blocking peptidoglycan cross-linking altered the rod''s shape only indirectly by first destabilizing its membrane"}, {"label": "D", "text": "Cell shape is determined by the cell''s DNA content, so the rounding of the treated rods reflects loss of chromosomal material rather than any change to the wall"}]'::jsonb,
  correct_answer = 'A',
  explanation = 'This is a Biology question that falls under the content category ''Prokaryotes and Viruses (BIO).'' OpenStax Biology states that most prokaryotes have a cell wall that "functions as a protective layer, and it is responsible for the organism''s shape," and separately notes that "bacterial shape is not phylum-dependent; bacteria within a phylum may be cocci, rod-shaped, or spiral." Peptidoglycan cross-linking builds the bacterial cell wall, so a compound that blocks it degrades the wall''s ability to hold a non-spherical form. (Choice A) is correct: both observations point to the wall, not ancestry, as the shape-determining structure — a spherical and a spiral cell can share a phylum because shape is not phylum-dependent, and blocking peptidoglycan cross-linking removes the wall''s shaping constraint so a rod collapses toward a sphere, showing an intact wall is needed to sustain an elongated shape. (Choice B) is incorrect: it treats shape as a dependable phylogenetic marker and dismisses the sequencing result, but the textbook explicitly states shape is not phylum-dependent, so two differently shaped cells sharing a phylum is expected, not an error. (Choice C) is incorrect: the plasma membrane is a fluid bilayer that conforms to the cell rather than imposing a rigid form, and the textbook assigns shape determination to the wall; the compound acts directly on wall synthesis (peptidoglycan cross-linking), not on the membrane. (Choice D) is incorrect: DNA content does not dictate external cell shape, and blocking peptidoglycan cross-linking targets wall assembly, not the chromosome, so attributing the rounding to lost genetic material misidentifies the affected structure. This is a Scientific Reasoning and Problem Solving question because you must apply the principles that the cell wall determines prokaryotic shape and that shape is independent of phylogeny to interpret two experimental results rather than recall a shape term.',
  difficulty = 'medium',
  cognitive_skill = 2
WHERE id = 'da4d4377-d380-4ef7-8d27-5ae94643c045';
DELETE FROM question_distractor_metadata WHERE question_id = 'da4d4377-d380-4ef7-8d27-5ae94643c045';
INSERT INTO question_distractor_metadata (question_id, choice_label, distractor_category, archetype) VALUES
  ('da4d4377-d380-4ef7-8d27-5ae94643c045', 'B', 'misconception', 'shape indicates evolutionary relationship / phylum'),
  ('da4d4377-d380-4ef7-8d27-5ae94643c045', 'C', 'adjacent_fact', 'plasma membrane rather than cell wall determines shape'),
  ('da4d4377-d380-4ef7-8d27-5ae94643c045', 'D', 'misconception', 'genome size dictates cell morphology');

COMMIT;
