import { all } from "../backfill/record.mjs";
const C=await all("concepts","id,status,deprecated_by,canonical_name");
const QC=await all("question_concepts","question_id,concept_id,role,mapping_status,source");
const AL=await all("concept_aliases","concept_id,alias");
const FC=await all("flashcard_concepts","flashcard_id");
const Q=await all("questions","id,topic");
const imIds=new Set(Q.filter(q=>q.topic==="The Immune System").map(q=>q.id));
const im=QC.filter(r=>imIds.has(r.question_id));
const dep=C.filter(c=>c.status==="DEPRECATED");
console.log("INDICATORS  (not-applied -> applied)");
console.log(`  question_concepts total      ${QC.length}        (2659 -> 2666)`);
console.log(`  deprecated concepts          ${dep.length}           (0 -> 83)`);
console.log(`  immune mappings              ${im.length}          (89 -> 96)`);
console.log(`  immune PRIMARY               ${im.filter(r=>r.role==="PRIMARY").length}          (89 -> 90)`);
console.log(`  immune SECONDARY             ${im.filter(r=>r.role==="SECONDARY").length}           (0 -> 6)`);
const src={}; im.forEach(r=>src[r.source]=(src[r.source]||0)+1);
console.log(`  immune provenance            ${JSON.stringify(src)}  (all DETERMINISTIC -> all AI_PROPOSED)`);
console.log(`  aliases                      ${AL.length}           (1 -> 5)`);
console.log(`  concepts                     ${C.length}        (1127 either way)`);
console.log(`  flashcard mappings           ${FC.length}        (4115 either way)`);
const applied = QC.length===2666 && dep.length===83;
const notApplied = QC.length===2659 && dep.length===0;
console.log(`\nVERDICT: ${applied?"APPLIED IN FULL":notApplied?"NOT APPLIED (transaction never committed)":"*** PARTIAL / UNEXPECTED, investigate ***"}`);
