import { all } from "../backfill/record.mjs";
import { PROPOSED, KEEP_EXISTING } from "../immune/design.mjs";
const C=await all("concepts","id,slug,canonical_name,status");
const byName=new Map(C.map(c=>[c.canonical_name,c]));
const QC=await all("question_concepts","question_id,concept_id,role");
const FC=await all("flashcard_concepts","concept_id");
const Q=await all("questions","id,topic");
const imIds=new Set(Q.filter(q=>q.topic==="The Immune System").map(q=>q.id));
const cards={}; FC.forEach(m=>cards[m.concept_id]=(cards[m.concept_id]||0)+1);
const qAll={}, qIm={};
QC.filter(m=>m.role==="PRIMARY").forEach(m=>{qAll[m.concept_id]=(qAll[m.concept_id]||0)+1; if(imIds.has(m.question_id)) qIm[m.concept_id]=(qIm[m.concept_id]||0)+1;});
const durable=[...PROPOSED.map(p=>p.name),...KEEP_EXISTING.map(k=>k.concept)];
console.log(`design set: ${PROPOSED.length} new + ${KEEP_EXISTING.length} reused = ${durable.length} durable immune concepts\n`);
console.log("| concept | immune Qs | all Qs | cards |");
durable.forEach(n=>{const c=byName.get(n);
  console.log(`| ${n} | ${qIm[c.id]||0} | ${qAll[c.id]||0} | ${cards[c.id]||0} |`);});
const withIm=durable.filter(n=>(qIm[byName.get(n).id]||0)>0).length;
const both=durable.filter(n=>{const c=byName.get(n); return (qAll[c.id]||0)>0 && (cards[c.id]||0)>0;}).length;
console.log(`\nholding at least one IMMUNE question: ${withIm} of ${durable.length}`);
console.log(`BOTH_MODALITIES (any question + any card): ${both} of ${durable.length}`);
