-- ============================================================
-- Section becomes many-to-many, like discipline and content category
--
-- FOUND BY THE VERIFIER, not by reading the schema. The section-compatibility
-- check failed on 4 of 2,242 mappings, all on one concept:
--
--   "Isoelectric Focusing" is taught in two chapters and classified under two
--   MCAT sections. 4 questions sit in chem_phys under Electrochemistry, and 4
--   in bio_biochem under Non-enzymatic Protein Function and Protein Analysis.
--   Both are biochemistry. It is one technique, examined from two directions.
--
-- The seeder had to choose one and chose arbitrarily, so 4 questions ended up
-- mapped to a concept whose section contradicted their own.
--
-- THE FIX IS THE ONE THE ARCHITECTURE ALREADY ARGUED FOR. Discipline and
-- content category were both made many-to-many precisely because forcing a
-- single parent misfiles real science. Section was left singular, which was an
-- oversight: the approved target model said section_ids, plural. This corrects
-- that inconsistency rather than splitting a genuine single concept in two or
-- relaxing the validation to hide the conflict.
--
-- Only one concept spans sections today. It is still worth fixing structurally,
-- because the alternative is a validation rule nobody can enforce and a slow
-- accumulation of arbitrary choices as Physics and Psych/Soc content arrives.
--
-- Additive and reversible. No question, flashcard, mapping, FSRS state, review
-- or attempt is touched; only where a concept's section is recorded changes.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.concept_sections (
  concept_id   UUID NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  section_code TEXT NOT NULL REFERENCES public.mcat_sections(code),
  is_primary   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (concept_id, section_code)
);

COMMENT ON TABLE public.concept_sections IS
  'Which MCAT sections a concept is examined in. Many-to-many because a concept can legitimately appear in two: isoelectric focusing is both an electrochemistry topic and a protein-analysis one. is_primary marks where most of its questions sit, for display; validation must check MEMBERSHIP, not equality.';

CREATE UNIQUE INDEX IF NOT EXISTS concept_sections_one_primary
  ON public.concept_sections(concept_id) WHERE is_primary;
CREATE INDEX IF NOT EXISTS concept_sections_section_idx
  ON public.concept_sections(section_code);

ALTER TABLE public.concept_sections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read taxonomy" ON public.concept_sections;
CREATE POLICY "read taxonomy" ON public.concept_sections
  FOR SELECT USING (auth.role() = 'authenticated');

INSERT INTO public.concept_sections (concept_id, section_code, is_primary) VALUES
  ((SELECT id FROM public.concepts WHERE slug=$x$2D_ELECTROPHORESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ABSOLUTE_CONFIGURATION_D_L$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACCESSIBLE_TARGETS_PRIOR_EXPOSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACCESSORY_ATRIOVENTRICULAR_CONDUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACTIVE_SITE_LOCK_KEY_INDUCED_FIT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ADDING_PROTEIN_PARTNER_CAPSULE_SUGAR$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ADOPTIVE_TRANSFER_CAUSAL_NECESSITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ADRENAL_GLANDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AFFINITY_CHROMATOGRAPHY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AFTERLOAD_VENTRICULAR_WALL_THICKNESS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AIRWAY_RESISTANCE_AIRFLOW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ALL_NOTHING_INTENSITY_CODING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ALVEOLI_RESPIRATORY_MEMBRANE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMINO_ACID_STRUCTURE_STEREOCHEMISTRY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMINO_ACID_CATABOLISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ANTIGEN_TRANSPORT_LYMPHOID_ORGAN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ANUCLEATE_ERYTHROCYTE_LIFESPAN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ARTERIAL_COMPLIANCE_PULSE_PRESSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ASSIGNING_DEFICIENCY_PATTERNS_IMMUNE_ARMS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ATP_HIGH_ENERGY_CARRIERS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ATRIAL_SYSTOLE_VENTRICULAR_FILLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ATRIOVENTRICULAR_VALVE_ANCHORING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AUTOIMMUNITY_CORRECT_MACHINERY_WRONG_TARGET$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BACKWARD_TRANSMISSION_PRESSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BACTERIAL_GROWTH_CURVE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BACTERIAL_SHAPES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BASELINE_SELF_FRAGMENT_DISPLAY_HEALTHY_CELLS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BASIS_INDUCED_RESISTANT_STATE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BETA_OXIDATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BIDIRECTIONAL_REFLEX_GAIN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BINDING_PROTEINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BINDING_STRENGTH_VERSUS_DISCRIMINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BLASTULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BLOOD_VISCOSITY_VASCULAR_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BONE_MATRIX_MICROSTRUCTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BONE_REMODELING_CALCIUM_HOMEOSTASIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BONE_STRUCTURE_MARROW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CANNULATED_LYMPH_SAMPLING_PERMEABILITY_ASSAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CAPILLARY_TYPES_PERMEABILITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CAPILLARY_WALL_ARCHITECTURE_EXCHANGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CARBOHYDRATE_METABOLISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CARDIAC_MUSCLE_FUNCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CARDIAC_OUTPUT_CALCULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CAROTID_SINUS_COMPRESSION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CARTILAGE_OSSIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CASCADE_AMPLIFICATION_FEEDBACK_ACTIVATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CATALYTIC_EFFICIENCY_KCAT_KCAT_KM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_CYCLE_CONTROL_CHECKPOINTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_CYCLE_PHASES_INTERPHASE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_MIGRATION_APOPTOSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_THEORY_PROKARYOTIC_FUNDAMENTALS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_CELL_COMMUNICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_FREE_CONTROL_PROTECTION_TRANSFER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELLULOSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHAIR_CONFORMATION_MUTAROTATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHEMORECEPTOR_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHEMOTAXIS_GRADIENT_SENSING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHOLESTEROL_TRIACYLGLYCEROL_SYNTHESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHROMATOGRAPHY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CIRCULATORY_HYPOXIA_NORMAL_ARTERIAL_CONTENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CITRIC_ACID_CYCLE_ENERGETICS_PRODUCTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CITRIC_ACID_CYCLE_REACTIONS_INTERMEDIATES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CITRIC_ACID_CYCLE_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CLEAVAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CLOT_RETRACTION_PLATELET_CONTRACTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CNS_SPINAL_CORD_ORGANIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CNS_TISSUE_ORGANIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COFACTORS_COENZYMES_VITAMINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COLLAPSE_BOTH_ADAPTIVE_ARMS_TOGETHER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COLLOID_VERSUS_CRYSTALLOID_OSMOTIC_EFFECTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COLONIZATION_RESISTANCE_RESIDENT_FLORA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COMMITMENT_SELECTED_B_LYMPHOCYTE_EXPORT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COMPARING_STARLING_FORCES_ACROSS_CAPILLARY_BEDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONDUCTION_BLOCK_ESCAPE_RHYTHMS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONDUCTION_TIMING_ECG$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONJUGATED_PROTEINS_DENATURATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONSEQUENCES_ENDOTHELIAL_DENUDATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONSEQUENCES_SUPPRESSED_SURFACE_DISPLAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONSTITUTIVE_PLASMA_DEFENSES_VERSUS_INDUCED_SPECIFICITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONTRACTILITY_EJECTION_FRACTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONTROL_ARM_DISPLAY_BLOCKING_REAGENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CONTROL_ARMS_SPECIFICITY_CLAIM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COOPERATIVITY_T_R_STATES_SIGMOIDAL_KINETICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COUNTER_REGULATORY_HORMONES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COUNTERCURRENT_VASCULAR_HEAT_EXCHANGE_LIMB$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CROSS_BRIDGE_CYCLE_SLIDING_FILAMENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CROSSING_OVER_RECOMBINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CULTURE_ARM_TESTING_MATCHED_VERSUS_GENERIC$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CUTTING_AFFERENT_LIMB$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYCLIC_SUGARS_ANOMERS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYTOSKELETON_CENTRIOLES_CENTROSOME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYTOSKELETON_CILIA_FLAGELLA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYTOSKELETON_INTERMEDIATE_FILAMENTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYTOSKELETON_MICROFILAMENTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CYTOSKELETON_MICROTUBULES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DAILY_LYMPH_RETURN_VOLUME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DEFENCE_AGAINST_EXTRACELLULAR_BACTERIAL_PRODUCT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DEFENCE_TIMELINE_AFTER_BREACH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DESIGNING_DONOR_COMPATIBILITY_CULTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DETECTING_ENTIRELY_INTRACELLULAR_INFECTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DIASTOLIC_FILLING_TIME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DIFFERENTIATION_STEM_CELL_POTENCY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DIHYBRID_TEST_CROSSES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DIRECTING_PLASMA_PROTEIN_CASCADE_ONE_SURFACE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DIRECTION_INNATE_ANTIVIRAL_SIGNAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISACCHARIDES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISPLAY_REQUIREMENT_T_LYMPHOCYTE_RECOGNITION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISSOLVED_OXYGEN_FRACTION_CONTENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISTINGUISHING_RESIDENT_FROM_RECRUITED_PHAGOCYTES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DOMINANCE_PATTERNS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DONOR_PLASMA_ANTIBODY_LOAD_WHOLE_BLOOD$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DOSE_RESPONSE_LICENSING_WITHHELD$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DRAINING_VERSUS_REMOTE_NODE_TIME_COURSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DUAL_BLOOD_SUPPLY_LIVER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DUCTUS_VENOSUS_FETAL_VS_ADULT_CIRCULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ECTODERM_DERIVATIVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EJECTION_FRACTION_CARDIAC_OUTPUT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELASTIC_ARTERIES_DIASTOLIC_FLOW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTRON_TRANSPORT_CHAIN_COMPLEXES_CARRIERS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTRON_TRANSPORT_CHAIN_PROTON_MOTIVE_FORCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTRON_TRANSPORT_CHAIN_SHUTTLES_INHIBITORS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTROPHORESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOCRINE_PANCREAS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDODERM_DERIVATIVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOMEMBRANE_SYSTEM_ORGANELLE_IDENTIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOPLASMIC_RETICULUM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOTHELIAL_CONTROL_TISSUE_PERFUSION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENERGY_BALANCE_APPETITE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENLARGED_RESPONSIVE_POPULATION_AFTER_CLEARANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENZYMATIC_CLOT_DISSOLUTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENZYME_CLASSIFICATION_EC_CLASSES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENZYME_REGULATION_ALLOSTERIC_FEEDBACK_COVALENT_MODIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENZYMES_CATALYSTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EPITOPE_SIZE_RESPONSE_DIVERSITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EQUAL_FLOW_THROUGH_TWO_CIRCUITS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ERYTHROCYTE_ATP_PRODUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ERYTHROCYTE_DEFORMABILITY_CAPILLARY_TRANSIT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ERYTHROCYTE_TURNOVER_SURVIVAL_TIME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ESTERIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EVOLUTIONARY_PATTERNS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EXCITATION_CONTRACTION_COUPLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EXERCISE_SCENARIO_INTEGRATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EXHALATION_ELASTIC_RECOIL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EXTRAMEDULLARY_HEMOPOIESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_AMINO_ACID_ENTRY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_ACTIVATION_CARNITINE_ENTRY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_STRUCTURE_NOMENCLATURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_SYNTHESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FEEDBACK_NEUROENDOCRINE_INTEGRATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FEMALE_HORMONES_ESTROGEN_PROGESTERONE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FEMALE_REPRODUCTIVE_ANATOMY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FERTILIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FETAL_HEMOGLOBIN_OXYGEN_TRANSFER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FLOW_REDISTRIBUTION_VASCULAR_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FORAMEN_OVALE_DUCTUS_ARTERIOSUS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FREE_ENERGY_EQUILIBRIUM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$G_PROTEIN_COUPLED_RECEPTORS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GAMETE_STRUCTURE_FERTILIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GAS_EXCHANGE_PULMONARY_CIRCULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_ACID_CHEMICAL_BARRIER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_MAPPING_RECOMBINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENETIC_DRIFT_POPULATION_CHANGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GESTATION_BIRTH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOSIDE_FORMATION_HYDROLYSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GOLGI_APPARATUS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GONADS_PINEAL_OTHER_TISSUES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GRADED_PROTECTION_AGAINST_MUTATED_COAT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GRANULOCYTE_FRACTION_DIFFERENTIAL_COUNT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HARDY_WEINBERG_EQUILIBRIUM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEAD_UP_TILT_RESISTANCE_ADJUSTMENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEART_RATE_CARDIAC_OUTPUT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEART_SOUNDS_VALVE_CLOSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEPATIC_PORTAL_ROUTE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HORMONE_CLASSES_CHEMISTRY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HORMONE_TRANSPORT_SPECIFICITY_KINETICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HYDROPHOBICITY_UNIQUE_RESIDUES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HYPOPHYSEAL_PORTAL_ARCHITECTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HYPOTHALAMUS_PITUITARY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IMMEDIATE_VESSEL_NARROWING_AFTER_INJURY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IMMUNOGLOBULINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IMPLANTATION_EXTRAEMBRYONIC_MEMBRANES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IMPULSE_PROPAGATION_CONDUCTION_VELOCITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INFECTION_PATTERN_POINTING_ONE_ARM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INHALATION_MECHANICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INJURY_EXPOSING_SEQUESTERED_BODY_CONSTITUENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INNATE_TRIGGERING_DAMAGE_VERSUS_NON_SELF$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INSULIN_GLUCAGON$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTERPRETING_MATCHED_DISPLAY_KILLING_ASSAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTERPRETING_PHAGOCYTE_MIGRATION_ASSAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTERPRETING_ELEVATED_HEMATOCRIT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTERSTITIAL_PROTEIN_RETENTION_AFTER_LYMPHATIC_LOSS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ION_CHANNELS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ION_EXCHANGE_CHROMATOGRAPHY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IRON_RECYCLING_HEME_BREAKDOWN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IRREVERSIBLE_INHIBITION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ISOELECTRIC_FOCUSING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ISOELECTRIC_FOCUSING$x$), $x$CHEM_PHYS$x$, false),
  ((SELECT id FROM public.concepts WHERE slug=$x$ISOELECTRIC_POINT_PI$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ISOVOLUMIC_CONTRACTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$JOINTS_MOVEMENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$KETO_ENOL_TAUTOMERISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$KETONE_BODIES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$KETONE_BODIES_ETHANOL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LACTEAL_ROUTING_ABSORBED_LIPID$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LAYERED_SURFACE_DEFENCES_RESPONSE_TIMING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LEUKOCYTE_EXIT_FROM_MICROCIRCULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LINEAGE_THAT_NEVER_LEAVES_BIRTHPLACE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LINEWEAVER_BURK_DOUBLE_RECIPROCAL_PLOTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LINKAGE_INDEPENDENT_ASSORTMENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_ABSORPTION_ROUTING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_DIGESTION_BILE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_MOBILIZATION_TRANSPORT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOCAL_CONDITIONS_TEMPERATURE_PH_SALINITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOCALISING_BLOCK_UPSTREAM_LYMPHOCYTES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOCALISING_TRANSFERABLE_REACTIVITY_BLOOD_FRACTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOCATING_BREAK_LOOP$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOCATING_SOURCE_TISSUE_DAMAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOSS_CELL_CYCLE_CONTROL_CANCER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOSS_SIGNAL_RELEASING_T_LYMPHOCYTE_POPULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOWERED_TRIGGERING_REQUIREMENT_SURVIVING_LYMPHOCYTES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LUNG_VOLUMES_CAPACITIES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LYSOSOMES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MALE_HORMONAL_AXIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MALE_REPRODUCTIVE_ANATOMY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MANIPULATING_FILTRATION_BALANCE_EXPERIMENTALLY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MATCHED_VENTRICULAR_OUTPUTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEAN_ARTERIAL_PRESSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEAN_ARTERIAL_PRESSURE_TOTAL_PERIPHERAL_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEIOSIS_I_VS_II_REDUCTIONAL_EQUATIONAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MENDEL_S_LAWS_EPIGENETICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MENDELIAN_FOUNDATIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MESODERM_DERIVATIVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$METABOLIC_STATES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MICHAELIS_MENTEN_KINETICS_VMAX_KM_SATURATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MITOCHONDRIA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MITOSIS_PHASES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MITOTIC_STRUCTURES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MODES_SELECTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MONOSACCHARIDE_CLASSIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MOTOR_PROTEINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MULTI_STEP_PURIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MULTI_TISSUE_COORDINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MURMUR_TIMING_VALVE_LESIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MUSCLE_ENERGETICS_FATIGUE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MUSCLE_FIBER_TYPES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MUSCLE_MECHANICS_CONTRACTION_DYNAMICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MUSCLE_TYPES_CHARACTERISTICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MUTATIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MYELIN_MYELINATING_GLIA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NATIVE_PAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NATURAL_SELECTION_FITNESS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEONATAL_VERSUS_ADULT_LOSS_SCREENING_ORGAN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NET_FILTRATION_PRESSURE_VENULAR_END$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEURAL_CONTROL_BREATHING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEURON_ANATOMY_SIGNAL_FLOW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEURON_FUNCTIONAL_TYPES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEUROTRANSMITTER_RELEASE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NEURULATION_NEURAL_CREST$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NONDISJUNCTION_MEIOSIS_VS_MITOSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NONSELF_PRESENT_DURING_SCREENING_WINDOW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NONSELF_RECOGNITION_GRAFTED_TISSUE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NUCLEUS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OOGENESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ORIGIN_B_LINEAGE_BINDING_DIVERSITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATION_REDUCING_SUGARS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATIVE_PHOSPHORYLATION_ATP_SYNTHASE_COUPLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATIVE_PHOSPHORYLATION_ATP_YIELD_BIOENERGETICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATIVE_PHOSPHORYLATION_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXYGEN_CONTENT_VERSUS_PERCENT_SATURATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXYGEN_DELIVERY_FLOW_TIMES_CONTENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXYGEN_BINDING_PROTEINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PACEMAKER_HIERARCHY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PAIRING_DISPLAY_TYPE_EFFECTOR_FUNCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PEPTIDE_BOND_FORMATION_HYDROLYSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PERITUBULAR_CAPILLARY_CONDITIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PEROXISOMES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PH_CONTROL_BICARBONATE_BUFFER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PHAGOCYTE_SIZE_LIMITS_EXTERNAL_ATTACK$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PKA_PROTONATION_STATES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLACENTAL_FUNCTIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLASMA_FRACTION_PLASMA_PROTEIN_CONTENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLASMA_PROTEINS_CAPILLARY_FLUID_BALANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLASMA_VERSUS_SERUM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLATELET_GRANULE_RELEASE_PLUG_GROWTH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLATELET_ORIGIN_FROM_MEGAKARYOCYTES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLATELET_PLUG_VERSUS_FIBRIN_REINFORCEMENT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PLEURAE_THORACIC_CAVITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PNS_SOMATIC_VS_AUTONOMIC$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POISEUILLE_DETERMINANTS_VASCULAR_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POLYSACCHARIDES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POPULATION_VALUE_MHC_ALLELE_DIVERSITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POSITION_FILTRATION_REABSORPTION_CROSSOVER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POSTSYNAPTIC_RECEPTORS_NEUROTRANSMITTER_REMOVAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PREBUILT_REPERTOIRE_FIRST_RESPONSE_LAG$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PREGNANCY_MENOPAUSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PRESSURE_GRADIENTS_ACROSS_VALVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PRESSURE_OVERLOAD_CHAMBER_REMODELING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PRIMARY_STRUCTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PRIONS_VIROIDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_CELL_WALL_GRAM_STAINING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_DOMAINS_ARCHAEA_BACTERIA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_FLAGELLA_MOTILITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GENETICS_CONJUGATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GENETICS_PLASMIDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GENETICS_TRANSDUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GENETICS_TRANSFORMATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GENETICS_TRANSPOSONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROKARYOTIC_GROWTH_METABOLISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROPERTIES_BROAD_ANTIVIRAL_SIGNAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROTEIN_CONTENT_ACCUMULATED_INTERSTITIAL_FLUID$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROTEIN_DIGESTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROTEIN_VERSUS_POLYSACCHARIDE_ANTIGEN_DEPENDENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PULMONARY_SYSTEMIC_CIRCUITS_SERIES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PULSE_PRESSURE_STROKE_VOLUME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PUNNETT_SQUARES_MONOHYBRID_CROSSES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PURKINJE_ACTIVATION_SEQUENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PURPOSE_OBLIGATE_DRAINAGE_DETOUR$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PYRUVATE_DEHYDROGENASE_ACETYL_COA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$QUANTITATIVE_ANALYSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$QUATERNARY_STRUCTURE_COOPERATIVITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$READING_LABELLED_LYMPHOCYTE_DISTRIBUTION_TIME_COURSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$READING_NATIVE_VERSUS_FRAGMENT_BINDING_TABLE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$READING_PRIOR_CONTACT_PATCH_PANEL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$READING_EXPANSION_RARE_CLONE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$READING_FRAGMENT_ORIGIN_FROM_ASSAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RECEPTOR_ENZYMES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RECEPTORS_SIGNAL_TRANSDUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REDUCING_NON_REDUCING_SUGARS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REDUCTION_DEOXY_SUGARS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REFLEX_ARCS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REFRACTORY_PERIODS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REGENERATION_SENESCENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REGIONAL_EXTRACTION_RESERVE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_PORTAL_HEMODYNAMICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REPOLARIZATION_HYPERPOLARIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESIDENT_MACROPHAGES_SOURCE_RECRUITMENT_SIGNALS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESIDENT_VERSUS_RECRUITED_POPULATIONS_OVER_TIME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESPIRATORY_IMMUNE_DEFENSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESTING_MEMBRANE_POTENTIAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESTRICTING_INGESTED_MATERIAL_DISPLAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RETICULOCYTE_COUNT_MARROW_RESPONSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REVERSIBLE_INHIBITION_COMPETITIVE_NONCOMPETITIVE_UNCOMPETITIVE_MIXED$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RIGID_CELL_WALLS_PORE_MEDIATED_LYSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ROLE_THERMOREGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SALTATORY_CONDUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SAMPLING_PORTAL_CIRCUIT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SARCOMERE_STRUCTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SCREENING_ANTIGEN_THAT_NEVER_LEAVES_VESSELS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SCREENING_DONOR_UNITS_AGAINST_RECIPIENT_ANTIBODY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SDS_PAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SECOND_MESSENGERS_AMPLIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SECONDARY_STRUCTURE_HELIX_SHEET$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SELECTION_VERSUS_INSTRUCTION_ANTIGEN$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SELF_VERSUS_NONSELF_DISCRIMINATION_PLASMA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SEMILUNAR_VALVE_COMPETENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SENSITIZATION_TIMING_AFTER_RH_EXPOSURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SEPARATE_CAUSES_SPEED_SIZE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SEPARATING_IRRITANT_INJURY_FROM_HOST_RESPONSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SEX_LINKED_INHERITANCE_PEDIGREES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SEXUAL_DEVELOPMENT_PUBERTY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SHARED_SURFACE_PATCHES_TEST_SPECIFICITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SIDE_CHAIN_CLASSIFICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SIGNAL_TRANSDUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SITE_GREATEST_VASCULAR_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SIZE_EXCLUSION_CHROMATOGRAPHY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SKIN_PHYSICAL_BARRIER$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPECIATION_ISOLATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPECIFICATION_DETERMINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPECIFICITY_CONTROL_TWO_EXPOSURE_TIME_COURSE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPERMATOGENESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPHYGMOMANOMETRY_TECHNIQUE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STARCH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STARLING_FORCES_LYMPH_FORMATION_RATE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STEREOCHEMISTRY_ISOMERISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SUBSET_DEPLETION_ARM_SPECIFIC_READOUT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SUPPORT_GLIA_ASTROCYTES_EPENDYMAL_MICROGLIA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SYMPATHETIC_VS_PARASYMPATHETIC$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SYNAPSIS_TETRADS_SYNAPTONEMAL_COMPLEX$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TARGETS_NAIVE_B_RECEPTOR_CAN_REACH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TERTIARY_STRUCTURE_FOLDING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TESTING_ENDOTHELIAL_FUNCTION_ISOLATED_VESSELS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TESTING_NECESSITY_LICENSING_CONTACT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TESTING_WHETHER_PLASMA_DEFENSE_IS_TAILORED$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MENSTRUAL_CYCLE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SYNAPSE_SYNAPTIC_TERMINAL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THERMODYNAMICS_SYSTEMS_FREE_ENERGY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THERMOREGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THRESHOLD_DEPOLARIZATION_SUMMATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THYROID_PARATHYROID$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THYROID_HORMONE_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TISSUE_SPECIFIC_METABOLISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TISSUES_CONNECTIVE_TISSUE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TISSUES_EPITHELIAL_TISSUE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TOLERANCE_SELF_PEPTIDES_MHC$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TOTAL_CROSS_SECTIONAL_AREA_FLOW_VELOCITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSPORTERS_SIGNALING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TURBULENCE_VASCULAR_SOUND$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TWINS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TWO_FRAGMENT_SOURCES_TWO_CARRIERS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TWO_MECHANISMS_INTERSTITIAL_FLUID_ACCUMULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TWO_SCREENS_DURING_LYMPHOCYTE_MATURATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TWO_SITE_DESIGN_LYMPHOCYTE_PRODUCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$UNIVERSAL_DISTRIBUTION_DISPLAY_MOLECULE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$UPPER_AIRWAY_CONDUCTING_ZONE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$UREA_CYCLE_METABOLIC_INTEGRATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VASCULAR_CHANGE_DELIVERY_PLASMA_COMPONENTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VASOMOTOR_CHANGES_ACROSS_CLOT_LIFECYCLE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VENOCONSTRICTION_VENOUS_RESISTANCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VENOUS_RETURN_SKELETAL_MUSCLE_PUMP$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VESSEL_OBSTRUCTION_DURING_MISMATCHED_TRANSFUSION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VESSEL_RADIUS_BLOOD_FLOW$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VIRAL_GENOMES_REPLICATION_STRATEGY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VIRAL_LIFE_CYCLE_LYTIC_LYSOGENIC$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VIRUS_STRUCTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VOLTAGE_GATED_NA_CHANNELS_DEPOLARIZATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHAT_NODE_ENLARGEMENT_ACTUALLY_CONSISTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHY_COATED_ORGANISM_IS_ONE_THAT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHY_RARE_CLONES_MUST_BE_CONCENTRATED$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHY_RARE_CLONES_MUST_KEEP_MOVING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHY_RE_ENCOUNTER_SHORTENS_DELAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WHY_SURFACE_OUTPUT_SPECIFICITY_MUST_MATCH$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WIDENING_EXTRACTION_PEAK_EXERCISE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ZWITTERIONS_TITRATION_CURVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMINO_ACID_TITRATION_ISOELECTRIC_POINT$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AUTOIONIZATION_KW_PH_POH_SCALES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BALANCING_EQUATIONS_INCL_REDOX$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BALANCING_REDOX_HALF_REACTION_METHOD$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BATTERIES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BICARBONATE_BUFFER_BLOOD_PH_PHYSIOLOGY$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BOND_LENGTH_BOND_ENERGY$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BOND_POLARITY_DIPOLE_MOMENT$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BUFFERS_HENDERSON_HASSELBALCH$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CARBON_OXIDATION_LEVEL$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CATALYSTS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_DIAGRAM_NOTATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_POTENTIAL_EMF$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_POTENTIAL_EQUILIBRIUM$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_TYPES_ELECTRON_FLOW$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COLLISION_THEORY_ARRHENIUS_EQUATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COMMON_NAMES_CARBONYL_STRUCTURE$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$COMMON_OXIDIZING_REDUCING_AGENTS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DEFINITIONS_CONJUGATE_ACID_BASE_PAIRS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISPROPORTIONATION_REACTIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTRODE_CHARGE_DESIGNATIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTROLYSIS_FARADAY_S_LAW$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTRON_CONFIGURATIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EMPIRICAL_MOLECULAR_FORMULA_PERCENT_COMPOSITION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENERGY_PROFILES_TRANSITION_STATES_MECHANISMS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FORMAL_CHARGE$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FREE_ENERGY_CELL_POTENTIAL$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FUNCTIONAL_GROUP_IDENTIFICATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GALVANIC_CELL_COMPONENTS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTEGRATED_RATE_LAWS_HALF_LIFE$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTERMOLECULAR_FORCES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IONIC_CHARACTER_BOND_TYPE$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$IONS_NOMENCLATURE_ELECTROLYTES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ISOTOPES_ATOMIC_WEIGHT$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LEWIS_ACIDS_BASES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LEWIS_STRUCTURES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIMITING_REAGENT_THEORETICAL_PERCENT_YIELD$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MOLECULAR_POLARITY$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MOLECULES_MOLES_MOLAR_MASS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NERNST_EQUATION_CONCENTRATION_CELLS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NET_IONIC_EQUATIONS_SPECTATOR_IONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OCTET_RULE_EXCEPTIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATION_NUMBERS_ASSIGNMENT_RULES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OXIDATION_REDUCTION_IDENTIFYING_AGENTS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PERIODIC_TABLE_STRUCTURE_CLASSIFICATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PERIODIC_TRENDS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$QUANTIZATION_BOHR_SPECTRA$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$QUANTUM_MODEL_QUANTUM_NUMBERS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REACTION_ORDER_METHOD_INITIAL_RATES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REACTION_RATES_RATE_LAWS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REACTION_TYPES_CLASSIFICATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REDOX_TITRATIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESONANCE_DELOCALIZATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SALT_HYDROLYSIS_PH_SALT_SOLUTIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SIGMA_PI_BONDS_HYBRIDIZATION$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STANDARD_REDUCTION_POTENTIALS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STEREOCHEMISTRY$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STRONG_VS_WEAK_ACIDS_BASES_KA$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SUBATOMIC_PARTICLES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MOLE_AVOGADRO$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TITRATION_TITRATION_CURVES$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TYPES_ELEMENTS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TYPES_REACTIONS$x$), $x$CHEM_PHYS$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VSEPR_MOLECULAR_GEOMETRY$x$), $x$CHEM_PHYS$x$, true)
ON CONFLICT (concept_id, section_code) DO NOTHING;
-- The singular column is now a second source of truth for the same fact, and
-- for one concept it holds the wrong half of it. Dropped rather than kept in
-- sync, because two places to look is how drift starts.
ALTER TABLE public.concepts DROP COLUMN IF EXISTS section_code;

-- ── Verification ────────────────────────────────────────────────────────
SELECT
  (SELECT count(*) FROM public.concept_sections)                              AS section_rows,    -- 489
  (SELECT count(DISTINCT concept_id) FROM public.concept_sections)            AS concepts_placed, -- 488
  (SELECT count(*) FROM (SELECT concept_id FROM public.concept_sections
     GROUP BY concept_id HAVING count(*) > 1) x)                              AS multi_section,   -- 1
  (SELECT count(*) FROM public.question_concepts)                             AS mappings_intact, -- 2242
  (SELECT count(*) FROM public.questions)                                     AS questions_intact,-- 2681
  (SELECT count(*) FROM public.flashcards)                                    AS cards_intact;    -- 4117

-- Section compatibility, now by MEMBERSHIP. Expect zero rows.
SELECT 'section mismatch' AS problem, count(*) AS n
FROM public.question_concepts qc
JOIN public.questions q ON q.id = qc.question_id
JOIN public.legacy_taxonomy_map m
  ON m.source_system='questions' AND m.source_field='section' AND m.source_value=q.section
WHERE NOT EXISTS (
  SELECT 1 FROM public.concept_sections cs
  WHERE cs.concept_id = qc.concept_id AND cs.section_code = m.section_code);

-- The concept that prompted this.
SELECT c.canonical_name, cs.section_code, cs.is_primary
FROM public.concepts c JOIN public.concept_sections cs ON cs.concept_id = c.id
WHERE c.slug = 'ISOELECTRIC_FOCUSING' ORDER BY cs.is_primary DESC;

-- ── ROLLBACK ────────────────────────────────────────────────────────────
-- ALTER TABLE public.concepts ADD COLUMN IF NOT EXISTS section_code TEXT REFERENCES public.mcat_sections(code);
-- UPDATE public.concepts c SET section_code =
--   (SELECT cs.section_code FROM public.concept_sections cs WHERE cs.concept_id=c.id AND cs.is_primary LIMIT 1);
-- DROP TABLE IF EXISTS public.concept_sections;
