-- ============================================================
-- Vocabulary extension: seed 88 concepts and map the 417
--
-- Approved after the QA pass. Additive and reversible; rollback at the foot.
-- Nothing is touched outside the taxonomy tables.
--
-- WHAT THE MAPPING IS. Unlike the first 2,242, these do NOT map by string
-- equality: a per-question descriptor is not a concept name. Instead the
-- descriptor-to-concept table below IS the approved artifact, and this file
-- applies it mechanically. Provenance is DETERMINISTIC rather than
-- DETERMINISTIC_EXACT for exactly that reason, and it is deliberately not
-- HUMAN_VALIDATED: the vocabulary and the clustering were reviewed, but not
-- each of 417 individual rows, and the status should not claim otherwise.
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Rename the existing concept, preserving its ID
--
-- All six of its questions are respiratory: panting, nasal and tracheal
-- mucosal blood flow, and why panting does not produce alkalosis. Checked
-- programmatically before writing this: zero of the six lack respiratory
-- vocabulary in stem or explanation.
--
-- The ID does not change, its 6 existing mappings are untouched, and the
-- concepts_archive_rename trigger files "Thermoregulation" as a LEGACY_NAME
-- alias automatically. That is the rename lifecycle working as designed.
-- ────────────────────────────────────────────────────────────
UPDATE public.concepts
SET canonical_name = 'Respiratory Thermoregulation'
WHERE canonical_name = 'Thermoregulation';

-- 88 approved extension concepts.
INSERT INTO public.concepts (slug, canonical_name, description, concept_level, status, version, split_candidate) VALUES
  ($x$LUMINAL_BRUSH_BORDER_DIGESTION$x$, $x$Luminal and Brush-Border Digestion$x$, $x$Where each class of macromolecule is cleaved, and the division between lumenal enzymes and membrane-anchored final steps.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTRIC_ACID_SECRETION$x$, $x$Gastric Acid Secretion$x$, $x$Parietal cell proton pump, its energetics, stoichiometry and blockade, and the alkaline tide that accompanies it.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTROINTESTINAL_HORMONAL_CONTROL$x$, $x$Gastrointestinal Hormonal Control$x$, $x$Gastrin, secretin, CCK and somatostatin as feed-forward and feedback regulators of secretion.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$PHASES_DIGESTION$x$, $x$Phases of Digestion$x$, $x$Cephalic, gastric and intestinal phases, and why the last is inhibitory.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTRIC_EMPTYING_STORAGE$x$, $x$Gastric Emptying and Storage$x$, $x$Reservoir capacity and the feedback that sets the rate of delivery to the duodenum.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTRIC_MUCOSAL_PROTECTION$x$, $x$Gastric Mucosal Protection$x$, $x$How the stomach lining resists the acid it secretes.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$PANCREATIC_EXOCRINE_SECRETION$x$, $x$Pancreatic Exocrine Secretion$x$, $x$Acinar enzyme output versus ductal bicarbonate, and the consequences of losing either.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$BILIRUBIN_CONJUGATION_EXCRETION$x$, $x$Bilirubin Conjugation and Excretion$x$, $x$Bile storage and delivery, and the hepatic conjugation that lets pigment be excreted.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$INTESTINAL_NUTRIENT_TRANSPORT$x$, $x$Intestinal Nutrient Transport$x$, $x$Secondary active uptake at the apical surface, facilitated exit at the basolateral, and carrier competition.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$INTESTINAL_ABSORPTIVE_SURFACE$x$, $x$Intestinal Absorptive Surface$x$, $x$The multiplicative anatomy of folds, villi and microvilli, and the unstirred layer over it.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$VITAMIN_ABSORPTION_DEFICIENCY$x$, $x$Vitamin Absorption and Deficiency$x$, $x$Site-specific vitamin uptake, the B12 relay, and how a deficiency localises the lesion.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$LARGE_INTESTINE_WATER_RECOVERY$x$, $x$Large Intestine and Water Recovery$x$, $x$Colonic water and electrolyte handling, fermentation, and residence time.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTROINTESTINAL_MOTILITY$x$, $x$Gastrointestinal Motility$x$, $x$Segmentation versus peristalsis, sphincter behaviour, and voluntary versus reflex control.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ENTERIC_NERVOUS_SYSTEM$x$, $x$Enteric Nervous System$x$, $x$Intramural plexuses and reflex arcs complete within the gut wall.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GASTROINTESTINAL_WALL_LAYERS$x$, $x$Gastrointestinal Wall Layers$x$, $x$The serial layers of the gut wall and what is lost when each is damaged.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GENETIC_CODE_READING_FRAME$x$, $x$The Genetic Code and Reading Frame$x$, $x$Triplet architecture, degeneracy, wobble tolerance by codon position, and how frame is set and lost.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$, $x$Transfer RNA Structure and Wobble$x$, $x$The two-ended adapter, anticodon pairing direction, and the tRNA economy wobble permits.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RNA_CLASSES_SECONDARY_STRUCTURE$x$, $x$RNA Classes and Secondary Structure$x$, $x$Division of labour among RNA classes, and why single-strandedness permits intramolecular folding and catalysis.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$, $x$Ribosome Structure and Ribozyme Activity$x$, $x$Subunit composition and assembly, and the evidence that rRNA rather than protein is catalytic.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TRANSLATION_INITIATION$x$, $x$Translation Initiation$x$, $x$How the small subunit is positioned: Shine-Dalgarno in prokaryotes, cap recognition in eukaryotes.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TRANSLATION_ELONGATION_TERMINATION$x$, $x$Translation Elongation and Termination$x$, $x$Peptidyl transfer, the GTP cost per cycle, and release-factor hydrolysis without a tRNA.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$, $x$Transcription Mechanism and Strand Roles$x$, $x$Template versus coding strand, polymerase direction, intrinsic melting and primer independence.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$, $x$Eukaryotic Promoters and General Transcription Factors$x$, $x$TATA positioning, TBP recognition and the assembly order of the pre-initiation complex.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$, $x$Enhancers and Transcriptional Activators$x$, $x$Position-independent elements, cognate specificity, and transferring a response element to a new gene.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$, $x$Operons and Prokaryotic Gene Regulation$x$, $x$Inducible and repressible logic, operator mutants, and coordinate control of a pathway.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$EUKARYOTIC_RNA_PROCESSING$x$, $x$Eukaryotic RNA Processing$x$, $x$Capping, polyadenylation, splicing by snRNPs, alternative splicing and export licensing.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RNA_INTERFERENCE$x$, $x$RNA Interference$x$, $x$Small RNAs directing transcript degradation or translational silencing.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$, $x$Post-Translational Processing and Targeting$x$, $x$Signal peptides, proteolytic maturation, glycosylation and lipid anchoring.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GENE_DOSAGE$x$, $x$Gene Dosage$x$, $x$How copy number and sequence changes scale or localise functional output.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$, $x$Nucleic Acid Structure and Polarity$x$, $x$Antiparallel strands, phosphodiester directionality, base pairing chemistry and the sugar that distinguishes RNA.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$DUPLEX_STABILITY_DENATURATION$x$, $x$Duplex Stability and Denaturation$x$, $x$Base stacking and GC content as determinants of melting, and the kinetics of reannealing.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$CHROMATIN_STRUCTURE_PACKAGING$x$, $x$Chromatin Structure and Packaging$x$, $x$Histone octamer, electrostatic binding, H1, and the euchromatin/heterochromatin distinction.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TELOMERES_TELOMERASE$x$, $x$Telomeres and Telomerase$x$, $x$Repetitive end structure, the internal RNA template, and repeat instability.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$REPLICATION_FORK_MECHANICS$x$, $x$Replication Fork Mechanics$x$, $x$Helicase, topological strain, supercoil relief and processivity at the moving fork.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ORIGINS_REPLICATION$x$, $x$Origins of Replication$x$, $x$Sequence specificity, AT-richness, multiple origins and plasmid maintenance.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$LAGGING_STRAND_SYNTHESIS$x$, $x$Lagging Strand Synthesis$x$, $x$Primers, Okazaki fragments, excision and ligation of the discontinuous strand.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$, $x$DNA Polymerase Chemistry and Fidelity$x$, $x$Substrate selection, 5' to 3' extension, proofreading direction and layered error rates.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$DNA_REPAIR_PATHWAYS$x$, $x$DNA Repair Pathways$x$, $x$Base excision, mismatch strand discrimination and nucleotide excision of helix-distorting lesions.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RESTRICTION_ENZYMES_CLONING$x$, $x$Restriction Enzymes and Cloning$x$, $x$Palindromic sites, compatible overhangs, vector ligation and selection.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$POLYMERASE_CHAIN_REACTION$x$, $x$Polymerase Chain Reaction$x$, $x$Cycle steps, exponential amplification arithmetic and primer design failure modes.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$DNA_SEQUENCING$x$, $x$DNA Sequencing$x$, $x$Chain termination chemistry and reading a sequencing ladder.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ELECTROPHORESIS_BLOTTING_PROBES$x$, $x$Electrophoresis, Blotting and Probes$x$, $x$Size-based migration, probe specificity, blot targets and density labelling.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$REVERSE_TRANSCRIPTION_CDNA$x$, $x$Reverse Transcription and cDNA$x$, $x$Making DNA from an RNA template and what cDNA lacks.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GENE_KNOCKOUT_EXPERIMENTS$x$, $x$Gene Knockout Experiments$x$, $x$Loss-of-function manipulation: what a knockout model is, and the rescue control that shows the phenotype follows from the missing gene rather than the engineering.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLOMERULAR_FILTRATION$x$, $x$Glomerular Filtration$x$, $x$Barrier layers, charge and size selectivity, and the pressures that set filtration rate.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RENAL_CLEARANCE_FILTERED_LOAD$x$, $x$Renal Clearance and Filtered Load$x$, $x$Clearance as a measure of filtration, filtered load, and what appears in urine.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$PROXIMAL_TUBULE_REABSORPTION$x$, $x$Proximal Tubule Reabsorption$x$, $x$Isosmotic bulk reabsorption, the basolateral pump that drives it, and carrier saturation.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$, $x$Loop of Henle and Countercurrent Multiplication$x$, $x$Limb asymmetry, how loop length multiplies a single-level difference, and the medullary gradient.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$URINE_CONCENTRATION_DILUTION$x$, $x$Urine Concentration and Dilution$x$, $x$The two requirements for concentrating urine, obligatory volume, and osmotic diuresis.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$DISTAL_NEPHRON_POTASSIUM_HANDLING$x$, $x$Distal Nephron and Potassium Handling$x$, $x$Distal sodium delivery as the driver of potassium secretion.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$RENAL_AUTOREGULATION$x$, $x$Renal Autoregulation$x$, $x$Myogenic and tubuloglomerular feedback holding filtration steady across a pressure range.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$, $x$Volume Versus Osmolarity Defence$x$, $x$Which variable the body protects when the two conflict, and nitrogen waste as a water cost.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$, $x$Skin Structure and Barrier Function$x$, $x$Layers, avascular epidermis, cornification and the water barrier.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$THERMOREGULATORY_MECHANISMS$x$, $x$Thermoregulatory Mechanisms$x$, $x$Heat exchange direction, insulation, piloerection, sweat gland populations and set-point shifts.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$CUTANEOUS_MECHANORECEPTORS$x$, $x$Cutaneous Mechanoreceptors$x$, $x$Receptor depth, spatial resolution and temporal filtering by encapsulation.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$, $x$Fluid Mosaic Model and Membrane Dynamics$x$, $x$Lateral versus transverse movement, phase behaviour and the experiments that demonstrated fluidity.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$MEMBRANE_LIPID_ASYMMETRY$x$, $x$Membrane Lipid Asymmetry$x$, $x$Flippase maintenance of leaflet composition and what its loss reveals.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$LIPID_RAFTS$x$, $x$Lipid Rafts$x$, $x$Ordered microdomains and the co-clustering of signalling partners.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$, $x$Membrane Protein Classification and Topology$x$, $x$Integral versus peripheral versus lipid-anchored, extraction criteria, hydropathy and stop-transfer logic.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$MEMBRANE_COMPOSITION_SPECIALISATION$x$, $x$Membrane Composition and Specialisation$x$, $x$Protein-to-lipid ratio, organelle-specific composition and porins.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$PASSIVE_TRANSPORT_PERMEABILITY$x$, $x$Passive Transport and Permeability$x$, $x$Unaided permeability ranking, channels versus carriers, saturation and facilitated diffusion.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$, $x$Active Transport and Energy Coupling$x$, $x$Primary versus secondary sources, uphill accumulation and the order in which transport fails without ATP.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$OSMOSIS_TONICITY$x$, $x$Osmosis and Tonicity$x$, $x$Particle count, dissociation, permeant solutes and predicting cell volume change.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$CELL_JUNCTIONS$x$, $x$Cell Junctions$x$, $x$Tight junction seal and fence roles, gap junction connexons and anchoring junctions.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$ENDOCYTOSIS_EXOCYTOSIS$x$, $x$Endocytosis and Exocytosis$x$, $x$Bulk versus receptor-mediated uptake, cargo enrichment, membrane area balance and lumenal topology.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCOCALYX_CELL_RECOGNITION$x$, $x$Glycocalyx and Cell Recognition$x$, $x$Surface carbohydrate in recognition and protection.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$, $x$Glycolytic Pathway and Energy Yield$x$, $x$Net ATP and NADH, the site of NAD+ reduction, substrate-level phosphorylation and the bisphosphoglycerate detour.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$HEXOKINASE_GLUCOKINASE$x$, $x$Hexokinase and Glucokinase$x$, $x$Tissue distribution, saturation profiles and product inhibition distinguishing the isozymes.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCOLYTIC_REGULATION_PFK_1$x$, $x$Glycolytic Regulation at PFK-1$x$, $x$Citrate and ATP inhibition, AMP signalling and the fructose-2,6-bisphosphate override.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$FRUCTOSE_GALACTOSE_METABOLISM$x$, $x$Fructose and Galactose Metabolism$x$, $x$Entry points for dietary hexoses and the lesions that block them.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$, $x$Gluconeogenesis and its Bypass Reactions$x$, $x$The irreversible steps requiring bypass, the enzymes that perform them and where they occur.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCOGEN_SYNTHESIS$x$, $x$Glycogen Synthesis$x$, $x$Glycogenin priming, UDP-glucose recycling, branching and the driving force from pyrophosphate hydrolysis.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCOGEN_BREAKDOWN_REGULATION$x$, $x$Glycogen Breakdown and Regulation$x$, $x$Phosphorylase control, debranching, limit dextrin and the junction into glycolysis.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$PENTOSE_PHOSPHATE_PATHWAY$x$, $x$Pentose Phosphate Pathway$x$, $x$Oxidative and non-oxidative branches, NADPH production, carbon accounting and NADP+ control.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$NADPH_OXIDATIVE_DEFENCE$x$, $x$NADPH in Oxidative Defence$x$, $x$The glutathione peroxide chain and the haemolysis that follows its failure.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$LIPID_CLASSIFICATION_CRITERIA$x$, $x$Lipid Classification Criteria$x$, $x$Solubility as the defining criterion, and glycerol versus sphingosine backbones.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$, $x$Glycerophospholipid Structure and Naming$x$, $x$Phosphatidic acid as the parent, phosphodiester head-group linkage and head-group charge.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$, $x$Sphingolipids and Glycosphingolipids$x$, $x$Sphingosine-based lipids and the phosphate-free glycosidic heads.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$AMPHIPATHICITY_MICELLE_FORMATION$x$, $x$Amphipathicity and Micelle Formation$x$, $x$Head versus tail contributions, critical micelle concentration, micelle geometry and the entropic driving force.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$SAPONIFICATION_SOAPS$x$, $x$Saponification and Soaps$x$, $x$Base-mediated ester cleavage, its irreversibility, products, and hard-water failure.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$, $x$Cholesterol Structure and Membrane Role$x$, $x$The fused-ring hydrophobic architecture, bilayer orientation and bidirectional fluidity buffering.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TERPENES_ISOPRENE_UNITS$x$, $x$Terpenes and Isoprene Units$x$, $x$Isoprene counting and terpene classification.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$, $x$Fat-Soluble Vitamins and Carotenoids$x$, $x$Retinal as chromophore, retinoic acid in development, and conjugation length setting colour.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$EICOSANOID_SIGNALLING$x$, $x$Eicosanoid Signalling$x$, $x$Prostaglandin autocrine and paracrine action, and blockade revealing function.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$STEROID_STRUCTURE_DERIVATIVES$x$, $x$Steroid Structure and Derivatives$x$, $x$The fused four-ring nucleus, recognising it in an unknown, and ring-opened derivatives such as vitamin D3.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$FATTY_ACID_SATURATION_PACKING$x$, $x$Fatty Acid Saturation and Packing$x$, $x$How saturation and double-bond geometry govern packing and melting behaviour.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$, $x$Triacylglycerol Structure and Hydrolysis$x$, $x$The glycerol tri-ester backbone and its complete hydrolysis stoichiometry.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false),
  ($x$WAXES$x$, $x$Waxes$x$, $x$Long-chain ester structure, chemical inertness and the barrier role that follows.$x$, 'CONCEPT', 'ACTIVE_SEED', 1, false)
ON CONFLICT (slug) DO NOTHING;

-- Section, discipline and AAMC category for each.
INSERT INTO public.concept_sections (concept_id, section_code, is_primary) VALUES
  ((SELECT id FROM public.concepts WHERE slug=$x$LUMINAL_BRUSH_BORDER_DIGESTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_ACID_SECRETION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_HORMONAL_CONTROL$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PHASES_DIGESTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_EMPTYING_STORAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_MUCOSAL_PROTECTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PANCREATIC_EXOCRINE_SECRETION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BILIRUBIN_CONJUGATION_EXCRETION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_NUTRIENT_TRANSPORT$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_ABSORPTIVE_SURFACE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VITAMIN_ABSORPTION_DEFICIENCY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LARGE_INTESTINE_WATER_RECOVERY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_MOTILITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENTERIC_NERVOUS_SYSTEM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_WALL_LAYERS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENETIC_CODE_READING_FRAME$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_CLASSES_SECONDARY_STRUCTURE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_INITIATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_ELONGATION_TERMINATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_RNA_PROCESSING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_INTERFERENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_DOSAGE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DUPLEX_STABILITY_DENATURATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHROMATIN_STRUCTURE_PACKAGING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TELOMERES_TELOMERASE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REPLICATION_FORK_MECHANICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ORIGINS_REPLICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LAGGING_STRAND_SYNTHESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_REPAIR_PATHWAYS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESTRICTION_ENZYMES_CLONING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POLYMERASE_CHAIN_REACTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_SEQUENCING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTROPHORESIS_BLOTTING_PROBES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REVERSE_TRANSCRIPTION_CDNA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_KNOCKOUT_EXPERIMENTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLOMERULAR_FILTRATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_CLEARANCE_FILTERED_LOAD$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROXIMAL_TUBULE_REABSORPTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$URINE_CONCENTRATION_DILUTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISTAL_NEPHRON_POTASSIUM_HANDLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_AUTOREGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THERMOREGULATORY_MECHANISMS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CUTANEOUS_MECHANORECEPTORS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_LIPID_ASYMMETRY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_RAFTS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_COMPOSITION_SPECIALISATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PASSIVE_TRANSPORT_PERMEABILITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OSMOSIS_TONICITY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_JUNCTIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOCYTOSIS_EXOCYTOSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOCALYX_CELL_RECOGNITION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEXOKINASE_GLUCOKINASE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_REGULATION_PFK_1$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FRUCTOSE_GALACTOSE_METABOLISM$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_SYNTHESIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_BREAKDOWN_REGULATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PENTOSE_PHOSPHATE_PATHWAY$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NADPH_OXIDATIVE_DEFENCE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_CLASSIFICATION_CRITERIA$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMPHIPATHICITY_MICELLE_FORMATION$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SAPONIFICATION_SOAPS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TERPENES_ISOPRENE_UNITS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EICOSANOID_SIGNALLING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STEROID_STRUCTURE_DERIVATIVES$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_SATURATION_PACKING$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$), $x$BIO_BIOCHEM$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WAXES$x$), $x$BIO_BIOCHEM$x$, true)
ON CONFLICT (concept_id, section_code) DO NOTHING;

INSERT INTO public.concept_disciplines (concept_id, discipline_code, role) VALUES
  ((SELECT id FROM public.concepts WHERE slug=$x$LUMINAL_BRUSH_BORDER_DIGESTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_ACID_SECRETION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_HORMONAL_CONTROL$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$PHASES_DIGESTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_EMPTYING_STORAGE$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_MUCOSAL_PROTECTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$PANCREATIC_EXOCRINE_SECRETION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$BILIRUBIN_CONJUGATION_EXCRETION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_NUTRIENT_TRANSPORT$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_ABSORPTIVE_SURFACE$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$VITAMIN_ABSORPTION_DEFICIENCY$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$LARGE_INTESTINE_WATER_RECOVERY$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_MOTILITY$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENTERIC_NERVOUS_SYSTEM$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_WALL_LAYERS$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENETIC_CODE_READING_FRAME$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_CLASSES_SECONDARY_STRUCTURE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_INITIATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_ELONGATION_TERMINATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_RNA_PROCESSING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_INTERFERENCE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_DOSAGE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$DUPLEX_STABILITY_DENATURATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHROMATIN_STRUCTURE_PACKAGING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TELOMERES_TELOMERASE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$REPLICATION_FORK_MECHANICS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ORIGINS_REPLICATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$LAGGING_STRAND_SYNTHESIS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_REPAIR_PATHWAYS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESTRICTION_ENZYMES_CLONING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$POLYMERASE_CHAIN_REACTION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_SEQUENCING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTROPHORESIS_BLOTTING_PROBES$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$REVERSE_TRANSCRIPTION_CDNA$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_KNOCKOUT_EXPERIMENTS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLOMERULAR_FILTRATION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_CLEARANCE_FILTERED_LOAD$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROXIMAL_TUBULE_REABSORPTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$URINE_CONCENTRATION_DILUTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISTAL_NEPHRON_POTASSIUM_HANDLING$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_AUTOREGULATION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$THERMOREGULATORY_MECHANISMS$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$CUTANEOUS_MECHANORECEPTORS$x$), $x$BIOLOGY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_LIPID_ASYMMETRY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_RAFTS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_COMPOSITION_SPECIALISATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$PASSIVE_TRANSPORT_PERMEABILITY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$OSMOSIS_TONICITY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_JUNCTIONS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOCYTOSIS_EXOCYTOSIS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOCALYX_CELL_RECOGNITION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEXOKINASE_GLUCOKINASE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_REGULATION_PFK_1$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$FRUCTOSE_GALACTOSE_METABOLISM$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_SYNTHESIS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_BREAKDOWN_REGULATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$PENTOSE_PHOSPHATE_PATHWAY$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$NADPH_OXIDATIVE_DEFENCE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_CLASSIFICATION_CRITERIA$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMPHIPATHICITY_MICELLE_FORMATION$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$SAPONIFICATION_SOAPS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TERPENES_ISOPRENE_UNITS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$EICOSANOID_SIGNALLING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$STEROID_STRUCTURE_DERIVATIVES$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_SATURATION_PACKING$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY'),
  ((SELECT id FROM public.concepts WHERE slug=$x$WAXES$x$), $x$BIOCHEMISTRY$x$, 'PRIMARY')
ON CONFLICT (concept_id, discipline_code) DO NOTHING;

INSERT INTO public.concept_content_categories (concept_id, content_category, is_primary) VALUES
  ((SELECT id FROM public.concepts WHERE slug=$x$LUMINAL_BRUSH_BORDER_DIGESTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_ACID_SECRETION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_HORMONAL_CONTROL$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PHASES_DIGESTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_EMPTYING_STORAGE$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTRIC_MUCOSAL_PROTECTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PANCREATIC_EXOCRINE_SECRETION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$BILIRUBIN_CONJUGATION_EXCRETION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_NUTRIENT_TRANSPORT$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$INTESTINAL_ABSORPTIVE_SURFACE$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VITAMIN_ABSORPTION_DEFICIENCY$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LARGE_INTESTINE_WATER_RECOVERY$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_MOTILITY$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENTERIC_NERVOUS_SYSTEM$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GASTROINTESTINAL_WALL_LAYERS$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENETIC_CODE_READING_FRAME$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_CLASSES_SECONDARY_STRUCTURE$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_INITIATION$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSLATION_ELONGATION_TERMINATION$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EUKARYOTIC_RNA_PROCESSING$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RNA_INTERFERENCE$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_DOSAGE$x$), $x$Gene Expression$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DUPLEX_STABILITY_DENATURATION$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHROMATIN_STRUCTURE_PACKAGING$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TELOMERES_TELOMERASE$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REPLICATION_FORK_MECHANICS$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ORIGINS_REPLICATION$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LAGGING_STRAND_SYNTHESIS$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_REPAIR_PATHWAYS$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RESTRICTION_ENZYMES_CLONING$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$POLYMERASE_CHAIN_REACTION$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DNA_SEQUENCING$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ELECTROPHORESIS_BLOTTING_PROBES$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$REVERSE_TRANSCRIPTION_CDNA$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GENE_KNOCKOUT_EXPERIMENTS$x$), $x$Nucleic Acids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLOMERULAR_FILTRATION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_CLEARANCE_FILTERED_LOAD$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PROXIMAL_TUBULE_REABSORPTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$URINE_CONCENTRATION_DILUTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$DISTAL_NEPHRON_POTASSIUM_HANDLING$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$RENAL_AUTOREGULATION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$THERMOREGULATORY_MECHANISMS$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CUTANEOUS_MECHANORECEPTORS$x$), $x$Organ Systems$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_LIPID_ASYMMETRY$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_RAFTS$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$MEMBRANE_COMPOSITION_SPECIALISATION$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PASSIVE_TRANSPORT_PERMEABILITY$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$OSMOSIS_TONICITY$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CELL_JUNCTIONS$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$ENDOCYTOSIS_EXOCYTOSIS$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOCALYX_CELL_RECOGNITION$x$), $x$Plasma Membrane$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$HEXOKINASE_GLUCOKINASE$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOLYTIC_REGULATION_PFK_1$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FRUCTOSE_GALACTOSE_METABOLISM$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_SYNTHESIS$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCOGEN_BREAKDOWN_REGULATION$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$PENTOSE_PHOSPHATE_PATHWAY$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$NADPH_OXIDATIVE_DEFENCE$x$), $x$Glycolysis, Gluconeogenesis, and the Pentose Phosphate Pathway$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$LIPID_CLASSIFICATION_CRITERIA$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$AMPHIPATHICITY_MICELLE_FORMATION$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$SAPONIFICATION_SOAPS$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TERPENES_ISOPRENE_UNITS$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$EICOSANOID_SIGNALLING$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$STEROID_STRUCTURE_DERIVATIVES$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$FATTY_ACID_SATURATION_PACKING$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$), $x$Lipids$x$, true),
  ((SELECT id FROM public.concepts WHERE slug=$x$WAXES$x$), $x$Lipids$x$, true)
ON CONFLICT (concept_id, content_category) DO NOTHING;

-- Descriptor to concept, 417 rows. A fixed approved lookup applied
-- mechanically: no string similarity, no model, no inference at run time.
INSERT INTO public.question_concepts (question_id, concept_id, role, confidence, mapping_status, source)
SELECT q.id, c.id, 'PRIMARY', 1.00, 'DETERMINISTIC', 'DETERMINISTIC'
FROM public.questions q JOIN (VALUES
  ($x$Membrane anchored final digestion step$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Surface loss and membrane-stage digestion$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Two lumen consequences of disaccharidase loss$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Starch relay across the acidic compartment$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Physical breakup versus bond cleavage$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Intracellular versus luminal digestion$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Consequence of losing salivary secretion$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Consequence of being the first processing stop$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Quantitative distribution of digestive work$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Consequence of staggered first attack$x$, $x$LUMINAL_BRUSH_BORDER_DIGESTION$x$),
  ($x$Gastric proton pump energetics and blockade$x$, $x$GASTRIC_ACID_SECRETION$x$),
  ($x$Alkaline tide and secretory stoichiometry$x$, $x$GASTRIC_ACID_SECRETION$x$),
  ($x$A second parietal cell product and the site of B12 uptake$x$, $x$GASTRIC_ACID_SECRETION$x$),
  ($x$Attributing a juice change to one cell arm$x$, $x$GASTRIC_ACID_SECRETION$x$),
  ($x$Limits of gastric absorption$x$, $x$GASTRIC_ACID_SECRETION$x$),
  ($x$Acid negative feedback on gastrin release$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Feed forward gastrin release by peptides$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Gut somatostatin as secretory brake$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Duodenal acid restrains gastric acid output$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Dual organ targets of one signal$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Self-limiting feedback in secretin release$x$, $x$GASTROINTESTINAL_HORMONAL_CONTROL$x$),
  ($x$Cephalic phase anticipatory gastric secretion$x$, $x$PHASES_DIGESTION$x$),
  ($x$Anticipatory stomach signal versus fuel gauge$x$, $x$PHASES_DIGESTION$x$),
  ($x$Why the final digestive phase inhibits$x$, $x$PHASES_DIGESTION$x$),
  ($x$Fat load, CCK and stomach exit rate$x$, $x$GASTRIC_EMPTYING_STORAGE$x$),
  ($x$Feedback braking of gastric outflow$x$, $x$GASTRIC_EMPTYING_STORAGE$x$),
  ($x$Meal composition and emptying rate$x$, $x$GASTRIC_EMPTYING_STORAGE$x$),
  ($x$Gastric reservoir capacity and meal size$x$, $x$GASTRIC_EMPTYING_STORAGE$x$),
  ($x$Gastric mucosal barrier: acid load versus mucosal defense$x$, $x$GASTRIC_MUCOSAL_PROTECTION$x$),
  ($x$Gastric self-digestion and the maintained lining$x$, $x$GASTRIC_MUCOSAL_PROTECTION$x$),
  ($x$Epithelial renewal as a component of gastric protection$x$, $x$GASTRIC_MUCOSAL_PROTECTION$x$),
  ($x$Division of secretory labour within pancreas$x$, $x$PANCREATIC_EXOCRINE_SECRETION$x$),
  ($x$Anion exchange and blocked ductal secretion$x$, $x$PANCREATIC_EXOCRINE_SECRETION$x$),
  ($x$Timing of alkaline delivery to duodenum$x$, $x$PANCREATIC_EXOCRINE_SECRETION$x$),
  ($x$Separating enzyme loss from bile loss$x$, $x$PANCREATIC_EXOCRINE_SECRETION$x$),
  ($x$Hepatic modification enabling pigment excretion$x$, $x$BILIRUBIN_CONJUGATION_EXCRETION$x$),
  ($x$Germ-free gut and pigment colour loss$x$, $x$BILIRUBIN_CONJUGATION_EXCRETION$x$),
  ($x$One duct lesion, two downstream consequences$x$, $x$BILIRUBIN_CONJUGATION_EXCRETION$x$),
  ($x$Energy source behind uphill sugar uptake$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Ceiling on uncoupled monosaccharide uptake$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Why the exit step needs no coupling$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Shared carrier competition between similar nutrients$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Peptide uptake outpacing free amino acids$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Designing a test for carrier mediated uptake$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Sugar salt coupling in rehydration fluid$x$, $x$INTESTINAL_NUTRIENT_TRANSPORT$x$),
  ($x$Multiplicative tiers of absorptive surface$x$, $x$INTESTINAL_ABSORPTIVE_SURFACE$x$),
  ($x$Aqueous diffusion barrier at the absorptive surface$x$, $x$INTESTINAL_ABSORPTIVE_SURFACE$x$),
  ($x$Route dependent amplification of nutrient signalling$x$, $x$INTESTINAL_ABSORPTIVE_SURFACE$x$),
  ($x$Pancreatic step in the B12 relay$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Localising a vitamin absorption defect$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Two lesion routes to one deficiency$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Which fat soluble vitamin fails first$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Uptake failure behind a bleeding tendency$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Antibiotic loss of bacterial vitamin production$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Pattern separating obstruction from red cell loss$x$, $x$VITAMIN_ABSORPTION_DEFICIENCY$x$),
  ($x$Colonic mucosa fuelled by luminal fermentation$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Colonic residence time and stool consistency$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Colonic transport machinery versus nutrient uptake$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Daily fluid load and colonic reserve$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Driving force versus route for colonic water$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Redundant bulk uptake versus unique distal recovery$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$One way flow into the large intestine$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Fasting test separating two fluid losses$x$, $x$LARGE_INTESTINE_WATER_RECOVERY$x$),
  ($x$Segmentation versus propulsive intestinal motility$x$, $x$GASTROINTESTINAL_MOTILITY$x$),
  ($x$Oesophageal transport independent of gravity$x$, $x$GASTROINTESTINAL_MOTILITY$x$),
  ($x$Reflux at the oesophagogastric junction$x$, $x$GASTROINTESTINAL_MOTILITY$x$),
  ($x$Voluntary and reflex control of evacuation$x$, $x$GASTROINTESTINAL_MOTILITY$x$),
  ($x$Ruling out a purely muscular explanation$x$, $x$GASTROINTESTINAL_MOTILITY$x$),
  ($x$Complete reflex arcs within the gut wall$x$, $x$ENTERIC_NERVOUS_SYSTEM$x$),
  ($x$Testing intramural signalling in isolated gut$x$, $x$ENTERIC_NERVOUS_SYSTEM$x$),
  ($x$Positional inference for two wall networks$x$, $x$ENTERIC_NERVOUS_SYSTEM$x$),
  ($x$Wall layer depth and lost function$x$, $x$GASTROINTESTINAL_WALL_LAYERS$x$),
  ($x$Triplet code architecture and consequences$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Degeneracy preserving protein sequence$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Codon position substitution tolerance$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Codon regrouping after nucleotide removal$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Initiating AUG sets reading frame$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Deriving a peptide from an ORF$x$, $x$GENETIC_CODE_READING_FRAME$x$),
  ($x$Antiparallel anticodon sequence derivation$x$, $x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$),
  ($x$Minimum tRNA count under wobble$x$, $x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$),
  ($x$Wobble pairing and tRNA economy$x$, $x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$),
  ($x$Transfer RNA two ended adapter logic$x$, $x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$),
  ($x$Labeled tRNA itinerary through sites$x$, $x$TRANSFER_RNA_STRUCTURE_WOBBLE$x$),
  ($x$RNA class functional division of labor$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Identity of heterogeneous nuclear RNA$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Single strandedness enables intramolecular folding$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Hairpin prediction from sequence data$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Reactive sugar hydroxyl underlying catalysis$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Compensatory mutations localize function to shape$x$, $x$RNA_CLASSES_SECONDARY_STRUCTURE$x$),
  ($x$Ribosomal RNA scaffold and catalyst roles$x$, $x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$),
  ($x$stripped subunit ribozyme evidence$x$, $x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$),
  ($x$ribosomal subunit assembly order$x$, $x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$),
  ($x$subunit division of labor$x$, $x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$),
  ($x$reconstituting ribosomes from subunits$x$, $x$RIBOSOME_STRUCTURE_RIBOZYME_ACTIVITY$x$),
  ($x$Shine Dalgarno ribosome positioning$x$, $x$TRANSLATION_INITIATION$x$),
  ($x$cap directed small subunit recruitment$x$, $x$TRANSLATION_INITIATION$x$),
  ($x$diagnostic features of initiation systems$x$, $x$TRANSLATION_INITIATION$x$),
  ($x$elongation GTP cost counting$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$elongation snapshot residue count$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$peptidyl transfer intermediate state$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$Stop codon recognition without tRNA$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$release factor water addition$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$nascent transcript ribosome loading$x$, $x$TRANSLATION_ELONGATION_TERMINATION$x$),
  ($x$antiparallel template reading direction$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$template versus coding strand roles$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$polymerase intrinsic duplex melting$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$primer independent transcription initiation$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$transcript derivation from labeled duplex$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$polymerase assignment for messenger RNA$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$inverted promoter directionality consequence$x$, $x$TRANSCRIPTION_MECHANISM_STRAND_ROLES$x$),
  ($x$TATA spacing sets start site$x$, $x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$),
  ($x$TBP mediated polymerase recruitment$x$, $x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$),
  ($x$TFIID omission assembly failure$x$, $x$EUKARYOTIC_PROMOTERS_GENERAL_TRANSCRIPTION_FACTORS$x$),
  ($x$enhancer position and orientation independence$x$, $x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$),
  ($x$activator cognate element specificity$x$, $x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$),
  ($x$shared response element transferred to a new gene$x$, $x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$),
  ($x$repressor bound distant element identification$x$, $x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$),
  ($x$cAMP independent activator variant$x$, $x$ENHANCERS_TRANSCRIPTIONAL_ACTIVATORS$x$),
  ($x$operon coordinate pathway control$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$promoter operator functional distinction$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$constitutive operator mutant diagnosis$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$inducer double negative logic$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$lactose absent state prediction$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$uninducible repressor expression table$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$end product corepressor shutdown$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$novel operon control classification$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$polycistronic message multiple proteins$x$, $x$OPERONS_PROKARYOTIC_GENE_REGULATION$x$),
  ($x$cap shielding the nascent transcript$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$adenosine tail lifetime data$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$nuclear processing gates export$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$terminal marks identify processed message$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$snRNP intron excision machinery$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$spliceosome blockade intermediate prediction$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$combinatorial exon isoform expansion$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$shared peptide splicing evidence$x$, $x$EUKARYOTIC_RNA_PROCESSING$x$),
  ($x$siRNA knockdown readout$x$, $x$RNA_INTERFERENCE$x$),
  ($x$small RNA target fate$x$, $x$RNA_INTERFERENCE$x$),
  ($x$signal peptide deletion swap predictions$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$mature secreted protein shortening$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$blocked prenyl anchor consequence$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$covalent sugar maturation mark$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$combined sugar expression prediction$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$chaperone dilution refolding interpretation$x$, $x$POST_TRANSLATIONAL_PROCESSING_TARGETING$x$),
  ($x$copy number output scaling$x$, $x$GENE_DOSAGE$x$),
  ($x$Antiparallel architecture of the double helix$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Complementary strand derivation with correct polarity$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Donor acceptor complementarity in base pairing$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Phosphodiester backbone strand directionality$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Backbone polyanion charge behavior prediction$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Base composition strandedness inference$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Sugar composition distinguishing RNA from DNA$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Uracil as compositional marker of RNA$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Nucleoside to nucleotide phosphate conversion$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Huckel rule applied to base analogs$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Coenzymes as adenine nucleotide derivatives$x$, $x$NUCLEIC_ACID_STRUCTURE_POLARITY$x$),
  ($x$Base stacking contribution to duplex stability$x$, $x$DUPLEX_STABILITY_DENATURATION$x$),
  ($x$GC content melting temperature ranking$x$, $x$DUPLEX_STABILITY_DENATURATION$x$),
  ($x$Thermal denaturation and slow reannealing$x$, $x$DUPLEX_STABILITY_DENATURATION$x$),
  ($x$Probe hybridization requires denatured target$x$, $x$DUPLEX_STABILITY_DENATURATION$x$),
  ($x$Chromatin compaction hierarchy levels$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Histone octamer core particle composition$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Electrostatic basis of histone DNA binding$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Linker histone H1 structural role$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Heterochromatin packing and probe accessibility$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Chromosomal region classification from properties$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Centromeric DNA sequence composition$x$, $x$CHROMATIN_STRUCTURE_PACKAGING$x$),
  ($x$Telomere repetitive structure and end protection$x$, $x$TELOMERES_TELOMERASE$x$),
  ($x$telomerase internal RNA template$x$, $x$TELOMERES_TELOMERASE$x$),
  ($x$repeat tract intergenerational expansion$x$, $x$TELOMERES_TELOMERASE$x$),
  ($x$Helicase inactivation fork consequence$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$fork geometry strand identification$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$fork strand reannealing diagnosis$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$replication fork asymmetry logic$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$torsional strain ahead of fork$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$Supercoiling strain relief by nicking enzymes$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$sliding clamp processivity definition$x$, $x$REPLICATION_FORK_MECHANICS$x$),
  ($x$origin AT richness and duplex opening$x$, $x$ORIGINS_REPLICATION$x$),
  ($x$origin sequence specificity bubble pattern$x$, $x$ORIGINS_REPLICATION$x$),
  ($x$multiple origins replication time$x$, $x$ORIGINS_REPLICATION$x$),
  ($x$origin requirement for plasmid maintenance$x$, $x$ORIGINS_REPLICATION$x$),
  ($x$lagging strand junction sealing$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$lagging strand primer counting$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$primase primer initiation requirement$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$pulse label fragment origin$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$new strand excision rationale$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$ligase deficient extract interpretation$x$, $x$LAGGING_STRAND_SYNTHESIS$x$),
  ($x$polymerase reading direction chemistry$x$, $x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$),
  ($x$labeled template extension direction$x$, $x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$),
  ($x$deoxyribonucleoside triphosphate substrate selection$x$, $x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$),
  ($x$proofreading exonuclease directionality$x$, $x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$),
  ($x$layered replication fidelity rates$x$, $x$DNA_POLYMERASE_CHEMISTRY_FIDELITY$x$),
  ($x$deaminated cytosine repair steps$x$, $x$DNA_REPAIR_PATHWAYS$x$),
  ($x$methyl directed strand discrimination$x$, $x$DNA_REPAIR_PATHWAYS$x$),
  ($x$thymine damage discrimination rationale$x$, $x$DNA_REPAIR_PATHWAYS$x$),
  ($x$helix distortion pathway routing$x$, $x$DNA_REPAIR_PATHWAYS$x$),
  ($x$xeroderma repair synthesis assay$x$, $x$DNA_REPAIR_PATHWAYS$x$),
  ($x$palindromic recognition site identification$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$compatible overhang ligation logic$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$double digest restriction site mapping$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$empty vector self ligation diagnosis$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$methylation based self nonself discrimination$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$antibiotic plate selection logic$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$cDNA insert for bacterial expression$x$, $x$RESTRICTION_ENZYMES_CLONING$x$),
  ($x$PCR annealing step purpose$x$, $x$POLYMERASE_CHAIN_REACTION$x$),
  ($x$PCR cycle fold amplification arithmetic$x$, $x$POLYMERASE_CHAIN_REACTION$x$),
  ($x$in vitro versus in vivo amplification$x$, $x$POLYMERASE_CHAIN_REACTION$x$),
  ($x$same strand primer pair failure$x$, $x$POLYMERASE_CHAIN_REACTION$x$),
  ($x$dideoxy chain termination$x$, $x$DNA_SEQUENCING$x$),
  ($x$sequencing ladder read reconstruction$x$, $x$DNA_SEQUENCING$x$),
  ($x$agarose size only migration ordering$x$, $x$ELECTROPHORESIS_BLOTTING_PROBES$x$),
  ($x$blot target discrimination$x$, $x$ELECTROPHORESIS_BLOTTING_PROBES$x$),
  ($x$probe sequence specificity$x$, $x$ELECTROPHORESIS_BLOTTING_PROBES$x$),
  ($x$density label design discrimination$x$, $x$ELECTROPHORESIS_BLOTTING_PROBES$x$),
  ($x$first generation hybrid band interpretation$x$, $x$ELECTROPHORESIS_BLOTTING_PROBES$x$),
  ($x$cDNA first strand enzyme requirement$x$, $x$REVERSE_TRANSCRIPTION_CDNA$x$),
  ($x$knockout phenotype functional inference$x$, $x$GENE_KNOCKOUT_EXPERIMENTS$x$),
  ($x$Barrier conductance as a determinant of filtration rate$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Capsular pressure in glomerular filtration$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Fixed anionic charge and charge selectivity$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Size limit of the filtration barrier and routes into tubular fluid$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Layer specific failure of the serial barrier$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Downstream obstruction and filtration rate$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Protein binding and filtrate solute composition$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Bladder compliance and upstream drainage$x$, $x$GLOMERULAR_FILTRATION$x$),
  ($x$Clearance as a filtration rate marker$x$, $x$RENAL_CLEARANCE_FILTERED_LOAD$x$),
  ($x$Filtered load sets urinary appearance$x$, $x$RENAL_CLEARANCE_FILTERED_LOAD$x$),
  ($x$Distinguishing tubular secretion from tubular reabsorption for a test solute$x$, $x$RENAL_CLEARANCE_FILTERED_LOAD$x$),
  ($x$Proximal secretion adds to what is filtered$x$, $x$RENAL_CLEARANCE_FILTERED_LOAD$x$),
  ($x$Basolateral pump failure in proximal reabsorption$x$, $x$PROXIMAL_TUBULE_REABSORPTION$x$),
  ($x$Composition of fluid leaving the proximal tubule$x$, $x$PROXIMAL_TUBULE_REABSORPTION$x$),
  ($x$Isosmotic bulk reabsorption in proximal tubule$x$, $x$PROXIMAL_TUBULE_REABSORPTION$x$),
  ($x$Saturable carrier ceiling and solute spillover$x$, $x$PROXIMAL_TUBULE_REABSORPTION$x$),
  ($x$Renal oxygen supply versus transport work$x$, $x$PROXIMAL_TUBULE_REABSORPTION$x$),
  ($x$Ascending limb dilution sets urine floor$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Ascending limb transport block and urine volume$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Descending limb volume loss at constant solute$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Loop depth versus maximal urine concentration$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Loop length multiplies a single level difference$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Why the medullary gradient is regional$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Urea contribution to the medullary gradient$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Medullary blood flow rate and gradient washout$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Consequence of nephron segment order$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Reading an osmolarity profile along the nephron$x$, $x$LOOP_HENLE_COUNTERCURRENT_MULTIPLICATION$x$),
  ($x$Ceiling on maximal urine concentration$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Two requirements for concentrating urine$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Obligatory urine volume caps water conservation$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Obligatory urine volume from solute load$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Osmotic diuresis from unreabsorbed solute$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Water load and collecting duct permeability$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Water deprivation then exogenous hormone challenge$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Why regulated water exit comes last$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Tonicity of fluid lost predicts urine$x$, $x$URINE_CONCENTRATION_DILUTION$x$),
  ($x$Distal sodium delivery and potassium secretion$x$, $x$DISTAL_NEPHRON_POTASSIUM_HANDLING$x$),
  ($x$Isolating the arteriolar myogenic stretch response$x$, $x$RENAL_AUTOREGULATION$x$),
  ($x$Renal autoregulation across a pressure range$x$, $x$RENAL_AUTOREGULATION$x$),
  ($x$Macula densa position and luminal salt sensing$x$, $x$RENAL_AUTOREGULATION$x$),
  ($x$Designing a test for a local tubular sensor$x$, $x$RENAL_AUTOREGULATION$x$),
  ($x$Volume defence overriding osmolarity defence$x$, $x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$),
  ($x$Nitrogen waste toxicity versus water cost$x$, $x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$),
  ($x$Cumulative sweat sodium loss and the limits of tubular conservation$x$, $x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$),
  ($x$Sweat tonicity and rehydration osmolarity swing$x$, $x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$),
  ($x$Dialysate composition and gradient design$x$, $x$VOLUME_VERSUS_OSMOLARITY_DEFENCE$x$),
  ($x$Avascular epidermis fed by diffusion$x$, $x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$),
  ($x$Cornification as intracellular chemical transformation$x$, $x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$),
  ($x$Stratum corneum as the water barrier$x$, $x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$),
  ($x$Supranuclear pigment cap geometry$x$, $x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$),
  ($x$Burn area scaling of fluid loss$x$, $x$SKIN_STRUCTURE_BARRIER_FUNCTION$x$),
  ($x$Direction of heat exchange when the surroundings are hotter than the skin$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Hypodermal fat depth and heat loss rate$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Piloerection and trapped still air$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Fever as an elevated set point$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Separating set point shift from heat overload$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Distinguishing the two sweat gland populations by their deficits$x$, $x$THERMOREGULATORY_MECHANISMS$x$),
  ($x$Lamellar capsule as temporal filter$x$, $x$CUTANEOUS_MECHANORECEPTORS$x$),
  ($x$Receptor depth and spatial resolution$x$, $x$CUTANEOUS_MECHANORECEPTORS$x$),
  ($x$Deficit pattern localizing receptor loss$x$, $x$CUTANEOUS_MECHANORECEPTORS$x$),
  ($x$Fluid mosaic model dynamic predictions$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Cell fusion protein intermixing experiment$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Lateral versus transverse lipid movement$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Protein versus lipid lateral mobility$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Bilayer phase transition diffusion data$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Self-sealing bilayer edge energetics$x$, $x$FLUID_MOSAIC_MODEL_MEMBRANE_DYNAMICS$x$),
  ($x$Flippase loss and asymmetry decay$x$, $x$MEMBRANE_LIPID_ASYMMETRY$x$),
  ($x$Glycan sidedness accessibility evidence$x$, $x$MEMBRANE_LIPID_ASYMMETRY$x$),
  ($x$Lipid raft physical organization$x$, $x$LIPID_RAFTS$x$),
  ($x$Raft co-clustering of signaling partners$x$, $x$LIPID_RAFTS$x$),
  ($x$Extraction condition anchoring forces$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Extraction data protein classification$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Lipid anchored protein classification logic$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Hydropathy plot topology prediction$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Alternating topogenic sequence membrane passes$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Stop-transfer sequence terminus orientation$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Protease protection sidedness assay$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$GPI leaflet and phospholipase release$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Bilayer span requirement for channels$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$receptor channel versus enzyme classification$x$, $x$MEMBRANE_PROTEIN_CLASSIFICATION_TOPOLOGY$x$),
  ($x$Protein-to-lipid ratio versus membrane function$x$, $x$MEMBRANE_COMPOSITION_SPECIALISATION$x$),
  ($x$Inner mitochondrial membrane compositional contrast$x$, $x$MEMBRANE_COMPOSITION_SPECIALISATION$x$),
  ($x$Porin basis of outer membrane leakiness$x$, $x$MEMBRANE_COMPOSITION_SPECIALISATION$x$),
  ($x$unaided bilayer solute permeability ranking$x$, $x$PASSIVE_TRANSPORT_PERMEABILITY$x$),
  ($x$channel versus carrier classification$x$, $x$PASSIVE_TRANSPORT_PERMEABILITY$x$),
  ($x$carrier saturation rate plateau$x$, $x$PASSIVE_TRANSPORT_PERMEABILITY$x$),
  ($x$GLUT1 down gradient passive uptake$x$, $x$PASSIVE_TRANSPORT_PERMEABILITY$x$),
  ($x$aquaporin water flux inference$x$, $x$PASSIVE_TRANSPORT_PERMEABILITY$x$),
  ($x$uphill accumulation energy requirement$x$, $x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$),
  ($x$primary versus secondary energy source$x$, $x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$),
  ($x$ATP depletion transporter failure order$x$, $x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$),
  ($x$liposome transporter direction terminology$x$, $x$ACTIVE_TRANSPORT_ENERGY_COUPLING$x$),
  ($x$particle count osmosis direction$x$, $x$OSMOSIS_TONICITY$x$),
  ($x$dissociation osmotic pressure comparison$x$, $x$OSMOSIS_TONICITY$x$),
  ($x$permeant solute tonicity distinction$x$, $x$OSMOSIS_TONICITY$x$),
  ($x$red cell dilute saline outcome$x$, $x$OSMOSIS_TONICITY$x$),
  ($x$tight junction paracellular seal$x$, $x$CELL_JUNCTIONS$x$),
  ($x$tight junction fence function$x$, $x$CELL_JUNCTIONS$x$),
  ($x$connexon hemichannel assembly$x$, $x$CELL_JUNCTIONS$x$),
  ($x$hemidesmosome anchoring target contrast$x$, $x$CELL_JUNCTIONS$x$),
  ($x$nonselective fluid uptake classification$x$, $x$ENDOCYTOSIS_EXOCYTOSIS$x$),
  ($x$receptor clustering cargo enrichment$x$, $x$ENDOCYTOSIS_EXOCYTOSIS$x$),
  ($x$secretory membrane area balance$x$, $x$ENDOCYTOSIS_EXOCYTOSIS$x$),
  ($x$lumenal tag exocytosis fate$x$, $x$ENDOCYTOSIS_EXOCYTOSIS$x$),
  ($x$Glycocalyx surface recognition role$x$, $x$GLYCOCALYX_CELL_RECOGNITION$x$),
  ($x$Net glycolytic ATP and NADH yield$x$, $x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$),
  ($x$Site of NAD+ reduction in glycolysis$x$, $x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$),
  ($x$Phosphoglycerate kinase ATP synthesis mechanism$x$, $x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$),
  ($x$ATP cost of the bisphosphoglycerate detour$x$, $x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$),
  ($x$Glycolytic stall without NAD regeneration$x$, $x$GLYCOLYTIC_PATHWAY_ENERGY_YIELD$x$),
  ($x$Hexokinase glucokinase saturation profiles$x$, $x$HEXOKINASE_GLUCOKINASE$x$),
  ($x$Glucokinase tissue restriction consequences$x$, $x$HEXOKINASE_GLUCOKINASE$x$),
  ($x$Glucose 6-phosphate product inhibition contrast$x$, $x$HEXOKINASE_GLUCOKINASE$x$),
  ($x$Citrate feedback inhibition of PFK-1$x$, $x$GLYCOLYTIC_REGULATION_PFK_1$x$),
  ($x$Potent allosteric override of ATP inhibition$x$, $x$GLYCOLYTIC_REGULATION_PFK_1$x$),
  ($x$Bifunctional PFK-2 kinase phosphatase domains$x$, $x$GLYCOLYTIC_REGULATION_PFK_1$x$),
  ($x$AMP as amplified low energy signal$x$, $x$GLYCOLYTIC_REGULATION_PFK_1$x$),
  ($x$Feed-forward activation of pyruvate kinase$x$, $x$GLYCOLYTIC_REGULATION_PFK_1$x$),
  ($x$Aldolase B cleavage of fructose 1-phosphate$x$, $x$FRUCTOSE_GALACTOSE_METABOLISM$x$),
  ($x$Fructose bypass of the PFK-1 checkpoint$x$, $x$FRUCTOSE_GALACTOSE_METABOLISM$x$),
  ($x$GLUT5 mediated fructose uptake$x$, $x$FRUCTOSE_GALACTOSE_METABOLISM$x$),
  ($x$First enzymatic step of galactose catabolism$x$, $x$FRUCTOSE_GALACTOSE_METABOLISM$x$),
  ($x$Tracer localization of classic galactosemia$x$, $x$FRUCTOSE_GALACTOSE_METABOLISM$x$),
  ($x$Irreversible glycolytic steps requiring bypass$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$bypass enzyme to step mapping$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$gluconeogenesis compartment span and organs$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$pyruvate carboxylase reaction package$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$acetyl CoA activation of pyruvate carboxylase$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$oxaloacetate malate exit route$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$convergent final glucose release step$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$glucose-6-phosphatase endoplasmic reticulum compartment$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$reciprocal effector control at FBPase-1$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$Pyruvate fate enzyme and compartment map$x$, $x$GLUCONEOGENESIS_BYPASS_REACTIONS$x$),
  ($x$glycogen synthase primer dependence$x$, $x$GLYCOGEN_SYNTHESIS$x$),
  ($x$glycogenin tyrosine autoglucosylation$x$, $x$GLYCOGEN_SYNTHESIS$x$),
  ($x$Catalytic recycling of UDP-glucose$x$, $x$GLYCOGEN_SYNTHESIS$x$),
  ($x$branching enzyme block transfer$x$, $x$GLYCOGEN_SYNTHESIS$x$),
  ($x$pyrophosphate hydrolysis driving force$x$, $x$GLYCOGEN_SYNTHESIS$x$),
  ($x$phosphorylase stall producing limit dextrin$x$, $x$GLYCOGEN_BREAKDOWN_REGULATION$x$),
  ($x$debranching dual activity product count$x$, $x$GLYCOGEN_BREAKDOWN_REGULATION$x$),
  ($x$AMP calcium muscle phosphorylase activation$x$, $x$GLYCOGEN_BREAKDOWN_REGULATION$x$),
  ($x$phosphoglucomutase glycogen glycolysis junction$x$, $x$GLYCOGEN_BREAKDOWN_REGULATION$x$),
  ($x$Oxidative phase carbon accounting$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$NADP ratio control of committed step$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$second oxidative NADPH step probed by substrate entry$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$non-oxidative branch reverse flux$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$transketolase and transaldolase carbon transfers$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$pentose phosphate pathway product ledger$x$, $x$PENTOSE_PHOSPHATE_PATHWAY$x$),
  ($x$NADPH glutathione peroxide defense chain$x$, $x$NADPH_OXIDATIVE_DEFENCE$x$),
  ($x$oxidant stress hemolysis enzyme lesion$x$, $x$NADPH_OXIDATIVE_DEFENCE$x$),
  ($x$Solubility as the lipid class criterion$x$, $x$LIPID_CLASSIFICATION_CRITERIA$x$),
  ($x$Glycerol versus sphingosine backbone classification$x$, $x$LIPID_CLASSIFICATION_CRITERIA$x$),
  ($x$Fat solubility drives tissue accumulation$x$, $x$LIPID_CLASSIFICATION_CRITERIA$x$),
  ($x$Water affinity ranking across lipid classes$x$, $x$LIPID_CLASSIFICATION_CRITERIA$x$),
  ($x$Phosphatidic acid as parent structure in glycerophospholipid naming$x$, $x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$),
  ($x$Phosphodiester linkage to head group$x$, $x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$),
  ($x$Head group charge and electrophoretic migration$x$, $x$GLYCEROPHOSPHOLIPID_STRUCTURE_NAMING$x$),
  ($x$Phosphate-free glycosidic heads of glycosphingolipids$x$, $x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$),
  ($x$Sphingomyelin as a glycerol-free phospholipid$x$, $x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$),
  ($x$Sphingomyelin structure in myelin insulation$x$, $x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$),
  ($x$Two-attribute sphingolipid classification from data$x$, $x$SPHINGOLIPIDS_GLYCOSPHINGOLIPIDS$x$),
  ($x$Amphipathic structure and micelle dispersal$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Head versus tail solubility contributions$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Critical micelle concentration monomer plateau$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Soap micelle self-assembly geometry$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Entropic driving force of micellization$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Grease sequestration cleaning mechanism evidence$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Tail number dictating micelle versus bilayer$x$, $x$AMPHIPATHICITY_MICELLE_FORMATION$x$),
  ($x$Irreversibility of base-mediated ester cleavage$x$, $x$SAPONIFICATION_SOAPS$x$),
  ($x$Saponification assay for lipid linkage type$x$, $x$SAPONIFICATION_SOAPS$x$),
  ($x$Saponification product identification$x$, $x$SAPONIFICATION_SOAPS$x$),
  ($x$Hard water soap failure experiment$x$, $x$SAPONIFICATION_SOAPS$x$),
  ($x$Doubled carboxylate calcium chelation logic$x$, $x$SAPONIFICATION_SOAPS$x$),
  ($x$Cholesterol's hydrophobic architecture$x$, $x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$),
  ($x$Cholesterol orientation in the bilayer$x$, $x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$),
  ($x$Cholesterol bidirectional fluidity buffering$x$, $x$CHOLESTEROL_STRUCTURE_MEMBRANE_ROLE$x$),
  ($x$Isoprene unit counting in terpenes$x$, $x$TERPENES_ISOPRENE_UNITS$x$),
  ($x$Squalene as hexaisoprenoid steroid precursor$x$, $x$TERPENES_ISOPRENE_UNITS$x$),
  ($x$Terpene unit counting convention$x$, $x$TERPENES_ISOPRENE_UNITS$x$),
  ($x$Terpene versus steroid structural discrimination$x$, $x$TERPENES_ISOPRENE_UNITS$x$),
  ($x$Retinal aldehyde as visual chromophore$x$, $x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$),
  ($x$Retinoic acid supports epithelial development$x$, $x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$),
  ($x$Conjugation length sets carotene color$x$, $x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$),
  ($x$Tocopherol chain-breaking site in membranes$x$, $x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$),
  ($x$Vitamin K glutamate carboxylation chemistry$x$, $x$FAT_SOLUBLE_VITAMINS_CAROTENOIDS$x$),
  ($x$Prostaglandin autocrine paracrine locality$x$, $x$EICOSANOID_SIGNALLING$x$),
  ($x$Enzyme blockade reveals mediator function$x$, $x$EICOSANOID_SIGNALLING$x$),
  ($x$Steroid nucleus recognition in novel isolates$x$, $x$STEROID_STRUCTURE_DERIVATIVES$x$),
  ($x$Vitamin D3 as a ring-opened steroid derivative$x$, $x$STEROID_STRUCTURE_DERIVATIVES$x$),
  ($x$Trans double bond chain packing$x$, $x$FATTY_ACID_SATURATION_PACKING$x$),
  ($x$Triacylglycerol backbone structure$x$, $x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$),
  ($x$Triacylglycerol complete hydrolysis stoichiometry$x$, $x$TRIACYLGLYCEROL_STRUCTURE_HYDROLYSIS$x$),
  ($x$Wax barrier against water loss$x$, $x$WAXES$x$),
  ($x$Wax ester structure and inertness$x$, $x$WAXES$x$),
  ($x$Wax versus triacylglycerol backbone identity$x$, $x$WAXES$x$),
  ($x$Wax classification from hydrolysis products$x$, $x$WAXES$x$),
  ($x$Storage capacity from bile concentration$x$, $x$LIPID_DIGESTION_BILE$x$),
  ($x$Pump failure versus open outlet in bile delivery$x$, $x$LIPID_DIGESTION_BILE$x$),
  ($x$Positive control in a bile diversion study$x$, $x$LIPID_DIGESTION_BILE$x$),
  ($x$multi-ion permeability equation selection$x$, $x$RESTING_MEMBRANE_POTENTIAL$x$),
  ($x$vesicle anion equilibrium potential sign$x$, $x$ION_CHANNELS$x$)
) AS m(descriptor, slug) ON m.descriptor = q.subtopic
JOIN public.concepts c ON c.slug = m.slug
WHERE c.status <> 'DEPRECATED'
ON CONFLICT (question_id, concept_id) DO NOTHING;
-- ────────────────────────────────────────────────────────────
-- Verification
-- ────────────────────────────────────────────────────────────
SELECT
  (SELECT count(*) FROM public.concepts)                       AS concepts,          -- 576
  (SELECT count(*) FROM public.question_concepts)              AS mappings,          -- 2659
  (SELECT count(*) FROM public.flashcard_concepts)             AS flashcard_maps,    -- 0
  (SELECT count(*) FROM public.concept_aliases)                AS aliases,           -- 1
  (SELECT count(*) FROM public.questions)                      AS questions,         -- 2681
  (SELECT count(*) FROM public.flashcards)                     AS flashcards,        -- 4117
  (SELECT count(*) FROM public.question_distractor_metadata)   AS distractors;       -- 8043

-- The rename kept the ID and filed the old name. Expect one row, LEGACY_NAME.
SELECT c.slug, c.canonical_name, a.alias, a.alias_type
FROM public.concepts c JOIN public.concept_aliases a ON a.concept_id = c.id
WHERE c.canonical_name = 'Respiratory Thermoregulation';

-- Coverage. Expect 2659 mapped, 22 unmapped.
SELECT count(*) FILTER (WHERE qc.question_id IS NOT NULL) AS mapped,
       count(*) FILTER (WHERE qc.question_id IS NULL)     AS unmapped
FROM public.questions q
LEFT JOIN public.question_concepts qc ON qc.question_id = q.id;

-- Section compatibility by membership. Expect zero rows.
SELECT 'section mismatch' AS problem, count(*) AS n
FROM public.question_concepts qc
JOIN public.questions q ON q.id = qc.question_id
JOIN public.legacy_taxonomy_map m
  ON m.source_system='questions' AND m.source_field='section' AND m.source_value=q.section
WHERE NOT EXISTS (SELECT 1 FROM public.concept_sections cs
                  WHERE cs.concept_id=qc.concept_id AND cs.section_code=m.section_code);

-- Exactly one PRIMARY per question. Expect zero rows.
SELECT 'duplicate primary' AS problem, question_id, count(*)
FROM public.question_concepts WHERE role='PRIMARY'
GROUP BY question_id HAVING count(*) > 1;

-- Largest concepts, watching for a catch-all.
SELECT c.canonical_name, count(*) AS questions
FROM public.question_concepts qc JOIN public.concepts c ON c.id=qc.concept_id
GROUP BY c.canonical_name ORDER BY count(*) DESC LIMIT 6;

-- ── ROLLBACK ────────────────────────────────────────────────────────────
-- DELETE FROM public.question_concepts WHERE source='DETERMINISTIC' AND mapping_status='DETERMINISTIC';
-- DELETE FROM public.concepts WHERE status='ACTIVE_SEED' AND created_at > now() - interval '1 hour';
-- UPDATE public.concepts SET canonical_name='Thermoregulation' WHERE canonical_name='Respiratory Thermoregulation';
-- DELETE FROM public.concept_aliases WHERE alias='Thermoregulation';
